### ISSUE TITLE
Add `select all` quick action for thumbnails

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#1000]
**Is your feature request related to a problem? Please describe.**
مرحبا، شكرا لك على كل ما تبذله في سبيل تطوير معرض صور متكامل.
عند محاولة تحديد كل الصور في ألبوم معين او في سلة المحذوفات، نقوم بذلك عبر عدة خطوات :
1- الضغط المطول على صورة.
2- الذهاب للخيارات في الأعلى.
3- ضغط على خيار تحديد الكل.

**Describe the solution you'd like**
اذا كان لك الوقت الكافي، أرجو منك إضافة خيار تحديد الكل في قائمة الإجراءات السريعة للصور المصغرة.

**Additional context**
![1](https://github.com/deckerst/aves/assets/153401125/d795f122-85b6-4520-9802-e014085a9708)
![2](https://github.com/deckerst/aves/assets/153401125/08163850-843f-42f0-a363-e16e3d3174ac)

**Comment by deckerst** [comment]
Good suggestion.
By the way: it's the 1000th issue!

**Comment by mohamedzerougdz** [comment]
أظن أني محظوظ اليوم هههه
