### ISSUE TITLE
Error entering the application when image browsing collapses

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#1001]
**Describe the bug**
خطأ في التطبيق وفشل تام عند تصغير التطبيق الى قائمة التطبيقات الاخيرة، ثم الدخول الى اي صورة من خلال مستكشف الملفات، بعد العودة للتطبيق مرة اخرى نلاحظ الانهيار التام في عرض الصور.

**To Reproduce**
1. الدخول في تطبيق Aves، ثم تصغيره الى قائمة التطبيقات الاخيرة.
2. الذهاب الى مستكشف الملفات، والدخول الى اي صورة بواسطة تطبيق Aves.
3. تصغيرة التطبيق الى قائمة التطبيقات الأخيرة.
4. النقر على ايقونة تطبيق Aves.
5. ملاحظة فشل التطبيق في استعراض كل الصور باستثناء الصور الجديدة.

**Expected behavior**
دخول التطبيق بسلاسة واستعراض كل الصور بدون خلل.

**System information and logs:**

Package: deckers.thibault.aves
Installer: com.google.android.packageinstaller
Aves version: 1.11.0-play, build 119
Flutter: stable 3.19.6
Android version: 14, API 34
Android build: UKQ1.230917.001 release-keys
Device: Xiaomi 23021RAAEG
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: ar_EG
Storage volumes: /storage/emulated/0/, /storage/809D-1606/
Storage grants: 
Error reporting: true

**Screenshots:**
https://www.mediafire.com/file/5rgoqkvy231i5dq/Screenrecorder-2024-05-02-10-14-04-939.mp4/file

**Additional context**
[aves-logs-20240502_103724.txt](https://github.com/deckerst/aves/files/15186391/aves-logs-20240502_103724.txt)

**Comment by deckerst** [comment]
Do you know if the issue could happen with previous versions of the app?

**Comment by mohamedzerougdz** [comment]
الاصدارات التي تحتوي على الخطأ هي:
الإصدار 1.11.0
الإصدار 1.10.9

**Comment by deckerst** [comment]
Do you still get the issue with [this test build](https://drive.google.com/file/d/1zn5HZnCU5P4JtZpj0Jt6A5_Vkk3zrqYZ/view?usp=sharing)? Note that it will install as "Aves [Profile]".

**Comment by mohamedzerougdz** [comment]
للأسف لا زال الخطا موجود.

Package: deckers.thibault.aves.profile
Installer: com.google.android.packageinstaller
Aves version: 1.11.1-play, build 120
Flutter: unknown unknown
Android version: 14, API 34
Android build: UKQ1.230917.001 release-keys
Device: Xiaomi 23021RAAEG
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: ar_EG
Storage volumes: /storage/emulated/0/, /storage/809D-1606/
Storage grants: 
Error reporting: true

[aves-logs-20240609_071327.txt](https://github.com/user-attachments/files/15750768/aves-logs-20240609_071327.txt)

**Comment by deckerst** [comment]
@mohamedzerougdz I expect the latest release v1.11.17 to fix issues like the one you've reported.

Could you please try it when it's available (it's being deployed now to the Play Store, but it should be available tomorrow or the next day) and let me know how it goes?

**Comment by deckerst** [comment]
Good to know it's finally solved.

As for the translations, I believe I gave you `power user` rights on Arabic on Weblate, so you can apply your own suggestions.

**Comment by mohamedzerougdz** [comment]
كنت اعتقد ذلك ايضا، لكن يبدو اني لست كذلك.

**Comment by deckerst** [comment]
Indeed, you were no longer in the list of users, so I've resent an invitation. Maybe you previously left the project by mistake. Anyway, now you should be able to rejoin and edit as you wish.

**Comment by mohamedzerougdz** [comment]
شكرا لك تم قبول الدعوة
