### ISSUE TITLE
Feature Request; Ability to export Motion Photos (as Video)

### ISSUE THREAD

**Issue by heuwerk** [deckerst/aves#1004]
**Is your feature request related to a problem? Please describe.**
Hello dear Aves team, first of all many thanks for this great app, so far I have hardly missed anything. However, I have noticed one small thing.
I think it's great that I can view the photos taken by my Pixel 8 including a moving photo.
However, I would also like to export this moving photo to share it with my contacts and I haven't found a way to do this yet.

**Describe the solution you'd like**
I would like to be able to export the moving images as a video (or similar format) to share them with my contacts.

**Describe alternatives you've considered**
Maybe the function I wanted already exists, I just couldn't find it.
In this case, a simple instruction would help me a lot.

**Additional context**
None that would be useful.

**Comment by deckerst** [comment]
A couple of ways already exist:
1) from the viewer page, you can long press on the `Share` quick action, and you'll see `Share image only`, `Share video only`.
<img width="250" src="https://github.com/deckerst/aves/assets/13898333/1082be80-1622-4f81-b921-03fa8b9a55f8" />

2) from the `Info` page, select `Open video` in the top right menu, then you can share it.
<img width="250" src="https://github.com/deckerst/aves/assets/13898333/27d22ec9-37a1-4847-9ad8-f872debd18ce" />


These special menus and menu items are only activated when viewing a motion photo. For now it's only possible to use them when viewing a single item, not in bulk.

Related, for motion photo processing in bulk:
- #883
