### ISSUE TITLE
Browser does not display JFIF images

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#1005]
**Describe the bug**
عند معاينة صورة من مستكشف الملفات بواسطة تطبيق Aves يقوم التطبيق باستعراضها بشكل جيد، لكن عند الدخوg الى تطبيق Aves نفسه لا أجد أي صور في أي البوم بتنسيق JFIF.
**To Reproduce**
1. فتح تطبيق Aves.
2. فشل العثور على الصور المصغرة لأي صورة بتنسيق JFIF في قائمة الصور او الالبومات.

**Expected behavior**
1. فتح تطبيق Aves.
2. العثور على الصور المصغرة لأي صورة بتنسيق JFIF في قائمة الصور او الالبومات.

**Screenshots**
https://www.mediafire.com/file/efdkzmfkbvl26hw/Screenrecorder-2024-05-02-22-47-37-519.mp4/file

**Comment by deckerst** [comment]
I don't know what you mean by JFIF images. Do you have a sample image?

**Comment by mohamedzerougdz** [comment]
https://www.mediafire.com/file/3bwqz3te4qzf665/JFIF.zip/file

**Comment by deckerst** [comment]
It seems Android simply does not recognize them as media files (at least that's the case on my device running Android 12). And even if it did, Aves would rely on the system codecs to decode them. I do not intend to provide additional codecs for that format.
