### ISSUE TITLE
Option to not reload app while relaunching from launcher

### ISSUE THREAD

**Issue by Aswin8** [deckerst/aves#1008]
**Is your feature request related to a problem? Please describe.**
The recent changes done on how Aves completely restarts everytime while relaunching app from launcher is affecting the productivity and kind of makes high RAM space in modern phones less meaningful. Even before this change unlike all other gallery apps, Aves take quite bit time for album cataloguing and slow animations to complete loading albums on every launch. Aves is simply perfect except the way it often feels the app doesn't stick to RAM. Especially while working on multimedia editing, i tend to have Aves in home screen and often open Aves for reference and stuff. 

**Describe the solution you'd like**
A switch to turn off the recent app relaunching mechanism or revert the change if possible.
(Additional humble suggestion - See if you can speed up the animation speed of Album cataloguing. There is a significant seconds the app shows white boxes before the album page gets loaded. But other gallery apps load albums faster and sticks to memory for long time  - Tested devices: Pixel 7, OnePlus 7T )

**Describe alternatives you've considered**
NA

**Additional context**
This is just a request and even without it Aves would be the top gallery app out here. And the new app icon is beautiful too, thanks.

**Comment by deckerst** [comment]
Related:
- #953
- #970

#953 was a reasonable request, and the change allows now to either 1) come back to the app as it was by switching back to it via the most recent apps, or 2) showing the app at the user home page when launched from the launcher. That was implemented in v1.10.8.

However there was a bug (#970) that made it always reinitializes the DB when accessed from the launcher. That was fixed in v1.10.9 so now it would show the home but not reload everything (if the app wasn't killed by the system in the meantime).

Which version do you use?

> And the new app icon is beautiful too, thanks.

Thanks! Glad you like it.

**Comment by Aswin8** [comment]
> Related:
> 
> * [Leaving and reopening the app brings you to previously state/navigated place instead of configured home #953](https://github.com/deckerst/aves/issues/953)
> * [Collection reinitializes when app reopens from launcher #970](https://github.com/deckerst/aves/issues/970)
> 
> #953 was a reasonable request, and the change allows now to either 1) come back to the app as it was by switching back to it via the most recent apps, or 2) showing the app at the user home page when launched from the launcher. That was implemented in v1.10.8.
> 
> However there was a bug (#970) that made it always reinitializes the DB when accessed from the launcher. That was fixed in v1.10.9 so now it would show the home but not reload everything (if the app wasn't killed by the system in the meantime).
> 
> Which version do you use?
> 
> > And the new app icon is beautiful too, thanks.
> 
> Thanks! Glad you like it.

a) Starting with the second part of your reply - I am using v1.11.1 now, but i was facing the bug #970 since i started using Aves almost a year back. I was facing the issue even while raising #805 request 6 months back. But i was reluctant to raise the issue as I didn't want to cry about a free app so much and apart from this Aves is far better than other galleries. Even with the latest version the issue is kind of there but also increasingly visible because the app reopen from Home page every time its opened from Homescreen/Launcher.
![photo_2024-05-05_18-33-35](https://github.com/deckerst/aves/assets/11328626/60cd0abf-4fd5-45aa-8ad5-c294fbef4aa3)

I am assuming the issue is mixed result of #970 issue, slow animations in album page, the bright boxes behind albums. (and additionally #953 implementation made it more visible)

b) Yes, i read through #953 again, it's a reasonable one but i feel its more of a different request/issue - 
What the 953 requester asks - When app is specifically closed by pressing back button twice, when reopening the app it should open from the home of the app.
What the current implementation is - When the app is minimized by pressing home button, while reopening the app through homescreen it reopens the app from scratch.  
Expected behavior as seen in all apps including Google apps, games - When the app is opened from launcher after minimizing it would resume from where we left.

**Comment by deckerst** [comment]
Regarding b) i think you're right. I should change the current behavior, as it's not obvious and some users even think it's a bug.
