### ISSUE TITLE
"file no longer exists" ... but it does

### ISSUE THREAD

**Issue by ajay-gh** [deckerst/aves#1009]
After update from earlier to v1.10.9 existing image files (fresh from the camera) are reported as "no longer exists".

**To Reproduce**
- take a photo
- open Aves -> "Collection"
- you do only see a placeholder for the photo file, but no thumbnail
- when you select it, a message "no longer exists" appears BUT the photo's date and time are correctly shown

**Expected behavior**
- obvious

**Screenshots**
- will send upon request
 
**System information and logs:**
My phone cannot connect to Github, so I have to type the basics here on a PC, extremely abbreviated, sorry.
"1.10.9-play, build 118"

**Additional context**
Android 12
The same photos are shown in Gallery without any problem and immediately after shutter action.

**Comment by ajay-gh** [comment]
When I use the share button no other "image" viewer (e.g. Gallery) is shown, but I can select the email client. Doing so, the client opens with a "new email" window, but the picture file does not get attached.
Seems silly but on the other question you have to guide me. I do not see a INnfo page, not in the main menu, not in the "tripple dots" menu, nor in settings.
I can confirm that opening the picture the following data are shown correctly on top of the screen:
file name, data & time, picture size.

**Comment by ajay-gh** [comment]
Just to explain, in settings under storage access the proper folder DCIM) is shown as having access as needed.
And no permissions have been denied (or changed after the upgrade).

**Comment by deckerst** [comment]
Thanks for following up. For the Info page, simply swipe up from the
fullscreen viewer page.

**Comment by ajay-gh** [comment]
That seems to be the explanation, the new version of Aves is trying to locate the image files in the 
.../0/Pictures folder, while the camera places them into the .../0/DCIM/Camera folder. 
ONLY ... I did  never change any such setting consciously.

**Comment by deckerst** [comment]
I'd like to clarify a few things.

You take a photo, and Aves thinks it's in "Pictures", but the camera actually stores it in "DCIM". And it does so everytime. Right?

You don't get the issue by other creation workflow, like taking a screenshot or downloading an image via a web browser. Right?

**Comment by ajay-gh** [comment]
2x yes
Yes, all I use is the camera and the new photo immediately shows in Gallery BUT not in Aves.
No screenshots, etc.
What is weird, Aves had no problems with this in the first few versions, now it does. And once you open the picture in Gallery (without moving it !), Aves sees it too.

**Comment by ajay-gh** [comment]
I think I mentioned it in my initial email, but let me just add two observations :
1) once a photo has been opened in Gallery, it also shows in Aves as it should, 
2) all older photos (in all folders incl. DCIM) show in Aves without any problems.

**Comment by deckerst** [comment]
@ajay-gh do you still have the issue with Aves v1.11.17?

**Comment by ajay-gh** [comment]
Just tested it, took a photo ... v1.11.17 shows all my photos BUT does dot show the photo just taken.
Best Regards

**Comment by deckerst** [comment]
Ok, then please follow the instructions at About > Bug Report, to attach here system info & logs. And a screen recording showing your workflow along the logs would be helpful.

**Comment by ajay-gh** [comment]
Aves 1.12.2. still has the same issue. Please let me know that you see the comment (as I am not allowed to re-open the issue).
Thanks

**Comment by deckerst** [comment]
You haven't read what I wrote above.

**Comment by ajay-gh** [comment]
I had send all these "reports" before, by email, before you asked me to open an issue here at Git.
Same for screen shots (a screen recording I cannot do on this phone).
