### ISSUE TITLE
Folder browse mode, quicker file operations. 

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#1010]
Broken record here 👋🏽 
*Aves really needs a folder browse mode. 
Simple gallery, Pictures and F-Stop gallery has it. 
This way files can be much faster organized than creating groups or categories by utilizing File Managers.

*Please make all files access permission or otherwise to speed up file operations. Deleting or moving files asking for folder access to each new directory is cumbersome and slow. The blue circle of death is what I call the percentage dialogue. 

Please dev 🥺

**Comment by mohamedzerougdz** [comment]
ملاحظة جيدة

**Comment by deckerst** [comment]
[Aves is not a file manager.](https://github.com/deckerst/aves/wiki/FAQ#is-aves-a-file-manager)
