### ISSUE TITLE
App switches to PiP mode when turning the phone while playing video

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#1013]
**Describe the bug**
If you play a video and then switch your phone from portrait to landscape (or vice versa) the app kicks you out to the home screen and plays the video in PiP

**To Reproduce**
1. Play any video
2. Without pausing the video, turn your phone

**Expected behavior**
The video should keep playing normally without crashing the app

**System information and logs:**
```
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.1-play, build 120
Flutter: stable 3.19.6
Android version: 14, API 34
Android build: 2024050300
Device: Google Pixel 7 Pro
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: ready
System locales: en_US, ru_RU
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: true
```

[aves-logs-20240508_012101.txt](https://github.com/deckerst/aves/files/15238841/aves-logs-20240508_012101.txt)

**Additional context**
It works fine if you pause the video before turning the phone

**Comment by deckerst** [comment]
Also, if you disable PiP in Aves, does turning your screen while playing a video work as expected?

**Comment by flexagoon** [comment]
Yes, if I click on the PiP, I do return to the app.

I am using GrapheneOS, but the issue happens even with the hardened malloc disabled

When PiP is disabled, the issue does not happen
