### ISSUE TITLE
HEIF Support

### ISSUE THREAD

**Issue by Trinangle** [deckerst/aves#1021]
I own a Sony camera in which I take photos in both HEIF and RAW. When moving the images to my phone the RAW/.ARW files render perfectly. However, my HEIF/.HIF do not render and just show an "oops!" When I select them for viewing.

I am not sure if it is my specific HEIF settings that are the issue or if it is the codec itself however the perfect solution would be it for it to be supported.

If it is unable to be implemented due to the codec being licensed (I believe this is why darktable does not offer the option to export in HEIF) then its no issue at all.

Screenshots of all errors I could find are attached:
![Screenshot_20240511-122847_Aves Libre](https://github.com/deckerst/aves/assets/97986514/3df72229-d550-43a8-ba15-609cb0019c4b)
![Screenshot_20240511-122824_Aves Libre](https://github.com/deckerst/aves/assets/97986514/af14d95f-4f66-4c46-925e-5a918e79c5f9)
I cannot attach an example image.
I have however attached a screenshot of the HEIF metadeta:
![Screenshot_20240511-123225_Aves Libre](https://github.com/deckerst/aves/assets/97986514/f69d335c-3070-44c3-af64-f7c53d76ffbc)

**Comment by deckerst** [comment]
In the past, someone with a Sony alpha 6700 camera privately reported the same issue to me. To which i replied: 
> Aves uses the native HEIF codec provided by the OS, so it's most likely that the version of Android on your device provides a simple codec that does not support the advanced profiles used by your Sony camera. In that case, there's nothing I can do (besides bundling a custom HEIF codec, which is out of the question).

That user also mentioned that their camera produced HEIF in HDR HLG, and that not all software managed to render it.

In any case, i don't intend to bundle custom codecs for HEIF.
