### ISSUE TITLE
Cannot delete files

### ISSUE THREAD

**Issue by RenLabz** [deckerst/aves#1025]
**Describe the bug**

**To Reproduce**
1. Go to gallery and select photo
2. Click on delete/trash can
3. It says to Please select DCIM directory of "internal shared storage" in the next screen to give this app access to it.
4. Says the system file picker is missing or disabled. Please enable it and try again

**Expected behavior**
Delete files, or prompt where to hive access to DCIIM

Screenshots
 [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**

**Additional context**
It was the first thing I wanted to do after install. Otherwise it looks amazing and some great features like memory and category, etc. Nice clean interface, easy to read.
![Screenshot_20240516-101953447](https://github.com/deckerst/aves/assets/168674648/a5d03707-f299-4db1-bcad-f3375cd8f25e)
![Screenshot_20240516-101922642](https://github.com/deckerst/aves/assets/168674648/7bca1425-51a1-4d48-a81f-3f77430137b6)
![Screenshot_20240516-101915856](https://github.com/deckerst/aves/assets/168674648/b5df3efa-e197-46e5-9519-4c45abfcd2a0)

**Comment by deckerst** [comment]
The system file picker is a core Android component. Do you use a custom ROM? A rooted device? Did you disable some services/packages/apps?

**Comment by deckerst** [comment]
The system file picker is a full screen system app that looks like this:
![Screenshot_20240516_193346_Files](https://github.com/deckerst/aves/assets/13898333/358836f5-cd01-4f3d-8247-473036dabd4f)

Have you seen this picker triggered from another app on your device?
