### ISSUE TITLE
[Screensaver] Add black background option similar to slideshow function

### ISSUE THREAD

**Issue by ajain-93** [deckerst/aves#1032]
**Is your feature request related to a problem? Please describe.**
I use Aves to show a slideshow of all the photos on my device using the Android builtin Screen Saver function. The screen saver settings shows has an option to either Fill or Fit the photo. When using the Fit mode, the background area is white.

The slideshow functionality which is very similar, uses a black background.

**Describe the solution you'd like**
I would like there to be an option to select what the background colour should be. Either White/Black option, or a colour picker.

**Describe alternatives you've considered**
I've tried using the slideshow functionality instead, but it does not start automatically. 

**Additional context**
None.

**Comment by deckerst** [comment]
Thanks for reporting this. It's a bug. I won't add a setting but I'll make it consistent with the slideshow.
