### ISSUE TITLE
App Crash everytime after start by cataloging

### ISSUE THREAD

**Issue by Dachbewohner** [deckerst/aves#1037]
Every time I open the app, the cataloging appears in the top bar. As soon as picture 55 is reached, the app crashes

Systeminfos:
Pixel 7 Pro
GraphenOS
Android 14

Logs attached
[Aves log 5c059b4262e3.txt](https://github.com/user-attachments/files/15525114/Aves.log.5c059b4262e3.txt)
[Error in Aves b460b4770aea.txt](https://github.com/user-attachments/files/15525115/Error.in.Aves.b460b4770aea.txt)
[System log 87c044441497.txt](https://github.com/user-attachments/files/15525116/System.log.87c044441497.txt)

**Comment by deckerst** [comment]
Could you please follow the instructions [here](https://github.com/deckerst/aves/issues/977#issuecomment-2061905514) and send me the file that makes it crash? If you don't feel comfortable with sharing it in this thread, you can also send it to me via [email](mailto:gallery.aves@gmail.com).

**Comment by Dachbewohner** [comment]
thank you for the fast response. It is a big .dng file (678MB) from Ligthroom. I send you a Mail

**Comment by deckerst** [comment]
Thanks for the sample. I can reproduce the crash on my device.
