### ISSUE TITLE
Identify non-geotagged photos

### ISSUE THREAD

**Issue by lordofscripts** [deckerst/aves#1038]
**Is your feature request related to a problem? Please describe.**

The app uses EXIF Geotag information to identify countries and show them in a collection. However, it NEVER identifies the photos which have no Geotag.

Personally, I aim to geotag ALL my photos so that I can put them on a map.

**Describe the solution you'd like**

• In the general view of All photos, put a small icon on the thumbnail to either identify photos with or without geotag.
• In the Country Collection show an un-named collection or something like that.

**Describe alternatives you've considered**

Anything that helps me identify photos without geotag, so that I (the user) can edit the information and add the Geotag

**Additional context**

It would also be nice if there was a shortcut to edit or view the geotag rather than going through so many steps.

**Comment by deckerst** [comment]
You're in luck:
- `Settings` > `Thumbnails` > `Overlay` > `Show location icon` > `Unlocated`,
- Search page > `Metadata` section > `Unlocated` filter,
- `Settings` > `Viewer` > `Quick actions` > 4th page of available buttons > `Edit location`.
