### ISSUE TITLE
Edit date time with accuracy to the second

### ISSUE THREAD

**Issue by wanzh5** [deckerst/aves#1041]
In the current version, the date of an image can only be edited to the minute. However, sometimes the order of photos needs to be accurate to the second.

**Comment by deckerst** [comment]
Related:
- https://github.com/flutter/flutter/issues/23764

I don't want to complexify the existing UI for `Set custom date` (which uses date and time pickers), but I will add `seconds` to the `Shift` operation.

Alternatively, you can already name your files with a timestamp that includes seconds then use the `Extract from title` operation.
