### ISSUE TITLE
Stack jpeg and raw if filename is shared

### ISSUE THREAD

**Issue by MrRinkana** [deckerst/aves#1045]
**Is your feature request related to a problem? Please describe.**

When images are imported from a source that takes raw images but also saves a jpeg (or similar other lossy format) a lot of duplicates appear in AVES. These files are typically named identically except for the ending format (ex: IMGP3947.JPG and IMGP3947.PEF). This can happen if for example images have been synchronised with a cloud where photos from a dedicated camera also are uploaded, if a camera microSD was inserted into the mobile or if the mobile camera app also generates two photos in the described way.

**Describe the solution you'd like**
Files that have identical names should be stacked similarly to how the burst patterns are. 

Potentially some additional check could be made, such as: "one photo must be a raw format" or "date in metadata must match"..

**Describe alternatives you've considered**
Another way could be to hide the raw images, but that might create problems if raw images are sourced from more than one place..

**Additional context**
I have not seen any other patterns than the one described.

There's some raw formats which I believe allow for embedding of the jpeg within, but that is another issue/feature.

**Comment by deckerst** [comment]
Related: 
- #810
- #1020

Contrary to those 2 issues that i won't implement, i like your suggestion of stacking the raw and jpeg.

The only thing that i need to think about is whether it's possible to have a burst of photos that are taken in raw and jpeg: 001.raw 001.jpg 002.raw 002.jpg etc.

**Comment by MrRinkana** [comment]
> The only thing that i need to think about is whether it's possible to have a burst of photos that are taken in raw and jpeg: 001.raw 001.jpg 002.raw 002.jpg etc.

Maybe related jpeg and raw files could be called a collection or something, and the current burst pattern logic to allow containing such "collections" in addition to single images (assuming its some kind of list internally).

I'm currently away from my computer so I haven't looked trough your code so sorry if I'm speaking nonsense!

**Comment by MrRinkana** [comment]
❤️!
