### ISSUE TITLE
Sorting Issue for Photos Taken Across Timezones

### ISSUE THREAD

**Issue by siubb** [deckerst/aves#1047]
**Describe the bug**
Last week, I flew from Tokyo to Taipei. Taipei is 1 hour behind Tokyo. I took some photos on the plane and at both airports. I want the photos taken in Taiwan to be shown after the ones taken in Japan. In the Samsung stock photo viewer and Fossify gallery, the thumbnails are in the correct order. However, in Aves, the order is wrong.
(I tried setting the sorting to "by date" and "by filename", but both options have some issues.)

(Thank you for the change in v1.11.2 : "opening app from launcher shows home page only when exited by back button")

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information and logs:**

**Additional context**

**Comment by deckerst** [comment]
I suspect these other galleries sort by the file date, which matches your expectation (as long as the files don't get modified and the date doesn't change). 

Could you please share a couple of your images with the different time zones? Please specify what order you expect with these samples.

If you don't feel comfortable sharing them here, you can also share them by email at gallery.aves@gmail.com

**Comment by siubb** [comment]
> I suspect these other galleries sort by the file date, which matches your expectation (as long as the files don't get modified and the date doesn't change).
> 
> Could you please share a couple of your images with the different time zones? Please specify what order you expect with these samples.
> 
> If you don't feel comfortable sharing them here, you can also share them by email at [gallery.aves@gmail.com](mailto:gallery.aves@gmail.com)

Thanks for getting back to me so quickly!
Actually, after thinking about it some more, I think this is more of a feature request than a bug.

I would greatly appreciate it if you could add one more sorting option called "file last modified date time", 
and change the current "By date" sorting option to "EXIF date taken" for example.
This would be really helpful because it looks like the phone corrects the last modified date of files after changes in the timezone, and hence sorting by this date could be more meaningful than EXIF dates in some cases.

Photo order in Fossify, in the same order I took the photos (Last Modified Date and Time)
Landed
About to land
In the air near Taiwan
In the air near Japan
Right after take-off
![fossify](https://github.com/deckerst/aves/assets/34423871/8b1153c1-6705-451d-ba73-6d147a0725e6)

Photo order in Aves (Date = EXIF date taken ?)
![Screenshot_20240613_105400_Aves Libre](https://github.com/deckerst/aves/assets/34423871/3f5f9970-353b-478a-ad0a-6073f3e52dfc)

Photo order in XnView on Win10 (Please check the labels)
![xnview-correct-order-by-file-modified-date](https://github.com/deckerst/aves/assets/34423871/8cd26eec-2832-4b9b-b18b-de2e56aaa67c)

**Comment by lordofscripts** [comment]
It would be _nice_ if we could _opt_ to have the timestamp (not filename) shown as UTC.

BTW sorting by UTC time would have all photos with the same time reference. The Disadvantage being that the app has to spend time converting.

**Comment by siubb** [comment]
> It would be _nice_ if we could _opt_ to have the timestamp (not filename) shown as UTC.
> 
> BTW sorting by UTC time would have all photos with the same time reference. The Disadvantage being that the app has to spend time converting.

Nice. For my use case, sort by "file modified date" should be good enough, and fast.

**Comment by deckerst** [comment]
I've thought about this issue and I believe playing with UTC times is not a good idea. It may help in this specific case, not in general. Besides, it's not a bug. The current date interpretation is logical, but against expectations of OP who travels faster than the Earth rotation.

As for the "file modified date", see this issue:
- #97

**Comment by siubb** [comment]
> I've thought about this issue and I believe playing with UTC times is not a good idea. It may help in this specific case, not in general. Besides, it's not a bug. The current date interpretation is logical, but against expectations of OP who travels faster than the Earth rotation.
> 
> As for the "file modified date", see this issue:
> 
> * [Sort by file created/modified date #97](https://github.com/deckerst/aves/issues/97)

I appreciate that you thought through the situation of users' reported problems.

I believe there is a small minority of users who travel even more frequently and may also find that the sorting can be improved.

It's similar to the iOS vs. Android comparison. iOS offers limited options and tries to guide you towards what it thinks you want. That's why it's the most popular phone system globally. On the contrary, Android provides a wide range of options, sometimes even too many. However, there are people who prefer it because they find it more flexible and livable compared to iOS.

I'm not sure what "discovered date" is, but I hope there will be a setting one day that can help display photos in the correct chronological order for our specific situation. Thank you.
