### ISSUE TITLE
not showing all pictures in an album

### ISSUE THREAD

**Issue by Yorha-Antimony** [deckerst/aves#1049]
**Describe the bug**
There are 100 pictures in a an album and it is only showing 15.

Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.1-play, build 120
Flutter: stable 3.19.6
Android version: 9, API 28
Android build: PPR1.180610.011.G955USQU8DUD3
Device: samsung SM-G955U
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/6339-3362/
Storage grants: 
Error reporting: true
[aves-logs-20240613_193226.txt](https://github.com/user-attachments/files/15830940/aves-logs-20240613_193226.txt)

**Comment by deckerst** [comment]
Duplicate: 
- #760
