### ISSUE TITLE
Edit existing tag

### ISSUE THREAD

**Issue by m0byn** [deckerst/aves#1051]
Is it possible to edit an existing tag? E.g. I would like to rename an existing tag called "AA" to "AB". I was clicking everywhere, but didn't find the option for it. If it is not possible, I would strongly suggest to implement this feature.

Otherwise I have to say it is an AMAZING app - keep up the good work!

**Comment by deckerst** [comment]
At the moment it is possible, but takes several steps:
https://github.com/deckerst/aves/wiki/FAQ#how-do-i-rename-a-tag

Please note that tags are written in the files themselves, so renaming a tag means editing all the files that have it.

> Otherwise I have to say it is an AMAZING app - keep up the good work!

Thanks!
