### ISSUE TITLE
Where is arm64 v8 version from IzzyOnDroid?

### ISSUE THREAD

**Issue by DeadSecTr** [deckerst/aves#1053]

**Comment by deckerst** [comment]
In the GitHub releases.

**Comment by deckerst** [comment]
Izzy repo does not host large APKs, and a "fat" APK containing all ABIs would be beyond their accepted threshold. The `v7` APK is compatible with more devices than the more recent `v8`.

In any case, if you prefer a specific artifact only available in the GitHub release, you can use something like [Obtainium](https://github.com/ImranR98/Obtainium).
