### ISSUE TITLE
Search multiple tags at once

### ISSUE THREAD

**Issue by sleepmaster91** [deckerst/aves#1056]
**Is your feature request related to a problem? Please describe.**
Currently when searchine multiple tags, if the pictures don't have ALL tags in them the search returns nothing (ex : searching for cats and dogs tags will return results only if the pictures are tagged with both cats and dogs)

**Describe the solution you'd like**
Being able to return results with items that have either tags (ex : cats OR dogs tags)

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerst** [comment]
You can select multiple tags in the `Tags` page, then in the top right menu > "Show in Collection".
