### ISSUE TITLE
Workaround to allow Pixel Camera (GMS indipendent google app) open pictures with aves

### ISSUE THREAD

**Issue by cyclomani** [deckerst/aves#1058]
I'm using Pixel Camera (com.google.android.GoogleCamera) on my Pixel mobile phone without GMS.
This is officially supported, but there's one drawback: I cannot watch the just taken picture from the in-app 'view picture' button/shortcut.
Pixel Camera app insits on using Google Photos.

I sucessfully installed Google Photos too, which works well without GMS likewise, but I'd prefer not to use different apps for same purpose.
Maybe there's a way to fix/spoof (soft) app-ID, resp. link-assignment.
Like other apps do it: "Open by default" -> "Open supported link" and registering links under "Links to open in this app".

The Google Photos app has the advantage of preserving directory structure (grouping by directory parent name), but the disadvantage that I lose geo-location rendering feature without GMS.  aves does a wonderful job in presenting geo-location via OpenStreetmap!
Thanks for that great app!

**Comment by deckerst** [comment]
If the camera expects a specific package instead of using regular intents, there's nothing I can do.
