### ISSUE TITLE
Checking do not ask again doesn't save preference

### ISSUE THREAD

**Issue by DarkShadowZX58** [deckerst/aves#1059]
**Describe the bug**
When moving images, a conformation to to save dates pops up, clicking do not ask again does not doesn't save the dates even though save dates was clicked

**To Reproduce**
1. Select Image
2.Click move to
3.Choose album
4.Check do not ask again in confirmation dialogue (leave save dates checked)
5.Click Continue

**Expected behavior**
The moved Images should not change  the date modified tag when save dates and do not ask again are checked together.

**Screenshots**
![Screenshot_2024-06-27-01-53-02-53_ee4e2c77f5dd6d2e03bdeacf38a89f81.jpg](https://github.com/deckerst/aves/assets/76984854/3e438146-032b-447b-a4ef-941e5c106c93)

**System information and logs:**
Package: deckers.thibault.aves
Installer: dev.imranr.obtainium
Aves version: 1.11.3-izzy, build 12202
Flutter: stable 3.22.2
Android version: 11, API 30
Android build: RMX1971_11_F.06
Device: realme RMX1971
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: ready
Connectivity: mobile
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/
Error reporting: false

![aves-logs-20240627_015410.txt](https://github.com/user-attachments/files/15995069/aves-logs-20240627_015410.txt)

**Comment by deckerst** [comment]
"Save dates" saves the current "file modified date" as a metadata date (typically In Exif, but could be XMP, depending on file format).

The "file modified date" will get modified as a side effect of moving the media, whatever you check. As a gallery app, Aves does not have full control of the file attributes.

**Comment by DarkShadowZX58** [comment]
> The "file modified date" will get modified as a side effect of moving the media, whatever you check. As a gallery app, Aves does not have full control of the file attributes.

Hmm but moving without the do not ask again option works fine like the date modified doesn't change then
