### ISSUE TITLE
Request the MANAGE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#106]
Android 11 API removed the ability to access all files on the device. However, you can still request the MANAGE_EXTERNAL_STORAGE permission to access all files if your app fits into one of the following categories:

- File management
- Backup and restore apps
- Anti-virus apps
- Document management apps
- Search (On Device)
- Disk/Folder Encryption and Locking
- Device Migration/Phone transfer

The "file management" category is described like this:
> App’s core purpose involves the access, editing, and management (including maintenance) of files and folders outside of its app-specific storage space

I think that Aves fits into that category, so you should use the MANAGE_EXTERNAL_STORAGE permission. That way user won't need to grant separate permissions for different folders, and also Aves will be able to access the Downloads folder.

Links:
1. [Google Play policy for this permission](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en#zippy=%2Cpermitted-uses-of-the-all-files-access-permission) 
2. [The Android Developers page about this permission](https://developer.android.com/training/data-storage/manage-all-files)

**Comment by deckerst** [comment]
> I also looked at some gallery apps on Google Play, and they do have this permission. So yeah, you should probably try to apply for it first.

Could you please give me the link to some of these apps?
