### ISSUE TITLE
Hide quick actions OSD when viewed

### ISSUE THREAD

**Issue by foxjaw** [deckerst/aves#1061]
**Is your feature request related to a problem? Please describe.**
Always tapping the image after opened to hide the OSD is taxing and repetitive.

**Describe the solution you'd like**
When the viewer is opened, let the OSD be hidden on media viewer access.

**Describe alternatives you've considered**
Provide a toggle in the settings to set this behaviour.

**Comment by deckerst** [comment]
I believe what you want is covered by Settings > Viewer > Overlay > Show on opening.
