### ISSUE TITLE
File-Database does not refresh by itself when Files have been added

### ISSUE THREAD

**Issue by ValentinJns** [deckerst/aves#1064]
**Describe the bug**
I am using an App that syncs files that have been created on an other device to my local folders that I am displaying in Aves, e.g. the "Camera"-folder.

When a new file has been added by any other App to a folder that has been already listed in Aves at Albums, the file won't be shown in Aves unless you restart Aves by force with phones settings Crash tool.

In other Apps though, the file would be displayed immediately after it had been added to the folder by any App.

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.3-play, build 122
Flutter: stable 3.22.2
Android version: 10, API 29
Android build: ELE-L29 10.1.0.150(C431E22R2P5)
Device: HUAWEI ELE-L29
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: de_DE
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Comment by ValentinJns** [comment]
As I experiance the Screenshots issue as well, I think the issue is related to: https://github.com/deckerst/aves/issues/687

Are there any plants to change the way Aves works concerning the Media Store to the way F-Stop works? Or giving the user the option between the two, for those who are worried about privacy and those who want better functionality?

**Comment by deckerst** [comment]
> Are there any plants to change the way Aves works concerning the Media Store to the way F-Stop works?

No, I believe that relying on the Media Store is the right thing to do. The Media Store reflects what the system is aware of, so other apps can safely register media and query them.

Usually, people having issues with this approach use a badly written app that move media around without properly updating the Media Store. And then they think other apps should be fixed.

Beyond that, there could be an update bug, which is tracked in this issue:
- #760
