### ISSUE TITLE
[Feature request] Tagging using CLIP 

### ISSUE THREAD

**Issue by dgudim** [deckerst/aves#1065]
First of all, loving your app, the tagging feature is a life saver!

But, it would be even better if the images could be searched by tags genearted by a CLIP model. Currently I am using this app to do that: https://github.com/slavabarkov/tidy but it's not really convenient. If it helps, I can even pay for implementing this feature (yes, I want this very badly :) )

**Comment by deckerst** [comment]
Duplicate:
- #939 

> I can even pay for implementing this feature (yes, I want this very badly :) )

Haha that's nice of you to suggest, but money is not the bottleneck. Mostly time and energy!
