### ISSUE TITLE
File size on viewer overlay

### ISSUE THREAD

**Issue by Techaku** [deckerst/aves#1066]
**Is your feature request related to a problem? Please describe.**
In the past, I've always loved and used Pip Photos, until I discovered this new project which seemed to embody the photo management tool of my dreams. However, during practical usage, I found an imperfection that should not exist—the critical piece of information about displaying image dimensions is absent from the overlay in the image viewer.

**Describe the solution you'd like**
Add show size of image/video on Settings > Viewer > Overlay > Show description. 
Display it on the right side of the resolution.

**DescribeDescribe alternatives you've considered**
None.

**Additional context**
In today's digital era, most social platforms and image hosting services automatically re-compress images uploaded by users. In these instances, the preview function of image dimensions becomes especially vital; it should not necessitate additional actions within the viewer, such as swiping up to enter the messaging interface, to obtain this information. Ideally, the image dimensions should be directly visible on the viewer's overlay, enabling users to promptly ascertain whether their images have undergone unnecessary compression. Moreover, I believe the text display approach in the overlay could be refined. Even though frosted glass effects are employed, the overall visual presentation remains cluttered, seemingly trying to camouflage the impact of the frosted glass on the underlying image content through a less-than-harmonious text layout. The image below demonstrates the effect of the overlay in Pip Photos, and I hope it will serve as a useful reference.
![20240707154109](https://github.com/deckerst/aves/assets/48639966/1bb93a82-baef-4a9e-b4ff-ebf3d43be793)

While I am aware that you responded to this issue on May 31, 2022 , I hope that by now your perspective from before has changed. Should my message encroach upon your valuable time, please accept my sincerest apologies.
https://github.com/deckerst/aves/issues/263#issuecomment-1141693285

**Comment by deckerst** [comment]
You mention both "size" and "dimensions", which are different things:
- "size" refers to the file size in bytes,
- "dimensions" refers to the image pixel count in width and length, like 1920 x 1080.

On the viewer overlay, Aves already shows the dimensions but it doesn't show the file size.
However the file size is displayed in the `Collection` page when using the `list` view.

As for your use case of determining whether the image got recompressed, you can already do it with the dimensions, whether they are the original dimensions or the smaller dimensions of the compressed images.

**Comment by Techaku** [comment]
Thank you for your reply. I'm very sorry that due to my failure to carefully proofread my post, it resulted in a confusion between resolution size and file size. something that went against my original intent. After receiving your reply, I've tried organizing my photo albums using the "List" layout, and I find this method brings a higher efficiency compared to comparing and deleting images within the viewer. Nevertheless,  I still believe that displaying file size on the viewer overlay is an important feature. perhaps due to my long-standing habit of using Pip Photos. I noticed you added the "wont-fix" label. I am feeling disappointed because this shouldn't be a disallowed feature, but I can only hope that this "Issues" post might help others who come across and wonder about this problem in the future. 
Thank you once again for your response and for taking the time to correct my mistakes.

**Comment by Techaku** [comment]
> You mention both "size" and "dimensions", which are different things:
> 
> * "size" refers to the file size in bytes,
> * "dimensions" refers to the image pixel count in width and length, like 1920 x 1080.
> 
> On the viewer overlay, Aves already shows the dimensions but it doesn't show the file size. However the file size is displayed in the page when using the view.`Collection``list`
> 
> As for your use case of determining whether the image got recompressed, you can already do it with the dimensions, whether they are the original dimensions or the smaller dimensions of the compressed images.

Thank you for your reply. I'm very sorry that due to my failure to carefully proofread my post, it resulted in a confusion between resolution size and file size. something that went against my original intent. After receiving your reply, I've tried organizing my photo albums using the "List" layout, and I find this method brings a higher efficiency compared to compare and delete images within the viewer. Nevertheless,  I still believe that displaying file size on the viewer overlay is an important feature. perhaps due to my long-standing habit of using Pip Photos. I noticed you added the "wont-fix" label. I am feeling disappointed because this shouldn't be a disallowed feature, but I can only hope that this "Issues" post might help others who come across and wonder about this problem in the future. 
Thank you once again for your response and for taking the time to correct my mistake.
