### ISSUE TITLE
Set video preview frame to first frame

### ISSUE THREAD

**Issue by HerrAugust** [deckerst/aves#1073]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
I have a bunch of videos and the preview is the n–th frame. I need it to be the first frame, or I need to be able to choose the video preview somehow. 

**Describe alternatives you've considered**
I have tried to modify the video and make the first frame, containing the video title actually, last more. Nothing.

If we could choose the video preview, it would be great! Thanks in advance! 

**Additional context**

**Comment by deckerst** [comment]
Duplicate:
- #1062
