### ISSUE TITLE
Media Navigation Bar

### ISSUE THREAD

**Issue by rqphaa** [deckerst/aves#1074]
**Is your feature request related to a problem? Please describe.**
If I took two or more photos of the same subject, I want to be able to compare them in the best possible way to choose the better one. This is currently only possible to a very limited extent.

**Describe the solution you'd like**
Samsung have the best solution in their native gallery app. There is a "Media Navigation Bar" with which you can quickly and easily switch back and forth between the photos and videos. 

**Describe alternatives you've considered**
Alternatives are superfluous compared to this implementation, since it has already been implemented perfectly here.

**Additional context**
https://github.com/deckerst/aves/assets/76430905/0dd51247-1a84-47b3-ac1a-1842e67a3294

**Comment by deckerst** [comment]
Have you tried to enable `Settings` > `Viewer` > `Overlay` > `Show thumbnails`?
Scrolling these thumbnails does not show the image instantly, but tapping on them does.

Also, to switch instantly between the next/previous images without swiping, you could enable `Settings` > `Viewer` > `Tap on screen edges to show previous/next item`.

**Comment by rqphaa** [comment]
Thanks, I haven't found that yet. However, an option for direct display when scrolling would still be helpful. Thanks for your work!

**Comment by deckerst** [comment]
Duplicate: 
- #378
