### ISSUE TITLE
Is this app 32bit only? It will stop working on GrapheneOS

### ISSUE THREAD

**Issue by Zeit08** [deckerst/aves#1076]
A recent update of GrapheneOS enabled a warning about apps which work in 32bit only. 

Aves seems one of those. I downloaded it from f-droid (not libre version) and I got the notice.

Can it be updates to support 64bit architecture?

**Comment by deckerst** [comment]
If you got it from f-droid but it's not the libre version, I suppose you have the izzy version from IzzyOnDroid repo. That repo publishes only the 32 bit build of Aves, but the 64 bit build of the Izzy version exists and is available with the GitHub releases. You could use Obtainium to get it and future updates.

**Comment by C0ffeeCode** [comment]
Why is only the 32bit being published on Izzy? Is it planned to resolve this issue?

**Comment by deckerst** [comment]
@C0ffeeCode you can raise this issue with Izzy.
