### ISSUE TITLE
"Cataloging" eternally.

### ISSUE THREAD

**Issue by MarddleDoo12** [deckerst/aves#1078]
I get a notification saying that the albums are being cataloged, but it never ends, Even if you press the "cancel" button, the notification reappears.

Expected behavior:
successfully cataloged albums

Current behavior:
the program never finishes cataloging the albums

More info:
Motorola G6 play
3GB ram
Non-Root

![Screenshot_20240712-162343](https://github.com/user-attachments/assets/f9ef5027-e4c3-40a0-bf74-009c5c085b10)

**Comment by deckerst** [comment]
Please fill in the sections of the bug report template. That includes attaching logs and system info from About > Bug Report.

**Comment by MarddleDoo12** [comment]
Log:
[aves-logs-20240712_174712.txt](https://github.com/user-attachments/files/16199170/aves-logs-20240712_174712.txt)


System info:
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.5-play, build 124
Flutter: stable 3.22.2
Android version: 9, API 28
Android build: PPPS29.55-35-18-7
Device: motorola moto g(6) play
Support: dynamic colors=false, geocoder=true, HDR=false
Mobile services: ready
Connectivity: wifi
System locales: es_AR
Storage volumes: /storage/FF07-1E20/, /storage/emulated/0/
Storage grants: /storage/FF07-1E20/
Error reporting: false

**Comment by deckerst** [comment]
Not sure of the root cause yet, but I see at least from the logs that you get that issue:
- https://github.com/flutter/flutter/issues/113697

That issue is unfortunately not getting solved on Flutter's side. I'll see what I can do.

**Comment by deckerst** [comment]
@MarddleDoo12 do you still have the issue with Aves v1.11.13?
If so, could you please share the logs you get with that version?

**Comment by MarddleDoo12** [comment]
I'm using v1.11.10 and I haven't experienced that error again.
