### ISSUE TITLE
Increase the 'recent tags' list

### ISSUE THREAD

**Issue by kmcbest** [deckerst/aves#1080]
**Is your feature request related to a problem? Please describe.**
I often go thru my images and apply tags to them. I'm a booru image collector so I have a LOT of tags (meaning my 'top tags' section is too long to find low frequency tags, so I often keep.that section collapsed). Since I often apply similar tags to images as I go, 'recent tags' can be handy . But the recent tags lists is too short. The pop-up list by long-pressing the tag button contains 5, while the 'recent' section contains 10.

**Describe the solution you'd like**
Increase the pop-up list by long-pressing the tag button to contain 10, and the 'recent' section to contain 20.

**Describe alternatives you've considered**

n/a

**Additional context**
n/a

**Comment by deckerst** [comment]
Do you realize that if the tag button long-press shows more items, you'll have to slide your finger that much more?
I'm thinking of adding items with an auto-scroll behaviour so that the finger wouldn't have to travel a large distance.

**Comment by kmcbest** [comment]
God idea. So keep the size of the pop up menu

**Comment by deckerst** [comment]
> Is that it?

Nope, as the tap release handling is useful to select/cancel without having to lift and tap again.

I was thinking of an auto-scroll the way selecting works in the `Collection` or `Albums` page, for example. When you long press and your finger goes close to the top or bottom of the screen, it scrolls in that direction so it continuously expands the selection.
