### ISSUE TITLE
Add button capture frame from video 

### ISSUE THREAD

**Issue by androidcn** [deckerst/aves#1081]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![Screenshot_20240717_223637.jpg](https://github.com/user-attachments/assets/63540b4b-7424-442e-9e90-692b301ec855)

**Comment by deckerst** [comment]
Already possible, via Settings > Viewer > Quick actions > 3rd page gather video actions.

**Comment by androidcn** [comment]
wow thanks
