### ISSUE TITLE
External video player support 

### ISSUE THREAD

**Issue by foxjaw** [deckerst/aves#1082]
I have mpv-android which have way more capabilities through libmpv. I wanna use that to play my gallery videos.

Unfortunately, Aves forces to use the built-in player. But I want a gallery, that can allow me to use external video player.

**Comment by deckerst** [comment]
Already possible, via Settings > Video > Controls > Buttons > Open with other player.

**Comment by deckerst** [comment]
Then how would you access for videos the info page and all related features?
