### ISSUE TITLE
Recommended to join "Google Maps"

### ISSUE THREAD

**Issue by nichousha123** [deckerst/aves#1083]
I remember the previous version of Google Maps, why was it deleted? Mainland China's data is still relatively detailed, compared with current map service providers. Looking forward to the next version of the "Google Maps API" trouble the author, thank you

**Comment by deckerst** [comment]
I don't understand your issue. Google maps layers are still available in the `play` and `izzy` flavours, if the Google Mobile Services are installed on the device. 

I recently removed the `huawei` flavour with the Petal maps layers, though. Is that what you mean?

Please paste here the system info your get from About > Bug Report.

**Comment by nichousha123** [comment]
> I don't understand your issue. Google maps layers are still available in the `play` and `izzy` flavours, if the Google Mobile Services are installed on the device.
> 
> I recently removed the `huawei` flavour with the Petal maps layers, though. Is that what you mean?
> 
> Please paste here the system info your get from About > Bug Report.


Hello author, please look at the screenshot, there is no "Google Maps option" in the map layer. The mobile phone brand is Vivo, with Google services

Package: deckers.thibault.aves.libre
Installer: null
Aves version: 1.11.5-libre, build 12402
Flutter: stable 3.22.2
Android version: 11, API 30
Android build: RP1A.200720.012 release-keys
Device: vivo V2046A
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: not available
Connectivity: vpn, mobile
System locales: zh_CN
Storage volumes: /storage/emulated/0/, /storage/caf-999/
Storage grants: /storage/emulated/0/下载/, /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/Download/YTDLnis/, /storage/emulated/0/DCIM/, /storage/emulated/0/我的文件/, /storage/emulated/0/Download/tgp/
Error reporting: false
![Screenshot_2024_0718_090000](https://github.com/user-attachments/assets/001305df-b120-4559-90ce-0a914f238841)
[aves-logs-20240718_084459.txt](https://github.com/user-attachments/files/16276376/aves-logs-20240718_084459.txt)

**Comment by deckerst** [comment]
You're using the `libre` flavour, which doesn't include the Google maps layers:
https://github.com/deckerst/aves/wiki/App-Versions

Use the `play` or `izzy` flavours.

**Comment by nichousha123** [comment]
> You're using the `libre` flavour, which doesn't include the Google maps layers: https://github.com/deckerst/aves/wiki/App-Versions
> 
> Use the `play` or `izzy` flavours.

❤️Thank you so much
