### ISSUE TITLE
Add option to open GPS location in card apps like Google Maps

### ISSUE THREAD

**Issue by ValentinJns** [deckerst/aves#1087]
**Is your feature request related to a problem? Please describe.**
In Aves, although I can view the GPS location of a picture/video within the App, there is no option to view it in Google Maps in order to start a navigation to the location or see labels that are only shown in the Maps App. The only option is to manually copy the coordinates.

**Describe the solution you'd like**
Add an option to type/klick on the GPS coordinates / street name unter the pictures and get the option to view the location in Apps like Google Maps, in a similar way Huawei Gallery handles this (see Screenshot attached).
![Screenshot_20240718_151115_com huawei android internal app](https://github.com/user-attachments/assets/910ecfff-8276-47de-a065-46c551e6544d)

**Comment by deckerst** [comment]
Have you tried the full screen viewer menu > Export> Show in map app?

**Comment by ValentinJns** [comment]
Thank you! Now I found the menu I was looking for.

Although, as I usually first use the in-App map, before I maybe switch to Google Maps, to me, it would make sense to aditionally add the same menu on the following two areas in the menu: 
![Screenshot_20240718_152317_deckers thibault aves_edit_253044911993678](https://github.com/user-attachments/assets/dc3882d3-9cac-4e88-ac3e-4c7d890cd634)
![Screenshot_20240718_152324_deckers thibault aves_edit_253063899762946](https://github.com/user-attachments/assets/3072ebaa-a18b-40f6-b656-1857ffaf2035)

**Comment by deckerst** [comment]
I added a button to open an external map app, next to the layer selection button.

**Comment by ValentinJns** [comment]
I just saw the update. Now, it is perfect. Thank you very much!

**Comment by koniu** [comment]
Hi thete

> I added a button to open an external map app, next to the layer selection button.

Has something changed? Used this button regularly but its now gone from the screen. Version 1.14.5
deckers.thibault.aves.libre from fdroid

<img width="1080" height="1302" alt="Image" src="https://github.com/user-attachments/assets/e2874d48-7a3f-4bff-9a55-3363b3e6b245" />

**Comment by deckerst** [comment]
@koniu That page does not have the button, but it sits right in the middle of 2 pages which do:
1) in the full screen viewer menu > Export > Show in map app,
2) in the map page (openable from the top-left button or the photo marker in the preview in your screenshot), top right menu button.
