### ISSUE TITLE
Vaults no longer functioning after updating to 1.11.7

### ISSUE THREAD

**Issue by akrscoi** [deckerst/aves#1088]
**Describe the bug**
After updating to Aves 1.11.7 (play), existing vaults will no longer open and show a 'Failed' message. Attempting to create a new vault gives a message that says 'local_auth plugin requires activity to be a FragmentActivity'

**Expected behavior**
Vault to open and being able to create a new vault.

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.google.android.packageinstaller
Aves version: 1.11.7-play, build 126
Flutter: stable 3.22.3
Android version: 14, API 34
Android build: REDMAGICOS9.0.12_NX729J_GB
Device: nubia NX729J
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: en_US, ja_JP, zh_Hans_CN
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/data/, /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/emulated/0/Download/Seal/, /storage/emulated/0/Audio/, /storage/emulated/0/Termux/
Error reporting: false

**Additional context**
Log file contains no logs. I can also see in the internal storage that vaults are still taking up their respective space.

**Comment by deckerst** [comment]
Thanks for the report! I'm releasing a hotfix. Should be available soon.
