### ISSUE TITLE
Not all Quick Actions appearing

### ISSUE THREAD

**Issue by LUFCFan** [deckerst/aves#1089]
Selected a number of quick actions in the settings.
When in selection mode, not all the quick actions appear, in portrait mode.
If you turn the phone to landscape, the quick actions appear.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by deckerst** [comment]
This is by design. It shows as many actions at it can, leaving some space for the title.

**Comment by LUFCFan** [comment]
Hi, here is the problem.

I setup some quick actions.

I select a photo to action.

In portrait mode, only a few quick actions display. I agree with what you
said, however I am unable to perform the action in the 3dot dropdown.
If I use landscape mode, the actions are there.

The 3 actions I could not see are. Tags, ratings and location. If they
appeared in the 3dot dropdown it would make sense.

Please let me know if you need screenshots.


Thanks

Gary

**Comment by deckerst** [comment]
Oh, right, there is a bug indeed, as they should appear in the 3dot menu. It currently fails for the actions that are in the `Edit` submenu. Thanks for pointing that out!
