### ISSUE TITLE
images turn black

### ISSUE THREAD

**Issue by tiptoptom** [deckerst/aves#1092]
**Describe the bug**
First of all, I don't know if aves is actually to blame for this phenomenon, but I have the feeling that it has only been occurring since I installed aves.

For some time now, it has been happening again and again (I estimate about 1-2 images per month) that images suddenly turn almost completely black. Only a narrow horizontal or vertical strip of the original image remains as well as a thumbnail of the original image in a correspondingly low resolution. And this is not only displayed in aves, but the file is saved as it is.

I have now revoked aves' access rights and will observe whether the error still occurs (then it must be due to something else). In the meantime, I would be grateful for any ideas as to what could be causing this.

**To Reproduce**
_I don't know yet_

**Expected behavior**
Images remain as they are

**Screenshots**
![c4a23356-a487-4cd7-9976-2f06204c6b15](https://github.com/user-attachments/assets/123d0255-0f1a-47cd-b054-839c4a0741a8)
(Well, that's funny. When I upload the picture here, it's white and not black.)

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.android.packageinstaller
Aves version: 1.11.5-libre, build 12402
Flutter: stable 3.22.2
Android version: 11, API 30
Android build: lineage_suzu-userdebug 11 RQ3A.211001.001 534503a1b7
Device: Sony Xperia X
Support: dynamic colors=false, geocoder=false, HDR=false
Mobile services: not available
Connectivity: wifi
System locales: de_DE
Storage volumes: /storage/emulated/0/, /storage/30D6-59D9/
Storage grants: /storage/30D6-59D9/Pictures/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/30D6-59D9/DCIM/
Error reporting: false

**Miscellaneous**
Apart from that, thanks for this great app! I find it incredibly useful!

**Comment by deckerst** [comment]
Thanks for the report, but it's unlikely Aves has anything to do with it. Let's not confuse correlation and causation.

If you manage to reproduce it following an action in Aves, be sure to save the logs.

I'll close this issue as it is unactionable, but feel free to comment/reopen if you have further insights, or at least proof that Aves is touching the files.
