### ISSUE TITLE
gallery view miniatures not loading

### ISSUE THREAD

**Issue by bejaranoo** [deckerst/aves#1093]
**Describe the bug**
gallery view miniatures not loading

**To Reproduce**
just recent and sometimes older photos fail to load the miniatures on the gallery but I can open them without issue

**Screenshots**
![WhatsApp Image 2024-07-21 at 16 08 00](https://github.com/user-attachments/assets/5aae1aa7-502e-45c8-87ac-f8da3545b292)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.miui.packageinstaller
Aves version: 1.11.2-izzy, build 12101
Flutter: stable 3.22.2
Android version: 12, API 31
Android build: SKQ1.211019.001 release-keys
Device: Xiaomi Redmi Note 9 Pro
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/03E5-266C/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/03E5-266C/DCIM/, /storage/03E5-266C/downloads/
Error reporting: false

**Comment by deckerst** [comment]
Logs please

**Comment by bejaranoo** [comment]
> Logs please

[aves-logs-20240721_161119.txt](https://github.com/user-attachments/files/16325955/aves-logs-20240721_161119.txt)

**Comment by deckerst** [comment]
Did you somehow remove the permission "ACCESS_MEDIA_LOCATION"?

**Comment by bejaranoo** [comment]
> Did you somehow remove the permission "ACCESS_MEDIA_LOCATION"?

![Untitled](https://github.com/user-attachments/assets/70a9b3a8-def5-4407-8883-89257541f830)
Thanks!, changing to always allowed fixed the issue, I guess Xiaomi just being xiaomi...
