### ISSUE TITLE
"hidden item" filters cannot be remove if album doesn't exist anymore

### ISSUE THREAD

**Issue by DeeDee22** [deckerst/aves#1095]
**Describe the bug**
I marked some albums as hidden and then later renamed the folder (outside of aves). I wanted to remove the now obsolete entries in the "hidden items" in the privacy settings but clicking the little x does nothing. It worked fine when I tried the same thing (without the renaming of course) on another folder.

**To Reproduce**
1. Mark an album as hidden
2. Rename the folder of the album using some other gallery or file app
3. go to privacy settings -> hidden items and try to remove the entries for the albums from step 1.

**Expected behavior**
The entries for the albums get removed

**Actual behavior**
Nothing

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: org.fdroid.fdroid
Aves version: 1.11.8-libre, build 12702
Flutter: stable 3.22.3
Android version: 13, API 33
Android build: FP5.TT4H.A.162.20240609
Device: Fairphone FP5
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
Connectivity: wifi, vpn
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/3462-6662/
Storage grants: 
Error reporting: false

**Comment by DeeDee22** [comment]
[aves-logs-20240723_232141.txt](https://github.com/user-attachments/files/16354423/aves-logs-20240723_232141.txt)

**Comment by deckerst** [comment]
Strange, your steps are clear (thanks!) but I can't reproduce the issue, and the logs don't show an error. I just tried it and the obsolete hidden item got removed when tapping the X, as expected.

The one you couldn't remove was within "Hidden Filters" (not "Hidden Paths"), right? And can you reproduce this issue at will?

**Comment by DeeDee22** [comment]
I just tried to reproduce it and.. umm. I was wrong about the cause of the problem. It has nothing to do with the renaming. Apparently I can't remove any hidden items that are toggle off.
Sorry for the confusion!

**Comment by deckerst** [comment]
Right, there's a bug, I just reproduced it. Thanks!
