### ISSUE TITLE
Reverted ? [v1.11.2] - 2024-06-11 opening app from launcher shows home page only when exited by back button

### ISSUE THREAD

**Issue by siubb** [deckerst/aves#1097]
**Describe the bug**
It seems the change has been reverted v1.11.8.
(i.e. the app always shows the home page now again)

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information and logs:**

**Additional context**

**Comment by deckerst** [comment]
It's a regression by mistake, not my intention. I'll fix it for the next release.
