### ISSUE TITLE
Make toast message thinner

### ISSUE THREAD

**Issue by pkoepke** [deckerst/aves#1100]
First of all, this is a really excellent app.

It would be nice if the toast bar that appears when you make a change to a file (such as renaming) were only as wide as the text. I do a lot of renaming files and moving them to other folders, and whenever I rename a file the toast message completely obscures the move option. If the toast bar message were only as wide as the message, the option to move the file would probably not be totally obscured. Screenshot attached.

![Screenshot_20240725-131757](https://github.com/user-attachments/assets/73e63313-f0a6-48d5-b5ad-8f7527383e1b)

No big deal if wide toast bar is a design decision you don't want to change, it's impossible to make everyone happy all the time.

**Comment by pkoepke** [comment]
Sounds good, want me to close the issue or leave it for you to close?

**Comment by deckerst** [comment]
Please leave it open. I'll close it when I tackle this.

**Comment by pkoepke** [comment]
I see the new behavior - thanks!
