### ISSUE TITLE
Allow specifying custom location of the .thumbnails folder

### ISSUE THREAD

**Issue by boredace** [deckerst/aves#1101]
Currently Aves creates hidden .thumbnails folder inside Pictures folder (/storage/emulated/0/Pictures/.Thumnails). This hidden folder contains cashed thumbnails of ALL photos browsed in the app. On a device which contains large numbers of photos this folder can be quite large. 
Another issue with this is that user may have photos in some random directory elsewhere on the device but share their Pictures folder (synchronize via Syncthing for example) and unwillingly is going to make those photos included in the synchronization via the .Thumbnails folder in the Pictures folder (!)

The app should:
1. Inform the user that it needs to cache photos which may make leave copy of all photos accessed by the app in a cached .thumbnails folder
2. Allow the user (in Settings) to specify custom location of the .Thumbnails folder

Alternatively app could store the thumbnails inside the app protected storage  which would make it unavailable to external access from outside of the application.

**Comment by deckerst** [comment]
> Currently Aves creates hidden .thumbnails folder inside Pictures folder (/storage/emulated/0/Pictures/.Thumnails

Nope. Android does that.
