### ISSUE TITLE
Updating app icon in Accrescent listing

### ISSUE THREAD

**Issue by matchboxbananasynergy** [deckerst/aves#1104]
Hi there,

Currently, the Accrescent listing for Aves has the app's old icon, rather than the [updated](https://github.com/deckerst/aves/blob/develop/aves_logo.svg) one.

For the time being, icons have to be updated by Accrescent itself, though developers being able to update it themselves is planned.

I am making this issue to ask whether it would be okay for Accrescent to update Aves' icon to the new one?

While I assume the answer is 'yes', it's better to have explicit consent from the app developer before making any changes to the app listing.

Thanks!

**Comment by deckerst** [comment]
Yes please! 
And thanks for asking, I appreciate the politeness ^^

**Comment by lberrymage** [comment]
The listing is updated now.
