### ISSUE TITLE
Cannot access OpenCamera subfolder

### ISSUE THREAD

**Issue by pybride** [deckerst/aves#1105]
**Describe the bug**
As I use both phone Camera app and OpenCamera, in DCIM folder, I have a Camera and OpenCamera folder. The OpenCamera pictures aren't visible in aves.

**To Reproduce**
1. Install OpenCamera
2. Set image saving to default DCIM/OpenCamera
3. Take some photos with OpenCamera
4. Try to see them in aves

**Expected behavior**
Another album OpenCamera should be displayed, like most other photo gallery app.

**Comment by deckerst** [comment]
Most likely that app creates media items but doesn't register them with the Android Media Store. Feel free to file an issue on their repo.
