### ISSUE TITLE
Saving filter set in Collection

### ISSUE THREAD

**Issue by deckerst** [deckerst/aves#1107]
### Discussed in https://github.com/deckerst/aves/discussions/1106

<div type='discussions-op-text'>

<sup>Originally posted by **artisak2** August  1, 2024</sup>
Is there a way to save a filtered collection you are currently viewing with all filters applied?

I know that i can "add a shortcut" to the launcher of the collection I am viewing with the filters applied, but I do not see away to save and access this in the app.

For example:
DirA
|
|__DirB
|
|__DirC
|
|__DirD

I would like to find a way to quickly view everthing in DirA but filter out DirC and anything with TAG: "xyz" etc.. etc..

I ask because there are some cases where i find myself repeating, and would find this useful.

Thanks!

edit: Formatting

In fact, if there is a way to have a page with all saved filter sets as "Home" when app opens, that would be even better</div>

**Comment by halfrafu** [comment]
From what I see there's a "set as home" option in collections which will save currently applied filters but when you go somewhere else (like to albums view) the filters are lost and you need to either reopen the app or set them up again. Also there seems to be no way to filter by parent directory which I think would be handy.

I think it would be cool to have an option to setup custom collections which will appear on the side menu. In my case it would be enough to setup a collection based on parent directory or multiple directories, for example /sdcard/DCIM for photos or /sdcard/Android/<etc. etc.>/WhatsApp/Media for whatsapp media.

**Comment by deckerst** [comment]
> filter by parent directory

Maybe you mean the kind of filters you get via the Explorer page, which filter by path and get all the images recursively.

**Comment by halfrafu** [comment]
Yes exactly! I didn't realize you can press currently selected folder at the bottom. Now if only I could set this up as a custom collection so I can quickly switch to it and it doesn't display the currently applied filter below "collection"... which pretty much is what this issue is about.

Actually that's a good point: do you think collection filters should be hidden or visible while entering the custom collection?

**Comment by deckerst** [comment]
I think filters should always be visible, mostly to inform, but also to allow removing them one by one. In my opinion, a "custom collection" (as you call it) is a filter group with a label.

Now, it's already possible to save a filter group as a shortcut, or set a filter group as home. What's missing is the labelling, so that it can be used in the navigation drawer or from the search page.
