### ISSUE TITLE
Option to sort videos by duration

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#1109]
**Is your feature request related to a problem? Please describe.**
I have many shorter videos, but sometimes I just want to quickly view the longer videos I took.

**Describe the solution you'd like**
Sort by duration. 

**Describe alternatives you've considered**
Adding labels

**Additional context**
-

**Comment by deckerst** [comment]
I understand it's not the same thing, but in the meantime couldn't you sort by file size?

**Comment by Donkey-Doug** [comment]
Closed in 2 days!
