### ISSUE TITLE
Widgets fail to load after reboot

### ISSUE THREAD

**Issue by pomstazlesa** [deckerst/aves#1110]
**Describe the bug**
When 3 or more widgets are placed on Home Screen, after a reboot, only 2 widgets at most load its content [It also seems to be random, which 2. Changes after every reboot]. Rest of the widgets, that fail to load its content, are completely transparent. When the widget setting "When tapping on the widget" is set to "Update widget", on the widgets that fail to load after reboot, tapping on these widgets does not update them and instead acts as if it was set to "Open home". These widgets load only after going into individual widget settings and hitting "Save".

**To Reproduce**
1. Create at least 3 different widgets on Home Screen.
2. Reboot phone.
3. Wait for widgets to load.
4. One of 3 possible outcomes:
      a. Only 2 widgets load successfully.
      b. Only 1 widget load successfully.
      c. No widgets load successfully.

Optional part:

5. When widget setting "When tapping on the widget" is set to "Update widget", tapping on widget that fails to load opens app, instead of updating widget.

**Expected behavior**
All widgets should load their content, in the same way they were set to before reboot.

**Screenshots**
Can send a video recording upon request.

**System information and logs:**
Package: deckers.thibault.aves
Installer: app.accrescent.client
Aves version: 1.11.8-play, build 127
Flutter: stable 3.22.3
Android version: 14, API 34
Android build: 2024080200
Device: Google Pixel 8a
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: ready
Connectivity: none
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/Camera/, /storage/emulated/0/Pictures/, /storage/emulated/0/Android/media/
Error reporting: false
[aves-logs-20240804_181656.txt](https://github.com/user-attachments/files/16487327/aves-logs-20240804_181656.txt)

**Additional context**
Tested on Google Pixel 7a and 8a, with Nova Launcher and AOSP Launcher, on Android 14.

**Comment by deckerst** [comment]
Thanks for the report.

Roughly how many items are in your collection? (From the logs I see "27", which is unusually low.)

In the logs I see shader related issues. I don't know whether it's related, but if it is, it may work better with the `izzy` or `libre` flavours (cf [here](https://github.com/deckerst/aves/wiki/App-Versions)). Could you give it a try and let me know if you have the same issue?

**Comment by pomstazlesa** [comment]
> Roughly how many items are in your collection? (From the logs I see "27", which is unusually low.)

That is correct, in fact it should now be 21, some were in Bin. This phone setup is about a week old, no previous media was restored, hence this low amount of media.


> In the logs I see shader related issues. I don't know whether it's related, but if it is, it may work better with the `izzy` or `libre` flavours (cf [here](https://github.com/deckerst/aves/wiki/App-Versions)). Could you give it a try and let me know if you have the same issue?

Tried `izzy` version, set up same widgets and content in them from scratch, same result. Info and logs bellow:

Package: deckers.thibault.aves
Installer: dev.imranr.obtainium
Aves version: 1.11.8-izzy, build 12702
Flutter: stable 3.22.3
Android version: 14, API 34
Android build: 2024080200
Device: Google Pixel 8a
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: ready
Connectivity: none
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false
[aves-logs-20240804_202533.txt](https://github.com/user-attachments/files/16487686/aves-logs-20240804_202533.txt)
