### ISSUE TITLE
Описание фотографий

### ISSUE THREAD

**Issue by Pank26m** [deckerst/aves#1113]
Связан с добавлением новой функции. 

В приложении есть возможность писать описание для фото, но оно отображается не полностью, если нажать на него над фото, а чтобы прочесть полностью, нужно открыть данные о фото, нажать три точки сверху, нажать на изменение описания и тогда будет всё описание видно. 

Прошу сделать создание описаний более удобней. Чтобы было видно всё описание, а также отображалось в данных о фото. 

Пример: Google photo. (фото ниже)

![Screenshot_20240805-102130~2.png](https://github.com/user-attachments/assets/3d91c9da-4931-4d08-aa5e-06feb89dd1fc)

![Screenshot_20240805-102136.png](https://github.com/user-attachments/assets/eb31dd22-ef67-41a4-bbf3-7b16dbef38f6)

![Screenshot_20240805-102144.png](https://github.com/user-attachments/assets/fc9665c5-ecdb-42bc-aadb-3215291bcf28)

![Screenshot_20240805-102247.png](https://github.com/user-attachments/assets/c6e33e4d-88b7-4b49-8d45-eef8fabb20c2)

![Screenshot_20240805-102301.png](https://github.com/user-attachments/assets/26ff7820-352a-4060-a61e-4eb433d3c58e)

![Screenshot_20240805-102308.png](https://github.com/user-attachments/assets/e5bbcc6a-469d-45be-bc3f-68f913294f3d)

**Comment by deckerst** [comment]
Long descriptions on overlay are now scrollable.

**Comment by deckerst** [comment]
By the way, I enjoyed your sweet story. And good luck in Kyiv.
