### ISSUE TITLE
Privacy leaks via maps

### ISSUE THREAD

**Issue by v6ak** [deckerst/aves#1114]
**Describe the bug**
When looking at details of a photo with geotag, Aves seems to load on-line maps at the place. Maybe it doesn't send the precise location (not sure), but it must inherently send approximate photo location in order to load the appropriate map, unless all the data is in the cache.

**To Reproduce**
1. Find a photo with geotag
2. Swipe for more information

**Expected behavior**
No network communication is performed, or sending the location is opt-in. From user PoV, I see several options:

a. Some off-line maps are supported. (This might be an overkill.)
b. Maps are loaded on-demand.
c. Automatic maps loading is opt-in.

Moreover, this should be covered in privacy policy.

**Additional context**

Disabling network connection breaks the feature, as expected.

**Comment by deckerst** [comment]
I don't intend to address your worries about this.

If you feel this is important to you, I suggest you install the `izzy` or `libre` flavour, and never select a layer for the maps. If you've already selected one, you'll need to clear the app data (but of course backup your vaults beforehand if you have any).

**Comment by v6ak** [comment]
OK. Could you at least clarify this in privacy policy, please?

-----

There is another workaround, but it is specific to Graphene OS: Disable network permission.

**Comment by deckerst** [comment]
I don't think it's necessary. It's not a policy of the app. Also, it's obvious that map tiles are loaded from the internet and that the coordinates of the map tiles are in the vicinity of the coordinates of the pictures. As I said, don't select a map layer if you mistrust the internet.
