### ISSUE TITLE
Duplicate Images displaying in App

### ISSUE THREAD

**Issue by krazykelv** [deckerst/aves#1121]
**Describe the bug**
I find that I semi regularly get certain images duplicated in the app, even though the images reference the same file on disk. If I delete one of the images, then both get deleted. The only way to fix it is to delete the image and then restore it. 

**To Reproduce**
Uncertain how to reproduce currently, as it happens intermittently. 

**Expected behavior**
It should only display a single image for each file on disk

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.8-play, build 127
Flutter: stable 3.22.3
Android version: 14, API 34
Android build: 68.1.A.2.230 release-keys
Device: Sony XQ-DC72
Support: dynamic colors=true, geocoder=true, HDR=false
Mobile services: ready
Connectivity: mobile
System locales: en_AU, en_NZ
Storage volumes: /storage/emulated/0/, /storage/3034-6131/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: true

**Additional context**

**Comment by deckerst** [comment]
Duplicate:
- #971 

Please follow the instructions [here](https://github.com/deckerst/aves/issues/971#issuecomment-2048108266) if you wish to help.
