### ISSUE TITLE
Misleading feature description? 

### ISSUE THREAD

**Issue by marciozomb13** [deckerst/aves#1122]
**Describe the bug**
The drop down menu option in viewer called "export" seems off, maybe should be called "expand" since is exactly what it does. 

**To Reproduce**
1. View some image 
2. Menu

**Expected behavior**
In description above. 

**Screenshots**
![Screenshot_20240809_133037_Aves](https://github.com/user-attachments/assets/bc93819d-6e6f-4777-aba7-46e9082a6305)

**Comment by deckerst** [comment]
The meaning "export" is correct, as all the actions in that menu are related to converting the item or forwarding it outside the app.

"Export" does not refer to the fact that it is an expandable menu.
