### ISSUE TITLE
Add Accrescent link to Aves Libre in version comparison chart

### ISSUE THREAD

**Issue by matchboxbananasynergy** [deckerst/aves#1130]
**Is your feature request related to a problem? Please describe.**

Since the decision to add the "Libre" flavor of Aves to Accrescent was made, it should also be reflected at https://github.com/deckerst/aves/wiki/App-Versions

**Comment by deckerst** [comment]
@matchboxbananasynergy I'll add the badge, but it seems the url I was using to get the current version published by Accrescent is no longer usable. I was using something like:
```
https://store.accrescent.app/apps/deckers.thibault.aves/repodata.json
```
Do you know if this is still supposed to work? Otherwise, is there a proper API for this?

**Comment by lberrymage** [comment]
@deckerst The domain was changed to `repo.accrescent.app` to free up the `store` subdomain for other purposes. Otherwise that should work fine.

There isn't a proper API for this right now and there likely won't be one for a while, but there are plans to have one eventually.
