### ISSUE TITLE
Adjustable Album View corner radius

### ISSUE THREAD

**Issue by derei** [deckerst/aves#1131]
In Album View, the thumbnails corners have a rather pronounced radius, as it can be seen below:

![ImgTbox_2024-08-14_12-31-19_4441](https://github.com/user-attachments/assets/52bf6d04-fa65-4b3a-9f42-2d6539053b9a)

I am sure that was done with a purpose, and the devrloper had a good reason fir it whether functional or aesthetic. And I was wondering if it would be possible to allow the user to adjust the corner radius value in settings.
Same with the album thumbnail outline thickness. From thi post https://github.com/deckerst/aves/issues/286 I infer there may be a meaning for the outline, not just aesthetic. However, in my case it doesn't seem to look different, unless I'm missing something.

**Comment by deviato** [comment]
> In Album View, the thumbnails corners have a rather pronounced radius, as it can be seen below:
> 
> ![ImgTbox_2024-08-14_12-31-19_4441](https://private-user-images.githubusercontent.com/34483372/357796209-52bf6d04-fa65-4b3a-9f42-2d6539053b9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDQwNjAsIm5iZiI6MTczNDIwMzc2MCwicGF0aCI6Ii8zNDQ4MzM3Mi8zNTc3OTYyMDktNTJiZjZkMDQtZmE2NS00YjNhLTlmNDItMmQ2NTM5MDUzYjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE5MTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNTdhNDhmMTBlMTg0OTYwYmJkMTZjOWQxNzFkYzUzMTY3YjQwYTcyZWU0ZjFlODJkZmEyNWMyMjBiN2U4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1SvP7vLZ3OH7W3x9fh6kPi7ON-w3yVUO3JW0oq6lvrc)
> 
> I am sure that was done with a purpose, and the devrloper had a good reason fir it whether functional or aesthetic. And I was wondering if it would be possible to allow the user to adjust the corner radius value in settings. Same with the album thumbnail outline thickness. From thi post #286 I infer there may be a meaning for the outline, not just aesthetic. However, in my case it doesn't seem to look different, unless I'm missing something.

I agree with you, the rounded corner radius is excessive resulting in a huge waste of space.
I understand that the style should be consistent with the filters, but in the case of albums imho they should be more consistent with the style of the thumbnails for the single pictures instead.
The semantic association between ‘tags’ and albums seems to me more a consequence of some sort of hack, to be able to display folders in the same programming way.
I think the primary purpose of an album thumbnail is to be able to identify at a glance what you are looking for, but in this case a large part of the screen is taken up by the too-thick borders and the empty space between the elements.
If it were up to me, I would also eliminate(or give the option to do so) the number of folder that take up an entire line, or I would move them, for example, overlapped to the top right corner.
In any case, for those who need it (besides me), I have created a fork with minor modifications of these values, and again imho, they make the interface more elegant and functional. OK, maybe I went a bit overboard with the too-thin border :D, but take it as a cue.
The code and apk can be found here:
[https://github.com/deviato/aves](https://github.com/deviato/aves)

**Comment by derei** [comment]
@deviato yes, it's much better (for me at least). Thanks for the work.
