### ISSUE TITLE
Video controls: seek buttons custom time

### ISSUE THREAD

**Issue by derei** [deckerst/aves#1133]
I noticed seek buttons have a predefined 10s seek time and it appears it cannot be changed.

Suggestion:
- screen edges tapping and seek buttons to have independently configurable seek times.
Example: screen edge tap: 10s; buttons 1s.
- the times to be configurable by the user and to permit 1ms (or smaller) increments. Or even "by number of frames".

Reasoning:
- for frame capture, especially in very short videos, or motion photos, frame by frame seek is essential.

**Comment by deckerst** [comment]
Frame by frame:
- #1086

**Comment by deckerst** [comment]
I'll close this one as the use case of frame-by-frame stepping is now covered.
