### ISSUE TITLE
Favorites section Grant access 

### ISSUE THREAD

**Issue by rayyanmm** [deckerst/aves#1135]
**Describe the bug**
when I open the favourite section, there is a grant access button that only leads me to the app info page, I'm not sure where the permission is because I've granted the app full storage permissions. (Device: Samsung Galaxy A54)
**To Reproduce**

**Expected behavior**
Show me some steps on what to grant access to.
**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).
![Screenshot_20240817_120609_Aves.jpg](https://github.com/user-attachments/assets/fd1e7fbb-c24c-45e4-bc62-7874013abbd0)

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.9-play, build 128
Flutter: stable 3.24.0
Android version: 14, API 34
Android build: UP1A.231005.007.A546EXXS9CXG2
Device: samsung SM-A546E
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/Download/YTDLnis/, /storage/emulated/0/iPhoneData/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: false
![aves-logs-20240817_120951.txt](https://github.com/user-attachments/files/16644205/aves-logs-20240817_120951.txt)

**Additional context**

**Comment by deckerst** [comment]
Thanks for the report. 

I'm aware of the issue, and it's just a superficial bug that you can ignore. You likely have the right permissions already, but the app wrongly displays this button when there are no images.

**Comment by rayyanmm** [comment]
Alright, Appreciate it!

**Comment by deckerst** [comment]
I'll keep this open until I fix it.
