### ISSUE TITLE
Secure Folder

### ISSUE THREAD

**Issue by Angelito3p** [deckerst/aves#114]
Just as many other apps, an option to hide pictures/videos with a lock, be it fingerprints, pin, etc. That'd be great:)

**Comment by Donkey-Doug** [comment]
Related to https://github.com/deckerst/aves/issues/84

**Comment by seriousfreezing** [comment]
Has the secure folder been implemented? How does it work?

**Comment by deckerst** [comment]
It's been implemented as "vaults". You create a vault like you create an album, in the Albums page menu. You can create as many as you want.

**Comment by seriousfreezing** [comment]
Thanks!

**Comment by lordofscripts** [comment]
Will it still show if someone fires up the default gallery viewer rather than Aves?

**Comment by deckerst** [comment]
No, items in Aves vaults are within the device internal storage, only accessible by Aves. This is also why all the items in vaults will be deleted forever if you uninstall Aves (or clear the app data).
