### ISSUE TITLE
Ability to set a specific album as home?

### ISSUE THREAD

**Issue by mxmilkiib** [deckerst/aves#1142]
**Is your feature request related to a problem? Please describe.**
I use the camera folder 90% of the time and it would be nice if it was the first thing that appeared when I opened the app.

**Describe the solution you'd like**
The ability in settings to set a specific album as home.

**Describe alternatives you've considered**
The ability to set an album as home by holding on it then using the menu.

**Comment by deckerst** [comment]
It is already possible: go to the Albums page, tap on the album you want, then in the filtered Collection page use the top right menu > Set as home.
