### ISSUE TITLE
Multiple duplicate photo

### ISSUE THREAD

**Issue by PAFCicleStick** [deckerst/aves#1144]
**Describe the bug**
Some photos in the gallery is multiplicated only in viewpoint but not the actual photo file is duplicated. Additionally if you delete the duplicate you will also delete the file because it only shows that the picture is duplicated but not the actual file is cloned.

**To Reproduce**
1. Go to Aves Libre
2. Click on some folders
3. See error

**Expected behavior**
Some pictures and videos are viewed with duplicate but not the actual file is duplicated.

**Screenshots**
![Screenshot_2024-08-22-08-40-38-95_33b445981d13b98f91994c60df898715](https://github.com/user-attachments/assets/6ba7259c-9ebc-4b59-b9d7-9044d5cbba80)
![Screenshot_2024-08-22-08-42-13-18_33b445981d13b98f91994c60df898715](https://github.com/user-attachments/assets/02e02361-c5b9-48ec-8357-2281c9cb7740)

https://github.com/user-attachments/assets/e0731d6d-da6a-4e08-aaa6-f3c6a26b8f79

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: org.fdroid.fdroid
Aves version: 1.11.9-libre, build 12802
Flutter: stable 3.24.0
Android version: 12, API 31
Android build: CPH2113_11_F.59
Device: OPPO CPH2113
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
Connectivity: mobile
System locales: en_PH
Storage volumes: /storage/emulated/0/, /storage/6564-3463/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/emulated/0/DCIM/Screenshots/, /storage/6564-3463/Download/Bluetooth/, /storage/6564-3463/DCIM/, /storage/emulated/0/MyOldBoy/, /storage/6564-3463/Pictures/
Error reporting: false

[aves-logs-20240822_084844.txt](https://github.com/user-attachments/files/16701475/aves-logs-20240822_084844.txt)

**Additional context**
If you delete the duplicate picture, you will also delete the actual file and both of them will be gone or put into the recycle bin.

**Comment by deckerst** [comment]
Thanks for the report. It's an known issue but I can't reproduce it myself, so I need feedback from users like yourself. You can check out the following issue: 
- #971
