### ISSUE TITLE
Aves wrongly thinks some of my jpeg files are webp

### ISSUE THREAD

**Issue by MCDever** [deckerst/aves#1146]
**Describe the bug**
Aves is detecting some files as WebP instead of their actual file format (for now, I've only seen this happen to files with the .jpg extention)

**To Reproduce**
Unknown.

**Expected behavior**
Should recognize the file as a jpg file and allow tagging.

**Screenshots**
![Screenshot_20240822-202707_Aves Libre](https://github.com/user-attachments/assets/6beff9ba-5a50-49a1-b597-b8a00f20ee18)

**System information and logs:**
[aves-logs-20240822_202838.txt](https://github.com/user-attachments/files/16720479/aves-logs-20240822_202838.txt)

Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.11.8-libre, build 12702
Flutter: stable 3.22.3
Android version: 10, API 29
Android build: QP1A.190711.020.G965U1UES9FVD1
Device: samsung SM-G965U1
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: not available
Connectivity: wifi
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/0123-4567/
Storage grants: 
Error reporting: true

**Comment by deckerst** [comment]
Could you please attach one of these files here?

**Comment by MCDever** [comment]
![RDT_20240805_1627032911055765185360376](https://github.com/user-attachments/assets/57f7a593-620b-45c8-9a99-73fa39b907d5)

This is the one of them. I downloaded the image from reddit of that helps, i think all the affected images are reddit downloaded, but I also have a tone of reddit downloaded images that arnt affected and are treated normally so idk

**Comment by deckerst** [comment]
The image you attached is actually a webp, even though the file name extension is "jpg". It's confirmed by other software like [ExifTool](https://exiftool.org/) and [Media Info](https://mediaarea.net/en/MediaInfo).
