### ISSUE TITLE
Private Mode Launcher Shortcut for Specific Albums

### ISSUE THREAD

**Issue by malta-khan** [deckerst/aves#1149]
A feature that allows users to create a launcher shortcut for a specific album in the gallery app. When launched from this shortcut, the app should open in a "private mode" where only the selected album is visible, and all other albums are hidden. To view other albums, users should launch the gallery app normally.

**Details:**

1. **Functionality:**
   - Allow users to select any album and create a dedicated launcher shortcut for it.
   - When the gallery app is opened through this shortcut, only the selected album should be accessible.
   - All other albums should be hidden from view unless the user restarts the app without album shortcut.

2. **Use Case:**
   - This feature is useful for users who wish to quickly access a specific album without exposing other albums.
   - It enhances privacy, especially when sharing the device or showing photos from a specific album.

3. **User Flow:**
   - The user selects an album and chooses the option "Create Private Shortcut."
   - A shortcut is added to the launcher for that album.
   - When the user taps the shortcut, the gallery app opens directly to the selected album in private mode.
   - To view other albums, the user must exit the private mode or launch the app through the normal app icon.

**Benefits:**
- Improves user privacy by limiting access to specific albums.
- Provides quick access to frequently used albums.
- Enhances user experience with customizable shortcuts.

**Comment by deckerst** [comment]
> Provides quick access to frequently used albums.
> Enhances user experience with customizable shortcuts.

For these two you can already create shortcuts to custom collections. For a specific album, open the album you want, then in the Collection page select in the menu "Add shortcut".

> Improves user privacy by limiting access to specific albums.

I don't intend to provide sandboxing features. If other people have physical access to devices, superficial features like these won't cut it.
