### ISSUE TITLE
Hide the progress circle that appears when deleting.

### ISSUE THREAD

**Issue by kc0ed** [deckerst/aves#1154]
In my Xiaomi photo album,There is no waiting to delete photos. After clicking Delete, the photo will disappear and jump to the next photo.

I think this is convenient because there is no impact on my operation when deleting, and I can do some operation on the next photo at will after clicking delete. (However, there is no "Undo Action" prompt)

I would like to ask the developers if they have any similar ideas, that is, the deletion process does not need to wait, so that users can directly do other operations.

thank u.

**Comment by deckerst** [comment]
For now and the foreseeable future, I intend to keep all I/O sequential.

The real issue here is that deleting files is too slow. It should be fast enough that users don't need to wait. I hope to find a solution for this issue instead.
