### ISSUE TITLE
Show only unsorted photos in DCIM/Screenshot folder in timeline feed.

### ISSUE THREAD

**Issue by bc6048** [deckerst/aves#1156]
For the ease of sorting photos, I request a feature, which is an option to show only unsorted photos in DCIM and Screenshot folder, which will help me avoid the inconvenience of forgetting whether some images have been sorted to albums.

**Comment by deckerst** [comment]
I suppose what you call the "timeline" is the Collection page, and by "sorted" you mean that the items are moved to other albums. 

If you were using tags, you could use use the "untagged" filter to see what hasn't been tagged yet. 

If you use albums, just open the "DCIM" album. And if you need both "DCIM" and other albums, you can select them in the Albums page, then in the menu select "Show in Collection". You could then use the Collection page menu actions "Set as home" or "Add shortcut".
