### ISSUE TITLE
Add option to not delete the folder after deleting the last image

### ISSUE THREAD

**Issue by z2rec** [deckerst/aves#1164]
**Is your feature request related to a problem? Please describe.**
I sort my images into different albums after downloading them. When I download stuff from lemmy I move the pictures to appropriate album and if it's the last image it deletes the "Lemmy" folder as well which creates the issue for my Lemmy client where it can't download new images since the folder doesn't exist anymore.

**Describe the solution you'd like**
Option to toggle which would prevent folder deletion.

**Comment by deckerst** [comment]
> my Lemmy client where it can't download new images since the folder doesn't exist anymore

Seems like a basic issue from this Lemmy client. Why aren't they fixing it?

**Comment by z2rec** [comment]
> > my Lemmy client where it can't download new images since the folder doesn't exist anymore
> 
> Seems like a basic issue from this Lemmy client. Why aren't they fixing it?

You are right, I don't know why I didn't think of that first. Will check with the client, thank you.
