### ISSUE TITLE
Blank or generic custom album cover

### ISSUE THREAD

**Issue by herrbrixter** [deckerst/aves#1165]
**Is your feature request related to a problem? Please describe.**
I want to hide the contents of an album by having a generic image as the album cover. Now it's difficult because I have to put a dummy picture in the folder and set it as the album cover.

I don't want to hide the folder under privacy because it would make it difficult for me to view them. I just want to make the album cover generic if I open the gallery app in front of other people.

**Describe the solution you'd like**
In the cover album choices, allow other choices:
- blank or a different color
- generic pictures like a picture of a folder or a camera
- pick a picture from another album

**Describe alternatives you've considered**
A workaround is to put a dummy generic photo in every folder that I want to be hidden and set it as the custom album cover.

**Comment by herrbrixter** [comment]
Gallery Elite and Fossify Gallery allows you to select an album cover from outside that album.

**Comment by deckerst** [comment]
> I don't want to hide the folder under privacy because it would make it difficult for me to view them.

Do you mean that you do not want to use a vault within Aves? If so, how using a vault makes it difficult to view them?

**Comment by herrbrixter** [comment]
I'll just use the vault. Thanks
