### ISSUE TITLE
Display recycle bin as an album

### ISSUE THREAD

**Issue by herrbrixter** [deckerst/aves#1168]
**Is your feature request related to a problem? Please describe.**
Technically, the recycle bin is an album of deleted pictures so it should show up as an album. I would like to see it in the album view so it is easy to access and recover deleted items.

**Describe the solution you'd like**
Recycle bin is an album that is shown at the bottom of the list of albums.

**Describe alternatives you've considered**
The recycle bin hidden by the menu makes me forget that the recycle bin is there. It is better if it is visible.

**Additional context**
F-stop Gallery, Gallery Elite and Fossify Gallery has the recycle bin as an album.

**Comment by deckerst** [comment]
> Technically, the recycle bin is an album of deleted pictures

Nope. In Aves it's a collection, not an album. And thanks to that you can filter it by album (or any other filter), so you could for example check the deleted screenshots only.
