### ISSUE TITLE
Search by multi tags!

### ISSUE THREAD

**Issue by hoanglongrs** [deckerst/aves#1171]
**Is your feature request related to a problem? Please describe.**
Usually I want to search images/videos by using tags. Example:
- Image 1 have tags: A, B
- Image 2 have tags: A, D, E
- Image 3 have tags: B, E
Now i want to search the image 1 only.
But if search tag A, the result include images 1 and 2. If search by tags B, the result include images 1 and 3.
I can not choose both tag A and B when searching.

**Describe the solution you'd like**
Allow choose multi tags, albums...while searching (similar to Samsung gallery).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deckerst** [comment]
I guess you just found out, but for future reference: users can narrow down and filter their collection with multiple tags by adding them via the Search page.

Alternatively, if what you want is tag A or tag B, you can select both A and B on the tags page and then use the "Show in Collection" in the top right menu.

**Comment by hoanglongrs** [comment]
Thank. Great work.

ps: Could i choose multi videos, and then send the list to another video player (i use the nplayer)?
Thank again.

**Comment by deckerst** [comment]
You can select multiple items and share the lot from Aves. Then it all depends on the receiving app to know how to handle them as a playlist.

**Comment by hoanglongrs** [comment]
Thank
