### ISSUE TITLE
The splash icon does not have the white background

### ISSUE THREAD

**Issue by GaucovyAero** [deckerst/aves#1173]
**Is your feature request related to a problem? Please describe.**
In later versions of Aves, there was an issue on AOSP that i did not report, and that was that the splash icon sometimes had the white circle background and sometimes it did not. What happens now is that it never shows the background, which i guess is better than before, but not ideal.

**Describe the solution you'd like**
I would like the white circle background to exist on the splash just as it is on the icon.

**Describe alternatives you've considered**
None.

**Additional context**
Device: Poco F3 8/256
ROM: crDroid 10.7
Launcher: crDroid Home (Default AOSP)

![Screenshot_20240906-123457_Aves](https://github.com/user-attachments/assets/207f9716-e1fd-4dba-aefc-af5321cf0677)

**Comment by deckerst** [comment]
Note to self: the [doc](https://developer.android.com/develop/ui/views/launch/splash-screen) says "The icon background is optional and useful if you need more contrast between the icon and the window background. If you use an [adaptive icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive), its background is displayed if there is enough contrast with the window background."

**Comment by GaucovyAero** [comment]
FYI, when I was using Lineage 21 (using dark mode), the white background was showing up 100% randomly and was not dependent on the wallpaper.
