### ISSUE TITLE
Quick actions fall under the gesture pill when hiding the UI in Slideshow mode

### ISSUE THREAD

**Issue by GaucovyAero** [deckerst/aves#1177]
**Describe the bug**
Quick actions fall under the gesture pill when hiding the UI when using the Slideshow feature. This bug does not occur when viewing the image normally.

**To Reproduce**
1. Open the slideshow mode, tap once to hide the UI and look carefully.

**Expected behavior**
The quick actions should not fall like this when in Slideshow mode.

**Screenshots**

https://github.com/user-attachments/assets/cd8fb502-51fc-459f-a457-1ccca379b20e

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.packageinstaller
Aves version: 1.11.10-izzy, build 12901
Flutter: stable 3.24.1
Android version: 14, API 34
Android build: AP2A.240805.005
Device: Xiaomi M2012K11AG
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: not available
Connectivity: wifi
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/
Error reporting: false
[aves-logs-20240908_221438.txt](https://github.com/user-attachments/files/16923572/aves-logs-20240908_221438.txt)

**Additional context**
Device: Xiaomi Poco F3
ROM: crDroid 10.7

**Comment by deckerst** [comment]
Thanks for the report. You have a keen eye!
