### ISSUE TITLE
Ultra HDR displayed as two MPF images

### ISSUE THREAD

**Issue by 0pLuS0** [deckerst/aves#1185]
**Describe the bug**

When I save an image sent to via text message, when I open the app at the bottom of the UI are two small thumbnails, one in color the other black and white. When I click on the Image Info MPF says; Number of Images 2 and there is MPF Image #1 and MPF Image #2.

I don't understand why this is happening showing two images/mpf?

**To Reproduce**
1. I save an image sent to me by text message
2. Then I look at the image in Aves Libre
3. I notice at the bottom of the UI two small thumbnails - one color and the other black and white.

**Expected behavior**
I expected to see only one image

**System information and logs:**
[aves-logs-20240911_154630.txt](https://github.com/user-attachments/files/16972179/aves-logs-20240911_154630.txt)

```P.S. I guess the simplest thing I can do is like Edit the photo and when I save it, then it's gone. But why did it do this in the first place have two MPF?```

**Comment by deckerst** [comment]
It's likely an HDR image containing a gain map (the black and white image), but without the required metadata.

MPF is a JPEG structure allowing multiple images to be embedded in a single JPEG. It can be used for multiple purposes: HDR gain map, stereoscopic images, panorama tiles, etc. To distinguish the use case, metadata has to be set the right way.

In Aves, the full screen viewer by default shows embedded images, unless it knows it's a gain map that is useless to the user. In your case, the metadata identifying the embedded image as a gain map is likely missing. I know it can happen when an HDR image is sent by SMS from an iPhone.

Please send me the (unmodified) sample file so I can see if there's a workaround.

**Comment by 0pLuS0** [comment]
Hi @deckerst 

I don't have access to the original, only these images sent to me...

As I mentioned, I guess the simplest thing for me to do is just edit it.

Maybe in the future if it's possible, you can add in a feature to edit/remove tags. Then I could just remove the MPF tags.

THANKS

P.S. I'm going to remove the images now that you've seen them...
