### ISSUE TITLE
Push the latest Swedish translation to the app Repositories

### ISSUE THREAD

**Issue by shift18** [deckerst/aves#1193]
Hello @deckerst
I've made some significant improvements to the Swedish translation for Aves.
Would you be so kind as to push them to the main release whenever you got the time?

I really appreciate how you supported me in my efforts to translate the app, without your support my translations would definitely be of on quite a few strings.
I really can't stress this enough, you've really been very helpful.

Thank you!

**Comment by deckerst** [comment]
Thanks for the translation.

There's no need to create issues for translations. I always merge in the code the latest translations before a release. As for releases, there's no schedule but I tend to release monthly, which is frequent enough. As a matter of fact, I was about to make a release tonight, but wanted to investigate some bug first.

**Comment by shift18** [comment]
Kind of embarrassed of some of the translation mistakes that were left in when the translation was first pushed for release.
So,  just wanted to make sure that the fixes weren't left on the table as it were.
