### ISSUE TITLE
Video Playback (Asking If Bug)

### ISSUE THREAD

**Issue by mitchwalton** [deckerst/aves#1195]
**Describe the bug**

When playing a video in Aves opposed to other video players it's oddly louder hence seems amplified. I have no equalizer on or anything.

**To Reproduce**
1. Go to video
2. Click on play
4. Hear what seems to be an amplification

**Expected behavior**
The video should not be louder opposed to other video players. However, this is my preference if not applying an equalizer. Was the app designed this way?

**Screenshots**
Not needed.

**System information and logs:**
Not needed latest version of Aves.

**Additional context**
Not needed.

**Comment by deckerst** [comment]
There's nothing on Aves side to make the sound louder. Funnily, some other people have complained that the app was playing videos with the sound too low... I guess it's simply that the video player engine that Aves relies on (`FFmpeg` via `mpv`) just does not interpret audio streams the same way as whatever video player people are used to.

**Comment by mitchwalton** [comment]
Thanks. People can be dishonest though and it was MPV video player and FX video player I compared yours to. No biggie it's not clipping or anything obviously! Just wanted a response for understanding and keep up the killer work.
