### ISSUE TITLE
Lock screen misfeature

### ISSUE THREAD

**Issue by rusty-snake** [deckerst/aves#1196]
**Describe the bug**

Full gallery exposed on locked device.

**To Reproduce**
1. Open Aves
2. Press Power-Button (i.e. lock device)
3. Double tap display (i.e. activate display)
4. Browse through your full gallery on a locked device.

*EDIT:* 5. Change settings and delete all images.

**Expected behavior**

Pressing Power-Button makes apps inaccessible. 

**Screenshots**
n/a

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

todo

**Additional context**
If this is intentional, there should be a privacy setting for this behaviour.

**Comment by deckerst** [comment]
Oh, thanks for the report. This is definitely not intended. I'll take a look as soon as possible.
