### ISSUE TITLE
Change to OSM

### ISSUE THREAD

**Issue by gogolo2** [deckerst/aves#1197]
Aves uses google maps for location info. I don't know if google is able to connect this info with me but I would be less worried if Aves used Open Street Maps. It would also fit better to the open source movement. Thx for considering.

**Comment by deckerst** [comment]
> Aves uses google maps for location info

Not quite:
1) Aves offers various layers when displaying the map. Google Maps layers are among them, as well as some layers using OSM data.
2) Reverse geocoding is performed through a provider-agnostic `geocoder` Android service on the device, which *can* be provided by Google, but that depends on what's installed on the device and not on Aves.

> It would also fit better to the open source movement. 

I'm not part of a movement.

**Comment by gogolo2** [comment]
thx for your explanation and sorry for the talk about "movement". "idea" would have been better, but also not neccessary to mention in the first place. Thx for your awsome work.
