### ISSUE TITLE
Option to choose a directory for album creation

### ISSUE THREAD

**Issue by SasikumarN** [deckerst/aves#1209]
**Is your feature request related to a problem? Please describe.**
When I'm creating an album, it ends up in Pictures directory with album name. Every album has its directory.
The pictures directory is used by every other application, distinguishing between others and Aves created albums are difficult.
Ex: I take photos on a trip, create album using Aves, look at pictures directory and it's mixed with other directories

**Describe the solution you'd like**
User of Aves can have an option to choose a directory where to save the albums
Ex: I choose "pictures/aves-albums" as album directory, I take photos on a trip, create album using Aves, I setup syncthing to this folder for synchronization.

**Describe alternatives you've considered**
I couldn't think of any other approach, handpicking the directories currently.

**Additional context**
I'm using Aves Libre - Version 1.11.13

**Comment by deckerst** [comment]
In the meantime, a little known feature: when creating an album you can give it a name containing "/" and that will put it deeper in subfolders. E.g. "aves-albums/trips/Firenze" will create an album "Firenze" in "/Pictures/aves-albums/trips/"

**Comment by deckerst** [comment]
Duplicate:
- #295

**Comment by SasikumarN** [comment]
> In the meantime, a little known feature: when creating an album you can give it a name containing "/" and that will put it deeper in subfolders. E.g. "aves-albums/trips/Firenze" will create an album "Firenze" in "/Pictures/aves-albums/trips/"

This is sufficient for me to manage.
