### ISSUE TITLE
Auto splitting coordinates shared by osm

### ISSUE THREAD

**Issue by pbergaus** [deckerst/aves#1211]
Hello,

Adding custom coordinates is currently, in my opinion, a bit unintuitive. Since I cannot search in ave directly I look up the desired location manually in osm and share the coordinates 
![ResizedImage_2024-09-29_13-55-58_6485](https://github.com/user-attachments/assets/2c6cb61e-dd03-45fb-bb31-e15daf52fabb)

In ave I have to paste that twice an edit it twice to get the coordinates ave requires.

My feature requesz would be that it gets automatically split up when coordinates come in that format.

Thanks
Philipp

**Comment by deckerst** [comment]
I'm thinking of a different feature that could combine with a solution for you: to make Aves a possible target for `geo` URI sharing.

Typically, map apps can be the target of URIs like `geo:48.20838,16.37243` and show that location. In Aves, it could 1) generally do the same (i.e. showing the map page so you can see your photos at that location), but 2) alternatively use that location as input if you were currently editing the location of items.

Just an idea, I need to try this out.

**Comment by pbergaus** [comment]
The first Option with geo: uri would be great and even more elegant.

**Comment by deckerst** [comment]
I implemented both:
- receiving a `geo:` URI opens the map, except
- if you've opened the location editing dialog, receiving a `geo:` URI will fill in the latitude and longitude, so you can review and validate with `apply`.

In OsmAnd, the `geo:` URI sharing button is the last of the sharing buttons: `Copy address`, `Copy POI name`, `Copy coordinates`, `geo:`).
