### ISSUE TITLE
aves internal mediascanner for jpg files: Try to harvest tags, title, description, geo, date from multible sources

### ISSUE THREAD

**Issue by k3b** [deckerst/aves#1218]
I have nearly 22000 jpg photos in 800 folders/albums on my phone and on my tablet.

Many of them have meta data tags, title, description, geo, date in different exif/iptc/xmp fields.

Example:

Some Photos got their "tags" in the microsoft-windows-explorer that were stored in Exif.XPKEYWORDS, other use xmp.Tags or the standard Iptc.KEYWORDS.

It would be great if the aves-media scaner tries to harvest it-s properties from different sources (exif/iptc/xmp)
Example: If tags are not found in Iptc.KEYWORDS try to get them from  xmp.Tags and if not found get them from Exif.XPKEYWORDS

In my not-maintained-anymore-app aPhotoManger i used these (taken from https://github.com/k3b/APhotoManager/wiki/Metadata#mapping under de.k3b.media.PhotoPropertiesImageReader) 

**de.k3b.media.PhotoPropertiesImageReader**

| property | #1 | #2 | #3 | #4 | #5 | #6 | #7 | #8 | #9 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| DateTimeTaken | ExifSubIFD.DATETIME_ORIGINAL | ExternalXmp.DateTimeTaken | InternalXmp.DateTimeTaken | 
| Latitude | ExifGps.Latitude | ExternalXmp.Latitude | InternalXmp.Latitude | 
| Longitude | ExifGps.Longitude | ExternalXmp.Longitude | InternalXmp.Longitude | 
| Title | ExternalXmp.Title | Exif.XPTITLE | IptcDirectory.TAG_HEADLINE | InternalXmp.Title | 
| Description | Exif.IMAGE_DESCRIPTION | ExternalXmp.Description | Exif.XPCOMMENT | Exif.USER_COMMENT | JpegComment.COMMENT | InternalXmp.Description | Iptc.CAPTION | 
| Tags | ExternalXmp.Tags | Exif.XPKEYWORDS | Iptc.KEYWORDS | InternalXmp.Tags | 
| Visibility | Exif.XPKEYWORDS(PRIVATE) | ExternalXmp.apm.Visibility | InternalXmp.apm.Visibility | 
| Rating | ExternalXmp.Rating | Exif.RATING | InternalXmp.Rating | 

* internalXmp means xmp embedded inside the jpg file
* externalXmp means external xmp sidecar file

Related tickets:
* https://github.com/deckerst/aves/issues/1063
* https://github.com/deckerst/aves/issues/1212

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/blob/1864f77866bffd855fd9a1fc209d228a19078813/android/app/src/main/kotlin/deckers/thibault/aves/channel/calls/MetadataFetchHandler.kt#L500

// set `KEY_DATE_MILLIS` from these fields (by precedence):
    // - Exif / DATETIME_ORIGINAL
    // - Exif / DATETIME
    // - XMP / xmp:CreateDate
    // - XMP / photoshop:DateCreated
    // - PNG / TIME / LAST_MODIFICATION_TIME
    // - Video / METADATA_KEY_DATE

// set `KEY_XMP_TITLE` from these fields (by precedence):
    // - XMP / dc:title
    // - IPTC / object-name

// set `KEY_XMP_SUBJECTS` from these fields (by precedence):
    // - XMP / dc:subject
    // - IPTC / keywords

// set `KEY_RATING` from these fields (by precedence):
    // - XMP / xmp:Rating
    // - XMP / MicrosoftPhoto:Rating

https://github.com/deckerst/aves/blob/1864f77866bffd855fd9a1fc209d228a19078813/android/app/src/main/kotlin/deckers/thibault/aves/channel/calls/MetadataFetchHandler.kt#L957

 // return description from these fields (by precedence):
    // - XMP / dc:description
    // - IPTC / caption-abstract
    // - Exif / UserComment
    // - Exif / ImageDescription

**Comment by k3b** [comment]
@deckerst 
Is it possible to add tags from Exif.XPKEYWORDS

**Comment by deckerst** [comment]
Could you please provide a sample with that kind of tags? Also, if I support them, I would read/clear them but I wouldn't write them, I would write standard XMP keywords instead.
