### ISSUE TITLE
Cross app tags

### ISSUE THREAD

**Issue by JoeHardi** [deckerst/aves#1219]
**Is your feature request related to a problem? Please describe.**
I've added plenty of tags, like "Dad" or "name xy" in Aves Libre. When I synchronize pictures with those tags added e.g. to " Memories", the official picture app of Nextcloud, which has the same tag function, the tags won't be recognized by Memories.

**Describe the solution you'd like**
To support tags across different apps - like the location. When a location is added to a picture, Memories recognizes the location.

**Describe alternatives you've considered**
Setting up tags twice.

**Additional context**
Aves Libre 1.11.13
LineageOS with MicroG

**Comment by deckerst** [comment]
Aves uses standard XMP metadata format for tags. It's a problem with the other app.
