### ISSUE TITLE
120hz 

### ISSUE THREAD

**Issue by Slakt82** [deckerst/aves#1221]
The app don't support 120hz in my phone (nothing 2a) 
Ok I figured out how to do it.

**Comment by deckerst** [comment]
> I figured out how to do it.

Did it work after you forced the highest refresh rate in Aves display settings, or did you change something at the OS level? If it's the latter, please share the fix so that it could help fellow users in the future.

**Comment by Slakt82** [comment]
It's work after i change it from Default to highest in the setting
