### ISSUE TITLE
Selfies appear fliped in the gallery thumbnail

### ISSUE THREAD

**Issue by srahman53171618** [deckerst/aves#1224]
I use gcam to take photos. The selfies are set to be saved as viewed. If I open the image, it shows up as expected on the app. However, the thumbnails in the gallery always show them inverted. When you open the thumbnail for a brief second, the image shows inverted as well, but then corrects. Other gallery apps show the image as saved.

It would be great if there was an option to not have inverted selfies in the gallery.

**Describe alternatives you've considered**
The problem does not happen when using apps other than Gcam to take selfies

**Additional context**

**Comment by deckerst** [comment]
Could you please check the `Info` page of one of your selfies, open the `Thumbnail` section, and tell me whether the thumbnail you see there matches the "right" full screen image you see in the viewer or the "wrong" preview you see in the Collection page?

**Comment by srahman53171618** [comment]
So sorry but I missed the comment earlier. The thumbnail matches the "wrong" preview in the collections page.

**Comment by deckerst** [comment]
Duplicate:
- #505

And as I've stated there, I believe it's a bug of the camera app. It should create the correct thumbnail.
