### ISSUE TITLE
Lags in scrolling

### ISSUE THREAD

**Issue by tsiflimagas** [deckerst/aves#123]
**Describe the bug**
First of all, I want to express how surprised I was when I discovered this app. It immediately became my favorite one to use for gallery. It has so nice and well implemented features and is so nicely designed, it left me wondering how I didn't notice it any earlier, and how it hasn't become famous yet.
Back to the topic, I've noticed that scrolling down the list of photos or albums isn't very smooth, especially at the end of the scroll. Also, scrolling friction feels a bit tight, since scrolling ends abruptly. I don't know whether this is a performance issue (my Redmi note 8 doesn't give the smoothest experience in general), but I was wondering whether this could be improved.

**To Reproduce**
1. Scroll through your photos or albums.
2. Observe that the movement isn't that smooth and feels intermittent.

**Expected behavior**
Scrolling to be smooth and fluid.

**System information and logs:**
Aves version: 1.5.5-izzy (Build 1059)
Flutter version: 2.5.3 (Channel stable)
Android version: 12 (SDK 31)
Android build: SD1A.210817.036.A8 release-keys
Device: Xiaomi Redmi Note 8
Google Play services: not available
[aves-logs-20211110_205537.txt](https://github.com/deckerst/aves/files/7515248/aves-logs-20211110_205537.txt)

**Comment by deckerst** [comment]
Thanks for the feedback and all the compliments!

There are 2 related topics:
1) fidelity: Flutter, the framework used by Aves, does not use regular Android components, but paints everything and tries to replicate the motion physics of Android. Replicating the exact acceleration, deceleration, dampening, tightness, etc. of scrolling is not easy. The Flutter team is talented, but there are some [reported issues](https://github.com/flutter/flutter/issues/16371) about scrolling physics fidelity. Also, Android 12 introduced new effects, like overscroll stretching, and the Flutter team is currently working on replicating that.
2) performance: Aves is trying to load low quality thumbnails in a quick way when scrolling and loading higher quality thumbnails when the user stops scrolling. Loading a thumbnail may block the UI in certain circumstances (especially if the thumbnail is displayed for the first time), but I don't have a clear reason yet. Could be memory pressure, could be image codecs doing synchronous work...

The tight scrolling friction may be a fidelity issue, which is up to Flutter to fix. The smoothness issue is more likely related to performance. I'll see if I can improve on this.

I'm surprised by what you say about the Redmi Note 8. From the specs it looks like a modern and very capable phone. If you say that it's not smooth in general, it's difficult for me to judge how Aves compares to the standard smoothness of other apps.

**Comment by tsiflimagas** [comment]
Well, my statement about my device is rather subjective, to be honest. For the last 2-3 years I've been messing around with custom Android ROMs, and like most people in this community, my tendency most of the time I use my phone is to be watching closely and be analytical about how well it performs. For a regular user it may be just fine, but I may have higher expectations, which this cursed sd665 doesn't match somehow, although the optimizations applied. Compared to a 625 for instance, it can pull off tasks faster, like compressing stuff, loading heavy apps, running benchmarks, but still a 625 feels smoother at times, having less jitter. So I guess the division of performance and ui rendering flutter makes in their docs, also applies here. It's not dramatically bad though.
My judgement about Aves was made inside this context (I hope I managed to do this well enough). Other gallery apps written in Java/Kotlin have pretty smooth scrolling, thus I thought something might be off here. After reading the issue you linked though, and observing how descriptive of my situation it is, I realize how the situation is. I thought to try another app made in flutter, to investigate a bit, so I tried [BlackHole](https://github.com/Sangwan5688/BlackHole) and my finding is interesting, I think. While scrolling still appears kinda intermittent, those "intermissions" are much shorter. The interesting thing though is that friction is a lot more fluid. Scrolls end very slowly and smoothly. I realize though that the two apps project different content. Still, this got me a bit curious.
I hope your effort on this will pay off, but since the factors are the aforesaid, any output will be fine. It's not a major thing in a gallery app anyway, I think.

**Comment by deckerst** [comment]
Thanks for the details. I checked BlackHole and their code. They use the kind of physics that replicate iOS scroll. The most obvious sign is the bouncing on overscroll, but the slippery scroll is part of it too. So more fluid, but not faithful to Android. For now, I prefer to stick to the inaccurate Android replica than use the iOS replica.

There's also a difference of memory pressure: Aves scrolls through many images that together cover the whole screen, while BlackHole scrolls mostly through text, with one thumbnail per row.

**Comment by tsiflimagas** [comment]
Hmm I see, thanks for the explanation. Well, it's your call. I hope there are other actions that can be taken on this issue.

**Comment by tsiflimagas** [comment]
So, I installed v1.5.6 from GitHub, and scrolling seemed pretty much fine. It got me wondering what happened, and I noticed that the build available on f-droid has armv7a libs. I never thought this could make such significant difference, so I thought to go back to it and try again, and to my surprise that felt fine too. So, it was maybe my device acting weird at that time, maybe dexopt hadn't run, some other coincidence, or I'm just frivolous.
I can say performance and fluidity don't seem to differ much from stock AOSP gallery or others, if not at all. So the only little thing left in this issue is the matter of friction. It's not so bumpy at the end of the scroll any more, as I had described, it just has a weird little effect as if it clicks into place at the very end of the movement. Rather insignificant I'd say, but it looks a little weird. Considering what you said about friction, I don't know whether there's any adjustment that could be done on it from your side (and not Flutter's), without moving away from the Android replica. If not, it's really fine, using this app is pleasant anyway, and this issue could be closed.

**Comment by deckerst** [comment]
> the build available on f-droid has armv7a libs

The build on the Play Store is distributed as an AppBundle, and the full APKs are attached to the GitHub releases, but the build on F-Droid is a partial one, only for armv7a, to fit the APK size constraint of IzzyOnDroid.

> So, it was maybe my device acting weird at that time, maybe dexopt hadn't run, some other coincidence, or I'm just frivolous.

Was it maybe the first time you run the app, and it was still scanning your media files? When many files should be scanned, it happens in a foreground service (in theory it shouldn't affect the main app performance). When only a few files need to be scanned, it happens within the app (in theory it should be quick).

> as if it clicks into place at the very end of the movement

I noticed the same thing. It doesn't bother me enough to spend time on it, but I agree that it should be fixed together with the friction issue.

But I noticed something else while scrolling: sometimes it looks like there is a jump, not because of performance, but as if there was an ambiguity in the scrolled position. I can trigger the jump when grabbing the scrollbar thumb in some specific situations, but I believe it also happens when scrolling by fling. I'll keep this issue opened to remind me to take a closer look at this.

@D3ZOXY you upvoted this issue. Do you experience some performance lag? Or is it just the friction issue?

**Comment by D3ZOXY** [comment]
> You upvoted this issue. Do you experience some performance lag? Or is it just the friction issue?
Yes, I noticed that the application has become a little slower to work. Most likely because of the new implementation of file thumbnails.
I was on android 10, recently upgraded to 11, now it seems to be working fast.

**Comment by tsiflimagas** [comment]
> Was it maybe the first time you run the app, and it was still scanning your media files?
I surely opened and closed the app a few times, but who knows, perhaps it was still something related to it.
> sometimes it looks like there is a jump
I just noticed this, but could only reproduce it 1-2 times. 
> I'll keep this issue opened to remind me to take a closer look at this.
Sure ;)

**Comment by deckerst** [comment]
The scrollbar jump seems related to this [flutter issue](https://github.com/flutter/flutter/issues/25652), but I found a workaround.
