### ISSUE TITLE
Always duplicate that actually not

### ISSUE THREAD

**Issue by AdityaMH** [deckerst/aves#1230]
**Describe the bug**
Every image or video from extracting, downloading, or from whatapp and another social media apps always show duplicated in aves collection that actually not in other image or file manager and delete one of them will remove all duplicate file.

**Screenshots**
![Screenshot_20241009-043922](https://github.com/user-attachments/assets/fcd463d8-7f11-401e-a879-7e7595bd2e7a)

**System information and logs:**
Android 13, lastest version

**another context**
Only reinstall aves again to bring back to normal, but this bug will happen again when added new image or video.

**Comment by deckerst** [comment]
- #234
