### ISSUE TITLE
Feature for Multi-Selection in Single/Fullscreen-View

### ISSUE THREAD

**Issue by bjspi** [deckerst/aves#1231]
Hi deckerst,

to make your Gallerie app even more powerful and feature-rich, this feature would really help to simplify a few things for me.

My idea / feature-wish would be that it is possible to create a user-selection of multiple elements (photos or videos) while viewing every media element one by one in "full" mode. **The motivation behind this is: If one has several shots/photos of the same scene, e.g. a person, it's really only possible to select the "best shot" while looking at it in full view because there you can detect the slight nuances and differences.** Being able to swipe left/right in full mode and than add an element to the selection would be highly appreciated!

This would help for a few things and workflows during organization of photos: For example to copy a specific selection to a new album, or share a specific selection of photos to a 3rd party app like Whatsapp etc... 

**Is your feature request related to a problem? Please describe.**
It's not directly related to one specific problem, but if added, it could solve one problem (the one of "slow" deletion / moving of files).
This way, one could first create a selection of all media-entries to be deleted while browsing and afterwards delete them in one shot.

**Describe the solution you'd like**
It would be awesome to have a small checkbox/toggle at the upper or lower right corner within the single-element view to be able to add/remove it to an selection. When going from the full-view to the media overview, the selection should be maintained/kept.

**Additional context**
In Telegram, such a selection within full-view is implemented and could be seen as a reference on how an implementation could look like. If you attach elements there for sending to a contact, you are presented with a media overview. Upon clicking on an element, the full-view is opened, and in the upper right corner there's this toggle to add this element to a selection.

Thank you very much for consideration!

**Comment by deckerst** [comment]
I'll properly read and answer later, but just so you know there's already some related feature which can help in some cases: when you are selecting items in the Collection page, you can tap in the lower right corner of a thumbnail to show the full screen viewer and then continue your selection there.

**Comment by bjspi** [comment]
Damnit, how did I miss this one. This is awesome! It's pretty close to what I was suggesting and incredibly helpful!

**Comment by deckerst** [comment]
It seems the selection process I explained in my earlier comment fits your feature request. Shall I close this or you see some workflow that requires something else?

**Comment by bjspi** [comment]
> It seems the selection process I explained in my earlier comment fits your feature request. Shall I close this or you see some workflow that requires something else?

Yes, I haven't played around with it in depth, just tried it shortly after your first post - but yes indeed, it really looks like it. So I think we can close here.
