### ISSUE TITLE
Video player cannot play high-resolution videos, and would not show the subtitles.

### ISSUE THREAD

**Issue by sheesh3178** [deckerst/aves#1236]
[Video](https://nyaa.si/view/1728426)
Device: Realme C51

The built-in video player struggles to play the video smoothly, and it also won't show the subtitle that's already in the video file.
![Screenshot_20241011-152147](https://github.com/user-attachments/assets/1da3a1a9-fa3e-4429-a7a9-fcafc115540f)

I tested the video file to MPV (currently the smoothest video player I've ever tested and used, it can play 1440p no sweat on my phone) and it played perfectly without noticeable quality loss. (well maybe other people would notice a quality drop but I definitely didn't) Also the subtitle shows which is great.

In the app, I tried switching hardware acceleration to on and off, tried turning off battery saver, and restarting the phone, and nothing changed. I know this app is not focused on video playback, but it would be nice to get it fixed.

**Comment by deckerst** [comment]
For the subtitles, aren't they listed in the tracks (viewer ... menu > Video > Select tracks)?

For smoother playback, did you hide the overlay (with a tap anywhere on the viewer)?

**Comment by sheesh3178** [comment]
Yeah I did. Nothing changed.

**Comment by deckerst** [comment]
And the subtitles, are they listed in the tracks?

**Comment by sheesh3178** [comment]
Sorry, what do you mean by track?

**Comment by deckerst** [comment]
![Screenshot_20241011-102039~2](https://github.com/user-attachments/assets/56f056ca-ab19-40f3-b977-fb7bc802402e)

**Comment by sheesh3178** [comment]
Oh, so you do need to set it yourself. That's pretty cool.

**Comment by sheesh3178** [comment]
Wait that's actually so good, MPV definitely doesn't have that and other
popular video players for Android (only for subtitles at least) so that's a
plus. I literally just deleted 2TBs of videos just because it was in
another language, not knowing I need to change the audio track which was
not a feature in any video player I've tested.

That said, the video player really needs a fix. At this point, I don't even
know if I'm viewing a non-HD video smoothly.

**Comment by deckerst** [comment]
Duplicate: 
- #811 
- #1043
