### ISSUE TITLE
Firebase in a Libre Release?

### ISSUE THREAD

**Issue by Scrat80** [deckerst/aves#1237]
**Describe the bug**
Using Firebase in a libre release of Aves

**To Reproduce**
Code an app and include it.

**Expected behavior**
Nothing of Google should be in it.

Let me know when it's removed.

**Comment by deckerst** [comment]
It's not in the libre flavour.

**Comment by Scrat80** [comment]
Where is it then? Cause I got the APK off here and it was listed in the disclaimer.

**Comment by Scrat80** [comment]
![Uploading Screenshot_20241012-223956.png…]()
![Uploading Screenshot_20241012-224049.png…]()

**Comment by Scrat80** [comment]
![Screenshot_20241012-223956](https://github.com/user-attachments/assets/8ae32735-fc3c-43b7-a221-1a388fbf8b3e)
![Screenshot_20241012-224049](https://github.com/user-attachments/assets/f391c1d1-5c8b-4b9f-a9b9-545b36569cda)
