### ISSUE TITLE
Google Play Store: v1.11.16 "not compatible with device" [LineageOS 21]

### ISSUE THREAD

**Issue by akki42** [deckerst/aves#1239]
**Describe the bug**
I am using two devices with LineageOS 21 (=Android 14), a Google Pixel 4a 5G and a Samsung Tab S5e.
On both these devices, installation and updates of aves were possible via Google Play Store up to v1.11.15.

The (automatic or manual) update to v1.11.16 via Play Store failed. Play Store now shows "This [smartphone / tablet] is not compatible with your device."

(Still installed v1.11.15 is working fine.)

**To Reproduce**
1. Go to 'Aves Galerie' in Google Play Store on affected devices / ROMs
2. See notice

**Expected behavior**
Aves should be available for installation / updates on such devices.

**Screenshot**
![image](https://github.com/user-attachments/assets/9a1c22ff-e79c-4f19-9f3e-e166c783c466)

**System information and logs:**
System information from Google Pixel 4a 5G:
```
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.15-play, build 134
Flutter: stable 3.24.3
Android version: 14, API 34
Android build: lineage_bramble-userdebug 14 AP2A.240905.003 650f04cc2c
Device: Google Pixel 4a (5G)
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: de_DE, en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/
Error reporting: false
```
System information from Samsung Tab S5e:
```
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.15-play, build 134
Flutter: stable 3.24.3
Android version: 14, API 34
Android build: lineage_gts4lv-userdebug 14 AP2A.240905.003 137f708a2c
Device: samsung SM-T725
Support: dynamic colors=true, geocoder=true, HDR=false
Mobile services: ready
Connectivity: wifi
System locales: de_DE, en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/
Error reporting: false
```

**Comment by deckerst** [comment]
I think it's related to a security setting I enabled in the Play Store console, which prevents "unsafe" devices to install the app. It's not due to Aves code itself. 

So I was wondering what kind of devices are "unsafe" according to the Play Store. Are your devices rooted or anything special beyond using a custom ROM?

In any case, thanks for letting me know. I'll disable this security setting on the store.

**Comment by akki42** [comment]
Thank you, Thibault!

My devices are not rooted. But custom ROM devices will not pass "Play Protect" - unless (i) rooted and used with Magisk or (ii) the custom ROM itself bypasses the integrity checks (which [LineageOS does not](https://lineageos.org/PlayIntegrity/)).

**Comment by deckerst** [comment]
I'll just keep this open for now.

I tried to find the setting to disable it, to no avail. I'll try again from my laptop later.

**Comment by deckerst** [comment]
Ouch:
https://support.google.com/googleplay/android-developer/thread/231487794?hl=en&msgid=231621465

Need to check whether it's possible if requested by email.

**Comment by deckerst** [comment]
I disabled the integrity check. Not sure whether the change is applied right away though. Could you try again and let me know?

**Comment by akki42** [comment]
Thank you, Thibault!

One of my devices (Pixel 4a) already shows the update as available in Play Store. I will let you know in case the other (Tab S5e) does not follow suit.
