### ISSUE TITLE
Firebase in libre release.

### ISSUE THREAD

**Issue by Scrat80** [deckerst/aves#1240]
Describe the bug
Using Firebase in a libre release of Aves

To Reproduce
Code an app and include it.

Expected behavior
Nothing of Google should be in it.

Let me know when it's removed.

![Screenshot_20241012-223956](https://github.com/user-attachments/assets/f7b19b59-7e26-45d3-b670-7629d7e29087)
![Screenshot_20241012-224049](https://github.com/user-attachments/assets/1bfec383-8ac1-4c51-ab12-abba94515c3a)

**Comment by deckerst** [comment]
Again: Aves libre does not include Firebase.

The privacy policy is the same for all flavours of Aves.

Please don't create multiple issues for the same thing. I don't mind banning obnoxious people.
