### ISSUE TITLE
Unable to add hidden paths

### ISSUE THREAD

**Issue by noearchimede** [deckerst/aves#1242]
It's very well possible that this is not a bug, in which case please excuse me for opening this issue.

The issue/question is that after upgrading to v1.11.14 (by the way, thanks for adding the ability to toggle hidden paths!) I've been unable to add new hidden paths. Previously there was a "add path" button at the end of the "hidden paths" tab in "privacy → hidden items", but I can't find its equivalent now...

In case I just missed the obvious answer this is obviously not a bug, but in that case I would ask if you'd consider adding that  button back. I think it would make sense to have the ability to add, toggle and remove hidden paths all in the same place.

Thank you for your attention and for your great work on Aves!

**Comment by deckerst** [comment]
It's still possible, via the Explorer page. You browse to the path you want to hide, and select hide in the top right menu.

**Comment by noearchimede** [comment]
Thank you! I suspected I might be missing something obvious. The explorer page was hidden in my setup and I didn't know it existed.

Just to make you aware, I am quite confident that I did not hide the explorer page manually, so it must have been hidden since I installed the update. If you intended it to be visible unless explicitly hidden by the user there might be a small bug somewhere.

**Comment by deckerst** [comment]
Not __really__ a bug. For new installs, `explorer` is by default in the navigation drawer. But upgrading generally does not modify settings, so the `explorer` option wasn't there in the navigation drawer of existing users who upgraded from an old version that didn't have that feature.
