### ISSUE TITLE
Empty albums do not save after force close

### ISSUE THREAD

**Issue by An-anonymous-coder** [deckerst/aves#1248]
**Describe the bug**
When you create a new album and then force close the app, the album goes missing but the app still thinks it's still there. 

**To Reproduce**
1. Open Aves
2. Go to "Albums"
3. Tap the three dots
4. Select "Create album"
5. Name the album anything. I named mine "Test" for clarity.
6. Click "CREATE"
7. Force close Aves
8. Open Aves
9. Go to "Albums"
The album you created is missing. This does not happen until you force close Aves.
10. Tap the three dots
11. Select "Create album"
12. Try to enter the name you had before. Mine was "Test"
It will say "Directory already exists", despite the album not showing up.

**Expected behavior**
The newly created albums should show up.

**Comment by deckerst** [comment]
Empty albums not being kept on relaunch is by design. However, preventing you from creating an album when the folder exists on storage is indeed a bug.
