### ISSUE TITLE
Share sheet images cannot be copied to Aves

### ISSUE THREAD

**Issue by An-anonymous-coder** [deckerst/aves#1249]
**Describe the bug**
When you share an image to Aves through the share sheet, you can't copy it to an album.

**To Reproduce**
1. Find an app that has shareable images. This could be done by searching for an image online and long pressing it to share.
2. Open the share sheet for that image
3. Select "Aves"
4. Tap the three dots
5. Select "Copy to album"
6. Select an album to copy to
It will say "Failed to copy 1 item"

**Expected behavior**
The image should be copied to the album you selected

**Additional context**
It would be nice if images shared to Aves get automatically downloaded. I can open a feature request, since there is no option under "Export"

**Comment by deckerst** [comment]
I've just tried it and `copy` worked in my case.
Could you try again, and at step 4 instead of copying go to the `Info` page, take a screenshot of that page and attach it here?

**Comment by deckerst** [comment]
And please paste your system info and logs from `About` > `Bug Report` (best is to save the logs right after you get the issue).

**Comment by deckerst** [comment]
> This works, but won't save it to the device, though.

Sorry for the confusion. I meant `copy to album` worked (not `copy to clipboard`).

Anyway, thanks for following up. I'll take another look.
