### ISSUE TITLE
Fast Seek by Holding Gesture

### ISSUE THREAD

**Issue by PytatoDuck** [deckerst/aves#1252]
It would be a great addition if the **Video Player** could support fast-seeking by holding down on the screen (_like YouTube_).

**How it works:**
- When the user holds their finger on the screen during playback, the video temporarily plays at a faster speed (`2x`).
- The fast-seek **speed** could be changed in the settings for preferences.
- The playback speed returns to normal if you are not holding the screen anymore.

> This feature would make it easier to skim through videos efficiently without needing to use the seek bar repeatedly.

**Comment by PytatoDuck** [comment]
I just realized someone already said this #262

**Comment by deckerst** [comment]
Indeed, duplicate it is:
- #262
