### ISSUE TITLE
Different sort methods for each albums.

### ISSUE THREAD

**Issue by dontknowhy** [deckerst/aves#1262]
**Is your feature request related to a problem? Please describe.**
_I'm not an native English speaker but translators always bad at translating Chinese to English. Sorry!_
I have about 20 different albums due to my amazing Chinese apps' different stategies to sort pics. (eg. Image_UNIX timestamp or bili_UNIX timestamp)
Although they might use UNIX timestamps, but their custom albums didn't ordered in a right way and I often need to change the sort method to adapt this situation.
**But this setting is for every albums!**

**Describe the solution you'd like**
So Aves might need to store this settings in every albums so I can always use different methods for different apps

**Describe alternatives you've considered**
nope

**Additional context**
Chinese version if you can't understand Chiglish:
```
我有大概20多个由中国知名app创建的以不同方式命名文件的相册。（例如用 Image_UNIX时间戳或者 bili_时间戳之类的……)
虽然看起来好像很好排列，但是Aves总是没法正常排列它们导致我需要经常更改排列方式。
但是这设置是应用到每一个相册的而我不是每个相册都需要用添加/修改时间排列的。

所以Aves貌似需要分别存储这些排序设置我才好正常看相册……
```

**Comment by deckerst** [comment]
Duplicate: 
- #207
