### ISSUE TITLE
RAW / DNG File type support 

### ISSUE THREAD

**Issue by Zidane5929** [deckerst/aves#1266]
RAW pictures don't seem to load correctly on AVES.

Adobe Lightroom (Mobile) supports RAW pictures. Could something be implemented to support RAW pictures 

For further discussion I am willing to provide a comparison screenshot of a RAW image on AVES and Lightroom.

**Comment by deckerst** [comment]
For image support, the app relies on the codecs on the device (except for Tiff and SVG), and I don't intend to ship with extra codecs.
