### ISSUE TITLE
The ability to add specific folders to view/ability to view hidden folders using Aves Libre

### ISSUE THREAD

**Issue by Libre-Software** [deckerst/aves#1267]
**Is your feature request related to a problem? Please describe.**
I would like the ability to manually add folders to view in Android. 

The problem is primarily with WhatsApp. For some reason, the pictures and videos you send are stored in folders that most gallery apps don't have access to.

I would like the ability to see, and sort those images and videos as well.

**Describe the solution you'd like**

I'm guessing the ability to specifically mention which folders you want to include should/maybe resolve the issue.

**Describe alternatives you've considered**

Fossify Gallery does give you the ability to manually add additional folders to view and that seems to have resolved the issue for me.

 What I have done is in Settings -> Manage Included Folders; I have navigated to and selected /storeage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Video/Sent & /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/ WhatsApp Images/Sent

I would also like the ability to view them in Aves Libre.

**Additional context**

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/wiki/FAQ#can-aves-display-media-inside-hidden-folders
