### ISSUE TITLE
Feature Requests: Improved Sorting, UI Enhancements, Metadata Retention, and Performance Boost

### ISSUE THREAD

**Issue by MisterKHUBAIB** [deckerst/aves#1277]
1. Manual Sorting for Albums
Please add an option to let users manually sort albums to organize them as desired.

2. Manual Sorting within Albums
Provide the ability for users to manually arrange photos and videos within each album, allowing for personalized media ordering.

3. Option to Hide Vaults
Add a feature to hide specific vaults, giving users more control over which content is displayed and helping maintain privacy within the gallery and a clutter-free view.

4. UI Redesign for Album Headers
Update the album header design to look more refined. Currently, it displays “Collection” at the top, with the album name in an oval shape below, along with a cross icon. A simplified design with the album name displayed alongside “Collection” (instead of the oval and cross layout) would improve the app’s overall aesthetic.

5. Streamlined Access to Export Options in Viewer
In the viewer mode, make the “Export” option directly accessible with a single tap on the three-dot menu. Currently, accessing the “Export” options requires an extra step, which complicates setting wallpapers or performing similar quick actions.

6. Improved Dynamic Thumbnail Interaction in Viewer
Enhance thumbnail interactions below quick actions in the viewer. Currently, the main view updates only after the user stops sliding through thumbnails. The app should instead dynamically preview photos or videos as the user slides across thumbnails, similar to the smooth interaction seen on iPhones.

7. Retain Favorites in Metadata
Include favorites (heart icons) in the image metadata so that when photos are shared with other devices, they retain their “favorite” status. This would make it easier to track selected photos across devices.

8. Performance Optimization for High-Resolution Images
Improve the loading speed of high-resolution images, particularly 64 MP photos, which currently load with a brief blur for 2-3 seconds before becoming fully clear. Apps like Google Photos display these images instantly on the same device, so optimizing for faster loading would enhance user experience.

**Comment by deckerst** [comment]
- #234
