### ISSUE TITLE
连拍

### ISSUE THREAD

**Issue by qzdxj** [deckerst/aves#1289]
手机原相机拍的照片在原相册只有一张照片，但在Aves里却是一张一张的图片![Screenshot_20241112_073549.jpg](https://github.com/user-attachments/assets/ff55b752-9ede-4d9e-a5ff-d1c0b6c3e7c5)

![Screenshot_20241112_073559.jpg](https://github.com/user-attachments/assets/59764c52-f81d-4378-9092-a3379453eeb9)
我希望可以把Aves也改成原相册那样的一张照片

**Comment by deckerst** [comment]
Please fill the report template sections and provide the system info as requested. If you keep opening incomplete reports, I won't mind banning you.

Please provide a sample burst too. Original files with original names.
