### ISSUE TITLE
UI enhancement: Remember "title filter" presence

### ISSUE THREAD

**Issue by FLAGEL** [deckerst/aves#1292]
Please consider having Aves remember showing/hiding the "title filter" per view (e.g. in _Albums_ and _Tags_, but not in _Collection_ if so configured by the user) between app exits/starts. As it stands, exiting Aves will have the "title filter" revert to default (i.e. disappearing).

Thanks!

**Comment by deckerst** [comment]
There's already a hint of that. It remembers in some cases but I forgot which ones (and I'm away from computers). If my memory serves me, for now it's only remembered for album picking.

**Comment by FLAGEL** [comment]
I am on Aves 1.11.17. Opening the thee dot menu, and selecting "Show title filer" will show the title filter, but after exiting/starting Aves the "title filter" is gone. I have tried this in the _Albums_, _Tags_ and _Collection_ views.

**Comment by deckerst** [comment]
It now remembers for the following pages:
1) lists:
- Collection
- Albums
- Countries
- States
- Tags
2) picks:
- Item pick (Collection variant)
- Album pick (Albums variant)
