### ISSUE TITLE
In Viewer, only one line worth of tag information is shown

### ISSUE THREAD

**Issue by FLAGEL** [deckerst/aves#1297]
In _Viewer_, when a media item has tag(s) that (together) are longer than what fits onto the display as one line, only partial tag information is shown to the user. A possible fix would be to intoduce a line break to show complete tag information.

Thanks!

**Comment by deckerst** [comment]
In that case, tap on the top overlay, and it will switch between one line / multiple display. Works also for long titles, descriptions, etc.

**Comment by FLAGEL** [comment]
That's great! However, would it be possible to have a global setting for the user to select the default behaviour between one line and multiple lines? As an example, if a media item has 4 tags, and the first 3 are sufficiently long on their own to hide the 4th tag, it will require the user to press the top overlay every time they enter the viewer.
