### ISSUE TITLE
Flie is getting corrupted / unplayable /broken frequently 

### ISSUE THREAD

**Issue by Emad-341** [deckerst/aves#1301]
I would give them 5.But every time I try to move or cut sometimes it gets stuck on 10% and couldn't close operation and I lose the photos videos forever. I thought it was one time issue but it is happening again again again. I close every app, stop battery saver only open this app and move photos and videos. But I lost many precious photos which I can't recover again.

[2aves-logs-20241117_130326 002.txt](https://github.com/user-attachments/files/17789202/2aves-logs-20241117_130326.002.txt)

Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.17-play, build 136
Flutter: stable 3.24.4
Android version: 11, API 30
Android build: RKQ1.200826.002 test-keys
Device: Xiaomi Redmi K20 Pro
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: en_GB
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Download/Aves/, /storage/emulated/0/MIUI/, /storage/emulated/0/Download/AllVideo/, /storage/emulated/0/Download/InstaPro/, /storage/emulated/0/Android/media/
Error reporting: true

**Comment by deckerst** [comment]
Thanks for the report.

Moving or deleting is a slow operation (because Aves does not have direct access to files), and it takes more time for larger files (especially videos). So it's normal that it takes time, but it's not normal that data gets corrupted.

Does it happen with images, videos, a specific type?

Can you reliably reproduce the issue?

Can you provide steps to reproduce the behavior? If you can provide a screen recording it could help too.

**Comment by Emad-341** [comment]
I don't have files to move now. It was stuck on 10%. I waited 20 minutes thought since it was copying huge files it needs time but even if I try to cancel operation it doesn't cancel.

**Comment by deckerst** [comment]
I cannot investigate this issue without responses to the questions above. 

And for moving large files, it's better to use file manager apps, as they have direct access to files.

**Comment by Emad-341** [comment]
I don't have files to move and I didn't screen recorded it. But it was stuck on 10% for quite a while. Tried cancel but it was not working either.

**Comment by deckerst** [comment]
> I don't have files to move

Can't you take pictures and videos with your device?

Without further details and answers to the [questions above](https://github.com/deckerst/aves/issues/1301#issuecomment-2481398389), I won't be able to investigate the issue you experience.
