### ISSUE TITLE
Video edit issue - hangs with loader over the screen

### ISSUE THREAD

**Issue by artem-tarasenko** [deckerst/aves#1305]
**Describe the bug**
Cannot shorten the video's length in the editor screen. When I set a new timeframe and press "save as a copy" the loader overlay pops up and nothing happens.

**To Reproduce**
1. Open videos collection
2. Pick any random video (22 sec in my case)
3. ...edit - set a new timeframe - save as a copy
4. See loading spinner as if the process work but it never disappears 

**Expected behavior**
Wait for it to finish, spinner disappears, UI unblocks

** Screenshots **
![Screenshot_20241118_184155_Photos](https://github.com/user-attachments/assets/50407794-2c88-44b4-a639-23cd21e2a7d3)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.17-play, build 136
Flutter: stable 3.24.4
Android version: 14, API 34
Android build: UP1A.231005.007.S918WVLU4CXI5
Device: samsung SM-S918W
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: ru_RU, en_CA
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: false

[aves-logs-20241118_184218.txt](https://github.com/user-attachments/files/17808612/aves-logs-20241118_184218.txt)

**Additional context**

**Comment by deckerst** [comment]
Aves does not include a video editor. It forwards to editing apps installed on your device.

**Comment by artem-tarasenko** [comment]
Wait, what? Forwarding where? I don't recognize that UI (surely not the default app) and it looks like it is still Aves. I also haven't found any settings specifying editing applications.

Can you give a little more details about that before closing it?

**Comment by deckerst** [comment]
When you press "edit" in Aves, it tells the OS it wants to edit an image/video, and the OS looks for apps that can handle it. If there's only one app that can do it, it opens that app right away.

If there are several apps that can handle it, it shows a dialog that lets the user choose which app and whether to use this app "always" or "only once". That dialog is a standard OS dialog. If you choose "always", it will not prompt you again in the future and use that app without asking.

I don't know in your case whether 1) you have just one video editing app, or 2) you have several but in the past you used one of them and pressed "always".

I can't help you identify which editing app is used. It could be the default gallery editor, Google Photos editor, etc.

**Comment by deckerst** [comment]
To identify the available apps for the editing intent, maybe you could use that app as interceptor: https://www.f-droid.org/en/packages/io.github.muntashirakon.AppManager/

**Comment by artem-tarasenko** [comment]
Ah I see, thanks for the detailed response.

The source of confusion for me was the absence of a dialogue to choose the editor. I'm pretty sure I didn't pick any options first time I opened the app, not to mention the option "always" (not my habit, but just in case I re-installed the app and checked editing once more - there was no dialogue.

I found out, however, where the "edit" was transferred by by opening a video via the default file manager (there was no default option, so I picked all options one by one) - it is a google picture.

After that I picked a default (proper) video player as a default option ("always" open with..) and get back to the app to see if it will use my choice to edit a video - and it didn't, again tried to open with google pics. Is there any way to resolve that?

Thanks.

**Comment by artem-tarasenko** [comment]
Here is the video of the first launch of the app.
https://github.com/user-attachments/assets/5ad4dc52-ee83-4986-8f57-775d2ff79543

**Comment by artem-tarasenko** [comment]
Alright, with your help I figured out why G.Photos was unable to edit videos - since I've never used it the app didn't have permissions, now when I started checking things I gave the permissions and an issue with editing kind of solved, but... 

I don't like it and I don't want G.Photos for this role, so I checked the settings as you pointed out:
- found Photos and reset defaults
- re-opened Aves
- checked editing - but still no luck, it opens Photos without asking me anything.

Even though it doesn't seem like an Aves problem, it is annoying and somewhat related. With your help, I solved my issue, but I'll gladly help you with this situation if you want to find the root of the problem, and why things work not exactly as intended.

**Comment by deckerst** [comment]
It is very likely that Google Photos is the only app able to edit videos on your device. In that case there is no dialog prompting to choose, because there is no choice.

**Comment by artem-tarasenko** [comment]
It was, I deleted it and Aves said "there are no apps to edit", which doesn't make sense, because I have a default app for that, plus I've installed a few more - GoPro Quik, Adobe Express and a bunch of project-based apps. Could it be the "intent" is somehow different...?

**Comment by deckerst** [comment]
These apps probably don't declare being able to handle that intent.

Sometimes it's on purpose, so that they can control who/how their editor is used. For example Samsung Gallery editors are great but they can only be used by Samsung apps.

Sometimes it's not on purpose, but the developers just didn't properly write the handled intents in the app manifest. If your app of interest is open-source, you could ask them to fix it.

**Comment by artem-tarasenko** [comment]
I don't have any specific preferred app for that, it's just the Photos is quite limited... I guess I have no choice but to try as many as I can hoping to find something suitable, keeping in mind the only working alternative so far (Photos). This is so troublesome.

Anyways, thank you again for helping me and all the explanations, appreciate it.

**Comment by deckerst** [comment]
Sometimes there is an alternative to using the "edit" intent: using the "share" intent. It's not as well defined, as receiving apps could do whatever, not only editing.

But I suggest this because an editing app I like is [img.ly](https://play.google.com/store/apps/details?id=com.photoeditorsdk.android.app). After installing it, if in Aves you press "edit", img.ly *is* listed among editing apps, but it fails when used that way. However, if you share the video to that app, you can use it for editing.
