### ISSUE TITLE
Video audio filled with static noise

### ISSUE THREAD

**Issue by Redmatzh** [deckerst/aves#1309]
**Describe the bug**
Recently (since 1-2 weeks) video audio is filled with static noise. At first i thought it could be bc of my device speakers but when i try to open the same video in different app like vlc there's no issue. Videos are in mp4 format

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.17-play, build 136
Flutter: stable 3.24.4
Android version: 14, API 34
Android build: AP2A.240905.003
Device: Google Pixel 7 Pro
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: en_GB, en_US, tr_TR, de_DE
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: false
[aves-logs-20241121_133043.txt](https://github.com/user-attachments/files/17845867/aves-logs-20241121_133043.txt)

**Comment by deckerst** [comment]
Thanks for the report. Could you please provide a sample video that has the issue?

**Comment by Redmatzh** [comment]
https://github.com/user-attachments/assets/242c40d2-9cbc-4c30-896d-97c74bf47217

**Comment by deckerst** [comment]
I got the video you shared and indeed when I play it on my device with Aves v1.11.18 there are no static. The one I got from you is 1080x1920 H.264 video with AAC audio. Maybe the video was transcoded when uploaded. 

One thing you could do on your device is to install the [MPV player](https://play.google.com/store/apps/details?id=is.xyz.mpv) and check whether your video plays fine with it. Aves uses a package that relies on the MPV engine for video playback.

**Comment by Redmatzh** [comment]
I just tried with that app. Videos were working completely fine, audio normal no static

**Comment by Redmatzh** [comment]
I tried it using that app, videos were completely fine, no static whatsoever. But i decided to reinstall the app to see it will fix it. Will let you know

**Comment by Redmatzh** [comment]
Update: don't know what happened, i didn't do anything but it's back to normal. Im guessing it was something to do with Android bc i see that the app is still on the same version
