### ISSUE TITLE
A way to view hidden albums other than going to settings alone

### ISSUE THREAD

**Issue by lalalasupa0** [deckerst/aves#1311]
I may be typing too much, but I just let whatever goes through my head flow
I know that the point of hiding is for it to not be so easy to access, but I don't think it has to be so limited either all the time, and anyway I would like what I propose to be optional at the same time (and it certainly would with the 1st solution here)
Also, come to think of it, I don't see how to hide vaults from the 'Albums' space this way either... lol

**Is your feature request related to a problem? Please describe.**
Having to go to settings and unhide albums to access their content in the app is pretty annoying, more so if I only want to view some media quickly and not to use another app to do so, and so far I haven't found any other way to do this

**Describe the solution you'd like**
The first thing that came to my mind is for there to be a space in the navigation menu for the hidden albums, and to lock the access to that space with the lock type "system default"

The lock type thing also made me thought of a feauture like Samsung Gallery's albums lock, [but](https://github.com/deckerst/aves/issues/114#issuecomment-950048708) ('would be a letdown if at the end this is also not considered for the same reason)

**Describe alternatives you've considered**
Another idea would be to simply add an option on 'View' in the filters under 'Albums' within the three little dots at the top right to show the hidden albums or to _only_ show the hidden albums and not the non-hidden ones

The lock thing reminds of the vaults, but I don't think it is so convenient because the only way to access them is via Aves, and yeah that's actually cool, but still if I want to share something from another app I would have to take that something out of the vault even if it's just a single media, and that in particular is limited too, in telegram for example if the integrated selector is not used I can only select individually if I use the selector from other apps, Aves included. And any other solution to all that specifically is mostly just a hassle, all this led me to want what I propose with this issue

****
I hope I've thought enough to cover everything hahah
I didn't find another issue that brought up all of this btw, but maybe I didn't look deeply enough

**Comment by deckerst** [comment]
To me there's a tension in your usage:
- you have decided that some images are superfluous most of the time so you hide them, 
- you need them so often that toggling their visibility in the settings is a hassle.

I'm not sure providing extra features will help with this tension.

**Comment by lalalasupa0** [comment]
> To me there's a tension in your usage:
> 
> * you have decided that some images are superfluous most of the time so you hide them,
> * you need them so often that toggling their visibility in the settings is a hassle.
> 
> I'm not sure providing extra features will help with this tension.

I don't deny it, but still

> you have decided that some images are superfluous most of the time so you hide them,

Not necessarily "superfluous", even productivity media can be hidden, the reason behind so can only be assumed

> you need them so often that toggling their visibility in the settings is a hassle.

The same, it would not necessarily have to be often but repetitive over a course of up to hours, and at the end of the day the most relevant thing is why they are hidden, as above

This can also simply be considered of little importance if the above ends up being no big deal, of course

**Comment by Flavelius** [comment]
I also would like to have a way to more easily access hidden albums/tags. My usecase is giving others my phone just for viewing a few images in my 'public' gallery. But whenever i take a picture that should end up in the non-public gallery, i have to go to settings and unhide the album or tag and only then can i move images there, after which i have to re-hide it.
I think a good solution would be either allowing images to be moved into a hidden album, or to allow filtering albums in the 'All Collection' view, or just unhiding a tag by long-pressing it (currently it always just shows the "hide" menu entry, even when it's already hidden).

**Comment by deckerst** [comment]
> currently it always just shows the "hide" menu entry, even when it's already hidden

@Flavelius How do you see the tag chip if it's hidden? In which page?

**Comment by Flavelius** [comment]
I had a look, and it looks like i misnamed it, it's actually just the album name (i had tags and an album with the same name for testing).
I added a custom entry to the navigation bar for the 'private' album.
When i hide the album, the navigation bar entry atleast stays visible. 
When i enter it, it doesn't show any images (which is fine) and the top search-bar-thing shows the name as filtered entry. This is what i can long-tap.

**Comment by deckerst** [comment]
I see. I hadn't thought about it, but adding "unhide" in that context menu would make sense. Thanks for the suggestion.
