### ISSUE TITLE
Don't necessarily obtain date and time from XMP (?)

### ISSUE THREAD

**Issue by lalalasupa0** [deckerst/aves#1312]
**Is your feature request related to a problem? Please describe.**
I'm quite confused myself, but I don't think it's actually that hard to understand what I mean, I'm just having problems with the *date and time* of my image(s)

I know it might be intended to be that way, but it seems pretty inconvenient for media saved from different sources and when it's a serie of images like 1,2,3 that should have a date and time following that ennumeration but don't (**in the XMP dates**)

![IMG_20241122_095650](https://github.com/user-attachments/assets/7d8b496b-adbc-4d7d-b389-0a40db66210b)
* Date and time in Aves' XMP

![IMG_20241122_093445](https://github.com/user-attachments/assets/a7edc418-408d-4d52-9985-6386ad3184ee)
* Date and time in a Files explorer **which is the date and time I want** the image to have for my preferred order in my collection with the 'Sort by' set on date and time

**Describe the solution you'd like**
For it gets the date and time in the same way as that file explorer (I don't know if where the file explorer gets the date and time from has a name like XMP).

**Describe alternatives you've considered**

**Additional context**
The solution of course would be to edit the date and time, but having to do that in the 1st place is the problem for me because of the amount of media I have and how often I get media like that

If that file explorer already does it that way, I can't think why Aves couldn't, making it hard, I really hope this gets done, Aves is my favorite gallery and goddamn I don't want to stop using it for something like this :(

**Comment by deckerst** [comment]
I'm not sure I understand your request, but I'll guess and explain the possible confusion.

File explorers handle files, and they usually use the "file created date" or the "file modified date" as the representative date.

Aves handle media items (photos, videos), and it uses, if possible, the date defined within the media (Exif, XMP, MP4 metadata boxes, etc.) as the representative date.

Aves is a gallery app, so it doesn't have the same access to files as file explorer apps. Aves can edit dates at the media level, but it cannot edit dates at the file level. Also, file dates may change when doing file operations, while the metadata date is under control.

Users who don't understand the difference get confused when they download a photo taken a long time ago. They expect to see a recent date (the downloaded file date), while Aves shows an older date (when the photo was taken).

**Comment by lalalasupa0** [comment]
> I'm not sure I understand your request, but I'll guess and explain the possible confusion.
> 
> File explorers handle files, and they usually use the "file created date" or the "file modified date" as the representative date.
> 
> Aves handle media items (photos, videos), and it uses, if possible, the date defined within the media (Exif, XMP, MP4 metadata boxes, etc.) as the representative date.
> 
> Aves is a gallery app, so it doesn't have the same access to files as file explorer apps. Aves can edit dates at the media level, but it cannot edit dates at the file level. Also, file dates may change when doing file operations, while the metadata date is under control.
> 
> Users who don't understand the difference get confused when they download a photo taken a long time ago. They expect to see a recent date (the downloaded file date), while Aves shows an older date (when the photo was taken).

My last hope goes here: 

> and it uses, if possible, the date defined within the media (Exif, XMP, MP4 metadata boxes, etc.) as the representative date.

From a perhaps silly point of view, would it be possible not to use that data within such things as exif or xmp? I thought that maybe that basic data out of all that exif-like stuff is what the file explorer uses

If not, maybe there is no solution to this other than editing the date and time from Aves? What matters to me is the order of my images, which gets messed up with the weird dates

**Comment by deckerst** [comment]
> the order of my images, which gets messed up with the weird dates

I'm a bit surprised by this. When you sort by date and they have the exact same date in the metadata, they are then sorted by their title (usually the file name, but not always).

**Comment by lalalasupa0** [comment]
> > the order of my images, which gets messed up with the weird dates
> 
> I'm a bit surprised by this. When you sort by date and they have the exact same date in the metadata, they are then sorted by their title (usually the file name, but not always).

Oh? That could help me in my case as I have a series of images, and like 2 of those images have the dates out of order but have the same title simply following a pattern of numbers (1,2,3,etc)
Will it work? Although right now I don't see that effect, as long as it does with the title it's perfect for me, the rest of the metadata is pretty irrelevant to me

**Comment by deckerst** [comment]
Please try it and let me know. For a proper test, please assign the same custom date to all the items (or assign the date of one of the items to all the others). Bear in mind that if you use descending order (i.e. newest first), you'll likely get the title with the highest number first: image3, image2, image1.

**Comment by lalalasupa0** [comment]
> Please try it and let me know. For a proper test, please assign the same custom date to all the items (or assign the date of one of the items to all the others). Bear in mind that if you use descending order (i.e. newest first), you'll likely get the title with the highest number first: image3, image2, image1.

Yup, works as expected
_In a series of 10 files, file number 7 had an old date, after setting the same date and time for all 10 files including 7, they were sorted by filenames_

Now then, I would be fine with sort by date ignoring the date of file 7 and placing it before file 8 by following the filename, I hope you can consider this in particular, although for now the above would be just fine tbh

**Comment by deckerst** [comment]
Do you know you can also sort by name, instead of dates?

**Comment by lalalasupa0** [comment]
> Do you know you can also sort by name, instead of dates?

Of couse, the thing is that dates are more important, and I don't have only series of images but individuals too
