### ISSUE TITLE
Batch convert date and time from file name to the metadata of files

### ISSUE THREAD

**Issue by WaveSmashies** [deckerst/aves#1313]
**Is your feature request related to a problem? Please describe.**
I switched from a Samsung phone to a Pixel and my images and videos in Secure Folder lose their date and time which completely screws up the sorting. I have THOUSANDS of images and videos which would all need to get their date and time changed manually. This is an unbelievable pain I'm sure you can imagine. The problem is, the date is lost the first time when copying the files from one device to another, then lost again when moving them to Private Space on the Pixel phones. Fortunately I can install apps like Aves Gallery within Private Space as well. So if you were so kind as to add this feature, you'd save me tens of hours of just changing dates on more files than I care to count.

**Describe the solution you'd like**
I'd like it to be perhaps included in the Rename menu or something similar and simple. 

**Describe alternatives you've considered**
I can't find anything online unfortunately. This is the closest I can get.

**Additional context**
I'll be honest, it's to move my NSFW material from my old Samsung phone to my new Google Pixel which handles this sort of thing..... poorly. It's frustrating. I would forever appreciate your help! I know for certain I would use this for years lol. Each time I get a new device. I know I'm sticking to Android, but I might go with any different carrier or manufacturer. I'm sure a lot of people that run into something similar would like this as well. Thank you for your time!

**Comment by deckerst** [comment]
If I understand correctly, you already can:
- in the Collection page, select the media items,
- top right menu > Edit > Edit date & time,
- in the date editing dialog, select "Extract from title".

Please note that it can only extract the dates when they are unambiguous and match some specific patterns. You could give it a try and if it doesn't work reply here with a sample title.

**Comment by WaveSmashies** [comment]
So I went ahead and tried this. It KINDA worked. It wasn't perfect. Some files were still pretty heavily shuffled, but most were pretty close to where they belong. I don't know why it happened that way, but it did. But the solution I found that worked perfectly is CX File Explorer on the play store. By starting an FTP server on the device with the files you need, you can access the server on the same app and copy them that way. Then every single date and file metadata is kept exactly how it was. I think I'll still be using the rename to date feature from now on just in case, and I really appreciate your help!
