### ISSUE TITLE
Fallback sorting method using metadata

### ISSUE THREAD

**Issue by mmahmoudian** [deckerst/aves#1316]
**Is your feature request related to a problem? Please describe.**

I recently changed my phone after some years and use the Android built+/-in method to "migrate" to the new phone. Upon opening the Aves, I noticed that all pictures are in messed up order and all are under "recently added" category. Basically years of taking pictures, screenshots, saving pictures from webSites, WhatsApp, ... are all bundled in a shuffled mix of pictures. My understanding is that Aves uses the creation date as "the date", and all these files, despite their metadata, have the same creation date.

This is somewhat distantly related to #97, but as far as I understand that discussion, very different thing.

**Describe alternatives you've considered**

at least use the metadata creation date as fallback if all the files have the same date.
**Describe the solution you'd like**

**Additional context**

It would be ideal if Aves can help adjusting the files ctime based on the metadata

**Comment by deckerst** [comment]
Actually, Aves uses the metadata date for filtering, sorting, etc. 

"Recently added" is the exception, as it only shows the items recently discovered by Aves. It's unrelated to the metadata date which Aves usually relies on. 

In your case, do you actually have an image with a metadata date that Aves ignores? It's easy to check: see the date displayed by Aves in the full screen viewer overlay (or the Info page).
