### ISSUE TITLE
External otg USB drive not recognized by aves gallery

### ISSUE THREAD

**Issue by wachkds** [deckerst/aves#1317]
Hello I just installed aves gallery on a new tablet running Android 13. Aves gallery does not recognize the otg USB external drive attached to the tablet.The same drive is well recognized by other apps, file manager etc.
The same otg USB external drive is well recognized by aves on another tablet running Android 10. 

Best regards and thank you for your great app

Pierre W
[aves-logs-20241127_111236.txt](https://github.com/user-attachments/files/17932748/aves-logs-20241127_111236.txt)

**Comment by deckerst** [comment]
File manager apps and gallery apps do not have the same view of the storage. Also, Aves relies on the OS Media Store (which is the native way of scanning for media on storage), and maybe it does not scan transient storage like OTG. It's something I need to investigate.

Duplicate:
- #366

**Comment by wachkds** [comment]
Hello Thibault,

Many thanks for your fast feedback .

I just tried to insert a microsd card in the internal dedicated slot of the
tablet, and this one is well recognized by Aves .
The issue is with external usb devices attached with an otg adapter through
the usb charging slot , although this was well working on older tablets
with Android 10 .

This one also to express a Big Thank You for your app that I discovered
lately and plan to use to cull pictures while on the go with a tablet .
My goal was to export my selection to an external usb drive so that I can
connect the usb drive on a computer without the fussle of removing the
internal micro sd slot .

Best

Pierre W


Pierre Wachholder
***@***.***
+32 (0)496 456 651

**Comment by deckerst** [comment]
Yes, SD cards and OTG drives are not treated the same way. SD cards are considered more permanent by Android, so the Media Store scans them. OTG drives are transient and not treated the same way.

Also, access to storage changed a lot with Android 11, and is more restrictive now for apps that are not file managers.

**Comment by Chimiell** [comment]
Hello I too want to thank you all for your app. I have a moto -g54 Mobil phone and Aves doesn't see the sd card pictures in view.

**Comment by deckerst** [comment]
@Chimiell OTG and SD card are not handled the same way.

A regular SD card should be automatically parsed by the Android Media Store which lists media and make them available to apps like Aves. If you don't see media on your SD card, it could be for various reasons, like using apps/scripts that do not register media properly.

OTG is transient storage, added and removed intermittently. So it is not parsed by the Android Media Store, and is therefore not readily visible to media galleries like Aves.

**Comment by Chimiell** [comment]
Thank you for reply any suggestions as to what to do?

**Comment by deckerst** [comment]
@Chimiell https://github.com/deckerst/aves/wiki/FAQ#why-isnt-my-album-in-the-albums-page
