### ISSUE TITLE
Double tap to zoom doesn't work until motion photo is played.

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#132]
Normally you would double tap to zoom into a photo when viewing it in full screen, but when I first try this it doesn't work. This is consistently reproducible.

However, when I then play the motion photo, I can now double tap to zoom in on any part of the screen which is expected behaviour - even as the motion photo plays. Now, if I turn off motion photo, on the same photo, it zooms as expected.

P6Pro, fully updated.

**Comment by deckerst** [comment]
For context:
- Before a video plays (whether by autoplay or manually pressing play), the viewer shows the video cover. Most of the time, it's just a frame extracted from the video, but not always. Some videos have a cover image, with possibly different dimensions and aspect ratio.
- A motion photo is displayed in the viewer as 2 parts: an image and a video. The video part should act like any other video in your collection.

From your description, I understand that you do not use video autoplay, and when you select a motion photo video part, you cannot zoom on the video cover by double-tap. I'd guess that you cannot zoom it by pinch-to-zoom either. And I'd guess you would have the same issue with other normal videos, not only motion photos. Is it correct?

**Comment by petazonk** [comment]
No, this is not what I mean. When viewing photos, where they be normal JPGs or motion JPGs, I can't double tap to zoom in on the photo. But, if I play the motion photo, then stop the motion photo, I can then double tap to zoom in on the photo. Please note that I'm not pinching to zoom, but instead double tapping to zoom. Also note that after playing the motion photo, and turning motion photo off, I can then double tap to zoom in on the photo. Shouldn't I always be able to double tap to zoom in on a photo?

**Comment by deckerst** [comment]
> whether they be normal JPGs or motion JPGs, I can't double tap to zoom in on the photo

Ah, it happens for regular images? I got confused with all the description regarding motion photos.

Then, let's forget motion photos for a moment, and let's focus on simple images. Does it happen on all images? Could you please give me the dimensions (width x height) of one the misbehaving images?

**Comment by petazonk** [comment]
It works fine for normal JPGs that are NOT motion photos. But it double tap to zoom on standard motion photos doesn't work until the motion photo has been played.
