### ISSUE TITLE
Feature Request: Preserve Date Created/Modified upon Convert

### ISSUE THREAD

**Issue by Saijin-Naib** [deckerst/aves#1322]
**Is your feature request related to a problem? Please describe.**
If I use Aves to batch-convert from JPEG to WebP on-device to save space for archival, the ordering of the Library gets all messed up because original file Date Created/Modified is changed and all the converted files jump to the top.

**Describe the solution you'd like**
An option to transfer/preserve these file attributes upon Convert.

**Describe alternatives you've considered**
Using another sort method (file name), but this is not available globally and also takes into account Library, significantly changing the sort layout.

**Additional context**
Niche for sure, but would smooth some rough edges for how I manage space on my wife's device.

**Comment by deckerst** [comment]
Metadata date is transferred (if enabled in the conversion dialog). File date is out of scope and unreliable anyway. Use metadata.

**Comment by Saijin-Naib** [comment]
Is there a way to address how this interferes with sort if file attributes are not transferred as now all the exported files are raised to the top of the list?

**Comment by deckerst** [comment]
I think it's too late. You had to give it a metadata date before the transfer. In a context of multiple devices and decentralised storage, never rely on file date.

**Comment by lalalasupa0** [comment]
I was thinking of opening an issue to *preserve timestamps when removing metadata*, but is it “unlikely” to be implemented too?
At least as an option, yk

**Comment by deckerst** [comment]
> I was thinking of opening an issue to _preserve timestamps when removing metadata_, but is it “unlikely” to be implemented too? At least as an option, yk

Same reason: https://github.com/deckerst/aves/issues/1322#issuecomment-2510768150
