### ISSUE TITLE
moving a video changes the date

### ISSUE THREAD

**Issue by bismanjit** [deckerst/aves#1329]
**Describe the bug**
Every time i move a video from one folder to another in the aves app. The 'recorded on' date of the file changes to the date when the move action is performed in the native s21 gallery app but not in the aves app. 

**To Reproduce**
1. Go to a file video
2. Move that video to a different folder in aves. 
3. Check the 'recorded on ' date of the video in the native gallery app

**Expected behavior**
The recorded on date remaining same

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.11.19-libre, build 13802
Flutter: stable 3.24.5
Android version: 11, API 30
Android build: RP1A.200720.012.G991WVLU4AUIB
Device: samsung SM-G991W
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: not available
Connectivity: mobile
System locales: en_CA
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: false
[aves-logs-20241206_222929.txt](https://github.com/user-attachments/files/18046528/aves-logs-20241206_222929.txt)
[aves-logs-20241206_222929.txt](https://github.com/user-attachments/files/18046529/aves-logs-20241206_222929.txt)

**Additional context**

**Comment by deckerst** [comment]
What your OEM gallery shows as "recorded on" is probably the file date, not the metadata date.
Aves only cares about the metadata date and does not have control over the file date.
Cf https://github.com/deckerst/aves/issues?q=label%3Anot-a-file-manager+is%3Aclosed
