### ISSUE TITLE
Introduce "Pinned at bottom" for Albums/Tags

### ISSUE THREAD

**Issue by FLAGEL** [deckerst/aves#1339]
Pinned Albums/Tags being shown at the top of their respective list is a useful feature. I suggest introducing a "Pinned at bottom" as well, i.e. the user would be shown the options "Pin at top" and "Pin at bottom". This would be useful with a media hierarchy such as:

[Pinned at top] Camera roll
[Pinned at top] Downloads
Travels X
Travels Y
Travels Z
[Pinned at bottom] Asana
[Pinned at bottom] Facebook
[Pinned at bottom] Instagram
[Pinned at bottom] WhatsApp videos
[Pinned at bottom] WhatsApp images

**Comment by deckerst** [comment]
I don't understand why it would be useful.

**Comment by FLAGEL** [comment]
I will try to be clearer by using a real-world example.

For me, pinned Albums/Tags serve the purpose of "active landing areas", meaning that contained items:
1) have actively been created by me (I took a photo, I took a screenshot, I downloaded something, etc), and
2) are to be edited, tagged, and moved to a final destination (another Album/Tag) when I get around to it.

I.e. the "active landing areas" are to be kept empty. Had I not pinned said "active landing areas" at the top, when time comes to sort them, I would first have to find each of them amongst hundreds of "final destination" Albums/Tags. I cannot prefix (with e.g. "!") these "active landing areas" as mostly they are system created filesystem directories ("Camera", "Download", "Screenshot", etc).

Unfortunately, there is also a need for "passive landing areas", meaning items I have not actively been involved with (automatically downloaded from mail, synced from the cloud, or created by a social media app). Often enough I do not get to name them either. I have no desire to hide these "passive landing areas" as they are browsed, but not sorted/emptied.

Ultimately, this has had me prefixing my "final destination" Albums/Tags with "!" to keep them listed above the "passive landing areas". Introducing a "Pin at bottom" option could allow me to send each "passive landing area" to the bottom of the list after acknowledging the existence of each new such Album (they show up as "New" at creation).

**Comment by deckerst** [comment]
It seems your passive landing areas will mostly fall into the "Apps" tier. If you could reorder the tiers, and place the "Apps" tier at the bottom (after the generic "Others" tier), would it solve your problem?

**Comment by FLAGEL** [comment]
I had entirely overlooked the tiers functionality. Is there a way to create tiers or associate albums with specific tiers? I don't seem to have an "Apps" tier; passive landing areas and final destination Albums both get listed under"Others".

**Comment by deckerst** [comment]
For now it's not possible to create tiers, and tiers depend on the grouping setting you use for the Albums page.

If you use the default grouping, there are tiers including the "Apps" tier. If an album is associated with an app, it will be in that tier. By default they are associated if the names match, but you can also customise an album to manually associate it with a specific app (or remove the default association). To customise, select the album with a long press, and at the top there's a button to change the cover/app/colour.

**Comment by FLAGEL** [comment]
I can change an Album cover and colour, but no app. It must be that I am using a (very) old LineageOS phone to experiment with - likely tied to that. 

That said, the idea of being able to reorder tiers sounds like a good solution.

**Comment by deckerst** [comment]
Have you enabled "allow access to app inventory" in the privacy settings?

**Comment by FLAGEL** [comment]
There seems to be no such permission on this device. Strange as I believe the QUERY_ALL_PACKAGES permission was introduced with AOSP 11.

Regardless, via ART interception there is no log of PackageManager.queryIntentActivities from Aves (but several other apps). I am not familiar with your code but I take there should be. I am running Aves Libre 1.11.19 from installed via F-Droid.

My setup is clearly unsupported so do not feel any pressure of putting time/effort into this before have had the chance to try it out on something more conventional.

**Comment by deckerst** [comment]
> Have you enabled "allow access to app inventory" in the privacy settings?

I was talking about the privacy settings inside Aves.

**Comment by FLAGEL** [comment]
That makes it work! Being able to reorder the tiers would indeed be a good solution, I personally would like to be able to move the Common and Apps tiers to the bottom.

**Comment by deckerst** [comment]
I'll close this one as I think having sorting (or custom tiers) would be a more flexible solution instead:
- #538
