### ISSUE TITLE
App starts, slows down, freezes, and crashes

### ISSUE THREAD

**Issue by MarOnic12345** [deckerst/aves#1342]
**Describe the bug**
The app becomes very slow shortly after starting it before it eventually freezes entirely and crashes.

**To Reproduce**
1. Start the app
2. Wait a few moments
3. App crashes

**Expected behavior**
For the app to function properly.

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.20-play, build 139
Flutter: stable 3.24.5
Android version: 8.1.0, API 27
Android build: M1AJQ.T927AUCU1ASC2
Device: samsung SM-T927A
Support: dynamic colors=false, geocoder=true, HDR=false
Mobile services: ready
Connectivity: wifi
System locales: en_US
Storage volumes: /storage/3137-3562/, /storage/emulated/0/
Storage grants: 
Error reporting: true

[aves-logs-20241214_021329.txt](https://github.com/user-attachments/files/18134952/aves-logs-20241214_021329.txt)

**Additional context**
I have tried three different versions of the app: Play, Libre, and the build found [here](https://github.com/deckerst/aves/issues/977#issuecomment-2061905514). Play and Libre both crash before I can see any images at all and just gets stuck on "Loading..." before crashing. However, the test build gets the furthest and I can actually see my pictures and scroll for a very brief amount of time before the app locks up and crashes. I tried saving a log file using the debug shortcut but the file was empty (the log file included above is from the Play version). Also, I don't get any notification that the app is cataloguing images. For further context, I have a lot of images saved on my microSD card. I don't know the exact amount, but I would say well over 100k, likely a lot more. I was using the test build and it was working fine before, but I recently transferred a ton of images to the SD card, and now it just crashes every time I try to use it. Maybe it can't handle the sheer amount of images on the card? I also tried reinstalling it but that didn't help. Lastly, my tablet doesn't support screen recording so I didn't include a video showcasing the issue, but if one is needed, I can try to find another way.

**Comment by deckerst** [comment]
Thanks for the report. 

> Maybe it can't handle the sheer amount of images on the card?

This is possible. The more media you have, the more time it will take to start the app and load everything. It also takes more memory.

I know some users have more than 250k items. But they use the app on a modern high-end phone, not a tablet on Android 8.

I'll take a look at the logs, but to be honest Aves is not the right app for large collections on old devices. It works best with curated media collections.

**Comment by MarOnic12345** [comment]
Appreciate the response. And yeah, my tablet is pretty low-end in terms of specs so that doesn't really surprise me. I guess I'll wait to find out if there's anything of note in the logs, but worst case scenario I can just delete some stuff.

**Comment by deckerst** [comment]
Looking at the logs, I just see some issue with shaders, but that shouldn't impact memory. However I see some automatic error reports for your device, which shows that it is indeed a memory issue (without a precise crash code location) and that it is indeed happening before trying to catalogue anything. 

I would like to understand where exactly it runs out of memory, and if possible fix that. But even with a fix, it will be very slow to load so many items in Aves on your device. With that in mind, if I can try and provide test builds to dig deeper. Are you interested to help test them and report?

**Comment by MarOnic12345** [comment]
> But even with a fix, it will be very slow to load so many items in Aves on your device.
I'm used to that at this point so it doesn't bother me too much. Actually getting it to load everything without crashing is more than enough.

> Are you interested to help test them and report?
Yes, that sounds good. I'm completely out of options at this point so I'm down to try anything.

**Comment by deckerst** [comment]
Here's a test build for a baseline:
https://drive.google.com/file/d/1kvO3oWt4z5CFYc3KGL2mV30cMaycpipt/view?usp=sharing

It should crash the same way, but it's based on the current code in repo (not the one released a few days ago). It will install as "Aves [Profile]" and is independent of the regular app (distinct settings, data, etc.).

It seems that the app crashes when saving the newly discovered media (but I miss some crucial details). From the logs I see it takes about a minute after launch to reach the crash. So please:
- install the test build,
- run it (preferably with automatic reporting enabled too) and let it crash,
- rerun it, and within a minute go to About > Bug Report to export logs,
- attach logs here.

**Comment by MarOnic12345** [comment]
Here you go.

[aves-logs-20241214_151915.txt](https://github.com/user-attachments/files/18137610/aves-logs-20241214_151915.txt)

**Comment by deckerst** [comment]
Another test build:
https://drive.google.com/file/d/1_zKNPSyV7s7hfsHEBXvO_ymYiVk3ggDf/view?usp=sharing

It will also install as "Aves [Profile]" and will replace the previous test build on your device. The initial loading of your whole collection (200k items!) should work on your device without a crash. Please give it a try. Even with that fix, loading and cataloguing will take a long time.

If you still encounter a crash (at initial loading or later in the app), please relaunch and export the logs as before.
