### ISSUE TITLE
App 1.11.19 - GUI Issues

### ISSUE THREAD

**Issue by bovirus** [deckerst/aves#1347]
**Describe the bug**

Soem GUI issues.
Please check screenshots

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/94a6d3f8-dab7-4345-ac63-5597048af9d9)
**Strings untranslated**

![image](https://github.com/user-attachments/assets/fbc96ed4-a933-4996-96bb-23fe77d2842f)
**Strings untranslated**

![image](https://github.com/user-attachments/assets/a01af434-0d7e-44d5-ba80-d1306971bff3)
**Two times same function**

![image](https://github.com/user-attachments/assets/c3e902d6-ec3b-4467-92f4-46e40ff78e42)
**Not clear function (Units)
"Units" could be "Measurement units"
"Metric" could be "Metric system"
"Imperial" could be "Imperial system"**
 
Note "Exlporer" could be "File manager" (more clear)

**System information and logs:**

**Additional context**

**Comment by bovirus** [comment]
@deckerst 

Sorry why "Won't fix"?

**Comment by deckerst** [comment]
Because I don't think your suggestions above are good ones.

**Comment by bovirus** [comment]
@deckerst

Other are issues (untranslatd strings / double function with same name in menu).

**Comment by deckerst** [comment]
Stop hassling or I'll ban.

If you find an actual bug, report it independently following the bug template.
