### ISSUE TITLE
Cannot view original, only copies

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#135]
See the video demonstration of this issue:
(Too big for github upload, link expires in 30 days)
https://upload.disroot.org/r/EF0Kh6uu#cctjsbepEdtWQ/8BYQ1WtTWTYq3lfOx9jvJgpqoiOj0=

First download:
![GNOME-Software-41-Responsive-Animation](https://user-images.githubusercontent.com/50382414/143370207-dae03011-db4b-4883-92fe-ab57c521de19.gif)

Second download:
![GNOME-Software-41-Responsive-Animation(1)](https://user-images.githubusercontent.com/50382414/143370235-38f44dfd-ad16-4cb3-9dc8-aab195a991c0.gif)

(Note that they are exactly the same file, except for (1) at the of the name of the second version)

As can be seen in the video, I need to download the image twice to be able to view it in Aves.

---

[aves-logs-20211125_033842.txt](https://github.com/deckerst/aves/files/7599784/aves-logs-20211125_033842.txt)

Aves version: 1.5.6-play (Build 60)
Flutter version: 2.5.3 (Channel stable)
Android version: 10 (SDK 29)
Android build: lineage_raphael-userdebug 10 QQ3A.200705.002 eng.abhish.20200710.065119 test-keys
Device: Xiaomi Mi 9T Pro
Google Play services: not available

**Comment by deckerst** [comment]
Thanks for the report.

From the logs, I see that the Media Store on your device thought the first GIF was a video (which is incorrect) and the second GIF an image (which it is). I can't reproduce that phenomenon, but I'll try to make Aves more robust against that kind of nonsense.
