### ISSUE TITLE
Thumbnails failing to load

### ISSUE THREAD

**Issue by nsarzyns** [deckerst/aves#1352]
**Describe the bug**
Thumbnails are failing to load; mostly in the albums section but a few fail in the collections section. When accessing an album, the first few rows will populate but after that, they stop. Leaving the app open for some time, scrolling, opening a different album, force closing the app, and rebooting the phone, has no effect. I originally installed the build from F-Droid but also tried the one from Google Play with the same outcome. This issue also recently started. Been using the app for a bit.

**To Reproduce**
1. Open app
2. See thumbnails failing to load

**Screenshots**
![Screenshot_20241219-101213](https://github.com/user-attachments/assets/4de6f35a-19d5-41c7-b7c6-74314dc82813)
![Screenshot_20241219-101235](https://github.com/user-attachments/assets/5a5fea3d-a83a-4067-b4e9-17eb0bdc6b80)
![Screenshot_20241219-101247](https://github.com/user-attachments/assets/375a3770-a88c-4b49-9e70-f6e94d2b9084)

**System information and logs:**
[aves-logs-20241219_100639.txt](https://github.com/user-attachments/files/18199701/aves-logs-20241219_100639.txt)

Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.19-play, build 138
Flutter: stable 3.24.5
Android version: 15, API 35
Android build: AP4A.241205.013
Device: Google Pixel 7 Pro
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Additional context**

**Comment by deckerst** [comment]
It shouldn't be related but I see some background processing in the logs. Have you enabled notifications to see when the media cataloguing service is running? If you haven't, please enable it. Then launch the app, wait for the cataloguing to finish, and let me know if thumbnails load better afterwards.

**Comment by nsarzyns** [comment]
To be honest, I'm not sure when I installed it nor when it updated through F-Droid, my go to place for this but the last time I used it was a few days ago. The logs I sent are from a reinstall. Juding by the F-Droid version history, I'd wager it was fine in 1.11.19 and started in 1.11.20

Not really sure if that helps.

Something I just noticed; opening an album that doesn't contain any *.mp4 loads fine. Albeit, the number of photos in that album is under small in comparison to some of the others.

**Comment by deckerst** [comment]
> I'd wager it was fine in 1.11.19 and started in 1.11.20

Above the system info show it's the 1.11.19 from the Play Store (where the 1.11.20 is only in beta at the moment). So if you have the issue with the Play Store release too, it means 1.11.19 was already having the issue.

**Comment by nsarzyns** [comment]
Uhhhhhh, this can be closed now 😅

I rebooted again, due to having a 1.2MB google play system update, and it works now. Moved back to the F-Droid install and it works fine as well. 2nd reboot did it?

As for the cataloguing service, I would see the 'cataloguing x/x' prompt under the heading, and it would disappear

**Comment by deckerst** [comment]
Mysterious, but I'm glad to know it now works for you.
