### ISSUE TITLE
Include private Cloud 

### ISSUE THREAD

**Issue by Peter20241220** [deckerst/aves#1354]
This is the best Photoorganizer App by far.
My problem is, that over the years I've much more pictures than space on my mobile / pad.
I am used to store them in a private cloud (pcloud from Swiss). 
It would be great to use Aves including all pictures stored there.
Maybe there could be the ability to include a login to online adresses, password or biometric, for safety reasons each time of opening the app.
The data of Aves should of course stay on the device, so there can be a hint if you're searching while not connected to the cloud.
Thank you!

**Comment by deckerst** [comment]
Duplicate: 
- #126
