### ISSUE TITLE
عرض الألبومات الفرعية في مجلد رئيسي واحد

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#1355]
يرجى اضافة ميزة إنشاء مجلدات في معرض الصور
مثلا يمكننا تحديد عدة ألبومات لا اريدها أن تظهر مباشرة في قائمة الالبومات ، عوضا عن ذلك اريدها ان تكون في مجلد واحد عند الدخول فيه نجد كل الالبومات المحددة مسبقا

مثال:

مجلد الخرائط:
خرائط صماء
خرائط طقس
خرائط جيولوجية
خرائط السكة الحديدة

شرط ان لا يكون هناك أي تقييد على عدد المجلدات المضافة و تسمياتها

وأن تكون أيقونة المجلد في قائمة الألبومات

![IMG_20241221_202729](https://github.com/user-attachments/assets/89a04a71-db75-4ff7-bcec-8358e496aefd)

**Comment by deckerst** [comment]
Duplicate: 
- #268
