### ISSUE TITLE
Aves cannot read GPS location from metadata

### ISSUE THREAD

**Issue by pktiuk** [deckerst/aves#1366]
**Describe the bug**

App shows 0 and 0 in GPS Latitude and Longitude, but other apps (like nextcloud memories or Gnome file picker) show proper location.

**To Reproduce**
1 Download image: [2024-09-28-12-23-51-025](https://github.com/user-attachments/assets/d912db81-397e-4911-b5f5-0b829afc98c7)
2 Check it's location via other app (not aves)
3 Check its location via Aves

**Screenshots**

Aves:

![obraz](https://github.com/user-attachments/assets/d3eede9a-a2a7-4b92-be91-536789b4d5c7)

Gnome (Ubuntu Linux) file picker:
![obraz](https://github.com/user-attachments/assets/3d9ba30b-3e21-423d-9bd4-a826d12a966d)

**System information and logs:**

```
Package: deckers.thibault.aves.libre
Installer: org.fdroid.basic
Aves version: 1.11.20-libre, build 13902
Flutter: stable 3.24.5
Android version: 15, API 35
Android build: AP4A.241205.013.24602012
Device: Google Pixel 6a
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
Connectivity: wifi
System locales: pl_PL, en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/
Error reporting: false
```

**Additional context**

Android ROM: CalyxOS 

Some of my photos work properly with Aves.

**Comment by deckerst** [comment]
Works fine on my device.

I suspect you didn't give all the permissions to Aves, especially "access media location". Can you check?

![Screenshot_20241228-230846~2](https://github.com/user-attachments/assets/2e3c3450-362b-4cdc-a041-99e303c164a5)

**Comment by pktiuk** [comment]
@deckerst   
It already has this permission.

This app properly shows me metadata of another photo from the same directory. The only difference is that the broken photo was copied to a subdirectory (and later copied back).

**Comment by pktiuk** [comment]
![Screenshot_20241228-232735](https://github.com/user-attachments/assets/dfb3bbea-0ef5-42b9-9cf9-d4b6da694e7e)

**Comment by pktiuk** [comment]
Info from another file:
![Screenshot_20241228-233101](https://github.com/user-attachments/assets/164f9fc1-3ae2-4042-bfb2-c728be121ad5)

**Comment by deckerst** [comment]
If you download the file from the link in your initial report above (without moving it), and open it in Aves, do you see the coordinates?

This is what I did and the GPS coordinates were there (with the latest version v1.12.0).

**Comment by pktiuk** [comment]
Downloaded file works fine.     
So I guess this seems to be an Android issue.      

Thank you for quick response. (I guess the issue can be closed now)

------------------

(In `Settings ->privacy ` there are some additional permissions which may be worth checking)

**Comment by deckerst** [comment]
Thanks for reporting back. Maybe the app that moved the file didn't have the permission I mentioned above.
