### ISSUE TITLE
Include images from subdirectories in the collections

### ISSUE THREAD

**Issue by pktiuk** [deckerst/aves#1367]
**Is your feature request related to a problem? Please describe.**

Recently I started organizing my photo collection. I have placed my photos from `./DCIM/Cameras` to subdirectories like `./DCIM/Camera/Wacation2024` etc. and I discovered that my photos disappeared from my timeline generic Camera timeline.

**Describe the solution you'd like**

Collections should contain images not only from the top level of the selected directory, but also from its subdirectories.

So for Camera directory with content:
```
├── 1.jpg
├── 2.jpg
├── vacations
│   ├── 3.jpg
│   ├── 4.jpg
```

Should generate collection with 4 photos, not with 2.

**Describe alternatives you've considered**

- Create custom collections - it would be a real headache in case of more directories and nested subdirectories.
- Switch in settings enabling this option - doable, but I don't find this necessary

**Comment by deckerst** [comment]
Instead of using the album filters from the Albums page, use the path filters from the Explorer page.
