### ISSUE TITLE
Missing thumbnails

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#140]
These files have no thumbnail on my device:

https://user-images.githubusercontent.com/50382414/145699341-31f17b03-c37f-4154-83cb-8b3e0a924b0b.mp4

https://user-images.githubusercontent.com/50382414/145699345-f1b73a1d-216d-456e-bc5d-4956354c2643.mp4

https://user-images.githubusercontent.com/50382414/145699348-2aae27e7-d62e-42cb-97b4-33d09705ea6a.mp4

https://user-images.githubusercontent.com/50382414/145699351-3d1a1afd-2663-4fd8-a37e-4dc22bf888e9.mp4

Aves version: 1.5.3 (Build 57)
Flutter version: 2.5.1 (Channel stable)
Android version: 10 (SDK 29)
Device: Xiaomi Mi 9T Pro
Google Play services: not available

Perhaps related: #103

**Comment by Donkey-Doug** [comment]
You probably already answered this question, but version 1.5.4 solved #103 so perhaps this is a bug.

**Comment by deckerst** [comment]
What I wrote in #103 is still true in the current version:

> For the missing thumbnail, for now this is expected for videos that your own device cannot natively play. This is because Aves does not currently rely on the same mechanisms to get video thumbnails on one hand, and play the videos on the other.

There are 2 cases:
1) if the video cannot be played by your stock video player / gallery, this is the known limitation explained above,
2) if the video can be played by your stock video player / gallery, then Aves should display a thumbnail and this is a bug indeed.

I cannot state which case it is for the videos you attached, because it depends on your device. Only you can tell me.

**Comment by Donkey-Doug** [comment]
All of the videos play, but have no thumbnail.

**Comment by Donkey-Doug** [comment]
Aves can play the videos. 

Example:

https://user-images.githubusercontent.com/50382414/145745579-46ba43a9-34f4-470d-bbf9-66a171815407.mp4

**Comment by deckerst** [comment]
Sorry, I wasn't clear, I meant to ask "do they play in your stock video player / gallery?"

**Comment by Donkey-Doug** [comment]
I think something went wrong with these files. Look at the title and path:

![Screenshot_20211213-040516_Aves](https://user-images.githubusercontent.com/50382414/145746109-aaa7582c-401b-4809-a43c-fda67f0a21b4.png)

I tried to rename it, but the name of the file is not correctly changed (I checked with file browser). In a file browser I still see the old name.

**Comment by Donkey-Doug** [comment]
New log with renaming issues:

[aves-logs-20211213_040955.txt](https://github.com/deckerst/aves/files/7700731/aves-logs-20211213_040955.txt)

This is the same as

**Comment by deckerst** [comment]
> I tried to rename it, but the name of the file is not correctly changed (I checked with file browser). In a file browser I still see the old name.

Aves prefers title and date from metadata over the ones from the file. And I bet this file has a title defined in its metadata. You can check it by opening the `Media` or `Stream X` sections. So this works as intended.

**Comment by Donkey-Doug** [comment]
> Aves prefers title and date from metadata over the ones from the file. And I bet this file has a title defined in its metadata. You can check it by opening the `Media` or `Stream X` sections. So this works as intended.

You are correct.
