### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by JanWaldhorn** [deckerst/aves#144]
A first attempt to translate the app into German. Probably a PR would be easier, but I have never done that. So here are the two files as attachments.

I have used the English files as a basis. Especially with the arb file the translations so far seem to contain only certain lines. I hope the full file does not cause any problems?
[aves_german.zip](https://github.com/deckerst/aves/files/7739606/aves_german.zip)

**Comment by deckerst** [comment]
Wow, thanks!

If you [email me](mailto:gallery.aves@gmail.com), I'll give you a link to a temporary build with your translation, so you can see how it looks in practice. It seems overall fine to me, but maybe you'll spot inconsistencies, or want to adjust some wording to improve the layout.

Also, is it fine to credit you in the About section as "JanWaldhorn"? Please let me know what you prefer.
