### ISSUE TITLE
Ability to set the EXIF/GPS metadata dates from the File Properties "Date Modified" within existing Edit Date/Time utility

### ISSUE THREAD

**Issue by jonathan2384** [deckerst/aves#146]
**Is your feature request related to a problem? Please describe.**
Editing tags and performing other modifications with images that lack Date/Time metadata within their EXIF data (such as those downloaded from social networking sites) causes the File Modified date to be set to the current time, shooting it up to the top of the chronological gallery. 

From the way the Android media access works, this behaviour is expected, but not ideal, as people may expect their media to still be on the correct place in the chronological gallery even after they've modified and edited it.

**Describe the solution you'd like**
Adding functionality to the existing "Edit Date and Time" utility to get the Last Modified Date from the file properties and embedding it into the file's EXIF and GPS metadata would be heavily appreciated.

It might also be done automatically when the tags and other metadata are edited for media that does not contain EXIF/GPS date, to prevent the user from being surprised with the loss of date information. 

**Describe alternatives you've considered**
I do believe other applications, namely Google Photos, allows modification of media descriptions and metadata without affecting the date. However, I've chosen Aves due to its unparalleled ability to view and modify metadata without propieratary services or file formats - and it's been great at that.

**Additional context**
I do believe similar functionality was implemented in #111 , but that only gets the Date from the filename, not the Last Modified date from file properties.

**Comment by deckerst** [comment]
I remember in #111 rejecting the idea of automatically editing the date when moving/renaming files, but automatically editing the date when editing metadata (tag, orientation, non-exif metadata removal) sounds fair.

Regarding the "Edit Date and Time" utility, I also wanted to allow copying from one field to another, so I'll do this work together with what you suggest.

Google Photos, as far as I know, doesn't actually modify the files when you edit descriptions or locations. Editing these metadata is only available when your files are backed up, as the metadata is stored by Google. People who wish to retrieve that metadata need to export their photos with Google Takeout, and the metadata is in separate JSON files.
