### ISSUE TITLE
Swipe through all photos when opening from camera app

### ISSUE THREAD

**Issue by tsiflimagas** [deckerst/aves#147]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this one is some kind of bug or is it just not implemented. When opening Aves from a camera app (I specifically did from a google camera port) to view the last shot picture, you can only view that picture, not having the ability to swipe through the rest. I tried with the stock AOSP gallery app and a few others to make sure this feature is there in general, and it is possible, so I hope it will be easily doable for Aves too.

**Comment by deckerst** [comment]
Opening the app to display a specific image does not entail showing the image in context, according to the way Android works. Funnily, Samsung Gallery and F-Stop do it, but Google Photos does not.

Anyway, I see the value of this feature and I implemented it for Aves, but you may notice that it will take more time to open (depending on the size of your collection). Let me know if the experience is not pleasant.

**Comment by tsiflimagas** [comment]
Sadly, I don't have that many photos on my phone to "stress test" this, but it seems to be working fine, as I didn't notice any difference in opening speed. Thanks for implementing this!
