### ISSUE TITLE
Create changelogs in the fastlane location

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#154]
There's this file: https://github.com/deckerst/aves/blob/develop/whatsnew/whatsnew-en-US.

I assume that it's created for Google Play changelogs (?), however, the F-Droid (Izzy) doesn't pick it up so the F-Droid page does not contain changelogs. To fix that, you need to create the changelog file in the fastlane directory. The location is `fastlane/metadata/android/en-US/changelogs/123456.txt`, where `123456` is the correct version code (currently it is 1064 for your app)

**Comment by deckerst** [comment]
I tried once to do exactly that, but it didn't pick it up. I didn't feel like spending more time on this at the time...

**Comment by flexagoon** [comment]
Maybe that's an issue on IzzyOnDroid's side?

@IzzySoft does your script pick up fastlane changelogs?

**Comment by IzzySoft** [comment]
Yes, if told to. I need to explicitly enable each feature for each app (set it up that way as with some projects some parts were broken – like a shortdesc containing rather a long text, a fulldesc with either no "real content" or badly formatted).

But I see no changelogs in your Fastlane structure? For your app, Fastlane settings here are:

    shortdesc,fulldescMD,icon,featureGraphic,screenshotsJPG

Which means: "pick shortdesc as-is, process fulldesc as Markdown, pick icon + featureGraphic in the format they are (and just optimize them), convert screenshots to JPG". This is done 1) for size optimization (considering users on low bandwidth/bad connections) and 2) for optimal formatting (fulldesc).

Now, should you add something (changelogs, `video.txt`, `title.txt`) just let me know so I can check and add that.

**Comment by flexagoon** [comment]
@IzzySoft thank you for your response!

@deckerst so you can add a changelog when you'll be releasing the next version of Aves, and then let Izzy know about this so that he includes it in the repo

**Comment by Donkey-Doug** [comment]
Perhaps also consider improving the screenshots and icon image.

The screenshots are cropped versions of those on github.
The icon is low-res in the fdroid (droid-ify) store.

**Comment by IzzySoft** [comment]
> The screenshots are cropped versions of those on github.

Intentionally. Consider folks on small smartphone screens. No need to waste valuable screen estate for "empty borders".

> The icon is low-res in the fdroid (droid-ify) store.

Yepp, that's currently the 192x192 version and could be replaced by a higher-res one (e.g. 256x256 or max 512x512 px).

Being one having actively worked on this: at least with my repo, I always have the mobile users in mind (after all, the apps are for mobile devices). That means considering screen estate and bandwidth. Hence my suggestions to keep screenshots "unframed", don't use the "highest res" (my updater usually downscales and compresses) etc.

Metadata (summary, descriptions, screenshots, icon) are to give you an idea of what an app is about. They are not intended to be a high-res art gallery, IMHO :wink:

**Comment by flexagoon** [comment]
@IzzySoft well the icon should at least have a transparent backgroud. And here it has a black backgroud and the white border is weird and choppy

**Comment by IzzySoft** [comment]
I agree with that. Must be the resizing process then which fails at transparency. I've replaced it manually for now and blocked it against being updated (change should become visible in a couple of minutes with the next sync). Will need to see what can be done to the resizer used.

PS: Found (and hopefully fixed) the culprit. That thingy defaults to ignore transparency by default (which I consider bad behaviour; I had expected it to stick to the original by default unless told otherwise). Well… That was that.

**Comment by deckerst** [comment]
@IzzySoft I just added a changelog for the current version and will do so for future versions. Please enable the feature to check them on your side:
https://github.com/deckerst/aves/tree/develop/fastlane/metadata/android/en-US/changelogs
And thank you for fixing the icon, it looks much nicer now!

**Comment by IzzySoft** [comment]
Changelog pickup enabled. And yeah, I could re-enable icon pickup as well, now that I've fixed that transparency issue. But that would also mean it would get resized to 48x48 (needed for many apps to get the icon to reasonable size; not so with yours, so I'd rather keep the current one). Just let me know if that's OK with you – or if you have plans for changing the icon. Currently, I've got the 192x192 px variant in, which at around 12k is reasonable in size (others only reach that when brought down to 48x48).

**Comment by deckerst** [comment]
Thanks! The icon looks fine as it is now, no need to change the pickup behaviour.

**Comment by IzzySoft** [comment]
As for changelog pickup: it will always only pick the corresponding changelog. I.e. if you release an APK with `versionCode: 184`, it will only look for `184.txt`. So make sure to have the corresponding file there when creating a new release (if you forgot and add a few minutes later: other than with F-Droid.org which only looks at the tag, my updater looks at HEAD and thus would still find it – as long as it wasn't picking the APK before you added the TXT :wink:)
