### ISSUE TITLE
Simplify 3-dots menu

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#155]
![Screenshot_20220109-063832_Aves_1](https://user-images.githubusercontent.com/50382414/148670763-05d8780b-86b9-4186-af7d-d5f2073761c7.png)

There are many entries I never use, like print, copy to clipboard, add shortcut, info (can be triggered by a gesture) amd set as.

It would be nice if this menu was customizable. I would like to hide some entries. I suggest making a "more" entry and categorizing all hidden options there (similar to the edit option when selecting an image).

**Comment by deckerst** [comment]
I agree that some of these actions are not used enough to be at a top level, but I'm reluctant to make yet another settings screen for customization.

In this particular case, I'm considering several options.
1) tucking the following in an `Export` sub menu:
- Export (renamed to `Save as`)
- Copy to clipboard
- Print
2) alternatively, turning these into icon buttons in one line (like the rotate / flip buttons):
- Create shortcut
- Copy to clipboard
- Print

By the way, do you use `Edit with...` and `Open with...`? Would you still need these actions at a top level if Aves provided a decent image editor?

**Comment by Donkey-Doug** [comment]
Maybe also relocate "add shortcut" to the proposed export menu?

**Comment by Donkey-Doug** [comment]
![Screenshot_20220201-235100_Aves](https://user-images.githubusercontent.com/50382414/152064766-207699dd-2c6d-4ad5-a962-b71ea4ebaff1.png)

After long-pressing an image this menu shows up in the 3-dots menu. I don't think view, stats and map should be visible in this particular 3-dots menu.

**Comment by deckerst** [comment]
This is intentional. "Map" and "stats" are contextual: they apply to the selected items. "View" allows you to change group, sort and layout settings without losing your current selection.

It has its use, even if you personally do not use these actions.

**Comment by Donkey-Doug** [comment]
I think you can remove "print" because in android you can share an image and select "print". The print option is in the share menu.

**Comment by deckerst** [comment]
It may vary with Android versions too (Aves goes back to KitKat), and OEMs can also tweak or remove basic features, so there's no guarantee that the experience on your device is universal.

**Comment by deckerst** [comment]
I just tried out the native share-to-print feature:
- it crops images (even when tweaking paper size settings),
- it cannot handle printing TIFFs (or other natively unsupported formats that Aves can render),
- it only prints the first image in multi-image HEIFs.

**Comment by Donkey-Doug** [comment]
Uhm. When I press print it gets opened in a printing app where I can choose certain settings. Probably different for different android versions.

But anyway, in that case just leave the print option available.

**Comment by Donkey-Doug** [comment]
What is the difference between open with and share? @deckerst

**Comment by deckerst** [comment]
Technically, it is not the same intent: "open with" to view/examine, "share" to send/transfer.

Apps on Android declare what intent they can handle. Some apps can handle the first intent, some apps the second one. Aves, as a viewer, can handle both.

Typically, you could use "open with" to view an image in an app that does not handle the share intent. It is also the right intent to play a video with another app (in Aves there's a purposefully redundant action for that use case among the video actions).
