### ISSUE TITLE
Export Favorites

### ISSUE THREAD

**Issue by onkoe** [deckerst/aves#156]
Hello, does the import/export feature in the settings also export my favorites and other info? If not, could this be implemented? I am extremely interested in this feature. Thanks for the great app! :)

**Comment by onkoe** [comment]
It seems that on both OnePlus Gallery and Samsung Gallery (2016 though, so quite old), photos are scanned and snowflakes are created when opening the app. This allows the apps to maintain a list of favorites even if an image moves externally. However, neither of these apps support syncing or local backups, so you'd have to manually add each one back to your favorites if you were to upgrade devices. This is what I hope to avoid, especially since I often swap ROMs and test alpha-stage software. 

For these reasons, my preference goes to creating fingerprints, though saving file paths wouldn't be too bad either. Restoring an Android backup is as simple as untar-ing your home directory, so most people would find either solution workable. Devices with automatic sync and backup, e.g. Google Photos, may have trouble, though. 

In any case, I will certainly make a "favs" tag until this feature is implemented. Thanks for your advice and assistance!

**Comment by deckerst** [comment]
In the next release of Aves, you'll be able to pick & choose what to export/import: 1) covers (for albums, countries, tags), 2) favourites, 3) settings.

For covers & favourites, I kept it simple with file paths, as fingerprinting is not in scope now (and it raises interesting questions about item identity).

I lightly tested this feature and it seemed to work well enough, even when export/importing 10k favourites, but let me know if it's not working for you.
