### ISSUE TITLE
gray screen

### ISSUE THREAD

**Issue by MeFinity** [deckerst/aves#158]
**Displays Gray Screen**
when pressing on almost anything it just displays gray,and when i tap 'back' the app just closes

**To Reproduce:**
click on 'All Collections' (and Images,etc etc)
**Expected behavior:**
goes to the 'All Collections' tab

**Screenshots:**
![Screenshot_2022-01-13-16-32-14-85](https://user-images.githubusercontent.com/72972952/149303742-5d9d01af-7855-4d03-8c41-4c660e83ffbf.jpg)

**System information and logs:**
```
Aves version: 1.5.10-izzy (Build 1064)
Flutter version: 2.8.1 (Channel stable)
Android version: 9 (SDK 28)
Android build: CPH2083EX_11_A.65
Device: OPPO CPH2083
Google Play services: ready
```
Logs: does not show anything,and github wont upload it
**Additional context:**
i think its cause theres too much images and im just an idiot

**Comment by deckerst** [comment]
>  i think its cause theres too much images and im just an idiot

Haha, you're not an idiot. The app is idiot for going gray though :/

Without log it will be tricky to solve. I'll need to ask many questions to get inspired...

As the app ever worked well for you in the past with the same collection of images? Did it work well with a previous version of the app?

When you launch the app all is well, right? If you tap on something it goes gray. But if you don't touch anything, does it go gray by itself? Or, if you just scroll on the home page but do not navigate to other pages, does it go gray?

You mention you have many images. How large is your collection? Do you have any exotic image/video file (like some large TIFF, PSD or MP4)?

You have installed the app via F-Droid/Izzy, so there's no automatic bug reporting. But if you're willing, you could temporarily install the Play version, enable error reporting (it uses Crashlytics) and try to reproduce the issue a couple of times. With any luck I would see the report from some background issue. The build of the Play version is on the Play Store, or [here on GitHub](https://github.com/deckerst/aves/releases/download/v1.5.10/app-play-release.apk).

**Comment by MeFinity** [comment]
1. No,this is the first time i downloaded the app

2. It goes gray when i try to load a folder/album list,and no it doesnt go gray by itself

3. 13k Photos and 400 Videos according to my phone (most are saved on my sdcard so there could be more)

4. i'll try that,thank you

**Comment by deckerst** [comment]
Out of curiosity, what's the locale (language) on your device?

It's probably unrelated to the issue here, but I just discovered that the app is practically unusable if the device locale uses numerals other than the usual Western Arabic ones (1 2 3) used in English. For example, if the device is set to Arabic, it uses Eastern Arabic numerals (١  ٢  ٣), and the app fail to load images O.o

Also, the collection on my device is about 13K+ images and Aves can handle it just fine.

**Comment by MeFinity** [comment]
my device locale language is English (US)
previously Indonesian

**Comment by deckerst** [comment]
Good news: I'm seeing reports in Crashlytics. I can't take a close look now, but it seems easy to fix. Thanks for helping with the reports!
