### ISSUE TITLE
svg export

### ISSUE THREAD

**Issue by TidalMist** [deckerst/aves#160]
[aves-logs-20220118_134716.txt](https://github.com/deckerst/aves/files/7888407/aves-logs-20220118_134716.txt)
[2_5318891364836971694.zip](https://github.com/deckerst/aves/files/7888419/2_5318891364836971694.zip)
svg in zip

Aves version: 1.5.10-izzy (Build 1064)
Flutter version: 2.8.1 (Channel stable)
Android version: 10 (SDK 29)
Android build: DUA-L29 3.1.0.169(C10E3R2P2)
Device: HUAWEI DUA-LX9
Google Play services: not available

**Comment by deckerst** [comment]
Fixed (in the next release), and because SVGs have no pixel dimensions, I added width/height parameters along the format in the export dialog. These parameters can also be used to resize raster images, too.
