### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by deckerst** [deckerst/aves#163]
Some people think it's important, but I've never needed slideshows myself and have no intuition about them.
Does it need wipe transitions a la Star Wars? Generic ukulele background music? Feel free to comment with ideas.

**Comment by Donkey-Doug** [comment]
I will never use such functionality.

**Comment by mdb571** [comment]
I used to like the memories widget in google photos app.. but now i no more use it and have switched to FOSS gallery apps.. I would love to see this feature implemented and it would be an awesome addition :)

**Comment by deckerst** [comment]
@mdb571 if you're specifically interested in the widget, you can upvote/subscribe to #175.

**Comment by ntbuilder** [comment]
> I used to like the memories widget in google photos app.. but now i no more use it and have switched to FOSS gallery apps.. I would love to see this feature implemented and it would be an awesome addition :)

It would be better if the widgets are from random favourates

**Comment by mdb571** [comment]
Woah, Cool :) I all excited to test this out. When can we expect a release ?
btw thanks for making this happen 👍🏼

**Comment by deckerst** [comment]
@mdb571 in Aves v1.6.11 you can now set up a widget to show any collection you like. For example, you could set it up with the new "on this day" filter to show photos taken on the same day as the current day.

@ntbuilder in Aves v1.6.11 you can now set up a widget to show any collection you like. In your case just set it up with the "favorites" filter.
