### ISSUE TITLE
Add Move to Album option when viewing a single photo

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#164]
It would be good to have a move to album option when viewing single photos.

An alternative to this request would be a flag option such that while viewing each photo you could flag them. After you have finished flagging your photos you could then select all flagged photos and perform an action like move to album, delete, add the same tag or whatever.

**Comment by deckerst** [comment]
From a productivity point of view, the flag idea is a good one, but it raises too many UX questions:
- is removing the flag manual or automatic?
- if it's automatic, how can we do several actions like tagging and moving?
- if it's manual, does it behave like favourites and persists after closing and reopening the app?
- can you have different kinds of flags (like photo managers often allow flagging with different colours)?
- and more...

So, I'll probably implement your first suggestion, but not the second one.

For what it's worth, I personally do not use the favourite feature to tag my best shots (I use tags for that). I use favourites as temporary flags exactly the way you describe!

**Comment by petazonk** [comment]
I do exactly what you do in that I use the favourite flag to flag photos
that I then move to separate albums. I then go and turn the favourite flag
off. But for other people that do use the favourite flag, then they
couldn't do this. I still think that having a dedicated FLAG would be quite
useful. People should be responsible for turning it off themselves but you
could also add a turn all flags off button.

**Comment by deckerst** [comment]
Added copy/move actions to the viewer.

As for the flag(s), I don't intend to implement that in the near future but I see the value. Feel free to open a dedicated issue and subscribe to it if you want.
