### ISSUE TITLE
App startup is abnormally slow

### ISSUE THREAD

**Issue by xd003** [deckerst/aves#170]
For some reason , the app startup is quite slow . To be precise , its taking approx 3 seconds for the images to fully load once app is opened . Other gallery app takes 1-1.5 second for the same . Majorly i would attribute this delay to the black screen that shows up for a second after opening app and before loading of images

I am not sure if log would help in this case but i am attaching it here nevertheless along the screen recording showing the comparison
[aves_slow_startup.txt](https://github.com/deckerst/aves/files/7972376/aves_slow_startup.txt)

https://user-images.githubusercontent.com/26503185/151840011-3425ecf5-4178-4f57-85ca-b5beab28621c.mp4

Do let me know if anything else is neeeded as well.

Aves v1.5.11
Android 10

**Comment by deckerst** [comment]
Thanks for the feedback.

Initial loading mostly depends on the number of items in your collection. How many images and videos do you have?

Did you notice a regression from a previous version of Aves, or you only compared to other apps?

For the foreseeable future, initial loading can be expected to be slower than more basic gallery apps, given the advanced indexing, categorization and search capabilities of Aves. I'll see what I can do, but if this extra second is unacceptable for your daily usage, I recommend you keep using a more basic gallery.

**Comment by xd003** [comment]
SInce i am using it for the very first time ,  I haven't compared the current version of aves with any older one . Everything else being perfect , this is the only one thing that stood out to me . I have around 10,300 items in  my collection 

Just out of curiosity , since you said the loading time is dependent on the items in collection implying that the 1 second black screen is where the collection is actually loading  . What if you make the collection to load partially on startup ( eg say just 100 items ) to improve startup time . The remaining collection items may very well load in the backgroud . This will cover both use case - If someone wants to quicky access their latest item in collection , they can do so faster than now and if someone scrolls down to access older items , it would have been already loaded in the background during the take taken to scroll

**Comment by Donkey-Doug** [comment]
What if you wait until "loading" is done. You can check in the top bar. Maybe after all images are loaded once, it speeds up.

Just open the app and leave it in the foreground for a couple of minutes.

**Comment by deckerst** [comment]
I took a closer look at what is happening before the first screen appears, and the delay is actually unrelated with the collection itself. It's initializing a few critical things like the settings (to know the user home page), and to do so there's some communication between Flutter and Android. Flutter apparently takes around 800ms (on my device) to initialize the plumbing for that kind of communication.

**Comment by Donkey-Doug** [comment]
> It's initializing a few critical things like the settings to know the user home page

Can't that be handled better? Maybe saving such settings in cache?

**Comment by deckerst** [comment]
Some things can get cached. Different dependencies for storage are needed too. Even so, communication with the platform is ultimately essential.

**Comment by xd003** [comment]
> I took a closer look at what is happening before the first screen appears, and the delay is actually unrelated with the collection itself.

Sorry for the late reply but i can also confirm this . I just tested opening a image directly from the file manager through Aves & Simple Gallery . For some reason , the difference is quite high , even more than the app startup loading times of 1-1.5 seconds . Its consistently around 4 second for Aves  & 1 second for Simple Gallery 


https://user-images.githubusercontent.com/26503185/153740134-3e488d86-b9c8-4a33-b8b5-d7c96294aa2b.mp4
