### ISSUE TITLE
3 dots menu parity

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#172]
I hate how there are different things in the 3 dots menu depending on how I access the settings.

Example - image viewer:
![Screenshot_20220203-002158_Aves](https://user-images.githubusercontent.com/50382414/152254390-d4f7b1ac-c0f3-4954-9fd7-37fd7b5f112e.png)

Example - Viewing images in an album:
![Screenshot_20220203-002355_Aves](https://user-images.githubusercontent.com/50382414/152254500-e33bcea5-e882-4b6f-9875-8b240e6351e1.png)

**Comment by deckerst** [comment]
Not going to change. Also, for your sake and mine, I recommend you use an app that you do not hate.
