### ISSUE TITLE
Cannot edit metadata from info overview, only from 3 dots menu

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#173]
https://user-images.githubusercontent.com/50382414/152254789-f3975214-492b-4b3d-b5bb-92e67e22e322.mp4

**Comment by deckerst** [comment]
You actually cannot in both cases. In the first case, trying to edit metadata will let you know which formats are unsupported (if any) so the user can choose to proceed or not with the items that are supported.

**Comment by Donkey-Doug** [comment]
Oh, my bad.
