### ISSUE TITLE
Customize viewer, to match thumbnails settings

### ISSUE THREAD

**Issue by rancidfrog** [deckerst/aves#176]
I have favourite thumbnails disabled but it appears in image viewer:
![](https://i.imgur.com/loTfLWk.jpg)

Settings,
![](https://i.imgur.com/2Kc6Ms3.jpg)

Show favourites is disabled.
Could this apply also to image viewer.
As having another button instead would be more productive for different users; i.e. delete button is more useful to me.

Thank you

**Comment by deckerst** [comment]
The settings in your screenshots are for `Thumbnails`. Thumbnails are the small images that appear in the grid in the Collection page (and a few other places).

To do what you want, take a look at the `Viewer` > `Quick actions` settings. The viewer page is the one where the image or video is displayed in full screen.

**Comment by rancidfrog** [comment]
Found it.
Perfect.
