### ISSUE TITLE
Manually set some folders as "app folders"

### ISSUE THREAD

**Issue by CavaleriOmar** [deckerst/aves#179]
Awesome app, too bad it's a little frustrating that setting albums display with grouping doesn't recognize all app folders.  It would be possible to implement a system to do this eventually...

Or maybe select some folders with special function... or even add new items for grouping (for example "job") ...

**Comment by deckerst** [comment]
Right, the app folder detection is hit & miss.

Aves tries to match the folder name with the name of an app installed on the device (its localized name and its English name). So it can fail in 2 ways:
- false negative: the folder name matches nothing, but it is actually created and managed by an app,
- false positive: the folder name matches something, but it shouldn't be associated with an app.

I believe there is no automated way to avoid these mismatches, but I'll try and provide a way to manually mark/unmark a folder with a user selected app.

Also, Aves has some additional hard-coded mappings for some folder names. As of Aves v1.5.11, there are already these:
- `KakaoTalkDownload` folder -> `KakaoTalk` app
- `Imaging Edge Mobile` folder -> `Imaging Edge` app
Feel free to let me know if you have good candidates like that.
