### ISSUE TITLE
Showing actual size by 4 taps

### ISSUE THREAD

**Issue by iJahangard** [deckerst/aves#181]
Some times I need to see some Media in their actual size

For example to see some of my designs that actually i exported for a especial purpose

**Comment by deckerst** [comment]
I believe it's already supported, at least for raster images larger than the device screen.

For example, here are the steps when opening a 14259 x 10925 image on a Samsung Galaxy S10e:

1) Opening the image (`contain fit`):
<img src="https://user-images.githubusercontent.com/13898333/153741049-8de5d548-f103-40e3-9331-f595799079d7.png"
      width="130" />

2) double-tap once (`cover fit`):
<img src="https://user-images.githubusercontent.com/13898333/153741050-e19fdc62-62f6-49e8-9504-c9b1426d976c.png"
      width="130" />

3) double-tap again (`actual size`):
<img src="https://user-images.githubusercontent.com/13898333/153741055-dd59e6be-4e3e-4d05-b058-ad834b12ba4b.png"
      width="130" />

But there are some limitations:
- if you pan between step 2) and 3), the zoom cycle is reset and double-tap will zoom out to show the full image in `contain` fit,
- SVGs: they do not have an "actual size", so there is no step 3),
- raster images that are smaller than the device screen: they are always scaled up to fit the screen.

Could you explain further what you need? Do you need this for small images (like icons)?

**Comment by iJahangard** [comment]
Uh yeah i need it for icons and stuff like that
I didn't want raster images to be scaled up to fit the display and yeah i want to see them in actual sizes

And .....
I guess the app does not provide actual size for bigger images when you tap 4 times

Let's see the photos that I got from your app and another one after 4 tap:
![Screenshot_20220217-011012_Aves](https://user-images.githubusercontent.com/67248292/154365092-704cc90f-0197-498f-9dd3-6e5ccd7e1a2d.png)
![Screenshot_20220217-011051_QuickPic Gallery](https://user-images.githubusercontent.com/67248292/154365783-5daf0916-a082-4d21-8698-a188d20c2238.png)

Bigger image?:
![Screenshot_20220217-011426_Aves](https://user-images.githubusercontent.com/67248292/154366109-c48a9843-d8d4-49ea-b7d8-44acf272ce1e.png)
![Screenshot_20220217-011417_QuickPic Gallery](https://user-images.githubusercontent.com/67248292/154366183-89e7eef1-5d60-47ef-b5f2-c0c5afa1203b.png)

Let's see a webm video by 512x512 in three situations(only in aves gallery)
![Screenshot_20220217-010853_Aves](https://user-images.githubusercontent.com/67248292/154366416-ff246d0c-6a73-4de6-a9f8-b1d79d7c6df9.png)
![Screenshot_20220217-010857_Aves](https://user-images.githubusercontent.com/67248292/154366434-729b22db-52ac-45cd-a835-db8c9afea4fd.png)
![Screenshot_20220217-010902_Aves](https://user-images.githubusercontent.com/67248292/154366484-dfa5aa5b-21ba-447c-a95e-5097b34d86d3.png)

You see i don't think they're in actual size
Please do something about it, I really need that feature for both videos and images
