### ISSUE TITLE
Selecting images

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#19]
Make it possible to select an image by long pressing it. Currently, long pressing does nothing.

UPDATE: It seems to work now. I do not know why it did not work earlier. I will take note if it fails again.

**Comment by deckerst** [comment]
Long pressing should select images in the current version v1.3.0 (and
in the next release, it will also be possible to long press + drag, to
select multiple items at once).

So it sounds like a bug.

You are long pressing a thumbnail in the collection view, right? Could
you give some details as to your device model and android version?

**Comment by Donkey-Doug** [comment]
Device: Xiaomi Mi 9T Pro
OS: LineageOS 17.1 (without google play services and without microg)

**Comment by deckerst** [comment]
I will close this issue but feel free to reopen it if you can provide further details.
