### ISSUE TITLE
Crash on attempting to empty/delete recycle bin content

### ISSUE THREAD

**Issue by DeiAsPie** [deckerst/aves#190]
## To Reproduce
1. Go to 'Aves Gallery'
2. Delete a bunch of pics
3. Go to Recycle Bin
4. Attempt to empty the recycle bin/delete a selection of images

## Expected behavior
Just delete the stuff and show empty recycle bin kinda message

## System information:
Aves version: 1.6.0-izzy (Build 1066)
Flutter version: 2.10.1 (Channel stable)
Android version: 11 (SDK 30)
Device: Xiaomi MI A2
Google Play services: ready
System locales: en_US
Aves locale: en

**Comment by deckerst** [comment]
Thanks for the report! I can't reproduce this with my own test devices, but I just saw similar Crashlytics reports (from an LG device with Android 7.0). I'll take a look.

**Comment by deckerst** [comment]
releasing v1.6.1 with the fix
