### ISSUE TITLE
Restoring from Recycle Pin: Modification-Timestamp reset

### ISSUE THREAD

**Issue by ChillDuder** [deckerst/aves#192]
**Describe the bug**
Recycling a image from the new recycle-pin (thank you very much!) resets the modification timestamp of the file to current time/restoring time.
In the app itself the image is shown/listed with correct time (e.g. time of photo taken) because of metadata of the image (i guess).

I dont know if this is a bug-report, or a feature request (and dont even know if changing mod.timestamp/'touch' is possible without root on android)

**To Reproduce**
1. capture photo & notice time
2. wait a few minutes
2. delete it in aves with recycle pin switched on
3. go to recycle pin view and restore that photo
4. in any file explorer look at the files properties at modification time.

**Expected behavior**
original modification timestamp from when the photo was shot on restored file

**Additional context**
Thank you very much for that great app!

**Comment by deckerst** [comment]
The issue, and limitations, of the modification date is discussed in #111.

Basically, with modern permission systems it's out of reach. That's one of the reasons I think the modification date is not a valuable field, and Aves uses the reliable metadata date instead.
