### ISSUE TITLE
Miniature Preview

### ISSUE THREAD

**Issue by MajinSaaY** [deckerst/aves#193]
**Is your feature request related to a problem? Please describe.**
I need a better way to nagivate through images/videos while in viewer page

**Describe the solution you'd like**
A miniature previewer

**Describe alternatives you've considered**
F-Stop Gallery have this feature (and some windows apps too: ImageGlass, Nomacs...)

**Additional context**
https://imgur.com/a/VLyraWL

**Comment by deckerst** [comment]
Good timing, I was going to work on it soon.

It will most likely be similar to the miniature preview already in use for bursts, multipage TIFF/HEIC, and the Map page:
<img src="https://user-images.githubusercontent.com/13898333/155442049-a617d75e-5a4b-4e20-a8f2-5f50ca179cbc.png"
      width="300">

**Comment by MajinSaaY** [comment]
That's great! Can't wait to see it working. Nice app btw 😉
