### ISSUE TITLE
Preview button when selecting items

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#197]
when i select multiple items, it would be useful to be able to have a full sized preview of that item. maybe an extra button on each item would do the trick

**Comment by deckerst** [comment]
If I understood correctly, that's what Samsung Gallery does:
<img src="https://user-images.githubusercontent.com/13898333/156147548-6dbb21e1-52c4-499b-9fa0-605db73a3d5f.png"
      width="250">

Google Photos takes another approach with a single FAB to change the layout into a zoomed in mosaic, so users can see the uncropped images but stay in the grid. It's pretty clever.

In the meantime in Aves, you can also pinch-to-zoom the thumbnails while you select (in case you didn't know). It's not fullscreen, but you may get large enough thumbnails to help you pick your selection.

**Comment by Ingegneus** [comment]
I personally prefer the samsung approach bc you can zoom into the picture which is useful, but a combined approach would be be pretty killer too.
