### ISSUE TITLE
show the facetag position in the image

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#199]
facetags are not displayed in the image, but only listed with the other tags. knowing which person is which is a key feature of facetags.

**Comment by deckerst** [comment]
Are you talking about face tags as described in #69, or another kind of tag?

**Comment by Ingegneus** [comment]
Should be the same, but i am not sure since i am not that proficient in this field. I use digiKam for tagging and i don't know if that is the same type of facetag as picasas

**Comment by deckerst** [comment]
You could share one of your tagged pictures here (or email me one if you want to avoid this public space) so I can check the metadata and confirm.

I'll close this issue in favour of #69. Feel free to upvote/subscribe to it.

**Comment by Ingegneus** [comment]
here is an image. i hope gihtub doesnt remove the metadata
![740full-daniel-craig](https://user-images.githubusercontent.com/78076361/157757921-d72126a7-70b8-409b-83d4-81ebf615bb98.jpg)
.

**Comment by deckerst** [comment]
Thanks!

There are 2 kinds of metadata here:
1) regions: giving the rectangle containing the face, and an optional name (in the standard "regions", and Microsoft Photo parts of XMP),
2) tags: just the name (in IPTC, and in the Dublin Core, DigiKam, MS Photo, Lightroom, Mediapro and ACDSee parts of XMP).

Only the first kind is relevant to your feature request. I intend to use the "regions" metadata, but it's nice to know MS created redundant tags.
