### ISSUE TITLE
Rating issues

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#204]
I don't know i this counts as a bug, but it doesn't seem as if Aves is reading and writing the ratings metadata to and from files. In the metadata section under the picture the rating is correct, but it is not displayed correctly among the other tags

**Comment by deckerst** [comment]
Ratings are stored in XMP (mostly). There are some standard non-software specific XMP tags but any software maker can freely add redundant tags (ACDSee, Microsoft Photo, DigiKam love to do this, but literally anybody can add anything to XMP, it's open).

Aves writes the standard one and ignores the others (with some exceptions). I'd have to check which tags for ratings specifically, but it's the general approach.

If you think I misunderstood your issue, please attach an image that you rated. Or you could also search for "rating" in the `Info` page of that image and attach the screenshot of that.

**Comment by Ingegneus** [comment]
From my understanding, this image should have a rating in aves, but i am not seeing it.
![IMG-20220304-WA0006](https://user-images.githubusercontent.com/78076361/158261055-cf49faab-5627-4445-8cfd-209aa69865aa.jpg)

**Comment by deckerst** [comment]
I opened the attached image and the rating is there. It's searchable by rating, there's the thumbnail overlay, and the rating filter in the `Info` page too. By the way, this particular image includes the standard rating tag (XMP), as well as the variants from MS Photo (XMP and non-standard Exif) and ACDSee (XMP).
<img src="https://user-images.githubusercontent.com/13898333/158281018-d5275d22-cc13-4d00-b1df-dfca1d1ded63.png" width="200"> <img src="https://user-images.githubusercontent.com/13898333/158281025-a68c92b4-cb63-4612-a68f-0a8c5a95e8e9.png" width="200"> <img src="https://user-images.githubusercontent.com/13898333/158281029-bc5dbf4d-ee2b-4710-9a78-ff4a299f47ce.png" width="200">

Ratings started being supported in Aves v1.5.10 (2022-01-07). It's possible that the ratings do not appear if the images were catalogued with an older version. In that case, you can select these images and `Rescan` them (or use `Rescan` on the whole collection). Does it apply to you?

If ratings don't show up with new images (or rescanned images), there's likely a bug. In that case please attach here your system info and logs, following instructions inside the app at `About` > `Bug Report`.

By the way, more details about rating reading in Aves [here](https://github.com/deckerst/aves/issues/143#issuecomment-1003948082).

**Comment by Ingegneus** [comment]
Ok rescanning did the trick. Thank you.
