### ISSUE TITLE
Connection with Cloud Services

### ISSUE THREAD

**Issue by git-pietro** [deckerst/aves#208]
Don't we all know the struggle of Cloud Services having an app that isn't made for viewing img/vid? 
So why don't just view let's say a OneDrive folder with only images inside from your Gallery App, like connecting it.
Would be nice if you could have an saving path that saves IMG/VID directly to an Gallery Album (individual) that is storing the data intern and extern on the cloud or even only on the cloud.

**Comment by deckerst** [comment]
I think this is more or less duplicate with #126. People there mostly mentioned Nextcloud, but for now it lumps Google Drive, One Drive, etc. all in the same issue. You could show interest in #126 by adding a thumb up reaction to the top post, and subscribe to the issue to get updates from the discussion.

> Would be nice if you could have an saving path that saves IMG/VID directly to an Gallery Album (individual) that is storing the data intern and extern on the cloud or even only on the cloud.

I'm not sure I follow. Are you suggesting to synchronize a specific local folder with a remote album? It seems easier to leverage the existing syncing capabilities of official cloud apps. What I mean is that the syncing can be triggered in the background thanks to a different app. It does not need to happen in the gallery.
