### ISSUE TITLE
Add mp3 audio 

### ISSUE THREAD

**Issue by gun4qmm7h** [deckerst/aves#209]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the app aves to add a way to see and play audio files like .wav, .mp3 ,and other formats.

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerst** [comment]
Aves focuses on visual media (photos & videos), and audio media having nothing much in common with visual media. The way to consume, index, search, edit them... everything is different.

So, this is out of scope for this app and I'll close this issue, but I'm really interested to hear why you think it would be a good fit.
