### ISSUE TITLE
Remove outline around icons, albums, filters etc.

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#21]
Some elements in the app have an outline, for example the three visible buttons favorite, share and the 3-dots menu. I believe this gives the app an outdated look. As far as I am aware, no other (modern) app does this.

**Comment by deckerst** [comment]
I welcome feature requests and bug reports, but I will probably reject
styling change requests: icons, fonts, colors, corner shapes, etc.

That said, I consider adding theming options, which would include an
alternate icon set.

**Comment by Donkey-Doug** [comment]
You designed an app according to your liking and you are sticking with it. I respect that.

However, be aware that this app has many potential users. By designing an interface very different from most other android apps, you could be putting off some potential users. I recommend making it possible to enable/disable the outline and changing the font in settings to reach a wider audience if you would prefer to keep the current look.
