### ISSUE TITLE
Toast in viewer blocks the quick action buttons

### ISSUE THREAD

**Issue by HoyanMok** [deckerst/aves#218]
**Is your feature request related to a problem? Please describe.**
I have been using Aves for a while. In older version, the quick action button is on top so there is no problem. 
While after updating the layout changed so that the quick action buttons lie below, 
so every time I delete, rename, etc. an image, an info toast (see screenshot below) pops up, blocking the quick action buttons.
I have to wait for the toast to disappear so that I can continue managing my images, which is frustrating.

**Describe the solutions you'd like**
The position of either the quick action buttons or the toast shall be moved, or the toast shall be interactively remove (by a swipe). 
Here are the possible options:
* Move the toast a little higher so that it would not block the buttons?
* Use old layout that the quick action buttons is located at top right
* Allow user clear the toast with a swipe (like clearing notifications)

**Additional context**
Screenshot:
![IMG_20220405_120845.jpg](https://user-images.githubusercontent.com/58337895/161677557-b72e79a8-d6cf-47bb-9c34-834c658c1b85.jpg)

**Comment by deckerst** [comment]
Agreed, i thought the same thing but didn't come to address it yet.

The buttons will stay below, as it's more convenient for one-hand use, but I'll find a way to move the toasts away.

By the way, the current toasts are swipable, but with a swipe down, not horizontally.

**Comment by deckerst** [comment]
Snack bars are now dismissible with an horizontal swipe instead of a down swipe.

As for the Viewer page, snack bars will avoid quick actions and thumbnails at the bottom. I'll leave it at that for now, but I'm also considering displaying toasts at the top, just for that Viewer page. We'll see!
