### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dude-shah** [deckerst/aves#221]
**Is your feature request related to a problem? Please describe.**

I've been using Aves for quite a while as my default gallery app and it's a great app, there are some feathers that i wanna request.

Size of image/video .. It's a very basic feature that every phone default gallery app has ... The app shows dimension and date, time but doesn't show size.

Location (where that image/video is stored in my phone storage) 

**Describe the solution you'd like**

The solution I'm looking for is ... Make a another tab in more option for **Details** which shows size, dimensions, date, time and name of the file and where it's stored.

Something like this.

![IMG_20220410_072039.jpg](https://user-images.githubusercontent.com/63038690/162598399-c8e452ea-43ca-4db1-b411-572955b56e01.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerst** [comment]
Maybe I misunderstood, but I believe everything you want is displayed at the top of the `Info` page, which is reachable with a swipe up from the viewer. I'm talking about this screen:
<img src="https://raw.githubusercontent.com/deckerst/aves_extra/main/screenshots/play/en/3.png"
      width="250">

And you can come back to the viewer from the `Info` page by swiping down or using common buttons/gestures for "back".

**Comment by dude-shah** [comment]
Sorry my bad ... I didn't knew this existed ... 
You should a little guide step for first timers

**Comment by deckerst** [comment]
No worries. In previous versions there was also a button to reach that page, but it got removed to make the menu simpler. You're right that it would nice to provide some guidance. I'll think about it!
