### ISSUE TITLE
Scrolling breadcrumbs

### ISSUE THREAD

**Issue by basings** [deckerst/aves#226]
Currently, it's difficult to find the next folder from within the "all collection" view. 

This is not a problem when folder sizes are small but if there are hundreds or thousands of pictures in a folder, it's difficult to search for the next folder. If folders were collapsible, it would be pretty much a no brainer to go to the next folder without scrolling. Breadcrumbs can also help to navigate large collections. Breadcrumbs are small bars, squares, dots at the scrollbar to indicate the position of something noteworthy, like a bookmark. 

This is only relevant when images are grouped.

**Comment by deckerst** [comment]
I intend to provide breadcrumbs. But you raise an interesting point with the album grouping.

Currently, when the collection is sorted by date and grouped by album, and the user fast-scrolls (grabbing the scroll thumb), it displays next to the thumb a popup with the matching album and month. What I had in mind was to move that popup away (at the top or bottom of the screen), and show breadcrumbs for the date (year, month or day, according to the collection and available space). So, breadcrumbs related to sorting, related to grouping, or for both? That is the question...

And I'm not a fan of the collapsible groups.
