### ISSUE TITLE
[FR] Indicate default Folder creation path

### ISSUE THREAD

**Issue by basings** [deckerst/aves#227]
It was not obvious to me where the app creates new albums. It's /storage/emulated/0/Pictures/ but it could've been the internal app folder, subfolder or another one. My experience is that image gallery softwares use the term "album" for an internal sorting concept. Here, album refers to a normal folder. I couldn't find a setting like "default album path" or something comparable. I'd consider myself a power user for whom the location is important because I use syncthing to sync images. I'm completely fine with the current location but it should be easy to know which one it is.

Moreover, I couldn't find the location of the folder (album) on my device from within the app. I had to create a test folder and move an image into it such that I could search with a file browser for the image to find the location. I am not sure why I can't find the folder/album without moving an image into it. I am not sure why I can't find an empty folder in the file browser. It's like the folder (album) isn't created with "create album" but with moving content into it.

**Comment by deckerst** [comment]
> It's /storage/emulated/0/Pictures/

Indeed! It's a safe and semantically meaningful place to put visual media.

And here's a tip for you, as you seem interested in the topic: you can create subdirectories when creating an album, e.g. providing the album name "a/b/c" will create the album at `[storage]/Pictures/a/b/c/`.

> My experience is that image gallery softwares use the term "album" for an internal sorting concept.

My experience is that apps aimed at casual users identify folders as albums, and apps with advanced organization features distinguish folders and albums (sometimes calling folders "albums", and albums "virtual albums", to add to the confusion).

> I couldn't find a setting like "default album path"

Right, there's none, and I don't intend to provide one.

> It's like the folder (album) isn't created with "create album" but with moving content into it.

Correct. If you want to create empty folders, you can do so in a typical file manager app. That said, empty folders are not listed among media albums in Aves, so you would still need to create the album in Aves if you want to move media to it.
