### ISSUE TITLE
Hide scrollbar in albums view

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#23]
I believe most people do not have that many different albums. On my device, the number of albums do not even fill up the entire album overview screen. However, everytime I touch the screen, the (in my case useless) scrollbar appears on the right side.

**Comment by deckerst** [comment]
Commit https://github.com/deckerst/aves/commit/695f8de2a4ac69d68f57e95654a09dec20f5d5ce should hide the scrollbar when it is useless.
