### ISSUE TITLE
Password protect hidden item visibility

### ISSUE THREAD

**Issue by Pauler221** [deckerst/aves#233]
I think the "hide folder" functionality is pretty useful. The only downside is that just in case if someone finds a way into the settings one could easily unhide hidden folders. It would be nice to password protect removing hidden directories from the settings.

I don't think there's a need to implement a full fledged encryption method into the app since there are already other apps for encrypting files. A simple solution like provided by the app "simple gallery" (which password protects hidden item visibility) would be sufficient in my opinion.

Thx for a great gallery app!

**Comment by deckerst** [comment]
Hiding folders (or other filters) is not meant for secrecy. It is useful to users who do not want to see in the gallery some media that should stay visible to the rest of the system (e.g. album covers in their music collection).

What you want is a vault / secure folder / locked folder. You can upvote #114 with a thumb-up reaction, or subscribe to it. 

I'll close this as duplicate.
