### ISSUE TITLE
Is there any way to get rid of the annoying 5 second count down that offers you to show a picture after moving it to a different album?

### ISSUE THREAD

**Issue by KevinStars** [deckerst/aves#236]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by deckerst** [comment]
Nope. Feel free to use the [discussions](https://github.com/deckerst/aves/discussions) tab for further questions.
