### ISSUE TITLE
Hide unnecessary info

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#24]
Make it possible to hide the info at the bottom (filename, date, resolution) when viewing an image/video.

**Comment by deckerst** [comment]
Do you mean to hide it altogether, or to pick and choose which info is
of interest to you?

**Comment by Donkey-Doug** [comment]
Why not both?

I personally prefer to have zero clutter. If I need more info, I click on the 3-dots menu and then on "info" :).

**Comment by deckerst** [comment]
Ok, I'll add options for this.
