### ISSUE TITLE
In map view, when going to fullscreen map, map disappears and just a detailed grid appears

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#241]
An example is when in the camera folder, with say 300 photos, I go to map view and the map loads very fast displaying all the photo icons on the map. The next step in inconsistent in that it doesn't happen every time but it happens frequently and that is when clicking the map to go full screen view, the map and icons disappear and you are left looking at just a grid pattern. Pinching and zooming doesn't bring the map back nor does waiting for a minute or so. You then have to touch the map again to go back to the smaller view. Now if you touch the map again and go to the full view it will appear correctly. This can happen multiple times and I haven't been able to narrow it down to be 100% reproducible.

On map view, click the screen to go to full map view.
Only a grid appears.
Touch the screen again to go back to normal map view. Sometimes this doesn't work and you have to pinch and zoom, then click again to return to normal map view.
The app never crashes and other features work normally.

I expect the normal map go to full screen map view, every time, when clicking on the map.

Aves version: 1.6.4-play (Build 70)
Flutter version: 2.10.4 (Channel stable)
Android version: 12 (SDK 32)
Android build: SP2A.220405.004
Device: Google Pixel 6 Pro
Google Play services: ready
System locales: en_AU
Aves locale: system -> en
Installer: com.android.vending
![Aves_full_screen_map_view_20220425-115944](https://user-images.githubusercontent.com/89827729/165008832-bf12884a-015c-4f2b-88ce-8cb4f6288867.png)

**Comment by deckerst** [comment]
Thanks for the report.

Sadly, I'm already aware of it and I don't have a solution at the moment. I believe it's a bug in the framework I'm using.

Related bugs:
- https://github.com/flutter/flutter/issues/28493
- https://github.com/flutter/flutter/issues/40284

**Comment by petazonk** [comment]
Ok thanks. Hopefully this will formalise the bug on Aves and other people
won't need to add it again.

**Comment by deckerst** [comment]
The good news is that upgrading to the latest version of the framework (Flutter v3.0.0) fixes this. The transition is still glitchy sometimes, but at least the map doesn't disappear.

The bad news is that the map is now completely broken on older devices (API <=22).
Related bug: https://github.com/flutter/flutter/issues/103630

So I'm delaying the current release of Aves, while I ponder whether to downgrade or wait for a patch in the framework.

**Comment by deckerst** [comment]
Reopening. The previous workaround no longer works with the latest version of Flutter -_-

Native plugin issues are still popping up with Flutter 3:
- https://github.com/flutter/flutter/issues/103686
- https://github.com/flutter/flutter/issues/107313

On the plus side, Google Maps layers are now working again on Android Lollipop (API 21 and 22).
