### ISSUE TITLE
Make optional the ability to write reverse lookup information to XMP metadata in photo

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#242]
There is already an option show the location in the viewer mode, eg Location Icon: Australia, Queensland, Brisbane ...
Allow this information to be written as a tag such that when searching for Brisbane, it will show up. I realise that you can achieve the same by looking at the map of Brisbane and then clicking on the GPS tag at the top but it would be nice to be able to just search for keywords generated from a reverse lookup. Reverse GEO coding exists in DigiKam, but it would be great to have an easier way of doing this on your phone.

Have an option that allows you to write the reverse lookup of the GPS coords to the metadata. It should work for all photos selected, eg similar to file renaming. A search for say Brisbane would then bring up all tags with Brisbane in the tag.

**Comment by deckerst** [comment]
I see the value of this, but i'm curious about your search process.

> when searching for Brisbane, it will show up

If you use the Search page, it already surfaces tags, countries and places. Typing `Brisbane` should already show it as a `place`. Do you not get these results? Or you would like tags for the benefit or search in other software?

> write the reverse lookup of the GPS coords to the metadata

The raw lookup results are not very clean or consistent, so I'd need to think about what data to transfer as tags.

For example, in a photo taken in Paris with the following result:
1) France
2) Île-de-France
3) Paris
4) address details

Should it commit 1 and 3 to be consistent with the Country / Place concept? Or 1 2 3 4 for completeness? Or 1 2 3 as a compromise?

**Comment by petazonk** [comment]
Yes location by name already works in Aves which is great but it would be
great if it worked in other software, eg Digikam

I think if it wrote all places that would be good. More is better in this
case. Double checking to see if it is compatible with digikam would also be
preferable.

**Comment by deckerst** [comment]
> I think if it wrote all places that would be good. More is better in this case.

You may underestimate how much noise the address details would bring to search results. Also, it just occurred to me that I don't store in Aves DB the geocoding result details that are not used in the app search. So I'll need to consider if this niche feature justifies making the DB larger.

> Double checking to see if it is compatible with digikam would also be preferable.

Maybe I misunderstood your initial request, but I thought you meant to save the data in basic XMP tags, just like other manual tags. Did you mean to save them in other location-specific tags (like the "Country" and "Sub-location" tags in the more-or-less obsolete IPTC standard)?

**Comment by petazonk** [comment]
Yeah it is always difficult making the best decision so all the noise might
be too much. Maybe just saving the street name or suburb might be best.
Maybe even an option in the config?

Yeah saving the information as a tag probably under XMP but as XMP that is
popular with other open source software like DigiKam.

This feature could also be used when sharing photos if people didn't want
to send geotag but are ok with something like city.
