### ISSUE TITLE
Allow picking multiple in pick mode

### ISSUE THREAD

**Issue by chaptergy** [deckerst/aves#249]
**Is your feature request related to a problem? Please describe.**
When picking a file using aves (so some app opened the file browser and I selected pick via aves) it is only possible to pick a single file.

**Describe the solution you'd like**
Ability to select multiple files in pick mode, just like it is possible in normal gallery mode.

**Describe alternatives you've considered**
Pick the files using my file browser

**Comment by deckerst** [comment]
Will be in the next release. Tested with the single pick (attach > "Gallery" > "Open in...") and multiple pick (attach > "File" > "Gallery" > "Open in...") intents from Telegram. I suppose other apps request picking the same way, but let me know if it doesn't work with your apps.
