### ISSUE TITLE
Feature Request: Add Media Type to View Menu

### ISSUE THREAD

**Issue by onkoe** [deckerst/aves#250]
**Is your feature request related to a problem? Please describe.**
In albums and favorites, it is difficult to find *just* videos. There is no filter for it in the More > View menu. 

**Describe the solution you'd like**
Implement a type filter in the More > View menu. I would just add another tab [here](https://user-images.githubusercontent.com/66580279/168148764-f7eab660-dde7-442e-b169-9f3e267abcbc.png) and add a couple checkboxes. 

**Describe alternatives you've considered**
You could always add another menu with type filters ([like in the Infinity for Reddit client](https://user-images.githubusercontent.com/66580279/161600883-5d5dce80-8fae-4957-9e70-1ae237ff52b3.png)). Alternatively, you can add a sort option (e.g. images, then videos), but that's a bit messy in my view. 

**Additional context**
Should be good. Feel free to tag me with any questions you may have. Thanks for your work on this app - it puts the AOSP gallery to shame!

**Comment by deckerst** [comment]
@onkoe I think users should leverage the `Search` page for any kind of filtering and refining.

For example, after opening your favorites, you then tap the app bar to show the Search page, then tap on `Video` and it will add the filter, so now you have "Video" and "Favorite" at the top. Adding filters like this is quick and flexible enough to accommodate all sorts of filtering (not only media type).

As for video albums, it's not exactly what you ask, but after opening videos, you could sort by date and group by album. The next version of Aves (coming soon) will display breadcrumbs along the scroll bar when grabbing the scroll thumb (cf #226), so it will also be easier to see and find albums for a filtered collection (favs, videos, whatever).

I will close this issue as I believe adding filtering to view settings is redundant and less powerful than the current features to add, combine and remove filters.
