### ISSUE TITLE
Ability to search internet for an image

### ISSUE THREAD

**Issue by iJahangard** [deckerst/aves#252]
As long as you know there's an ability to search an image in the internet by a search motor like Google or etc.
The most well known app is Google lens (etc) which needs Google app to be installed (you now how large is that app) that makes me crazy , for an image search you have to install two apps with plenty of unnecessary stuff which i personally always debloat them from my system (& you?)

There is some third party apps in play store that can do that thing which are so light weight but a gallery app with that feature is something awesome
It can be like a layout with a clipping box you simply resize an press search and then it opens up in the browser

So that would be great if you bring this option to your great app
Thanks in advance

**Comment by Donkey-Doug** [comment]
Lile #99
