### ISSUE TITLE
Bottom navigation bar not hidding system buttons

### ISSUE THREAD

**Issue by hycday** [deckerst/aves#258]
**Is your feature request related to a problem? Please describe.**
Some devices have onscreen system buttons (back/home/multi) and not physical ones.
When opening the app, with option to show "Bottom navigation bar", the navigation bar overlaps bellow the system buttons.

**Describe the solution you'd like**
"Bottom navigation bar" should be slightly moved up to not overlap with the system buttons

**Describe alternatives you've considered**
Choice to have the navigation bar on top (sticky)

**Additional context**
![Screenshot_20220526_095446_deckers thibault aves](https://user-images.githubusercontent.com/11727370/170426248-c7110f7f-460f-47b8-acdc-2d4b543c17af.jpg)

**Comment by deckerst** [comment]
Thanks for the report. It's actually a bug, as Aves is supposed to place the bar above the system buttons. You can see how it does so on this screenshot:
<img src="https://raw.githubusercontent.com/deckerst/aves_extra/main/screenshots/play/en/1.png" width=300 />

By the way, you don't have the same issue with the viewer page? The quick action buttons are also supposed to place themselves above the system buttons, like so:
<img src="https://raw.githubusercontent.com/deckerst/aves_extra/main/screenshots/play/en/2.png" width=300 />

Could you please navigate in the app to `About` > `Bug Report`, copy your system information, and paste it here?

Also, do you use a custom ROM?

**Comment by hycday** [comment]
wow, impressed with prompt reacivity !

viewer page displays it all good (like your screenshot)

Aves version: 1.6.7-play (Build 73)
Flutter version: 3.0.1 (Channel stable)
Android version: 10 (SDK 29)
Android build: VOG-L29 10.1.0.150(C431E19R2P5)
Device: HUAWEI VOG-L29
Mobile services: ready
System locales: en_LU, de_LU
Aves locale: system -> en
Installer: com.android.vending

**Comment by deckerst** [comment]
Reproduced on emulators (API 29, API 22, probably API independent).

**Comment by hycday** [comment]
some steps to "fix" this (of course, not a solution due to complexity of steps):

1- open a video
2- click play
3- swipe down to exit video
4- the navigation bar is now correctly displayed above the system buttons

**Comment by deckerst** [comment]
Yes, I found out you can also:
- rotate the device, and rotate back (if you have auto-rotate, that is)
- in the viewer page, you can toggle the overlay off and on.

Either will make the device refresh its metrics. My diagnostic is that in some environments, the device initially provides the wrong metrics when the app start. Don't know why, but I have to find a workaround.

**Comment by hycday** [comment]
confirmed both reproduced on my device.

**Comment by deckerst** [comment]
@hycday Aves v1.6.8 got released with a few fixes, including this one. I found a workaround that seems to solve the issue when I tested on an emulator, but if you could confirm that it works also for your device, that would be great.

**Comment by hycday** [comment]
Confirmed fixed after updated to v1.6.8 ! 
Thank you @deckerst
