### ISSUE TITLE
Albums are not displayed as Home

### ISSUE THREAD

**Issue by hycday** [deckerst/aves#259]
**Describe the bug**
When home is albums, no albums are displayed

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Navigation'
3. Choose "Albums" for "Home" option
4. Close app and reopen
5. No albums are shown despite having albums (and if Go to 'Albums' from side menu I can see the albums)

**Expected behavior**
Albums should be shown when Home = Albums

**Screenshots**
![Screenshot_20220526_103501_deckers thibault aves](https://user-images.githubusercontent.com/11727370/170434323-cfa5fcab-d5b3-47aa-b52b-1d1bd1ce35a3.jpg)
![Screenshot_20220526_103456_deckers thibault aves](https://user-images.githubusercontent.com/11727370/170434332-7e6766a3-968a-48ba-bfa1-508cb9fa0b1c.jpg)

**System information and logs:**
Aves version: 1.6.7-play (Build 73)
Flutter version: 3.0.1 (Channel stable)
Android version: 10 (SDK 29)
Android build: VOG-L29 10.1.0.150(C431E19R2P5)
Device: HUAWEI VOG-L29
Mobile services: ready
System locales: en_LU, de_LU
Aves locale: system -> en
Installer: com.android.vending

**Comment by deckerst** [comment]
Could you please attach the logs? (you can export them from `About` > `Bug Report`)

If you navigate to the collection and back to the Album page, without leaving the app, do you see them?

**Comment by hycday** [comment]
attached logs.
once I opened app and don't see Albums on Home, if I go to menu, click on "All collection", then back to "Albums", I see the albums yes.
[aves-logs-20220526_110505.txt](https://github.com/deckerst/aves/files/8777011/aves-logs-20220526_110505.txt)

**Comment by hycday** [comment]
Confirmed fixed after updated to v1.6.8 ! 
Thank you @deckerst
