### ISSUE TITLE
material design 3

### ISSUE THREAD

**Issue by andsofine** [deckerst/aves#261]
it would be nice if you switched to material design 3 then there would be no problems with using colors on android 12

**Comment by deckerst** [comment]
I may adopt parts of M3 (likely the typography, probably some controls) but not everything. As for the colors, I explained in #260 why I don't intend to adopt the whole dynamic scheme. It's not a technical limitation, it's an aesthetic choice on my part.

**Comment by deckerst** [comment]
> stands out from other applications and the system

I guess you're on a Pixel phone and referring to Google apps.

In my case, I only see that Google apps harmonized their looks to the latest Google fashion. On a Samsung phone, all the system apps follow their own One UI style. As for the other apps I'm using, they each have their own style: Firefox, Telegram, Bookshelf, KakaoTalk, Merlin, AntennaPod, Musicolet, MS Office, VLC...

But more importantly, I *do* want Aves to be unique and recognizable by its UI. Originality over conformity.

**Comment by deckerst** [comment]
#266 Your dream come true ^^

**Comment by deckerst** [comment]
No idea! That thing is unrelated with me. I suppose it's just an unscrupulous company which intends to make an Aves copycat and put in some ads or something later on.

Anyway, you can find the original offer [here](https://www.upwork.com/freelance-jobs/apply/Create-android-app-from-github-sourcecode_~018f4600585fd657d2/).
