### ISSUE TITLE
Create new folder

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#27]
Make it possible to create a new folder form the folder overview. After creating a new folder, the user cna copy/move photos to this folder. Currently the user has to create a new folder using a file explorer.

**Comment by deckerst** [comment]
It it already possible to copy/move to a new folder. When selecting a
folder to copy/move items, you can create a folder at that point.

As you request, some users prefer a workflow where they create the folder
in advance, and then select items to move. I may allow folder creation that
way in the future, but it's low priority for now.

**Comment by Donkey-Doug** [comment]
Agreed that this is low priority.
