### ISSUE TITLE
Add support for the tags in image name

### ISSUE THREAD

**Issue by CavaleriOmar** [deckerst/aves#270]
It would be possible to have a second support for tags, similar to that of TagSpace, for example:
```
nameimage[tag1 tag2].jpg
```

It is true that this type of tag does not support space in the name (at least in theory), but it allows you to use a tag, however fake, with any application that allows searching.

It might seem like something one can do for oneself by simply renaming the image, but when you use over a hundred tags you often don't remember them all or you can end up spelling it wrong sometimes (effectively rendering the tagging useless).

In practice, on the left and in the center you can see the name of the file from Aves, on the right you see how the tags are in TagSpaces
![GridArt_20220611_135919683.jpg](https://user-images.githubusercontent.com/54171779/173187049-77247e17-9c1a-4b00-b8b2-d779f020199e.jpg)

**Comment by deckerst** [comment]
Thanks for the suggestion, but it's not something I will support.

Aves is an opinionated product. One core principle is to favor the metadata standards available to image and video formats.

I understand the benefits that tags in file names do not depend on formats and are available to generic file browsers, but for many reasons this is an inferior solution compared to standard metadata tags. These standards are not vendor specific. Most desktop photo viewer/managers already know how to process them, and it's about time the mobile world catches up.

The real question is: why would you search tags in file names, when you can search them in a semantically stronger way with Aves and other metadata-aware software?

**Comment by sourcevault** [comment]
I have run into a practical problem with this. How should I tag **all possible** _different_ types of files - `.jpg`, `.pdfs`, `.mp3`, `.amr`, `.mp4`, etc. The filename based system used by tagspace - with all it's limitations and drawbacks - seems to work for now atleast. Sometimes, getting _something_ is better than getting **nothing**. Aves would work really nicely with tagspaces if it was possible to incorporate filename based tagging.

> The real question is: why would you search tags in file names, when you can search them in a semantically stronger way with Aves and other metadata-aware software?

I agree 💯, but given how there is no universal method of tagging **any** filetype, how would you go about convincing everybody to adopt the same standard ? even among image files there is no universal standard - for example no tagging app on desktop does integration with `aves`. The shortest and simplest method to go about this is the filename method. The worst outcome is not a _sub-optimal_ tagging standard, but **no tagging** as all.
