### ISSUE TITLE
Custom grouping and sorting for albums

### ISSUE THREAD

**Issue by RafeeDaBoy** [deckerst/aves#276]
**Is your feature request related to a problem? Please describe.**
Currently albums can be sorted by name, date and item number and grouped by tier and storage volume.

**Describe the solution you'd like**
Allowing to reorder albums by just dragging them would really useful as well as creating custom groups would be really useful.

**Comment by deckerst** [comment]
1) custom sort: duplicate of #231 
2) custom groups: I won't do that, but there's a request for nested albums #268
