### ISSUE TITLE
long tag names issue

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#277]
when a tag is too long there is no way to know what the full name is. it could be useful to let the text "scroll" through or something. my tags are all hierarchical so I often can't tell which tags I am tapping.
![image](https://user-images.githubusercontent.com/78076361/176484198-15048571-aafe-452d-975c-2f23dd4fe2be.png)

**Comment by deckerst** [comment]
I have the same issue with album names myself. Here's what I've considered so far:
1) use "marquee" labels. It is what you've suggested. The major flaw is that scrolling takes time, and users are always in a hurry.
2) change the maximum width of these filter chips. Not a fixed size like it is now, but something like half the screen width. It would feel more or less like the current layout, but when you switch to landscape you see twice more right away. It wouldn't help normal users that are not good with lateral thinking though.
3) add the full name of the chip as a label in the long press menu of that chip. Useful one by one, but not for comparing multiple chips at once.
4) add title filtering to album/country/tag page. Title filtering combined with list view would solve the issue on these pages, but not for search/info/stats.
5) remove the width limit in some context, e.g. when there's a single chip on the Collection page. 
6) remove the width limit altogether, but it would break the layout in various places.

**Comment by Ingegneus** [comment]
Maybe 1, 2 and 3 mixed together?
Another option might be to let the text wrap in the button and either reduce the font size or increase the height of the label/button whatever you want to call it.
![image](https://user-images.githubusercontent.com/78076361/176662811-16ebac1b-c56f-41b7-91d2-a1bf17ed930b.png)

**Comment by deckerst** [comment]
Aves v1.6.11 is released. It includes the improvements 2) 3) and 5) described above. Please give it a try and let me know if it helps.
