### ISSUE TITLE
Apply a dynamic background color for the photo viewer when in light mode

### ISSUE THREAD

**Issue by DodoLeDev** [deckerst/aves#278]
**Is your feature request related to a problem? Please describe.**
Coming from the MIUI Galery app, I loved their dynamic background color they used when viewing photos in light mode.
- When menus are displayed, the background is white
- When entering fullscreen mode (menus hidden), the background progressively turns dark!

**Describe the solution you'd like**
Could you please add this as “Dynamic background” in the background config of the photo viewer in settings?

**Describe alternatives you've considered**
I lived without this feature 😱

**Additional context**
https://user-images.githubusercontent.com/59477313/176977403-7b397926-b163-4eae-813d-5655d10b3687.mp4

**Comment by deckerst** [comment]
Nice suggestion! Actually, I've noticed Samsung Gallery does this too and considered it when I introduced the light theme way back. Good to know it's widespread. I'll probably do it in Aves then, without a setting.

> I lived without this feature 😱

haha!
