### ISSUE TITLE
Thank You Tremendously

### ISSUE THREAD

**Issue by GithubContributor832** [deckerst/aves#279]
I only opened this to say a huge thank you. This is incredible work and I haven't found any bugs yet. This is more stable then Simple Gallery Pro. I run this off preference and love cream of the crop quality work done incredibly right. I know this will obviously be closed but I don't have a google account to say thank you as I'm an AOSP guy over privacy concerns with as little connection to google as possible being evil tech. Thanks a lot for no trackers in the app too and please continue as I'll run this for years to come!

**Comment by deckerst** [comment]
Thanks for the kind words, I'm glad you enjoy the app!

**Comment by GithubContributor832** [comment]
No problem. It's more than well earned and I forsee this app exploding even bigger. Anybody that rates this bad is either a moron or a jealous prick! Thanks again.
