### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#28]
GIFs are currently not supported. My gifs are visible, but are not animated. They are static.

In the buttom left the same icon for videos is shown, but without a duration.

**Comment by deckerst** [comment]
Animated GIFs and WebP are supported. They should be static as
thumbnails in the collection view, but should be animated in the
fullscreen viewer.

The icon you described shows that the app recognizes that file as an
animated GIF.

Are you using the latest version v1.3.0 of the app? Could you share an
example of a GIF that does not animate?

**Comment by deckerst** [comment]
I will close this issue but feel free to reopen it if you can provide further details.
