### ISSUE TITLE
Create folders in different Directory

### ISSUE THREAD

**Issue by TheReiko69** [deckerst/aves#280]
I have been using aves for a few months now, and its amazing. I do wish though that when creating an album you can choose whatever directory you want to save this album to instead of it auto saving in my pictures folder. Its really tedious going into my file manager and needing to move it back to my DCIM folder to whatever folder I have in their to keep my phone more neatly organized. And as a side note to that, when moving media you should have the choice to move it to whatever directory you want as well. even if its an empty folder

**Comment by deckerst** [comment]
I do not intend to provide this level of folder management.

About being "neatly organized", I believe adding albums in "Pictures" is actually the right thing, given how Android organizes folders and associated media permissions. I consider "DCIM" a relic of the past.

To move media to empty folders, maybe it's not what you mean, but just in case, know that you can create an empty album when selecting a destination album to move/copy (i.e. no need to create it *before* selecting media to move).

Also, a tip with album creation: you can create an album named "Trips/This trip" and it will create the album "This trip" in the intermediate folder "Trips" (inside "Pictures").
