### ISSUE TITLE
It's hard to unhide status bar only

### ISSUE THREAD

**Issue by barackenkumpel** [deckerst/aves#281]
https://user-images.githubusercontent.com/93818968/177348610-47557e52-6c5c-49cc-b249-784d18449f91.mp4

https://user-images.githubusercontent.com/93818968/177348665-69ab351d-f286-4233-b47e-6c9044b41c8a.mp4

I am asking because I'm used to it watching the time this way instead of tapping on the screen with all other ui elements appearing.

**Comment by deckerst** [comment]
I'll try and block user gestures in the viewer top area. It may not be bullet-proof, but it will hopefully make it easier to drag the status bar without closing the viewer.
