### ISSUE TITLE
Ability to disable behavior of deleting folder when it's contents get deleted

### ISSUE THREAD

**Issue by barackenkumpel** [deckerst/aves#283]
**Is your feature request related to a problem? Please describe.**
Not really a problem I experienced under serious conditions, but when I was testing I couldn't restore a picture from recycle bin because it's parent folder was deleted automatically.

**Describe the solution you'd like**
An option in the settings to choose wether delete always, never delete or always ask.

**Additional context**
Simple gallery which I used before doesn't delete it. Even when deleting the whole album from the albums view.

**Comment by deckerst** [comment]
> I couldn't restore a picture from recycle bin

I couldn't reproduce the issue when restoring items in Aves. It worked fine whether the folder existed or not. Did you experience this inside Aves or another app? If it's Aves, I'd be interested to know the exact steps to reproduce this behaviour.

Regarding your request, I want to keep settings related to file management to the absolute minimum, so I intend to keep the current behaviour without additional settings. I'd rather address the restoring issue you encountered.

**Comment by barackenkumpel** [comment]
The issue was that I placed the picture in a subfolder of /sdcard/Download. Since you can't grant storage access to the Download directory directly it failed to restore the directory and the picture. Also, the permission for the subfolder was gone after it was deleted, I think.
Tested with another directory and (of course) everything was fine.
