### ISSUE TITLE
Complete Storage Access at once.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [deckerst/aves#284]
**Is your feature request related to a problem? Please describe.**
Everytime i have to delete a photo and if its a different directory, i will have to grant storage access to that particula location.

**Describe the solution you'd like**
Grant access to whole storage at once.

**Describe alternatives you've considered**
If cannot implemented due yo android limitation, how about adding this for root permission users.

**Comment by PhoenixCODE2322** [comment]
@deckerst  then it is on my side ... i have different directories like : /IDMP, /Download  
And one time when i tried to delete whats app images then it wanted the access ..
And some more ... i will just grant those access  when they come ..

**Comment by PhoenixCODE2322** [comment]
I will be closing the issue , as its on my side snd the limitation ( but its a good feature) ... thank you for this grea app

**Comment by MSOB7YY** [comment]
it would be nice making an option to give all_files_access permission
