### ISSUE TITLE
Add monet themed icon support

### ISSUE THREAD

**Issue by splice11** [deckerst/aves#285]
Would it be possible to make the app icon change depending on the monet theme engine palette in android 12+?

Example:

![Screenshot_20220715-140433_crDroid Home](https://user-images.githubusercontent.com/92755960/179211311-f1da649d-2414-4d44-b644-1a5cb2d7d228.png)

**Comment by deckerst** [comment]
I added support for this for Android 13 (API 33):
![Screenshot_20220715_175001](https://user-images.githubusercontent.com/13898333/179260161-796e54de-5fb4-4bcc-8435-126d2422f588.png)

But I thought that on Android 12, it was only available on Pixel phones, and only for apps whitelisted by the Pixel Launcher, not third-party apps.

On your screenshot, is it really the Monet dynamic theming or just an icon pack? By the way, do you use Android 12 or 12L, and what model and ROM do you use?

**Comment by deckerst** [comment]
I tried on a Pixel 5 emulator with Android 12L (API 32), and the latest version of Nekogram X (which appears themed on your screenshot) is not themed on that emulator. So I'd bet that you are actually using an icon pack, and not the Monet themed icons. Could you confirm?

**Comment by splice11** [comment]
My, bad I thought this was the vanilla monet themed icons, but there seems to be an icon pack in use.
