### ISSUE TITLE
Wrong country tag

### ISSUE THREAD

**Issue by gg-gg1** [deckerst/aves#287]
**Describe the bug**
Hi. In the latest release I have discovered that some of the pictures taken in one country are shown in the folder of a different country.
Also, after I have uninstalled the app, cleared the cache, data and reinstalled, it doesn`t load anymore the countries and tags.

**Expected behavior**
I would think that it should localise the gps coordinates correctly. 

**Screenshots**
I have attached a screenshot showing that it doesn`t load the tags.

**Additional context**
Thank you for your amazing work.

![signal-2022-07-18-184543_002](https://user-images.githubusercontent.com/98748676/179571807-97621c0a-fbc2-4e43-8455-8566faaf3af4.jpeg)

**Comment by deckerst** [comment]
Thanks for the report. In the app, there are instructions in the `About` page > `Bug Report` section. After following them, please paste here your system information and attach your logs.

**Comment by gg-gg1** [comment]
Ok. I have done what you have said and I will attach the files.
Thanks for your support.

Aves version: 1.6.9-izzy (Build 2075)
Flutter version: 3.0.2 (Channel stable)
Android version: 12 (SDK 32)
Android build: SQ3A.220705.003.A1
Device: Xiaomi POCO F1
Mobile services: ready
System locales: en_GB
Aves locale: system -> en
Installer: com.android.packageinstaller

[aves-logs-20220719_142001.txt](https://github.com/deckerst/aves/files/9141417/aves-logs-20220719_142001.txt)

**Comment by deckerst** [comment]
I've found and fixed the issue about the analysis service that got stuck on "Loading".

About the wrong country tag issue, could you share here an image that gets the wrong country? If you don't want to share it publicly, you could instead [send it to me by email](mailto:gallery.aves@gmail.com). Could you give me an example of country mismatch? Is it in geopolitically ambiguous areas?

**Comment by gg-gg1** [comment]
> I've found and fixed the issue about the analysis service that got stuck on "Loading".
> 
> About the wrong country tag issue, could you share here an image that gets the wrong country? If you don't want to share it publicly, you could instead [send it to me by email](mailto:gallery.aves@gmail.com). Could you give me an example of country mismatch? Is it in geopolitically ambiguous areas?

Thanks for the fix.

About the wrong country tag issue, I cannot provide you an image because it doesn`t show anymore any tag on countries because it doesn`t load anymore. It gets stuck on loading.... Also, before it used to show country, city, etc... now it shows only 3 digit from countries, like GBP, ESP, etc...

**Comment by deckerst** [comment]
Yes, if the analysis service gets stuck, you won't get the precise country/places from the Google geocoding service. Instead, it falls back to a quick and local country identification with the 3-letter ID.

I'd like to release a new version of Aves soon (including the fix for this issue), but I'm waiting from some fixes in Flutter itself...

**Comment by deckerst** [comment]
Aves v1.6.11 is released and should fix the stuck analysis service. Please give it a try, and let me know if you still experience country detection issues.

**Comment by gg-gg1** [comment]
Hi. Thank you for the release. The stuck analysis is fixed and also country detection work. It even gives more details about the location. Will test it further to see if it will stay like that.
