### ISSUE TITLE
Bug displaying two or more albums with the same name - only one is shown

### ISSUE THREAD

**Issue by marcosilva85** [deckerst/aves#294]
**Describe the bug**
I usually create new Albums by myself under the DCIM, instead of Pictures like Aves does - my reason is because I have this folder synchronized across devices.
I typically use the following structure:
DCIM/Trip-to-UK/**day1**
DCIM/Trip-to-UK/day2 or whatever...
DCIM/Trip-to-Spain/**day1**
..
DCIM/Trip-to-Whatever/**day1**
..

When I go to Aves, **only one album** named as day1 appears, although there are two (or even more).

**To Reproduce**
Go to your file manager and under DCIM create albums structured as above. Then check them in the Albums section of Aves.

**Expected behavior**
Aves should show each Album, even if they have the same name. Perhaps also show the parent folder in order to aid the viewer to distinguish them, as Aves already does this when Albums are under Pictures.

**Additional context**
Aves does not allow creation of two albums with same name (seems there's a check for that), however I can do so via File Manager and this situation should not lead to this bug.
On a side-note, I would also love if Aves could have an option for people like me to choose where we want new Albums to be created in, like Pictures or DCIM, or maybe even custom (GDrive/Pictures for those that use Cloud apps)...

Thanks for Aves!

**Comment by deckerst** [comment]
> DCIM/Trip-to-UK/day1
> DCIM/Trip-to-Spain/day1

When there are multiple albums with the same name like `day1`, Aves automatically shows the parent folders, to lift the ambiguity. Here it would show albums `Trip-to-UK/day1` and `Trip-to-Spain/day1`. This mechanism should work wherever the albums are, it's not only applied to albums within `Pictures`.

One important thing to consider is that Aves only shows albums that have items in them. So if you have some pictures in `DCIM/Trip-to-UK/day1` but not in any other `.../day1` folders, in Aves there will only be one album `day1` (backed by `DCIM/Trip-to-UK/day1`). Does it look like your situation?

Also, when you create albums within Aves, the folder on storage is not created until items are added to that album. As for new album naming, here's a trick: when giving the new album name, you can include `/` to create subfolders within `Pictures`. So if you create an album named `Trip-to-UK/day1` in Aves, it will be stored in `Pictures/Trip-to-UK/day1`.

**Comment by marcosilva85** [comment]
I've tried it again and failed to reproduce what I experienced 2 months ago... either way seems I wrote too soon from what I recalled from my experience...
I think back then I saw the first day1 album and I was expecting to see another day1 next to it, but instead I didn't as it probably was sorted at the bottom, at letter T (Trip-to-Spain/day1) because of the mechanism you just described.

It seems clear to me now, hope it is a bit more clear also what I tried to describe. Sorry to have thought that it was a bug.

**Comment by deckerst** [comment]
No worries. I'll close this issue, but feel free to let me know if you spot something strange with album naming in the future.

Also, if you're looking for albums, you can also use the search page and type "day1" and it will surface all of them.
