### ISSUE TITLE
Avif image is not shown correctly

### ISSUE THREAD

**Issue by basings** [deckerst/aves#296]
**Describe the bug**

Avif image is not shown correctly. It is shown distorted for a second in the image viewer but then disappears. 

**To Reproduce**
1. Put Image on phone
2. Open aves, go to image
3. See error

**Expected behavior**
Image and metadata are shown

**Screenshots**
Photo viewer
![Screenshot_20220803-181224](https://user-images.githubusercontent.com/92867705/182658987-68743e7e-0b39-449c-86fb-1e32095ca0b2.png)
thumbnail
![Screenshot_20220803-181242](https://user-images.githubusercontent.com/92867705/182660196-70479e7d-80d5-4611-895b-4660910552d6.png)
actual image
https://drive.proton.me/urls/ART16ZDQ4C#f1nYwNGUONmn

**System information and logs:**
Aves version: 1.6.11-izzy (Build 1077)
Flutter version: 3.3.0-0.0.pre (Channel beta)
Android version: 12 (SDK 32)
Android build: SQ3A.220705.003.A1.2022073100
Device: Google Pixel 6
Mobile services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.machiav3lli.fdroid

**Comment by deckerst** [comment]
It looks like a broken image to me. The file is only 251.80 KB for a 18 MP image (8211 × 22542⁩), and other gallery apps on my device also fail to render it.

**Comment by basings** [comment]
There's no problem in displaying the image on eye of gnome or digikam (on arch).

I see that neither google photos nor gwenview can open it. I just removed all exif data and then it displays the correct resolution in aves. Might be a bug of image magick?

**Comment by basings** [comment]
thx for looking into this. must me image magick!

**Comment by deckerst** [comment]
Just so you know, even if the image is well formed, Aves does not currently show metadata for AVIF files. It can render them on Android 12+, but that's it.

**Comment by basings** [comment]
That's important to know, thanks!
