### ISSUE TITLE
General performance, and other things 

### ISSUE THREAD

**Issue by UniverseCodex01** [deckerst/aves#297]
- High ram consumption:
During pictures scan, gallery has a very high ram consumption (500mb - 1gb), I think this bug only happens in scan of a lot of files, my 20000 pictures and 40 albums generated the problem environment, I think.

- App stability:
General app performance is not good if you have 20000+ pictures and 40 albums.

- Albums names text:
I'm facing pixelify problems in some albums names text, I can see pixels of name texts, and looks ugly.

- In general:
App need to be optimized and improve to support very big content of pictures and albums

**Comment by deckerst** [comment]
Please [read this before opening issues](https://github.com/deckerst/aves/issues/234).

1) High ram consumption
Unless the app crashes, it's not an issue.

2) App stability
Unactionable

3) Albums names text
Screenshot please

4) In general
Unactionable
