### ISSUE TITLE
Add support edit EXIF description tag

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#301]
Please add support edit EXIF `description` tag.

**Comment by deckerst** [comment]
Probably going to support these fields, to de/select when editing:
- Exif ImageDescription (0x010e)
- Exif UserComment (0x9286)
- IPTC Caption-Abstract (120)
- XMP dc:description

**Comment by deckerst** [comment]
I changed my mind. It will write:
- Exif ImageDescription (0x010e)
- XMP dc:description
- IPTC Caption-Abstract (120), *only if there is already other IPTC metadata*

It *doesn't* write:
- Exif UserComment (0x9286)
