### ISSUE TITLE
Cannot choose the video-editor of Google Photos when I select "Edit" in a Video in Aves

### ISSUE THREAD

**Issue by marcosilva85** [deckerst/aves#302]
**Describe the bug**
I'm not sure if this is a Google Photos/Android bug or Aves, so sorry for it if isn't. Nevertheless, perhaps there is a smart way to solve this.
I like how in Aves when I'm viewing a picture and I want to edit it, Aves allows to use the Google Photos editor. (even amazing is the fast-transition when doing so).
However, if I'm viewing a Video, and I want to edit it, it says "no matching app" to me and it does not offer the Google Photos video-editor where one can crop / trim / rotate and so on the videos.

Therefore, at the moment if I want to use the video editor of Google Photos, I have to open Google Photos app, find and navigate to the video again and then click "Edit" in there, which is a cumbersome workflow.

**To Reproduce**
1. Go to Aves and play a video.
2. Click on "Edit" in the menu options.
3. Three things can happen now:
3.1. If you have a video-editor app installed (e.g. Inshot), it will open directly the video with it ✅.
3.2. if you have more video-editor apps, Aves proposes them for you to choose one ✅. But is weird that Google Photos isn't on the list ⚠️.
3.3. In case you don't have any extra video-editor apps, it says "No matching app", but I have Google Photos and it is never shown/considered ❌

**Expected behavior**
Clicking edit on a Video in Aves should at least offer Google photos since it also has a Video Editor. It is confusing to me why it works for editing photos from Aves to Google Photos editor, but not for Videos.

Thanks, hope everything is understandable ;)

**Comment by deckerst** [comment]
As far as I know, it's because Google Photos does not declare that it can handle video editing. (If you're interested i can explain further.)

If you want to improve on your workaround, instead of launching Google Photos and navigating to the file in it, in Aves you could use `Export` > `Open with`, choose Google Photos and then "edit" in GP.

> Aves allows to use the Google Photos editor. (even amazing is the fast-transition when doing so).

Credit goes to Google Photos, not Aves ^^

**Comment by marcosilva85** [comment]
> As far as I know, it's because Google Photos does not declare that it can handle video editing. (If you're interested i can explain further.)
No need, understood. Sad then :(

> If you want to improve on your workaround, instead of launching Google Photos and navigating to the file in it, in Aves you could use `Export` > `Open with`, choose Google Photos and then "edit" in GP.
Yes, this is ok as a workaround for me. Strange sub-menu combination though, the "Export->Open With".
Thanks for the reply and wisdom, as usual.
