### ISSUE TITLE
Blurry image rendering

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#303]
**Describe the bug**
Aves seems to not render a specific image correctly.

**To Reproduce**
1. Download the image: https://www.swisstransfer.com/d/981aa5cc-7497-4a7f-a829-aedf2f70ba88
2. Open in Aves. It looks blurry
3. Open in any other gallery app and it looks good

**Expected behavior**
The image/text should be sharp.

**System information and logs:**
Aves version: 1.6.11-izzy (Build 2077)
Flutter version: 3.3.0-0.0.pre (Channel beta)
Android version: 10 (SDK 29)
Android build: lineage_raphael-userdebug
Device: Xiaomi Mi 9T Pro
Mobile services: not available
System locales: en_US
Aves locale: system -> en
Installer: com.android.packageinstaller

**Additional context**
Simple gallery was used to verify the image itself is not blurry.

**Comment by deckerst** [comment]
Interesting, thanks for the report. I'll take a closer look when I get to a computer.
