### ISSUE TITLE
Motion Picture is not recognized as such / handled corretly on Pixel 4a

### ISSUE THREAD

**Issue by linesquarecube** [deckerst/aves#304]
**Describe the bug**
Motion pictures taken with my Pixel 4a are not recognized as such and thus not handled as motion picture --> no video, only picture is visible. Filename is as expected PXL_JJJJMMDD_XXXXXXX.MP.jpg, also metadata shows that it is a Motion Photo as shown in the attached screenshot.

**To Reproduce**
1. Go to 'Google Camera App'
2. Make a Photo (Motion Photo enabled)
3. Open Aves
4. See Photo without motion

**Expected behavior**
Motion Photo is tagged with Motion Photo symbol in overview, Motion Photo is playable or will autoplay if configured

**Screenshots**
Screenshot of correct XMP Metadata showing container with two directories. One for image, one for video.
<img src="https://user-images.githubusercontent.com/81855936/185462289-6a388659-9253-4d5c-8b7a-4fd1a7585367.png" width=40% height=40%>

**System information:**
Aves version: 1.6.11-izzy (Build 1077)
Flutter version: 3.3.0-0.0.pre (Channel beta)
Android version: 12 (SDK 32)
Android build: SQ3A.220705.003.A1.22307002
Device: Google Pixel 4a
Mobile services: ready
System locales: de_DE
Aves locale: system -> de
Installer: com.android.packageinstaller

**Sample picture**
![PXL_20211024_142656260 MP](https://user-images.githubusercontent.com/81855936/185488077-60c84e99-145d-45ac-94bd-a93168e021f9.jpg)

**Comment by deckerst** [comment]
Thanks for the report.

Please paste your system information following the instructions in the app > About > Bug Report. (no need for logs, just the system info)

Would you mind attaching here one of these motion pictures?

**Comment by linesquarecube** [comment]
I've added the system information in the bug report description. I'm also open to upload a picture, but it gets renamed when I try to upload it. Do you know if it still remains a Motion Picture?

Thanks for looking into this :smiley:

**Comment by deckerst** [comment]
Attaching it here shouldn't change the file itself, even if the name is different.

**Comment by linesquarecube** [comment]
Attached a file and tested it afterwards with https://github.com/dj0001/Motion-Photo-Viewer without any issues :+1: 
So you are right - the file doesn't change in any way, only the filename is different

**Comment by deckerst** [comment]
Thanks!

Interestingly, the file plays well as a motion photo on my device. When I check the metadata, I see the XMP `Container` as "Container" (which is expected), while on your screenshot it's `Container_1_` (which usually happens if there are multiple sections with the same name). I know more or less how to circumvent this naming issue, but I'm curious to know why it happens on your device.

Just to confirm, on your device, the attached image has the XMP metadata "Container_1_" like your screenshot above, right?

**Comment by deckerst** [comment]
Unrelated to the current issue, but the appended video in the attached motion photo actually contains 2 video streams:
- #1: 1280x720, 30.957 FPS
- #2: 1920x1080, 3.001 FPS

Stream #1 is playable, but stream #2 seems weird and can't be played. I wonder what Google is doing.

**Comment by linesquarecube** [comment]
As all already shot the motion pictures I have on my phone are currently not detected, I tried to shot a new one today. For whatever reason, the picture is detected properly as motion picture and plays without an issue. I have not changed anything on the phone or with the google camera app, besides the XMP metadata looks different now as you can see in the screenshot. 

This is not an issue Aves in my opinion but rather an issue with the google camera app.

Screenshot of XMP Metadata showing container with two directories in a different way than the one above.
<img src="https://user-images.githubusercontent.com/81855936/185705851-1ce6447d-54d6-4a5d-8303-d0be38837681.png" width=40% height=40%>

**Comment by deckerst** [comment]
Ah, I see. Even if it's an issue with the camera app, I believe I can make Aves recognize the faulty metadata.

If you can attach here one of your older motion photo (one showing "Container_1_"), that would be swell. (You can also [email](mailto:gallery.aves@gmail.com) it to me privately if you're concerned about privacy.)

**Comment by linesquarecube** [comment]
Sorry for my late reply. The motion picture I've added in my first post is one of these showing "Container_1_". The screenshot in my post on 19.08.2022 is from a newly shot motion photo which is detected correct. 

The Motion Picture from my first post has been shot with my old Pixel 4a which is broken. The Motion Picture which properly works is shot with my exchange Pixel 4a. Both - my old and my new Pixel - run CalyxOS with the GCam Mod from cstark without further modifications. So I cannot guess anything that causes this difference :man_shrugging: 
<img src="https://user-images.githubusercontent.com/81855936/186487834-d4d02d96-507a-4c3a-b987-08e53fc169e4.png" width=40% height=40%>
 
Still happy if you can manage that Aves will show all Motion Pictures correct :)

**Comment by deckerst** [comment]
Thanks for the details.

I changed the way XMP is interpreted for the upcoming release of Aves. I don't expect the changes to fix your particular issue, but if you still see "Container_1_", you should now see the full namespace next to it. It's useful to check whether there's some misspelling in the namespace.

**Comment by deckerst** [comment]
I'll close this for now, but feel free to comment if you have additional information, like the misinterpreted namespace.
