### ISSUE TITLE
Album size

### ISSUE THREAD

**Issue by Ikura9** [deckerst/aves#312]
An option to see the size of the album when you select it like in huawei gallery app

![IMG_20220901_230856](https://user-images.githubusercontent.com/111642864/188004015-d5f2a8eb-b4f5-4ced-8e3c-da7077d0e1b5.jpg)

**Comment by Ikura9** [comment]
> The total file size in bytes, right? And if you refer to another app, please attach a screenshot or screen recording.



> The total file size in bytes, right? And if you refer to another app, please attach a screenshot or screen recording.

Like this

![Screenshot_20220901-230139](https://user-images.githubusercontent.com/111642864/188001923-bcdd7ed4-ce37-4449-a9df-c81f95252fe2.jpg)

**Comment by Ikura9** [comment]
> The total file size in bytes, right? And if you refer to another app, please attach a screenshot or screen recording.
Added a screen shot
It doesn't have to be in bytes megabytes is fine

**Comment by deckerst** [comment]
I'll probably add this information to the stats.

As for your original request, it would be helpful if you explain your use case, in which situation you need this information.

**Comment by Ikura9** [comment]
> I'll probably add this information to the stats.
> 
> As for your original request, it would be helpful if you explain your use case, in which situation you need this information.

I use it when I need to free up space on my phone

**Comment by deckerst** [comment]
In the next version, you can sort albums (or countries, tags) by their total size. And the size is also displayed if you choose the list layout.

![Screenshot_20220905_184938](https://user-images.githubusercontent.com/13898333/188493399-db85261c-d2c6-4d71-b1dd-0dcb065f1027.png)
