### ISSUE TITLE
Touch Area to instantly change to next/previous image is too wide

### ISSUE THREAD

**Issue by marcosilva85** [deckerst/aves#315]
**Is your feature request related to a problem? Please describe.**
I got to try #289 and thanks for that!
However I'm finding it troublesome to use as sometimes I want just to pop up the toolbar (center-action) and as the side-action is too wide (and invisible), it actually lands on it instead, therefore I make instead an unintended picture change. As its too wide, while I'm using the phone in e.g. landscape mode and I want to bring-up the toolbar, I have to move a lot of my hand so that my finger can reach the middle of the screen, which makes me act in a more rigorous manner in attempt to really get a center-action.

**Describe the solution you'd like**
Could be either narrower bands on the side, or if this isn't intended, at least having a way to set the "band" size (wide/narrow).

**Additional context**
I would like to share my observation in terms of UX. I acknowledge that what other users prefer to have might be for debate, but disregard this for a moment and think instead if a user clicks the invisible area he intends but gets instead the unintended action:

a) [Bigger area for center-action] and user mistakely clicks on it when he intends to "swipe" to another picture.
 - Just the toolbar is brought up, he can still just click again more towards the side: No eye-coordination needed + small finger adjustment. 

b) [Bigger area of side-action] and user mistakely clicks on it when he intends to bring-up the toolbar.
 - instead, the next picture is loaded, so he has to act again another time to come back to previous picture, and a 3rd time to bring toolbar. This is more disruptive of the workflow than a) because the picture change causes eye saccade + requires more broad hand coordination.

**Comment by deckerst** [comment]
Agreed. Did you think it too wide only in landscape, or whatever the device orientation?

As i remember, the current area for side touches is 1/4 of the window width.

**Comment by deckerst** [comment]
I reduced the tap areas (1/5 for portrait, 1/8 for landscape). Let me know how it goes with the next version.
