### ISSUE TITLE
Swiping when on edge of picture visible

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#316]
So when I zoom in and swipe to move around all is fine, but when I zoom in, move to the edge of an image and swipe, the app moves to the next/previous image. 

See the video I made:
https://www.swisstransfer.com/d/3c41a5b6-b270-46f7-bc16-66c429321b60

**Comment by deckerst** [comment]
I'm aware of this behaviour, but I'm not sure whether I can fix this, given the way scrollable areas are nested. I figured nobody would practically scroll in such a way, if you actually try to go to the next image. Do you often run into this issue when using the app normally?

**Comment by deckerst** [comment]
I checked how other apps handle this problem:
- `Google Photos` simply prevents going to the next image when zoomed in. That's underwhelming.
- `Samsung Gallery` does the same thing... with a twist: it blocks panning to the edge when zoomed in, but it allows going to the next image if it recognizes a horizontal __fling__ gesture (as opposed to a panning gesture).

Once again, the UX people at Samsung deserve a raise. It's brilliant. I'll see if I can replicate this behaviour.

**Comment by BrownBoy11** [comment]
Similar behavior when cropping. It is difficult to move the left or right edge of a crop window without initiating the android “go back”. I have to grab the corner and move it a tiny bit (before the “go back” arrow appears) then let go, then do it again to get the crop edge far enough away from the screen edge. Then I can adjust the crop box freely. I love the app and this is the only criticism I can find. Please let me know if there is a way to get around this: I crop a lot of photos and do not want to use other apps.

**Comment by deckerst** [comment]
@BrownBoy11 At the moment Aves does not provide its own image editor. I believe the crop feature you're talking about is from your default image editor app that is launched when you choose to `edit` in Aves. You could install another editor app (Google Photos, Snapseed, etc.) and find one that does not have this gesture issue.
