### ISSUE TITLE
Unable to edit tags on photos!

### ISSUE THREAD

**Issue by DodoLeDev** [deckerst/aves#318]
**Describe the bug**
Since the last update, I am unable to edit tags of my photos! :cry:

**To Reproduce**
0. Update the Aves app
1. Open a photo
2. Open file properties (scroll down)
3. Click 'Edit tags' :label:
4. Add/remove a random tag to the file
5. The app says 'Failed!'

**Expected behavior**
Tags should be correctly edited, as it has been done on older versions!

**Screenshots**
As you can see, after adding a tag, nothing but an error message is shown!
![Screenshot](https://user-images.githubusercontent.com/59477313/188317259-2f1aef00-d455-40ab-811f-0bbdf093cbf0.jpg)

**System information and logs:**
```bash
Aves version: 1.6.13-izzy (Build 1079)
Flutter version: 3.3.0-0.5.pre (Channel beta)
Android version: 11 (SDK 30)
Android build: RP1A.200720.011
Device: Xiaomi M2003J15SC
Mobile services: ready
System locales: fr_FR
Aves locale: system -> fr
Installer: com.looker.droidify   # My F-Droid client
```

[Aves Logfile](https://github.com/deckerst/aves/files/9484813/fataLog.txt)

**Additional context**
Any workaround while waiting for an update would be welcome!

**Comment by deckerst** [comment]
Thanks for the report.

It still works fine on my device, and the logs are not pointing to anything useful, so it will be tricky to debug...

Do other operations besides tagging still work (e.g. rotating, editing the date, changing the rating, renaming)?
Does it fail on new files only or old files as well?

**Comment by DodoLeDev** [comment]
It also fails when changing the rating, when rotating and when editing the date!
Well.... It is unable to apply any modification to the files on my device :scream: !
EXCEPT copying and moving files... :thinking:
That's a kinda strange behaviour...

**Comment by deckerst** [comment]
Strange indeed.

I suppose you've already granted write access to the containing folders (you can double-check in `Settings` > `Privacy` > `Storage access`).

Do you use a custom ROM?

Some OEMs customize their ROM with some kind of "permission monitor" which makes it behave differently from standard Android. I'm aware of this on some Realme UI / ColorOS for Android 10. Maybe Xiaomi also adds similar bloatware. Do you know if that's the case on your device? If you have some way to disable this additional permission monitor (maybe in the "Developer options" settings), could you try and let me know if it makes a difference?

**Comment by DodoLeDev** [comment]
Wait... This is what I get when I list Aves' permissions and their status (granted or revoked):
![AvesPremissions.jpg](https://user-images.githubusercontent.com/59477313/188325026-108b9f84-e35f-4c16-af0b-59f891b3be0c.jpg)

It is REALLY strange.... 🤔
Maybe trying to allow these permissions with ADB....?

**Comment by deckerst** [comment]
`READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` are meaningful only from Android 13 (API 33), and can be safely ignored on your device. Until Android 12L (API 32), the meaningful read permission is `READ_EXTERNAL_STORAGE` (which is granted for you).

And in your case, reading is fine. It's writing which is troublesome.

Did you see my comment above? https://github.com/deckerst/aves/issues/318#issuecomment-1236361787

**Comment by DodoLeDev** [comment]
**EUREKA**! 🥳 I've found a solution!
But I still don't know what caused this problem...

I use [App Manager](https://github.com/MuntashirAkon/AppManager) to get advanced info about apps, and in the App's operations tab, I've allowed those permissions:
![Aves OperationsTab.jpg](https://user-images.githubusercontent.com/59477313/188325742-82944668-cc82-4d7d-951c-c27ad94d3712.jpg)

And now everything works like before!

What could be the root cause of this modification between 2 versions of this app? 🤔

**Comment by DodoLeDev** [comment]
And to answer to your last post, no, I don't use a custom rom, but I have a Xiamo and all the bloatware packaged with it! (I've at least disabled or systemless-ly uninstalled all the non-essential Mi Apps)

**Comment by deckerst** [comment]
I'm glad you found out a solution!

These permissions `WRITE_MEDIA_IMAGES` and `WRITE_MEDIA_VIDEO` are not explicitly requested or even defined in Aves, but maybe one of the libs I'm using do so. It's also intriguing that these permissions look like counterparts to the Android 13 red permissions mentioned earlier. That they matter on an Android 11 device is a mystery.

Anyway, I'll close this issue, as I don't think I can do anything about it. I'll just blame Xiaomi and move along ^^

**Comment by deckerst** [comment]
For reference, this is the complete permission list i have for Aves (installed from the Play Store):
![Screenshot_20220904-194752_App Manager](https://user-images.githubusercontent.com/13898333/188326794-a5aabffb-6fb8-40df-80d5-705ad3574cc5.jpg)
