### ISSUE TITLE
Add Persian language

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#321]
Hi, I need the Persian language for this app.
How can I contribute to new language additions?

**Comment by deckerst** [comment]
Hi, and thanks for your interest in contributing!

Please take a look at https://github.com/deckerst/aves/wiki/Contributing-to-Translations

If you have questions, don't hesitate (here in this thread, or by [email](mailto:gallery.aves@gmail.com)).

**Comment by deckerst** [comment]
I'll close this issue, but feel free to ask if you need help.

**Comment by deckerst** [comment]
I'll close this issue, but feel free to ask if you need help.

**Comment by deckerst** [comment]
@xmha97 you can now contribute on weblate: https://hosted.weblate.org/languages/fa/aves/

**Comment by xmha97** [comment]
Thanks
