### ISSUE TITLE
How I can disable resume feature?

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#322]
How can I disable the video resume feature?

![Screenshot_2022-09-12-03-04-29-108_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/189551884-1584dc77-98a5-4560-b9b5-c51f082e9160.jpg)

**Comment by deckerst** [comment]
It cannot be disabled at the moment.

More generally, If you mean to ask questions, please use the [discussions](https://github.com/deckerst/aves/discussions). And if you mean to request features or improvements, please fill the [issue template](https://github.com/deckerst/aves/issues/new?assignees=&labels=type%3Afeature&template=feature_request.md&title=).
