### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#323]
Hi, I'm using Microsoft Launcher on Xiaomi 11T (Android 12)
Why the Aves widget is bad?

![Screenshot_2022-09-12-03-30-39-361_com.microsoft.launcher.jpg](https://user-images.githubusercontent.com/23485114/189552630-e2fd6a28-d1c1-42d2-97ab-bcb46dfd12dd.jpg)

![Screenshot_2022-09-12-03-30-42-753_com.microsoft.launcher.jpg](https://user-images.githubusercontent.com/23485114/189552625-da8c0aed-d74f-49ee-add5-ed182b393e9b.jpg)

**Comment by xmha97** [comment]
```
Aves version: 1.6.13-play (Build 79)
Flutter version: 3.3.0-0.5.pre (Channel beta)
Android version: 12 (SDK 31)
Android build: SP1A.210812.016
Device: Xiaomi 21081111RG
Mobile services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.android.vending
```

**Comment by xmha97** [comment]
[aves-logs-20220912_152113.txt](https://github.com/deckerst/aves/files/9547282/aves-logs-20220912_152113.txt)

**Comment by xmha97** [comment]
![Screenshot_2022-09-12-15-20-00-318_deckers thibault aves](https://user-images.githubusercontent.com/23485114/189636303-2e46f739-6e18-4b6c-be1a-4528e360f78f.jpg)

![Screenshot_2022-09-12-15-20-07-242_com microsoft launcher](https://user-images.githubusercontent.com/23485114/189636334-15031568-7590-4d4c-ada1-3689d8587eff.jpg)

**Comment by deckerst** [comment]
Thanks for the logs. I previously got a similar bug report from a different system (Android 8.0, Moto Z XT1650) but I didn't have logs at the time. I'll take a look.

And it's not related to MS Launcher, as I tried it on my device and the widget was loading fine.

**Comment by xmha97** [comment]
Why did you close the issue?  Will this problem be solved on my phone?

**Comment by deckerst** [comment]
I fixed the root cause of the issue. The next release of Aves should fix it for you.

**Comment by xmha97** [comment]
Thanks, fixed on my phone.
