### ISSUE TITLE
Description is not being considered while doing full-text search

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#325]
**Describe the bug**
Using Aves I edited exif tags for one of my photos - added a description. But when I attempted to search among my photos, using a part of that description (one full word match) - nothing came out in search results.

**To Reproduce**
1. Modify a description of any photo(s) and make sure it appeared among Exif IFD0 tags. For this our exercise set the description to "test description"
2. Perform a search by providing strings "description", "test" or "test description"
3. Nothing comes up as result

**Expected behavior**
Photo(s) we just modified to set their descriptions to "test description" are supposed to appear in search results.

**Screenshots**
![Screenshot_20220913-022533_Aves](https://user-images.githubusercontent.com/110789576/189706532-f685adc3-3e23-4642-84ec-bc2b437e712a.jpg)

**System information and logs:**
Aves version: 1.6.13-play (Build 79)
Flutter version: 3.3.0-0.5.pre (Channel beta)
Android version: 12 (SDK 31)
Android build: SP1A.210812.016.G970FXXSEGVA9
Device: samsung SM-G970F
Mobile services: ready
System locales: en_GB, ru_RU
Aves locale: system -> en
Installer: com.android.vending

**Additional context**
Or probably I'm misusing the search and it's not (yet) considering this IFD0 EXIF "Description" tag? If so, feel free to reclassify this as feature request

**Comment by deckerst** [comment]
The app is not intended to index every metadata field. Titles and descriptions are borderline.

Also, there's currently some inconsistency in the app support for title and description. Titles are indexed, but descriptions are not. In Aves v1.6.13, you can edit descriptions but not titles, and metadata titles are always preferred over filenames.
In the next version of Aves, you will be able to edit both titles and descriptions (already implemented), and I may add options to let users decide whether they prefer metadata titles or filenames to be used as titles.

I won't index descriptions for the time being. I hope people will use titles instead if they rely on text search. In any case I'm interested in feedback regarding the next version of Aves.

**Comment by kha84** [comment]
Awesome. Waiting patiently for the next version then
