### ISSUE TITLE
"Recently added" filter doesn't do much

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#326]
**Describe the bug**
I have a fresh installation of Aves, with all my photos/videos being scanned and indexed already. When I navigate through my library by using various combinations of filters, I noticed that when I add "Recently added" quick filter either as alone filter or as an additional filter to the list of applied filters, the actual search results are not narrowed at all. All other "Date" filters work just fine.

**To Reproduce**
1. Go to your collection in Aves
2. Click on magnifying glass icon on a top right apply filters
3. Out of all filters select "Recently added" under "Date" group of filters 

**Expected behavior**
I was expecting to see the effect of this filter, like it should narrow down the amount of shown media to show only the ones, which were recently **created**, but it looks like this filter doesn't have any effect at all.

**Screenshots**
Will happily provide ones if needed, but I'm hoping this behavior can be replayed by just following above steps

**System information and logs:**
Aves version: 1.6.13-play (Build 79)
Flutter version: 3.3.0-0.5.pre (Channel beta)
Android version: 12 (SDK 31)
Android build: SP1A.210812.016.G970FXXSEGVA9
Device: samsung SM-G970F
Mobile services: ready
System locales: en_GB, ru_RU
Aves locale: system -> en
Installer: com.android.vending

(Aves is still the best photo manager app!)

**Comment by deckerst** [comment]
Currently, the "recently added" filter shows items discovered by Aves within the last 24 hours. If you just installed the app, all the items are discovered at that time, so all the items are "recently added".

I'm not entirely happy with this, and I may switch the criterion date to something like this (by precedence):
- date added to Media Store
- file creation date
- date added to Aves

**Comment by kha84** [comment]
Sure, that makes all sense to me. If you can make it configurable, I think every user will find his own sweet spot. Off course it's a low prio thing

**Comment by kha84** [comment]
Wow! I've seen you closed my other feature request as well. Amazing job!
Ping me if you want me to do some alfa / beta testing, once the recent build is there
