### ISSUE TITLE
Long tap on month name to select all photos made in that month

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#327]
Currently long tap on photo switches the mode from "viewing" to "selecting". I've seen this kind of behavior been implemented in some other gallery apps, when long tap on *month name* switches app to selecting mode as well but on a top of that *it also selects all displayed photos in that month*. I find it very useful while bulk processing photos

**Comment by deckerst** [comment]
True, it would be an improvement.

In the meantime, when in selecting mode, tapping on the month name will select/deselect all the pictures of that month.

**Comment by kha84** [comment]
I know, I'm already using that :)
