### ISSUE TITLE
Map position is off, when you set geodata to photo which is missing it

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#328]
**Describe the bug**
If you open a map with the purpose of setting GPS coordinates for a photo *which never had it*, the map is opened while being centered on some completely unrelated location. This is fine for the very first use, but if user is assigning coordinates to a series of photos, this kind of behavior forces user to do some extra finger exercise: to scroll / move map from the "default position" to a point user wants. 

I think it would be much better, if the map will be remembering last position and zoom, so when user invokes it to set the GPS for his next photo, it will be showing him the place he set/seen right before.

**To Reproduce**
Typical use case:
1. Find some photo which is missing geodata and open it.
2. Edit Location -> Click on map icon
3. Mind what point map shows by default
4. Adjust the point to some place, tap "Use this location" button on map, then click "Apply" button to save these coordinates to image
5. Open another photo which is not having GPS data. Edit Location -> Click on map icon. Make a not what map is showing you as the starting point 

**Expected behavior**
When the map view is opened for a photo which is not having GPS data *for a second time*, it makes sense to show it centered & zoomed the same way / on the same point it was set the very last time, when user edited GPS data for a previous photo. 

Currently when the map is invoked while assiging GPS data to a  photo which never had those - it's centered at some unrelated point by default 

**Additional context**
Just a funny side note.
it looks like this behavior (what point the map is centered at by default, when no coordinates are given) is depending on map provider. Like Google is trying to set this point somewhere in Turkey, Egypt or Greece.
OSM is setting the starting point somewhere to Nepa.

**Comment by deckerst** [comment]
The default position/zoom of the map depends on whether there are currently located items in the current collection:
- If there are, it will try to size the map to fit all the located items.
- If there aren't it will use a default location. In Aves v1.6.13, that default location was a randomly selected one among the 7 wonders (so Turkey, Egypt or Greece...) But I already changed that behaviour for the next version of Aves, where it will remember and reuse the last position of the map as the default location.

The default location shouldn't change according to the map provider.

**Comment by kha84** [comment]
> But I already changed that behaviour for the next version of Aves, where it will remember and reuse the last position of the map as the default location.

Splendid. You're ahead of me again :)
