### ISSUE TITLE
Easy copy & paste coordinates 

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#329]
**Is your feature request related to a problem? Please describe.**
I tend to accumulate a number of photos from the same event, some of them I made myself, some others were sent to me by friends via messengers. Such images are usually having no exif tags, as messangers do strip them away. Something my camera app just fails to grab & save GPS coordinates to photos I shoot myself. In order to organize my photo library I usually set GPS coordinates for such photos manually. Aves allows that, but it's kind a hardsome as you cannot easily copy gps coordinates from one photo and apply it to other.

**Describe the solution you'd like**
There's a need for 1 more tiny button, to copy coordinates into a clipboard (without having usual android pixel-hunting hassle to select them with cursor):

![Screenshot_20220913-225832_Aves](https://user-images.githubusercontent.com/110789576/189907479-96ac98fe-bac6-45c5-952a-30b4e9852505.jpg)

Then, in a dialog to set GPS location, if you have GPS coordinates in a clipboard, it should offer you to put them into appropriate columns (so you're avoiding another android text editing nightmare of manually split coordinates from clipboard into two columns):

![Screenshot_20220913-230209_Aves](https://user-images.githubusercontent.com/110789576/189908987-00aad0df-456c-4901-8396-71ac89cd1953.jpg)

**Comment by kha84** [comment]
I found a sort of workaround for copying GPS coordinates from one photo to another. For that you need first to select a photo, whose GPS data you want to copy to other photos. This is important to select it first. Then you select your other photos (like the ones wich are having no GPS on them). Then you click edit -> set location and the coordinates in location popup will be prefilled from your first selected photo. So you can just presss apply there.

**Comment by deckerst** [comment]
> This is important to select it first.

I tweaked it so that it is no longer necessary to be the first.

**Comment by kha84** [comment]
Wow, awesome! Waiting for a ping to do the translation thing :)

**Comment by deckerst** [comment]
I didn't add the copy/paste buttons as you suggested but I added a way to edit location by picking an item, as you can do for dates.

As for the translations, I'm trying out Weblate these days (cf README). It's promising, but I need to see whether my request for their free "Libre plan" will go through.

**Comment by kha84** [comment]
This way or another, if that can be done - it's great.
