### ISSUE TITLE
Gps label is not being shown for a photo

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#332]
**Describe the bug**
There was a photo in my library, without GPS coordinates (usual bug for my Samsung S10E to "miss" to tag some photos with GPS coordinates). I set the location manually with using Aves. For some reason, in the list of photos this photo is not having a usual makrer in a bottom left corner, indicating it has GPS coordinates. And map is not being show, when I open that photo and swipe it up.

**Screenshots**
Mind the second photo in a first row. It's missing an indicator that it has GPS data:
![Screenshot_20220915-165743_Aves](https://user-images.githubusercontent.com/110789576/190336890-de5c1f89-80e9-4871-88c2-7c6723db54d5.jpg)

If I open details for this photo, I can see that it has "GPS" section, but it doesn't show the mini-map there:
![Screenshot_20220915-165812_Aves](https://user-images.githubusercontent.com/110789576/190336929-2ee2672e-6552-4138-82ee-b2361f42315b.jpg)
![Screenshot_20220915-165821_Aves](https://user-images.githubusercontent.com/110789576/190336954-8ada9032-3854-4bb8-acb4-c3df1c4d779e.jpg)

I tried to restart the app but it doesn't help. I'm guessing rescanning will help, but we will loose this error context if I do this :)

**Comment by kha84** [comment]
```
Aves version: 1.6.13-play (Build 79)
Flutter version: 3.3.0-0.5.pre (Channel beta)
Android version: 12 (SDK 31)
Android build: SP1A.210812.016.G970FXXSEGVA9
Device: samsung SM-G970F
Mobile services: ready
System locales: en_GB, ru_RU
Aves locale: system -> en
Installer: com.android.vending
```

Logs attached 
[Uploading aves-logs-20220915_170914.txt…]()

**Comment by kha84** [comment]
Sorry looks like I 
[aves-logs-20220915_170914.txt](https://github.com/deckerst/aves/files/9572799/aves-logs-20220915_170914.txt)
failed to attach logs. Trying once again

**Comment by kha84** [comment]
A small update: I added a tag to that and bunch of othres photos, and while this operation was processed, there was a status text on top of screen, something like 'Locating places x/y'. And after that was completed, the issue with that photo is gone.

**Comment by deckerst** [comment]
Did you edit the location from the `Info` page, or from the `Collection` page after selecting the photo?

Do you remember if, after setting the location, the app displayed a "Done" or "Failed" feedback message?

**Comment by kha84** [comment]
Sorry, I didn't remember that and I tried to reproduce it multiple times and I couldn't. I will keep a close eye on how I update locations from now on, and if I face the same bug again - I'll let you know here with all those details.

As a side note: when I faced that bug, the cellular coverage was poor and phone had EDGE-level internet, if at all. If this has any relation to that behavior.

**Comment by deckerst** [comment]
I'll close this one as neither you nor I can reproduce it, and there's not enough trace to investigate, but feel free to comment if it happens again.
