### ISSUE TITLE
Duplicate item after copying and replacing

### ISSUE THREAD

**Issue by deckerst** [deckerst/aves#335]
I also have this bug. I copied the same photo from one folder (WhatsApp images) to another (Camera) couple of times. The second time I tried to copy Aves asked me if I want to replace - I said yes. But as a result now Aves shows me 2 thumbnails for the very same photo in "Camera" folder. Both photos details are identical (including path). Rescanning or app restarting doesn't get rid of that duplicate. File manager shows me there's just a single file. 

```
Aves version: 1.6.13-play (Build 79)
Flutter version: 3.3.0-0.5.pre (Channel beta)
Android version: 12 (SDK 31)
Android build: SP1A.210812.016.G970FXXSEGVA9
Device: samsung SM-G970F
Mobile services: ready
System locales: en_GB, ru_RU
Aves locale: system -> en
Installer: com.android.vending
```

_Originally posted by @kha84 in https://github.com/deckerst/aves/issues/107#issuecomment-1248210810_

**Comment by deckerst** [comment]
@kha84 This is fixed for the next version. If you want to clean the duplicates, you can select all of them and move them to another album (if it asks to rename/replace/skip, choose `skip`).

**Comment by kha84** [comment]
Awesome - that move forth and back did a trick, I got rid of that duplicate. And happy to know this is fixed in the upcoming version. You're the star!
