### ISSUE TITLE
Tags are wiped from the photo after using editing features

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#338]
**Describe the bug**
Information about Tags assigned on photo is getting removed from the photo after using editing features.

**To Reproduce**
1. Create a new screenshot
2. Wait for it to appear in Aves collection
3. Assign any tag to that image and set some location
4. Edit that image with using [...] -> Edit. In editor crop it, save and allow Aves to override image.
5. See the tag has disappeared from the edited photo but GPS coordinates remained

**Expected behavior**
Ideally edits should preserve original image metadata - both GPS corrdinates and Tags. 
GPS is preserved now, but Tags are not.

**Comment by deckerst** [comment]
Aves does not include an editor at the moment, so it is not a bug with Aves but a bug/improvement you could report/suggest to whatever external app is used as an editor on your device.
