### ISSUE TITLE
Scrolling Wallpaper is not set for Large Images

### ISSUE THREAD

**Issue by RuthlessRuler** [deckerst/aves#341]
**Describe the bug**
So, if we have image with large widths (lot larger than the device width) the wallpapers is scrollable on home screen if we have multiple Home Screens Panels and the wallpaper shifts as we move LTR or RTL based on a action.

The same can be achieved if we used Simple Gallery to set the Image as wallpaper.

**To Reproduce**
1. Go to Aves
2. Click on a Wallpaper Image that's very wide
3. Set it as Wallpaper 
4. Go to Home screen and scroll left/right

**Expected behavior**
The wallpaper shifts as we move to other home screen.

**Wallpaper Example**
![flip-4-wallpaper-5](https://user-images.githubusercontent.com/20885012/191500564-09d01df6-fb75-4393-9796-81e222b91521.jpg)

**System information and logs:**
Aves version: 1.7.0-play (Build 80)
Flutter version: 3.3.2 (Channel stable)
Android version: 12 (SDK 31)
Android build: SKQ1.211006.001 test-keys
Device: Xiaomi M2102J20SI
Mobile services: ready
System locales: en_IN
Aves locale: system -> en
Installer: com.android.vending

**Comment by deckerst** [comment]
Fixed, but I noticed a couple of things:
- Samsung One UI Home does not support scrolling wallpapers,
- the specific scrolling offsets are up to the launcher/home app. For example, the Microsoft Launcher app can scroll wallpapers, but it doesn't align the wallpaper center on the home central page.
