### ISSUE TITLE
Include/Exclude folders

### ISSUE THREAD

**Issue by mani0608** [deckerst/aves#345]
**Is your feature request related to a problem? Please describe.**
I have a number of music videos which I'm syncing across my devices through Syncthing. The app includes these music videos along with my camera photography. 

**Describe the solution you'd like**
An option to include/exclude certain folders on my phone. 

**Describe alternatives you've considered**
I considered switching to Simple Gallery which does have this option. But, for some reason, it's really slow on my phone. Also I like the asthetics, widgets and customization features of this app. I like using it.

**Comment by deckerst** [comment]
You could exclude specific albums one by one, but in your case it seems better to exclude the root of all your music in one shot, via `Settings` > `Privacy` > `Hidden items` > `Hidden paths`. please give it a try and let me know whether that addresses your needs.

**Comment by mani0608** [comment]
Ah sorry. I didn't notice that option. My bad 🤦‍♂️
It worked like a charm and that's exactly what I was looking for 👌
