### ISSUE TITLE
An option for hide videos from widget collection

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#346]
Hi developer,

I don't want the videos to be displayed in the widget because their first frame is usually an inappropriate photo.

![Screenshot_2022-10-08-01-10-20-183_com miui home](https://user-images.githubusercontent.com/23485114/194665776-10b66abc-b590-433f-9913-ad44aa766717.jpg)

An option to hide videos from the widget collection.

**Comment by deckerst** [comment]
There's no need for a specific option for that. You could add the "Image" filter to the collection used by the widget. Do you see what I mean?

**Comment by xmha97** [comment]
Yes, thank you for your reply.
![IMG_20221008_052621.jpg](https://user-images.githubusercontent.com/23485114/194682302-0539291f-ff19-4a22-91d7-9aa879c2db25.jpg)
