### ISSUE TITLE
Customize home page

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#347]
Hi, how can I customize the home screen?
![Screenshot_2022-10-09-07-16-37-335_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/194737253-7e493035-15ab-4c82-95b0-1f4fa172dea2.jpg)

I want to see only camera photos when start the app:
![Screenshot_2022-10-09-07-28-55-422_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/194737301-c71f23f0-833f-49ab-98f6-ec21f8f511a6.jpg)

**Comment by deckerst** [comment]
It's not possible at the moment, but I'd like to implement it.

**Comment by deckerst** [comment]
Actually, why don't you use a shortcut? You can create a shortcut to any filtered collection from the Collection page menu > "Add shortcut", and then launch this shortcut instead of the normal app icon.

**Comment by xmha97** [comment]
I am using the widget to access this app.
![Screenshot_2022-10-09-22-42-59-700_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/194775353-cc2d2623-51fe-48ad-8138-f7f8c6b983c9.jpg)
Please add an option for widget settings.
![Screenshot_2022-10-09-22-43-54-662_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/194775363-f2936c7f-fcbb-44fa-bdb5-91521cf85580.jpg)

**Comment by deckerst** [comment]
Ah, i see. Then opening the app by the widget should open it to the collection configured for that widget. For example if the widget is configured with the "image" and "camera" filters it would open the app to the `Collection` page with "image" and "camera" filters already there. Is that your expectation?

**Comment by xmha97** [comment]
Yes 🤩
