### ISSUE TITLE
Add an option to remove drawer

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#349]
Hi, the drawer is useless for me and I want to disable it.
Please add an option to remove the drawer.
Thanks.
![IMG_20221011_162653_892.jpg](https://user-images.githubusercontent.com/23485114/195096774-313e8310-bd25-47e8-a4ef-1a019fb2fd0a.jpg)

**Comment by iJahangard** [comment]
As you may know, many apps just deleted the drawer add people felt good about it
Like some Google apps (ofc. GPhotos) 
The drawer is not useless or something but some people may or may not like it
I got used to it but prefer without drawer
Problem is you had drawer and added navigation bar which i think it kinda a bad design
The drawer also show over all other content which make you do more steps to find something
Navigation bar can have a 5th icon which can do what you expect from the drawer Or you can combine different parts of drawer to other layers that they linked to navigation bar by their icons (you may get some idea if you take a look at Google Gallery and Google photos and make something with your own type of specific design)
Please don't be straight about it I'm sure you will come up with a good combination
