### ISSUE TITLE
After Wallpaper change, the App goes back to default nav

### ISSUE THREAD

**Issue by RuthlessRuler** [deckerst/aves#350]
**Describe the bug**
Hey, so I tried setting the wallpaper and it worked well, but I noticed that after setting the wallpaper the app would close the current image and go back to collection folder. (Default page/view)

**To Reproduce**
1. Go to Albums tab from bottom menu
2. Click on folder containing an image 
3. Set the Image as Wallpaper

**Expected behavior**
After successfully setting up the image as wallpaper, the app keeps displaying the image .

**Screenshots**

**System information and logs:**
Aves version: 1.7.1-izzy (Build 2081)
Flutter version: 3.3.4 (Channel stable)
Android version: 12 (SDK 31)
Android build: SKQ1.211006.001 test-keys
Device: Xiaomi M2102J20SI
Mobile services: ready
System locales: en_IN
Aves locale: system -> en
Installer: com.google.android.packageinstaller

**Additional context**

**Comment by deckerst** [comment]
I just tried and for me it comes back to the viewer, as expected. Maybe I misunderstand the issue. Would you mind attaching a screen recording?

**Comment by RuthlessRuler** [comment]
> I just tried and for me it comes back to the viewer, as expected. Maybe I misunderstand the issue. Would you mind attaching a screen recording?

I currently have my default home to collection page(default option). Then I set an image by opening Album page and picking relevant file. After setting the wallpaper, the apl displays the viewer window with image but then kicks me back to Home Page (ie Collection page).

If I set my home page to album, this bug doesn't trigger.

**Comment by deckerst** [comment]
Thanks for the logs, I'll take a look.

I would appreciate a screen recording, though. If you're worried about privacy, feel free to [email me](mailto:gallery.aves@gmail.com) the recording instead.

**Comment by RuthlessRuler** [comment]
https://user-images.githubusercontent.com/20885012/195277900-3372a4fa-87cb-472f-ba6a-e0329bdd705c.mp4

Here is a video describing the issue. While making the video, I also noticed that there was no option for "Allow Only " folder. Ie Only Images in Allowed Folders will be displayed and rest all are hidden.

**Comment by deckerst** [comment]
@RuthlessRuler 

Does it still happen with the latest version of Aves v1.7.10?

Does it happen reliably or randomly?

Do you use a custom ROM? Is your device rooted?

**Comment by RuthlessRuler** [comment]
I'm on MIUi 13, Android 12.

On latest build, 1.7.10, after setting wallpaper it goes back to All Collection page/view.

**Comment by deckerst** [comment]
No custom ROM? I saw in your original report "Android build: SKQ1.211006.001 test-keys" and i thought `test-keys` was strange.

**Comment by RuthlessRuler** [comment]
> No custom ROM? I saw in your original report "Android build: SKQ1.211006.001 test-keys" and i thought `test-keys` was strange.

Nope. Its stock MIUI 13.

**Comment by deckerst** [comment]
If you don't mind, could you please install this temporary build:
https://drive.google.com/file/d/1I01jYfoM66UHML8QkYytg5aJesAra_DD/view?usp=share_link

This build will install the app `Aves [Profile]`, along the app `Aves` you already have. Changing settings in `Aves [Profile]` won't modify your settings in `Aves`.

Please launch `Aves [Profile]`, try to set a wallpaper (selecting `Aves [Profile]`, not `Aves`, as the app to set the wallpaper). If you still get the redirection issue, please export the logs from `About` > `Bug Report` and attach them here.

**Comment by RuthlessRuler** [comment]
Still facing the issue.

Logs: https://0.0g.gg/?1b7e73b07c48bc98#2HQ9XZTCwWedbifx6MBvzauK9DHbHxiia3esRhsV1C3X

**Comment by deckerst** [comment]
I suspect that your device is aggressively killing app activities as soon as you leave them. And Aves is not currently designed to resume with your last screen in this case. I intend to work on that.

I still don't understand why it fails with `Collection` as home, while it works with `Albums` as home.

If you have insight into the possible app killing, I'm all ears.

**Comment by RuthlessRuler** [comment]
I dont have the device to check for this issue.
