### ISSUE TITLE
Cannot choose different custom cover

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#351]
**Describe the bug**
Cannot choose different custom cover for my album. I can choose an initial custom cover, but not replace it with another.

**To Reproduce**
1. Go to Albums
2. Select an album
3. Click on edit cover
4. Choose a custom cover
5. Go back to albums
6. Choose the same album again
7. Click on the edit button to choose a different custom cover
8. Close and reopen the app. The old cover is shown.

**Expected behavior**
Custom cover should be edited

**System information and logs:**
Aves version: 1.7.1-izzy (Build 2081)
Flutter version: 3.3.4 (Channel stable)
Android version: 12 (SDK 32)
Android build: lineage_raphael-userdebug 12 
Device: Xiaomi Mi 9T Pro
Mobile services: not available
System locales: en_US
Aves locale: system -> en
Installer: com.android.packageinstaller

[aves-logs-20221013_010824.txt](https://github.com/deckerst/aves/files/9769197/aves-logs-20221013_010824.txt)

**Comment by deckerst** [comment]
I can't reproduce on my device, and i don't see issues in the attached logs.

Do you experience this with specific albums / specific picked items? Did you get this issue starting with Aves v1.7.1 but not with previous versions?

If you can, could you try the following:
- reproduce the issue,
- screenshot the `Info` page of the item you picked as a cover but got ignored,
- go to `Settings`, export the "Covers", and attach the exported file.

**Comment by Donkey-Doug** [comment]
Info page (but it happens on all pictures):

![Screenshot_20221103-220258_Aves](https://user-images.githubusercontent.com/50382414/199833682-d75cf8ce-1952-4616-8535-d2b401633e6c.png)

**Comment by Donkey-Doug** [comment]
Exported covers:

**Comment by deckerst** [comment]
Thanks for following up! I'll take a closer look when i get to a computer.

**Comment by deckerst** [comment]
I believe that you experience this issue because something changed between v1.7.0 and v1.7.1, and you customized the cover of the albums `Apex` and `Animals` before v1.7.1. Could you please confirm my intuition by trying to set the cover of a brand new album? In that case I expect you don't get the issue if you try to modify it again.

In any case, I'll fix it to recover from the version mismatch.

**Comment by Donkey-Doug** [comment]
> I believe that you experience this issue because something changed between v1.7.0 and v1.7.1, and you customized the cover of the albums `Apex` and `Animals` before v1.7.1. Could you please confirm my intuition by trying to set the cover of a brand new album? In that case I expect you don't get the issue if you try to modify it again.
> 
> In any case, I'll fix it to recover from the version mismatch.

This is correct.
