### ISSUE TITLE
Picture Thumbnail Has Discoloration

### ISSUE THREAD

**Issue by GithubAccount990** [deckerst/aves#352]
**Describe the bug**

A specific photo I have is discolored when it comes to it being a thumbnail. Other photos dont do this that aren't grey/black/white and even if I download the same photo again but with a different source it does the same thing. 

**To Reproduce**

1. Download Starting Over by Chris Stapleton and the thumbnail is discolored after a few opens/restarting the app and this has happened with other grey/black/white photos. I have this by the way stored for my music collection in PowerAmp a powerful music player you can purchase via their website without any connection to Google on a degoogled phone.

**Expected behavior**

The thumbnail should be identical to the picture opened. 

**Screenshots**

![Screenshot_20221012-202737_Aves_1](https://user-images.githubusercontent.com/115674114/195472735-9e79989e-9a87-4f44-958e-6d7df900075f.png)

**System information and logs:**

None

**Additional context**

Clearing the app cache temporarily fixes the problem.

**Comment by deckerst** [comment]
I'm confused. The image you attached, is it a screenshot of what you see in Aves? Is it the original image?

Please attach (and clearly label):
- the original image/video,
- screenshot of what it is supposed to look like,
- screenshot of problematic discoloring.

**Comment by GithubAccount990** [comment]
Sorry if I'm not being clear enough. The image I attached is what I see in Aves when it as a thumbnail which would be the original image with problematic discoloring. Here is the photo enlarged without any discoloration and as it should look. 
![Screenshot_20221013-042639_Aves](https://user-images.githubusercontent.com/115674114/195545102-30fe44a7-a4bd-4000-a78a-7234d89ab897.png)

**Comment by deckerst** [comment]
Oh, i see. I understand now that the thumbnail is a highly compressed JPEG with color artifacts (the discoloration). Usually it doesn't matter much but it's very visible on this one.

Do you use large thumbnails? How many columns do you have in the grid?

If you go to the `Info` page of that item, do you see a `Exif Thumbnail` section, like this?
![Screenshot_20221013_104705](https://user-images.githubusercontent.com/13898333/195548949-5e89e72b-20ca-44a0-82a9-2da5488f7bde.png)

**Comment by GithubAccount990** [comment]
Tjanks for the fast response and I have four pictures per column and in the info table I see no Exif Thumbnail.

**Comment by deckerst** [comment]
Thanks for the kind words! But don't be too excited about the "fix" yet ^^
My first thought is that it's probably fixable by changing the JPEG compression quality, but it would come with performance tradeoff. Given that it would only be useful for a few images, i have to meditate on this. Maybe yet another opt-in setting...

**Comment by GithubAccount990** [comment]
Ok, thanks for the information. I'm sure you'll come up with a bright fix as it's certainly an annoying bug. I'll be waiting patiently.

**Comment by deckerst** [comment]
You might need to clear the app cache to see the change.

**Comment by GithubAccount990** [comment]
Thanks but in the bug report I mentioned it only temporarily fixes the problem.

**Comment by deckerst** [comment]
Sorry, I wasn't clear. I meant that the upcoming version of Aves will include a fix, but the cached thumbnails on your device might be the lower quality ones, so you would need to clear the cache after installing the upcoming version.

**Comment by GithubAccount990** [comment]
Ok, thank you. You fixed this quick:)
