### ISSUE TITLE
Panoramas fail to render

### ISSUE THREAD

**Issue by Terrance** [deckerst/aves#353]
#### Describe the bug

Panorama photos (with tags managed using digiKam) are heavily distorted when viewed full-size.

#### To reproduce

1. Locate a panorama photo.
2. Tap on it to view the full-size preview (which looks fine).
3. Tap on Open Panorama.

#### Screenshots

<details>
<summary>Screenshots</summary>

![The right side of the panorama](https://user-images.githubusercontent.com/4025899/195856788-b2bc1206-d2d1-4ff2-834b-1263756043b0.jpg)
![The left side of the panorama](https://user-images.githubusercontent.com/4025899/195856818-b5bb0c84-c365-4166-8ecc-917ae6b2ad20.jpg)
![The "back" of the panorama, where no image was captured](https://user-images.githubusercontent.com/4025899/195856851-85b731d4-6a71-41c8-87fe-8cdd50217237.jpg)
</details>

#### System information and logs

<details>
<summary>System information</summary>

```
Aves version: 1.7.1-izzy (Build 1081)
Flutter version: 3.3.4 (Channel stable)
Android version: 12 (SDK 31)
Android build: EB2103_11_C.07
Device: OnePlus EB2103
Mobile services: ready
System locales: en_GB
Aves locale: system -> en
Installer: com.google.android.packageinstaller
```
</details>

[aves-logs-20221014_141349.txt](https://github.com/deckerst/aves/files/9786598/aves-logs-20221014_141349.txt)

#### Additional context

[IMG_20220911_120020_tagged.jpg](https://user-images.githubusercontent.com/4025899/195855572-dd3249aa-ed57-4f20-873f-281dc6350c3c.jpg) is one such affected image.

See also: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2590#issuecomment-1243024371

**Comment by deckerst** [comment]
Thanks for the nice bug report! My first guess is that the 90° orientation declared in Exif doesn't gel well with the way I use the Google Panorama metadata. I'll take a closer look later.

**Comment by deckerst** [comment]
I wouldn't be surprised if other apps have trouble with this file... Its panorama metadata seems weird to me, probably because of the aforementioned rotation. Anyway, I fixed it by salvaging what I could, but I ignore the exact offset from top/left in those cases (the panorama will be centered).

**Comment by Terrance** [comment]
Curious, as all my panoramas have the same rotation issue -- quite possibly down to the OnePlus camera app writing dodgy metadata then.  I'll have to try some other camera apps with panorama modes and experiement...

Will give the fix a go in the next release and see if it helps with rendering the existing ones.

**Comment by Terrance** [comment]
Just got the update through, and looks like that's enough to render my existing panoramas (I think they still look slightly squished, but I'll chalk that up to the poor metadata).  :+1:

I've switched to a [GCam port](https://www.celsoazevedo.com/files/android/google-camera/) for my device in the meantime, which seems to produce panoramas with accurate metadata.

**Comment by deckerst** [comment]
Good to hear, thanks for the follow-up!
