### ISSUE TITLE
Customize AppShortcuts

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#354]
I need "Camera" and "Screenshots" on AppShortcuts.
![Screenshot_2022-10-15-22-19-15-434_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/196003238-873d8cba-fd99-445f-93e6-ee371ac89ed7.jpg)

**Comment by deckerst** [comment]
Do you know you can create shortcuts of anything from the `Collection` page?

1) Go to the `Albums` page
2) Tap "Camera"
3) On the `Collection` page, select menu ... > `Add shortcut`
