### ISSUE TITLE
A website for translation 

### ISSUE THREAD

**Issue by iJahangard** [deckerst/aves#355]
My main language is Persian (Farsi)
And I'm so willing to contribute
But the problem is that strings file you said is not comfortable for translation of a right to left language
If it's possible provide a link on **weblate.org** so i can translate the app to farsi

**Comment by deckerst** [comment]
I've set it up on weblate: https://hosted.weblate.org/projects/aves/
For now it's in trial but I'll request approval for `Libre hosting`.

I'm not familiar with the system yet. Not even sure whether other people can access it, create languages, etc.
Could you give it a try and let me know how it goes?

**Comment by iJahangard** [comment]
Thank you
I'll try it for sure & let you know

**Comment by iJahangard** [comment]
Hi! I have translated those strings that you inserted in weblate ,so that would be great if you put all the strings to weblate.org?

**Comment by deckerst** [comment]
From what i see at https://hosted.weblate.org/languages/fa/aves/ you just translated a few keys from the "Android" component, but most keys are in the "Main" component. All the keys are in Weblate, but they are split in a few components.

**Comment by deckerst** [comment]
@iJahangard @xmha97 Aves got validated by Weblate for a Libre plan, so i confirm that you can use Weblate to contribute.

**Comment by iJahangard** [comment]
> @iJahangard @xmha97 Aves got validated by Weblate for a Libre plan, so i confirm that you can use Weblate to contribute.

Absolutely we can , but what should I do while it only include 17 strings?
IDK whether its me doing it wrong or there's no more strings

**Comment by deckerst** [comment]
Did you see my [comment above](https://github.com/deckerst/aves/issues/355#issuecomment-1288128297) about components?

The "main" component isn't there in weblate for you?
![Screenshot_20221105_120631_Firefox](https://user-images.githubusercontent.com/13898333/200116890-f7b15570-58d7-471c-9c41-501e914bf93c.png)
