### ISSUE TITLE
Duplicate thumbnails glitch

### ISSUE THREAD

**Issue by 0xalis** [deckerst/aves#368]
**Describe the bug**

**To Reproduce**
1. Go to '...' camera roll
4. See error duplicate thumbnails 

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

I don't know how to attach logs, I have never used GitHub before and this is very confusing. I'm on mobile. I don't see an attachment thing.

Aves version: 1.7.1-play (Build 81)
Flutter version: 3.3.4 (Channel stable)
Android version: 13 (SDK 33)
Android build: TP1A.221005.002
Device: Google Pixel 6
Mobile services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.android.vending
![Screenshot_20221023-154301](https://user-images.githubusercontent.com/116525295/197421755-088118ff-dc74-42f8-8c34-35655c412a91.png)

**Additional context**

**Comment by deckerst** [comment]
Thanks for following up on this issue! And don't worry, I got your emails with the logs, etc.

The issue you encountered looks like one I fixed (or so I thought) in Aves v1.6.13. I fixed the issue that duplicates could appear when the app was discovering new items. But the fix does *not* clear existing duplicates once they appeared (for that, see below). It's possible that duplicates appeared in, say, v1.6.12 and you still see them in v1.7.1, even though new duplicates shouldn't appear anymore.

So I have a few questions:
- the duplicates you found, did they appear when you were using the current version of Aves you have (v1.7.1), or a previous version?
- do they appear randomly sometimes, or consistently?
- do you know any way to make them appear? (for example, downloading images from a browser, or copying them from a connected device)

To clean existing duplicates, there are several ways:
- move the items to a different folder,
- delete and restore them (as in the video you sent me),
- clear the app data (not only the app cache), but that's using a sledgehammer to crack a nut.
