### ISSUE TITLE
Recent not showing media from sdcard

### ISSUE THREAD

**Issue by telrod11** [deckerst/aves#376]
When I look at collections, it should show everything this month whether it be on the local storage are the SD card storage, and it doesn't

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by deckerst** [comment]
- #234

**Comment by telrod11** [comment]
May I please ask what "Not Planned" actually means?   TY

**Comment by deckerst** [comment]
Did you read #234 ? Please follow guidelines and provide details when opening issues.

**Comment by telrod11** [comment]
Sorry.   I just tried to complete it as I should have now.

__
Tony Elrod
***@***.***
