### ISSUE TITLE
Aves does not show photos from SD card in monthly collection

### ISSUE THREAD

**Issue by telrod11** [deckerst/aves#377]
**Describe the bug**
When viewing photos in collection, aves only shows photos that are on local storage not SD card

**To Reproduce**
Open aves
View "collection"
Observe that photos are missing from view

**Expected behavior**
Expected behavior would be seeing all the photos for the month of October whether they be in local dcim are in SD card dcim.   I'll attach screenshots from a competitor, f-stop, that renders these views as it should

**Screenshots**
![Screenshot_20221030-150707_F-Stop](https://user-images.githubusercontent.com/105058921/198897297-e9d38465-65a7-4309-9b87-6b44f1d8473d.jpg)
![Screenshot_20221030-150650_Aves](https://user-images.githubusercontent.com/105058921/198897298-6e2c2fa0-b4c1-4c11-bb04-695886e7fd0d.jpg)

**System information and logs:**
Aves version: 1.7.1-play (Build 81)
Flutter version: 3.3.4 (Channel stable)
Android version: 12 (SDK 31)
Android build: SP1A.210812.016.G781WVLS7FVI4
Device: samsung SM-G781W
Mobile services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.android.vending

[aves-logs-20221030_091354.txt](https://github.com/deckerst/aves/files/9896648/aves-logs-20221030_091354.txt)

**Additional context**
Thanks for the app!

**Comment by deckerst** [comment]
Thanks for the details.

The pictures you expect to see in October 2022, are they completely missing from Aves, or are they somewhere else with a wrong date? (You could double check this by searching for the name of one of these pictures, or searching for the name of the album.)

**Comment by telrod11** [comment]
They are completely missing from Aves.   

F-Stop (the other screenshot), shows them by date, and they are all there.

OK, digging a bit deeper....
1 - If you search "Recently Added" (which is probably where I was), it says "This Month"  (screenshot attached) with photos missing.
2 - If you deselect "Recently Added", it says "This Month" (screenshot attached), and the photos are there.

I guess maybe the only issue is how the app is deciding how long the month actually is in "Recently Added".
![Screenshot_20221031-084158_Aves](https://user-images.githubusercontent.com/105058921/199011035-cb7b3481-206a-42c2-8e19-33aba41033ae.jpg)
![Screenshot_20221031-084241_Aves](https://user-images.githubusercontent.com/105058921/199011042-fef50b9a-bee3-4499-b920-afa521cb7412.jpg)

**Comment by deckerst** [comment]
Good to hear that the pictures are actually detected by Aves. It's just a misunderstanding regarding the "Recently added" filter.

Aves uses, when possible, the date from the picture metadata, in other words the date when the picture was taken. This date is used for sorting, grouping, filtering, statistics, etc. The "Recently added" filter does *not* refer to that date, but instead refers to the date when the picture was added to your device.

More specifically, the "Recently added" filter only shows pictures added to your device in the last 24 hours. This is useful for example to quickly find pictures that you just downloaded/transferred but that were taken a long time ago.

**Comment by telrod11** [comment]
Ok, perfect, thanks!

__
Tony Elrod
***@***.***
