### ISSUE TITLE
Ship the 64-bit version instead

### ISSUE THREAD

**Issue by cohesive-flight** [deckerst/aves#379]
**Is your feature request related to a problem? Please describe.**
The current app being shipped to the IzzyOnDroid F-Droid Repository is incompatible with the Pixel 7 and Pixel 7 Pro. 

**Describe the solution you'd like**
I'd like for the 64-bit version to be shipped instead.

**Describe alternatives you've considered**
Install the app through Github, but that would require manual checks for updates.

**Additional context**
The Pixel 7 and Pixel 7 Pro only support 64-bit apps.

**Comment by deckerst** [comment]
I suppose the 64-bit version is incompatible with the devices that currently rely on the arm-v7 version. For now, I'll stick with the current version as it matches most devices.

Also, IzzyOnDroid policy regarding apk size means i can't ship the "fat apk" version (that contains all variants).

What you could do is use something like [Obtainium](https://github.com/ImranR98/Obtainium) to get the 64-bit version and track updates. Disclaimer: i haven't tried the app, i don't know whether it works.

You could also simply get Aves from the Google Play Store or Amazon Store. Same features.

**Comment by cohesive-flight** [comment]
That app is extremely useful. Thank you for recommending it.
