### ISSUE TITLE
Change subtitle position to top

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#380]
Please add feature below:
- Add an option to change subtitle position to top
![Screenshot_2022-11-02-08-57-43-598_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/199405683-af2fa617-fa16-43c8-a87d-921af7d08ab9.jpg)

Thanks

**Comment by xmha97** [comment]
Sorry for the late reply, some movies have hardcode subtitles and that's why I want to move the subtitles up of the screen.

![Screenshot_2022-11-13-02-44-24-772_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/201498218-32442e60-cae3-44ff-8cf0-ea6ece570593.jpg)

**Comment by deckerst** [comment]
Fair enough.

**Comment by xmha97** [comment]
> Fair enough.

In Windows, most players have this feature (PotPlayer, KM Player) but not in Android!
I really don't know how much this feature will be used by users, but it is really necessary for me.

**Comment by deckerst** [comment]
@xmha97 actually, now that the subtitle background height is fixed, can't you display your subs with a background on the bottom, over the hard-coded subtitles? The background would hide them.

**Comment by xmha97** [comment]
Yes, I can but I prefer to see the subtitle at the top of the screen.

**Comment by xmha97** [comment]
Thanks
