### ISSUE TITLE
Subtitle background

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#381]
Hi, please fix the subtitle background.
![Screenshot_2022-11-02-09-09-42-910_deckers thibault aves](https://user-images.githubusercontent.com/23485114/199407394-94ec3947-3698-49a3-ab09-a5de99820d90.jpg)
The subtitle language is Persian.

**Comment by deckerst** [comment]
I'm aware of this issue, as it happens with some other non-latin scripts too, like CJK. It's actually an issue with text rendering from the Flutter framework that Aves is using. I'll take a look whether a workaround exists.
