### ISSUE TITLE
android 12 media management permission

### ISSUE THREAD

**Issue by Heliosungum** [deckerst/aves#383]
**possible special permission missing**
modifying/deleting files in the downloads folder shows a prompt each time due to an android 12 update on my redmi note 9 merlin :
![image](https://user-images.githubusercontent.com/117355478/199704741-cb930826-873e-4bb6-bc99-b5e6a39a0ea2.png)

**possible solution:**
adding the MANAGE_MEDIA permission to the apps manifest

**google photos as an example (needed to be manually turned on too otherwise the same prompt would appear):**

![image](https://user-images.githubusercontent.com/117355478/199704117-aefbd148-bb61-49fb-9394-7c42984f0df0.png)

**google's dev docs:**
![image](https://user-images.githubusercontent.com/117355478/199704479-9013811b-7bce-43e7-8e96-9ec787adbad4.png)

**Comment by deckerst** [comment]
Thanks for reminding me. I wanted to add it (at least allowing the user to toggle it, even if there's no guiding from the app) and I forgot~~
