### ISSUE TITLE
Thumbnails Glitch (not the same as other one)

### ISSUE THREAD

**Issue by Mavendow** [deckerst/aves#384]
**Describe the bug**
Thumbnails are either duplicated from an older version (as reported in the other ticket) or "the file no longer exists" when duplicated image has been moved or deleted. The latter is still an issue even if the app is completely reinstalled.

**To Reproduce**
1. Have a corrupted media cache, or in my case, corrupted media cache permissions (which I can't fix, sorry. Even if I could, android always does this after a while since I often accumulate more than 10,000 photos. It was even worse on my previous phones.)
2. Open Aves
3. View invalid thumbnails

**Expected behavior**
No duplicated thumbnails

**Screenshots**
![Uploading Screenshot_20221105-083433.jpg…]()

**System information and logs:**
[aves-logs-20221105_084647.txt](https://github.com/deckerst/aves/files/9943835/aves-logs-20221105_084647.txt)
Image of media/24513 as shown in the log:
![Screenshot_20221105-084944](https://user-images.githubusercontent.com/114033461/200120753-e4881d26-4fe3-45b4-8f96-8db4ed28fbab.jpg)

Aves version: 1.7.1-play (Build 81)
Flutter version: 3.3.4 (Channel stable)
Android version: 10 (SDK 29)
Android build: QQ2A.200405.005
Device: Google Pixel 2 XL
Mobile Services: ready
System locales: en_us
Aves locale: system -> en
Installer: com.android.vending

**Additional context**
Suggestion: Use a dictionary (key-value pair array) that has the media URI as the key and the rest of the data as the values, thus preventing duplicates with no additional overhead since the URI needs to be available to the app anyway.
Suggestion 2: The duplicates showing as "the file no longer exists" apparently have a different media address unlike the duplicates I witnessed previously. However, that error takes a moment to trigger when the API fails to render the image. On my phone it would probably take days to eliminate them all. So, when grabbing the media URI/path, probably check if the image actually exists since that should be a much faster operation than a failed render. Maybe toss the bad ones into an array to avoid re-scanning them as disk I/O is usually slower than memory access.

I checked whether moving the image back to its original location has an identical media URI - it doesn't, so that should work. Maybe there are other quirks of the media URI I don't understand, though, because that creates a new issue. Upon moving it back the thumbnail DOES render but then on full view the app says "Oops!" I did this with media/24518 in this log, the new URI was media/24729 which I don't see in the log:
[aves-logs-20221105_091322.txt](https://github.com/deckerst/aves/files/9943897/aves-logs-20221105_091322.txt)

Hopefully these suggestions will keep computational overhead low. Sorry if you don't have access to Dictionary or File.Exists() or something, I don't know how to code on android.

**Comment by deckerst** [comment]
Thanks for the report!

A few assumptions here are not always true, because the media store and the way media URIs are allocated are not the same across Android versions. Anyway, besides the "other" issue, you might have stumbled upon an issue with items moved on Android 10 (which is now fixed but unreleased yet).

I hope to release the next version of Aves around next week. It will be best to upgrade, and then we can revisit this issue.

**Comment by Mavendow** [comment]
Yeah, you are correct. My original suggestion was a combination of URI and path to prevent potential overlap between two different but identically named files being moved into the same location. Then I thought, if the URI isn't the same between the two files anyway, why bother? Well, I don't know how you'd reliably differentiate files for thumbnail purposes if the URI is finicky barring a hash which is computationally intensive or a version case which is maintenance intensive.

Regardless, the basic idea is that if it's not possible for the array to contain duplicates then you don't need to scan for duplicates. All of my functional duplicates had identical URIs. All of the "the file is not found" duplicates were caused by moving the files while Aves was not installed and therefore did not have duplicate URIs. But if these URI patterns don't hold true then that might be useless information. I'll keep your advice about assumptions in mind for the future.

To add a point I accidentally omitted; some of these duplicates showed up in other gallery apps. Not the ones which were simply missing however, as that was unique to Aves. That difference is why I made a separate ticket.

Regarding "oops," it was caused by moving a file into the same file path that the media cache believed already contained a file. I'd seen "oops" before in other circumstances but not that specific case. It is indeed possible they're the same bug. I only mentioned it here because I believed it was related to the same root cause, that is, invalid duplicates living in the media cache.

I will keep an eye out for your update and let you know if these are fixed. Thanks.

**Comment by deckerst** [comment]
@Mavendow Do you still have issues with duplicates? If so, is it for files that you moved/deleted with another app?

**Comment by Mavendow** [comment]
Yes, most of the issue is still occurring. I don't actually know how to trigger the exact duplicates I reported initially, it had something to do with running a media scan, but it was kind of random. I haven't seen it since the newest update. If that is the issue with Android 10 that you patched, then I believe you did fix that particular bug, because I'm not seeing it.

However, the nonexistent duplicates caused by moving things with another app are still present. Which, I'll add, until recently I was not entirely clear on the fact it was caused by moving things with other apps. That may because I was also experiencing the Android 10 move bug and this may have confused my ability to discern between what was effectively two separate issues.

Out of curiosity I tried toggling the "update media index" option in my zip program to see if that would make a difference. Unfortunately, nothing seemed to change after doing that.

It might be my imagination but Aves does seem to be loading thumbnails more swiftly. So that's pretty neat.

**Comment by deckerst** [comment]
> the nonexistent duplicates caused by moving things with another app are still present.

Then it's a problem with the other app. That app is mismanaging items in the system Media Store database. Aves shows items from that database, including non-existent ones. That's on purpose so that 1) you can be aware that the Media Store is mismanaged, and 2) you can clean these items by deleting them in Aves.

I'll close this issue as it seems everything is fixed on Aves side.

**Comment by Mavendow** [comment]
First, your app stalls when it hits a missing file due to a thrown error taking far longer to process. The ones that loaded faster were the thumbnails of properly loading files, not the non-existent ones. Which means deleting the "mismanaged" files would, as I said initially, take literal days. So your initial reasoning is nonsensical. Second, the reason my media cache breaks is not due to the mentioned Zip app, I didn't even have that app on my previous phone. In fact, my previous phone became so corrupt that it threw thousands of errors a second and made the UI unusable. Though I'm not 100% sure of the actual cause I believe it's because android's webview does not appear to release all of its file locks on downloads until the phone is rebooted, and I download a hell of a lot of files. Third, even if you want to argue it's because of my own fault, if you actually wanted to help the user delete these files you could, far more easily than any user manually can, delete the nonexistent reference when an error is thrown within Aves' backend. I am not an Android dev but as a C# dev I do understand that doing this much is trivial.

I really don't mind in the slightest if you don't want to do anything about it. After all, this is a free and open source project, and maybe you're right that it's merely me being an idiot and causing user error. However, I also took time out of my day to try help you with your project because I thought it was useful and interesting. You are choosing, in my view, to lie to my face so I'll go away.  Since you gave me some fair advice about assumptions, I'll return the favor: I don't see why this kind of response is necessary when you could just as easily label it "nofix" and then say you can't be bothered.
