### ISSUE TITLE
Crash on Android KK

### ISSUE THREAD

**Issue by MikaelaMuller** [deckerst/aves#388]
**Describe the bug**
The app crashes instantly when opened after installing on Android 4.4.2

**To Reproduce**

1: Install the App
2: Open the App

**Expected behavior**
App should launch

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).
![2022_11_08_17 42 53](https://user-images.githubusercontent.com/91151184/200530798-fef04f55-c403-414b-82dc-b7387707d594.jpg)

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.
Device: Samsung Galaxy Tab 4 7.0
SoC: Marvell PXA1088
Android version: 4.4.2
Ram 1.5GB
[Logcat](https://pastebin.com/APZDnHmG) 

**Additional context**

Rooted using legacy software, Xposed installed.

**Comment by MikaelaMuller** [comment]
> 

Sorry but where can i find this about page > bug report?
Also yes this app never worked on my device which is why im subitting this bug report.

**Comment by deckerst** [comment]
Ah, i forgot you get a crash on launch, so you can't get to that page. Sorry, I'm dumb ^^

Did you install it from F-Droid / IzzyOnDroid? If that's so, could you try and install the [Google Play flavor APK](https://github.com/deckerst/aves/releases/download/v1.7.1/app-play-release.apk)?

By the way, I tried the app on an Android 4.4.2 emulator and it was working fine. I'll try and search this issue at the Flutter framework level.

**Comment by MikaelaMuller** [comment]
> Ah, i forgot you get a crash on launch, so you can't get to that page. Sorry, I'm dumb ^^
> 
> Did you install it from F-Droid / IzzyOnDroid? If that's so, could you try and install the [Google Play flavor APK](https://github.com/deckerst/aves/releases/download/v1.7.1/app-play-release.apk)?
> 
> By the way, I tried the app on an Android 4.4.2 emulator and it was working fine. I'll try and search this issue at the Flutter framework level.

I am going to try the googke play version now.

**Comment by MikaelaMuller** [comment]
Hello, i just tried the "Google Play flavour" of Aves and it crashed the same way the one from izzy did.

**Comment by deckerst** [comment]
If you can, could you please try to launch these 4 builds?
- [aves-play-profile_20221109_1030_default](https://drive.google.com/file/d/1E-szcs2SmAESPLRltZkRFrpq2MUEG_vK/view?usp=share_link)
- [aves-play-profile_20221109_1030_minified](https://drive.google.com/file/d/1chOkQ4C6KUuTj3VXLL6OHfAZO8yGOLk8/view?usp=share_link)
- [aves-play-release_20221109_1030_default](https://drive.google.com/file/d/1hUYoMzyE7QTIhyL50gNsP7dbb__vhZBt/view?usp=share_link)
- [aves-play-release_20221109_1030_not_minified](https://drive.google.com/file/d/1v-NRLO2JUd5CXya9OriaYneo-pLIexxD/view?usp=share_link)

There are 2 `release` builds, that will install/replace the "Aves" app, and there are 2 `profile` builds, that will install/replace the "Aves [Profile]" app.

I did some research but I'm not sure yet of the nature of the cause. If one of these builds work, this would help the investigation.

Also, if you get a crash with the `aves-play-profile_20221109_1030_default` build, could you put a screenshot of the stack trace like you did above?

**Comment by MikaelaMuller** [comment]
> If you can, could you please try to launch these 4 builds?
> 
> * [aves-play-profile_20221109_1030_default](https://drive.google.com/file/d/1E-szcs2SmAESPLRltZkRFrpq2MUEG_vK/view?usp=share_link)
> * [aves-play-profile_20221109_1030_minified](https://drive.google.com/file/d/1chOkQ4C6KUuTj3VXLL6OHfAZO8yGOLk8/view?usp=share_link)
> * [aves-play-release_20221109_1030_default](https://drive.google.com/file/d/1hUYoMzyE7QTIhyL50gNsP7dbb__vhZBt/view?usp=share_link)
> * [aves-play-release_20221109_1030_not_minified](https://drive.google.com/file/d/1v-NRLO2JUd5CXya9OriaYneo-pLIexxD/view?usp=share_link)
> 
> There are 2 `release` builds, that will install/replace the "Aves" app, and there are 2 `profile` builds, that will install/replace the "Aves [Profile]" app.
> 
> I did some research but I'm not sure yet of the nature of the cause. If one of these builds work, this would help the investigation.
> 
> Also, if you get a crash with the `aves-play-profile_20221109_1030_default` build, could you put a screenshot of the stack trace like you did above?


Hello,  i just got done testing all four variants.

Heres the `Profile` Variants

Heres the screenshot of the logcat of `aves-play-profile_20221109_1030_default`.
![Aves-profile-default](https://user-images.githubusercontent.com/91151184/201087358-64232fbc-f903-4bac-bd08-cf013edc8c29.jpg)
Full logcat: 
[Aves-Profile-default.txt](https://github.com/deckerst/aves/files/9980496/Aves-Profile-default.txt)
Note: Profile default didnt appear to have crashed from a fatal error.

Here's the one for `Profile minified`.
![aves-profile-minified](https://user-images.githubusercontent.com/91151184/201087699-0b3f083e-726d-453d-91d9-aa576a359e9e.jpg)
Full Logcat:
[aves-profile-minified.txt](https://github.com/deckerst/aves/files/9980505/aves-profile-minified.txt)

Here's the one for the `Release` versions.

Here's a screenshot of `Release Default`.
![aves-release-default](https://user-images.githubusercontent.com/91151184/201088390-a19e7447-4a59-4463-a601-93dd8c1afe80.jpg)
Full Logcat:
[aves-release-default.txt](https://github.com/deckerst/aves/files/9980540/aves-release-default.txt)

And lastly, the one for `Release Not Minified`.
This one behaved differently, it froze and a "Not responding" message popped up.
Multiple screenshots of logcat and message
The Message: 
![aves-release-not-minified](https://user-images.githubusercontent.com/91151184/201089560-30883f35-664f-4dd2-86cc-3b192b0abef4.jpg)
Logcat screenshots:
![aves-release-not-minified-logcat1 (2)](https://user-images.githubusercontent.com/91151184/201089700-0b17ca80-5743-4dec-9948-c0ce9163ad2a.jpg)
Full Logcat:
[aves-release-not-minified.txt](https://github.com/deckerst/aves/files/9980593/aves-release-not-minified.txt)

Thats all, thanks for responding to this issue.

**Comment by deckerst** [comment]
Thanks a lot. I believe the magic crash recipe is this:
- API 19
- Android Gradle plugin 7.3
- minified build

I filed this issue at the framework level:
- https://github.com/flutter/flutter/issues/115100

Could you please confirm whether [this build](https://drive.google.com/file/d/1YOKdNGG1G5yb-ojN3JLEKJraMW9o4JHo/view?usp=share_link) works for you? I hope to get this fix in the imminent new release of Aves.

**Comment by MikaelaMuller** [comment]
> Thanks a lot. I believe the magic crash recipe is this:
> 
> * API 19
> * Android Gradle plugin 7.3
> * minified build
> 
> I filed this issue at the framework level:
> 
> * [Crash when running minified app on Android KitKat (API 19) with Android Gradle plugin 7.3 flutter/flutter#115100](https://github.com/flutter/flutter/issues/115100)
> 
> Could you please confirm whether [this build](https://drive.google.com/file/d/1YOKdNGG1G5yb-ojN3JLEKJraMW9o4JHo/view?usp=share_link) works for you? I hope to get this fix in the imminent new release of Aves.

Hi, i just tested this and unfortunately it crashed.

Screenshot:
![2022_11_11_13 05 51](https://user-images.githubusercontent.com/91151184/201345025-871d9822-b5d5-44b7-a3bf-3773659c43f5.jpg)
Full logcat: 
[aves-logcat.txt](https://github.com/deckerst/aves/files/9990362/aves-logcat.txt)

**Comment by MikaelaMuller** [comment]
![2022_11_11_21 02 21](https://user-images.githubusercontent.com/91151184/201346279-3b838294-0d96-45f3-9d0e-be69f24ce1c3.jpg)
![2022_11_11_21 02 09](https://user-images.githubusercontent.com/91151184/201346286-6af5e676-ac3f-42ff-9c0b-e84941960df4.jpg)
![2022_11_11_21 01 44](https://user-images.githubusercontent.com/91151184/201346288-086aa196-0d5b-4eb8-94e4-42816a505361.jpg)
Some flutter related issues i found on the logcat i sent above

**Comment by deckerst** [comment]
> Note: Profile default didnt appear to have crashed from a fatal error.

The profile default build you tested the other day didn't crash and didn't get stuck, right? You could launch it and use it normally?

Related to your last logs, I see these reported issues:
1) Skia shader compilation issue, followed by `Fatal signal 11 (SIGSEGV) at 0x812d8000 (code=1), thread 13720 (1.raster)`, followed by a memory dump. Seems serious, but I see the same thing in the `profile default build` mentioned above.
2) Various `Could not find class...` and `Could not find method...` but it's normal on older device. It shouldn't prevent the app to launch and run.

From anonymous error reports, I see that there are some KitKat 4.4.4 and 4.4.2 users of Aves until v1.7.0 (but I don't know for v1.7.1 and above). Does [Aves release v1.7.0](https://github.com/deckerst/aves/releases/download/v1.7.0/app-play-release.apk) work for you?

Could you please let me know whether these builds crash/freeze/run fine?
1) [aves-play-release_20221113_1900_with_shaders](https://drive.google.com/file/d/16Qg5BF_XPPWCwMBqd9HrjAYctpTAQxC9/view?usp=share_link)
2) [aves-play-release_20221113_1900_no_shaders](https://drive.google.com/file/d/1re7wvZ8kcGnbYeryPnwze6NdYjcHS9Dd/view?usp=share_link)

**Comment by MikaelaMuller** [comment]
> > Note: Profile default didnt appear to have crashed from a fatal error.
> 
> The profile default build you tested the other day didn't crash and didn't get stuck, right? You could launch it and use it normally?
> 
> Related to your last logs, I see these reported issues:
> 
> 1. Skia shader compilation issue, followed by `Fatal signal 11 (SIGSEGV) at 0x812d8000 (code=1), thread 13720 (1.raster)`, followed by a memory dump. Seems serious, but I see the same thing in the `profile default build` mentioned above.
> 2. Various `Could not find class...` and `Could not find method...` but it's normal on older device. It shouldn't prevent the app to launch and run.
> 
> From anonymous error reports, I see that there are some KitKat 4.4.4 and 4.4.2 users of Aves until v1.7.0 (but I don't know for v1.7.1 and above). Does [Aves release v1.7.0](https://github.com/deckerst/aves/releases/download/v1.7.0/app-play-release.apk) work for you?
> 
> Could you please let me know whether these builds crash/freeze/run fine?
> 
> 1. [aves-play-release_20221113_1900_with_shaders](https://drive.google.com/file/d/16Qg5BF_XPPWCwMBqd9HrjAYctpTAQxC9/view?usp=share_link)
> 2. [aves-play-release_20221113_1900_no_shaders](https://drive.google.com/file/d/1re7wvZ8kcGnbYeryPnwze6NdYjcHS9Dd/view?usp=share_link)

Hi sorry for the lack of contributions for the last 3 days on this issue, adhd things.

Now then, i tested the two files attached here and `aves-play-release_20221113_1900_no_shaders` worked for me!
![2022_11_16_22 41 05](https://user-images.githubusercontent.com/91151184/202238343-089b6049-becf-41d1-a6c9-3f21885fe6d6.jpg)

while the one with shaders didnt, here's the logcat for `aves-play-release_20221113_1900_with_shaders`.
Screenshot: 
![2022_11_16_22 47 55](https://user-images.githubusercontent.com/91151184/202238204-81691e3c-5d94-4b23-9065-5ab85cdabd6a.jpg)
Full logcat: [aves-withshaders.txt](https://github.com/deckerst/aves/files/10023842/aves-withshaders.txt)

Hope this helps!

**Comment by deckerst** [comment]
> Hi sorry for the lack of contributions for the last 3 days on this issue, adhd things.

No worries!

> Now then, i tested the two files attached here and aves-play-release_20221113_1900_no_shaders worked for me!

Pre-compiled shaders are supposed to help, but they're completely optional. It's strange that the shaders prevent launching on your device. I don't even know yet if they prevent launching on all KitKat devices or only some devices. I'm in a pickle, because these shaders make the animations smoother for many devices, so I can't just remove them from the general build...

**Comment by MikaelaMuller** [comment]
> > Hi sorry for the lack of contributions for the last 3 days on this issue, adhd things.
> 
> No worries!
> 
> > Now then, i tested the two files attached here and aves-play-release_20221113_1900_no_shaders worked for me!
> 
> Pre-compiled shaders are supposed to help, but they're completely optional. It's strange that the shaders prevent launching on your device. I don't even know yet if they prevent launching on all KitKat devices or only some devices. I'm in a pickle, because these shaders make the animations smoother for many devices, so I can't just remove them from the general build...

The specs of my device might help.
I heard from people who developed ROMs for my device is that developing custom roms for it is a pain because of a lack of documentation.

![2022_11_17_01 58 45](https://user-images.githubusercontent.com/91151184/202257639-aa4ca8b0-243f-40e2-a27b-96b3a18f0b19.jpg)

**Comment by deckerst** [comment]
cf https://github.com/deckerst/aves/issues/398#issuecomment-1325530187

**Comment by deckerst** [comment]
@MikaelaMuller Aves v1.7.5 is available via IzzyOnDroid. Does it work well for you?
