### ISSUE TITLE
Change actual file date?

### ISSUE THREAD

**Issue by MotchoIV** [deckerst/aves#393]
**Is your feature request related to a problem? Please describe.**
Not really a problem more like an extension to the change date feature.
**Describe the solution you'd like**
Currently when I change the date of an image it doesn't actually change the file's date. I would love it if it is possible to be able to actually change the file date so that I can export the images with the modified date

**Comment by deckerst** [comment]
[Aves is not a file manager](https://github.com/deckerst/aves/wiki/FAQ#is-aves-a-file-manager), so it cannot change the file date to an arbitrary date. At best it could touch a file so its file date would become the current date, but that's not really interesting.

Aves focuses on standard metadata and not file properties. When you set the metadata date and move/send/sync the file somewhere, it still contains the metadata date you set. It's more resilient.
