### ISSUE TITLE
MP4 tagging doesn't work

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#396]
I am using the latest version of aves and the MP4 tagging doesn't seem to work. I always get the "failed" message. I am using android 9 if that makes any difference
I am really hyped about this feature

**Comment by deckerst** [comment]
v1.7.2 had an issue and MP4 editing was failing every time. v1.7.3 seems to work fine for me. If you're actually experiencing the issue with v1.7.3, could you please follow the instructions in `About` > `Bug Report` and paste here the system info and logs? And a sample video could be useful too.

**Comment by Ingegneus** [comment]
the file is actually somehow corrupted after the failed tag assignment... in my file manager it shows up as having 0kB. tried it with a few test videos. I wanted to upload one here, but I can't because github is telling me to upload a nonempty file. the video I appended is untouched yet.

Aves version: 1.7.3-play (Build 83)
Flutter version: 3.3.8 (Channel stable)
Android version: 9 (SDK 28)
Android build: PPR1.180610.011.N950FXXUGDVG5
Device: samsung SM-N950F
Geocoder: ready
Mobile services: ready
System locales: en_AT, de_AT
Aves locale: en -> en
Installer: com.android.vending
[aves-logs-20221111_193635.txt](https://github.com/deckerst/aves/files/9992632/aves-logs-20221111_193635.txt)

https://user-images.githubusercontent.com/78076361/201409892-a406fe6e-69c1-43c7-b8d4-4fb6851a46b0.mp4

**Comment by deckerst** [comment]
Damn, I can't reproduce on Android 12 but I do reproduce on Android 9. I need to check which platforms are impacted :/

**Comment by deckerst** [comment]
Thanks again for the quick report. I'll push the fix to a new release as soon as possible.

**Comment by deckerst** [comment]
@Ingegneus the update is in production on the Play Store. Please try and let me know if you still encounter issues.

**Comment by Ingegneus** [comment]
seems to be working. I will give it some further testing later

**Comment by deckerst** [comment]
@IzzySoft sorry to bother you but today i released several buggy versions of Aves (v1.7.2 v1.7.3) and finally a good one (v1.7.4). It seems IzzyOnDroid picked up v1.7.3, but not the latest one. I'm telling you this because users of Android 9 and below may corrupt their videos with Aves v1.7.3. Is it possible for you to manually update your system to pick up Aves v1.7.4 instead of waiting 24 hours?

**Comment by IzzySoft** [comment]
Ermergency sequence initiated. 1.7.4 will be up in a few minutes (update checker only runs once a day, starting around 6:30 UTC – that would be a bit late for this I feel). Wow, do you really have different screenshots for all those languages? :scream: OK, all here. Now I'll run publish, and for the F-Droid clients the new index will be there within 5 minutes or so. WebIf will update a bit later.

**Comment by IzzySoft** [comment]
Up now. And say what, I've triggered the importer on the webserver as well, so it should be visible now.

**Comment by deckerst** [comment]
@IzzySoft Thank you!

> do you really have different screenshots for all those languages?

I automated this so it's not painful to keep consistent and up-to-date. I run [this scenario](https://github.com/deckerst/aves/blob/develop/test_driver/driver_screenshots_test.dart) to cycle through the languages and take the screenshots, and then I run [this script](https://github.com/deckerst/aves/blob/develop/scripts/screenshot_post_process.sh) to resize/overlay/frame them for the different stores.

**Comment by IzzySoft** [comment]
:astonished: Wonderful! I first was afraid of "everything duplicated" (had that misunderstanding with several projects where the authors weren't aware of the fall-back to `en-US` for missing elements). So I've checked myself before publishing my comment – which then was more a :astonished: :bow: :bow: (kudos). You amaze me more every day :smile:
