### ISSUE TITLE
Slideshow viewer shortcuts.

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#401]
Good day. As always much appreciation.

•Would like to see more shortcuts added to the Slideshow viewer hopefully.
Eg. 
•Having all the slideshow settings tucked away in a menu popup while playing in the viewer as well as a numbered (44/250 for example) or otherwise progress indicator can really help with like, slideshow overall play time estimation, and ease of use - instead of always going into settings/viewer/slideshow to change the settings and losing current progress in the viewer.
And possibly a favorites button as well in the slideshow viewer, could help with adding images to the category much faster - instead of losing current slideshow progress, then to re-enter the slideshow afterwards.

Much thanks for your consideration.

**Comment by deckerst** [comment]
1) Access to slideshow settings during slideshow

Agreed.

2) Slideshow progress indicator

Agreed, I could add something like "44/250" on the overlay when you pause the slideshow. But I'm not sure about some of your suggestions like "overall play time estimation". Do you mean something like "3 hours remaining"?

3) Access to other actions during slideshow

Unlikely. The point of the slideshow is that it is playing automatically, without user interaction. If you wish to keep your device at hand and manage your gallery, just use the regular viewer, not the slideshow.

**Comment by DroidFloyd** [comment]
Appreciate your response

*Estimated play time - meaning guessing remaining time with my mind. (Not meant as a feature ask, sorry.)

3. Answering your #3 - The only other thing I would want other than the "progress indicator and slideshow settings" is a button to quickly add an image to favorites from the slideshow viewer.

-Reason being: Currently the "show in collection" takes you to the current image, but you lose the current slideshow progress and order if they're shuffled, the favorites button would stop me leaving the slideshow.
