### ISSUE TITLE
Optional linking of heart/favorites and x stars in xmp:Rating

### ISSUE THREAD

**Issue by JanWaldhorn** [deckerst/aves#406]
Picking up from Issue #143, I would like to suggest the following feature:

Would it be possible to optionally combine the heart with x stars in the settings? Within the app it is so much easier to quickly set a heart or to filter for it, but I miss this information in my photo management on the desktop, because the hearts are purely local.

Currently, I usually filter for hearts, mark all of them in the month and then set stars.

**Comment by JanWaldhorn** [comment]
Based on this, I would find it just as helpful to be able to automatically move the favorite images into the (sub-) folder "Favorites".

**Comment by deckerst** [comment]
> optionally combine the heart with x stars

What would it do? Adding to favourites would rate the item 5 stars? Removing from favourites would unrate it? Rated items would automatically be favourites? 1 star items too?

> Within the app it is so much easier to quickly set a heart

From how you use favourites as an intermediate step, it seems that the actual issue is that it's not easy/quick enough to rate.
I'm about to add the rate action as a potential viewer quick action:
 - #390

Additionally, long-pressing on the "rate" quick action button could display a transient 1 to 5 stars pop-up. So rating would become a simple long-press + slide gesture. I need to try this idea in practice.

> automatically move the favorite images into the (sub-) folder "Favorites"

I won't do that. It's a risky feature, and I prefer to solve the actual issue at its source.

**Comment by JanWaldhorn** [comment]
Thanks for the detailed answer.

> What would it do? Adding to favourites would rate the item 5 stars? Removing from favourites would unrate it? Rated items would automatically be favourites? 1 star items too?

Yes for me a favorite would be 3 stars and the number a rating within the favorites. Accordingly, even 1 star images would still be favorites. Definitely an optional feature because I understand it can be confusing.

> From how you use favourites as an intermediate step, it seems that the actual issue is that it's not easy/quick enough to rate. I'm about to add the rate action as a potential viewer quick action:

A quick setting would be great. I often mark multiple images and then assign stars are 4 clicks, which is a bit annoying in the long run.

> I won't do that. It's a risky feature, and I prefer to solve the actual issue at its source.

I understand that, I'll make a new issue to better explain the idea behind it, since it's only partially related to favorites.

**Comment by deckerst** [comment]
@JanWaldhorn In Aves v1.7.5, you can set a rating from a quick action in the viewer. Could you let me know if it helps your workflow, skipping the "favourite" step?

By the way, I haven't implemented (yet) the long-press idea mentioned above. Also, the fav button shows the current fav state, but the rating button does __not__ show the current rating. I'm thinking of improving this, but I'm undecided on the right way to do it.

**Comment by JanWaldhorn** [comment]
I'm looking forward to the long pressed option, that sounds promising. Maybe it would be easier to implement an additional x stars quick action?
But I would meanwhile prefer more the favorites folders as described in #407.

**Comment by deckerst** [comment]
It's now possible to:
1) display the rating in the viewer overlay,
2) use a long press gesture to rate the item from the rating quick action.

<img width="250" src="https://user-images.githubusercontent.com/13898333/204607086-1e3a1d04-e782-4bc0-8eeb-c8c57cb88ef4.png"/>

**Comment by deckerst** [comment]
With the coming changes to the quick actions (rate / tag / move / copy) and overlay (rate / tags), I think it's best to close this issue and let you try out the next version of Aves (whenever it will be released). Feel free to give feedback then.
