### ISSUE TITLE
Archive functionality like in Google Photos

### ISSUE THREAD

**Issue by dAtA-TRoN** [deckerst/aves#410]
**Is your feature request related to a problem? Please describe.**
An archiving function would be great to hide photos and videos from the collection-view that you no longer want to see but also don't want to throw away (e.g. pictures of an ex girlfriend or maybe a recently deceased family member and so on; there are many reasons for wanting to hide photos and videos).

**Describe the solution you'd like**
I would like to have a separate area called "Archive" where you can store photos and videos that you no longer want to see in the collection-view.

**Describe alternatives you've considered**

**Additional context**
Here's how Google solved it:
![IMG_20221124_205318.jpg](https://user-images.githubusercontent.com/71184627/203856638-b3b03461-7802-4c1b-8c86-506f2df35be4.jpg)

And here you can watch a short YouTube Video in which the feature is explained in detail using Google Photos:
https://youtu.be/aimOvvbZvDU

All that remains for me to say is thank you for your great work. Aves is a great gallery app. I love it.

**Comment by JanWaldhorn** [comment]
Isn't this already implemented under Privacy -> Hidden items?

**Comment by dAtA-TRoN** [comment]
> Isn't this already implemented under Privacy -> Hidden items?
> 

One might think, but using an archive is much faster and more flexible. Precisely because it is often just individual images you want to hide, not entire folders. In addition, you have the images in an archive very quickly at hand. They're just a swipe of your finger away. The hidden items option is something you use to make entire folders disappear. This is for items that you don't need for longer times.

**Comment by deckerst** [comment]
> The hidden items option is something you use to make entire folders disappear.

The hiding feature is much more powerful than that in Aves. You can hide __any__ filter. You can hide a specific tag, a country, app panoramas, a specific month... Just long press on a filter and select "Hide".

In your case, i would do this:
1) tag photos you don't want to see with the tag "archive"
2) hide the tag "archive"

And from now on, every time you tag an item with "archive" it will get hidden right away. If you want to show them again, you go to the "Hidden items" settings and unhide. No need to edit or move the files. Please give it a try and let me know how it goes.

**Comment by dAtA-TRoN** [comment]
Wow, okay... -That's cool. That is of course a very good alternative to do that. This is exactly how I will handle it in the future. Thanks for the advice. The thread can be closed now ☺️.
