### ISSUE TITLE
It would be nice if the map opened where most photos are taken or allow a default to be set.

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#413]
It would be nice if you could change where the map opened or if it opened on say where the last few photos were taken.

Allow a use to set a default location on where the map opens when viewing the entire collection or even if you could default it to the where the last photo was taken.

I'm not sure there is an alternative.

I love seeing my photos on the map, but I dislike having to scroll across the globe to get to where my most of my photos were taken. Maybe there is also a limitation in not being able to see the entire world map on a phone as it would make it easier to go straight to your area of interest.

**Comment by deckerst** [comment]
I have the same problem. With my pictures mostly in western Europe and eastern Asia, the whole collection cannot be displayed at the same time, and it opens in central Asia where I have few pictures, if any.

In general, I'm satisfied with automatically finding the right zoom and bounds to fit the map on all the images, but i will try and find a better strategy when they can't fit. If possible i don't want to add another setting, but have better default behavior instead.
