### ISSUE TITLE
Lithuanian Translation - Finished. (LT)

### ISSUE THREAD

**Issue by 70h** [deckerst/aves#415]
I've just finished the Lithuanian translation. (lt = LTU = Lietuvių)
https://hosted.weblate.org/languages/lt/aves/
so you may include it in the next release. Thank you for a great app!

**Comment by deckerst** [comment]
Wonderful, thanks for your contribution!
Would you like a preview build with your translation, to check out how it looks in practice before it gets released?

**Comment by 70h** [comment]
No need. 
Lately I've been finding it difficult to plan my free time, so I'm afraid I might take too long to do the check up. 
Thought if there will be any typos in the new version, I will try to iron out the kinks in the translation as soon as possible!
