### ISSUE TITLE
Replace Loading screen for Deletion with something better.

### ISSUE THREAD

**Issue by KAGEYAM4** [deckerst/aves#419]
**Is your feature request related to a problem? Please describe.**
Currently , if a large amount of data is deleted , a circular loading screen pops up to show deletion is ongoing, this makes aves unusable until the process is finished.

**Describe the solution you'd like**
Smaller Rectangular pop up at bottom , also which can be dismissed by sliding left or right on it like notification and the process should happen in background.

**Comment by deckerst** [comment]
While items are getting deleted in the background, do you expect to see in your collection the items not yet deleted, disappearing one by one? Or you expect the collection to look like the items are all already deleted?

**Comment by PhoenixCODE2322** [comment]
> While items are getting deleted in the background, do you expect to see in your collection the items not yet deleted, disappearing one by one? Or you expect the collection to look like the items are all already deleted?

The second option `expect the collection to look like the items are all already deleted` will be good.

**Comment by deckerst** [comment]
Duplicate:
- #750
