### ISSUE TITLE
Compact Mode for UI

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#420]
**Is your feature request related to a problem? Please describe.**
Currently, it is tedious to tag items, because there are multiple categories of tags (Current Tags, Recent, Top Tags) and each line and item takes up a lot of vertical space, which means I'm often blind on, like, half the options available to me because of the keyboard hiding them (it is standard height).

**Describe the solution you'd like**
I would like an option in the Settings to toggle a "compact mode" for these UI elements (and possibly others). This could reduce the item and line height to about 60% of their original height. This should be enough to make a substantial improvement to usability in this way without causing issues.

**Describe alternatives you've considered**
I have not considered many others, since it gets too much into the nuances of design. Maybe there are other options. If there are, I would be open to them, as well. This was the simplest and most standard solution I could think of.

**Additional context**
Here is a screenshot:
![Screenshot_2022-11-29_20-07-36](https://user-images.githubusercontent.com/59938024/204707261-6ddd4034-7047-4853-ac7d-db59558dd91d.jpg)

**Comment by deckerst** [comment]
Another way would be to not give focus to the text field when opening this page. So the keyboard wouldn't show up and all the page content would be visible.

**Comment by OkyDooky** [comment]
Hmm. That doesn't seem like it would solve my problem, since I type out part of my tags to find them. But, once I've applied one, if I search for a similar one, that category is obscured by the keyboard, because the (Applied) and (Recent) rows (and the tag bubbles) take up so much real estate.

**Comment by DroidFloyd** [comment]
> Hmm. That doesn't seem like it would solve my problem, since I type out part of my tags to find...

*Good day looks like you're using Gboard. A simple tap on the back button will solve that issue. If not you'll need to tweak you're keyboard behavioral settings.
![Screenshot_20221201-103025_Aves.jpg](https://user-images.githubusercontent.com/118023622/205093838-5c1c027b-609b-423a-b7a0-7d141644d834.jpg)![Screenshot_20221201-103038_Aves.jpg](https://user-images.githubusercontent.com/118023622/205093882-a5c1704d-6388-42ae-beca-a3ed265bd820.jpg)

**Comment by OkyDooky** [comment]
Actually, friend, it is [FlorisBoard](https://github.com/florisboard/florisboard). I also notice in your screenshots that the vertical resolution for the screen is larger than mine and that there is less "dead," or heavily padded, space between the categories.
>just hit the back button, bro

Also doesn't solve my workflow problem, because that was what I woild have to do (or scroll). I use the keyboard to search for my tags, because I like to be specific in my tagging, which leads to another issue I will fill out soon (having the search, partial or full, persist after tapping a tag - this will allow me to add multiple related tags with having to retype their partial strings).

**Comment by deckerst** [comment]
@OkyDooky would you say a typical image for you has 2~3 tags or more than that? And when you type, is it usually to then press enter to commit it, or to select one of the existing tags from your collection?

I also noted your comment about wiping the text field, but I'm trying to understand your workflow better first.

(And i believe that DroidFloyd's device isn't particularly more dense, but rather use larger fonts, and their screenshots show the search page, not the more challenging tag page.)

**Comment by OkyDooky** [comment]
> @OkyDooky would you say a typical image for you has 2~3 tags or more than that?

Definitely more than that. Sometimes it'll be as low as one (1) if I'm just tagging a character and it's a lone illustration of them. But, I can average about six (6) or more, if I'm describing any other elements. Even then, I'm making a conscious effort to not go full-blown booru autist and tag all the unique characteristics I notice.
>And when you type, is it usually to then press enter to commit it, or to select one of the existing tags from your collection?

I select from the tag bubbles that appear before hitting enter, because it seems faster to type just the bare minimum needed to bring it up and then add it. If you mean by "commit it" to create a new tag, I still wind up tapping the little plus icon next to the text box (though, I might have used the enter key and just not made a big mental note about it).
> I also noted your comment about wiping the text field, but I'm trying to understand your workflow better first.

Thank you. Should I still make a separate issue ticket for that?
The gist is that I'll start typing the most unique part of the tag I want (to narrow it down as much and immediately as possible) and then I tap on it when it comes up. However, there are sometimes similar tags that contain a "qualifier" element in it. For instace, "lipstick" and "red lipstick" could both be used. One to indicate the presence of that kind of makeup and the other to clarify the specific version of it, in case I want to search for all pictures that include a character with lipstick and/or search for just the subset of images.
I guess that went a little long, since I described my organizational structure and methodology as well. But, if I search for "lipstick," as an example, and then add it, I'll have to start typing again to bring up the "red lipstick," unless it is at the top of the Recent tags.
> (And i believe that DroidFloyd's device isn't particularly more dense, but rather use larger fonts, and their screenshots show the search page, not the more challenging tag page.)

Huh, that might be. It looked more dense (definitely taller, with 1080 x 2400 vs my 1080 x 1920), because the text for the category section was closer to the divider line than on mine. With mine, you can see the distance between "Recent" and the line above it is significantly bigger than in Droid's search page screenshot.
But, you're right: the distance between the category text and the tags looks about the same in both, but his text fills out the bubbles more.

**Comment by deckerst** [comment]
On the tag editor page:
1) I added a toggle to expand/collapse the current tags. So far it was always expanded, so if you had more than 2~3 tags, it was taking up several rows, making everything below more likely to be hidden by the keyboard. Now you can collapse the current tags on one row, and that setting is persisted, so you don't need to toggle it again every time you edit tags.
2) I placed the `Top Tags` section first, before the recent ones. As you type and narrow down the matching results, you're likely to find what you want in that section.
3) Added tags are now placed at the front of the current tags, so users get visual confirmation of the addition even when the row is collapsed.

<img width="250" src="https://user-images.githubusercontent.com/13898333/205485993-c3a819e1-fd83-487a-abfc-75d76108be7d.png" />

On the viewer, the tag quick action can now be long pressed to show the 5 most recently used tags, so users can quickly tag an item with one of these without going to the tag editor page.

<img width="250" src="https://user-images.githubusercontent.com/13898333/205485984-cccabf48-5e4a-478d-88b6-cb9a6c7c9631.png" />

**Comment by deckerst** [comment]
About (not) wiping the text field, I've thought about it and I won't implement that change, as I believe your use case (typing once to select several tags with the same beginning) is rarer than the more common case of typing / select one / typing / select another.

**Comment by OkyDooky** [comment]
These changes look great! There are a lot of minor solutions I didn't think of, but will definitely improve things for me (and hopefully a lot of others).
>I've thought about it and I won't implement that change

Hmm, even as a toggleable setting? I'm not sure why I didn't include that bit, because that was how I was thinking of it being implemented.
I agree that this is not the average workflow for the common person tagging just their photos, but this is more common for people who download large quantities of art from places like Pixiv or other sites (I mention Pixiv, because it allows artists to have multiple images per post, upwards of 100, so they can have comics or post collections of Twitter sketches for that week/month or to have variations on the same image). Those kinds of users would definitely have use for a tool that can help them tag large numbers of images easily and in a detailed way quickly. Some use desktop apps, but many use their phone to download and manage their content (usually with folders). And I believe this could help speed up the process for that, or at least make it a little less troublesome.

Again, thank you for what you have made. I was actually thinking of requesting an "overlay" mode for the tag editor to more easily see what I'm trying to tag, at some point, but you already implemented a solid start to that, which is more than I expected.
