### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#421]
Is Aves on the F-Droid official?
https://f-droid.org/packages/deckers.thibault.aves.libre/

If yes, why didn't you release the app with the original package?

I also want to know how it differs from the IzzyOnDroid version?

**Comment by deckerst** [comment]
Yes it is. See the discussion here:
- #29 

See the [wiki](https://github.com/deckerst/aves/wiki/App-Versions) for version comparison.
