### ISSUE TITLE
Add F-Droid badge

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#422]
Please add "Get it on F-Droid" button.

![IMG_20221201_000251_581](https://user-images.githubusercontent.com/23485114/204902430-164c8f5d-9b3b-4f41-aea8-2339e8c39a74.jpg)

![IMG_20221201_000414_272](https://user-images.githubusercontent.com/23485114/204902451-75a13267-16c8-428e-933e-c8993a4c3ea8.jpg)

Thanks.

**Comment by deckerst** [comment]
Thanks, but don't worry about that kind of things ^^
