### ISSUE TITLE
Allow photos to be dragged on the map so as to change their GPS coords

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#423]
Sometimes a photo will be displayed at the wrong place on the map, maybe due to poor GPS signal.

If you could long press and drag the photo (or group of photos) to another place on the map, then this could correct the GPS location quite quickly. After you release it, you could possibly have a toast message pop up and say GPS loc has been changed, click to undo. Another way could be to long press the photo and a menu pops up asking if you want to edit the location. This would then lock the photo in it's position and you could then drag the map around to the correct location before long pressing again and accepting the new location.

I think GPS location can be edited already, but not as easily as dragging the photo on map.

**Comment by deckerst** [comment]
Implemented via a context menu on map clusters and picking on map. It's not dragging, but i think it's as quick and more flexible in the end.
