### ISSUE TITLE
Preserve EXIF SubIFD > Date/Time Original when editing image

### ISSUE THREAD

**Issue by foss-** [deckerst/aves#425]
**Describe the bug**
When editing an image, Date/Time Original EXIF info is lost.

**To Reproduce**
1. open an image with Date/Time Original showing in EXIF SubIFD info
2. tap three dots icon > Edit
3. change selection
4. tap checkmark at top
5. save image

**Current behavior**
The new image no longer shows EXIF SubIFD info Date/Time Original.

**Expected behavior**
Date/Time Original is important info. It would be desirable to keep that info in the new image file.

**System information and logs:**
LineageOS 19.1-2022-11-28

**Comment by deckerst** [comment]
Aves does not include an editor. When you press "edit" in Aves, it forwards the item to whatever editor app(s) you have on your device. So you should open an issue with that editor app instead.
