### ISSUE TITLE
Support for modern image formats.

### ISSUE THREAD

**Issue by AniXL** [deckerst/aves#426]
**Is your feature request related to a problem? Please describe.**
There is a lack of support for newer standards of image formats.

I have started using JPEG XL for still images but there are no convenient way to view them on android. And I use AVIF to replace my GIFs but same issues here as well.

**Describe the solution you'd like**
Adding support for JPEG XL and AVIF will not only solve this issue but also make the app future-ready.

**Describe alternatives you've considered**
For now, I'm using standalone apps for decoding and viewing AVIF and JPEG XL (AVIF viewer and Jpeg XL Viewer). They have some issues and are inconvenient but work good enough.

Thanks.

**Comment by deckerst** [comment]
Regarding JPEG XL, there's already this issue:
- #56 

As for AVIF, decoding support is already provided by the device (from Android 12 onwards, if my memory serves me correctly) and i don't intend to provide separate AVIF support for older devices.

**Comment by OkyDooky** [comment]
Just to clarify re: AVIF, this means the app should play well with the files as long as the device supports (and is running) some form of Android 12 and above? I mean, aside from bugs and quirks, it should basically work out of the box?

**Comment by deckerst** [comment]
Yes, for decoding. But metadata listing and editing isn't supported.

**Comment by OkyDooky** [comment]
Ah, that makes sense. Also, I saw in the other issue thread you mentioned possibly using FFmpeg to possibly decode them for older Android versions. Did that not seem viable?

**Comment by deckerst** [comment]
It was just an idea, and I didn't explore it because it doesn't seem necessary. Having AVIF support on modern devices only is good enough for me.

**Comment by OkyDooky** [comment]
Alright. I was just curious if it turned out to not be viable. Thanks for clarifying.
