### ISSUE TITLE
Delete, files app broken

### ISSUE THREAD

**Issue by Zarbok786** [deckerst/aves#427]
When trying to delete an image/video I'm printed to set the directory of the images folder but when it opens up the files app it is broken (shows just the basic ui) then crashes. I don't know why this is happening every other app that uses files when importing/setting directory works fine.
![Screenshot_20221202-223045_Aves_Libre](https://user-images.githubusercontent.com/65620861/205400884-d74a032c-f14a-4748-8ee8-69bd7c28f373.png)
![Screenshot_20221202-223042_Files](https://user-images.githubusercontent.com/65620861/205400890-6e1de81d-64a9-463c-8061-0ac05d297df7.png)

**Comment by deckerst** [comment]
Please follow the instructions in "About" > "Bug Report" and paste here the logs & system info.

Also:
- Do you use a custom ROM?
- Is your device rooted?
- Did you enable error reporting in Aves?

**Comment by Zarbok786** [comment]
> Please follow the instructions in "About" > "Bug Report" and paste here the logs & system info.
> 
> Also:
> - Do you use a custom ROM?
> - Is your device rooted?
> - Did you enable error reporting in Aves?

I am using a custom ROM (Evolution X)
My device is rooted (Magisk)

Package: deckers.thibault.aves.libre
Aves version: 1.7.7-libre
Aves build: 8702
Flutter version: 3.3.9
Flutter channel: stable
Android version: 13
Android API: 33
Android build: evolution_fajita-userdebug 13 TD1A.221105.001 1669330020 release-keys
Device: OnePlus ONEPLUS A6013
Geocoder: ready
Mobile services: not available
System locales: en_GB
Aves locale: system -> en
Installer: io.github.muntashirakon.AppManager

I can't save the logs as files crashes when trying to save them

**Comment by deckerst** [comment]
Thanks for following up.

Did you try to bring this issue to the attention of the makers of Evolution X? Even if it doesn't happen with other apps, it is still a standard system dialog, out of reach of Aves code.

**Comment by deckerst** [comment]
Do you also get the system files dialog crash when you go to Settings > menu > Import settings?

And just to be sure, when do you experience the crash?
1) while browsing in the system files dialog,
2) at the moment you pick a file/folder in the system files dialog.

If you know your way around android tools, getting `adb logcat` when the crash happens would help.
Alternatively, installing the play version of Aves and enabling error reporting would help too.

**Comment by Zarbok786** [comment]
Seems like it may have been an issue with the ROM, I did a dirty flash to put the documentsui app back to normal but it still crashed. Running 'adb shell cmd package install-existing com.google.android.documentsui' and rebooting fixed it. Thanks for your help anyway :)

**Comment by Zarbok786** [comment]
I would like to add that the mixplorer Magisk module also causes issues with documentsui for anyone else having this issue
