### ISSUE TITLE
aves libre sometimes access geomobileservice-pa.googleapis.com

### ISSUE THREAD

**Issue by ToJeMoDo** [deckerst/aves#433]
Fore someone this is a bug, for most this this is a feature request.

When displaying the Infobox for a picture or a detailed view in the map with press on the picture the real address is calculated from the coordinates using the service of "geomobileservice-pa.googleapsis.com". This interfere with a google-free usage.

After blocking the access to "geomobileservice-pa.googleapsis.com" "aves libre" works fine and perfect - only a near address is displayed.

Two Proposal:
For OpenStreetMap maps please use an other method for calculation the address from the coordinates (reverse geocoding) like "Nominatim" but which is not for heavy users but an entry point for related services.

Alternative make a switch in the section privacy to control the call of the google function. The price for a google-free usage is displaying only the near address. 

But please don't drop the displaying of the real address.

**Comment by deckerst** [comment]
Aves Libre does not reference proprietary code from Google (or from anybody else), but Aves uses the standard [Geocoder](https://developer.android.com/reference/android/location/Geocoder) from Android. Apparently, on your device, you have the Google Mobile Services installed and they take care of responding to the Geocoder API calls.

The way your device responds to this Geocoder call is out of scope of Aves.

**Comment by pawlosck** [comment]
I hope you will change the decision and you will implement other way to translate gps coordinate to address.
It sad, but when i started to use aves, i receive spam mails like 'buy flat/house etc in [city, where i was]'.
It's always, when i  back from travel.

Ps. Your app is the best 🙂
