### ISSUE TITLE
Add share motion video feature

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#434]
Aves is the only app (apart from GP) that allows you to view motion photos which is amazing! It would be even more amazing if Aves had the ability to share the motion video from motion photos. Quite often I want to quickly share the video via DM but this doesn't work as most message apps compress the jpg and thus the motion part is removed.

When viewing a motion photo, it would be nice if the share option shared the video instead of the photo.

The only alternative that I have seen is either to upload the motion photo using GP and then share a link to the that motion photo, which is time consuming and annoying, as you have to use GP. Or, use GP to export the motion photo as a video and share that video which is again time consuming and frustrating as it forces you to use GP which is a bad user experience.

**Comment by deckerst** [comment]
If you opened a motion photo in the viewer, you can go to `Info` > menu > `Open video`, and then do whatever you wish with the video part (share, inspect metadata...)
<img width=300 src="https://user-images.githubusercontent.com/13898333/205588497-8671ba50-8eb5-4aa0-9812-2d6026f64e53.png"/>

But i think i could make things even easier by adding a long press menu to the `Share` quick action. Something like "share image only" and "share video only".

**Comment by petazonk** [comment]
Wow! I didn't even realise you could do this!

It works like a charm. A faster more visible way, like you suggested, might
be even better.

**Comment by deckerst** [comment]
<img src="https://user-images.githubusercontent.com/13898333/205980334-3e34753d-e2b5-4482-a2f7-8679b264cd1b.png"/>
