### ISSUE TITLE
Optimise playing motion photos by having just a play button (or a play and a pause)

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#436]
It takes two presses to play a motion photo when maybe just one is needed (unless the default is selected). This could also result in the removal of the default option for always playing motion videos.

Instead of having a default to always play or not play motion photos, instead just have a play button that is always visible (it will be either play or stop) . You hit the play button to play the motion photo. If you tap the photo while playing the MP then it pauses and if you tap the photo again it a plays from when it paused. If you scroll to the next photo it continues to play that motion photos as it remembers the state of the last play or stop motion. If you have the MP stopped, then it remember the state as you scroll between photos. Also, I'm not sure how much value is added by having the the position indicator of each MP as they are all nearly always only 2 seconds long anyway. The visual indicator of length and how far you are through it is not really applicable in MPs.

An alternative might be having 2 buttons which are play and pause. Play will start the MP and the play button will change to a stop button so you can get back to the high res photo. Pause (the equivalent of tapping the photo as mentioned in the previous paragraph) will pause the motion photo while keeping it at that exact low res frame and pressing it again will continue. Or, have each frame displayed within the play indicator (the bar which shows how far into the MP you are) and tapping one of the frames will pause and show just that frame.

**Comment by deckerst** [comment]
Thanks for the suggestions, but I'm not sure which problem you're trying to solve here.

As I understand it, people typically browse their collection and if they stumble upon a motion picture, they expect to see the picture a bit, and the movie a bit, with minimum/no effort. Details differ, but that's what basically Google Photos and Samsung Gallery do. And in Aves, if you enable motion photo autoplay, that's what you get too. The rest (playing specifically with the video part) does not have to be a one-tap action.

About your suggestion to `have each frame displayed within the play indicator`. Ideally I'd like to have that, to be on par with Google/Samsung features, but I'm a bit limited by the video library I'm using at the moment. As it's not an option in the short term, I'm happy to keep the regular video playback bar used throughout in Aves.

Overall, the current layout you see for motion photos is a particular case of the layout I use for mixed image/video content, also used for multi-track HEIC, or Samsung "single take". It is flexible enough to accommodate these, and I don't intend to overspecialize the layout unless it solves a core use case.

**Comment by petazonk** [comment]
Ok.

How about this, when you click on the MP thumbnail it immediately starts
playing the MP instead of requiring a second press on the play button?
Ideally I think it would be more efficient to play the video with a single
press.

**Comment by deckerst** [comment]
Pressing play is only necessary if auto play isn't enabled. Do you keep it
disabled?
