### ISSUE TITLE
Support Android TV

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#437]
Hi, I want to install this app on the TV.
Please support Android TV.
Thanks.

**Comment by deckerst** [comment]
Do you expect a different UI when it's on the TV?

**Comment by deckerst** [comment]
@xmha97 I just fixed a few things to launch and use it on TV, but I have doubts about a core functionality.
If you're willing to help and you know how to sideload APKs on your TV, could you try a build for me?

**Comment by deckerst** [comment]
@xmha97 Aves v1.7.8 should work on Android TV, but it has been rejected by the Play Store for the following reasons:
- **Missing DPad functionality**
Your app requires user interaction for menus or app navigation. Please make sure that all menus and app navigation are fully functional using a DPad. Please refer to our [DPAD Control](http://notifications.google.com/g/p/AM0OveoIDlMQOKPqAYX5bVjVg6qCAlRiRKBs5QdnjyzjNG3jAjWvdxZmD6SguqXBeq9m83SLSqU_FX2RiLpx3NrPoHccDKB0yHPwQxh85nmajFdXEVa8M-wwzIs4pgXzRYndrGmA1GqQMvZX6ovDtzu4fvkNEUWQWliDPPMUn2Sc7IHtDV1T8W5jRoHKSpgkNtqdXNoU1ZkA_tbmkjfAZac9u_6EzKUFEpi5XZJAXtY2GKDvBueQkDL4z7n3XA) and [Hardware Declaration](http://notifications.google.com/g/p/AM0OveqkT1kEVSKXr1Ez-LF03ruIzpdJ8PL95LTs0FOdg2K_8A0sbaRr4eZ3PMoPS73wW_NHGuNE_tLD9r6lrKBGspX-F9WpyCmczXPtxNXKYKA0da8utEyMdP_Nhp0La7OJB3RctJBqVL4PpUQomyNkXRUoO8dU8vQkNVt36MaNvj_s8PrLcbzp0vaeeiYRErXtp7IdSAoNqDHBdim_ugU2GlIU96CQUd4elKo3DKzgUeF6MItmz5cYIEPlMnyoZ88YCbmFj6C5) documentation.
- **Not designed in landscape orientation**
Your app or game has vertical letterboxing when displayed on TVs. Please design your TV app or game to be displayed in landscape mode. Please refer to our [TV Layouts documentation](http://notifications.google.com/g/p/AM0OveocaNAuP4mB29LhqzqPn-uD0nLni2gD0NSe-6T3OfkCF756I_hA8s0zFMLIlnqsa-By02kAw3E5QIGn_2VfNQFbjCgIZtJkS4OMGe4yPCamVhitb1diM0TxfTZ6KZu38tAC4dv_1PCUmL3Eji5AKJKKh_ZA4SNkgkREJH4nO268jfeldhl5wBX8PQQka_QlIrmx64yI9up9icrn4vs00AcIXrVquDU25OjZFZzJFxZi) for more details.

I don't get why they rejected it, as it was working fine on the emulator. If you know how to sideload an APK on your TV, could you please try Aves v1.7.8 and let me know how it goes?

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by deckerst** [comment]
> Thanks pray

So, does it work? Can you navigate and press the buttons with a DPAD?

**Comment by xmha97** [comment]
> > Thanks pray
> 
> So, does it work? Can you navigate and press the buttons with a DPAD?

Now I have no access to Android TV
But it is working fine on my phone with the keyboard.

https://user-images.githubusercontent.com/23485114/220794456-ac147876-96dd-455c-b40e-4380a657913a.mp4

Please add more keyboard buttons
For example:
`ESC`: back
`BACKSPACE`: back
`DEL`: delete
