### ISSUE TITLE
Tags assigned on photo is getting removed from the photo

### ISSUE THREAD

**Issue by axac** [deckerst/aves#441]
Describe the bug
Information about Tags assigned on photo is getting removed from the photo after .

To Reproduce

- Create a new screenshot
- Wait for it to appear in Aves collection
- Assign any tag to that image and set some location
- Upload in a photo manager (Photoview, Photoprism)
- The tag has disappeared in thé photo manager after being uploaded.

**Comment by axac** [comment]
in Photoprism, Aves tags are in "description" box.

**Comment by deckerst** [comment]
Isn't it an issue with Photoview/Photoprism?

Aves uses standards to store tags and location. These photo managers could easily read the metadata, but there's nothing Aves can do if they don't.
