### ISSUE TITLE
Zooming system on Aves App

### ISSUE THREAD

**Issue by turzo47** [deckerst/aves#446]
![Screenshot_2022-12-15-20-49-44-37_6a29bb0652347cc63e7de6f980acb9f5](https://user-images.githubusercontent.com/120658170/207891919-b38f9b60-9ebe-44a4-9cb3-a4d605688bfb.jpg)
![Screenshot_2022-12-15-20-47-30-69_ee4e2c77f5dd6d2e03bdeacf38a89f81](https://user-images.githubusercontent.com/120658170/207891954-e02d0cd6-00f5-4a0b-a934-88bee61e5f40.jpg) 
Difference between Aves and another local apk.
I have been using this app atleast 2 month. If I can zoom more than this it would be great. It’s really needed.

**Comment by deckerst** [comment]
Welcome to GitHub!

Can you explain further what you mean and why you need it?
Are you talking about the Viewer page, or the Collection page?
Are you zooming on vector images, raster images, videos?

**Comment by turzo47** [comment]
I don't know about vector image or raster image but I zoom on general photos that people use in there app. But sometimes it’s not Enough when i try to zoom. I just don't know what type photo are those. But zooming system should get more higher like I attached two screenshots up there, those are definitely blurry right now but some photos doesn’t get bluryy. I just don't wanna use another third party app. So that's why i am requesting you. Thank you.

**Comment by deckerst** [comment]
So you're zooming on regular raster images.

Aves already allows zooming to 500%. It's already high enough that you can see the blurry pixels. The other app on your screenshot allows you to go further, with even blurrier pixels.

Raster images have a native resolution, and when you go above 100% zoom, it's normal to see it get blurry.

I don't understand why you want to go over 500% zoom.
