### ISSUE TITLE
Several ideas - mostly appearance. 

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#447]
**Is your feature request related to a problem? Please describe.**
–

**Describe the solution you'd like**
1. Appearance:
1.1 Thinner image border (or none, if none then the thumbnail would need the round border ) and smaller corner radius. Perhaps slightly reduce font size of album title. 
![Screenshot_20221215-211528](https://user-images.githubusercontent.com/41201383/207961626-fbeba768-02fb-4e94-ba0c-e79245097e88.png)
(see Google gallery attach/ for a good example).
1.2 In grid mode, ability to define number of columns.
1.3 In list mode there is way too much empty space between each item. Suggest to reduce size of thumbnail. Slightly increase album font size (1px or so)
![Screenshot_20221213-135215_Gallery](https://user-images.githubusercontent.com/41201383/207958151-bc0defc7-45db-437f-8154-245ea12536bc.jpg)
 (see Samsung gallery attach/ for a good example - good spacing, not too much empty space). 
1.4 Perhaps add option for having the usual simple slide animation instead of current one, when swiping images. 
2. Ability to define custom tiers (name and order).

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by deckerst** [comment]
Do you know that you can resize the thumbnails by doing a pinch-to-zoom gesture? In effect changing the number of columns for "grid"/"list" view (but not exactly that in "mosaic" view).
