### ISSUE TITLE
Exif image description when viewing an image

### ISSUE THREAD

**Issue by polinom11** [deckerst/aves#449]
**Is your feature request related to a problem? Please describe.**
In addition to the problem: https://github.com/deckerst/aves/issues/448

**Describe the solution you'd like**
1. Display exif image description on top of the screen.
2. From the bottom, make a button for quick editing of the exif image description.

**Screenshots**

![1671137688057](https://user-images.githubusercontent.com/48948406/207969534-6b131f42-5dd3-4de0-841d-33f21c34de06.jpg)

**Additional context**
Ideally, I would like to find a gallery app with the ability to take notes on photos with the ability to upload in txt format.

**Comment by deckerst** [comment]
Do you know you can add editing actions to the viewer via `Settings` > `Viewer` > `Quick actions`?

![Screenshot_20221215_231341_Aves](https://user-images.githubusercontent.com/13898333/207978717-66b7e802-bef9-4e60-b8a2-a4ecc50d7c8b.png)
