### ISSUE TITLE
Moved files not detected

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#45]
I currently have two gallery apps on my phone, Simple Gallery Pro (from simple mobile tools) and Aves. If I move a file to a different folder using Simple Gallery Pro, these files do not show up in Aves. They are nonexistent in Aves. They are not in the original folder and not the destination folder. I used my file explorer to confirm the pictures were in the destination folder. It seems Aves fails to update the destination folder.

This only happens for some moved files. No matter what I do, these files do not show up in Aves except when I delete and reinstall the app.

**Comment by deckerst** [comment]
Thanks for the feedback. I confirm the issue.

Aves relies on the "last modified date" to scan for changes, but Simple Gallery Pro allows performing file operations without updating this date. I need to think of another way to scan for changes, hopefully without scanning the whole collection.

In the meantime, as a workaround for you to keep using both galleries, I suggest you disable the Simple Gallery Pro setting "Keep old last-modified value at file operations" (in "FILE OPERATIONS" section).
