### ISSUE TITLE
Apply Tag(s) From One Image to Group on Tap (or Long-Press)

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#453]
**Is your feature request related to a problem? Please describe.**
Currently, if you select multiple images, you can see all the tags they contain and how many of those omages they apply to. This is great. However, it is intuitive to me to tap on one of the applied tags to have it apply to the rest of the images, as well; it removes the tag, instead. The way to apply it is through the normal searching and adding process, shich seems weird, since it is already right there.

**Describe the solution you'd like**
I would like a general tap on the tag bubble to apply the tag to the group. Since the (x) is already there, tapping elsewhere in the bubble should not count as a removal then.
OR
Since some tags with only 1 or 2 characters can be quite small, I actually recommend getting rid of the (x) entirely and have a more intuitive visual flow that way. Then, to apply to group, long-pressing on the tag could toggle that function.

**Describe alternatives you've considered**
Other than above, none that fit in Aves' current workflow.

**Additional context**
None, at the moment.

**Comment by deckerst** [comment]
> I would like a general tap on the tag bubble to apply the tag to the group. Since the (x) is already there, tapping elsewhere in the bubble should not count as a removal then

Probably going to do it this way.

**Comment by OkyDooky** [comment]
Sweet. Looking forward to the next release. The last round with all the tagging workflow changes has greatly improved things for me and I've really enjoyed it.
