### ISSUE TITLE
Video Player UI layout needs to be optimized for left or right-handed touch use

### ISSUE THREAD

**Issue by Pentaphon** [deckerst/aves#456]
**Is your feature request related to a problem? Please describe.**
The Video Player UI layout is not optimized for left or right-handed touch use.

**Describe the solution you'd like**
1) Play button needs to be in the center of the screen rather than the right-most side of the screen so both thumbs can reach it easily.
2) The video player scrubbing bar is too short because the play button is next to it, making it harder to scrub through longer videos. The scrub bar should extend to both sides of the screen to make it longer, more precise and not biased towards handedness. The same way you see it in other video/audio players in portrait mode. 

**Describe alternatives you've considered**
From looking at other video players you can see that they made similar UI decisions to improve touch use. 

**Additional context**
N/A

**Comment by deckerst** [comment]
Go to Settings > Video > Controls:
- enable double tap to play,
- select "none" for buttons.
