### ISSUE TITLE
Android tv: viewer navigation prevents control access

### ISSUE THREAD

**Issue by joefast77** [deckerst/aves#459]
I'm using Chromecast wgt , it's running on android 12.
anyway the app works great except when playing a video press down to get to control buttons like seek forward and playback speed it's not working when you click right or left it skips to next or previous video .

**Comment by joefast77** [comment]
actually chromecast wgt is a deceive that allows you to download actual apps on so I've downloaded the app on the device , I'm using the remote to navigate through the app , so when I'm playing a video try to go to a button like playback speed or seek forward if i click on navigation buttons on the remote left or right it skips to next / previous video .
there's no way you can reach those buttons with the remote control of the device .
I hope my explanation is clear .

**Comment by joefast77** [comment]
what you said is right except when i click right or left it skips to next / previous video .

**Comment by joefast77** [comment]
![IMG20221222205155](https://user-images.githubusercontent.com/80571759/209185949-94b44dbf-15cb-4fd5-a591-7f6d02054c88.jpg)

only play/pause is possible .

**Comment by deckerst** [comment]
@joefast77 if I provided a test build, would you try and test it on your TV?

**Comment by deckerst** [comment]
@joefast77 could you try with Aves v1.7.10 and let me know whether you still have this issue?

**Comment by deckerst** [comment]
@joefast77 @xmha97

Aves v1.8.1 has been rejected by the Play Store for distribution to Android TV. They say the following:
`Your app is not navigable using a 5-way D-pad controller. App functionality should be navigable using 5-way D-pad controls. For example, within app (version code 92) buttons are unresponsive vis DPAD controller.`

When I test on the emulator, everything works fine using the DPAD, so I don't know what buttons they're talking about. I requested more precise feedback but they refuse to give any.

Could you try to sideload the app and let me know if you have this issue with unresponsive buttons (or other components)?
