### ISSUE TITLE
Autoblur NSFW

### ISSUE THREAD

**Issue by Terkyz** [deckerst/aves#461]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option in Reddit's autoblur-style settings, where content is shown censored until the user interacts with it or disables the filter.

**Describe alternatives you've considered**
Hiding a directory does the trick but does not work if the directory is the download directory.

**Additional context**

**Comment by DroidFloyd** [comment]
I know persons who use Gallery in Samsung secure folder for NSFW, I presume the same in Aves is possible as well.
I think that all nsfw content would have to be tagged as such first before that would be possible or a photo identification system, that sounds like it could be a privacy issue.

**Comment by Leonetienne** [comment]
Pls someone implement this

>  photo identification system

i would not use the sevice if it sent my nsfw stuff, as such, to some weird service
