### ISSUE TITLE
Dual instance of Aves

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#467]
Good day dev. Usually I was able to make a second instance of Aves with App Cloner, therefore I was able to use two Aves apps at once for browsing or split screen. It's no longer possible, cloned app no longer shows no images, even with permissions turned on. 

Could you please provide a second APK where the filename or such is different to be able to install Aves twice.

**Comment by deckerst** [comment]
You could install the Libre flavor. It has a different app ID so it can be installed along the other flavors. You can find the Libre flavor on F-Droid or directly on the GitHub release page.

**Comment by DroidFloyd** [comment]
Searched. Never found Libre flavor

**Comment by deckerst** [comment]
It's [here](https://f-droid.org/packages/deckers.thibault.aves.libre/). The Libre flavor is not on the Play Store. Have you installed F-Droid?
