### ISSUE TITLE
Openstreetmap is very very slow

### ISSUE THREAD

**Issue by Spielmops** [deckerst/aves#468]
In mapview the map is loaded very very slow, it takes a minute or more either zooming in or zooming out. My connection is FTH (100Mb), my wifi-speed ist 400Mb, my device is a Samsung S6 tablet with enough RAM and CPU-power and has nothing else to do without any Google-apps. 

I wish, the app could use my Osmand-maps ...

System info:
Package: deckers.thibault.aves.libre
Aves version: 1.7.8-libre
Aves build: 8802
Flutter version: 3.3.10
Flutter channel: stable
Android version: 12
Android API: 32
Android build: lineage_gta4xlwifi-userdebug 12 SQ3A.220705.004 2dfa72bd51
Device: samsung SM-P610
Geocoder: not available
Mobile services: not available
System locales: de_DE
Aves locale: system -> de
Installer: com.android.packageinstaller

Spielmops

**Comment by deckerst** [comment]
Is it also slow to zoom in/out areas with no photos?

Is it slow only for the Humanitarian OSM layer? The Stamen layers? All of them?

**Comment by Spielmops** [comment]
Stamen-layer and Watercolor are a little bit faster: zooming from 15km (measurement line on bottom) to 2km takes about 50 seconds, where the humanitarian layer takes 60 seconds. Loading speed is not any better without photos.

**Comment by deckerst** [comment]
Simply zooming in areas without any picture shouldn't block like that... There's no heavy processing at all. By the way, maybe I misunderstood but when you say it "takes 60 seconds", do you mean that the app freezes or is sluggish with low framerate during 60 secs, or that the app is responsive but the tiles are just loading slowly, as if the internet connection was slow?

Not fixing this issue, but as a workaround, you could install the Izzy version instead of the Libre one, and replace the GMap backend via MicroG, etc.. I cannot give precise instructions as it's not my setup, but I know some users do so, e.g. [Izzy](https://github.com/deckerst/aves/issues/70#issuecomment-1302130195) themself.

**Comment by Spielmops** [comment]
> Not fixing this issue, but as a workaround, you could install the Izzy version instead of the Libre one, and replace the GMap backend via MicroG, etc.. 

> S6 tablet with enough RAM and CPU-power and has nothing else to do without any Google-apps.

The app responds fast, but
the

tiles

a r e       l o a   d   i    n    g

v      e     r        y

s    l      o      w ....

**Comment by deckerst** [comment]
I see. Then I don't think there's anything I can do. The free tile servers are just slow for you. Feel free to try the workaround so you can plug whatever backend you prefer.

**Comment by Spielmops** [comment]
Ok, but why is tile-loading very fast with my browser?

**Comment by deckerst** [comment]
If I knew the answer, I'd fix it ^^
But it works normally for most people, I can't reproduce the issue, it's happening on a custom rom, and it seems out of Aves logic, so I doubt I'll find the answer.

I forgot to ask earlier, but you could save logs (via About > Bug Report) and attach them here. Maybe it will help.

**Comment by Spielmops** [comment]
The tiles for the map are loaded from hot, right? I found no way, to look or load their maps via browser and see, if they load fast or not. I load tiles of Openstreetmap just from Openstreetmap.org and they come fast. Maybe the different sources make the different speed?

I have Osmand installed and can change the map-source from off- to online and that online-map loads fast ...

**Comment by igorzhilin** [comment]
Exactly my issue and wording.

Tiles by Stamen are super slow. Other tiles also slow. In USA and Canada. On a Honk Kong Sim card. Just slow. 

Questions :
- where are the tiles by Stamen hosted? 
- how can I contribute to make it faster? (eg pay for the cdn or host own instance)

**Comment by deckerst** [comment]
> where are the tiles by Stamen hosted?

https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.png

> how can I contribute to make it faster? (eg pay for the cdn or host own instance)

You can't. I've added a couple of alternate map tile providers which allowed free usage, without quota nor API key. They can be slow, and they can stop their service whenever they want. It's unreliable, like anything provided for free, but at least they are hosted by companies. I won't have Aves rely on tile servers hosted by private individuals.

I you want a responsive tile service, why not using the Google layers? They're available with the `play` and `izzy` flavours of Aves (provided the Google Mobile Services are installed on your device).
