### ISSUE TITLE
Jittery transition when opening/closing images

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#469]
**Describe the bug**
Both opening any image from thumbnail view and closing it back to view thumbnails is jittery. Seems like there is an intermediate step that happens where the screen is changed (seems like it moves up/down very quickly) between image in full screen and thumbnail view which causes this.

This effect persists even when animations are disabled on Ave's "Accessibility" option.

[See video attachment](https://file.io/I4WZv0UdkMAs)

**To Reproduce**
Reproduced in attachment.

**Expected behavior**
A clean non-jittery transition between opening/closing images.

**System information and logs:**

Package: deckers.thibault.aves
Aves version: 1.7.8-play
Aves build: 88
Flutter version: 3.3.10
Flutter channel: stable
Android version: 13
Android API: 33
Android build: TQ1A.221205.011
Device: Google Pixel 4a (5G)
Geocoder: ready
Mobile services: ready
System locales: en_NL, pt_PT, nl_NL
Aves locale: system -> en
Installer: com.android.vending

--------- beginning of main
01-02 14:21:09.321 25227 25227 I d.t.a.MainActivity: onStop
01-02 14:21:09.322 25227 25549 I flutter : _AvesAppState lifecycle paused
01-02 14:21:11.016 25227 25227 I d.t.a.MainActivity: onStart
01-02 14:21:11.057 25227 25250 E OpenGLRenderer: Unable to match the desired swap behavior.
01-02 14:21:11.062 25227 25227 E SurfaceSyncer: Failed to find sync for id=0
01-02 14:21:11.062 25227 25227 E SurfaceSyncer: Failed to find sync for id=1
01-02 14:21:11.062 25227 25227 E SurfaceSyncer: Failed to find sync for id=2
01-02 14:21:14.271 25227 25549 I flutter : _AvesAppState lifecycle resumed
01-02 14:21:31.927 25227 25281 I b.n     : request user to select and grant access permission to path=/storage/emulated/0/Movies/
01-02 14:21:31.964 25227 25549 I flutter : _AvesAppState lifecycle inactive
01-02 14:21:32.554 25227 25227 E BLASTBufferQueue: [VRI[MainActivity]#6](f:0,a:1) Applying pending transactions on dtor 1
01-02 14:21:32.566 25227 25227 I d.t.a.MainActivity: onStop
01-02 14:21:32.566 25227 25549 I flutter : _AvesAppState lifecycle paused
01-02 14:21:33.056 25227 25227 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10393; state: ENABLED
01-02 14:21:33.056 25227 25227 I d.t.a.MainActivity: onStart
01-02 14:21:33.058 25227 25227 I d.t.a.MainActivity: onStorageAccessResult with requestCode=1, uri=null
01-02 14:21:33.059 25227 25549 I flutter : _AvesAppState lifecycle resumed
01-02 14:21:33.075 25227 25250 E OpenGLRenderer: Unable to match the desired swap behavior.
01-02 14:21:33.078 25227 25227 E SurfaceSyncer: Failed to find sync for id=0
01-02 14:21:33.078 25227 25227 E SurfaceSyncer: Failed to find sync for id=1
01-02 14:21:33.078 25227 25227 E SurfaceSyncer: Failed to find sync for id=2
01-02 14:21:33.078 25227 25227 E SurfaceSyncer: Failed to find sync for id=3
01-02 14:21:36.070 25227 25250 E OpenGLRenderer: Unable to match the desired swap behavior.
01-02 14:21:36.074 25227 25227 E SurfaceSyncer: Failed to find sync for id=0
01-02 14:21:36.074 25227 25227 E SurfaceSyncer: Failed to find sync for id=1
01-02 14:21:36.074 25227 25227 E SurfaceSyncer: Failed to find sync for id=2
01-02 14:21:36.074 25227 25227 E SurfaceSyncer: Failed to find sync for id=3
01-02 14:21:36.074 25227 25227 E SurfaceSyncer: Failed to find sync for id=4
01-02 14:21:36.119 25227 25283 E MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed.
01-02 14:21:41.839 25227 25281 I b.n     : request user to select and grant access permission to path=/storage/emulated/0/Movies/
01-02 14:21:41.860 25227 25549 I flutter : _AvesAppState lifecycle inactive
01-02 14:21:42.574 25227 25227 I d.t.a.MainActivity: onStop
01-02 14:21:42.577 25227 25549 I flutter : _AvesAppState lifecycle paused
01-02 14:21:43.738 25227 25227 I d.t.a.MainActivity: onStart
01-02 14:21:43.742 25227 25227 I d.t.a.MainActivity: onStorageAccessResult with requestCode=1, uri=null
01-02 14:21:43.743 25227 25549 I flutter : _AvesAppState lifecycle resumed
01-02 14:21:43.759 25227 25250 E OpenGLRenderer: Unable to match the desired swap behavior.
01-02 14:21:43.762 25227 25227 E SurfaceSyncer: Failed to find sync for id=0
01-02 14:21:43.763 25227 25227 E SurfaceSyncer: Failed to find sync for id=1
01-02 14:21:43.763 25227 25227 E SurfaceSyncer: Failed to find sync for id=2
01-02 14:21:43.763 25227 25227 E SurfaceSyncer: Failed to find sync for id=3
01-02 14:21:43.763 25227 25227 E SurfaceSyncer: Failed to find sync for id=4
01-02 14:21:43.763 25227 25227 E SurfaceSyncer: Failed to find sync for id=5
01-02 14:21:45.509 25227 25549 I flutter : _AvesAppState lifecycle inactive
01-02 14:21:45.544 25227 25227 I d.t.a.MainActivity: onStop
01-02 14:21:45.563 25227 25549 I flutter : _AvesAppState lifecycle paused
01-02 14:21:45.612 25227 25227 I d.t.a.MainActivity: onDestroy
01-02 14:29:22.167 26707 26707 E s.thibault.aves: Not starting debugger since process cannot load the jdwp agent.
01-02 14:29:22.183 26707 26707 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10393; state: ENABLED
01-02 14:29:22.197 26707 26707 D nativeloader: Configuring classloader-namespace for system apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/lib/arm64:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/base.apk!/lib/arm64-v8a:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.en.apk!/lib/arm64-v8a:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.nl.apk!/lib/arm64-v8a:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.pt.apk!/lib/arm64-v8a:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.xxhdpi.apk!/lib/arm64-v8a:/system/lib64:/system_ext/lib64, permitted_path=/data:/mnt/expan
01-02 14:29:22.205 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.arm64_v8a.dm': No such file or directory
01-02 14:29:22.205 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.arm64_v8a.dm': No such file or directory
01-02 14:29:22.205 26707 26707 W s.thibault.aves: Entry not found
01-02 14:29:22.205 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.en.dm': No such file or directory
01-02 14:29:22.205 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.en.dm': No such file or directory
01-02 14:29:22.205 26707 26707 W s.thibault.aves: Entry not found
01-02 14:29:22.205 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.nl.dm': No such file or directory
01-02 14:29:22.205 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.nl.dm': No such file or directory
01-02 14:29:22.205 26707 26707 W s.thibault.aves: Entry not found
01-02 14:29:22.206 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.pt.dm': No such file or directory
01-02 14:29:22.206 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.pt.dm': No such file or directory
01-02 14:29:22.206 26707 26707 W s.thibault.aves: Entry not found
01-02 14:29:22.206 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.xxhdpi.dm': No such file or directory
01-02 14:29:22.206 26707 26707 W ziparchive: Unable to open '/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.xxhdpi.dm': No such file or directory
01-02 14:29:22.206 26707 26707 W s.thibault.aves: Entry not found
01-02 14:29:22.208 26707 26707 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/base.apk:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.arm64_v8a.apk:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.en.apk:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.nl.apk:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.pt.apk:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_config.xxhdpi.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/lib/arm64:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/base.apk!/lib/arm64-v8a:/data/app/~~LHeAVzAg3M4KG0gd71n2aw==/deckers.thibault.aves-YhqAUknikV8J_nrJKKTxdA==/split_confi
01-02 14:29:22.211 26707 26707 W s.thibault.aves: JIT profile information will not be recorded: profile file does not exist.
01-02 14:29:22.211 26707 26707 W s.thibault.aves: JIT profile information will not be recorded: profile file does not exist.
01-02 14:29:22.211 26707 26707 W s.thibault.aves: JIT profile information will not be recorded: profile file does not exist.
01-02 14:29:22.211 26707 26707 W s.thibault.aves: JIT profile information will not be recorded: profile file does not exist.
01-02 14:29:22.211 26707 26707 W s.thibault.aves: JIT profile information will not be recorded: profile file does not exist.
01-02 14:29:22.219 26707 26707 V GraphicsEnvironment: ANGLE Developer option for 'deckers.thibault.aves' set to: 'default'
01-02 14:29:22.219 26707 26707 V GraphicsEnvironment: ANGLE GameManagerService for deckers.thibault.aves: false
01-02 14:29:22.219 26707 26707 V GraphicsEnvironment: Updatable production driver is not supported on the device.
01-02 14:29:22.221 26707 26707 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-02 14:29:22.221 26707 26707 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-02 14:29:22.222 26707 26707 I MultiDex: VM with version 2.1.0 has multidex support
01-02 14:29:22.222 26707 26707 I MultiDex: Installing application
01-02 14:29:22.222 26707 26707 I MultiDex: VM has multidex support, MultiDex support library is disabled.
01-02 14:29:22.227 26707 26707 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10393; state: ENABLED
01-02 14:29:22.228 26707 26707 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
01-02 14:29:22.229 26707 26707 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.3.2 for deckers.thibault.aves
01-02 14:29:22.254 26707 26707 I FirebaseInitProvider: FirebaseApp initialization successful
01-02 14:29:22.282 26707 26707 I d.t.a.MainActivity: onCreate intent=Intent { act=android.intent.action.MAIN flg=0x10000000 pkg=deckers.thibault.aves cmp=deckers.thibault.aves/.MainActivity }
01-02 14:29:22.314 26707 26707 W s.thibault.aves: type=1400 audit(0.0:193753): avc: denied { read } for name="max_map_count" dev="proc" ino=9558320 scontext=u:r:untrusted_app:s0:c137,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=deckers.thibault.aves
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: QUALCOMM build                   : 4783c89, I46ff5fc46f
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Build Date                       : 11/30/20
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.01
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Local Branch                     : QPR2
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Remote Branch                    : 
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Remote Branch                    : 
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Reconstruct Branch               : 
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
01-02 14:29:22.322 26707 26707 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-02 14:29:22.336 26707 26707 I AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
01-02 14:29:22.345 26707 26707 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
01-02 14:29:22.346 26707 26707 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
01-02 14:29:22.413 26707 26707 I d.t.a.MainActivity: onStart
01-02 14:29:22.469 26707 26731 E OpenGLRenderer: Unable to match the desired swap behavior.
01-02 14:29:22.599 26707 26707 E SurfaceSyncer: Failed to find sync for id=0
01-02 14:29:22.622 26707 26731 W Parcel  : Expecting binder but got null!
01-02 14:29:22.638 26707 26736 I flutter : Device has Google Play Services=true
01-02 14:29:22.655 26707 26736 I flutter : [sil] 2023-01-02 14:29:22.653142 [fijk] set log level FijkLogLevel{level:500, name:war}
01-02 14:29:22.655 26707 26736 I flutter : App setup in 182ms
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'android.os.Build$VERSION' loaded
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'android.os.Build' loaded
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'java.nio.Buffer' loaded
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'java.nio.ByteBuffer' loaded
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'java.util.ArrayList' loaded
01-02 14:29:22.666 26707 26707 I J4A     : API-Level: 33
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'android.media.AudioTrack' loaded
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
01-02 14:29:22.666 26707 26707 D J4A     : J4ALoader: OK: 'android.media.MediaCodec' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'android.media.MediaFormat' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'android.media.PlaybackParams' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'android.os.Bundle' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IAndroidIO' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.MediaCodecSurface' loaded
01-02 14:29:22.667 26707 26707 D J4A     : J4ALoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
01-02 14:29:22.670 26707 26707 D IJKMEDIA: ijkmediaplayer version : 
01-02 14:29:22.674 26707 26707 D IJKMEDIA: IjkMediaPlayer_native_setLogLevel(5)
01-02 14:29:22.675 26707 26736 I flutter : [sil] 2023-01-02 14:29:22.675067 [fijk] native log level 500
01-02 14:29:22.682 26707 26736 I flutter : Apply display refresh rate: auto
01-02 14:29:22.685 26707 26707 D permissions_handler: No permissions found in manifest for: []15
01-02 14:29:22.702 26707 26736 I flutter : disable Firebase & Crashlytics collection
01-02 14:29:22.703 26707 26736 I flutter : Storage check complete in 41ms
01-02 14:29:22.758 26707 26736 I flutter : MediaStoreSource load essentials complete in 53ms
01-02 14:29:22.758 26707 26736 I flutter : MediaStoreSource refresh start
01-02 14:29:22.758 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.000025 fetch known entries
01-02 14:29:22.876 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.118086 check obsolete entries
01-02 14:29:22.922 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.163363 add known entries
01-02 14:29:22.938 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.179176 load metadata
01-02 14:29:23.002 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000003526, mimeType=image/jpeg, dateModifiedSecs=1669721798, rotationDegrees=0, isFlipped=false
01-02 14:29:23.002 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000002455, mimeType=image/jpeg, dateModifiedSecs=1641567004, rotationDegrees=0, isFlipped=false
01-02 14:29:23.003 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001652, mimeType=image/jpeg, dateModifiedSecs=1620364308, rotationDegrees=0, isFlipped=false
01-02 14:29:23.003 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001653, mimeType=image/jpeg, dateModifiedSecs=1620364308, rotationDegrees=0, isFlipped=false
01-02 14:29:23.003 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001642, mimeType=image/jpeg, dateModifiedSecs=1619990260, rotationDegrees=0, isFlipped=false
01-02 14:29:23.003 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001417, mimeType=image/png, dateModifiedSecs=1613931604, rotationDegrees=0, isFlipped=false
01-02 14:29:23.003 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001418, mimeType=image/png, dateModifiedSecs=1613931604, rotationDegrees=0, isFlipped=false
01-02 14:29:23.003 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001229, mimeType=image/jpeg, dateModifiedSecs=1609314790, rotationDegrees=0, isFlipped=false
01-02 14:29:23.004 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000001009, mimeType=image/gif, dateModifiedSecs=1597173896, rotationDegrees=0, isFlipped=false
01-02 14:29:23.004 26707 26736 I flutter : Evict cached images for uri=file:///storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/kCisCiR.jpg, mimeType=image/gif, dateModifiedSecs=1672214303, rotationDegrees=0, isFlipped=false
01-02 14:29:23.004 26707 26736 I flutter : Evict cached images for uri=content://media/external/images/media/1000000454, mimeType=image/jpeg, dateModifiedSecs=1588673530, rotationDegrees=0, isFlipped=false
01-02 14:29:23.005 26707 26736 I flutter : Evict cached images for uri=file:///storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/68nNeD5.jpg, mimeType=image/gif, dateModifiedSecs=1672310980, rotationDegrees=0, isFlipped=false
01-02 14:29:23.028 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.269623 check obsolete paths
01-02 14:29:23.071 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.313177 fetch new entries
01-02 14:29:23.128 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.369202 analyze
01-02 14:29:23.133 26707 26736 I flutter : Device is connected=true
01-02 14:29:23.287 26707 26736 I flutter : MediaStoreSource refresh 0:00:00.528761 done for 3841 known, 0 new, 0 removed

**Comment by deckerst** [comment]
Thanks for the report.

Do you use a custom ROM?

**Comment by NDR-113** [comment]
No custom ROM, I use stock Android 13.

**Comment by deckerst** [comment]
I can't reproduce it...

Could you export your settings (via "Settings" > menu "..." > "Export" and selecting just the settings, no need for the rest) and attach the exported file here?

Also, if you've used a previous version of the app before, did you see this issue with the latest version only, or with previous versions too?

**Comment by NDR-113** [comment]
Hi,

here are my settings.
[aves-settings-20230103_202656.zip](https://github.com/deckerst/aves/files/10339268/aves-settings-20230103_202656.zip)

Yes, i have "Use cutout area" disabled.
