### ISSUE TITLE
Folder tiles on top of each other in album view (Bug?)

### ISSUE THREAD

**Issue by ProjectEphra** [deckerst/aves#47]
Hello everyone,

Ever since the last update from around 21 hours ago, aves has had a breaking bug (or feature?) for me.

The default view I like to use is the album view, by folder.
I like to see a tile for every folder that contains images/videos.
Now this usually displays correctly on my device, as two columns. Since the last update, the columns now display on top of each other, with tiles stacked on top of each other, and the right half of the display is empty.
This makes it a hassle to select the folders on the bottom of the stack, since only a tiny fraction of the tile is visible.

Not to mention that aves won't scroll all the way to the bottom, making it impossible to click on the very last tile because the android navigation bar is in the way.

I'm honestly not completely certain whether this is a bug or an intentionally implemented feature, since the app is clearly still aware of the existence of the tiles on the bottom layer of the stack, the way that they're displayed just makes them difficult to click on.

I have been using aves for a few months now and it has been absolutely perfect up until now.

---

**Aves** 1.4.2, with flutter 2.2.1 (from about)

**My device**
Pixel 3a (sargo)
Android version 11
Build no. RQ3A.210605.005
Kernel 4.9.248-ga11ff008926d6-ab72664851

I don't know whether any of this info is helpful, but more info certainly couldn't hurt. I'd be happy to provide any more info I have access to if it could help resolve this.

I wanted to attach a screenshot but github won't let me upload it. I'll try again later.

**Comment by ProjectEphra** [comment]
Hi! I didn't expect a quick reaction so I forgot about the issue for a while, sorry about that.

I didn't know about the pinching gesture in album view. I just tried it. Pinching in to make the tiles smaller does work. However, the far right column (5 columns in total) would still be empty, and at least two of my folders are in a stack. Not sure if the right column being empty is how it's supposed to be since I haven't tried it before.

Pinching back out to make the tiles larger does display the "shadow" tiles on the right column, I'm guessing as a preview for where the tiles would be. But when I let go they would return to stacking on top of each other.

Just tried attaching the screenshots again but it still didn't work. I'm guessing it's because I'm on firefox. Will try again when I get back home.

**Comment by deckerst** [comment]
Ok, thanks for the feedback and sorry for the inconvenience. I'll try and
release a fix soon.

**Comment by ProjectEphra** [comment]
![Screenshot Album 1](https://user-images.githubusercontent.com/58222762/121708616-0d4f9c80-cad8-11eb-93d4-21d8300bb502.png)
![Screenshot Album 2](https://user-images.githubusercontent.com/58222762/121708629-104a8d00-cad8-11eb-897d-57179468c1b3.png)

As promised, here are some screenshots. I just noticed that this issue also exists within the folder. The right column is also completely empty, and some pictures are stacking.

> sorry for the inconvenience

Please don't be! I'm enjoying aves and rooting for it to succeed. If I didn't care I would not bother with the bug report. Thanks a lot :)

**Comment by deckerst** [comment]
I've just released a fix. Could you please try v1.4.3 and let me know how it goes?

Out of curiosity, did you (or github) downscale the screenshots? I'm asking because their size don't match the 2220 × 1080 resolution of the Pixel 3a.

**Comment by ProjectEphra** [comment]
Hello again. I just installed the update and everything seems to have returned to normal. Thanks for the effort! I'm going to close the issue with this comment, and if you don't have anything against it, I'm going to remove the screenshots, as I'm not a great fan of having the some contents of my gallery publicly visible without good reason.

To your question: I haven't done any compressing actively, but I think since google moved the screenshot functionality to the little menu below the open window view, my phone has been taking the screenshots at a condensed resolution (Although please don't quote me on this, I'm not sure anymore). The resolution you have is actually the correct one.

Thanks again for the awesome work!
