### ISSUE TITLE
Add Portrait and Landscape tags to Search > Metadata so that people know they exist

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#470]
Recently both portrait and landscape metadata tags were added (thanks!) which work great, however, it might be good to show that these tags exist in the Search > Metadata tags.

It would be nice to see both tags show up on the metadata search fields, eg show both tags in the same place that the unlocated tag is.

**Comment by deckerst** [comment]
They are not in the metadata section, but they are already there, at the top, next to other type-related filters, like panoramas.

Also, on the Search page, when you start typing you can see matching filters, so you could start typing "land..." and you would see the matching "landscape" filter at the top.
