### ISSUE TITLE
Use native media controls for video playback

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#475]
**Is your feature request related to a problem? Please describe.**
When playing a video in Aves, it doesn't register a `MediaSession` in Android. This means that there are no system playback controls, and also that playback control buttons on external devices (eg. headphones) don't work.

**Describe the solution you'd like**
Implement Android's media controls

**Additional context**
Android Developers documentation https://developer.android.com/guide/topics/media/media-controls

It seems like the `fijkplayer` library does not support this, so it should probably be implemented in [deckerst/fijkplayer](https://github.com/deckerst/fijkplayer). Although I may be wrong about this.

**Comment by deckerst** [comment]
I've looked into it quickly when working on Android TV support. There is currently code to register sessions, but I haven't implemented handling of external playback controls. The code to register sessions is probably buggy, as I couldn't test it.

How did you test whether there were media sessions? Did you just try to control it via headphones or did you test it another way?

**Comment by flexagoon** [comment]
@deckerst I just assumed that there is no media session because there are no media controls. I haven't done any additional testing yet, so my theory may be incorrect.
