### ISSUE TITLE
Playback position is not remembered when video is opened with an intent

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#476]
**Describe the bug**
https://github.com/deckerst/aves/commit/87b007c60fb4ea1ace6a37fe1adf54e9c1db3c43 added support for resuming playback from the last remembered position. However, that feature only works when the video is opened from Aves itself, but not when it's opened from a different app via the `android.intent.action.VIEW` intent. 

**To Reproduce**
1. Open NewPipe
2. Download a video
3. Go to the "downloads" page in NewPipe
4. Click on the video
5. Skip to the middle of the video
6. Close the video
7. Open it again (either from NewPipe or from Aves)

You can use any other app that tries to open videos in the default gallery. NewPipe is just an example.

**Expected behavior**
The "resume playback" dialogue should show up

**System information and logs:**
```
Package: deckers.thibault.aves
Aves version: 1.7.8-play
Aves build: 88
Flutter version: 3.3.10
Flutter channel: stable
Android version: 13
Android API: 33
Android build: TQ1A.221205.011.2022122700
Device: Google Pixel 7 Pro
Geocoder: not available
Mobile services: ready
System locales: en_US, ru_RU
Aves locale: system -> en
Installer: com.android.vending
```

Can't attach the logs for some reason, but I don't think they are relevant. If they are, tell me and I'll try to upload them again.

**Comment by deckerst** [comment]
Just to be clear, your step 5 happens in Aves, right?

**Comment by flexagoon** [comment]
@deckerst yes
