### ISSUE TITLE
Support Picture-in-picture for video playback

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#478]
**Is your feature request related to a problem? Please describe.**
I sometimes want to watch a downloaded video while using other apps on my phone

**Describe the solution you'd like**
A picture in picture mode (like YouTube has, for example)

**Additional context**
- [Android Developer documentation](https://developer.android.com/develop/ui/views/picture-in-picture)

**Comment by deckerst** [comment]
@flexagoon Do you also expect PiP also for playing a video while continuing to use Aves itself?

**Comment by flexagoon** [comment]
@deckerst yes, probably, although it's really important for my use case, so I'm fine without that

**Comment by deckerst** [comment]
I'll handle the first use case: when pressing home while playing a video, it will go to PiP (if you enable it in the settings).

Because of boring technical details, I won't deal with the second use case for now. We'll see if users really need that in practice.

**Comment by DroidFloyd** [comment]
Please consider In-app PIP mode.
PIP mode doesn't work for Samsung Secure Folder (default android pip)

**Comment by deckerst** [comment]
@DroidFloyd if you want to report a bug or request a feature please open a new issue with all the required details.
