### ISSUE TITLE
Animation effect on browsing pictures

### ISSUE THREAD

**Issue by mizzunet** [deckerst/aves#48]
Could you please make this to Aves,
https://transfer.sh/12sAT3N/screen-20210626-141747.mp4

This is an archived project, Camera Roll, https://github.com/kollerlukas/Camera-Roll-Android-App

**Comment by deckerst** [comment]
Nice effect, thanks for the suggestion! It's done in https://github.com/deckerst/aves/commit/dc4db4c4e394b28aa49de9437c2772d7a276eb59 and will be in the next release.

Camera Roll and Aves use different UI components to scroll through the images, so don't expect an exact replica. I just added the parallax effect to what was already in Aves. It is notably different when the image doesn't take the full width of the device.

**Comment by mizzunet** [comment]
🤟

**Comment by wh7** [comment]
Is it possible to add an option to enable/disable this animation effect? I personnaly find it a a little bit dizzy.

**Comment by deckerst** [comment]
Instead of sliding the pictures, you could tap on the screen edge to go to
the previous/next picture without animation. You can enable this gesture in
Settings > Viewer > Tap on screen edge.
