### ISSUE TITLE
Don't maintain full brightness when viewing Info

### ISSUE THREAD

**Issue by e-t-l** [deckerst/aves#485]
**Is your feature request related to a problem? Please describe.**
When the Settings > Viewer > Maximum Brightness is active, max brightness is maintained even when viewing the item's Info page (which takes up the entire screen), making it painful to read. 

**Describe the solution you'd like**
Even when the Maximum Brightness setting is active, the Info page should be displayed at system brightness

**Describe alternatives you've considered**
- Disabling Maximum Brightness completely, which has obvious downsides. 
- Squinting

**Comment by deckerst** [comment]
> Squinting

Haha, nice.
