### ISSUE TITLE
Accrescent version code

### ISSUE THREAD

**Issue by Silther** [deckerst/aves#489]
**Is your feature request related to a problem? Please describe.**
The version code format used for Accrescent is not compatible with that used for IzzyOnDroid.
That's why you can't just change the app store.
> https://github.com/accrescent/accrescent/issues/160

**Describe the solution you'd like**
use a four-digit format (8900).

**Additional context**
> https://matrix.to/#/#accrescent-offtopic:matrix.org
> https://matrix.to/#/#accrescent:matrix.org

**Comment by deckerst** [comment]
I don't intend to change that.
