### ISSUE TITLE
Add "copy to clipboard" quick action button in viewer

### ISSUE THREAD

**Issue by dist-a** [deckerst/aves#490]
Currently, the copy to clipboard feature can be found under **_Show menu > Export_** in the viewer. Considering that this is a fairly common action, I think we should give users the option to add it as a quick action button.

**Comment by deckerst** [comment]
I'm having second thoughts on this. Do you personally have that need, or are you simply thinking of the need of others?

I'm asking because I actually don't think this is a common need on mobile. I believe putting a picture in the clipboard is very rare, compared to sharing. Especially because apps traditionally do not provide the means to copy/paste images on mobile.

**Comment by dist-a** [comment]
Yes, I'd personally like to have the feature. But I also think it's a common need because the clipboard is used for inserting inline images (in emails, notes, documents, etc.) and sharing/posting images without exposing the filename and metadata.

It's true that traditional gallery apps on Android doesn't let you copy to the clipboard at all, but iOS has it built-in and the button is singled out and placed high up in the photos sharing menu and I suspect that's a deliberate user experience consideration.

<img src="https://user-images.githubusercontent.com/123013298/214981262-7e6ffc84-8c76-4caa-b68a-7694ad2f98c9.png" width="256" />

And speaking personally again, the ability to copy to clipboard is among the top 3 reasons why I chose Aves over every other Android gallery app. If anything we should mention this feature in the Play Store descriptions or even in the infographics because it's differentiating.

**Comment by deckerst** [comment]
Thanks for the follow-up. I value actual use cases like yours, rather than hypotheticals.

> sharing/posting images without exposing the filename and metadata

Please be aware that when the image is copied, metadata stays the same (unless the app in which you paste it does something).

**Comment by dist-a** [comment]
Oh I see! I always thought that the clipboard automatically strips the filename and metadata but on closer look it seems like everything is preserved. Many apps strip them on paste, so I got the illusion that they were not exposed. Perhaps stripping on copy is worth considering as a privacy enhancement feature later on, but I digress. Thanks for the heads up.
