### ISSUE TITLE
FC on ATV 11

### ISSUE THREAD

**Issue by chuk-75** [deckerst/aves#492]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by deckerst** [comment]
Thanks for following up.

1) the first time you installed and launched the app, did you reach the welcome screen? Or did it crash even before that?

2) if I provide a test build, would you be willing to try it on your TV?

**Comment by chuk-75** [comment]
> Thanks for following up.
> 
> 1. the first time you installed and launched the app, did you reach the welcome screen? Or did it crash even before that?
> 2. if I provide a test build, would you be willing to try it on your TV?

① Before
② Ok

**Comment by deckerst** [comment]
Here is a temporary build:
https://drive.google.com/file/d/1MIqCdn3JmKZw1qZmfaj5nTvnNpu2tWm0/view?usp=share_link

This build will install an app called `Aves [Profile]`, different from the regular `Aves`.
It will most likely crash like the regular one, but this builds enables Crashlytics reporting by default, so I hope to see a report with the crash details. For this to work, you should __launch the app a few times (not just once)__.

**Comment by chuk-75** [comment]
> 

Strange... This version ran fine. It lacks the zoom and delete functions. Is it supposed to be like this?

**Comment by deckerst** [comment]
Yes, editing features are removed for the TV. The UI is also modified and simplified in many places to accommodate navigation by D-pad.

About the FC, what was the file you used to install on your TV?

**Comment by chuk-75** [comment]
> Yes, editing features are removed for the TV. The UI is also modified and simplified in many places to accommodate navigation by D-pad.
> 
> About the FC, what was the file you used to install on your TV?

I extract the apk out of my smartphone and installed it on the TV. I couldn't find any other way to do it. Your app is not in the Play Market for Android TV. There is also no device selection for remote installation.

**Comment by deckerst** [comment]
The Play Store hasn't approved yet the app for Android TV (but I'm working on it...)

I understand now why it was crashing. The APK you extracted from your smartphone is not compatible with the architecture of your TV.

Until it's available on the Play Store, the best thing for you would be to take the APK from the [GitHub release](https://github.com/deckerst/aves/releases). You should pick the file named "app-play-release.apk".

**Comment by chuk-75** [comment]
> 

It is quite possible. I usually don't have problems with extracted apk's. Thanks for the tip. It's a very good app. I hope you will add the "Delete" feature. It's a must-have feature.
