### ISSUE TITLE
Location details

### ISSUE THREAD

**Issue by gg-gg1** [deckerst/aves#494]
**Describe the bug**
On previous 2 versions of the app the location details where accurate. Now it just shows the first 3 letters of the country. For example, for Belgium it shows BEL.
[aves-logs-20230120_171805.txt](https://github.com/deckerst/aves/files/10468643/aves-logs-20230120_171805.txt)

**Expected behavior**
I was expecting to see the location details like on previous versions, like the street name, number, city, etc...

**System information and logs:**
Package: deckers.thibault.aves
Aves version: 1.7.10-izzy
Aves build: 9002
Flutter version: 3.3.10
Flutter channel: stable
Android version: 13
Android API: 33
Android build: TQ1A.230105.001.A2
Device: Xiaomi POCO F1
Geocoder: Ready
Mobile services: ready
System locale: en_GB
Aves locale: system -> en
Installer: com.android.packageinstaller

**Comment by gg-gg1** [comment]
Hi. The app is just perfect, except for the location details. I love the addition of editin videos locations and to copy the location from one photo to another. 
Just this issue is missing to make it better, the location details.
Thanks.

**Comment by deckerst** [comment]
You get that kind of 3 letter country code when the app cannot get the full address from the geolocation service on the device. From the system info you pasted, it seems the geocoder is detected, but sometimes it fails temporarily. Could be related to network connectivity...

If you try again to open the app, do you see in the title bar "Locating..."?

**Comment by gg-gg1** [comment]
Yes, when I open the app I get the `Locating...` .

**Comment by deckerst** [comment]
1) Do you still have the issue?

2) If you open one of your photos taken in Belgium, and you go to the `Info` page, do you see an address below the map?

3) Are the regular Google Mobile Services installed on your device, or do you use an alternative like MicroG?

**Comment by gg-gg1** [comment]
Hi. Yes, the issue is gone. I use microG and I think the geocoder wasn`t working well. I have reinstalled microG and now it shows like before.
Thank you for your replies and help!
