### ISSUE TITLE
1- Keep empty folders pinned (hidden), 2- Showing images in album after tag searching, 3- Edit tag button '+', 4- quick action bar

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#495]
**Is your feature request related to a problem? Please describe.**
1- Use an app to make annotations to images . App then saves the image to its own folder. So far so good. Since we will want eventually to move the images from the apps folder to their album, it's usually useful to pin that folder the apps saves them to make it quicker access, since often different images will go to different albums. Less scrolling. After all images are moved from the apps image folder to their final destination, the apps folder is empty, so naturally Aves doesn't show it (that's OK). However, next time the app saves another image its folder, the same we just pinned, Aves forgets the fact it used to be pinned before it hid it.

2- When searching for a tag, there doesn't seem to be an easy way to be taken to the album and specific location where the image is.

3- "Edit tags" button symbol is misleading as it looks like an "add tag" button due to the '+' sign.

4- Several images (ones that fill the entire screen vertically) are shown partially behind the quick action overlay. Especially for text based images, this makes it so that we need to hide the overlay. However, when wanting to use said quick actions it's necessary to constantly tap the screen to hide/show the overlay.

**Describe the solution you'd like**

1- When hiding empty folders that were previously shown in Aves, as described above, memorize their pin status.

2- After searching for tags, might it be useful to have an option somewhere to show where the image is in its album? Similar to the "Show" functionality that Aves already has right after you move an image. Eg. Search tag >> Images with that tag are shown >> Long press on an image >> select "show in album" >> Aves then takes us to the place where the image is stored and highlights it. Since an image can only be in one album at a time, this should be possible?

3- Would it maybe be an option to replace '+' on the tag edition button with a gear, a wrench, or other some other commonly used symbol that give more the idea that it is to edit tags, not just to add (or just the tag symbol itself even)?

4- Similar to how the option to "use cutout area" works perhaps having an option to have quick action always displayed not as an overlay, but as a fixed area, ie. in a way it doesn't interfere with the image? (just like if we don't use cutout area, that top area is not used to show the image).

PS: I put all of these in one post so as not to spam the forum, but let me know if you prefer i separate them, i can do that

**Comment by deckerst** [comment]
Please open one issue per issue.
