### ISSUE TITLE
Viewer Setting "Image Background" Won't Change From Black

### ISSUE THREAD

**Issue by MWalton233** [deckerst/aves#496]
**Describe the bug**

Go to settings and expand viewer section changing image background to preferred color. Open picture and the background is still black. 

**To Reproduce**
1. Go to settings
2. Click on viewer and expand
3. Scroll down to image background and change color to preferred one
4. Open photo and background is still black. 

**Expected behavior**

Image background should be the color you changed it to. 

**Screenshots**

None

**System information and logs:**

None

**Additional context**

None

**Comment by deckerst** [comment]
Welcome to GitHub!

I believe you misinterpreted the "Image background" setting.

In the following image:
<img width="300" src="https://user-images.githubusercontent.com/13898333/213923051-bdbd6f52-0cdf-4be6-8b68-efbc71e29f40.png" />

(1) is the viewer background. It depends on the app theme (light/dark) and whether the overlay is displayed.
(2) is the image background. It is only meaningful for items with transparency (PNG, GIF, TIFF, etc. but not JPEG or MP4).

**Comment by MWalton233** [comment]
My bad for the misunderstanding. Hope I'm not a bother as it was an honest mistake. Thanks for the info and please keep up the hard work.

**Comment by deckerst** [comment]
No worries! Feel free to ask questions and report bugs, it's always useful.

**Comment by nullnullnullnull0** [comment]
> Welcome to GitHub!
> 
> I believe you misinterpreted the "Image background" setting.
> 
> In the following image: <img alt="" width="300" src="https://user-images.githubusercontent.com/13898333/213923051-bdbd6f52-0cdf-4be6-8b68-efbc71e29f40.png">
> 
> (1) is the viewer background. It depends on the app theme (light/dark) and whether the overlay is displayed. (2) is the image background. It is only meaningful for items with transparency (PNG, GIF, TIFF, etc. but not JPEG or MP4).

There should be a third background color setting. When hiding icons and picture information and only displaying the current picture, the background color is always black. The strong contrast between black and white is very unfriendly to users who use light themes.
