### ISSUE TITLE
Remember empty folders' pinned status

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#498]
**Is your feature request related to a problem? Please describe.**
Workflow: Use an app to make annotations to images. App then saves the image to its own folder. So far so good. Since we will want eventually to move the images from the apps folder to their respective album, it's usually useful to pin that apps folder to make it quicker access, since often different images will go to different albums. Less scrolling. When all images have been moved from the apps image folder to their final destination, the apps folder becomes empty, so naturally Aves doesn't show it (that's OK). However, next time the app saves another image in the apps folder, it shows up again (good) but Aves forgets the fact it used to be pinned before it hid it.

**Describe the solution you'd like**
When hiding empty folders that were previously shown, as described above, memorize their pin status.

**Comment by deckerst** [comment]
I implemented it that way on purpose, but I wasn't sure whether forgetting the pin was a good thing. Thanks for the use case explanation.
