### ISSUE TITLE
Can't scroll hidden filter list

### ISSUE THREAD

**Issue by yant0** [deckerst/aves#50]
i cannot scroll hidden filter list
device :
asus zenfone max pro m1
android 9 stock
orientation 0
aves version latest

**Comment by deckerst** [comment]
Thanks for the bug report. I fixed it, but it got me thinking... If you need to scroll, you probably have a *lot* of hidden filters. It may be tedious to set them up, so maybe a different feature would work better for your use case. Do you have a lot of folder filters? A lot of format filters?

**Comment by yant0** [comment]
well i do have pretty big collection of music, with each album having their own cover art. but yeah, in Aves it shows the folder individually and since they consume screen space i decide to hide them. manually.

i was thinking of select multiple albums and at the top right corner have three dots showing what you could do with them e.g hide/pin/group them

**Comment by deckerst** [comment]
You're right, multiple selection would be one solution. Actually it's [been asked before](https://github.com/deckerst/aves/issues/35) so I'll try and get it done.

Another solution, which might be more suitable for your case, is to have a way to include/exclude folders with their subfolders. So you could exclude the root of your music collection, and you wouldn't have to hide albums every time you have new music.

**Comment by deckerst** [comment]
@yant0 Settings import/export #51, multiple album selection #35, and the path hiding features are now all in the latest release. Did you get to try them? Did it help with your situation?
