### ISSUE TITLE
Make Tag Order in the Overlay and Details Section Consistent

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#502]
**Is your feature request related to a problem? Please describe.**
After enabling the tags for the Image Viewer Overlay, I noticed that they would be ordered in the sequence I selected them in the editor. But, when I swipe up to the Image Details section (or open the editor), the tags are automatically sorted in alphabetical order. Even closing and re-opening the app does not change the sorting order for the overlay

**Describe the solution you'd like**
I would like the order of the tags listed in the overlay to match that of the image details section and in the tag editor (post-edit).

**Describe alternatives you've considered**
The only reason I can think to keep it the way it is would be to be able to see the last changes made.
Two alternatives would be to have it re-sort only when going back to thumbnail view and then back into the image (swiping to the next or previous image could retain the order as a "just in case") or to have an option to change the general order between "last added" and "alphabetical" that would affect both overlay and details/editor equally.

**Additional context**
None.

**Comment by deckerst** [comment]
> After enabling the tags for the Image Viewer Overlay, I noticed that they would be ordered in the sequence I selected them in the editor.

That's a bug, they should be sorted in alphabetical order. Thanks for the heads-up!

**Comment by OkyDooky** [comment]
Oh, cool! Glad it was something relatively simple, then.
