### ISSUE TITLE
Add Option to Display Multiple Rows of Tags in Overlay

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#503]
**Is your feature request related to a problem? Please describe.**
Currently, the overlay only shows about 3~ tags maximum, depending on character count. Since I tend to have many images that contain more than that, I would like to have the option to show all the tags (that the screen can display).

**Describe the solution you'd like**
Since this will clutter the viewer even more, I figure this would make more sense as an option to toggle than any sort of default. Essentially, the default cutoff will remain, but this option would allow the number of tags to increase the area taken up by that part of the overlay.

**Describe alternatives you've considered**
None, at the moment.

**Additional context**
A technical concern I have is that tapping the overlay does not retract it; only tapping the image proper does that. If the number of tags is considerable, then it could make it difficult to hide the overlay, because of this. I'm not sure if there's an option or a general usability purpose that this default is here to support, so I don't want to recommend just changing it, unless it's fine to do so.

**Comment by OkyDooky** [comment]
On second thought, maybe I should change this request to apply to the other details, as well; either as separate individual options or as a universal switch.
Another option, probably better, would be to have it be purely an interactive toggle that is activated and deactivated by tapping on the overlay itself. Essentially, keep the normal defaults, but tap the overlay to expand it and tap it again to compact it. This setting should be remembered when swiping between images/videos and even when exiting to thumbnail view and going back in...or just the first half.
That should take care of the concern I had in the "Additional Context" section, as well.

Sorry and thanks for enduring my rambling.

**Comment by deckerst** [comment]
> an interactive toggle that is activated and deactivated by tapping on the overlay itself

That's what I had in mind. For now I'm thinking of expanding the title/description/tags, but not the location (because its layout is more complex). Remembering between horizontal swipes yes, but not when exiting the viewer.

**Comment by OkyDooky** [comment]
>That's what I had in mind.

Awesome!

>but not the location (because its layout is more complex)

Interesting. I guess I'm not familiar with how the location aspect works (since I don't really use geotagging), but that sounds fine to me.

>Remembering between horizontal swipes yes, but not when exiting the viewer.

That makes more sense. After my meanderings, I kinda got to that same point: "This setting should be remembered when swiping between images/videos and even when exiting to thumbnail view and going back in...or just the first half."

Thanks for actually reading through my ideas and considering them. I trust your implementation, since the last few major changes you added really did improve things for me much more than I expected.

**Comment by OkyDooky** [comment]
Damn. You closed them about as fast as I opened them. 😮
If only implementing feature requests was that easy for all projects. 😅
Thanks, again.
