### ISSUE TITLE
Remember the Expand/Collapse Setting for the "Recent" Tags Section

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#504]
**Is your feature request related to a problem? Please describe.**
When you recently made the change to the section with current tags, that made a world of difference for me and my workflow and almost completely solved my problem.

**Describe the solution you'd like**
I'd like the same done to the "Recent" section, since that would save time and a step.

**Describe alternatives you've considered**
None.

**Additional context**
This shouldn't really mess anything up or be a big change, I would think. If that's the case, I would love to see this added in the near future. Otherwise, I'll understand.

**Comment by deckerst** [comment]
Not a major change, but instead of remember the expansion of the `Recent` section specifically, it would remember which, if any, section is expanded (only one section is expanded at once between `Top Tags`, `Recent` and `Placeholders`).
