### ISSUE TITLE
gives an error when copying to the sd card

### ISSUE THREAD

**Issue by borivit** [deckerst/aves#506]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by borivit** [comment]
Package: deckers.thibault.aves
Aves version: 1.7.10-play
Aves build: 90
Flutter version: 3.3.10
Flutter channel: stable
Android version: 11
Android API: 30
Android build: RP1A.200720.011
Device: Xiaomi 2201117PG
Geocoder: ready
Mobile services: ready
System locales: ru_RU
Aves locale: system -> ru
Installer: com.android.vending 
[aves-logs-20230126_230225.txt](https://github.com/deckerst/aves/files/10513744/aves-logs-20230126_230225.txt)

**Comment by deckerst** [comment]
Thanks. The logs are weirdly empty :/

1) Can you write to your SD card with other apps? I'm asking because some SD cards are buggy and read-only.

2) Could you go to `Settings` > `Privacy` > `Storage Access` and take a screenshot?
Something like this:
<img width="250" src="https://user-images.githubusercontent.com/13898333/214962676-c49363f8-9bd8-48ee-b225-9d54a084116f.png" />

3) If you already have an image or video on your SD card, could you open it in the viewer, then go to its `Info` page and take a screenshot?
Something like this:
<img width="250" src="https://user-images.githubusercontent.com/13898333/214963352-6b28402f-76a2-4ee2-8f75-f36997efd700.png"/>

**Comment by borivit** [comment]
![Screenshot_2023-01-26-23-35-23-369-edit_deckers thibault aves](https://user-images.githubusercontent.com/59554169/214966578-2df5e350-c92b-4cf2-98d5-be29024e8589.jpg)

**Comment by borivit** [comment]
I'm starting to think it's Xiaomi's fault because no file manager can copy files to the SD card except the pre-installed one

**Comment by deckerst** [comment]
Thanks for checking. The format of the SD card volume ID (`FE38BD1638BCCF41`) looks weird to me. I'm expecting something like `1243-5678`. Maybe that's confusing non-Xiaomi apps.

Also, as I've mentioned before, maybe the SD card is not mounted properly, which prevents regular apps from writing to it.

I'll close this issue, as it seems to be unrelated to Aves, but feel free to comment if you have additional insights.

**Comment by borivit** [comment]
I don't know how, but this gallery manages to copy files from me. Maybe you can find out how they do it.
![Screenshot_2023-01-27-00-04-02-651-edit_com visky gallery](https://user-images.githubusercontent.com/59554169/214970804-b62975ac-df2f-4768-bfb6-721ce80bc2d5.jpg)

**Comment by deckerst** [comment]
Is that app open-source? Please share if you have a link to the app source.

Also, if you can please check my question 3. [here](https://github.com/deckerst/aves/issues/506#issuecomment-1405749323).

**Comment by borivit** [comment]
it looks like this gallery is not open source unfortunately
![Screenshot_2023-01-27-00-21-11-909_deckers thibault aves](https://user-images.githubusercontent.com/59554169/214973102-0f2d4fef-36cd-43f8-97f0-125feef634bf.jpg)

**Comment by deckerst** [comment]
The gallery app that works for you targets API 29 (Android 10), so it doesn't follow the requirements of the Play Store. Soon it will no longer be listed for download to new users.

Targeting older API allows that app to bypass the permission system of modern Android.

**Comment by borivit** [comment]
why do they complicate everything so much with these permissions that now because of this everything is not working well, what worked fine...

**Comment by deckerst** [comment]
I don't want to give up just yet.

If you're willing to help further, I'll prepare a test build for you to try. I don't know what's wrong, so it will be trial and error... Let me know and I'll work on it.

**Comment by borivit** [comment]
ok, let's try to solve this problem

**Comment by deckerst** [comment]
Nice, thanks.

In the meantime, could you try what the user described [here](https://github.com/deckerst/aves/issues/318#issuecomment-1236383621)?

**Comment by borivit** [comment]
I still don't understand where to go to do the same, Xiaomi is so confused

**Comment by deckerst** [comment]
The [App Manager app](https://github.com/MuntashirAkon/AppManager) which that user refers to is not a standard Android or Xiaomi app. It's an open-source app with advanced features and insights for app management. You can install it to try what worked for that user.

**Comment by borivit** [comment]
I wanted to install this appmanager, but I don't find it in googleplay, and the code that I understand needs to be compiled on GitHub, if possible, give a link to the compiled version or tell me where to look for it on GitHub

**Comment by deckerst** [comment]
You can install it with [this apk](https://github.com/MuntashirAkon/AppManager/releases/download/v3.0.4/AppManager_v3.0.4.apk). I found that one attached as an asset to the latest stable release in the [releases](https://github.com/MuntashirAkon/AppManager/releases) page.

**Comment by deckerst** [comment]
I've prepared a build with more detailed logs: [here it is](https://drive.google.com/file/d/1gGZjmRBWY6qP0ziZXh_Z1JNkrOEMExwV/view?usp=share_link).

This will install an app called "Aves [Profile]". It won't interfere with the settings and preferences in the regular app "Aves".

Please do the following:
1) install the APK, launch it and wait for it to analyze everything,
2) close and relaunch the app,
3) try to copy 1 image from your main storage to the SD card (give permission when needed),
4) go to `About` > `Bug Report` and save the logs,
5) attach the logs here.

**Comment by borivit** [comment]
I tried appmanager, but my tab is empty
![Screenshot_2023-01-27-23-01-36-571_io github muntashirakon AppManager](https://user-images.githubusercontent.com/59554169/215212817-f39cb2f9-c2dd-4580-b194-411bcd976c68.jpg)

**Comment by borivit** [comment]
did as you asked

Package: deckers.thibault.aves.profile
Aves version: 1.7.10-play
Aves build: 90
Flutter version: unknown
Flutter channel: unknown
Android version: 11
Android API: 30
Android build: RP1A.200720.011
Device: Xiaomi 2201117PG
Geocoder: ready
Mobile services: ready
System locales: ru_RU
Aves locale: system -> ru
Installer: com.google.android.packageinstaller
[aves-logs-20230127_230932.txt](https://github.com/deckerst/aves/files/10523479/aves-logs-20230127_230932.txt)

**Comment by borivit** [comment]
I don't have root access on my phone

**Comment by deckerst** [comment]
> I tried appmanager, but my tab is empty

Same for me. Sorry i didn't know that root was required. I just saw this solution from that other user.

Thanks for the logs! There's something interesting, but I can't take a closer look at the moment. I'll try to get back to you in a few days.

**Comment by deckerst** [comment]
[Here's another build](https://drive.google.com/file/d/1Ofi_TRhuT7NxjH465CX084nIp1H7hv-7/view?usp=share_link). It will replace "Aves [Profile]".

Please do the following:
1) install the APK, launch the app,
2) try to copy 1 image from your main storage to the SD card,

If it succeeds, please take a close look at the created file on your SD card. Can you open it? Does it have the same size as the original? Does it look ok?

If it still fails, please do the following:
3) go to `About` > `Bug Report` and save the logs,
4) attach the logs here.

Also, I have a question: with the normal Aves release, you said it fails when you copy a file to your SD card, but does it also fail when you edit (rotating, tagging, rating, etc.) a file already on your SD card?

**Comment by borivit** [comment]
I copied the file as you requested. The photo has opened and the dimensions have been preserved and the quality seems to have remained, but it will need to be viewed on a stationary computer. I also tried to make changes to the photo on the sd card on the original application and everything went well.

**Comment by deckerst** [comment]
Ok, good. Let me know if anything is weird. Otherwise, I'll consider the issue fixed.

Thanks again for all the help!

**Comment by borivit** [comment]
Okay, I'll play around with copying photos, I hope everything will be ok. Is it possible to make a few small changes in your gallery?

**Comment by borivit** [comment]
While everything is working well, tomorrow I will compare the quality of the copied photo and the original. If you had tweaked a few more things in design and management, it would be super :)

**Comment by deckerst** [comment]
> Is it possible to make a few small changes in your gallery?

What do you mean? If you have feature requests, you can open issues, but please [read this before](https://github.com/deckerst/aves/issues/234).
