### ISSUE TITLE
Autorotate viewer with device orientation

### ISSUE THREAD

**Issue by e-t-l** [deckerst/aves#507]
**Is your feature request related to a problem? Please describe.**
Having to manually rotate images in the Viewer with the rotate buttons even when the device is already in landscape mode (because many users do not have Android's system-wide Autorotate setting enabled by default) 

**Describe the solution you'd like**
An option in Settings > Viewer to autorotate (assuming system-wide autorotate isn't already enabled) 

**Describe alternatives you've considered**
- Manually rotating the image in viewer (the downside is that this rotation is permanently applied to the image) 
- Using a different gallery app (the downside is not being able to use and support this awesome project!) 

**Additional context**
Autorotating fullscreen images (and video) based on the device's orientation is a basic feature present in Google Photos and Simple Gallery, among many other gallery apps.

**Comment by e-t-l** [comment]
Simple Gallery is written in Kotlin, so I suggest checking out how they handle this: https://github.com/SimpleMobileTools/Simple-Gallery/search?q=ROTATE_BY_DEVICE_ROTATION (with particular attention to `ViewPagerActivity.kt` around line 466). It seems pretty straightforward.

**Comment by deckerst** [comment]
Thanks for the suggestion, but I disagree with the premise. If users want to autorotate, they should enable it at the OS level. It's so easy to toggle the existing OS setting, I don't think apps should add a redundant setting for it.

**Comment by e-t-l** [comment]
Oh. That's unfortunate. I think you might find that there's many users who don't want any of their apps to autorotate, _unless_ they're viewing a photo/video in full-screen. I would guess that's the reason all the major gallery apps have fullscreen autorotate as the default, or at least an option.

**Comment by deckerst** [comment]
Actually, maybe you missed something. You mention rotating the images themselves (which is bad and unnecessary indeed), but there's also a button to rotate the viewer when the app detects that the OS is in fixed orientation.

![Screenshot_20230127_205034_Aves](https://user-images.githubusercontent.com/13898333/215184397-386e7ad5-8b02-458d-b71c-26b619998b75.png)

Have you tried that?

**Comment by e-t-l** [comment]
Thanks for pointing that. I don't have that button pinned to quick actions, currently, because I don't find it works very well. (When activated, it only rotates to left/right landscape mode. Ideally, rotating with device orientation would include regular (upright) portrait mode, as well as inverted (180° upside-down) portrait mode.

The intention of this feature request was to have an option in settings that makes that sort of auto-rotation be active by default.
