### ISSUE TITLE
A few thoughts to improve the convenience and appearance

### ISSUE THREAD

**Issue by borivit** [deckerst/aves#508]
If you find my thoughts interesting, then I hope you will bring them to life :)
1. Make it possible to change the dimension of the sketch grid; 
2. Add the ability to change the shape and edges of landscape sketches; 
3. Add to the video player the ability to put the start button in the center of the screen, as well as start and stop the video with one click; 
4. When viewing the album, put the album name instead of the word "collection", quick the menu that appears when the photo is selected, put it in the place where the album name is now.
That's it for now:) then maybe I'll add more

**Comment by deckerst** [comment]
> Make it possible to change the dimension of the sketch grid;

Are you talking about the thumbnails in the Collection page? If so, you can pinch-to-zoom on thumbnails to change their size.

> Add the ability to change the shape and edges of landscape sketches;

I don't understand. Could you illustrate what you mean with a screenshot?

> start and stop the video with one click;

You can enable double-tap to play/pause in the `Settings` > `Video` > `Controls`.

> When viewing the album, put the album name instead of the word "collection",

I won't do that. It would be redundant with the album filter just below it.

**Comment by borivit** [comment]
"Are you talking about the thumbnails in the Collection page? If so, you can pinch-to-zoom on thumbnails to change their size." - unfortunately I have not found where this size changes
"I don't understand. Could you illustrate what you mean with a screenshot?"
![Screenshot_2023-01-29-09-18-50-634-edit_deckers thibault aves profile](https://user-images.githubusercontent.com/59554169/215314551-3e9cbcd7-6368-4ce7-8c53-9949fbdca672.jpg)
here is a preview of the album and it would be nice to be able to change its shape
"You can enable double-tap to play/pause in the Settings > Video > Controls." - that's exactly what a double tap is, but I would like a single tap
"I won't do that. It would be redundant with the album filter just below it."
![Screenshot_2023-01-29-09-17-12-026-edit_deckers thibault aves profile](https://user-images.githubusercontent.com/59554169/215314774-ade94007-435d-46cc-a174-44ed95b6e979.jpg)
![Screenshot_2023-01-29-09-18-00-089-edit_deckers thibault aves profile](https://user-images.githubusercontent.com/59554169/215314783-6a01cecb-3f03-4dd9-a3ca-ae23645789ba.jpg)
I think the screenshots show what I meant
in principle, I don't care, I suggested it, you didn't like it, close the topic.

**Comment by deckerst** [comment]
Resizing thumbnails: https://www.swisstransfer.com/d/26cb44cb-7b27-4191-a3cf-104f8b0dfaec

As for the UI, thanks for the suggestions but I will leave it as it is.
