### ISSUE TITLE
Bottom Navigation Bar not responding

### ISSUE THREAD

**Issue by HandHsince1920** [deckerst/aves#514]
After using the app for a while and sometimes running in the background for some time the bottom navigation bar, which I modified via the settings, does not respond anymore. Instead it opens the pictures behind the bar.
Restarting the app seems to help.

Package: deckers.thibault.aves.libre
Aves version: 1.7.10-libre
Aves build: 9002
Flutter version: 3.3.10
Flutter channel: stable
Android version: 12
Android API: 32
Android build: SQ3A.220705.004 dev-keys
Device: samsung SM-G973F
Geocoder: ready
Mobile services: not available
System locales: en_GB
Aves locale: system -> en
Installer: org.fdroid.fdroid.privileged

**Comment by deckerst** [comment]
> the bottom navigation bar, which I modified via the settings

The bottom navigation bar cannot be modified. The settings only allow to show or hide it. Could you explain further what you mean? Or maybe attach a screenshot to be sure we mean the same thing.

**Comment by deckerst** [comment]
By the way, next time you witness this behavior, please go to About > Bug Report, export the logs and attach them here.

Also, i don't think it's related, but do you use a custom ROM? a rooted device?

**Comment by HandHsince1920** [comment]
Sorry, took a while to get back. I checked the settings and you were right, the bottom bar was not modified

**Comment by HandHsince1920** [comment]
> By the way, next time you witness this behavior, please go to About > Bug Report, export the logs and attach them here.
> 
> Also, i don't think it's related, but do you use a custom ROM? a rooted device?

I use iodé, which is based on lineage

**Comment by deckerst** [comment]
This is a very strange bug, and for now I'll blame the custom rom ;p

I do not mean to dismiss your issue, but I'll need to see with time what kind of device/rom/environment has it. Basically waiting for other people to have the same issue.

And in the meantime if you have additional insights, feel free to comment here.
