### ISSUE TITLE
ToS says that Crashlytics is used, even in Aves Libre

### ISSUE THREAD

**Issue by gdt** [deckerst/aves#518]
**Describe the bug**
When starting Aves Libre, there is text that Crashlytics is used

**To Reproduce**
Install Aves Libre from F-Droid, start it, and see ToS screen.  Specifically the third paragraph of the privacy policy.

**Expected behavior**
There is no non-Free code present and nothing that says it is.

**Screenshots**
Leaving out because this is obviously intended for the Play build.

**System information and logs:**
(About is not accessible due to #517.)

**Additional context**
It seems the way to fix is to change the text for the Libre build flavor.

Also, and I won't bother you by opening a separate issue right now, the README should explain the difference between the build flavors.   I can't tell if it's just dropping Crashlytics, or if there is more.

**Comment by deckerst** [comment]
> When starting Aves Libre, there is text that Crashlytics is used

Incorrect. At the beginning of that paragraph it says `__Optionally__, __with your consent__, the app collects...`
In the libre flavour, this option is not displayed and you cannot give consent, so Crashlytics cannot be used.

Please don't spam this issue section with technicalities that are just a waste of time.
