### ISSUE TITLE
Ope app with password or(and) biometrics

### ISSUE THREAD

**Issue by LSD4K** [deckerst/aves#521]
Ability to block on a timer. Open by password or biometric.

**Comment by deckerst** [comment]
Duplicate of #114.

**Comment by LSD4K** [comment]
> Duplicate of #114
I got it. But I was referring to the open app itself, not the secret folders. In case someone takes the phone open.

**Comment by deckerst** [comment]
I see, then i think it's out of scope for Aves. The app shows media that's publicly available on your device. In the use case you describe, you'd need a lock on every single app that can access files.
