### ISSUE TITLE
Filter tags by no tags

### ISSUE THREAD

**Issue by csprr** [deckerst/aves#523]
**Is your feature request related to a problem? Please describe.**
I can properly assign tags and use them, however I'm missing an option to show all the files that have no tag.

**Describe the solution you'd like**
Have an option to filter by 'no tags'

**Describe alternatives you've considered**
Connect phone to my computer and use windows explorer to show everything in details view, there filter by 'tags' not having a tag, but having to use my PC for that is not always very viable.

**Comment by deckerst** [comment]
There's un "untagged" filter, you can find it on the search page. Also, you can check out Settings > Thumbnails > Overlay > Show location icon, and there are options to show "tagged" or "untagged" icons.
