### ISSUE TITLE
Batch processing of file conversion

### ISSUE THREAD

**Issue by HarriBuh** [deckerst/aves#526]
****Describe the solution you'd like****
Right now, it's quite uncomfortable to convert picture files into another format. You would have to select one picture at a time, open the context menu, select export, select convert a.s.o. If you select several pictures in the current build, you aren't able to convert them at all.
Since I'm using the converting option daily, this is much of a hassle.

****Describe alternatives you've considered****
One word: Batch. It would be much easier, faster and more comfortable to just select several files at once and run the conversion process once.

**Comment by deckerst** [comment]
Agreed.

Out of curiosity, what kind of conversion do you usually do? Do you convert to change the format, or reduce the size?

By the way, your linked item on Mega have expired. It could be easier to simply attach them to the GitHub thread.

**Comment by HarriBuh** [comment]
@deckerst I will re-uoload them if they were still of use for you then.

I always convert formats (my phone saves screenshots in PNG and I want them to become JPG to save space). I already resize them with the screenshot tool.

**Comment by deckerst** [comment]
> @deckerst I will re-uoload them if they were still of use for you then.

No need. I just wanted to let you know, in case you want to attach other images in the future.

> I always convert formats (my phone saves screenshots in PNG and I want them to become JPG to save space). I already resize them with the screenshot tool.

Thanks for the explanation. At the moment, metadata is not preserved when converting. I suspect that converting in bulk your screenshots would yield images that have all the same date, losing screenshot initial order. I'd like to improve this before I allow users to convert in bulk. Not for the imminent next release, but maybe the one after that.
