### ISSUE TITLE
More consistent processing of images

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#528]
**Is your feature request related to a problem? Please describe.**
When media is moved using another app, for example simple gallery pro, aves does not detect the change 

**Describe the solution you'd like**
I want Aves to react to file changes. From a user's perspective, if an image is in a folder it should be visible in Aves as well. 

**Describe alternatives you've considered**
.

**Additional context**
One way to test this is by creating a large folder with many pictures and also having a .nomedia file. Then remove the .nomedia file using a file explorer and take note of whether aves detects the newly available media. Note that manually triggering a rescan still does not detect the images, which it really should. It can only detect the images if I restart my device.

**Comment by deckerst** [comment]
Aves already reacts to media updates from the Media Store. The Media Store is the database of media maintained by the Android OS. In the old days, the Media Store wasn't always reactive, but with modern Android versions it's fine.

With large amounts of media files, the Media Store may take some time to index them. That's normal, nothing is instantaneous.

Another reason for discrepancy between file storage and Media Store state is misbehaving apps. These apps create or move media files around without registering/updating them correctly with the Media Store.

In any case, one principle of Aves is that it collaborates with the system media management. It's not trying to be clever by bypassing it and monitoring storage itself.
