### ISSUE TITLE
Feature Request: Add "Places" as Navigation Menu Item

### ISSUE THREAD

**Issue by Saijin-Naib** [deckerst/aves#533]
**Is your feature request related to a problem? Please describe.**
I don't often travel outside my Country anymore, but I do often travel between States and Minor Civil Divisions (Counties, Towns, etc). 

**Describe the solution you'd like**
I'd love to be able to put Places in the Navigation menu like Countries currently is so I can get an easy way to see how many locations I've been, and to jump into that navigation. 

**Describe alternatives you've considered**
Replacing Countries with Places, as it might make more sense that way rather than having both. 

**Additional context**
I've been to one Country with this phone since I last moved photos off, but like 30 Places. It just seems more widely useful a way to explore our library by location.

**Comment by deckerst** [comment]
Related:
- #70
