### ISSUE TITLE
Vault unlock prompt after the vault has been created doesn't work with KeePassDX Autofill

### ISSUE THREAD

**Issue by matchboxbananasynergy** [deckerst/aves#534]
**Describe the bug**

Vault unlock prompt doesn't work with KeePassDX Autofill, while the initial prompt to set the password does, which makes me think that the unlock screen after the vault has been generated isn't tagged in a way that's compatible?

**To Reproduce**
1. Create a Vault while using KeePassDX with Autofill turned on
2. Notice that when you're asked to set a password, it gives you the option through Autofill to create one
3. Once the vault is created, try to unlock it.

**Expected behavior**

The prompt should bring up KeePassDX's autofill, but it doesn't.

**Additional context**

Version 1.8.1, Android 13. This may be an issue with KeePassDX, but I'm assuming it's not based on it working when setting the password, but not afterwards.

**Comment by deckerst** [comment]
Strange, I personally use [Keepass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&gl=US) and when I tried it with Aves, it seemed to work fine.

Also, the dialog used to unlock is literally [the same as the one used to create the password](https://github.com/deckerst/aves/blob/cbf555a31f0f940df7a8893362456ffe4edeb020/lib/widgets/dialogs/filter_editors/password_dialog.dart), so the autofill hints are the same.

I don't know what could be the issue here. If any autofill enthusiasts have insights, I'm all ears.

**Comment by deckerst** [comment]
Just to be sure, we're talking about using the vault lock type "Password", right? Not using the lock type "System default" and your system protection is a password.

And do you use a custom rom or a rooted device?

**Comment by deckerst** [comment]
Glad it solved itself, that's my favourite kind of issue.

> P.S. Really like the vault feature. :)

Nice! I tried to make it fit seamlessly with the rest of the collection, but i already noticed some unhandled cases (like converting an item and saving it into a vault). Also, there may be limited storage space for vaults, but I'm not sure how it would manifest. Please let me know if you see *anything* suspicious with this new feature.

**Comment by deckerst** [comment]
I followed your instructions on my device, but with [Keepass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&gl=US), and it works fine:
https://user-images.githubusercontent.com/13898333/226591151-6651ddb3-e235-482a-b0c8-a485399f24ed.mp4

Is it possible that it's a bug with KeePassDX?

**Comment by deckerst** [comment]
I'm hesitant to call this a bug, as it could be a feature to disable AutoFill when the service thinks it's no longer appropriate. As it fails for a specific field, maybe the service disables itself on purpose for that field.

In any case, there's nearly no configuration for AutoFill on Aves side so I'll close this issue, but feel free to comment if you have additional insight.
