### ISSUE TITLE
Obsolete storage volume / Recycle Bin Bug

### ISSUE THREAD

**Issue by mitchwalton** [deckerst/aves#536]
**Describe the bug**

Moving items to recycle bin and clearing recycle bin doesn't remove items from storage.

**To Reproduce**

1. Go to picture and move to recycle bin
2. Go to recycle bin and clear it
3. Reopen app and photos appear in collection

**Expected behavior**

Clearing recycle bin should remove contents from storage.

**Screenshots**

![Screenshot_20230223-162823_Aves](https://user-images.githubusercontent.com/123303123/221034559-04ff7c25-14e9-4fdc-bd14-02548dbb8ee7.png)

**System information and logs:**

[aves-logs-20230223_160318.txt](https://github.com/deckerst/aves/files/10818487/aves-logs-20230223_160318.txt)

Package: deckers.thibault.aves
Aves version: 1.8.1-izzy
Aves build: 9202
Flutter version: 3.7.3
Flutter channel: stable
Android version: 11
Android API: 30
Android build: lineage_beyond2lte-userdebug 11 RQ3A.211001.001 eng.root.20220401.202916 dev-keys
Device: samsung SM-G975F
Geocoder: not available
Mobile services: not available
System locales: en_US
Aves locale: system -> en
Installer: com.android.packageinstaller

**Additional context**

Only happening on local storage.

**Comment by deckerst** [comment]
Please fill in the sections.

**Comment by mitchwalton** [comment]
I thought the other three sections set to none were optional. Which ones do you have to have?

**Comment by deckerst** [comment]
`System information and logs:` is often useful.

**Comment by mitchwalton** [comment]
Its seems to be specific to my Custom ROM. I can post system info and logs but it won't contain any private info correct? Reading them obviously goes above my head and I dont want to post info that's to revealing.

**Comment by deckerst** [comment]
The system info as output from About > Bug Report has nothing personal.
The logs may contain the path to one of your files (like the one getting deleted).

But more importantly, if you're using a custom rom, please note that things often go awry because of the rom tweaks. As I can't test on these roms, it's unlikely that I'll address the issue if I can't reproduce it on stock android.

**Comment by mitchwalton** [comment]
Thanks for the info. I'll be posting I'm just careful with my privacy after what some app developers collect or especially big tech companies. One of the reasons I love your app is for it's stability, privacy, and overall beauty.

**Comment by deckerst** [comment]
You can also send me the logs by email if you want to be extra careful.

**Comment by mitchwalton** [comment]
I just posted. Thanks again!

**Comment by deckerst** [comment]
Just from a quick look at the logs, there are some weird things related to storage.

Do you have an SD card? If not at the moment, did you have in the past and used Aves to manage files on it?
Is the SD card fully functional, in the sense that other apps can write to it without issue?

Also, could you please attach a screenshot of what you have in `Settings` > `Privacy` > `Storage access`? (Again, if you think paths on that screenshot are too personal, you can email that to me instead.)

**Comment by mitchwalton** [comment]
I just changed phones over Lineage OS and other Custom ROMs not supporting volte on Samsung phones. I'll be buying a pixel soon with Lineage OS for volte support and am currently running a googled phone unfortunately. This phone really isn't used anymore but I came across this bug and wanted to help you out. I did have an SD card full of photos but it's no longer in the phone running Lineage OS. I had no problems with the SD card when I ran it in the phone with removing, adding, or changing content from other apps. I'll post the screenshot for you.

**Comment by mitchwalton** [comment]
Clearing app storage fixed it. It's running smoothly now.

**Comment by deckerst** [comment]
Glad it works for you now. I'll try and take a closer look at your logs later, and handle better obsolete SD cards. It seems Aves is confused by the missing card.

**Comment by mitchwalton** [comment]
Thanks and glad to hear you'll dive depper into this problem. Your an amazing app developer and very stable. One of the biggest problem I had when switching to a degoogled phone and open source apps was bugs. After running the phone for a while I developed my privacy focused app collection that feels like running a common phone without lacking many features.

**Comment by deckerst** [comment]
Related: #557
