### ISSUE TITLE
Slide up/down final part of animation takes a bit too long and not visible

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#539]
**Describe the bug**
Final part of sliding up/down animation taking a bit too long to complete. The final stage of the animation (deceleration of image) is barely visible, but since it hasn't finished yet, it's not yet possible to slide sideways. This makes it a bit awkward to wait for some time without almost no visible indication about when we finally can slide sideways.

**To Reproduce**
1. Go to an image by tapping on it
2. Slide upwards to show metadata info, tags, etc.
3. Slide down to go back to image
4. Slide sideways to go to another image

**Expected behavior**
Last part of animation finish sooner, so slide down and sideways can be done quicker one after the other and it is easier to visually identify when it's possible to slide sideways.

**Comment by deckerst** [comment]
I changed the physics to make that animation a bit faster (and more consistent when using buttons v. gestures), but you may still feel a delay between the end of the animation and the handling of new gestures:
- #553

**Comment by deckerst** [comment]
Seems we can never please everybody. Just got a review on the Play Store:
> Bring back slow animations plz 😭 Opening and closing transition also swiping up to see details is now too fast not relaxed as before

**Comment by NDR-113** [comment]
I just thought of another solution which may be better, and actually fits with the way Aves already works. Which is to allow sliding sideways even while the animation is still running. This is already the case when we slide sideways and then up. Here it's possible to slide up even before the sideways animation hasn't finished. So the same could perhaps be done for sliding up and then sideways?

**Comment by deckerst** [comment]
I see what you mean, but this is not how it works. The scrolling UI components are one into the other, so one axis is dominant. That's why you can vertically scroll without waiting for horizontal scroll to finish, but that's mutually exclusive with the reverse.
