### ISSUE TITLE
Weird behavior on long vertical images and swiping up/down

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#540]
**Describe the bug**
When viewing a tall vertical image, and zoomed in, trying to swipe up and down to scroll often results in closing the image. It seems to depend on how fast the swiping movement is, how much zoom is applied, and whether the finger is lifted after swiping.

**To Reproduce**
1. Open tall vertical image.
2. Zoom in in some area in the middle, eg. by double tapping.
3. Swipe up/down in order to do a rolling scroll, ie. after swiping, lift finger so the image keeps moving, decelerating until stopping. (If you zoom after a certain point, the behavior of Aves changes and it doesn't exit the image anymore, behaving as expected)
4. Aves understand this swipe action as a closing swipe movement and closes image.

**Expected behavior**
Swiping up/down in a long tall image while zoomed in does not close image.

**Comment by deckerst** [comment]
In Aves v1.8.0, I "improved" gesture handling for this issue:
- #316

But it messed up other aspects, like the one you've described. Other issues are:
- scaling out often closes the item,
- flinging through images sometimes go backwards.

I've just fixed this and intend to release a new version soon.
