### ISSUE TITLE
Pattern for vault

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#543]
Thanks for adding vault.
Can I use the pattern instead of pin and password?

![IMG_20230301_024137_457.jpg](https://user-images.githubusercontent.com/23485114/222003748-ef6ac0a1-7248-4d1f-92df-73f8026eaddc.jpg)

**Comment by deckerst** [comment]
Not as a separate lock type option, at the moment. But if your current device unlock method is via pattern, you could select the "system default" lock type.

**Comment by xmha97** [comment]
Yes, but I want to use another pattern.
But if you think it is hard to implement the pattern, close this issue.

**Comment by xmha97** [comment]
Thanks 🙏
