### ISSUE TITLE
Tap filename to search

### ISSUE THREAD

**Issue by JimW1at** [deckerst/aves#545]
First of all Thanks for your work on the app, it's awesome!!

So, i was wondering is there a way to have filenames as appear tags....

What i mean is i have hundreds of photos of birds and it is a lot of work to tag all of them in the tag editor :) but the filenames in these pictures have the names of the birds, So could there be a way to tap on the filename and intiate a search query in the app with that bird's name.... just like how we tap a tag and all photos with that tag appear.

Example:

Grey_Buzzard.jpg
Grey_Owl.jpg

If i tap the word "Buzzard" in the title when viewing the image, all pictures with the filename buzzard should appear on the search page similarly if i tap "Grey" then all photos with filename Grey should appear. This could make searching a large gallery a bit easier.

Thanks for reading anyway, i hope i was clear enough.

**Comment by deckerst** [comment]
I'll think about this, but in the meantime, maybe you can leverage the title filter. I'd recommend making it a quick action in the Collection page, via Settings > Thumbnails > Quick actions, and add "Show title filter".

Also, when you simply search for a term, it will find it in titles. And this search can handle some extras, like doing "-warbler" to hide all the items with "warbler" in their names.

**Comment by JimW1at** [comment]
> I'll think about this, but in the meantime, maybe you can leverage the title filter. I'd recommend making it a quick action in the Collection page, via Settings > Thumbnails > Quick actions, and add "Show title filter".
> 
> Also, when you simply search for a term, it will find it in titles. And this search can handle some extras, like doing "-warbler" to hide all the items with "warbler" in their names.

Yes, i already use this feature and Aves search is very powerful, its shows the desired results without needing to tag the images individually. If only there was a way tap the title and search in the app, it would
make it more intuitive, right now i copy the title from the description page and then search in the title filter,
its a bit cumbersome.

But thanks for replying i will wait for the solution.

**Comment by deckerst** [comment]
Actually, I won't do this, for various reasons. There's already some logic to handle taps on the overlay text (to expand/collapse long filename/description). Also, navigating when tapping on text would be surprising, so a confirmation/explanation dialog would be required, and it would break the design language used throughout the app to indicate filters. Last but not least, defining what a word is in the title is not trivial: even assuming we're dealing with English where words are separated by spaces, users don't always use spaces (like in your example, with underscores).

Navigation through text is out. I believe the proper solution would be a way to tag in bulk your media from the filenames. Using a custom pattern, you could define which words to extract and how to split them. It's very niche and geeky, I won't do it in the short term, and see whether there's demand for that kind of solution.
