### ISSUE TITLE
Save Scroll Position

### ISSUE THREAD

**Issue by JimW1at** [deckerst/aves#550]
When i scroll down in the collections tab and open a picture, and then tap a tag or folder in the info page, it opens the the tag or folder as expected but when i press the back button it closes the app instead of taking me back to the original scroll position in the collections tab and i have to open the app again and scroll to that picture again...

Can this behaviour be changed?

**Comment by deckerst** [comment]
I don't intend to change the way navigation works. I tried before something similar to what you suggest (see below) and i wasn't convinced.

Related:
- #82 

Here's some explanation i gave before about Aves navigation (it was about home and the drawer, but it's still relevant to your request):

> I don't have a bulletproof answer, because page history management is not obvious for an app that allows lots of navigation and customization. But here's my rationale.
> 
> First off, the home is customizable. The default is the Collection page, but some prefer the Albums page, and in the future I might allow a specific sub collection (e.g, starting with your favourite family pictures). With that in mind, what would happen when pressing back from the Countries page. Would it go to the Albums page, or the specific sub collection? It may be unintuitive.
> 
> Also, a tricky thing is to determine what to do when the user is pressing back on their home page. Let's say you were on the Albums page, tap on an album and it goes to the Collection page. Should pressing back leave (because Collection is your home), or go back to Albums page?
> 
> In earlier releases, I experimented with a different style of history management, keeping *all* the history, never resetting it. That way you were always leaving by the page you started, the home. But the app allows so many ways to navigate that it was quickly becoming disorienting to go back after a few page jumps.
> 
> Now the approach is that the navigation drawer lets you go to a top level page (Collection, Albums, Countries, Tags) and this resets page history. So it becomes more predictable whether pressing back leaves or navigates.

**Comment by deckerst** [comment]
One thing I will do though, is to scroll to the item you were looking at in the Info page when you tapped on that tag (or other filter). So that it will be easy to reopen the item from there.
