### ISSUE TITLE
gestures are often missed/ignored/misinterpreted

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#553]
**Describe the bug**
when swiping through the images in the viewer, gestures aren't consistently recognised. for example if I swipe left or right to the next image and then swipe up to see the info, I often need to repeat the gesture multiple times before it is recognised. in general fast gestures are not handled optimally.

**System information and logs:**
Package: deckers.thibault.aves
Aves version: 1.8.3-play
Aves build: 94
Flutter version: 3.7.7
Flutter channel: stable
Android version: 9
Android API: 28
Android build: PPR1.180610.011.N950FXXUGDVG5
Device: samsung SM-N950F
Geocoder: ready
Mobile services: ready
System locales: en_AT, de_AT
Aves locale: en -> en
Installer: com.android.vending
Error reporting: true

[aves-logs-20230314_104751.txt](https://github.com/deckerst/aves/files/10966859/aves-logs-20230314_104751.txt)

**Comment by deckerst** [comment]
I've just fixed some gesture mismanagement which should help in your case.

That said, the different scrollables are nested in such a way that if the vertical axis is animating (to go from the `Info` page to the `Viewer`), it won't accept horizontal swipes (to go to the previous/next item) until it's static. To help with this particular use case, I've made the switch between `Info` / `Viewer` a bit snappier:
- #539
