### ISSUE TITLE
Aves cannot open images from other apps on android 13

### ISSUE THREAD

**Issue by lyaaz** [deckerst/aves#556]
**Describe the bug**
Aves cannot open photo from other apps.

**To Reproduce**
1. Go to Telegram.
2. Click on an image file.
3. Select Aves to open image.
4. Aves is opened, but viewer doesn't show.

**Expected behavior**
Aves open images correctly.

**System information and logs:**
```
Package: deckers.thibault.aves
Aves version: 1.8.3-izzy
Aves build: 9402
Flutter version: 3.7.7
Flutter channel: stable
Android version: 13
Android API: 33
Android build: TQ1A.230205.002 dev-keys
Device: Xiaomi MI 9
Geocoder: ready
Mobile services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.android.packageinstaller
Error reporting: false
```

[aves-logs-20230316_090520.txt](https://github.com/deckerst/aves/files/10985827/aves-logs-20230316_090520.txt)

**Additional context**

It works on Android 12 as expected.

<details>
<summary>
Intent captured by <a href="https://github.com/MuntashirAkon/AppManager">App Manager</a> Inspector:
</summary>

```
URI	intent://org.telegram.messenger.web.provider/media/Android/data/org.telegram.messenger.web/files/Telegram/Telegram%20Files/XP%604Y5%5B~%60)GLR%24%7DNN%5D%25AB%5DC.jpg#Intent;scheme=content;type=image/jpeg;launchFlags=0x3000001;end

VERSION	1
ACTION	android.intent.action.VIEW
DATA	content://org.telegram.messenger.web.provider/media/Android/data/org.telegram.messenger.web/files/Telegram/Telegram%20Files/XP%604Y5%5B~%60)GLR%24%7DNN%5D%25AB%5DC.jpg
TYPE	image/jpeg
FLAGS	0x3000001

MATCHING ACTIVITIES	4
0	LABEL  	Image Viewer
 	NAME   	com.mixplorer.activities.ImageViewerActivity
 	PACKAGE	com.mixplorer
1	LABEL  	Aves
 	NAME   	deckers.thibault.aves.MainActivity
 	PACKAGE	deckers.thibault.aves
2	LABEL  	Aves Libre
 	NAME   	deckers.thibault.aves.MainActivity
 	PACKAGE	deckers.thibault.aves.libre
3	LABEL  	Interceptor
 	NAME   	io.github.muntashirakon.AppManager.intercept.ActivityInterceptor
 	PACKAGE	io.github.muntashirakon.AppManager

ACTIVITY RESULT	0
```

</details>

Screen record:

https://user-images.githubusercontent.com/45838887/225485998-0affd035-7102-4d77-a6e5-0fd708f06832.mp4

ps: I hided all the image paths in the video above.

**Comment by deckerst** [comment]
Thanks for the detailed report!

Just checking from the logs, it seems that the sharing app doesn't give the permission to read the content. I'll take a closer look when i can, but in the meantime could you verify that you can open the image shared to another 3rd party gallery app? (targeting at least API33, and not a Xiaomi system app)

**Comment by deckerst** [comment]
Also, when i share with my Telegram app, i get a uri like:
`content://org.telegram.messenger.provider/media/...`

But yours is:
`content://org.telegram.messenger.web.provider/media/...`

Could you give me a link to the Telegram app you use?

**Comment by lyaaz** [comment]
Tested with Mixplorer v6.61.6 (target API 33), works fine when open from Telegram.

> Could you give me a link to the Telegram app you use?

It's downloaded from the website, https://telegram.org/dl/android/apk

**Comment by deckerst** [comment]
I've tried with Telegram from the Play Store (`org.telegram.messenger`) and Telegram from the website (`org.telegram.messenger.web`), both installed on a Pixel 4 emulator with Android 13. With either, a media opened with Aves works fine.

One thing I've noticed though, is that the UX I get in Telegram is not the same as yours:
- With yours, tapping an image (attached as a file) allows you to open it with another app.
- With mine, tapping on an image (attached as an image, or attached as a file), directly opens it in the Telegram viewer, and I can't open it outside. I could only open media with another app for attached videos. [Here's a demo on my S10e](https://www.swisstransfer.com/d/dab30bc9-df43-4306-aa91-bbcf3249fdb4).
Do you know why your telegram does not behave the same?

Do you get the issue randomly, or get it all the time?
Also, do you also get the issue when you open a media with simple ascii in the name, like "foobar.jpg"?

**Comment by lyaaz** [comment]
> Do you know why your telegram does not behave the same?

You need a picture with high enough resolution, such as a scrolling screenshot, and "send without compression"/"send as file".

Here an example: 
[f057b9b7-21b3-4935-90e5-8cd77526f4b7.png](https://user-images.githubusercontent.com/45838887/225662270-4205790e-8603-4aaa-a982-b1d3d63f3435.png)




> Do you get the issue randomly, or get it all the time?

All the time since days ago upgrade my system to android 13.

> Also, do you also get the issue when you open a media with simple ascii in the name, like "foobar.jpg"?

yes.

**Comment by deckerst** [comment]
Thanks for following up. I'll try again.

Do you use a custom rom? or maybe enable some kind of "security" feature specific to xiaomi?

Sorry to bother you with all these questions, but it's tricky for me to address issues when I can't reproduce them.

**Comment by lyaaz** [comment]
I use iodeOS, a lineageOS based rom.

> or maybe enable some kind of "security" feature specific to xiaomi?

no.

> Sorry to bother you with all these questions, but it's tricky for me to address issues when I can't reproduce them.

Never mind, I really appreciate your hard work.
If this still cannot be reproduced, there may be other reasons.  I'll probably do a factory reset tomorrow to confirm.

**Comment by lyaaz** [comment]
Just reset my phone, now everything works as expected! I'm not sure but the reason may be dirty data from system upgrade.
Sorry for wasting your time!
