### ISSUE TITLE
Cannot Delete/Edit Tags after changing SD Card

### ISSUE THREAD

**Issue by jpkanter** [deckerst/aves#557]
Samsung S20 FE 5G (it got an SD Card Slot)
```
Package: deckers.thibault.aves
Aves version: 1.8.3-play
Aves build: 94
Flutter version: 3.7.7
Flutter channel: stable
Android version: 13
Android API: 33
Android build: TP1A.220624.014.G781BXXU4HWB1
Device: samsung SM-G781B
Geocoder: ready
Mobile services: ready
System locales: sv_SE, en_GB
Aves locale: system -> en
Installer: com.android.vending
Error reporting: false
```

Changed SD Card from 256 to 512 GByte update, powered Phone down, Copied old to new Card, placed new Card into the phone and booted up.

It turns out, internally SD Card have an unique(?) ID. Had to re-add albums but everything seems to work fine so far on the display side of things. But i cannot delete pictures or add tags (or any other file manipulation). When i delete it will act as if had done so but when closing and opening Aves the picture will be present again. When editing tags it will display a "failed", similar to https://github.com/deckerst/aves/issues/318
I investigated my storage access settings:

![signal-2023-03-17-135725_002](https://user-images.githubusercontent.com/64833010/225912610-8857f5cf-ed92-424f-9cb6-71049eeeb2e7.jpeg)

In my file manager (MiX) the current SD cards ID is the same as in the permission, although i cannot remember having given those.

![signal-2023-03-17-135719_002](https://user-images.githubusercontent.com/64833010/225912786-014c27a2-6a72-4211-b12b-b1ad98c4a96a.jpeg)

Problem: Aves never prompts me for new permission nor seem I to see a path to make it manually requesting access to the new sd card as it still thinks it can access everything just fine (maybe due some lingering overall access permission?)

I could probably just hard reset the app but then i had to redo all the albums and hide things again (there is a lot of non-picture images on a 512 gbyte sd card) so I would appreciate a softer solution.

**Comment by deckerst** [comment]
Thanks for the report. I'll investigate the bug itself when i can, but first let's try to solve your situation. If you remove the current accesses you have in `Storage Access`, and then retry to edit/delete your items on the SD card, does it prompt you for access and then do it right?

**Comment by deckerst** [comment]
> then i had to redo all the albums and hide things again

Do you know you can export/import settings (including what's hidden), custom covers and favorites? It's in the top right menu in the Settings page.

**Comment by jpkanter** [comment]
Okay i was able to work around:

I could actually not delete the rights to individual folders in the privacy settings, tapping the *revoke* button did nothing (might be a bug in itself but if noone else has it i have no clue how to trigger that). So i was about to go the settings ex/import route you suggested. When fumbling around in the app settings i deleted the right to external sd cards all together. Back in Aves i tried to edit a tag once more and *now* it asked me to grant permissions, i did ad it worked.

I am deeply sorry that i cannot provide further info how i actually got in this messy half state in the first place, but my best bet would still be some SD card related ID nonsense but my knowledge of android13 right management is spotty at its best.

*fun fact, according to android Aves uses 14 gbyte of space, is that all thumbnails?*

**Comment by deckerst** [comment]
Don't be sorry, you actually provided very useful things for me to try and debug. I'm glad things worked out for you but i will keep this issue open until i figure things out.

> fun fact, according to android Aves uses 14 gbyte of space, is that all thumbnails?

Haha, that's possible:
- #206 

In the meantime, you can safely "clear cache" (*not* "clear data") in the app android settings.

**Comment by deckerst** [comment]
Fixed the permission issue when changing SD card. Thanks again for reporting the issue!
