### ISSUE TITLE
Slideshow interval setting wheel bug

### ISSUE THREAD

**Issue by TramW** [deckerst/aves#559]
When using the wheels to set the slide time, 1 to 9 is fine, 10 to 19 only show 1, 20 to 29 only show 2  etc.
This is also the same for the minutes wheel. #
![2023_03_19_21 11 40](https://user-images.githubusercontent.com/128290360/226169255-e7f2b7ce-8300-4526-8290-eafe8a640f9d.jpg)
![2023_03_19_21 11 19](https://user-images.githubusercontent.com/128290360/226169291-ee343f4d-3c1a-4dc9-8b51-cc3dbf33b7f5.jpg)
[aves-logs-20230319_211311.txt](https://github.com/deckerst/aves/files/11010698/aves-logs-20230319_211311.txt)

**Comment by TramW** [comment]
Package: deckers.thibault.aves
Aves version: 1.8.4-play
Aves build: 95
Flutter version: 3.7.7
Flutter channel: stable
Android version: 12
Android API: 31
Android build: SP1A.210812.016.M315FXXU3CWA2
Device: samsung SM-M315F
Geocoder: ready
Mobile services: ready
System locales: en_GB
Aves locale: en -> en
Installer: com.android.vending
Error reporting: true

**Comment by deckerst** [comment]
Would you be willing to try a test build?

**Comment by TramW** [comment]
Yes, no worries.  I'm assuming that if  needs be I can reinstall the
current version

**Comment by TramW** [comment]
Hi Thibault,
  Yes, all OK, thanks for that, screen shot attached.
Regards
Geoff W

**Comment by deckerst** [comment]
It seems you can't attach screenshots when you reply to a GitHub issue by email.

Anyway, if you say it's ok now, i trust you and I'll close this issue!

**Comment by TramW** [comment]
I'll send you the screen shot to your email
