### ISSUE TITLE
Video player lock/ unlock button 🔒 on screen 

### ISSUE THREAD

**Issue by Dmarcil** [deckerst/aves#560]
Request a Lock button included on the video player interface, because all the time you find out you touched the screen without knowing and it changes the screen resolution to all available layout sizes in quick successions when in horizontal mode mostly ruining the whole wonderful experience

Touching the screen unintentionally also brings up / pops up the current video info at the top again ruining the horizontal full screen watch mode experience. 
The info cannot go away unless you tap on the video... Doing so may again zoom in or zoom out the resolution which is frustrating

A lock button 🔒 to lock video player in vertical/horizontal mode may solve

**Comment by deckerst** [comment]
Welcome to GitHub!

As I understand it, the lock could prevent:
1. tap to show the overlay (details at the top, quick actions and thumbnails at the bottom)
2. side tap to show the next/previous item
3. double tap (to toggle play, skip/rewind)
4. vertical drag (to show the `Info` page, leave the viewer, or adjust volume/brightness)
6. zooming
7. rotating

I'll probably provide a lock action (that you can add as a quick action) that will tackle 1~6, but I'm undecided about 7. The way I see it, if the player is locked and you interact with the screen, it only shows an unlock button and nothing else. This unlock button overlay will automatically hide away after a few seconds.
