### ISSUE TITLE
Show the description photo when viewing it

### ISSUE THREAD

**Issue by lixuuu** [deckerst/aves#561]
**Edit the title and the description**
The application allows you to edit a comment and a title on a photo. Useful for a memory reminder on photos. Unfortunately when you view the photos, only the title is displayed. The description of the photo is not displayed.

**Describe the solution you'd like**
Show the description photo when viewing it (as the title)

**Comment by deckerst** [comment]
It's already possible, via `Settings` > `Viewer` > `Overlay` > `Show description`.

And if the description is long, it's truncated by default, but you can tap on the overlay to show the whole text.
