### ISSUE TITLE
Support burst groups from Sony

### ISSUE THREAD

**Issue by sjordet** [deckerst/aves#562]
**Is your feature request related to a problem? Please describe.**
I'm aware that you support Samsung burst groups from issue #6 , but Sony apparently uses a different naming scheme.

**Describe the solution you'd like**
To have burst groups have a single thumbnail, and even better if I can select coverimage and have an option to delete all bursts but one. (Google Photos do this neatly.

**Describe alternatives you've considered**
Don't know...

**Additional context**
The format for Sony is: "BURST/DSC_20230321152231242/DSC_0000_BURST20230321152231242.JPG" for a burst taken just now, with the "0000" increasing for each burst and one of them having "_COVER.JPG" at the end...

Can send you a couple of bursts privately if needed.

Great project! Very happy to find it!

**Comment by deckerst** [comment]
> Can send you a couple of bursts privately if needed.

Yes, please. You can use that [that email](mailto:gallery.aves@gmail.com).

**Comment by deckerst** [comment]
Could you please paste here the system info you get from `About` > `Bug Report` in step 2?

About the feature itself, supporting the burst pattern for Sony is ok, but I probably won't work on extra features (like cover selection) in the short term.

**Comment by deckerst** [comment]
Checking for multiple patterns could become costly, especially if I add more patterns for more manufacturers in the future, so I've decided to let users choose which patterns they want to use to group bursts.

By default, it will activate the Samsung pattern for Samsung devices, and same deal for Sony. But for people who *already* use Aves, you'll need to go to the settings and activate what you need.

<img width=250 src="https://user-images.githubusercontent.com/13898333/226940130-08d6f646-9535-44a5-a50e-dbb5759fbd10.png"/>

**Comment by sjordet** [comment]
I'm not sure if I should answer to this issue or create a new one - but here goes!

I'm very happy with your extremely fast turnaround in implementing this, and I've been eagerly awaiting a new release for the past month. So I was very happy last night when it was finally released. But there are still some nitpicks - please tell me if I should file seperate issues for these - I just want to hear your take on it first.

1: This is the "easiest" one; if you open a burst, and you delete one of the pictures in the burst - it's still there. The number of images in the burst show the same count, and you can go back and forth between them as before. If I go back to the thumbnail view and then open it again - the deleted image is gone. Seems a refresh of some kind is missing after a delete

2: This is entirely my fault. When I gave you the Sony burst-format, I was not aware there were two different - earlier they had something they called "Predictive Capture" (I don't think it's on recent phones?), which might take a image before you actually pressed the trigger. Or one after you pressed the trigger. They look like "normal" bursts, except that the filenames are "DSCPDC_0000_BURST20180224164317669.JPG" - notice the 'PDC' there. 

Would it be possible to add this as well? The folder-structure is "PREDICTIVE_CAPTURE/DSC_20180224164317669/DSCPDC_0000_BURST20180224164317669.JPG"

3: Since Bursts (of both types) are creating a folder for each burst, I get many-many "Albums" - which I don't really want. Would it be possible to hide bursts as separate albums, if that makes any sense?

Other than that - really, really love your app! Really featureful - still very sleek and fast! Love it!


Regards,
Stian

**Comment by deckerst** [comment]
Thanks for the feedback. Glad you enjoy the app.

Please open an issue for each. It's easier to manage, especially when it's a mix of bugs and feature requests.
