### ISSUE TITLE
When selecting photos in grid view, can you move the top toolbar (with delete and share options) to the bottom for better reachability?

### ISSUE THREAD

**Issue by matdam99** [deckerst/aves#563]
**Is your feature request related to a problem? Please describe.**
When I mass select images too either delete or tag collectively, the delete option is presented at the top of the screen, which is inconvenient to get to each time with my thumbs. 

**Describe the solution you'd like**
I would like the top toolbar with the delete option to be present at the bottom of the screen for better reachability. This could be implemented as a separate toolbar entirely, or as an option where users can modify their select their own preferences for options they want present. (for example, I would also like a shortcut to tag multiple photos at once. Currently, that option takes 4 taps to get to when selecting multiple items). 

**Describe alternatives you've considered**
Using the phone in landscape makes the delete option closer to one hand, but is not ideal. 

**Additional context**
I have added a screenshot of what I'm asking for. 
![Screenshots_2023-03-22-05-45-45](https://user-images.githubusercontent.com/128549308/226755445-0e9e0533-d660-4e08-b251-016593155b05.png)

**Comment by deckerst** [comment]
Welcome to GitHub!

Thanks for the suggestion, and I understand that some users would like to have more UI at the bottom for easy reach with one hand, but I'm unlikely to change the current layout.
