### ISSUE TITLE
Quick actions page

### ISSUE THREAD

**Issue by JimW1at** [deckerst/aves#565]
Can there be Info page button in quick actions ...

**Comment by deckerst** [comment]
There are actually 3 sections of available buttons in the settings. The info actions are in the 3rd section. You can swipe horizontally to switch between the sections.

![Screenshot_20230324_083204_Aves](https://user-images.githubusercontent.com/13898333/227455177-e26b1785-65af-43f9-8aa7-83fece16c024.png)
