### ISSUE TITLE
Bigger rename box

### ISSUE THREAD

**Issue by JimW1at** [deckerst/aves#566]
Can we get a bigger rename box, the current rename box is too small, files with long names do not appear fully.
![lsF2PJSLpx](https://user-images.githubusercontent.com/126959019/227521059-308d1c9c-4bab-4b21-a72a-f0e7f9fb6bcb.jpg)

Can the box be bigger to display longer filenames.

**Comment by deckerst** [comment]
Do you mean increasing the height to allow multiple lines?

**Comment by JimW1at** [comment]
> Do you mean increasing the height to allow multiple lines?

Yes
