### ISSUE TITLE
Plagiat at PlayStore

### ISSUE THREAD

**Issue by IzzySoft** [deckerst/aves#568]
There's a plagiator active at PlayStore having published a lot of libre apps with their own ad stuff included. Unfortunately, Aves Libre seems to be affected as well, [see here](https://www.appbrain.com/app/aves/deckers.thibault.aves.libre). You might wish to file a takedown request with Google. Other affected devs [have done so](https://fosstodon.org/@AAMfP/110040759238409645) already, with success. Maybe request a closure of that "developer" account right along, as it seemingly exists only to make money of plagiated apps (which Google should already have received notice for), violating their licenses (in your case I suspect number 2 of BSD3 will not be met as it otherwise would blow their cover).

**Comment by deckerst** [comment]
The "developer" account, and incidentally the Aves copycat, are down. Champagne!

**Comment by IzzySoft** [comment]
:champagne: Congrats! :champagne:
