### ISSUE TITLE
Baidu or Amap / Gaode map support

### ISSUE THREAD

**Issue by mikehendry** [deckerst/aves#572]
Can you add [baidu map](https://map.baidu.com/) or amap（[www.amap.com](https://www.amap.com/)）to the app？

**Comment by deckerst** [comment]
I can include maps if they are provided on mobile for free without quota, and without heavy usage clause in the license.

For `Google Maps` and `Petal Maps`, they require services installed on the user's device (`Google Mobile Services` and `Huawei Mobile Services`, respectively) and they require an API key, but they are free without quota.

For the `Humanitarian OSM` and `Stamen` maps, they do not require installed services nor an API key, and are freely accessible via open endpoints.

For `Baidu` and `Amap`:
1) is it free?
2) do they enforce quota?
3) do they require installed services?
