### ISSUE TITLE
files on sd card suddenly not found anymore

### ISSUE THREAD

**Issue by lukask99** [deckerst/aves#577]
**Describe the bug**
I have my photos organised in folders/albums on an sd card. Today suddenly after a phone reboot, the files on the sd card are not visible anymore (no access?). Aves only finds files on internal storage, and asks permission to use folders there. Other gallery apps still show the sd card folders and photos.

**System information and logs:**

Package: deckers.thibault.aves
Aves version: 1.8.4-play
Aves build: 95
Flutter version: 3.7.7
Flutter channel: stable
Android version: 12
Android API: 31
Android build: FP4.SP21.B.048.20230215
Device: Fairphone FP4
Geocoder: ready
Mobile services: ready
System locales: en_US, en_GB, nl_NL
Aves locale: en -> en
Installer: com.android.vending
Error reporting: false

Log

--------- beginning of system
04-06 09:09:39.937  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:09:56.020  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:10:00.642  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:10:13.172  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:10:50.793  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:12:44.968  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:13:56.227  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:14:44.279  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:15:16.432  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:16:52.517  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:19:03.091  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:19:25.624  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:21:40.512  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
--------- beginning of main
04-06 09:22:10.538  4120  4120 I d.t.a.MainActivity: onStart
04-06 09:22:10.542  4120  4120 I d.t.a.MainActivity: onNewIntent intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10600000 cmp=deckers.thibault.aves/.MainActivity bnds=[843,811][1045,1139] }
04-06 09:22:10.543  4120  5353 I flutter : _AvesAppState onNewIntent with intentData={}
04-06 09:22:10.543  4120  5353 I flutter : Report log=Relaunch
04-06 09:22:10.544  4120  5353 I flutter : Report log=Lifecycle resumed
04-06 09:22:10.599  4120  6401 I OpenGLRenderer: Davey! duration=179457ms; Flags=1, FrameTimelineVsyncId=39061, IntendedVsync=616624044743, Vsync=616624044743, InputEventId=30336359, HandleInputStart=616626971064, AnimationStart=616626972679, PerformTraversalsStart=616626973668, DrawStart=616645038877, FrameDeadline=616690711407, FrameInterval=616626960960, FrameStartTime=16666666, SyncQueued=616645134450, SyncStart=616645272679, IssueDrawCommandsStart=616645408304, SwapBuffers=616647796585, FrameCompleted=796081409225, DequeueBufferDuration=1238541, QueueBufferDuration=1086406, GpuCompleted=796081409225, SwapBuffersCompleted=616649510179, DisplayPresentTime=0, 
04-06 09:22:14.378  4120  5353 I flutter : Device is connected=false
04-06 09:22:14.490  4120  5353 I flutter : Device is connected=true
04-06 09:22:23.767  4120  5353 I flutter : Report log=Lifecycle inactive
04-06 09:22:24.468  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:22:24.471  4120  4120 I d.t.a.MainActivity: onStop
04-06 09:22:24.577  4120  5353 I flutter : Report log=Lifecycle paused
04-06 09:22:31.908  4120  4120 I d.t.a.MainActivity: onStorageAccessResult with requestCode=3, uri=null
04-06 09:22:31.909  4120  4120 I d.t.a.MainActivity: onStart
04-06 09:22:31.911  4120  5353 I flutter : Report log=Lifecycle resumed
04-06 09:22:31.959  4120  4120 I n.d     : onCancel arguments={op=createFile, bytes=[B@b4a43c4, name=aves-logs-20230406_092223.txt, mimeType=text/plain}
04-06 09:22:31.968  4120  6401 I OpenGLRenderer: Davey! duration=200834ms; Flags=1, FrameTimelineVsyncId=39061, IntendedVsync=616624044743, Vsync=616624044743, InputEventId=30336359, HandleInputStart=616626971064, AnimationStart=616626972679, PerformTraversalsStart=616626973668, DrawStart=616645038877, FrameDeadline=616707378073, FrameInterval=616626960960, FrameStartTime=16666666, SyncQueued=616645134450, SyncStart=616645272679, IssueDrawCommandsStart=616645408304, SwapBuffers=616647796585, FrameCompleted=817458530988, DequeueBufferDuration=1238541, QueueBufferDuration=1086406, GpuCompleted=817458530988, SwapBuffersCompleted=616649510179, DisplayPresentTime=0, 
04-06 09:22:43.472  4120  5353 I flutter : Report log=Nav pop to /collection
04-06 09:22:48.194  4120  5353 I flutter : Report log=Lifecycle inactive
04-06 09:22:48.679  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:22:48.688  4120  4120 I d.t.a.MainActivity: onStop
04-06 09:22:48.767  4120  5353 I flutter : Report log=Lifecycle paused
04-06 09:22:59.969  4120  4120 I d.t.a.MainActivity: onStart
04-06 09:22:59.972  4120  4120 I d.t.a.MainActivity: onNewIntent intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10600000 cmp=deckers.thibault.aves/.MainActivity bnds=[843,811][1045,1139] }
04-06 09:22:59.973  4120  5353 I flutter : _AvesAppState onNewIntent with intentData={}
04-06 09:22:59.973  4120  5353 I flutter : Report log=Relaunch
04-06 09:22:59.973  4120  5353 I flutter : Report log=Lifecycle resumed
04-06 09:23:00.016  4120  6401 I OpenGLRenderer: Davey! duration=115655ms; Flags=1, FrameTimelineVsyncId=45439, IntendedVsync=729841853883, Vsync=729841853883, InputEventId=1024067322, HandleInputStart=729843322115, AnimationStart=729843323365, PerformTraversalsStart=729843323990, DrawStart=729857852583, FrameDeadline=729875187215, FrameInterval=729843314406, FrameStartTime=16666666, SyncQueued=729857970344, SyncStart=729858062063, IssueDrawCommandsStart=729858197011, SwapBuffers=729861103313, FrameCompleted=845497834466, DequeueBufferDuration=1170938, QueueBufferDuration=762240, GpuCompleted=845497834466, SwapBuffersCompleted=729862395604, DisplayPresentTime=0, 
04-06 09:23:02.039  4120  5353 I flutter : Report log=Nav push to /about
04-06 09:23:05.804  4120  5353 I flutter : Report log=Lifecycle inactive
04-06 09:23:06.273  4120  4120 V ActivityThread: handleTrimMemory:deckers.thibault.aves
04-06 09:23:06.277  4120  4120 I d.t.a.MainActivity: onStop
04-06 09:23:06.367  4120  5353 I flutter : Report log=Lifecycle paused
04-06 09:23:24.392  4120  4120 I d.t.a.MainActivity: onStart
04-06 09:23:24.404  4120  4120 I d.t.a.MainActivity: onNewIntent intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10600000 cmp=deckers.thibault.aves/.MainActivity bnds=[843,811][1045,1139] }
04-06 09:23:24.404  4120  5353 I flutter : _AvesAppState onNewIntent with intentData={}
04-06 09:23:24.404  4120  5353 I flutter : Report log=Relaunch
04-06 09:23:24.405  4120  5353 I flutter : Report log=Lifecycle resumed
04-06 09:23:24.435  4120  6538 I OpenGLRenderer: Davey! duration=73883ms; Flags=1, FrameTimelineVsyncId=49607, IntendedVsync=796042557501, Vsync=796042557501, InputEventId=698320704, HandleInputStart=796053697298, AnimationStart=796053698548, PerformTraversalsStart=796053699069, DrawStart=796070893287, FrameDeadline=796075890833, FrameInterval=796053690319, FrameStartTime=16666666, SyncQueued=796071034954, SyncStart=796071142871, IssueDrawCommandsStart=796071259537, SwapBuffers=796076723860, FrameCompleted=869925779093, DequeueBufferDuration=3617396, QueueBufferDuration=1004323, GpuCompleted=869925779093, SwapBuffersCompleted=796078148287, DisplayPresentTime=0,

**Comment by deckerst** [comment]
Thanks for letting me know.

Just to be clear, what you see in the storage access settings is related to *write* access, necessary to edit pictures. It's different from the basic *read* access that allows Aves to retrieve pictures from the device.

Related to this topic of SD card write access, I recently made the app more robust when switching cards from one to another.

But for read access, it just seems the Android Media Store on your device was not listing SD card media. Other gallery apps may list media differently, but Aves uses the Android Media Store as the source for media. Sometimes the store takes time to update itself.

I'll close this issue because it's flaky and not actionable. But if this happens again, I'd like to know whether the media SD card media would reappear by themselves after some minutes/hours (without reboot).

**Comment by lukask99** [comment]
Thanks for the explanation.
