### ISSUE TITLE
Add some tags to many photo at once

### ISSUE THREAD

**Issue by jerem-ma** [deckerst/aves#579]
**Is your feature request related to a problem? Please describe.**
To add the same tags to many photos, one has to add them one at a time to each photo. It will be great if it were possible to add the tags to many photos at once.

**Describe the solution you'd like**
Select wanted photos, click on a button "add tags", and choose the wanted tags. Maybe also a reverse option to remove some tags to many photos ?

**Describe alternatives you've considered**
No idea of alternatives

Thank you !

**Comment by deckerst** [comment]
You're in for a treat.

In the `Collection` page, select items, then go to the top right `...` menu, then tap on `Edit` to open the submenu with various actions to modify all selected items at once. Among them is the `Edit tags` action. Give it a try!

I'll close this issue, but don't hesitate to ask if you have questions about the feature.

**Comment by jerem-ma** [comment]
Amazing, I described the way to do that without  looking carefully at it ! Thank you !

**Comment by mxmilkiib** [comment]
It would be great if saving tags was a first class button.

If I can favourite an image with one tap, how about being able to add a tag with two taps rather than five?
