### ISSUE TITLE
Pictures that had tags associated to them previously are unable to show tag unless the pictures are viewed manually

### ISSUE THREAD

**Issue by Terryzinni** [deckerst/aves#582]
**Describe the bug**
Pictures that had tags associated to them previously are unable to show tag unless the pictures are viewed manually

**To Reproduce**
1. Create a tag and associate it to a picture 
2. Transfer that picture to your desktop from your phone.
3. Delete that picture in your phone
4. Transfer the picture from your desktop back to your phone
5. Launch the Aves photo app and search the tag you Created in step 1. Found nothing.
6. Touch the picture and view it, notice the tag name is there.
7. Search the tag again, the picture is now appeared under search result. 

**Expected behavior**
App can scan the tag in the pics and make them appear in the app without the need to manually open and view them.

**Comment by deckerst** [comment]
In step 5, do you see in your collection the photo you transferred in step 4?

Aves uses the system Media Store to list the photos. When transferring files from your desktop, it's likely that the Media Store will take time to update itself. Aves will show you the tags once the Media Store is up-to-date.
