### ISSUE TITLE
Slow motion playback

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#583]
Hi,
Please add an special playback for slow motion videos (like Google Photos, Xiaomi Gallery, Samsung Gallery)

![Screenshot_2023-04-14-08-06-59-384_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/23485114/231943536-e857dbcd-6055-41bd-bc42-682af3ffeccb.jpg)

![Screenshot_2023-04-14-08-13-21-495_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/23485114/231943704-1c34dee6-caa2-41ce-9557-d0291b641ea1.jpg)

**Comment by deckerst** [comment]
Please share a sample of slow motion video.

If you have different samples from different manufacturers (Google, Xiaomi, Samsung), please share a sample for each.

**Comment by xmha97** [comment]
I will share slow motion videos, here: https://github.com/deckerst/aves/issues/585

**Comment by xmha97** [comment]
> On my phone, a Samsung device, Google Photos plays your sample video as you describe, but Samsung Gallery does not detect it as a slow motion video. And i can't test Xiaomi Gallery on my device.

Please see my messages on Telegram.

![Screenshot_2023-04-14-18-16-14-051_org.telegram.messenger.web.jpg](https://user-images.githubusercontent.com/23485114/232077289-4abeef62-2131-4ead-889a-21416a6ea8e6.jpg)
