### ISSUE TITLE
Support video thumbnail

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#584]
Hi,
Currently, the thumbnail is just a picture.
I want it to be a video.
It means that the videos are played before opening.

Like TikTok and Google Photos:

https://user-images.githubusercontent.com/23485114/231945262-8354aef4-ff95-469d-9df7-b5a81a655fd4.mp4

Yes, it uses a lot of battery, but I don't care.
Thanks.

**Comment by deckerst** [comment]
Duplicate:
- #20
