### ISSUE TITLE
Add Quality Slider to Conversion Menu

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#587]
**Is your feature request related to a problem? Please describe.**
Currently, all Jpegs are saved at (what seems to be) 100 Quality, which can bloat some files that were saved at anything less and minimizes the potential space savings converting can have.

**Describe the solution you'd like**
I would like a quality slider (or any way to change numbers: text box, drop-down, etc.) to adjust the quality setting for the target format in the conversion menu, alongside the scaling option.
Ideally, it would conform to the target format's native quality options (Jpeg, PNG, WebP, any future added formats, like Avif or Jpeg XL). PNG is exclusively lossless (unless you use pngquant), but the quality slider does adjust compression ratio and process time, which might matter more to people on mobile devices and with large images.

**Describe alternatives you've considered**
I've been using a separate app to do batch image conversions, but it has ads and it would be better to have an integrated solution.

**Additional context**
It would be nice, for single images (specifically Jpegs), to have the quality slider (or number) be set at the image's current quality. This could be pulled from the metadata, I think. For multiple selected images, it could set at the highest detected Jpeg quality value. I'm pretty sure there's a lot more room for thought on this idea. But I wanted to include it, since I see it being a nice hint as to what the user would be working with that can help avoid bloat by encoding to a higher quality than the original image (with multiple, I'm not sure how to avoid that, aside from showing the highest and lowest values of all selected Jpeg images - PNGs would be ignored, unless the target is PNG...even then, it might not make a difference, but I'm open).
Also, I'm thinking this could be a toggleable option in the settings, unless it's not too intrusive or odd for users to see the setting change depending on what image they're working with. Maybe there could be a little "(?)" hint button next to it that could explain in short form what the slider or whatever means for the selected image format (JPG, PNG, WebP) and why it is at a different spot than "default."
Oh, I forgot about WebP. Does the encoder Aves use support lossless WebP encoding, or is that handled by the system? Maybe there could be a checkbox next to the quality option for toggling lossless (or that could be the max value...I'm not sure how lossless WebP encoding works or what the options are), when WebP is the selected target format.

**Comment by deckerst** [comment]
> Does the encoder Aves use support lossless WebP encoding

It supports both lossless and lossy (on modern Android at least). In practice, i already use a quality parameter internally (i just haven't exposed it to the conversion UI) and i select lossless when quality is 100, lossy otherwise.

**Comment by OkyDooky** [comment]
Smart. That wouls probably be the most intuitive, anyways. If you use a slider, then the value could be in a small point font underneath and the value could go from "99" to "Lossless" instead of to "100." Not sure using a string in any other context would work, though.

**Comment by OkyDooky** [comment]
Thank you. I just took a look at it and it's exactly what I pictured. And, playing around with it, it works like expected!
