### ISSUE TITLE
Ability to choose *never* resume and *always* resume videos. 

### ISSUE THREAD

**Issue by texturesplunky** [deckerst/aves#590]
Every time I revisit a video I get a promt asking if I want to resume where I left of. Please allow us to turn that off, by offering *never* and *always* resume. This would offer more complete control over the issue for the users. Theres no need to take away the option to choose every time as that is preferred by some (other) users. 

Thanks!

**Comment by deckerst** [comment]
I did not add the options to the dialog itself, but it's now in the video playback settings.

**Comment by texturesplunky** [comment]
> I did not add the options to the dialog itself, but it's now in the video playback settings.

Thank you very much! Really great work!
