### ISSUE TITLE
Explorer / Ability to open a specific folder inside a nested folder structure

### ISSUE THREAD

**Issue by Raoul-Kima** [deckerst/aves#592]
Problem:
One of the most common ways of organizing things on a computer/smartphone etc. is to organise things into some kind of nested folder structure. E.g. 2023/summer/photoProjects/birdProject/photos/bird3/portrait.
But Aves currently doesnt allow you to see/utilize the nested nature of this structure, instead showing all folders in a flat way.
Here are some examples where this leads to problems:

Example 1:
Suppose you organize your hobbies (and jobs) into projects, each living in a separate folder. Over time these accumulate, there could be hundreds of them. Inside each project there is a sub-folder called "photos" which documents that project.
How can one browse the photos of a specific project?
With the current app version I see two ways to do this:
1. Enter "photos" into the search box and then go through the (possibly hundreds) of same-named entries, trying to guess which one is the one you were looking for. Problem: cumbersome and annoying until you found the right folder. It's worse if you want to quickly compare different projects, now you have to jump between the folders quickly, which is basically impossible with this method.
2. Find the right folder using a file management app, then from within that app open one of the photos via Aves. Problem: When Aves is invoked in this way then one can only see individual photos in Aves, but cannot utilize the mosaic view.

Example 2:
I photograph birds. Lots of them, many different individuals from many different species. Each individual bird lives in its own folder. Naturally, these folders tend to have similar names, e.g. something like date_speciesName_locationName. Many of these bird-folders contain subfolders naming body parts e.g. head, wing, tail, and so forth (it's a reference database for bird-identification purposes). The same problem as in Example 1 occurs: How can I navigate to the "wing" folder of a specific bird and see it in mosaic view? Another problem that arises here is that if i want to compare several birds its difficult to quickly navigate from (the mosaic view of) one to the next, even though each has a unique folder name. Basically one has to either do it the same way as in example 1 or manually type in the folder name.

Example 3:
Sticking with the scenario of example 2: suppose I have found the folder of a specific bird and want to browse all of its photos. Problem: If some of these photos are in subfolders Aves doesn't show them. I can't even see that this problem exists from within Aves, it just looks as if these photos wouldn't exist.

Possible solutions:

Solution 1: Incorporate some kind of file system view (e.g. by showing folders alongside photos and allow navigating to the enclosing folder)
Solution 2: Allow entering mosaic view after an image has been opened in aves from a file manager app.

Solution 1 may (depending on how it's implemented) have the advantage of allowing users to more quickly navigate subfolders within a folder, and, if the subfolders are shown alongside the photos, the advantage of making the user aware that subfolders exist.

Alternatives:
One natural alternative would be if it was possible to open a folder in aves from a file manager. But my file manager doesn't allow that, it only allows opening files in external apps, not folders. I suspect that is how it generally is on android?

**Comment by deckerst** [comment]
Interesting use cases and ideas, thank you.

Generally about nested folders, there is already this issue:
- #268 

About opening a folder from the file manager, it's true that it is not currently possible, but i could try and allow opening it from the `Info` page of the opened image.

About album comparison, what you can do is pin them. Let's say you searched for the album, then you can long press on the chip and select `Show in Albums`, then pin it to the top. Do the same with the other albums of interest. Then from the `Albums` page you can quickly switch between the pinned albums.

Also, i don't intend to change your workflow, but it seems to me that your intricate folder structure would be better represented by tags instead. You can use tags for the name of the bird, body part, project, commissioner, whatever... Because they are multidimensional (compared to folders that are just a tree), they are preferred by photographers, journalists, archivists, etc. who need to precisely document their images.

**Comment by Raoul-Kima** [comment]
True, I should have mentioned #268 .
These two issues are related, but not necessarily equivalent, because albums are not necessarily the same thing as folders. E.g. a folder could contain all kinds of things, only some of which being subfolders containing photos. It is not clear to me what the definition of "album" used by Aves is, and what the vision for their user interface is.

As a sidenote: I have accidentally deleted files in other photo-viewing apps because I thougt the folder was empty. So in case you end up implementing folder view then it's probably a good idea to either display non-image files, or not allow deleting folders from within Aves, or to emitting a warning if one tries to delete a folder containing non-image files.

Thanks for the tip to pin albums for comparison. When I want to compare back and forth between several albums that could work well. But I also have the use case where I linearly traverse a large number of folders without going back to previous ones. This use case comes up when I do bird identification training, when I explain some bird id stuff to someone, or when I encounter a bird in the field and compare it to my photos to identify it.

About tags vs folders for organisation: True! Unfortunately I want to organise not only my photos but many other file types as well. I dont want to have separate systems for photos and the rest. There is software for that, but the solutions I found all had problems like vendor lock-in, being too use-case specific, too complicated or expensive.

**Comment by deckerst** [comment]
> It is not clear to me what the definition of "album" used by Aves is

I favoured the word "album" rather than "folder" because it would be future-proof in case I someday connect with cloud services like Google Photos, where the notion of "album" exists but not "folder". In practice, for local storage, an album is backed by a single folder (without its subfolders).

> I have accidentally deleted files in other photo-viewing apps because I thougt the folder was empty

In Aves, when you rename/delete an album, it actually moves/deletes media files in it, but it never touches non-media files. Even if I expose folder structure as it is on storage, I would do file manipulation the same way. Data loss is to me the most important thing to avoid.

**Comment by DroidFloyd** [comment]
Good day dev. The only thing I want for Christmas is this feature to arrive as soon as possible.

**Comment by DroidFloyd** [comment]
Rant Alert! 
Good day dev. Any time line on this feature? Too many things are being prioritized over nested folder/groups.

Almost everyday I check up on your app for updates and features, although always appreciated I never see this 1 feature to make Aves perfect in my eyes.

I don't serve to annoy or upset you. I'm just tired of seeing one long strip of albums, and blindly🧑‍🦯 waiting for when this will be added.

**Comment by deckerst** [comment]
> Any time line on this feature?

No timeline, no promise. It may never be implemented.

> Almost everyday I check up on your app for updates and features, although always appreciated I never see this 1 feature to make Aves perfect in my eyes.

This is useless. You can subscribe to issues (or simply watch repo releases) for updates.

> I don't serve to annoy or upset you. I'm just tired of seeing one long strip of albums, and blindlyperson_with_probing_cane waiting for when this will be added.

I don't mind banning people who are rude, feel entitled, or are generally annoying. Don't rant on this repo.

**Comment by DroidFloyd** [comment]
I fully understand. However it's not useless.
