### ISSUE TITLE
Add Sony "Predictive capture" as burst-format

### ISSUE THREAD

**Issue by sjordet** [deckerst/aves#598]
**Is your feature request related to a problem? Please describe.**
At least earlier, Sony had something they called "Predictive Capture" (I don't think it exists on recent phones?), which might take a image before you actually pressed the trigger. Or one after you pressed the trigger. They look like "normal" bursts, except that the filenames are "DSCPDC_0000_BURST20180224164317669.JPG" - notice the 'PDC' there.

Would it be possible to add this as well? The folder-structure is "PREDICTIVE_CAPTURE/DSC_20180224164317669/DSCPDC_0000_BURST20180224164317669.JPG"

**Describe the solution you'd like**
To have these "predictive captures" show up as regular bursts.

**Comment by deckerst** [comment]
Is `DSCPDC_0000_BURST20180224164317669.JPG` in the same folder as the other pictures in the burst?
How's the file name of the other pictures in the burst?

**Comment by sjordet** [comment]
Hi!

Same as for other bursts, the only difference is the added "PDC"... 

# ls PREDICTIVE_CAPTURE/DSC_20180619163426901
DSCPDC_0000_BURST20180619163426901.JPG
DSCPDC_0001_BURST20180619163426901.JPG
DSCPDC_0002_BURST20180619163426901.JPG
DSCPDC_0003_BURST20180619163426901_COVER.JPG

**Comment by deckerst** [comment]
Unrelated: do you `ls` directly on your phone?

**Comment by sjordet** [comment]
Hehe, no. I use FolderSync (which is one of probably many different tools that do the same) to sync all images from my phone to my server. This was just the easiest way to show the structure...
