### ISSUE TITLE
Better GUI design when editing tags (applied changes button)

### ISSUE THREAD

**Issue by JanWaldhorn** [deckerst/aves#601]
**Is your feature request related to a problem? Please describe.**
When I add tags I am confused how to confirm the change. For me, the non-intuitive solution is to use the back arrow in the upper left corner, then the changes are made.

**Describe the solution you'd like**
As in the attached screenshot, I would find a dedicated confirmation button (red checkmark) useful, as there is already an undo button. The back arrow would require a confirmation if the changes should be applied or discarded.

**Describe alternatives you've considered**
I can live well with the current state, as I now know how it works. I just don't think it's solved in a comprehensible way, unlike the rest of the app. Thanks a lot for Aves again!

**Additional context**
![aves_tag_accept_icon](https://user-images.githubusercontent.com/57268762/233183809-32d0c971-52fb-4e4b-86c6-836a00205787.png)

**Comment by deckerst** [comment]
True, it's a bit awkward ^^
