### ISSUE TITLE
Pip mode not working properly

### ISSUE THREAD

**Issue by tsiflimagas** [deckerst/aves#603]
**Describe the bug**
When watching a video and switching to another app or returning to home screen it either pauses or sometimes switches to paused PiP. 

**To Reproduce**
1. Start playing a video
2. Leave the app while it's playing (don't close the app though)
3. Observe that PiP either isn't entered at all or it gets paused

**Expected behavior**
When leaving the app while a video is playing it should seamlessly switch to PiP.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.android.packageinstaller
Aves version: 1.8.5-libre, build 9602
Flutter: stable 3.7.11
Android version: 13, API 33
Android build: TQ1A.230105.001.A2
Device: Xiaomi Redmi Note 8
Geocoder: not available
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/3A6F-15EF/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Download/VideoDownloader/
Error reporting: false
[aves-logs-20230421_155100.txt](https://github.com/deckerst/aves/files/11295860/aves-logs-20230421_155100.txt)

**Comment by deckerst** [comment]
As I understand it, the switch to PIP should happen only when pressing home, not when switching to another app.

I'll take a closer look into the pause issue.

**Comment by tsiflimagas** [comment]
> As I understand it, the switch to PIP should happen only when pressing home, not when switching to another app.

Hmm you're right, I didn't think that well about that part.

**Comment by deckerst** [comment]
It actually works fine when going home via the button nav bar, but it's buggy when going home by gesture. I don't use navigation gestures so I never catch these discrepancies myself >.<

**Comment by tsiflimagas** [comment]
Huh, you're right. I never use navigation bar, ever since navigation gestures were added in Android, so I never noticed that either, conversely.
