### ISSUE TITLE
Add more space at the top

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#604]
Hi, you can follow the Samsung UI and add more space at the top:

![screen-1](https://user-images.githubusercontent.com/23485114/233789570-b9d724bb-ceba-4b57-aa8f-460132c8cde9.jpg)

**Comment by deckerst** [comment]
I have a Samsung device and I am familiar with One UI esthetics. I like it overall and it's already an influence on Aves design, but the app is *not* trying to fit into Samsung esthetics, and I'm not a fan of this top space in particular.

**Comment by xmha97** [comment]
The existence of empty space is because the app can be used with one hand.
Currently, you have to use another hand to select items on the top of the page.
What was interesting to me was this idea.
I don't care if the app follows the Samsung UI.

Some apps use this idea, for example, Kiwi Browser, which has a feature that adds empty space to the top of sites:

https://user-images.githubusercontent.com/23485114/234136388-eea058c9-f152-46e8-bc10-f1281a29c1d6.mp4

**Comment by deckerst** [comment]
I see, thanks for the explanation. Even so, having everything accessible for one hand usage is not a goal.

By the way, on a Samsung device (and probably others) you can address your issue by opening the app in a pop-up view.
![Screenshot_20230425_102749_One UI Home](https://user-images.githubusercontent.com/13898333/234219597-1a21a370-f774-49a6-9871-96d25833faf2.png)
