### ISSUE TITLE
Only images opened at least once show up on the map

### ISSUE THREAD

**Issue by ray0711** [deckerst/aves#606]
**Describe the bug**
After installation the map and countries list is empty. None of the pictures with location information is displayed.
After opening a picture it is added to the map. Opening all 5k pictures inr by one is not efficient. Rescan button has no impact.

**To Reproduce**
1. Install app
2. Go to countries or go to map

**Expected behavior**
Scanning resolves also location information or there could be an additional option for it if the process is very slow

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.8.5-play, build 96
Flutter: stable 3.7.11
Android version: 13, API 33
Android build: TQ2A.230405.003.E1
Device: Google Pixel 7
Geocoder: ready
Mobile services: ready
System locales: en_US, en_DK
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Additional context**

**Comment by deckerst** [comment]
Duplicate:
- #324
