### ISSUE TITLE
Make Countries entirely highlighted/filled if a photo was taken in that country.

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#608]
It is not always easy to see which countries you have taken photos in when fully zoomed out, especially in Europe where there are so many small countries.

When viewing photos on the map, and fully zoomed out, it would be good to colour the entire country instead of displaying photo icons. This would make it nice to see which countries you have visited. This could also maybe even apply to states, regions or provinces in the country. 

The main point of this feature is to give you nicely coloured countries that you have visited. This could automatically occur when you fully zoom out or even via another toggle icon on the map.

**Comment by deckerst** [comment]
I think this is out of scope.

Also, from a technical point of view, I have topological data about countries (for a quick first pass of reverse geocoding) but I don't have data about actual country borders.

**Comment by petazonk** [comment]
Fare enough as I thought the map APIs might allow for easily highlighting countries.
