### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by tashijayla** [deckerst/aves#610]
What is the difference between the app on f-droid called aves and the app called aves Libre 

https://apt.izzysoft.de/fdroid/index/apk/deckers.thibault.aves

https://www.f-droid.org/packages/deckers.thibault.aves.libre/

Even aves Libre still have the option to use Google firebase analytics so their doesn't seem to be a difference between them

 ![Screenshot_20230425_184255.jpg](https://user-images.githubusercontent.com/93866029/234359483-e7d1dba2-f97f-4853-87f5-36b0e93d6192.jpg)

**Comment by deckerst** [comment]
You can peruse the wiki for [version comparison](https://github.com/deckerst/aves/wiki/App-Versions).

The terms are the same for both versions because it's more convenient for me. However, the libre version does not include Crashlytics and the option to enable it is not present.
