### ISSUE TITLE
Moving right and left between Pictures is slow compared to Simple Gallery App.

### ISSUE THREAD

**Issue by matt873** [deckerst/aves#613]
Can it be made fast like in the Simple Gallery App?

**Comment by deckerst** [comment]
Are you talking about swiping? If so, maybe you would prefer tapping on edges for instant change without animation. You can enable that in `Settings` > `Viewer` > `Tap on screen edges to show previous/next item`.

To answer your question, I have no interest in matching design or feel of other apps.
