### ISSUE TITLE
Screen edge detection for swiping is not great

### ISSUE THREAD

**Issue by jcperil** [deckerst/aves#622]
**Describe the bug**
Sometimes, it detects two quick touches on the edge of the screen as an action to zoom in, instead of swiping two pictures ahead.

**To Reproduce**
1. Go to an album with sufficient photos to swipe.
2. Click to open the first photo in the album.
3. Touch very frequently on the right edge of the screen to swipe right.
4. Multiple quick touches are detected as an action to zoom in.

**Expected behavior**
Touches on screen edges should be detected as an action to swipe instead of zooming in.

https://user-images.githubusercontent.com/89805719/235377568-fc59df68-c071-476c-81ed-7b049625bf45.mp4

**Screenshots**

https://user-images.githubusercontent.com/89805719/235377634-f5bcd92b-d933-4dfe-9e41-1aee43dbd899.mp4

**System information and logs:**
```
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.8.5-libre, build 9602
Flutter: stable 3.7.11
Android version: 13, API 33
Android build: TKQ1.221013.002 test-keys
Device: Xiaomi M2101K6P
Geocoder: ready
Mobile services: not available
System locales: en_IN
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false
```

[aves-logs-20230501_031809.txt](https://github.com/deckerst/aves/files/11362491/aves-logs-20230501_031809.txt)

**Additional context**

**Comment by deckerst** [comment]
Now single tap to go to previous/next entry has precedence over double tap to zoom.
For the users who enable the video gesture to skip 10 sec by double tap on the side, this gesture has precedence over the 2 above.
