### ISSUE TITLE
Generate geo clickable links

### ISSUE THREAD

**Issue by tch123** [deckerst/aves#623]
1. When displaying GPS coordinates, it is hoped that a clickable GEO link can be generated, so that it is convenient to call the map app for positioning or navigation

2. When the GPS coordinates are displayed, it is hoped that the display format can be set in the options

**Comment by deckerst** [comment]
1. There is an action for this in the viewer export menu.
![Screenshot_20230501_092953_Aves](https://user-images.githubusercontent.com/13898333/235423268-0332a37d-efa2-4a3c-beb6-bddd15bfc0de.png)

2. Go to `Settings` > `Language & Formats` > `Coordinate format`.
