### ISSUE TITLE
Sharing video problem [with certain app]

### ISSUE THREAD

**Issue by marcosilva85** [deckerst/aves#624]
**Describe the bug**
Disclaimer: I do not know if this is a bug from Aves or from the destination app.
But 1) here is the problematic effect:
Sharing a video from Aves to FFshare does not work (specific video, not sure why). What I see: FFshare seems to load it but then crashes just after.
(It always works properly when sharing from Google Photos or from Simple Gallery to FFShare.)

and 2) the steps to get the issue:
Install FFShare from fdroid: [Github FFShare](https://github.com/caydey/ffshare/), [Fdroid FFShare](https://f-droid.org/en/packages/com.caydey.ffshare/)
Open Aves, go to a video (try several ones) and share it to FFshare, until you see this behaviour.
(Sorry that I don't have a special non-personal video to share. Please try to check with your videos, I believe you might also see this behaviour quickly. If you have difficulty in reproducing I might try to find some other mp4 online, where issue happens.)

Could be connected to some special way that Aves uses to share the files, could be FFshare itself, but its odd that it works properly always from GPhotos app and Simple Gallery.

**Comment by deckerst** [comment]
Thanks for letting me know.

I've tried with various videos and so far no crash.
I got:
- most of the time, the compression process starting correctly,
- sometimes, the compression process failing with "Error compressing media", but retrying the same video works,
- the error message "Unknown filetype" when opening exotic formats like M2TS.

Have you tried to reach `FFShare` and see if it's a bug on their side?

As for a sample, even if the crashing video is personal, if you trust me you can send me one via [email](gallery.aves@gmail.com).

**Comment by marcosilva85** [comment]
@deckerst just to leave a comment for sake of completeness here in this ticket - I think the issue was in FFShare as this https://github.com/caydey/ffshare/issues/45 could indicate of what was happening to me back then.
