### ISSUE TITLE
easier opening of filter bar in move dialogue

### ISSUE THREAD

**Issue by totti4ever** [deckerst/aves#626]
**Is your feature request related to a problem? Please describe.**
I try to organizer my camera's picture by throwing them in different folders. Having the search bar in the filter tab is a big help, it is just annoying that I have to open it by going though the 3-dot menu each time.

**Describe the solution you'd like**
Show it as default, maybe by a global setting. Or show it when pulling the screen down

**Describe alternatives you've considered**
Use other apps for moving

**Additional context**
No

**Comment by deckerst** [comment]
Showing it was the default a looong time ago, probably before it was possible to toggle it.

I won't add a setting or change the current layout, but I will make it remember whether the user enabled the search bar when picking an album (whatever the goal: move / copy / convert).
