### ISSUE TITLE
Disable "auto delete media from trash"

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#629]
Hi, please add an option to disable "auto delete media from trash" (like Google Podcasts)

![Screenshot_2023-05-01-22-52-53-279_com google android googlequicksearchbox](https://user-images.githubusercontent.com/23485114/235515647-c7d412c9-ced8-4cb5-a263-fe6cef21fcf0.jpg)

Thanks 🙏

**Comment by deckerst** [comment]
Where do you see "auto delete media from trash" in your screenshot?

**Comment by xmha97** [comment]
> Where do you see "auto delete media from trash" in your screenshot?

Photos and videos that are in the trash will be deleted after one month. I want to disable this feature. This means that photos and videos will remain in the trash forever.

The photo I sent is not related to the Aves app.

**Comment by xmha97** [comment]
Why was this feature request closed? Do you think it's impractical? @deckerst

**Comment by deckerst** [comment]
@xmha97 then you wouldn't need a recycle bin, you could just move your files to a specific directory.

**Comment by xmha97** [comment]
I understand that the current Trash behavior is intentionally designed to auto-delete items after 30 days.

However, it would be great if this behavior were configurable instead of fixed. Some users prefer using Trash as a long-term safety layer and may not want automatic deletion at all.

Many other gallery apps already allow:

* custom retention periods
* disabling auto-delete entirely

For example:

* 7 days
* 30 days
* 90 days
* Never auto-delete

## [ReFra Gallery](https://github.com/IacobIonut01/ReFra):

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/c74346c1-2d93-493b-b296-68047b50fcef" />

## [Photo Gallery - Secure Photo and Video Manager](https://play.google.com/store/apps/details?id=photography.blackgallery.android):

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/c75b8f50-5681-4e34-b6e0-cddf8d2ed8cc" />

The current 30-day behavior could remain the default, while giving users more flexibility and control.

Thanks for considering it.

**Comment by xmha97** [comment]
Sorry for commenting on this issue again.

Since you added the “recycle-bin” label, I thought you might be planning to work on it in the future. If you plan to work on it, please reopen the issue. Otherwise, feel free to ignore this comment.
