### ISSUE TITLE
Add functionality to Widget for displaying random photos

### ISSUE THREAD

**Issue by pachesp** [deckerst/aves#638]
The app and the widget work really nicely.

It would be great though, if the widget for displaying photos could be configurable for:

- Displaying random photos every X seconds, X being also configured by the user. 

- Displaying random photos as the user swipes

**Comment by deckerst** [comment]
I like the idea but as far as I know this is not possible, because widgets cannot be updated too often (30 minute at best, from memory). Also, widgets cannot handle as many different gestures as apps do. Basically you can tap or scroll a list, and that's all.

**Comment by pachesp** [comment]
Thanks for updating

Would the 30 minutes option be feasible? Or anything that randomly changes the image? Like locking/unlocking the phone, or some other accessible callback?

I think such a feature could bring great added value to the app.

**Comment by deckerst** [comment]
It's already changing the picture every 60 minutes (more or less, depends on the OS scheduling). In the widget settings you can choose if the displayed item is `random` or `most recent`. And it also changes the image when tapping on the widget.

**Comment by pachesp** [comment]
Right. 

As a last question/ request, in the configs there is also a configuration "when taping on the widget" could something like " show next" be added?
I've seen some widgets updating the display within seconds. 

You mentioned that the gestures are limited, but if any other simple gesture ( such as double tap) can be added, some additional functionality could be added there.

**Comment by deckerst** [comment]
> could something like " show next" be added?

I'll take a look.

**Comment by pachesp** [comment]
Nice! Thanks! Excited to try it out
