### ISSUE TITLE
Question: Where are vaults located?

### ISSUE THREAD

**Issue by Bitwolfies** [deckerst/aves#643]
I've browsed through the Android/Data/deckers.thibault.aves.libre folder, and while the trash bin is there, vaults are not. Just wondering how you managed to completely hide them from view, thank you!

BTW, best photo app I've ever used on android.

**Comment by deckerst** [comment]
Glad you enjoy the app.

Among app specific directories, there are some on the external storage (what you looked at, where you found the trash), and some on the internal storage (where i put the vaults). Note here that "external" does not mean that it is on a removable SD card.

In practice, the app specific external storage is:
`/storage/emulated/0/Android/data/deckers.thibault.aves.libre/files/...`

And the app specific internal storage is:
`/data/user/0/deckers.thibault.aves.libre/files/...`

Cf [Android doc](https://developer.android.com/training/data-storage/app-specific).
