### ISSUE TITLE
Hide/unhide vault

### ISSUE THREAD

**Issue by jerryn70** [deckerst/aves#646]
It will be great if you add toggle in the 3 dot menu to hide/unhide vault from Albums. So that no one say their is a secret vault on our Phone. Otherwise some will ask what is this vault or what's inside  this vault.

**Comment by deckerst** [comment]
Not going to do that. Content is already hidden. If you're worried about people seeing there's a lock, you could be also worried that they see the hidden items in the app settings.

> Otherwise some will ask what is this vault or what's inside this vault.

You don't have to answer them.
