### ISSUE TITLE
Operations on photos fail after upgrade to new version

### ISSUE THREAD

**Issue by avalx** [deckerst/aves#653]
**Describe the bug**
After every upgrade to a new version all operations (copy, move, assign tag, ..) that I try on any photo fail. I just get the notification as in the attachments. This is happening until I reboot my phone and after that everything works fine again.

**To Reproduce**
1. Upgrade to a new version (from IzzyOnDroid)
2. Chose any photo
3. Try to do some operation as mentioned above
4. See error "Failed"

**Expected behavior**
Photo operations should work after upgrade without the need to reboot the phone.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

![Screenshot_20230314-080442](https://github.com/deckerst/aves/assets/22810741/6f5f6c51-db45-4104-b507-f7989599a730)
![Screenshot_20230314-080254](https://github.com/deckerst/aves/assets/22810741/115648fe-0b30-43fb-8bbd-8d7b3d08d18b)

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

[Aves.txt](https://github.com/deckerst/aves/files/11610099/Aves.txt)
[aves-logs-20230531_094311.txt](https://github.com/deckerst/aves/files/11610100/aves-logs-20230531_094311.txt)

(PNOTE: The log is not from when the problem occurs as I already rebooted the phone!)

**Additional context**

**Comment by deckerst** [comment]
Thanks for the report.

Please paste your system information (from About page > Bug Report section).

Also, do you use a custom rom or a rooted device?

**Comment by avalx** [comment]
> Thanks for the report.
> 
> Please paste your system information (from About page > Bug Report section).
> 

I thought I already did this - it's supposed to be in the attachment Aves.txt. But here it goes again:

Package: deckers.thibault.aves
Installer: com.google.android.packageinstaller
Aves version: 1.8.8-izzy, build 9901
Flutter: stable 3.10.2
Android version: 11, API 30
Android build: HD1903_14_220617
Device: OnePlus HD1903
Geocoder: ready
Mobile services: ready
System locales: en_SI, en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/fooViewSave/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Snapseed/, /storage/emulated/0/TMP/, /storage/emulated/0/Android/media/com.whatsapp/
Error reporting: false



> Also, do you use a custom rom or a rooted device?

I'm using stock OOS 11 but my device is rooted!

**Comment by deckerst** [comment]
I tried to manually install Aves v1.8.7 (Izzy) on a device, then upgrade it to v1.8.8 (Izzy) and it worked as expected. I got the APKs from the release page. I tried doing it with both the `arm64-v8a` and the `armeabi-v7a` variants. I tested this on a Galaxy S7 running 8.0.0 (Oreo). I need to try again on Android 11+.

How do you upgrade? Do you use an app like Neo Store, or do you get the releases from the GitHub page?

**Comment by deckerst** [comment]
I'm in the process of releasing a new version of Aves. If you encounter the problem again when upgrading, please save logs of that issue __before__ rebooting.

**Comment by avalx** [comment]
> 
> How do you upgrade? Do you use an app like Neo Store, or do you get the releases from the GitHub page?

I always upgrade via a store app: Droid-fy or F-Droid.

**Comment by avalx** [comment]
> I'm in the process of releasing a new version of Aves. If you encounter the problem again when upgrading, please save logs of that issue **before** rebooting.

OK, I'll do that.

**Comment by avalx** [comment]
I've just upgraded to version 1.8.9 and the problem is still there. Included are the logs before the phone was rebooted. (I still didn't reboot so if there is somethin else I should try let me know).

[aves-logs-20230605_213921.txt](https://github.com/deckerst/aves/files/11662003/aves-logs-20230605_213921.txt)

**Comment by deckerst** [comment]
Thanks for the feedback. You can reboot, don't wait for me. If you're willing to help further, please contact me by email and I'll provide some test builds.

**Comment by deckerst** [comment]
@avalx Do you still experience the issue with the latest version of Aves, v1.11.13?

**Comment by avalx** [comment]
I'm not sure - the last time I tried this was still a problem but that was quite some versions ago. I'll check with the next upgrade.

**Comment by avalx** [comment]
Just to let you know that this is problem is not present anymore.

Thanks again for this great app and your efforts.

**Comment by deckerst** [comment]
Nice, thanks for following this up!
