### ISSUE TITLE
Alternate Thumbnail Zoom Gesture

### ISSUE THREAD

**Issue by AeliusSaionji** [deckerst/aves#654]
**Is your feature request related to a problem? Please describe.**
Sort of- it's a small accessibility concern. I only have one hand, and pinch zoom is inconvenient.

**Describe the solution you'd like**
Swipe left to zoom out, right to zoom in on a given thumbnail view.

**Describe alternatives you've considered**
I suppose I could try to use tasker to simulate this.

**Additional context**
This is a nice feature of Sony's old abandoned Album app. 

https://github.com/deckerst/aves/assets/4342746/e134ddb3-c8d9-461b-bbb6-fef9c7df42fd

Thanks!

**Comment by deckerst** [comment]
I don't know whether I'll do what you suggest, but in the meantime, you could try `Settings` > `Accessibility` > `Show multi-touch gesture alternatives`. Then, when you go to the Collection page menu `...` > `View`, you'll see a slider to select the number of columns.

**Comment by deckerst** [comment]
I've thought about it, and I want to reserve lateral swipe for other uses in the future, so I won't implement it for thumbnail size change.

That said, I care about accessibility, so please let me know whether the alternative control I've described above works for you.
