### ISSUE TITLE
Choosing the different media player for videos like MPV

### ISSUE THREAD

**Issue by they10** [deckerst/aves#655]
**Is your feature request related to a problem? Please describe.**
I wanna watch videos with MPV and I want to start videos automaticly with different media player instead of aves media player

**Describe the solution you'd like**
When first time try to open a video on aves, can aves ask us with which media player we wanna open the video? And on the bottom "remember this" section.

**Comment by deckerst** [comment]
I don't understand how automatically playing in another app wouldn't conflict with normal browsing within Aves.
Let's say you have 3 items in your collection:
- image 1
- video 2
- image 3

You tap on image 1 thumbnail, so it opens image 1 in full screen. Then you swipe to video 2, and you want it to open in another app? So you can't continuously swipe to go to image 3?

Also, you can no longer browse to a video and vertically swipe to see the detailed info.

Current in-app autoplay combine well with these workflows, but outside-app autoplay would.
