### ISSUE TITLE
Rename app to "Gallery" or "Gallery Aves" (adapting it to other languages) in the Apps list/drawer

### ISSUE THREAD

**Issue by ikki4** [deckerst/aves#657]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Since this is a Gallery App, it should me named "Gallery" (or "Gallery" equivalent in other languages) in the Apps list/drawer, just like other gallery apps. 
The following screenshot exemplifies/explains what I mean. If this need translators, I'm glad to help with the Brazilian Portuguese language, just please tell me how.

![Screenshot_2023-06-03-14-10-16-940_com miui home](https://github.com/deckerst/aves/assets/38467650/cbb6e058-e5f3-4023-9adb-218e66adabf9)

**Describe alternatives you've considered**
There are a lot of other apps (including other foss apps) that does this, like SimpleMobileTools/Simple-Gallery (which is the app I'm intending to replace with Aves).

**Additional context**
None.

**Comment by deckerst** [comment]
I understand what you mean, but I disagree. Other apps may want to be used as basic interchangeable tooling apps. This is not how I want to promote Aves. It has a name, an idiosyncratic design and identity. I do not intend to tone that down.
