### ISSUE TITLE
bug: Skipping in Videos is Widely Divided

### ISSUE THREAD

**Issue by onkoe** [deckerst/aves#660]
## Describe the bug
When you skip to a certain point in a video, you'll often find that the Aves video player puts you back to the beginning or skips to the end. In comparison to other gallery applications, Aves handles this task oddly.

## To Reproduce
1. Open a video
2. Skip around
3. You'll likely notice that the skip goes far away from where you selected on your bar, perhaps over 50-60% of the video's length away from your intended location. 

## Expected behavior
The playback progress bar should be draggable to a very specific location. For example, Simple Gallery offers no fancy features, but the video skipping works by dragging a SeekBar to some location, where the video frame is interpreted. 

You can see how they handle it [in their VideoPlayerActivity.kt file](https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/kotlin/com/simplemobiletools/gallery/pro/activities/VideoPlayerActivity.kt), with their specific skipping functionality below. 

    override fun onProgressChanged(seekBar: SeekBar?, progress: Int, fromUser: Boolean) {
        if (mExoPlayer != null && fromUser) {
            setPosition(progress)
            resetPlayWhenReady()
        }
    }

## Screenshots

https://github.com/deckerst/aves/assets/66580279/816bf596-2411-44a9-b258-8d7e0993daae

## System information and logs:

```
Package: deckers.thibault.aves
Installer: org.fdroid.fdroid.privileged
Aves version: 1.8.9-izzy, build 10001
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: lineage_guacamole-userdebug 13 TQ1A.230205.002 eng.root.20230309.013843 dev-keys
Device: OnePlus GM1911
Geocoder: ready
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Download/Barinsta/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Download/TelegramRust/, /storage/emulated/0/AeroWitter/
Error reporting: false
```

[aves-logs-20230605_173357.txt](https://github.com/deckerst/aves/files/11658327/aves-logs-20230605_173357.txt)

## Additional context
This has been a long-time problem for me on several different devices, including a OnePlus 7 Pro, Pixel 6 Pro, and a Samsung Tab S6 Lite, running several ROMs. These include OxygenOS, stock Pixel, LineageOS, LineageOS for microG, CalyxOS, GrapheneOS, and Pixel Experience. All of them have the issue. 

The video demonstration of the bug is on my OnePlus 7 Pro. I hardly use it after switching to an iPhone, but it was happy to download the newest update - though only over a VPN..? I threw together some memes and tried a bunch of videos. I was able to recreate the problem many, many times...

Anyways, I've considered fixing it myself, but the codebase is Dart and I don't use Android phones anymore. Just hoping this will get fixed so my tablet can skip around videos correctly - at least, when I use its gallery once a year. Thank you! ☺️

**Comment by deckerst** [comment]
Not a bug but a limitation of the current video engine used by Aves. The benefit of the one I'm using is that i can configure which codecs it includes, so i can support AVI, MKV, AC3, MP2TS, and others of interest to me. The downside is that this engine is not as good as others with seeking, looping, etc.

**Comment by deckerst** [comment]
Should be improved with the new engine.
