### ISSUE TITLE
Show actions on the bottom 

### ISSUE THREAD

**Issue by Turhvjbufv** [deckerst/aves#661]
In the "all collection" screen when you long press on an item it shows you the actions you can do with it on the top of the basically replacing ![3.png](https://github.com/deckerst/aves/assets/91851160/e91a2200-c323-4d7c-bf25-c7f0492c01df)

With this
 app![1.png](https://github.com/deckerst/aves/assets/91851160/6a4abee8-5d6a-452a-bd9a-ce760b9023bd)

Instead I would like it if we were able to choose if it should do what it does now or be placed right above this(or even replacing it) menu![2..png](https://github.com/deckerst/aves/assets/91851160/d2433c4d-e786-4e07-8a8a-98081a78c121)

**Comment by deckerst** [comment]
I don't want to complexify design related settings, and not everything can be at the bottom.

**Comment by deckerst** [comment]
Oops, I meant to do so. Thanks.
