### ISSUE TITLE
Keep screen on while watching a video

### ISSUE THREAD

**Issue by glemco** [deckerst/aves#662]
**Is your feature request related to a problem? Please describe.**

When watching a video without interacting with it for long enough, the screen gets black (I set a relatively short system wide timeout).

**Describe the solution you'd like**

Many video players on several platforms prevent the screen to power down while playing a video, regardless of the system settings, it would be nice if aves did the same.
(I couldn't find a setting to enable this if it is possible already)

**Comment by deckerst** [comment]
You could try `Settings` > `Navigation` > `Keep screen on` and select `During video playback` (or `Viewer page only`). Let me know whether that works for you.

**Comment by glemco** [comment]
Thanks, don't know how I definitely overlookeed it, my bad!
(I don't find it so intuitive to have it under _Navigation_, rather than under _Screen_ or other sub-menus though. But I think that can be strongly subjective)
