### ISSUE TITLE
Ability to add package name of editing app

### ISSUE THREAD

**Issue by Tanmandal** [deckerst/aves#664]
When I press the edit icon a menu appears which shows all the available picture editors in my phone but  I use 1 of them most of the time so it would be nice if in the settings I could add the package name of the editor app I mostly use and when I press the edit button it directly opens that app

**Comment by deckerst** [comment]
You should be able to directly do it from the OS dialog, by selecting "always".

![Screenshot_20230615_142825_Android System](https://github.com/deckerst/aves/assets/13898333/74338a15-a749-407f-b39a-ac3b8b8cf13d)

**Comment by Tanmandal** [comment]
I am not getting the always option
![Screenshot_2023-06-16-01-11-23-670_android](https://github.com/deckerst/aves/assets/93572359/021f3e07-8034-40e6-85c5-017f5c5082d1)

**Comment by deckerst** [comment]
Are you using a very old Android? Or a custom rom maybe?

In any case, that's up to your device environment. The app is already doing what needs to be done.

**Comment by Tanmandal** [comment]
No its Android 12 and MIUI but I am having the same issue on oxygen os running android 11
