### ISSUE TITLE
Favorite pictures are not remembered. 

### ISSUE THREAD

**Issue by ThomasLeigh** [deckerst/aves#669]
**Describe the bug**
Pictures marked as Favorite are not remembered -  and change in time when new pictures are added into their folder. 

**To Reproduce**
1. Mark a picture as a Favorite (the heart icon) - e.g., from the screenshots folder. 
2. Make new screenshots to add new files in the screenshots folder. 
3. Relaunch the app.
4. See that the favourite picture is not the same as You've marked before.

**Expected behavior**
The picture once marked as Favourite should stay the same on the Favourite bookmark.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.8.9-libre, build 10002
Flutter: stable 3.10.3
Android version: 10, API 29
Android build: QKQ1.190910.002 V12.5.1.0.QFGEUXM
Device: Xiaomi Redmi Note 7
Geocoder: ready
Mobile services: not available
System locales: en_AU
Storage volumes: /storage/emulated/0/, /storage/75F7-14F9/
Storage grants: 
Error reporting: false

**Comment by deckerst** [comment]
I've just tried and I can't reproduce the issue.

Does it reliably happen all the time when following the steps you highlighted above, or does it happen randomly?
Could you take a screen recording showing the issue and attach/link the video here?
Could you please save logs (from `About` > `Bug Report`) and attach them here?
