### ISSUE TITLE
Aspect ratio (mosaic) layout

### ISSUE THREAD

**Issue by deckerst** [deckerst/aves#67]
### Discussed in https://github.com/deckerst/aves/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **quantified1995** August 31, 2021</sup>
One of the best but rarely seen features of gallery apps is the ability to display photos in their original aspect ratio or what some call Mosaic layout. Some apps that employ this are Google photos, Samsung gallery, and recently the gallery x app on the Play store (no tagging or metadata system, definitely not feature rich). Would it be possible to allow photos to be shown this way? Would love to see it!</div>

**Comment by Donkey-Doug** [comment]
Example:
![image](https://user-images.githubusercontent.com/50382414/135726071-58954e43-c6da-48a0-a764-b69c5fe4bf25.png)

**Comment by Ilithy** [comment]
A really greatest feature <3
