### ISSUE TITLE
Converted Image From Batch Came Out As 0 Bytes

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#671]
**Describe the bug**
I did a few batch conversions that were successful with one image (out of 100+) that appears to be 0 bytes.
The odds are way better than last time, but I figured I should do the usual reporting in case it's indicatave of a deeper issue and not just a fluke.

**To Reproduce**
All I did was a large batch conversion of images (various-to-jpeg 96 quality).

**Screenshots**
It just gives the "Oops (!)" Screen in fullview and "Jpeg" on the thumbnail. Info has correct information about the file name, but says it is 0 bytes.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: dev.imranr.obtainium
Aves version: 1.8.9-libre, build 10002
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: lineage_ocean-userdebug 13 TQ2A.230505.002 eng.root.20230607.204517 dev-keys
Device: motorola moto g(7) power
Geocoder: ready
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/3062-3833/
Storage grants: /storage/emulated/0/Movies/, /storage/3062-3833/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/3062-3833/Pictures/, /storage/emulated/0/Download/Pixel 4 Downloads and Photos/, /storage/emulated/0/Download/Image Converter/
Error reporting: false
[aves-logs-20230621_202343.txt](https://github.com/deckerst/aves/files/11828377/aves-logs-20230621_202343.txt)

**Additional context**
This has happened a time or two in the past and I just got around it by redownloading the file. But, I can't see a specific pattern to what kinds of files or anything else.

**Comment by deckerst** [comment]
For the image that failed to convert, did you retry to convert the same image and it worked?

I'm trying to reproduce the issue by converting several hundreds of images at once but I can't reproduce the issue. I wonder whether it depends on the image, or the running environment (for example low memory, or low storage), or the OS, or something else.

Do you use a regular Lineage or some derivative? Do you enable some special memory or security features?

**Comment by OkyDooky** [comment]
It might be related to low storage. This last time, it was the last file output from the converter, so it could be that it "finished operation" but couldn't write all the information it actually needed to. And I did that conversion to try to help free up space, so it may have filled too much space before I could remove the original files.
And my Lineage is the MicroG build of the stable releases. No special developer options tweaked, especially not with regards to memory.

**Comment by OkyDooky** [comment]
For an update: I haven't encountered this particular issue since, on any of the devices I use Aves with. So, it is very likely just because of the available storage space running out.
I guess it's not a bug, then. But it could benefit from intelligently responding to this by stopping operations at the last successful output and inform the user about the error (Warning/Error: Could not complete operation. Reason: insufficient storage.)
