### ISSUE TITLE
Description missing

### ISSUE THREAD

**Issue by BenVB1** [deckerst/aves#672]
Title and description entry. Title shows fine, but description is no longer displayed. Both new & existing entries are affected.

**Comment by deckerst** [comment]
Please paste your system environment and logs from `About` > `Bug Report`.

Also, please attach here a sample item with a description that does not appear.

By the way, have you double-checked the relevant settings: `Settings` > `Viewer` > `Overlay` > `Show description`?

**Comment by BenVB1** [comment]
Oops. It was the setting in the overlay options. Which is strange, because
I never touched those.
Still, at least that resolved it. Thank you for taking the time to correct
it Thibault.

Best regards, Ben
