### ISSUE TITLE
Exporting without metadata

### ISSUE THREAD

**Issue by noearchimede** [deckerst/aves#675]
Since I started using Aves, I have been increasingly relying on metadata to organize my photo collection (with titles/captions, tags, ...).
However when I share pictures with other people I'd usually like to remove most metadata, either for privacy (e.g. in the case of GPS data) or simply because my "custom" metadata such as tags is only relevant in the context lf my own photo collection.

I think it would be useful to have an option to export pictures without metadata. I'm aware of the "convert" option, which lets the user choose whether to include metadata in the exported file, but I think it would be nice to have that option also for exporting the original image (i.e. without recompression or change of format).

Additionally I would also find it very useful if such a new "export without metadata" menu offered a choice of removing some metadata while keeping some other. For example in my personal workflow I'd often like to share a picture with most EXIF metadata, including in particular camera-related information (camera type, shutter speed, ISO, ...), GPS coordinates and any embedded color profile, but without stuff relating to my photo collection, such as tags, captions, star ratings, "face tags" (i.e. the names of people in the picture, which is not a feature of Aves but might be added to the metadata using other apps).
However, since as far as I know there is no unique standard on how to store e.g. tags in JPEG metadata, I don't know if there is a sensible way to implement this.

My current workaround relies on the existing "remove metadata" option: I create a copy of all of the pictures I want to export, I remove their metadata, I share them and then I delete the copies without metadata. However this workflow is rather cumbersome, and it is also relatively easy to mix things up and accidentally share the copy with metadata or keep the one without. Also there is no way to selectively delete unwanted metadata while keeping the rest.

**Comment by deckerst** [comment]
Agreed. This is actually the kind of things i intend to do as part of this:
- #10

Refining what kind of metadata to keep/remove is possible, but i'd like to keep a balance between being flexible and newbie friendly.
