### ISSUE TITLE
Make Temporary Warning Messages More Alerting

### ISSUE THREAD

**Issue by OkyDooky** [deckerst/aves#676]
**Is your feature request related to a problem? Please describe.**
I just had completed a batch conversion of a decently large number of images and noticed that the pop-up message near the bottom said "(X) Image(s) Didn't Convert: Show" right about the time it disappeared. I thought it was the usual success message and was prompting me to show the results and I was going to ignore it like usual.

**Describe the solution you'd like**
A change in either the text or the banner behind it to be more alerting when the message is notifying the user about an error. It could be a change in color, for instance (orange, red, etc.)

**Describe alternatives you've considered**
I guess I could change the setting "Time to Take Action" to a higher number and just swipe away messages I know are good. But, having a more alerting error message helps interrupt any muscle memory or habits that could ignore important information

**Additional context**
Since this was a large-ish conversion batch and it was like 1 image that didn't convert, I will have a hard time manually checking (eyeballing) which one it is.
That's one of the situations I'm hoping this could avoid.

**Comment by deckerst** [comment]
I agree with you about giving a clue that this is a warning rather than the usual success message.

That said, it wouldn't have helped you in this case to identify the missed media, because the "show" action would still show the successfully converted media.

**Comment by OkyDooky** [comment]
Ah. Thanks for the clarification.
