### ISSUE TITLE
Use `media_kit` to play videos

### ISSUE THREAD

**Issue by deckerst** [deckerst/aves#678]
(originally explored as part of #555)

The good:
- improved seek accuracy (fixing #660 and making it possible to implement #262),
- improved looping transition (but not fixing #356, cf https://github.com/alexmercerind/media_kit/issues/150 https://github.com/mpv-player/mpv/pull/10748),
- improved speed selection (works fine at least from x0.25 to x4,
- HDR support (fixing #486),
- AV1 support (fixing #555),
- some corrupted videos become playable (e.g. mp4 with inconsistent duration in their metadata).

The bad:
- often fails to load the first frame of local videos (cf https://github.com/media-kit/media-kit/issues/339)

<table>
  <tr>
    <th>Flavor</th>
    <th>Package</th>
    <th>media_kit<br/>v1.1.1<br/>+ ffmpeg_kit<br/>v5.1.0-LTS (min)</th>
    <th>media_kit<br/>v1.1.1<br/>+ ijk</th>
    <th>ijk<br/>only</th>
  </tr>
  <tr><td>play</td><td>aab</td><td>83.6</td><td>63.7</td><td>47.4</td></tr>
  <tr><td>izzy</td><td>armeabi-v7a</td><td>34.2</td><td>23.1</td><td>18.1</td></tr>
  <tr><td>izzy</td><td>arm64-v8a</td><td>27.5</td><td>23.1</td><td>17.9</td></tr>
  <tr><td>izzy</td><td>x86_64</td><td>29.3</td><td>24.7</td><td>18.7</td></tr>
</table>

**Comment by deckerst** [comment]
@alexmercerind

1) subtitles

- Using the subtitle stream works fine, but the stream only contains the unstyled text. Not a big deal, but it's a step down from the subtitle stream I was receiving from `ijkplayer`, where things like `bold`, `italics`, etc. was inlined with the text.

- I currently style `SubtitleViewConfiguration` with a transparent color to hide the embedded subtitle view, but it would be cleaner if there was a way to remove the `SubtitleView` from the widget tree altogether (and without using `libass`).

2) screenshot

It works fine!

3) codec selection

I appreciate that you reduced the library size by tightening the codec selection. However, I can no longer play some of my video/audio streams (e.g. avi, ac3). Is it possible for consuming apps to customize which codecs are bundled? Should I rebuild mpv, and then fork media_kit to point to that custom build? 

4) errors

- I get the following exception when destroying video views (loaded from Android content URIs). It seems `final fd = int.parse(data.pathSegments.last)` is assuming `pathSegments` are not empty. But it may be a deeper issue.
```
E/flutter ( 3507): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter ( 3507): #0      _Array.last (dart:core-patch/array.dart:56:5)
E/flutter ( 3507): #1      Media._finalizer.<anonymous closure> (package:media_kit/src/models/media/media_native.dart:47:48)
E/flutter ( 3507): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter ( 3507): #3      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1633:26)
E/flutter ( 3507): #4      _FinalizerImpl._runFinalizers (dart:core-patch/finalizer_patch.dart:63:18)
E/flutter ( 3507): #5      _FinalizerImpl._handleFinalizerMessage (dart:core-patch/finalizer_patch.dart:76:15)
```

- last but not least, I can still make my app crash by quickly going through my videos (after about 30 videos? maybe related to the dispose cleanup issue above). I'm willing to provide additional details, just let me know how I can help you debug this.

**Comment by alexmercerind** [comment]
[Replacing `mediacodec` to `mediacodec-copy` can improve stability ot some degree](https://github.com/alexmercerind/media_kit/blob/6d0f0401b8d87596a6167fd629912cff92003edc/media_kit_video/lib/src/video_controller/android_video_controller/real.dart#L200). The `VideoControllerConfiguration` allows this. An overall efficient approach will be to reuse existing `Player`s (if possible).

I'll have a look at the rest. I possibly messed up the `Media` GC finalizer.

**Comment by alexmercerind** [comment]
[I did enable AVI](https://github.com/media-kit/libmpv-android-video-build/blob/42772c7c856ec17def6e94cb818058d19a9c6bef/buildscripts/scripts/ffmpeg.sh#L140). Something seems missing.

**Comment by deckerst** [comment]
> [I did enable AVI](https://github.com/media-kit/libmpv-android-video-build/blob/42772c7c856ec17def6e94cb818058d19a9c6bef/buildscripts/scripts/ffmpeg.sh#L140). Something seems missing.
> 
> EDIT: An AVI sample I grabbed does play.

My bad, I was imprecise: the AVI container I tried contained an `MJPEG` video stream. This is niche, but useful to me. Your codec selection is reasonable for most users, that's why I was asking how to customize it for my needs.

**Comment by alexmercerind** [comment]
You can create your own builds for libmpv + FFmpeg + media_kit by:

1. Fork https://github.com/media-kit/libmpv-android-video-build & enable GitHub actions.
2. Modify the FFmpeg [`configure` step](https://github.com/media-kit/libmpv-android-video-build/blob/42772c7c856ec17def6e94cb818058d19a9c6bef/buildscripts/scripts/ffmpeg.sh#L31-L202).
  It may look overwhelming (it is in-fact). Mostly you need to only look at the `--enable-decoder`, `--enable-demuxer` & `--enable-parser` for your codec selection; other things are configured already.
3. The GitHub actions will compile the project(s) & resulting binaries will be automatically uploaded as release & artifact.
4. Remove `media_kit_libs_android_video` from `pubspec.yaml`.
5. Bundle your *.jar(s) with your application by modifying `build.gradle`, [something like this](https://github.com/alexmercerind/media_kit/blob/6d0f0401b8d87596a6167fd629912cff92003edc/media_kit_libs_android_video/android/build.gradle#L50-L224).

**Comment by alexmercerind** [comment]
I picked the FFmpeg configuration from fijkplayer; kind of surprising things are different. Still, you have the freedom.

**Comment by deckerst** [comment]
> I picked the FFmpeg configuration from fijkplayer; kind of surprising things are different. Still, you have the freedom.

I customized the FFmpeg config for Aves, so it's not the same as the basic fijkplayer.

**Comment by alexmercerind** [comment]
Interesting.

**Comment by deckerst** [comment]
> we are encoding pixel-buffer with package:image

I noticed that the screenshot function is a tad slow. Not a big deal, but maybe it's because you use `package:image`, which is pure dart and usually slower compared to native encoders. That package is actually more suitable for server usage, or when performance are no concern. On Android for example, you may use instead `android.graphics.Bitmap` and its `compress(Bitmap.CompressFormat.JPEG, ...)`.

**Comment by alexmercerind** [comment]
It runs on another `Isolate`, so it may be slow (but definitely **non-blocking** unlike native interop); portable too.

The performance isn't really crucial for screenshots (not at all). When we want hardware-level performance at the time of rendering, we don't even use pixel buffers.

**Comment by deckerst** [comment]
I was not talking about native in the sense of FFI, but rather to use Android JPEG encoder instead of the slow `package:image`. And of course it's non-blocking when done on the appropriate threads, but being slow means you don't know whether it worked successfully after a long time.

**Comment by alexmercerind** [comment]
The performance gain from using the Android JPEG encoder may be lesser than sending pixel-buffer across platform-channels/FFI & then receiving back encoded image buffer.

[`screenshot-to-file`](https://mpv.io/manual/stable/#command-interface-screenshot-to-file) will use FFmpeg. I'm not really going to invest time into this at the moment.

**Comment by Quackdoc** [comment]
do you have a sample mkv that is unplayable that you would be willing to share? I have not been able to replicate the issue.

**Comment by deckerst** [comment]
@Quackdoc please contact me by [email](mailto:gallery.aves@gmail.com). By the way, that video does not play well with the vanilla MPV player app either.

**Comment by alexmercerind** [comment]
Hi!

Apologies for the day; catching up again.

- [The file-descriptor `close` crash should now be resolved](https://github.com/alexmercerind/media_kit/issues/286).
- [I added the codecs you specified above & few more to package:media_kit_libs_android_video itself](https://github.com/media-kit/libmpv-android-video-build/releases/tag/v1.0.0).

I think it's all green now. This update will make a lot of things better (esp. for Android).

**Comment by alexmercerind** [comment]
I monitored the `screenshot` performance:

I can make it use a native C/C++ JPEG/PNG encoder based on [stb_image](https://github.com/nothings/stb/blob/master/stb_image.h) if you wish.
For the time being, I exposed raw pixel-buffer which you can use to manually encode (`main` branch).

```bash
pixel-buffer = 57ms
pixel-buffer = 21ms
pixel-buffer = 35ms
pixel-buffer = 36ms
pixel-buffer = 34ms
pixel-buffer = 33ms
pixel-buffer = 30ms
pixel-buffer = 39ms
pixel-buffer = 30ms
pixel-buffer = 41ms
JPEG         = 525ms
JPEG         = 489ms
JPEG         = 442ms
JPEG         = 481ms
JPEG         = 385ms
JPEG         = 369ms
JPEG         = 381ms
JPEG         = 425ms
JPEG         = 451ms
JPEG         = 403ms
PNG          = 2679ms
PNG          = 3392ms
PNG          = 3211ms
PNG          = 2814ms
PNG          = 2713ms
PNG          = 2759ms
PNG          = 2559ms
PNG          = 2156ms
PNG          = 2394ms
PNG          = 2441ms
```

**Comment by alexmercerind** [comment]
What kind of additional metadata are you exactly looking for?

**Comment by deckerst** [comment]
Am i looking for additional metadata? What makes you ask this?

At this stage, the last hurdle with your library is that the first frame of each video is a plain solid color frame, but that aside I'm quite happy with your library!

**Comment by alexmercerind** [comment]
I mean why do you require separate FFmpeg or IJK?

Yeah, I also saw that issue on Android. I thought it was resolved after this:

> At this stage, the last hurdle with your library is that the first frame of each video is a plain solid color frame.

https://github.com/media-kit/media-kit/blob/5ea2c84b5c7b074a45b3887dc64a997f9a5e3172/media_kit_video/lib/src/video_controller/android_video_controller/real.dart#L146-L148

**Comment by deckerst** [comment]
> I mean why do you require separate FFmpeg or IJK?

Aves shows stream details, etc. It's not just a viewer.

> https://github.com/media-kit/media-kit/blob/5ea2c84b5c7b074a45b3887dc64a997f9a5e3172/media_kit_video/lib/src/video_controller/android_video_controller/real.dart#L146-L148

I don't mind the delay, but couldn't the surface be transparent while it's initializing?

**Comment by alexmercerind** [comment]
You mean that solid color is black (or ?)

**Comment by alexmercerind** [comment]
I mean it should be possible to show stream details within media_kit. There's a large list of properties:
https://mpv.io/manual/stable/

**Comment by deckerst** [comment]
> You mean that solid color is black (or ?)

No, it depends on the video. When the player initializes, it shows as the first frame a solid color which can be pink, brown, purple, etc. It seems derived from the video, and it's always the same color for a given video.

> I mean it should be possible to show stream details within media_kit.

Maybe it's possible with MPV, but I didn't see an API in your package to retrieve the same info as I get from ffprobe.

Also, I don't need it now but ffmpeg kit could allow Aves to edit videos someday.

**Comment by alexmercerind** [comment]
Just try to increase that delay & provide me with a value that works fine. That will avoid that first glitchy frame.

I personally don't see that first uni-color 1x1 texture frame after that delay.

**Comment by deckerst** [comment]
Cf https://github.com/media-kit/media-kit/issues/339

**Comment by alexmercerind** [comment]
I'd be really glad if we're able to avoid package:ffmpeg_kit_flutter. Is it really a good deal for it's size?

**Comment by deckerst** [comment]
I am just a consumer of `media_kit`. If its API allows probing and editing like `ffmpeg_kit_flutter` I won't have to use that package, but until then I do. Please do not get distracted with Aves needs, and follow your own roadmap.

**Comment by alexmercerind** [comment]
It won't really take much effort from my end to expose an API that allows listening to native property changes like [we already provide an API to make native property changes](https://github.com/media-kit/media-kit/issues/129#issuecomment-1508019709). It'd be up to you whichever you wish to listen to & display (but you have to find them out).

<hr>

The ultimate goal of `media_kit` is to meet the community's demands.

Our new Android support has been well-tested by your project & now it is at its sweet spot. This stability can now be enjoyed by others, that's open-source. From a personal usage stand-point, I only created package:media_kit for my music app & wasn't even going to add video support.

Lastly, public contributions are also welcomed :)

<hr>

At your project level, you may even consider forking our media-kit/libmpv-android-video-build & create a build which dynamically links to FFmpeg (instead of static, like we have to avoid conflicts). Then, you can use that "shared" FFmpeg to query metadata (while it'll be used by media_kit too). With our compilation optimizations in-place, the resulting bundle size is also decent (~5 MB for ARM64).

**Comment by alexmercerind** [comment]
Few more updates on my part:

- [**#350 :** feat: `NativePlayer.observeProperty` & `NativePlayer.unobserveProperty`](https://github.com/media-kit/media-kit/pull/350)

For allowing you to listen to custom properties.

```dart
import 'package:media_kit/media_kit.dart';

Future<void> main() async {
  MediaKit.ensureInitialized();
  final player = Player();
  await (player.platform as NativePlayer).observeProperty(
    'demuxer-cache-state',
    (data) async {
      print(data);
    },
  );
  await player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
}
```

- [**#355 :** https://github.com/media-kit/media-kit/pull/355](https://github.com/media-kit/media-kit/pull/355)

Fixed support for AV1.

- [**#358 :** feat: `VideoTrack`/`AudioTrack`/`SubtitleTrack` expose more parameters](https://github.com/media-kit/media-kit/pull/358)

```
VideoTrack(auto, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(no, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(1, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 1920, h: 1080, channelscount: null, channels: null, samplerate: null, fps: 60.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(2, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 1280, h: 720, channelscount: null, channels: null, samplerate: null, fps: 60.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(3, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 854, h: 480, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(4, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 640, h: 360, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(5, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 426, h: 240, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(6, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 256, h: 144, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(7, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 256, h: 144, channelscount: null, channels: null, samplerate: null, fps: 15.0, bitrate: null, rotate: null, par: null, audiochannels: null)
AudioTrack(auto, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
AudioTrack(no, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
AudioTrack(1, null, null, image: false, albumart: false, codec: aac, decoder: null, w: null, h: null, channelscount: 2, channels: stereo, samplerate: 44100, fps: null, bitrate: 1172, rotate: null, par: null, audiochannels: 2)
AudioTrack(2, null, null, image: false, albumart: false, codec: aac, decoder: null, w: null, h: null, channelscount: 2, channels: stereo, samplerate: 44100, fps: null, bitrate: 443, rotate: null, par: null, audiochannels: 2)
AudioTrack(3, null, null, image: false, albumart: false, codec: aac, decoder: null, w: null, h: null, channelscount: 2, channels: stereo, samplerate: 44100, fps: null, bitrate: 278, rotate: null, par: null, audiochannels: 2)
SubtitleTrack(auto, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
SubtitleTrack(no, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
```
