### ISSUE TITLE
Long press again to multi select

### ISSUE THREAD

**Issue by Turhvjbufv** [deckerst/aves#682]
**Is your feature request related to a problem? Please describe.**

When I need to select a bunch of files that are next to each other and I need to press on each and every one of them 

**Describe the solution you'd like**

I would like the feature that When you have already selected an item, you can long press another item and it will select all the items between them(kinda like when you press "shift" and another item in windows), this would make it so much easier.

**Comment by deckerst** [comment]
> I need to press on each and every one of them

Not so. You can long press, then drag, to select (or deselect) a range of items quickly.

But I don't intend to implement the particular solution you suggested. It's been suggested before, actually.
