### ISSUE TITLE
Support artist tag

### ISSUE THREAD

**Issue by lyaaz** [deckerst/aves#683]
**Is your feature request related to a problem? Please describe.**
I have lots of pictures downloaded from the internet, which have artist tags, but Aves can't display these tags or search by artist yet. 

**Describe the solution you'd like**
Allow display artist tag just like other tags, and also can search or modify.

**Additional context**
I have found two related exif tags: `Artist` and `XPAuthor`

**Comment by deckerst** [comment]
Similar to other minor tags, like the `model`, I don't intend to include them like I do for the major ones. Reasons here:
- #424

That said, I'd like to find a way to let users add custom tags of interest for the app to scan and register.
