### ISSUE TITLE
Change number of columns and universal tags

### ISSUE THREAD

**Issue by reitenth** [deckerst/aves#690]
**Describe the solution you'd like**
1. I would like a way to change from 4 columns to 3 for example. 
2. It seems to me that tags are all local. It would be nice if a picture is tagged in Windows, it follows it and automatically uses that.

**Comment by deckerst** [comment]
1. [You already can](https://github.com/deckerst/aves/wiki/FAQ#can-i-change-the-size-of-thumbnails).
2. [It already uses standard XMP tags](https://github.com/deckerst/aves/wiki/Support:-Metadata-editing). They are not local in a private database, they are embedded within the files themselves.
