### ISSUE TITLE
Sort by distance

### ISSUE THREAD

**Issue by HannesGitH** [deckerst/aves#693]
**Is your feature request related to a problem? Please describe.**
When being somewhere you've already been near to (in holidays) and you want to show people the photos you took last time. Its very hard to find them in any gallery app if you don't know the date you've been there last time.

**Describe the solution you'd like**
Sorting the files by distance (of associated geo metatag to current position (or a custom one when using search)) would fix this and be some cool new way of exploring old photos anywhere you go.

**Describe alternatives you've considered**
well.. i cant think of any, that was a spontanous idea i had when i wanted to show my great parents photos i took at there place when i last visited.

**Additional context**
if you want to i might be able to help with a PR

**Comment by deckerst** [comment]
Have you tried the filter at the top of the map page? It seems to me like one solution to what you want to achieve.

Let me know if you don't see what I'm talking about!

**Comment by HannesGitH** [comment]
thats pretty close, didnt know thats more than a title but filter button! thx

its only a filter thought not exactly the sort-by-distance feature i had in mind, but it solves this use case as well
