### ISSUE TITLE
offline open street map

### ISSUE THREAD

**Issue by Yaniv125** [deckerst/aves#695]
Hi

It will be nice if we could view photos on the map at places with no internet connection, this will also improves private

**Comment by deckerst** [comment]
Are you proposing that Aves downloads maps from servers that allow that, and then store these maps on the user's device? If so, i do not intend to do that.

But i know that users who use alternatives to Google Mobile Services (like microG) can redirect Google Maps access to the service they want, so they could use an offline OSM service.
