### ISSUE TITLE
Motion photo screen jitter

### ISSUE THREAD

**Issue by r6fgu** [deckerst/aves#696]
**Describe the bug**

Upon opening a motion photo, immediately prior to playing the clip, the entire screen flashes a portion of the clip.

**To Reproduce**
1. Set to autoplay motion photos.
2. Open motion photo.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.looker.droidify
Aves version: 1.8.9-libre, build 10002
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: TQ3A.230705.001
Device: Google Pixel 7 Pro
Geocoder: ready
Mobile services: not available
System locales: en_GB
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

[Logs](https://anonfiles.com/ia08fa53ze/aves_logs_20230729_210359_txt)

**Comment by deckerst** [comment]
Thanks for the report. Actually I've already noticed this and fixed it, but it's not released yet (I'm considering another video engine and need to see how it works out before releasing).
