### ISSUE TITLE
Open location in a maps app

### ISSUE THREAD

**Issue by tsiflimagas** [deckerst/aves#697]
**Is your feature request related to a problem? Please describe.**
I wouldn't really call it a problem, more like a wish. It happened to me a couple of times I wanted to navigate to a place based on the location provided by the photo, as it was the only piece of information linking me to it. The map provided in the app is already quite nice and useful, but it sometimes could fall short if you actually want to use it to move to the location using it. It's not its primary purpose anyway, I guess.

**Describe the solution you'd like**
I'd like to have a button to open the location in a maps app, like OrganicMaps etc.

**Comment by deckerst** [comment]
You can already do so via the viewer `...` menu > `Export` > `Show in map app`.

**Comment by tsiflimagas** [comment]
Ah damn, I missed that. I guess I didn't expect to find it there. Anyway, good that my request was already resolved 😄
