### ISSUE TITLE
Spoiler 

### ISSUE THREAD

**Issue by HalfBloodprinc3** [deckerst/aves#699]
Can you guys implement the feature which allows the user to select one or more than one folder and the content of that selected folders can be seen in the main home page but in the spoiler format. Spoiler means, like in reddit,all NSFW content is blurred. But in this app, not only Just NSFW, but all types of photos or videos that the user wants to access efficiently but don't want to show it to others. 
If this function is implemented in the app then I think it would be more secure to access the gallery in public areas.

**Comment by deckerst** [comment]
It's not what your suggesting, but for that use case, you should try creating a "vault". It's just like an album but content is protected by a lock.
