### ISSUE TITLE
Aves

### ISSUE THREAD

**Issue by Fabiofct** [deckerst/aves#703]
Hi
It seems aves gallery app does not reproduce the most of my MP4 video recorded before having installed aves app on Cell phone.

If I open video with another app (eg Google foto) It works.

Thanks
Fabio

**Comment by deckerst** [comment]
[Your issue does not follow the rules](https://github.com/deckerst/aves/issues/234). Also, I don't understand what you wrote, you'll have to explain better if you expect me to take a look.

**Comment by Fabiofct** [comment]
Do you know why aves cannot play MP4 files?
Thanks 
 
 
  Il mar, 1 ago, 2023 alle 19:33, Thibault ***@***.***> ha scritto:   


Your issue does not follow the rules. Also, I don't understand what you wrote, you'll have to explain better if you expect me to take a look.

**Comment by deckerst** [comment]
What do you mean "cannot play"? Do they appear in the collection? Do they appear but when you start playing them you get "oops"? Do you get audio only? video only? What's the MP4 video/audio codecs used? Do you have a sample video?...
If you don't put any effort in explaining your issue, I won't try harder either.
