### ISSUE TITLE
Sort by date saved and or date modified.

### ISSUE THREAD

**Issue by Gatoz97** [deckerst/aves#708]
**Is your feature request related to a problem? Please describe.**
Only option for date sorting is date of file creation. Not very useful.

**Describe the solution you'd like**
Give us more options for file date sorting, like sorting by date modified ideally like in Samsung's gallery.

**Describe alternatives you've considered**
Sorting by date saved could also work.

**Additional context**
The more options the better. The app is already phenomenal but some pictures get lost in my large albums because they were saved or created long time ago.

**Comment by deckerst** [comment]
Duplicate:
- #97 

> The more options the better

I disagree. Complexity has a cost.
