### ISSUE TITLE
Viewer - Quick Actions

### ISSUE THREAD

**Issue by Lorestan00** [deckerst/aves#711]
**Is your feature request related to a problem? 
It would be great to reduce the steps it takes to set wallpaper. At the moment you have to go to quick actions in the viewer then click three dots then export then set as then pick a program to set wallpaper 

**Describe the solution you'd like**
Two points on this. 

Firstly add a quick action called set wallpaper. So immediately you can cut out two steps (click three dots then export)

Secondly ideally rather than use another app set wallpaper sets the wallpaper with an option for home screen, lockscreen or both. 

Perhaps retain the current workflow for those who want to use other programs to set wallpaper

**Additional context**
Really would speed things up massively

**Comment by deckerst** [comment]
All true, but I'm surprised you need quick access to it. Do you often change your wallpaper?

**Comment by Lorestan00** [comment]
Not that often. Just every time I do I find it annoying :)
