### ISSUE TITLE
images or photos deleted with another application still appear in the application

### ISSUE THREAD

**Issue by franco27** [deckerst/aves#712]
Hello

I cleaned and sorted my images and photos with Ccleaner.
I have a large quantity.

And now in the gallery of your application, replacing the deleted photos or images, I have an image with a logo (the thumbnail ) (see screenshots) and when I click on it, the display is done with writes "file does not exist".

To try and fix the problem, I clicked refresh gallery or rescan. (see screenshot, I circled the menu)
After this task, I still see the deleted photos or images.

I hope you will be able to fix this problem. Obviously if you want additional information I am here to answer it.

I give you the system information of my phone. 
Xiaomi Redmi 8
Android Version 10 Android 10
MIUI V12.5.2.0.QCNEUXM

Architecture 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm® Snapdragon™ 439

CPU 4 x Cortex-A53
Cores 8
RAM size 4 GB

![Screenshot_2023-08-15-19-44-47-436_deckers.thibault.aves.jpg](https://github.com/deckerst/aves/assets/31793920/cb205352-6191-4750-b81a-f893a6097f7b)

![IMG_20230815_194929.jpg](https://github.com/deckerst/aves/assets/31793920/6533df1f-25cc-45a1-a44b-4f967838fe83)

![Screenshot_2023-08-15-19-45-06-604_deckers.thibault.aves.jpg](https://github.com/deckerst/aves/assets/31793920/14fca870-8209-4ecd-8d2e-848b61d4fc6b)

![Screenshot_2023-08-15-21-23-39-133_deckers.thibault.aves.jpg](https://github.com/deckerst/aves/assets/31793920/9db914ed-5c25-4cc8-a220-f2e67950e698)

**Comment by deckerst** [comment]
Thanks for the report, but it's a known problem when using a bad app:
https://github.com/deckerst/aves/wiki/FAQ#why-does-aves-show-thumbnails-with-a-broken-image-symbol

Instead of using Ccleaner, I suggest you use an app that respects the system Media Store when dealing with media files.

Once you have obsolete items, you could restart your device to make the Media Store update and remove these items.

**Comment by franco27** [comment]
thank you for your reply.
I will look for another application that is able to view a photo and keeping selected images checked
