### ISSUE TITLE
Creating a Default Photo Editor

### ISSUE THREAD

**Issue by RickAust** [deckerst/aves#714]
**Describe the bug**
I can't find the section in settings to change the default photo #editor. 

**To Reproduce**
When I edit a photo, there's an "I" icon there that says I can change in the apps section of Settings. The `problem` is that I have no apps section in Settings.

**Expected behavior**
Just want to create a default editor.

**Screenshots**
If applicable, 
[aves-logs-20230818_120616.txt](https://github.com/deckerst/aves/files/12377037/aves-logs-20230818_120616.txt)
![Screenshot_20230818_120403_Android System](https://github.com/deckerst/aves/assets/56009454/d1b14ad9-730f-4a74-ae51-6edd013129e7)
![Screenshot_20230818_120525_Aves](https://github.com/deckerst/aves/assets/56009454/7d7f85a9-3297-40fa-8daa-ab1a09f678f3)
 email](mailto:gallery.aves@gmail.com).

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.8.9-play, build 100
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: TP1A.220624.014.G988NKSU3IWE1
Device: samsung SM-G988N
Geocoder: ready
Mobile services: ready
System locales: en_GB
Storage volumes: /storage/emulated/0/, /storage/EAD4-A932/
Storage grants: 
Error reporting: false

**Additional context**

**Comment by deckerst** [comment]
> When I edit a photo, there's an "I" icon there that says I can change in the apps section of Settings. The problem is that I have no apps section in Settings.

This is an Android system dialog. They're referring to the Android settings, not Aves settings.

**Comment by RickAust** [comment]
I wondered if that might be the case but I don't have this option under
phone settings either.
Anyway, thanks for the clarification.

**Comment by deckerst** [comment]
![Screenshot_20230818_114913_Settings](https://github.com/deckerst/aves/assets/13898333/9df4964e-1f05-4eb3-a9d7-2d9af4d53cac)
