### ISSUE TITLE
Adding tags to any mp4 file with multiple MDATs always corrupts them

### ISSUE THREAD

**Issue by rewrib** [deckerst/aves#716]
**Describe the bug**
If you try to add tags to any mp4, that contains multiple MDATs, the app will corrupt this file and it becomes unplayable.

**To Reproduce**
1. Get a mp4 with multiple mdats (the online video downloader "rapidsave" creates this type of file in some cases for example)
2. Add tags through Aves
3. Video becomes unplayable and corrupt after this

**Expected behavior**
Either refuse to add tags to mp4 files with multiple mdats, or the app should find a way to add the tags correctly.

**System information and logs:**

Package: deckers.thibault.aves
Installer: com.looker.droidify
Aves version: 1.8.9-izzy, build 10001
Flutter: stable 3.10.3
Android version: 10, API 29
Android build: QP1A.190711.020.G960FXXUHFVG4
Device: samsung SM-G960F
Geocoder: ready
Mobile services: ready
System locales: en_US, de_DE
Storage volumes: /storage/emulated/150/
Storage grants: 
Error reporting: false
 
[aves-logs-20230819_040728.txt](https://github.com/deckerst/aves/files/12384828/aves-logs-20230819_040728.txt)

**Comment by deckerst** [comment]
Thanks for the report. Could you please provide a sample file with multiple mdat?

**Comment by rewrib** [comment]
https://send.bitwarden.com/#4rss-Pe6Ckyf1bBkAJ9e-Q/NtyKwh6i2uOFPvwTY2xCsQ

If you want, I can also send you it through email.

**Comment by deckerst** [comment]
Thanks for the sample.

For now, I "fixed" this by making Aves fail when trying to edit a fragmented mp4.

In the future, I intend to switch to ffmpeg for video edition, which should be more robust and versatile.
