### ISSUE TITLE
paypal link on fdroid metadata

### ISSUE THREAD

**Issue by jindam-vani** [deckerst/aves#718]
@deckerst 
* **without your explicit consent** paypal link ```https://www.paypal.com/donate/?hosted_button_id=RWKQ4J7D8USX6``` given in https://github.com/deckerst/aves#donations was replaced by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/deckers.thibault.aves.libre.yml)
* paypal link updated in fdroid metadata will create link on fdroid client
* should i remove it?

**Comment by deckerst** [comment]
It's fine, thank you.
