### ISSUE TITLE
Samsung Gallery Missing in Editing 

### ISSUE THREAD

**Issue by RickAust** [deckerst/aves#719]
**Describe the bug**
I'm sorry if I'm missing something obvious but Samsung Gallery isn't showing up in the edit list. It only shows One Drive, a photo resizer app, and Google Photos. The "i" icon asks me to modify the edit apps in the 'default' settings but this isn't possible on Samsung Galaxy S20. Is there anyway around this? I tried deleting the photo resizer app but that didn't help (it just left me with the remaining two apps in the edit options display).
Note that Samsung Gallery is my default photo editor and it's not possible to make another app the default photo editor. From what I've read online, this seems to be a common complaint amongst S20 owners.

**To Reproduce**
1. Go to a given photo
2. Click on edit
3. Gallery app doesn't appear

**Expected behavior**
Was hoping the Gallery app would appear. My only other option it seems is to go to 'export', then 'open with', then tap on 'Gallery' (which does appear here interestingly), then tap on the edit option within Gallery.
[aves-logs-20230821_180634.txt](https://github.com/deckerst/aves/files/12396848/aves-logs-20230821_180634.txt)

**Screenshots**
![Screenshot_20230821_180335_Android System](https://github.com/deckerst/aves/assets/56009454/f46b8429-73ec-4ffa-a735-ca1a4b81078e)
![Screenshot_20230821_175517_Android System](https://github.com/deckerst/aves/assets/56009454/e5e369a4-e498-4798-9b33-2d8dd63c9288)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.8.9-play, build 100
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: TP1A.220624.014.G988NKSU3IWE1
Device: samsung SM-G988N
Geocoder: ready
Mobile services: ready
System locales: en_GB
Storage volumes: /storage/emulated/0/, /storage/EAD4-A932/
Storage grants: /storage/EAD4-A932/DCIM/
Error reporting: false

**Additional context**

**Comment by deckerst** [comment]
Yes, I'm aware of this, having a Samsung device myself. It's Samsung Gallery's fault: it does not expose itself as an editor, so it does not appear in the list. I suppose this is Samsung intention to keep their tools within a tight ecosystem of Samsung apps. It's a shame because the Samsung gallery editor is great.

**Comment by RickAust** [comment]
Thanks very much, Thibault. And yes, I agree re the Gallery editor. I'm
very happy with it.

Appreciate the explanation (and the very quick response). Have a great day
(or night, depending on where you are). 🙂
