### ISSUE TITLE
Add support for opening from Xiaomi camera app

### ISSUE THREAD

**Issue by cewbdex** [deckerst/aves#727]
I know this is unlikely to be implemented, but it's still worth a try. Some time ago I sadly bought a Xiaomi phone. I have disabled builtin gallery app, as it was buggy and privacy nightmare. However, I did not find a good replacement for the camera app, so I use the stock one. Naturally, it has an option to open last taken photo, but it does not work with anything else than stock gallery app. No app even opens when I select it, only Termux. I post all details. If would you manage to find time, I will do anything on my device to help you.

**Describe the solution you'd like**
Be able to open this gallery app from stock Xiaomi camera.

**Describe alternatives you've considered**
Switching to another camera app, but I didn't find any what would work as well as stock one.

**Additional context**
![Screenshot_2023-08-25-08-27-24-505_com android camera](https://github.com/deckerst/aves/assets/9021297/73f552b6-1372-4ddf-b70a-7f0c91962a75)
![Screenshot_2023-08-25-08-27-36-666_android](https://github.com/deckerst/aves/assets/9021297/78f66064-22ee-49c7-93fc-ebc239eb029b)
![Screenshot_2023-08-25-08-27-47-735_com termux](https://github.com/deckerst/aves/assets/9021297/9ec12f98-9a05-4f18-9a39-36ee45c6a6c6)

**Comment by deckerst** [comment]
On your second screenshot i see a selection of galley apps, including Aves. When you select it, it opens Aves but you don't see the photo? If that's the case, try it and then, in the app go to About> Bug Report, save the logs and then attach them here.

**Comment by cewbdex** [comment]
It does not open at all, stays in the camera app, just the camera app behaves like it was reopened (blurry loading image and then it loads data from camera sensor). I will try to get logs now.

**Comment by cewbdex** [comment]
Nothing got logged at all, event time is exactly 9:09
[aves-logs-20230825_091013.txt](https://github.com/deckerst/aves/files/12436567/aves-logs-20230825_091013.txt)

**Comment by deckerst** [comment]
Could you install this app https://github.com/MuntashirAkon/AppManager and see if you can select that app when you select an app to open the photo? If it works you should get details about the intent, please screenshot that.

**Comment by cewbdex** [comment]
Unfortunately it does not, I will try to fill a issue with them, if they manage to do anything.

**Comment by deckerst** [comment]
I see. Then i don't think i can do anything on my side.

**Comment by cewbdex** [comment]
The developer of that application is very quick and implemented it. Here is the screenshot:

![Screenshot_2023-09-02-10-35-15-342_io github muntashirakon AppManager debug](https://github.com/deckerst/aves/assets/9021297/4a14c926-59ca-46c2-8888-0279a7093ee4)

The text, so you don't have to rewrite it:
content://media/external/images/media/1000001970
intent://media/external/images/media/1000001970#Intent;scheme=content;launchFlags=0x3000000;end

**Comment by deckerst** [comment]
Thanks!

For reference:
- https://github.com/MuntashirAkon/AppManager/issues/1155
- fixed by https://github.com/MuntashirAkon/AppManager/commit/2e84e0407ef2dcf39814c61cc343690d13a82048

**Comment by cewbdex** [comment]
I noticed that the URI changed, when I did a picture and opened it while the device was locked, attaching for reference:

![Screenshot_2023-09-02-11-12-19-064_io github muntashirakon AppManager debug](https://github.com/deckerst/aves/assets/9021297/6b0f7c0e-127f-4a50-b814-3648ecb0f7fb)

Id is different probably because it is different photo, but the "_primary" is only present if opening when the device is locked.

**Comment by deckerst** [comment]
Thanks for the precision. I'm aware of that kind of variation in the media url, but here i believe it's related to different intents and/or mime types. I'll inspect the fix from AppManager and come back to you with a test build soon™.

**Comment by cewbdex** [comment]
Thank you for the effort. While I was poking around and installing a lot of stuff from F-Droid, I found that Material Files application can handle this, it opens the picture, although I would rather prefer if I can swipe to older ones, not to be stuck on the latest one. Maybe you could also inspire there.

**Comment by deckerst** [comment]
Here's a test build:
https://drive.google.com/file/d/11vALMyGuS3SgTNsEZnnLNfqeUUE3TTHX/view?usp=sharing

It will install as "Aves [Profile]", so try to select that app (not the regular "Aves") to open your camera image, and please let me know whether it works.

But something does not add up from your original report. You say that you see Aves in the list of apps you can choose from, and that's consistent with the fact that the intent is `android.intent.action.VIEW` (Aves can handle these intents). But from the logs, I only see Aves started with the generic `android.intent.action.MAIN`, I see no call with `android.intent.action.VIEW`, as if Aves had never been selected.

So if you still can't open the image with Aves, please attach your system info and logs from `About` > `Bug Report` as well as a screen recording. And if you know what `logcat` is, please attach full logs from logcat at the time you tried to open the image with Aves.

**Comment by cewbdex** [comment]
Does not work, I will try the logcat later today.

**Comment by deckerst** [comment]
Also: "please attach your system info and logs from About > Bug Report as well as a screen recording".

**Comment by cewbdex** [comment]
[aves-logs-20230903_134700.txt](https://github.com/deckerst/aves/files/12505951/aves-logs-20230903_134700.txt)
Time was around 13:35.
https://youtu.be/_AX8nS3OJlo?si=0KA6MjSc59e0TTQe
I will find out how do do the logcat now. Also found Amaze tools can open the image too.

**Comment by deckerst** [comment]
In the `AppManager` screenshots you attached [here](https://github.com/deckerst/aves/issues/727#issuecomment-1703766066) and [here](https://github.com/deckerst/aves/issues/727#issuecomment-1703774141), I don't see whether there were "Extras" (it's the section below "Flags"/"Vlajky"). Could you please screenshot that section?

Also, if you catch the intent via `AppManager` first, then you can see matching activities at the bottom. You should see Aves main activity, among others. If you forward the intent to it from there, do you get the same behaviour (i.e. Aves does not even open)?

**Comment by cewbdex** [comment]
There is nothing in extras.

When I use interceptor and then launch the activity from it to Aves, it works in both stable and the one you sent.

**Comment by deckerst** [comment]
> When I use interceptor and then launch the activity from it to Aves, it works in both stable and the one you sent.

Unless the interceptor modifies the intent, this means Aves can deal with the intent from Xiaomi. Without checking what's going on in logcat, I'm afraid there's nothing more I can do here.

**Comment by cewbdex** [comment]
Sorry for not doing the logcat yet, it's on my todo list, but the phone is now broken and I use a backup one. If the phone gets repaired, I will send it here and you will see if you can do anything about it.

**Comment by cewbdex** [comment]
I have sent you an email, the attachment was big, so I am not sure if it did arrive. Just for inspiration, Interceptor did not open before the same as Aves does not, this is how the author fixed it: https://github.com/MuntashirAkon/AppManager/commit/2e84e0407ef2dcf39814c61cc343690d13a82048 . Maybe it could help if the logcat won't.

**Comment by deckerst** [comment]
Here's a test build:
https://drive.google.com/file/d/1AMxo_4tcNw0bZRXL2k0WlASmvGaLAcrT/view?usp=sharing

It will install as "Aves [Profile]", so try to select that app (not the regular "Aves") to open your camera image, and please let me know whether it works.

**Comment by deckerst** [comment]
Here's a test build:
[aves-play-profile_727_20230101_2115.apk](https://drive.google.com/file/d/1dHdwb-ZRQ-ToIHhBBIDGJ6t7eujlqHyR/view?usp=sharing)

It will install as "Aves [Profile]", so try to select that app (not the regular "Aves") to open your camera image, and please let me know whether it works.

**Comment by cewbdex** [comment]
Thank you very much for your effort. I will test as soon as I get the working phone back.

**Comment by cewbdex** [comment]
I am very sorry, but the 2nd repair shop has my from 22.11. and still no response, I hope you don't take this personally, I am very grateful for all of your work.

**Comment by deckerst** [comment]
No worries, it's for you. I just prefer to close this as I can't work on it any further without additional insight.
