### ISSUE TITLE
Add fixed-image widget

### ISSUE THREAD

**Issue by ukrbugreporter** [deckerst/aves#728]
Add an option to create a widget that will display only one chosen image. Currently this is only possible to do by creating a new collection or tag with for desired image, but this method is inconvenient and not obvious.

**Comment by deckerst** [comment]
I'm glad you found a way with tags. This seems easy and flexible enough to me.

**Comment by ukrbugreporter** [comment]
I agree, but as I said this workaround is not obvious and it also makes user do additional steps to change the displayed image (remove tag from old image and add it to a new one). If you are happy with the way it works now and not planning to implement this feature - close the issue. Otherwise - consider my request, please.
