### ISSUE TITLE
Application Crashes when opening download video file

### ISSUE THREAD

**Issue by Striker789** [deckerst/aves#729]
**Describe the bug**
After the update when downloading videos from WhatsApp/Signal the application crashes.

**To Reproduce**
1. Download the video file from WhatsApp/Signal.
2. Open aves to view the video
3. The application crahaes

**Expected behavior**
The video downloaded from WhatsApp/signal be viewed without crashing.

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.aurora.store
Aves version: 1.9.2-play, build 103
Flutter: stable 3.13.1
Android version: 13, API 33
Android build: TQ3A.230805.001.2023080800
Device: Google Pixel 7 Pro
Geocoder: not available
Mobile services: not available
System locales: en_GB
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/
Error reporting: false

**Comment by deckerst** [comment]
Please attach app logs, and a sample video.

Also, do you use a custom ROM?

**Comment by Striker789** [comment]
I have attached both requirements. Yes, GrapheneOS.
https://github.com/deckerst/aves/assets/85591381/1af9f435-c2f3-47ca-8b0b-ff43e70ce7eb

[aves-logs-20230826_120735.txt](https://github.com/deckerst/aves/files/12444959/aves-logs-20230826_120735.txt)

**Comment by deckerst** [comment]
Thanks, but I meant the sample video that makes things crash, not a screen recording. Anyway, isn't your issue the same as #722, because of hardened malloc? If so, I'll close this issue as duplicate.

By the way, on your device with hardened malloc, do you have some videos that play fine with Aves and some that crash, or all videos make it crash?

**Comment by Striker789** [comment]
Unfortunately, the issue persists with all videos as well as the motion pictures. I have checked #722, and it appears to be the exact same problem.
