### ISSUE TITLE
.ico support

### ISSUE THREAD

**Issue by AdityaMH** [deckerst/aves#731]

**Comment by deckerst** [comment]
Already works, as far as i know.
![Screenshot_20230828_081121_Aves](https://github.com/deckerst/aves/assets/13898333/7c1aca2d-7544-474b-b140-dc5a6b5f997d)

**Comment by AdityaMH** [comment]
![IMG_20230912_201457](https://github.com/deckerst/aves/assets/33791472/93645932-6c05-4502-adec-891355449fa1)

**Comment by deckerst** [comment]
Could you please share a sample?

**Comment by AdityaMH** [comment]
[ico.zip](https://github.com/deckerst/aves/files/12605079/ico.zip)

**Comment by deckerst** [comment]
These icons are corrupted. Other viewers can't open them either.
