### ISSUE TITLE
Option to add ".folder"

### ISSUE THREAD

**Issue by sjiawjbssj** [deckerst/aves#734]
**Is your feature request related to a problem? Please describe.**
I have some folders with a . before the name because I don't want the pictures to show in the normal gallery or media picker. I'd like to view them in aves.

**Describe the solution you'd like**
Just like being able to hide paths I'd like the option to add paths.
An option to only show albums in those manually added paths would be great as well.

**Comment by deckerst** [comment]
Duplicate:
- #574
