### ISSUE TITLE
Dual slideshow not working anymore. 

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#737]
Good day dev. Usually would use Aves and Libre in split screen to play dual slideshows, however since recent updates the slideshow stops when the window is out of focus.

**Comment by deckerst** [comment]
You're creative with your use of multiple Aves!

I'll take a look to see whether it should or should not stop the slideshow. One thing though, if the app loses focus I'll keep stopping videos.

**Comment by DroidFloyd** [comment]
Thanks for your consideration.
