### ISSUE TITLE
Horizontally scrolling buttons

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#738]
Good day.
![Screenshot_20230901_100433_Aves.jpg](https://github.com/deckerst/aves/assets/118023622/aa40a902-8afd-4b76-a966-dff5dc24300b)

![Screenshot_20230901_100600_Aves.jpg](https://github.com/deckerst/aves/assets/118023622/7778cb17-0d81-4224-beef-917fb8c9b38f)

![Screenshot_20230901_100348_Aves.jpg](https://github.com/deckerst/aves/assets/118023622/ba163325-25b6-415e-bd03-925b8b7b599c)

Some viewer buttons will be hidden because there's not enough space on the screen. The same goes for all the other buttons outlined in my screenshots.

Having them to be scrolled horizontally could fix this issue imho. 
Hope this finds you well.

**Comment by deckerst** [comment]
This is on purpose. If you need to scroll, you may use the existing overflow menu just as well.
