### ISSUE TITLE
Double tap increase zoom

### ISSUE THREAD

**Issue by baptistebisson** [deckerst/aves#739]
Hello,
First issue here, thanks a lot for the app !

**Is your feature request related to a problem? Please describe.**
I have a lot of picture with the format 720x1280 and the double tap only fit the image to fill the screen. Another double tap zoom out

**Describe the solution you'd like**
I've used a lot solid explorer and the viewer first double tap zoom a lot more into the picture. Another double tap zoom again. It would be nice to have the same functionality.

**Describe alternatives you've considered**
Maybe too much but it can be nice to be able to personalize the zoom level in the settings

**Comment by deckerst** [comment]
Welcome, and glad to hear you enjoy the app!

The first double-tap zooms to fit the screen (as you've mentioned), but the second double-tap actually zooms to the image actual size if the image is larger than the screen (unless the zoom to fit is already the same as the zoom to actual size, such as a 720x1280 image in a 720x1280 screen). In other words, if your image was high res, you would see the behaviour you request.

I'm happy with the behaviour as it is and don't intend to change it. Maybe custom zoom settings is the solution to please everybody, but I want to avoid adding settings as much as possible.

As for your need, you can always quickly zoom more with these gestures:
- pinch-to-zoom gesture (2 fingers), or
- double-tap and vertical drag (1 finger).

**Comment by baptistebisson** [comment]
> Welcome, and glad to hear you enjoy the app!
> 
> The first double-tap zooms to fit the screen (as you've mentioned), but the second double-tap actually zooms to the image actual size if the image is larger than the screen (unless the zoom to fit is already the same as the zoom to actual size, such as a 720x1280 image in a 720x1280 screen). In other words, if your image was high res, you would see the behaviour you request.
> 
> I'm happy with the behaviour as it is and don't intend to change it. Maybe custom zoom settings is the solution to please everybody, but I want to avoid adding settings as much as possible.
> 
> As for your need, you can always quickly zoom more with these gestures:
> 
> * pinch-to-zoom gesture (2 fingers), or
> * double-tap and vertical drag (1 finger).

Thanks for the reply. I understand your point of view. It would be great to ignore the quality in order to zoom in.

I didn't know about the double-tap and drag. Less easy to use but get the job done !

**Comment by deckerst** [comment]
> It would be great to ignore the quality in order to zoom in.

It is not a matter of quality but size. As it is now, when you double-tap twice, you know you're at 100%. If it was zooming further in also when the image already fit the screen at 100% (as you wish), you wouldn't know whether you're at 100% or more.

> I didn't know about the double-tap and drag. Less easy to use but get the job done !

The nice thing with that gesture is that it can be done with one finger. I personally use that gesture a lot with map apps.
