### ISSUE TITLE
1.9.x not available on F-Droid but on IzzyOnDroid

### ISSUE THREAD

**Issue by hadesxp** [deckerst/aves#740]
Currently I have 1.8.9 from F-Droid installed, 1.9.3 is only available from IzzyOnDroid.

But since 1.9.x Anti-Features are listed - could you specify, maybe in the changelogs?

**Comment by deckerst** [comment]
There was an issue with building 1.9.x by F-droid servers, but the last version should build fine and it will be up there eventually. Nothing changed otherwise.
