### ISSUE TITLE
Update fdroid version

### ISSUE THREAD

**Issue by MrRulf** [deckerst/aves#741]
**Describe the bug**
The fdroid version of the app hasnt been updated for over 2 months now, wanted to ask why?
izzyonandroids repo is up to date, but says something about anti features, different versions?
Since there is both, aves in izzyonandroids repo, and aves libre in fdroid i wanted to ask, whats the difference amd which one should be picked?

**To Reproduce**
1. Check fdroids latest version number for aves libre

**Expected behavior**
To see the latest version after most two weeks after release

Didn't find any hugs regarding this or documentation, sorry if there is and for the inconvinience, u have a great project!

**Comment by MrRulf** [comment]
I didnt see the compare versions button

**Comment by MrRulf** [comment]
Didn't see the compare versions button, however I still don't get why fdroid version is so outdated

**Comment by deckerst** [comment]
Aves Libre v1.9.3 is already available via the GitHub release.

F-droid usually takes several days to catch up. Also, for some technical reasons F-droid was unavailable to build Aves v1.9.x, before Aves v1.9.3.

So, if you still don't see Aves Libre v1.9.3 on F-droid in a week, feel free to create an issue on their repo.

**Comment by MrRulf** [comment]
Yes, but always updating manually by getting the new file is kinda exhausting if u do it with many apps, so I take the store approach. 

Thanks for the information, just wanted to know if I need to switch to izzy or something bc of some new feature or library that conflicts with fdroids guidelines or something (happened with other apps) or if fdroid support stopped bc there are other ways (izzy) ^^"

**Comment by deckerst** [comment]
I agree with you about the convenience of stores, but just in case you need it someday I recommend you check out [Obtainium](https://github.com/ImranR98/Obtainium).
