### ISSUE TITLE
Openexr file support

### ISSUE THREAD

**Issue by jere-a** [deckerst/aves#742]
**Is your feature request related to a problem? Please describe.**

I would use that support because I use the Blender 3d program's exr file storage format a lot and I want to see the images in full color on my phone because usually phones are calibrated to the right image settings and no other program supports the exr file format

**Describe the solution you'd like**

Add support for openexr files format

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerst** [comment]
Android (at least on Android 12 and older, not sure on 13+) does not recognize EXR files as media, so they're not listed and are not accessible to gallery apps like Aves.
