### ISSUE TITLE
Can't Open Videos

### ISSUE THREAD

**Issue by Seanld** [deckerst/aves#745]
Just today I noticed I can no longer play videos.  Every time I tap one, it starts the animation to open the video, and then crashes.

This is on the latest version. It does not happen with 1.8.9, which I just went back to. However it seems the problem persists on all 1.9+ versions. I'm not sure why my version must've been so out of date. I keep it auto-updated via Neo Store.

**Comment by BillORights** [comment]
Same problem

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/issues/234
