### ISSUE TITLE
Change of Tagging-Flow

### ISSUE THREAD

**Issue by user13v31** [deckerst/aves#746]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Not a problem, just a maybe easier way to tag pictures.

**Describe the solution you'd like**
Instead of selecting tags and then press the confirm-button just tap on the tags so they show up in the "selected tags"-list and save those by pressing the "back"-button of the phone to move back to the previous menu. Especially if you use gesture controls it gets much easier to edit the tags.

**Describe alternatives you've considered**
Maybe instead of "confirm" provide a "undo"- or an "abort"-button if you want to undo changes.

**Additional context**
I just stumbled upon the app yesterday and already I'm in love. Have a coffee on my tab :)

**Comment by deckerst** [comment]
> Instead of selecting tags and then press the confirm-button just tap on the tags so they show up in the "selected tags"-list and save those by pressing the "back"-button of the phone to move back to the previous menu. Especially if you use gesture controls it gets much easier to edit the tags.

Funny you should suggest this, it was actually working that way before! Like you, at first I thought it would be easier and smoother. But [some people complained about the experience](https://github.com/deckerst/aves/issues/601), and I agreed with them. It was not consistent with the rest of the app.

> Maybe instead of "confirm" provide a "undo"- or an "abort"-button if you want to undo changes.

I believe there is already a cancel button available for long operations (editing tags on many elements at once could be a long operation). The "X" button inside the progress circle.

About alternatives, maybe you don't know and it would be helpful to you: when you long press on the tag button (in the `Info` page, or if you add it as a viewer quick action), you can quickly tag with one of your most recent tags.

> I just stumbled upon the app yesterday and already I'm in love. Have a coffee on my tab :)

Glad you like it, thanks!

**Comment by user13v31** [comment]
Hahaha... Quick-Tags via long-press.... no I didn't know 😂
I could cry right now. Thank you so much👍
gz dijak

----------------------------------------

07.09.2023 19:22:10 Thibault Deckers ***@***.***>:
