### ISSUE TITLE
Pictures distroyed after trying to transfer to full sd card

### ISSUE THREAD

**Issue by TotallyNormalPerson** [deckerst/aves#753]
**Describe the bug**
I tried to transfer some files to the sd card, but the sd card was full. It let me do it anyway. I realized that's maybe not the best idea and cancelled it, but it took a while and then it had already transferred 7 files successfully and 22 files unsuccessfully. The 22 are shown as black with a little 'oops!' text on it. Within the app it still says they have a normal picture size, but in Total Commander they show up as 0B.

**To Reproduce**
1. have a full sd card
2. (optionally) forget that it's full
3. select a lot of pictures from a folder in internal storage and click to transfer them to a folder on the sd card
4. click 'okay' on the message popping up to tell you that there is no space
5. I think it gave me the option to cancel or continue at this point?, so maybe click 'okay' again
6. wait for the circle that shows the progress to show up, and click 'cancel'
7. wait
8. stare in agony at the lost pictures of cute kittens

**Expected behavior**
I assumed it wouldn't LET me ACTUALLY transfer anything to an actually full card. I thought it meant that there is not enough space on the card for ALL selected pictures and it was just gonna transfer the first few until the card was full.
If you wanted to give users the freedom to decide to destroy their pictures by transferring them to a full sd card, I respect that, but I would have appreciated a warning for dummies like 'are you SURE?'

**Screenshots**
language is German, pink dots are edited in to censor faces
![Screenshot_20230914-153333_1](https://github.com/deckerst/aves/assets/138627586/4c1840d7-9331-4feb-aeae-42ed920fd9f2)
![Screenshot_20230914-163011](https://github.com/deckerst/aves/assets/138627586/a9cbadbc-b1cc-46b3-a4f9-fcd0527f8905)
![Screenshot_20230914-162958](https://github.com/deckerst/aves/assets/138627586/09bad7d6-8984-4ad6-b175-2bc2ceacd876)

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.8.9-libre, build 10002
Flutter: stable 3.10.3
Android version: 12, API 31
Android build: FP4.SP2K.B.089.20230807
Device: Fairphone FP4
Geocoder: ready
Mobile services: not available
System locales: de_DE
Storage volumes: /storage/emulated/0/, /storage/042C-7A6B/
Storage grants: /storage/042C-7A6B/DCIM/, /storage/042C-7A6B/OperaDownloads/, /storage/042C-7A6B/Pictures/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/042C-7A6B/Bilder/, /storage/emulated/0/Bilder/, /storage/emulated/0/Android/media/
Error reporting: false
[aves-logs-20230914_164310.txt](https://github.com/deckerst/aves/files/12610478/aves-logs-20230914_164310.txt)

**Additional context**
Obviously, it did tell me that the card was full, and I should have cancelled it sooner, so maybe this isn't even technically a bug.
Anyway, trying to repair the files at this point would probably be futile because I have since shifted some things between internal storage and sd card, and deleted things, porbably (or so I'm told) overwriting any fragments that might still have been there. It's sad but not the end of the world.

**Comment by deckerst** [comment]
I'm surprised it let you transfer files if there wasn't enough space for the whole operation. As i remember, it's not possible to pass the warning about insufficient storage. I'll double check when i can.

**Comment by deckerst** [comment]
Ah, my bad. The warning dialog has only one button "OK", which is  normal, but it goes on with the operation, which is wrong. It should stop there and prevent what you experienced. Thanks for bringing this to my attention.
