### ISSUE TITLE
Option to change thumbnails display

### ISSUE THREAD

**Issue by l2eused** [deckerst/aves#754]
**Describe the solution you'd like**

Allow user to change thumbnails style for image/video and album

- **change rounded corners**
ie. no rounded corners

- **border thickness**
ie. no border, 2dp border (or thin/thick) //use dynamic color

- **text position for album** (title and amount of pictures)
ie. above thumbnails, below thumbnails (and center/left text position)

- **gap between thumbnails**
ie. no gap, 2px

P.S could be better if separate option for albums/pictures and grid/mosaic layout

**Comment by deckerst** [comment]
Thanks for the suggestions but I don't intend to provide that kind of design settings. This would break the consistency of design throughout the app, clutter settings, and be tedious to maintain.

Duplicate:
- #286
