### ISSUE TITLE
For albums view, limit the min width for album.

### ISSUE THREAD

**Issue by zbutfly** [deckerst/aves#755]
For albums contain only long screenshots, the albums veiw displays them too narraw (just like attachment image, second row and left two albums). 

It can be resolved easily by give a minimal width of each album in albums view, for example 25% of the width of screen.

![Screenshot_20230916-002347_Aves Libre](https://github.com/deckerst/aves/assets/2871795/1a0969fe-0457-4082-96dc-e0ef8a79d86a)

**Comment by deckerst** [comment]
For the mosaic layout in `Albums` page only? Not also in the `Collection` page?

**Comment by zbutfly** [comment]
> For the mosaic layout in `Albums` page only? Not also in the `Collection` page?

in clooection view the thumbnail of single longshot is narrow too. Hard to tap exactly but since no lable overflow, looks much better than in album view.

**Comment by deckerst** [comment]
Instead of playing with widths, I constrained thumbnail aspect ratios to be within [32/9, 9/32]. This is arbitrary but it seems to work well, whether you have long vertical screenshots, or very wide panoramas (which were also messing up the layout).

**Comment by zbutfly** [comment]
looks much better. thanks for your great work on the app. it's the best one for my huge gallery (more than 100k pictures on phone)

**Comment by deckerst** [comment]
Nice! By the way, doesn't it take a long time to load your 100k pictures when launching the app? I'm glad it works for you but it may not be optimized for such a large collection.

**Comment by zbutfly** [comment]
I can accept the low initialization performance since my strange requirements, and most gallery apps including aves can browser them on loading finished. since i hashed them into hundreds of folders hierarchy.

the problem is on updateing one or some subfolder in the huge album with adding/removing some picture files. other app update the subfolder slowly. I think it's because of dependence of althe Android metastore. Aves has no such problems.
