### ISSUE TITLE
Some images are incorrectly marked as shot on 1st January 1970 

### ISSUE THREAD

**Issue by mijorus** [deckerst/aves#756]
I'm attaching the exported Exif data here below, I just stripped the GPS section .

Apparently it does not have any Date / Time info in the exif, but Google Gallery is able to list it just fine.

```
[Exif IFD0]
  Make: Nothing
  Model: A063
  Orientation: Top, left side (Horizontal / normal)
[Exif SubIFD]
  Aperture Value: f/1,9
  Exposure Time: 0.04 sec
  F-Number: f/1,9
  Flash: Flash did not fire
  Focal Length: 5,6 mm
  ISO Speed Ratings: 1881
  Time Zone: +01:00
  Time Zone Digitized: +01:00
  Time Zone Original: +01:00
  White Balance Mode: Auto white balance
[Huffman]
  Number of Tables: 4 Huffman tables
[JFIF]
  Resolution Units: none
  Thumbnail Height Pixels: 0
  Thumbnail Width Pixels: 0
  Version: 1.1
  X Resolution: 1 dot
  Y Resolution: 1 dot
[JPEG]
  Component 1: Y component: Quantization table 0, Sampling factors 2 horiz/2 vert
  Component 2: Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
  Component 3: Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
  Compression Type: Baseline
  Data Precision: 8 bits
  Image Height: 4096 pixels
  Image Width: 3072 pixels
  Number of Components:

```

**Comment by deckerst** [comment]
Google Gallery/Photos does not only pull out dates from photo metadata. It can also get it from the Maps Timeline, for example, and probably some other black magic.

Aves should never show any item date as "1st January 1970". This date corresponds to some default value, and it is ignored when encountered. Then the file modified date is used, but maybe that too is not initialized/readable for some reason.

Could you share a sample? You could also provide a screenshot to back your claim. Following instructions in `About` > `Bug Report` could help too.

**Comment by mijorus** [comment]
![Screenshot_20230916-085508.png](https://github.com/deckerst/aves/assets/39067225/e53fc134-d001-41d8-b4d4-dff32eaed727)

![Screenshot_20230916-085615~2.png](https://github.com/deckerst/aves/assets/39067225/d28f9959-c3c1-4413-ac69-e0fc945e7cad)

I'm attaching two screenshots here.

One is from aves, the latest version from the play store, the other from Solid Explorer.

Solid is able to read the file properties just fine, and the photo is shown in the correct spot in the timeline, while aves reports it was taken on 01/01/1970 +01.00

**Comment by deckerst** [comment]
Thanks for the details. Can you send me a sample file that has this issue? (you can also send it by email if you don't want to put it in this public space)

**Comment by mijorus** [comment]
> Thanks for the details. Can you send me a sample file that has this issue? (you can also send it by email if you don't want to put it in this public space)

I'll be contacting you soon

**Comment by deckerst** [comment]
Reproduced with the samples, thanks.

Apparently, the metadata date in these is "-1", not the usual default value "0". "0" means `1st January 1970 00:00:00`. "-1" is one millisecond before that, then add the time zone offset of 1 hour, and you get `1st January 1970, 00:00:59.999`.

As i already exclude "0" as an invalid value, I'll also exclude "-1" to fix this.

**Comment by mijorus** [comment]
> Reproduced with the samples, thanks.
> 
> Apparently, the metadata date in these is "-1", not the usual default value "0". "0" means `1st January 1970 00:00:00`. "-1" is one millisecond before that, then add the time zone offset of 1 hour, and you get `1st January 1970, 00:00:59.999`.
> 
> As i already exclude "0" as an invalid value, I'll also exclude "-1" to fix this.

This could very well be an issue caused by the NothingOS, their camera app does not always behave reliably. I'll report this issue on their Discord, so maybe they can also take a look.

Thank you
