### ISSUE TITLE
Crashes when catalouguing on A13 starting from 1.9.0

### ISSUE THREAD

**Issue by ghdotc** [deckerst/aves#758]
[aves-logs.txt](https://github.com/deckerst/aves/files/12641340/aves-logs.txt)
**Describe the bug**
Starting from 1.9.0 app randomly crashes.

**To Reproduce**
1. Just use the app

**Expected behavior**
No random crashes

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.android.packageinstaller
Aves version: 1.9.4-libre, build 10502
Flutter: stable 3.13.4
Android version: 13, API 33
Android build: TQ3A.230805.001
Device: Xiaomi M2012K11AG
Geocoder: not available
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Additional context**
It happens not only on libre variant, but on others too.
I've deleted path's and names of files in log cuz I don't like to share this info. And as I don't fully understand logs, I can't say if it's app bug or kernel, cuz I've updated my kernel today. I've also reported it on kernel bugtracker.

**Comment by deckerst** [comment]
Do you use a custom ROM?

If you use GrapheneOS, you're likely encountering:
- #722

**Comment by ghdotc** [comment]
> Do you use a custom ROM?
> 
> If you use GrapheneOS, you're likely encountering:
> 
>     * [Opening a video in the viewer crashes the app #722](https://github.com/deckerst/aves/issues/722)

I'm on crdroid 9.8. Infinir kernel.

**Comment by deckerst** [comment]
Does it use some kind of hardened malloc functionality?
The major thing with Aves v1.9.0 is the usage of 2 new libraries for handling videos, `media kit` for video playback (the one making trouble with hardened malloc, discussed in #722), and `ffmpeg kit` for video cataloguing.

If for you it happens "randomly", maybe video cataloguing happens in the background. Do you have enabled notification permission? Do you see a notification when cataloguing large amount of new items?

**Comment by ghdotc** [comment]
> Does it use some kind of hardened malloc functionality? The major thing with Aves v1.9.0 is the usage of 2 new libraries for handling videos, `media kit` for video playback (the one making trouble with hardened malloc, discussed in #722), and `ffmpeg kit` for video cataloguing.
> 
> If for you it happens "randomly", maybe video cataloguing happens in the background. Do you have enabled notification permission? Do you see a notification when cataloguing large amount of new items?

Idk about hardened malloc.
I think I've misunderstood crashes.
When notification permsisions is enabled, then I see that it crashes when it's cataloguing for some time.

**Comment by deckerst** [comment]
Just for confirming it's from cataloguing, could you start the app via the "Safe mode" app shortcut? It will start the app as usual but will not trigger the cataloguing. Then you can wait and see whether it crashes.

If it doesn't crash after a while in safe mode, please try to open a video (without auto-play) and go to its `Info` page (swipe up).

**Comment by ghdotc** [comment]
> Just for confirming it's from cataloguing, could you start the app via the "Safe mode" app shortcut? It will start the app as usual but will not trigger the cataloguing. Then you can wait and see whether it crashes.
> 
> If it doesn't crash after a while in safe mode, please try to open a video (without auto-play) and go to its `Info` page (swipe up).

No crashes.

**Comment by ghdotc** [comment]
> > Just for confirming it's from cataloguing, could you start the app via the "Safe mode" app shortcut? It will start the app as usual but will not trigger the cataloguing. Then you can wait and see whether it crashes.
> > If it doesn't crash after a while in safe mode, please try to open a video (without auto-play) and go to its `Info` page (swipe up).
> 
> No crashes.

So... I know now that crashes produceded by files with this names: 
痛，太痛了（unravel） [BV1qs4y1R75w_p1]
有生之年系列！中岛美嘉献唱《KISS OF DEATH》 [BV1nf4y1b7bM_p1]

**Comment by ghdotc** [comment]
> > > Just for confirming it's from cataloguing, could you start the app via the "Safe mode" app shortcut? It will start the app as usual but will not trigger the cataloguing. Then you can wait and see whether it crashes.
> > > If it doesn't crash after a while in safe mode, please try to open a video (without auto-play) and go to its `Info` page (swipe up).
> > 
> > 
> > No crashes.
> 
> So... I know now that crashes produceded by files with this names: 痛，太痛了（unravel） [BV1qs4y1R75w_p1]
> 
> 有生之年系列！中岛美嘉献唱《KISS OF DEATH》 [BV1nf4y1b7bM_p1]

Now I think it's an app issue, since it'll crash also on other divices with other roms and kernels if it'll try to catalouge it. It'll even crash if file was opened by aves via 'open with' android menu. Also material files and mpv handles this files properly.

**Comment by deckerst** [comment]
Oh, thanks for the investigation!
Could you share one of the files that make it crash? You can also send it to me via email if you do not want to share it here.

**Comment by deckerst** [comment]
Thanks, i reproduce the crash.

**Comment by deckerst** [comment]
Could you try [this build](https://drive.google.com/file/d/111W4BfffaTyECRp1R7o1M6ADB7E_pyG3/view?usp=sharing) and let me know how it goes? It will install as a separate app called "Aves [Profile]". Also, cataloguing from scratch can take a while if you have many items, so you may want to enable notification permission to track cataloguing progress and know for sure when it's complete.

**Comment by ghdotc** [comment]
> Could you try [this build](https://drive.google.com/file/d/111W4BfffaTyECRp1R7o1M6ADB7E_pyG3/view?usp=sharing) and let me know how it goes? It will install as a separate app called "Aves [Profile]". Also, cataloguing from scratch can take a while if you have many items, so you may want to enable notification permission to track cataloguing progress and know for sure when it's complete.

No crashes. I can also open those files through 'open with' android menu without crashes. Playback of those files aslo works without crashes.
