### ISSUE TITLE
Slideshow favorites button

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#759]
Good day dev.
Please add a favorites button to the slideshow viewer, for ease of use.
![Screenshot_20230905_022554_Aves.jpg](https://github.com/deckerst/aves/assets/118023622/663e42ce-09c9-47cf-b6bf-4228c04fb78b)

**Comment by deckerst** [comment]
Slideshow is not there for interaction. You can use the regular mode for that.

**Comment by DroidFloyd** [comment]
With all due respect, it serves me how I see fit.

The thing is it's a waste of time to leave the slideshow to like a picture. 

If the button was right there, I'd never have to leave the slideshow to like another one. Please understand.

**Comment by DroidFloyd** [comment]
Favorites button in slideshow playback please.

**Comment by DroidFloyd** [comment]
Hello dev, my apologies. I can't stop asking for the favorites button in the slideshow and All Files Access permission 😭 mainly. (Need those in my life)

I keep having to switch apps because I know Aves is the slowest performing in file operations.🐌🦥

It's the absolute best overall across the board no doubt, but I keep having to use alternatives, no matter how much time passes and Aves is updated.👍🏽
