### ISSUE TITLE
Gallery auto-update does not work

### ISSUE THREAD

**Issue by snooppr** [deckerst/aves#760]
### The essence of the problem

Open "Aves".  Take a screenshot.  The gallery should update and the screenshot should appear in "Aves".  Does not update automatically.  Try updating the gallery manually: click the three dots in the upper left corner -> rescan, this also does not work, new photos/screenshots do not appear in Aves.  The decision to close Aves and open it again, all new photos will appear.  Inconvenient.

Aves v1.9.3 f-droid, Android 9.

**Comment by deckerst** [comment]
I don't think it's a bug with Aves but with the Android Media Store on your device. On older device, the Media Store was often taking time to update.

**Comment by snooppr** [comment]
As you wish.  The problem only occurs with Aves; third-party gallery applications and the native one work normally.  So I'm sure the problem is on Aves' side.

**Comment by deckerst** [comment]
Could you provide the system info and logs you get from following instructions at "About" > "But Report"?

**Comment by snooppr** [comment]
I can probably send the log, but can I do it not as publicly as suggested?  For example, to the developer's email?

**Comment by deckerst** [comment]
Sure (and the system info too).

**Comment by snooppr** [comment]
Sent.

**Comment by deckerst** [comment]
Possibly related:
- #687

**Comment by deckerst** [comment]
@snooppr do you still have the issue with the latest version of Aves?

**Comment by snooppr** [comment]
> @snooppr do you still have the issue with the latest version of Aves?

The problem persists v.1.10.8

**Comment by SeeleVolleri** [comment]
```
Package: deckers.thibault.aves.libre
Installer: com.android.packageinstaller
Aves version: 1.11.4-libre, build 12302
Flutter: stable 3.22.2
Android version: 11, API 30
Android build: TYH 11.0.0.10Q
Device: ChinaTelecom TYH212U
Support: dynamic colors=false, geocoder=true, HDR=true
Mobile services: not available
Connectivity: wifi
System locales: zh_CN
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/
Error reporting: false
```
Can we just re-add the ability to rescan all folders by manual?
For unknown reason even I tried moving the folder of photos (png jpg it worked before) in every folder(DCIM Pictures etc.) it just won't show up. But if I takes a picture it shows up immediately.

**Comment by deckerst** [comment]
> Can we just re-add the ability to rescan all folders by manual?

The "rescan" action in Aves has never done what you think it does. It only reads and interprets metadata of known items, it does not discover new items.

> even I tried moving the folder of photos

How do you move them?

**Comment by SeeleVolleri** [comment]
> How do you move them?

Let's just say, `adb shell mv /sdcard/randommemes /sdcard/Pictures/` back and forward

**Comment by SeeleVolleri** [comment]
structure be like:
```
$  adb shell ls -alh /sdcard/DCIM/randommemes/
total 273M
-rwxrwx--- 1 u0_a164 u0_a164 4.6M 2023-02-19 16:06 -3c5f95a3d0c3ae81.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.6M 2023-02-19 16:06 2023-02-19 144712.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.8M 2023-02-19 16:06 2023-02-19 144813.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.7M 2023-02-19 16:06 2023-02-19 144858.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.4M 2023-02-19 16:06 2023-02-19 145101.jpg
-rwxrwx--- 1 u0_a164 u0_a164 3.7M 2023-02-19 16:06 2023-02-19 145232.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.6M 2023-02-19 16:06 2023-02-19 145353.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.5M 2023-02-19 16:06 2023-02-19 145438.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.6M 2023-02-19 16:06 2023-02-19 145508.jpg
-rwxrwx--- 1 u0_a164 u0_a164 4.6M 2023-02-19 16:06 2023-02-19 145523.jpg
```

**Comment by deckerst** [comment]
I see. Then it's normal the media are not registered. You're not transferring media files using appropriate protocols like MTP. If for some reason you have to use adb, maybe you could find a way to trigger media store scan on these files via adb too.

**Comment by SeeleVolleri** [comment]
And I also tried `$ find /sdcard/Pictures -type f -exec sh -c 'am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file://"$1"' _ {} \;`
to try force refresh the Android media store.

**Comment by SeeleVolleri** [comment]
I tried MTP, it worked...

**Comment by SeeleVolleri** [comment]
But without mtp it never refreshes. Can Aves try to trigger that?

**Comment by deckerst** [comment]
Depending on Aves is a bad idea. It means that until you would use that magic rescan, no other app is aware of the new media.

It's better to fix the media registration at the source. In essence it means using MTP for inter-device transfers, and well-written file managers for intra-device transfers.

**Comment by snooppr** [comment]
The developer finally fixed 1/2 bugs, success. I confirm, version 1.11.13 works updating the gallery when adding a photo.
But when deleting a photo, the gallery does not update, you need to restart the application for the photo to disappear.

**Comment by deckerst** [comment]
@snooppr you've mentioned an issue refreshing the app after deleting a photo (outside Aves, I suppose). Do you still have the issue with Aves v1.11.17? If so, could you report it following the instructions at `About` > `Bug Report`. Adding a screen recording showing your workflow would be helpful too.

**Comment by gambhiro** [comment]
It would be useful to have a menu item to manually trigger a media store update which scans all folders for media files.

Users manipulate files in all sorts of contexts, for example opening the SD Card folders on a laptop, or moving around images in the Termux app.

At first I didn't realize that the app is not displaying the images as they are in a given folder, and it was confusing why they don't appear or disappear when I move the files around.

After I learned that the app sees the images via the media store API, I understood that I need to trigger some kind of wholesale all-folders re-scan after moving files around.

I found a separate app to do that ([media Re.Scan](https://play.google.com/store/apps/details?id=com.house.noranuko.mediarescanner)) but I suggest that this function would be useful in the Aves app itself.

Seeing a menu item for such a re-scan would also prompt a user to understand the media store concept.

**Comment by deckerst** [comment]
@CyberNeutrino what app do you use for editing?

**Comment by CyberNeutrino** [comment]
@deckerst I tried on the stock image editor (com.coloros.photoeffects), Snap Seed and [Photo Editor](https://github.com/burhanrashid52/PhotoEditor). Also, seems like Aves won't load edited images even if these images are picked and edited entirely inside editors, while Aves is still opening.

Hmmm... And I noticed that Aves doesn't always successfully update images taken via the camera (again, while Aves is opening). Sometimes they appear, but sometimes they don't.

However, seems like Aves can always update new screenshots.

**Comment by Wizard-Mage** [comment]
I have version 1.14.9 Installed on the following devices: 
Samsung tablet S10 FE Android Version 16
Galaxy Note 20 Ultra 5G Android version 13

I regularly update the picture files on both devices using FreeFileSync , and SSHServer 

Both devices the images are stored on a MicroSD card. 

When I open Aves on the Note ... all the images are updated. 

When I open Aves on the Tablet they are not updated ,  however I know the images have been updated because I can find the new images on a different gallery app so they do exist but Aves is not picking them up. 

I tried to select all images in the collection page and hit rescan but that did not seem to work.  I have closed and reopened the app , but no changes. 

Anything else I can try , short of uninstalling and reinstalling the app?

**Comment by deckerst** [comment]
@Wizard-Mage if Aves does not pick up changes, it's either because of a bug in Aves, or because the Android Media Store hasn't found them yet. Reinstalling Aves wouldn't help in either case.

Rebooting your device may help, as Android often triggers media scanning after boot (but that behaviour wildly varies across Android versions and phone makers).

**Comment by Wizard-Mage** [comment]
> [@Wizard-Mage](https://github.com/Wizard-Mage) if Aves does not pick up changes, it's either because of a bug in Aves, or because the Android Media Store hasn't found them yet. Reinstalling Aves wouldn't help in either case.
> 
> Rebooting your device may help, as Android often triggers media scanning after boot (but that behaviour wildly varies across Android versions and phone makers).

So rebooting does work on the tablet , the Note does not need rebooting.
