### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by nwamugo** [deckerst/aves#761]
**Describe the bug**
The app randomly closes when I am using it, regardless of whether any button is pressed or not.

**To Reproduce**
1. Be inside the app
2. Do anything or do nothing at all
3. Maybe scroll or click one or two buttons
4. The app crashes.

**Expected behavior**
That the app works without crashing every now and then

**Screenshots**
Not applicable

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.9.3-play, build 104
Flutter: stable 3.13.1
Android version: 13, API 33
Android build: TKQ1.220829.002 test-keys
Device: Xiaomi 22081212UG
Geocoder: ready
Mobile services: ready
System locales: en_GB, en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Android/media/
Error reporting: true

**Additional context**
None

**Comment by deckerst** [comment]
Do you recognize your situation in either of these?
- #758 
- #722

**Comment by deckerst** [comment]
Also, please attach the exported logs from “About " > "Bug Report".

**Comment by nwamugo** [comment]
Yes, I recognize my situation in #758 

> Do you recognize your situation in either of these?
> 
> * [Crashes when catalouguing on A13 starting from 1.9.0 #758](https://github.com/deckerst/aves/issues/758)
> * [Opening a video in the viewer crashes the app #722](https://github.com/deckerst/aves/issues/722)

**Comment by nwamugo** [comment]
> Also, please attach the exported logs from “About " > "Bug Report".

[aves-logs-20230917_121710.txt](https://github.com/deckerst/aves/files/12642672/aves-logs-20230917_121710.txt)


The save button in the About > Bug Report has only worked once for me. Which is what I have attached here. It shows 0 B in my file manager

**Comment by nwamugo** [comment]
> Also, please attach the exported logs from “About " > "Bug Report".

[aves-logs-20230917_122931.txt](https://github.com/deckerst/aves/files/12642688/aves-logs-20230917_122931.txt)

**Comment by deckerst** [comment]
Could you try [this build](https://drive.google.com/file/d/111W4BfffaTyECRp1R7o1M6ADB7E_pyG3/view?usp=sharing) and let me know how it goes? It will install as a separate app called "Aves [Profile]". Also, cataloguing from scratch can take a while if you have many items, so you may want to enable notification permission to track cataloguing progress and know for sure when it's complete.

**Comment by nwamugo** [comment]
I have tried the build. So at first it crashed after spending some time in it, showing the same behavior as before. But then, I closed all open/background applications, and tried it again. And this time, the app stayed working with no crashing experience.

**Comment by deckerst** [comment]
I'll release soon another version with the fix.
Feel free to comment here if you still experience crashes later on.
