### ISSUE TITLE
Set Home to Camera folder option

### ISSUE THREAD

**Issue by tharubberchicken** [deckerst/aves#763]
This would be most useful for me, but also others who would like quick and direct access to their camera photos.

I know there is a shortcut on the side bar, but I like the idea of going directly to my camera photos, without seeing the other mess of images/folders I have on my phone. Especially if I'm showing other people my camera photos, in person.

Thanks so much if you can.

**Comment by deckerst** [comment]
In the meantime, do you know that you can create shortcuts? Open your Camera album, then in the top right menu select "Add shortcut".

**Comment by tharubberchicken** [comment]
Nice workaround. 👍🏻 This does the trick for the time being. Thank you.

**Comment by gety9** [comment]
@deckerst i see that issue is fixed. Could you please tell when it will be released? (available for download via gplay or here on GH in releases)

I want to set "screenshots" folder as home

**Comment by deckerst** [comment]
No fixed date or plan. I'll release when the time is right.
