### ISSUE TITLE
file corruption after modification

### ISSUE THREAD

**Issue by xunil89** [deckerst/aves#765]
**Describe the bug**
I assigned the location to a group of photos and twice the same problem occurred, two out of 12 photos were corrupted after editing, other users report corruption of photos after rotation. I found in the gallery many corrupt photos blamed the problem to a recovery after change rom but now I have doubts.

**To Reproduce**
Edit photo

**System information and logs:**

Package: deckers.thibault.aves
Installer: null
Aves version: 1.9.4-izzy, build 10501
Flutter: stable 3.13.4
Android version: 13, API 33
Android build: TQ3A.230805.001
Device: Xiaomi Redmi Note 9 Pro
Geocoder: ready
Mobile services: ready
System locales: it_IT
Storage volumes: /storage/emulated/0/, /storage/7CE6-CEE1/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Download/Nekogram/, /storage/7CE6-CEE1/storage/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/storage/, /storage/emulated/0/Android/media/
Error reporting: false

[aves_issue765_20230918.log](https://github.com/deckerst/aves/files/12709619/aves_issue765_20230918.log)

**Comment by deckerst** [comment]
Did it happen with WEBP files, by any chance?

Aves v1.9.4 includes a fix to prevent corruption when editing some WEBP files, addressing this issue:
- #721

If it happens with other files, were you possibly low on storage?

Also, do you use a custom ROM?

**Comment by xunil89** [comment]
The files were simple jpg, space I had enough, the rom is a crdroid based on los android 13

18 set 2023 23:25:54 Thibault Deckers ***@***.***>:

**Comment by deckerst** [comment]
I can't reproduce the issue myself, but I've added some check to prevent corrupting the file if the modified image with the EXIF edits can't be decoded. In that case it will report failures, but the images should be safe.

I will try and make a release soon. If you still experience this issue afterwards, please let me know here, with as much details as possible.

**Comment by xunil89** [comment]
the bug seems fixed🫵👍!
