### ISSUE TITLE
Add a "Show hidden" toggle button

### ISSUE THREAD

**Issue by Spaceman333** [deckerst/aves#767]
Currently the app shows everything - every album, every picture by default.
I have a lot of albums that I'd like to keep hidden by default, but have the option to view them all at once sometimes. 

The problem with the existing "Hide" feature is that theres no middle ground. If I hide something, I have to go through several button presses to reveal it, then once I'm done I have to go through the process of hiding it again.

What'd id like instead is to just Hide everything I want hidden and keep it hidden by default, but when I want to view them, I could press the ... button and then select "Show hidden" to reveal all hidden albums for as long as I keep the app open or press "Show hidden" again to reverse the toggle. If I close the app, it should default back to hiding them all.

**Comment by deckerst** [comment]
I won't do that, but i think your use case (and others) will be addressed by the broader solution of profiles:
- #520

**Comment by Spaceman333** [comment]
> I won't do that, but i think your use case (and others) will be addressed by the broader solution of profiles:
> 
>     * [Settings profiles / Ability to exclude albums from Collection #520](https://github.com/deckerst/aves/issues/520)

Nice! That's way better and more flexible. That'd allow me to hide/reveal multiple album groups based on what I want to browse at any given time.
