### ISSUE TITLE
Slideshow transition is always "slide"

### ISSUE THREAD

**Issue by Driexus** [deckerst/aves#769]
**Describe the bug**
Slideshow transition is always "slide" regardless of the selected choice.

**To Reproduce**
1. Go to an album
2. Click slideshow
3. Click options
4. Select any transition other than "slide"
5. Click back
6. Click play

**Expected behavior**
Slideshow transition should be as selected (e.g. "fade") instead of "slide".

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.9.5-play, build 106
Flutter: stable 3.13.4
Android version: 10, API 29
Android build: QKQ1.200114.002 test-keys
Device: Xiaomi Redmi Note 8
Geocoder: ready
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

[aves-logs-20230920_143754.txt](https://github.com/deckerst/aves/files/12672601/aves-logs-20230920_143754.txt)

**Extra context:**
The app was installed for the first time so I am not sure if I clicked everything correctly, but I guess this should not be the expected behavior.

**Recording:**

https://github.com/deckerst/aves/assets/72216504/a9b6e092-2057-4180-8596-57f921c24e40

**Comment by deckerst** [comment]
I've just tried and it works for me. Could you take a screen recording, just to be sure we're on the same page?

**Comment by Driexus** [comment]
Added screen recording to bug description.

**Comment by deckerst** [comment]
The logs don't say much :/

If you don't mind, could you enable error reporting (Settings > Privacy > Allow anonymous error reporting) and reproduce the issue a couple of times? Hopefully I can see something in these automatic reports from Crashlytics.

Also, do you use a custom ROM?

**Comment by deckerst** [comment]
@Driexus Could you please install this build and let me know whether the issue is fixed?
[aves-play-profile_769_20231220_2300](https://drive.google.com/file/d/1OyQALZlJqdHYGH_FFQH2GJoklDDNCinE/view?usp=sharing)

**Comment by lalalasupa0** [comment]
This happens to me. In two of devices, actually (motorola one 5g and a s10e. Dunno if both logs and testings are necessary, so I'll just include the s10e one rn)
Same thing issue has:
(recording) https://github.com/user-attachments/assets/db976878-61bf-41bf-a943-d7e38a6177f4

> Settings > Privacy > Allow anonymous error reporting and reproduce the issue a couple of times?

I did that, in each "page" of Aves (All, Albums, Videos, Tags, etc):

[aves-logs-20251223_232054.txt](https://github.com/user-attachments/files/24322676/aves-logs-20251223_232054.txt)

```
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.13.11-play, build 162
Flutter: stable 3.27.4
Android version: 10, API 29
Android build: QP1A.190711.020.G970USQU4ETH7
Device: samsung SM-G970U
Display: pixel ratio=2.34375, logical=460.8x972.8, physical=1080.0x2280.0
Support: dynamic colors=false, geocoder=true, HDR=true, wide gamut=true
Mobile services: ready
Connectivity: vpn, mobile
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: true
```

It happens with any kind of image and video and amount of items in album. Happens in individual albums and—anywhere in the app
