### ISSUE TITLE
Cannot delete vault folder

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#771]
**Describe the bug**
A created a vault just to try it out. I copied some images to the vault, but then deleted them. The vault is empty and contains no images. Deleting it does nothing.

**To Reproduce**
1. Go to the vault
2. Delete all images in the vault
3. Delete the vault folder itself

**Expected behavior**
Vault should be deleted

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.looker.droidify
Aves version: 1.9.5-izzy, build 10601
Flutter: stable 3.13.4
Android version: 12, API 32
Android build: lineage_raphael-userdebug 12 SQ3A.220605.009.A1 eng.seba.20220707.103313 test-keys
Device: Xiaomi Mi 9T Pro
Geocoder: not available
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: false

**Comment by Donkey-Doug** [comment]
Update: I needed to delete the files in the recycle bin that originated from the vault first. After that I could delete the vault. This is not very user friendly. I think a popup stating "If you delete this folder, all corresponding files in the recycle bin will also be deleted" is better.

**Comment by deckerst** [comment]
I disagree, and you found out by yourself how it worked, without any extra explanation requiring translation for dozens of languages.
