### ISSUE TITLE
Start a community driven Wiki

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#773]
Today I set up aves on another phone and I spent a good 20 minutes trying to find the mosaic view. 
I think this is a good indication that the app needs some sort of documentation beyond the CHANGELOG.
How do you feel about this? it wouldn't have to be solely maintained by you

edit: *right here in GitHub with the wiki feature

**Comment by deckerst** [comment]
I've just changed the wiki settings so that it's publicly editable (if I understood it correctly).
That said, if I see that I need to spend time to take care of misbehaviour there, I'll revert the settings.
