### ISSUE TITLE
Improper Image Manifestation (Flaws That Aren't In Other Gallery / Image Viewers)

### ISSUE THREAD

**Issue by mitchwalton** [deckerst/aves#775]
**Describe the bug**

It's really rare but some images aren't shown in the gallery properly at full screen.

**To Reproduce**

1. Go to image
2. Click on image until full screen
3. Image isn't properly depicted in full screen. The photo I give beneath has a white line beneath the photo in Aves not present in other apps. This has happened with other photos in different ways such as showing artifacts but very rare.

**Expected behavior**

The photo should be shown properly.

**Screenshots**

![Screenshot_20230925-095753_Aves](https://github.com/deckerst/aves/assets/123303123/97defb04-9787-471e-88f3-464be9e5ecdc)

**System information and logs:**

[aves-logs-20230925_100243.txt](https://github.com/deckerst/aves/files/12716036/aves-logs-20230925_100243.txt)

I wound up clearing Aves cache and data before I copied the logs to see if it fix my problem but it did not. I hope this isn't a problem as I should of copied Aves logs before I did that. However, I went to the photo that's being depicted wrong before I copied the logs. I'm not sure if that helps or I screwed things up for you over not much info being logged.

**Additional context**

https://postimg.cc/vxGTPGMT

Here is the link to the actual photo in my gallery. I couldn't upload it on Github because it's a .webp.

**Comment by deckerst** [comment]
Image formats that can be transparent (like WEBP) are rendered in Aves on top of a background layer that users can customize (between white, black, and checkers) in Settings > Viewer > Image Background. For you i suppose it's white.

I need to check your image but it can be either:
- a rounding error in Aves that makes the background layer slightly too large at the bottom, or
- your image is really transparent at the bottom, and in that case, seeing the background layer below is not a bug.

**Comment by mitchwalton** [comment]
Ok, thanks. Changing the background layer fixed it. I'm a huge .webp fan as it's better technology than .jpg. However, don't take this as a guarantee but I'm pretty sure all the ones that I viewed off were my .webp. I do alter images in GIMP and RawTherapee but don't remember ever doing anything to cause this. It's obviously a mistake on my end as like I said this happens rare. I'm no photographer so I'm ignorant on what your saying. However, I can get my way around GIMP and always save my files on export without saving layers. However, in RawTherapee I often export in .tiff and then master in GIMP so it's likely that I've accidentally saved layers going from lossy to lossless then back to lossy to prevent quality loss on big / mild editing as both programs have filters that are incredible. I'm sorry to blow up your bug reports if it's all me. I'm all ears for further info.
