### ISSUE TITLE
Showing .ts (typescript files) in library

### ISSUE THREAD

**Issue by Robin-Sch** [deckerst/aves#778]
**Describe the bug**
Typescript files are shown like images (with a placeholder banner saying MP2TS).

**To Reproduce**
1. Create a file called test.ts
2. Open the app

**Expected behavior**
The typescript file should not show up in the gallery, since it's a typescript (code) file and not an image.

**System information and logs:**
Aves 1.9.5-libre (from f-droid)

**Comment by deckerst** [comment]
If the Android media store thinks it is a media, Aves will list it, whether Aves can play it or not.
In your case, the media store gets it wrong.
You can easily hide your code in Aves, cf Settings > Privacy > Hidden items > Hidden paths.

**Comment by Robin-Sch** [comment]
Thank you!
