### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#78]
Make it possible to show the albums and images in a list view. This could simply be achieved with the pinch gesture to increase/decrease the number of columns. Currently the minimum amount of columns is 2. I suggest allowing 1 column.

**Comment by deckerst** [comment]
The way you describe it as 1 column sounds like you want this:
<img src="https://user-images.githubusercontent.com/13898333/135556070-40668e69-f966-4bcc-9ba2-c1e6e00291f0.png" height="400" />

However, "list view" in this context usually means something like this:
<img src="https://user-images.githubusercontent.com/13898333/135556133-e8aaa2e8-de9c-4ed6-8db7-ce8735507100.png" height="400" />

I intend to make the latter someday. Do you really mean the former?

**Comment by Donkey-Doug** [comment]
I mean the latter, a.k.a. list view.

**Comment by Donkey-Doug** [comment]
Actually, maybe also make it possible for the images themselves and not just the albums. I suggest consistent behavior in all views. It would otherwise be annoying if some features are only available in some places.
