### ISSUE TITLE
add a default basic edit image

### ISSUE THREAD

**Issue by Ullash58** [deckerst/aves#787]
**Is your feature request related to a problem? Please describe.**

I frustrated When I try to crop image a rotate image and save it 
it is not possible by default when I click in edit image button its suggest me to open edit image software which is present in my phone like markup or any other editing software 

**Describe the solution you'd like**

add Crop and Clean Up Your Images. ...
Adjust the White Balance. ...
Adjust Exposure and Contrast. ...
Adjust Color Vibrancy and Saturation. ...
Adjust Sharpness. ...
Finalize and Share Your Photos.
rotate image
basically by default editing tool which is present in your app

**Describe alternatives you've considered**
Some kind of plugin if anyone wants to use in your app then install that plugin and they can easily able to edit images  if they cannot install then they use any software which they have

**Additional context**
I am not saying that you have to give a any advance kind of photo editing software or any kind of editing software just a basic editing software which present in all kind of gallery like Samsung gallery,  MI gallery, oppo gallery, Vivo gallery, every gallery have their own editing software 
so just a basic editing software not too much hard like a basic crop edit basic software thats it

**Comment by deckerst** [comment]
Duplicate:
- #17
