### ISSUE TITLE
Improvement to rename feature

### ISSUE THREAD

**Issue by marciozomb13** [deckerst/aves#790]
I would like to suggest some tweaks to rename feature:

1) Ability to set the amount of digits of a counter placeholder (01, 001, 0001, etc)

2) Ability to set the initial number on counter and save the results after the operation - if I renamed 10 images, the next batch will start with 11 automatically.

**Comment by deckerst** [comment]
It's undocumented, but you can already specify both the padding and the initial number, by editing the naming pattern, which is originally simply `<counter>`.

For example, setting the initial number as `11` and setting a padding of `4` (to get `0011`):
`<counter, start=11, padding=4>` 

As for saving the last count to resume with the next batch, I won't do that.
