### ISSUE TITLE
Hardened malloc / App crashes when I try to open a Video

### ISSUE THREAD

**Issue by samuelps26** [deckerst/aves#791]
When I try to open a video from the gallery overview the app crashes.
This happenes since I updated from version 1.9.3 to 1.9.5. Also with the latest update (1.9.6) I can't open videos. Even version 1.9.3. doesn't work anymore.

I am now on Android 14 but even on 13 it didn't work.

I uploaded the system information and logs in a txt file to my cloud. Because it's to long to paste it here...
Here you can find the logs:

Thanks for your help!

**Comment by deckerst** [comment]
Would this apply to you?
- #722

**Comment by samuelps26** [comment]
Thank you very much. Enabling the toggle "disable_hardened_malloc" worked perfectly!
