### ISSUE TITLE
Capture Frame Function No Longer Working

### ISSUE THREAD

**Issue by quinb96** [deckerst/aves#799]
**Describe the bug**
Starting on version 1.9.0, the capture frame function stopped working. I have a Samsung Galaxy A13 5G running Android 13.
Version 1.8.9 was the last version that this function worked.

**To Reproduce**
1. Select a video.
2. Tap the capture frame button
3. Nothing happens.

**Expected behavior**
To take a picture of the current frame of the video.

**Screenshots**
No screenshots since absolutely nothing happens.

**Comment by deckerst** [comment]
With the new video engine introduced in Aves v1.9.0, the frame capture process takes a lot more time (several seconds), but it should still work. I know that's not great, but just to be sure, could you confirm whether it actually does not work, or it's just unbearably slow?

**Comment by quinb96** [comment]
> With the new video engine introduced in Aves v1.9.0, the frame capture process takes a lot more time (several seconds), but it should still work. I know that's not great, but just to be sure, could you confirm whether it actually does not work, or it's just unbearably slow?

It 100% is not working at all. At least on my device it's not. I've tried versions 1.9.0 to 1.9.5 and the function never worked on any of those versions. 1.8.9 is the farthest back I'm able to go before it works. I noticed this issue either on 1.9.4 or 1.9.5.

**Comment by deckerst** [comment]
Ok, then could you follow instructions in `About` > `Bug Report`, and attach here your system info and logs?

**Comment by quinb96** [comment]
Package: deckers.thibault.aves
Installer: null
Aves version: 1.8.9-izzy, build 10001
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: TP1A.220624.014.A136USQU6DWI3
Device: samsung SM-A136U
Geocoder: ready
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/02FE-E4BF/
Storage grants: /storage/02FE-E4BF/DCIM/
Error reporting: false

**Comment by deckerst** [comment]
And the logs? Best is to save the logs right after trying to capture a frame.

**Comment by deckerst** [comment]
I see in the logs an issue coming from the video engine I'm using. I'd like to report that issue to the developer of that engine, but it may be specific to some video formats. Could you provide me with a short sample of a video with which you have the problem?

**Comment by quinb96** [comment]
Sorry for taking so long to respond. I'll do this for you tomorrow.
