### ISSUE TITLE
Please support avif!!!

### ISSUE THREAD

**Issue by Mario-Hero** [deckerst/aves#801]
The avif files are much smaller than jpg, so I convert almost all my photos to avif. They can be opened on PC by XNView MP, but on Android, there are few apps support avif.
Please support avif!!!

**Comment by deckerst** [comment]
Aves can already show AVIF from Android 12. Animated AVIF are also supported. Editing metadata is not (like a lot of exotic formats).

What kind of support do you need?

**Comment by Mario-Hero** [comment]
show AVIF on Android which version is lower than 12.
I'm using Huawei and it doesn't support install other OS.

**Comment by deckerst** [comment]
Oh, i see. I don't intend to work on that. In general it's not great to work with new formats on old devices. Anyway this problem will solve itself with time.
