### ISSUE TITLE
Blank slideshow

### ISSUE THREAD

**Issue by plneappl** [deckerst/aves#803]
**Describe the bug**
In slideshow, on the first image or when I bring up the slideshow controls, the image is shown only for a few frames, then only black is shown.
Device: Zenphone 8, Android 13
Aves version: 1.9.7 F-Droid

**Screenshots**
Video attached

https://github.com/deckerst/aves/assets/4385742/d75c967d-fe2c-4ad0-b02d-c7d7f0f61921

[aves-logs-20231028_205206.txt](https://github.com/deckerst/aves/files/13196525/aves-logs-20231028_205206.txt)

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.9.7-libre, build 10802
Flutter: stable 3.13.7
Android version: 13, API 33
Android build: TKQ1.220807.001.33.0210.0210.314 release-keys
Device: asus ASUS_I006D
Geocoder: ready
Mobile services: not available
System locales: en_US, de_DE
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Comment by DroidFloyd** [comment]
I'm facing the same issue too on Galaxy A71F android 13. Been a long standing issue, thought I was alone.

The animated zoom effect is also not buttery smooth, has a frame stop of at least 500mseconds, makes the slideshow not look seamless and choppy.

Would appreciate a bokeh effect on media in slideshow to give a more fuller and more immersive viewing experience.🙏🏼

Video also not seamless in slideshow, as it shows 1 second of still video frame before playing the video. (Would love a feature for making all videos play to the end in slideshow before skipping, also with gifs as well.🙏🏼)

Good day dev. 🙏🏼

**Comment by OmlineEditor** [comment]
it seems to me that the next image that needs to be shown has not been loaded into memory yet and therefore there is a delay. there is nothing on the screen because the picture has not loaded. it is necessary to proactively start reading in advance. before switching the picture, you need to open and read the following picture
