### ISSUE TITLE
Haptic feedback - Vibration while selecting images / folders 

### ISSUE THREAD

**Issue by Aswin8** [deckerst/aves#805]
**Is your feature request related to a problem? Please describe.**
Not a problem but a improved user experience 

**Describe the solution you'd like**
It would be great if you could add a haptic feedback - Vibration while selecting images / folders 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by deckerst** [comment]
Would you know another gallery that does this? No need to be open-source, it's just for me to experience.

**Comment by Aswin8** [comment]
> Would you know another gallery that does this? No need to be open-source, it's just for me to experience.

F-Stop Gallery
Google Photos

Even most other apps while we long press and select an item-
Gmail
Mixplorer.

Probably ill rephrase what i mentioned in the main post - 'While long pressing and selecting an item - Photo,Folder,..'

Perfect open source example for this haptic feedback- https://github.com/IacobIonut01/Gallery

**Comment by Aswin8** [comment]
sorry closed it unknowingly.

**Comment by deckerst** [comment]
I wasn't feeling the haptic feedback in Google apps, but felt it in `IacobIonut01/Gallery`. So I looked a bit and I had it disabled at the OS level (on my Samsung device it's in Settings > Sounds and vibration > System sound/vibration control >  Vibration > Touch interactions). After enabling it, I felt it in the Google apps too.

Anyway, it tells me 2 things:
- `IacobIonut01/Gallery` could be improved by respecting the OS setting,
- if I implement it in Aves, I should respect it too.

**Comment by Aswin8** [comment]
Great, excited to try it.
