### ISSUE TITLE
Error while deleting images 

### ISSUE THREAD

**Issue by KnownTomato5056** [deckerst/aves#806]
**Describe the bug**
When I press the delete button, error pops up saying, "The system file picker is missing or disabled, please enable it and try again" 
The problem is native to this application. The default gallery AND the 'Simple Galary' works just fine.

**To Reproduce**
1. Open aves gallary
2. Click on image
3. Press the delete button

**Expected behavior**
The photo should move to recycle bin without much hassel

**Screenshots**
![Screenshot_20231102-165843](https://github.com/deckerst/aves/assets/85822989/5194227f-92d0-456e-9f4b-bb06f3a00d5a)
![Screenshot_20231102-165857](https://github.com/deckerst/aves/assets/85822989/427931db-a255-49be-8eed-60ad7a389b26)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.9.7-play, build 108
Flutter: stable 3.13.7
Android version: 13, API 33
Geocoder: ready
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Comment by deckerst** [comment]
Please attach the logs, too.

Do you use a custom ROM, or use a rooted device?

**Comment by KnownTomato5056** [comment]
The issue has been resolved, seems there was a problem in android filemanager which a quick reinstall fixed
