### ISSUE TITLE
Motion Picture/Photo not recognized

### ISSUE THREAD

**Issue by uizore** [deckerst/aves#808]
**Describe the bug**
The motion pictures from my pixel 8 with google pixel camera are not recognized by aves, they only show up as simple picture.

**To Reproduce**
Open the attached picture.
![PXL_20231028_134942358_ MP](https://github.com/deckerst/aves/assets/150226562/97df1c43-f268-4518-933a-9454d0c42c4c)

**Expected behavior**
Aves should detect the pictures as motion pictures :)

**Screenshots**
![Screenshot](https://github.com/deckerst/aves/assets/150226562/f772454b-54b3-4931-9607-ce4517785fe5)

**System information and logs:**
GrapheneOS

Package: deckers.thibault.aves 
Installer: com.android.vending 
Aves version: 1.9.7-play, build 108 
Flutter: stable 3.13.7 
Android version: 14, API 34 
Android build: UD1A.231105.004.2023110700 
Device: Google Pixel 8 
Geocoder: not available 
Mobile services: ready 
System locales: de_DE 
Storage volumes: /storage/emulated/0/ 
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/ 
Error reporting: false 

**Additional context**
Some time ago there was a similar issue with pixel 4?
https://github.com/deckerst/aves/issues/304

**Comment by deckerst** [comment]
Until the next release, please be careful. If Aves does not recognize them as motion photos, editing them may make the video part inaccessible in the future.

**Comment by uizore** [comment]
Wow, thanks for the quick fix.
I will keep that in mind.
Plesse keep up the good work, I really like the app!
