### ISSUE TITLE
Files delete slowly

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#809]
Files take a while to delete, progress bar counts to 100% without being able to interact with the app until the operation is over and at times will restart and count to 100 again in the same operation.
I think this may be a reproduced bug, I tried searching at first (not extensively.)👍🏼

**Comment by deckerst** [comment]
> Files take a while to delete

Yes, because Aves is not a file manager it does not have direct file access. Contrary to file managers, gallery apps must rely on other media-related APIs, which take time to move/delete files. 

> at times will restart

Sometimes deleting can be in 2 steps, when it's moving the items to the bin and you configured Aves to let it preserve dates when moving items. In that case, there will be a first step to edit the metadata, then another step to move it to the bin, so you see the progress indicator going from 0% to 100% twice.

**Comment by e-t-l** [comment]
> > Files take a while to delete
> 
> Yes, because Aves is not a file manager it does not have direct file access. Contrary to file managers, gallery apps must rely on other media-related APIs, which take time to move/delete files.

That's understandable, but doesn't change the fact that it can take a significant amount of time to delete a large file, like a video, during which the app is completely unusable. (And I *like* using your app! It makes me sad when I can't use it!)

Would it be possible to move the delete operation to a background process so that the app can remain interactable while delete operations are occurring?

**Comment by deckerst** [comment]
[Play Store policy](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en#zippy=%2Crecommended-privacy-friendly-alternatives%2Cexceptions%2Cpermitted-uses-of-the-all-files-access-permission%2Cinvalid-uses)

> When should you request the All files access permission?
> You should only access the All files access permission when your app cannot effectively make use of the more privacy-friendly [best practices](https://developer.android.com/training/data-storage#scoped-storage), such as the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) or the [MediaStore API](https://developer.android.com/training/data-storage/shared/media).

> Invalid uses
> Below is a list of common use cases that won't be permitted to request the MANAGE_EXTERNAL_STORAGE permission
> - Media Files access (see [Alternatives](https://support.google.com/googleplay/android-developer/answer/10467955#alternatives) below)

**Comment by e-t-l** [comment]
> > You should only access the All files access permission when your app cannot **effectively** make use of the more privacy-friendly best practices

It seems like "the app goes totally unresponsive when attempting a normal file operation" puts Aves squarely in the realm of "cannot effectively make use of other methods." 

> some stores reject gallery apps relying on it.

Which stores? I understand your hesitation to use more powerful methods, but given that Fossify Gallery is permitted on the Play Store, it also seems safe for Aves to use it. Is there a store besides the Play Store that you're concerned about?

**Comment by ryanwwest** [comment]
I run into this same slow deletion problem all the time, every day. For me it's just the fact that sometimes I wait 20 seconds for the delete ui to disappear (usually more like 1 second). I don't really care if it takes 20 seconds, but what I want is the ability to instantly continue browsing in the app - maybe some in-app notification can confirm when it is actually deleted instead?

**Comment by e-t-l** [comment]
> but what I want is the ability to instantly continue browsing in the app

You're probably looking for issue #750, then

> I do agree with their policy. Other users also wrote to tell me that they were happy that Aves does not request this abusive permission

Look, I do agree with you, it is definitely best to work with minimal permissions necessary. I respect the desire to avoid **invasive** permissions (not "abusive"; there is nothing inherent about a permission that makes it abusive. Some permissions may be *easily abused* by malicious devs, but that's a whole different problem!) and I respect users' desire not to grant invasive permissions. 

But that's exactly what it is: a *permission*, right? Why not give users an *option* to use All Files Access for efficient file operations. There can be a disclaimer that this permission does grant Aves more extensive capabilities, and that granting it is *totally optional.* It's the best of both worlds: Users who grant the permission will get faster, more performant file operations, while those who reject it will get Aves working exactly the same as it currently does.

I'm not trying to push you towards invading users' privacy or compromising your morals. I'm just trying to find a way to keep using Aves in situations where it is, in its current state, unfortunately completely unusable.

**Comment by deckerst** [comment]
Related:
- #2144

**Comment by deckerst** [comment]
Current state of API usage to move items: https://github.com/deckerst/aves/issues/2144#issuecomment-5584806163
