### ISSUE TITLE
Hide raw photos

### ISSUE THREAD

**Issue by nearapogee** [deckerst/aves#810]
**Is your feature request related to a problem? Please describe.**
My thumbnail view is cluttered with RAW photos.

**Describe the solution you'd like**
I'd like a global toggle for RAW photos being displayed when viewing collections. It would be even better if RAW icon would show only when there is a RAW version of the same photo and tapping it would let me access it. I only need RAW when I transfer to my computer.

**Describe alternatives you've considered**
Looked through all the filters. Found where I can filter for RAW but not "not RAW".

**Additional context**
Love the app.

**Comment by deckerst** [comment]
I won't add a special toggle for this, but I believe you can already get what you want with the current features.

A couple of things you can do:
1) For any filter, you can long press on it and select "filter out" to reverse it. So, with the "RAW" filter you found, the "filter out" would make it a "non-RAW". 
2) If you don't want to do this every time, you could long press the "RAW" filter and select "hide". This will hide all RAW within Aves. If you need to show them again, go to `Settings` > `Privacy` > `Hidden items`.
