### ISSUE TITLE
Work profile / Decoding issue following Harmony OS upgrade

### ISSUE THREAD

**Issue by FarAhead-Huawei** [deckerst/aves#813]
**Describe the bug**
尊敬的作者大大！
你好！我的手机是鸿蒙系统，我不超过一周前没更新的时候还能看的，不知道为什么突然就不能点击略缩图进行查看了，我手机自带的华为相册和下载的谷歌相册以及各种文件管理器自带的查看器都能看图片，而我以用aves点到图集里面的图片放大看就出来一个大大的感叹号和糟糕两个字并且黑屏，我的所有权限的给了也尝试安装了不同的版本、安装包，各种方法都试过了就是无法生效！

**To Reproduce**
进入相册
点开具体的图片

**Expected behavior**
出现黑屏、感叹号和糟糕这个词

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**

Package: deckers.thibault.aves
Installer: org.localsend.localsend_app
Aves version: 1.9.7-play, build 108
Flutter: stable 3.13.7
Android version: 10, API 29
Android build: TEL-AN00a 3.0.0.165(C00E165R4P2)
Device: HUAWEI TEL-AN00a
Geocoder: not available
Mobile services: not available
System locales: zh_Hans_SG
Storage volumes: /storage/emulated/0/
Storage grants: 

Error reporting: false

**Additional context**
你们的软件是我所知道的最好的！我试过了我能在国内外各种大小开源商店中我能找到的所有同类软件，毫无疑问你们的软件是最好的！除了没有上传云端功能外简直完美！ 但是很抱歉！我没有国外的账户不知道该怎么赞助你们，
[aves-logs-20231119_233618.txt](https://github.com/deckerst/aves/files/13403678/aves-logs-20231119_233618.txt)
这是AVES
![Snipaste_2023-11-20_00-05-07](https://github.com/deckerst/aves/assets/151452455/6dcf5d2d-408a-4c38-af29-ae4ce33d6ec1)

这是系统自带相册
![Snipaste_2023-11-20_00-02-24](https://github.com/deckerst/aves/assets/151452455/124d0d8d-715d-4b31-a314-4bf896c1e357)
这是谷歌相册
![Snipaste_2023-11-20_00-04-11](https://github.com/deckerst/aves/assets/151452455/bea17f82-2819-4f3d-8330-1525690d9c4d)

**Comment by deckerst** [comment]
> 我不超过一周前没更新的时候还能看的

Could you please clarify whether 1) you updated HarmonyOS, or 2) you updated Aves?

Do you have the issue with all images? Or some specific files?

**Comment by FarAhead-Huawei** [comment]
更新了aves   
所有图像都打不开

**Comment by FarAhead-Huawei** [comment]
视频没问题

**Comment by deckerst** [comment]
Do you know which version of Aves you had before which was working fine?

**Comment by FarAhead-Huawei** [comment]
应该是上个版本，具体记不太清了，我看了下上次的版本是9月份更新的那么应该就是这个版本。

**Comment by deckerst** [comment]
Could you please confirm things are ok when you reinstall and view images with Aves v1.9.6:
https://github.com/deckerst/aves/releases/download/v1.9.6/app-play-release.apk

Because it's a downgrade, you probably need to uninstall v1.9.7 before trying to install v1.9.6. Also, make sure you disabled automatic upgrade for Aves in the Play Store.

**Comment by FarAhead-Huawei** [comment]
没用，还是一样的，我也没有GMS

**Comment by deckerst** [comment]
GMS is not necessary to decode images, so don't worry about the flavor of Aves: you can install the `play`, `huawei`, `izzy` or `libre` flavor, it doesn't matter.

But i need to know whether an older version of Aves works in your current environment. You said at the top that it used to work, but i need to know which version precisely. You can try previous releases from the [releases page](https://github.com/deckerst/aves/releases).

By the way, are you sure that the images failing to display are not obsolete images? Sometimes when moving files with badly written apps, the Media Store is not updated and obsolete images remain for a while.

**Comment by FarAhead-Huawei** [comment]
我发现放在在工作模式的分身可以正常使用了，只是会有一些卡顿。
![image](https://github.com/deckerst/aves/assets/151452455/848b4ee4-efa4-4f62-80c2-332d8a1e7b9e)

**Comment by deckerst** [comment]
@FarAhead-Huawei Do you still experience this issue with the latest Aves v1.11.13? If so, could you please share the logs you get with that version?

By the way, I checked how work profiles work and they're like sandbox, with their own storage and media list, which is different from the storage and media visible in the regular user profile. In your case, the work profile and the user profile access the same media as if it were common to both?
