### ISSUE TITLE
incorrect date for panorama photos

### ISSUE THREAD

**Issue by GuitarBilly** [deckerst/aves#814]
hello!
i am a happy user of Aves. I have searched for this issue but I could not find it.

**Describe the bug**
all my panorama photos that i create with the phone have an incorrect date and are therefor sorted on top of anything else in Aves.

**To Reproduce**
1. open camera app.
2. make a panorama in any size and any direction
3. open aves 
4. find the panorama on top of normal photos as the date is wrong and the year is > 2500 with 4 or 5 digits i.e. Aug 10577.

**Expected behavior**
Aves should recognize the correct date or in case of incompatible Exif data fall back to other options like file creation date.
If the phone date is 2023 then any newly processed file should not have a date too much in the future.

**Screenshots**
i made a very quick example panorama from the Aves github site.
![IMG_20231120_132721](https://github.com/deckerst/aves/assets/38086529/d9598215-ac1b-4402-8aa5-cfa378293781)
![Screenshot_20231120-133033](https://github.com/deckerst/aves/assets/38086529/533c4a7d-bec2-4c7c-9d61-f9bb4e7b5885)
![Screenshot_20231120-133054](https://github.com/deckerst/aves/assets/38086529/c74f9982-beda-49ee-ab3f-df65c5ece13e)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.9.7-play, build 108
Flutter: stable 3.13.7
Android version: 7.1.2, API 25
Android build: 00WW_3_7OE
Device: HMD Global TA-1033
Geocoder: ready
Mobile services: ready
System locales: en
Storage volumes: /storage/85AC-1F1A/, /storage/emulated/0/
Storage grants: /storage/85AC-1F1A/
Error reportting: false

**Additional context**
This is a 2018 Nokia 6 phone.
When i use another gallery app like Simple Mobile Tools it sorts panorama dates correctly but i cannot confirm if that app uses exif data or plain file date.

=== end ===

**Comment by deckerst** [comment]
The Exif date field value in your file is a timestamp (in milliseconds) while it's supposed to be text like `2023:10:28 15:49:42⁩`. I'll check why Aves interprets it with such creativity.
