### ISSUE TITLE
Stamen Toner and Watercolor

### ISSUE THREAD

**Issue by opk12** [deckerst/aves#820]
Thank you for this great app. I do not use the Stamen feature personally, but in the context of Stamen Toner being removed and Stamen Watercolor being pointed to the Smithsonian Institution ([1.9.7 changelog](https://github.com/deckerst/aves/blob/develop/CHANGELOG.md#v1.9.7), [commit](https://github.com/deckerst/aves/commit/817bc4bc1e0dcdc0f2a9b6012b2d384467e8ef54)), I thought you'd want to know that the two updated URLs to the new hosting at Stadia Maps are listed [here](https://wiki.openstreetmap.org/wiki/Raster_tile_providers#Base_maps) (OpenStreetMap Wiki), with info about pricing (free for non-commercial projects under 200K tiles / month).

**Comment by deckerst** [comment]
Thanks. I was aware of the Stadia Maps hosting, but I don't want to add an API key and have quotas for these layers.
