### ISSUE TITLE
.mov playback is slow

### ISSUE THREAD

**Issue by idontveapc** [deckerst/aves#825]
**Describe the bug**
> A clear and concise description of what the bug is.

- i was playing a .mov file, and it's duration is 20secs. but the whole playback takes a minute to complete!

**To Reproduce**
> Steps to reproduce the behavior:
1. Go to 'videos'
2. Click on 'a mov video/file'
3. Scroll down to 'nothing'

- it might the .mov file
  - or any .mov file may be

**Expected behavior**
> A clear and concise description of what you expected to happen.

shouldn't play slow...

**Screenshots**
> If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

- the link to the .mov file:
  - [link](https://drive.google.com/file/d/1fofXXn4NAZhS-wmyr6S4tQJ8--exZNRV/view?usp=sharing)

**System information and logs:**
> In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**
> Add any other context about the problem here.

**Comment by deckerst** [comment]
I think these samples get downloaded at first, but then you should see the menu and what i described.

If your device and the test app get stuck at the loading screen, there's likely something wrong with your device (and maybe that's why you have issues with Aves too).

**Comment by deckerst** [comment]
Then i suggest you open an issue there, providing the video and details about your device.

I'll close this issue as it's out of the scope of Aves itself.
