### ISSUE TITLE
Moved files are not detected any more

### ISSUE THREAD

**Issue by opk12** [deckerst/aves#829]
**Describe the bug**
If a file is moved, Aves does not see it any more. It sees it at the old location, just unavailable.

**To Reproduce**
1. Download an image.
2. Open Aves, check that it appears.
3. Using a file manager, rename the directory that contains the image, or move the image in another directory.
4. Aves now says that the image does not exist.
5. Rescanning from the hamburger menu, and force-closing the app from the Android settings, do not solve it.

**Expected behavior**
Aves its info automatically or when rescanning.

**System information and logs:**
Aves 1.9.7 (10804) from F-droid on Samsung Android 11 and Samsung Android 7.1

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/wiki/FAQ#why-does-aves-show-thumbnails-with-a-broken-image-symbol

Isn't the file manager app that's moving the file without updating the Media Store, as it should?

**Comment by opk12** [comment]
Hello, I now changing to Simple File Manager and I get the same result. Simple Gallery shows the images at the new locations.

**Comment by deckerst** [comment]
Duplicate:
- #760
