### ISSUE TITLE
Why Aves Libre takes time to get uploaded on F-Droid?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [deckerst/aves#834]
While Aves get uploaded on GitHub & F-Droid on the same day, Aves Libre takes 3-4 days to get uploaded on F-Droid from the date of getting uploaded on GitHub.

I can wait 3-4 days. I can wait even a week.

But what is the technical reason behind this delay?

**Comment by deckerst** [comment]
That's because of F-Droid building process, you can read about it on their FAQ. You see the other flavor right away because it is hosted by Izzy, which does not build the apps but simply redistribute already built APKs.

**Comment by Aryan-Chauhan** [comment]
> That's because of F-Droid building process, you can read about it on their FAQ. You see the other flavor right away because it is hosted by Izzy, which does not build the apps but simply redistribute already built APKs.

Got it.

Any reason for Aves Libre not being on IzzyOnDroid?

**Comment by deckerst** [comment]
If the libre flavor was also distributed by Izzy, it would be redundant. The izzy flavor of Aves is a middle ground between the play and libre flavors. You can check out the version differences in the FAQ.
