### ISSUE TITLE
Unable to view documents properly

### ISSUE THREAD

**Issue by lianzhoulu** [deckerst/aves#835]
**Describe the bug**
The moment you first open the application it shows a thumbnail of the documents, but after that moment all documents are not seen properly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the application
2. Wait for a very short time
3. Have seen error

**Expected behaviour**
Upon opening this application, one can browse the files normally

**Screenshot and screen recording**

https://github.com/deckerst/aves/assets/109811457/8d937aa2-75f6-485d-95b5-ab6569c39deb

![Screenshot_2023-12-05-21-05-19-123-edit_deckers thibault aves libre](https://github.com/deckerst/aves/assets/109811457/077c1c33-9add-4967-bf15-3161cef1019b)
![Screenshot_2023-12-05-21-05-32-197-edit_deckers thibault aves libre](https://github.com/deckerst/aves/assets/109811457/d58e490c-eb5a-4534-81b7-d0fa4a6343e2)

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.android.packageinstaller
Aves version: 1.9.7-libre, build 10802
Flutter: stable 3.13.7
Android version: 12, API 31
Android build: SKQ1.211006.001 test-keys
Device: Xiaomi M2012K11AC
Geocoder: ready
Mobile services: not available
System locales: zh_CN
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false
[aves-logs-20231205_210233.txt](https://github.com/deckerst/aves/files/13560984/aves-logs-20231205_210233.txt)

**Additional information**
None

**Comment by deckerst** [comment]
Does it sound like your situation?
https://github.com/deckerst/aves/wiki/FAQ#why-does-aves-show-thumbnails-with-a-broken-image-symbol

In particular, are the files actually on storage or just obsolete items left in the Media Store by misbehaving apps?

**Comment by lianzhoulu** [comment]
> Does it sound like your situation? https://github.com/deckerst/aves/wiki/FAQ#why-does-aves-show-thumbnails-with-a-broken-image-symbol
> 
> In particular, are the files actually on storage or just obsolete items left in the Media Store by misbehaving apps?

After clearing all the data and restarting the application, it can be used normally, but I still do not know why I could not view the files properly at the beginning.
