### ISSUE TITLE
Browse hidden content

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#84]
Currently it is only possible to hide folders (tags) and unhide them. It would be nice if the user could browse hidden content.

I suggest clicking on the tag in the privacy settings should show the hidden content and maybe a longpress to select it and having an option to unhide.

**Comment by deckerst** [comment]
By "show the hidden content", are you thinking of:
1) a non-interactive list of file paths
2) a non-interactive grid of thumbnails (that you can sort/group/filter by title)
3) an interactive grid of thumbnails where you can edit/delete items, open them in the viewer, check their info, navigate/drill down from there, view them on the map, etc.

I don't have that need myself, so I can't judge what's adequate.

**Comment by Donkey-Doug** [comment]
Option 3. Basically just everything you can do with any pictures, but just not having the images as hidden.

**Comment by deckerst** [comment]
> clicking on the tag in the privacy settings should show the hidden content

It sounds like you want to see items for a specific hidden tag. Then why not remove the hidden filter, browse it, and hide it again when you're done? Isn't that achieving what you want?

But if you really need to see at once all the items hidden from multiple filters, do you see this as a separate collection (a "hidden collection" that only contains hidden items), or you need to see a collection with all items mixed together, hidden and non-hidden?

**Comment by Donkey-Doug** [comment]
Just the hidden items is fine. Would it be possible to temporarily unhide a tag? Having to re-enable hide is very annoying. Also, if you forget to unhide, private data is available to anyone.

**Comment by Donkey-Doug** [comment]
Summary:

- An option to hide images.
- An option to temporaily unhide images and view them in Aves.
- After being revealed, the hidden images should have the same functionality as regular images.
- Whenever Aves gets closed and reopened, the items should be hidden again. The user should not have to re-hide the images again.
- Mixed view of regular images and revealed hidden images is nice (makes sense for all collections view), but not necessarily.
-

**Comment by flexagoon** [comment]
@deckerst I think I understand what @Donkey-Doug means, and I guess I'd also like to have such behavior. 

This is kinda like hidden photos work in the iOS gallery. They are hidden from everywhere else, but you can see them in a separate "hidden photos" tab inside of the gallery app. You can also hide individual photos there, not just albums.

Thoug I'm not sure if iOS also hides those photos from other apps (like Telegram etc). I'll have to ask someone who uses an iPhone.

**Comment by deckerst** [comment]
> They are hidden from everywhere else, but you can see them in a separate "hidden photos"

What you describe is, as I understand, a "vault" (aka "locked folder", "secure folder", etc.) cf #114. And I think sentences like "if you forget to unhide, private data is available to anyone" from Donkey-Doug reveals that they actually want a vault too.

I'm not familiar with iOS, so I can't appreciate your comparison with the gallery there.

The "hidden" feature stems from a different need: to not show in Aves media files that should stay where they are on the device, public, and usable by other apps.

If Aves provides a vault, I believe this issue of browsing hidden content will be obsolete.

You can upvote #114 to show your interest.
