### ISSUE TITLE
Display more than 5 quick action buttons; separate video/photo actions

### ISSUE THREAD

**Issue by 4evermaat** [deckerst/aves#847]
I noticed that there seems to be a cap of 5 quick actions that show up on screen.

It would also help to separate video and photo quick action menus;  they are 2 different types of media and the menus for each should be managed separately.  The order of the buttons would be different.

https://github.com/deckerst/aves/assets/830306/37095ad6-52a1-42a1-b85c-0223e2fcf970

---
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.0-play, build 109
Flutter: stable 3.16.2
Android version: 11, API 30
Android build: RKQ1.201004.002 test-keys
Device: Xiaomi Redmi Note 8
Geocoder: ready
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/3739-3232/
Storage grants: /storage/emulated/0/DCIM/
Error reporting: true

**Comment by deckerst** [comment]
There is no hard limit to the number of quick actions, but there is a dynamic limit deprived from the available space. If your screen is small it won't display as many quick actions as it will on a larger screen. Also, it can display more quick actions in landscape as it does in portrait mode.

Additionally, quick actions that are not relevant to the current media won't be displayed. For example, video actions are not displayed for images.

I do not intend to implement what you suggest, as it's quite easy to set up quick actions for videos and images with the current way.

Also, keep in mind that quick actions are just a way to bring menu actions that you use most often to the forefront, but if you need so many quick actions you may just as well use the menu.
