### ISSUE TITLE
خطأ عند تصفح SVG

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#852]
**Describe the bug**
التوقف الكلي للتطبيق عند التعامل مع ملفات SVG، عند الدخول للملف او عند التمرير بين ملفات SVG التي اشتغلت.

**To Reproduce**
1. الدخول في ملف SVG
2. التمرير بين ملفات SVG

**Expected behavior**
عند الدخول في ملف SVG يقوم التطبيق بالتوقف تلقايا وتظهر رسالة النظام "تطبيق Aves يستمر بالتوقف"، واحيانا عند التمرير بين صور SVG التي اشتغلت تحدث نفس المشكلة ويتوقف التطبيق عن العمل.

**Screenshots**
سأرسل لك من يحدث معي في جيميل

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.1-play, build 110
Flutter: stable 3.16.5
Android version: 13, API 33
Android build: TKQ1.221114.001 test-keys
Device: Xiaomi 23021RAAEG
Geocoder: ready
Mobile services: ready
System locales: ar_EG
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/
Error reporting: true

**Additional context**
التوقف الكلي للتطبيق عند التعامل مع ملفات SVG

**Comment by deckerst** [comment]
Please attach the logs saved when following the instructions in `About` > `Bug Report`.

**Comment by deckerst** [comment]
Please also provide a sample SVG that makes the app crash.
