### ISSUE TITLE
خطأ عند قراءة SVG

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#853]
Describe the bug
التوقف الكلي للتطبيق عند التعامل مع ملفات SVG، عند الدخول للملف او عند التمرير بين ملفات SVG التي اشتغلت.

To Reproduce

الدخول في ملف SVG
التمرير بين ملفات SVG
Expected behavior
عند الدخول في ملف SVG يقوم التطبيق بالتوقف تلقايا وتظهر رسالة النظام "تطبيق Aves يستمر بالتوقف"، واحيانا عند التمرير بين صور SVG التي اشتغلت تحدث نفس المشكلة ويتوقف التطبيق عن العمل.

Screenshots
سأرسل لك من يحدث معي في جيميل

System information and logs:
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.1-play, build 110
Flutter: stable 3.16.5
Android version: 13, API 33
Android build: TKQ1.221114.001 test-keys
Device: Xiaomi 23021RAAEG
Geocoder: ready
Mobile services: ready
System locales: ar_EG
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/
Error reporting: true

Additional context
التوقف الكلي للتطبيق عند التعامل مع ملفات SVG

https://github.com/deckerst/aves/assets/153401125/5f023b04-2ca3-49e0-acc3-0345468c4b61

[aves-logs-20231224_092832.txt](https://github.com/deckerst/aves/files/13761297/aves-logs-20231224_092832.txt)

**Comment by deckerst** [comment]
Thanks for the logs. Seems like a memory limitation issue.

Could you please provide a sample SVG that makes the app crash?

**Comment by mohamedzerougdz** [comment]
‫في الأحد، 24 ديسمبر 2023 في 9:51 ص تمت كتابة ما يلي بواسطة ‪Thibault
Deckers‬‏ ***@***.***‬‏>:‬

**Comment by deckerst** [comment]
I didn't see any sample SVG file attached to any of your issues or emails.

I know heavy SVG files can lead to memory errors, but maybe there is something else going on with the specific SVG files you have. That's why I'd like to get a sample file from you.

**Comment by mohamedzerougdz** [comment]
‫في الأحد، 24 ديسمبر 2023 في 10:23 ص تمت كتابة ما يلي بواسطة ‪Thibault
Deckers‬‏ ***@***.***‬‏>:‬

**Comment by mohamedzerougdz** [comment]
![djelfa20](https://github.com/deckerst/aves/assets/153401125/51d4f5f0-a146-4182-97a0-e4b3d1709d9a)
![djelfa21](https://github.com/deckerst/aves/assets/153401125/2ab70f32-b1a1-4ff2-bfc1-602087a6a7f9)
![djelfa22](https://github.com/deckerst/aves/assets/153401125/83417665-72b1-4d84-82ae-686a5f9922b5)
![djelfa23](https://github.com/deckerst/aves/assets/153401125/5c9d8b0d-b5a7-4bfd-b638-e9e399c79020)
![djelfa24](https://github.com/deckerst/aves/assets/153401125/409da5d4-6a1f-4749-ba74-a58af2420801)
![djelfa25](https://github.com/deckerst/aves/assets/153401125/e4cabd82-f637-4385-a2ff-0c01dc079549)
![djelfa26](https://github.com/deckerst/aves/assets/153401125/9b9dca4e-2200-4441-a031-77f10621604d)
