### ISSUE TITLE
Changing border albums color

### ISSUE THREAD

**Issue by nightznero** [deckerst/aves#855]
Helloz,

I would like to suggest to have option to change the color of albums,as for apps (idk it's luck or its made to be as this) looks nice,snapchat yellow,fb more darky blue while Telegram more lightly blue. And it's cool! But for the other albums the colors are lil weirdo,they don't take color from the first/last pic so I would like to have option to choose what color it is to fit my cuz for now I see my albums have like 1green 1yellow and most of Blue/pink (90% of albums) borders and every album looks almost the same.

Best Regards, NIGHTZNERO.

**Comment by deckerst** [comment]
You can change the color (as well as the cover image, and the associated app):
- go to the Albums page
- long press on the album to select it
- tap on the "Set cover" action in the app bar on top
- go to the 3rd tab "Color" in the customization dialog
- select your custom color and apply.
