### ISSUE TITLE
Sorting Albums - Manual type

### ISSUE THREAD

**Issue by nightznero** [deckerst/aves#856]
Helloz,

I would like to suggest an option to sort albums not only by date,name or so but also by manually by users. Nice there is bookmark for Apps like **FB Mess Tg** and so on. But here and below that bookmark i would like to choose which album gonna be first and which one would be at the middle and which at the end. I would like to have most important for me albums like **DCIM Videos SS** at the but like the other albums like photo of docs,memes,ss from games/browsing at the bottom while I don't use em a lot but I cannot (or don't see option for that) sort them as I wish to.

Best Regards, NIGHTZNERO.

**Comment by deckerst** [comment]
You can pin albums to the top (select them and use the "Pin" action) but no manual sorry yet.

Duplicate:
- #231

**Comment by deckerst** [comment]
You can pin albums to the top (select them and use the "Pin" action) but no manual sorry yet.

Duplicate:
- #231
