### ISSUE TITLE
Add custom collections/playlists

### ISSUE THREAD

**Issue by jinyus** [deckerst/aves#858]
**Describe the solution you'd like**
Just as `favorite` is a built-in collection. It would be great if we could create custom collections. This could also be implemented by allowing us to create new tags, give us the ability to attach a tag to a media.

**Describe alternatives you've considered**
I currently achieve this with custom albums and copy files to it, but this is a waste of storage.

**Comment by deckerst** [comment]
You can already tag media, either individually by going to the media `Info` page, or in bulk by selecting them in the `Collection` page and then go to the menu > `Edit` > `Edit tags`. Contrary to favorites, tags are embedded in the files, so if you sync or copy the media out of your device, the tags are not lost.
