### ISSUE TITLE
Border around images

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#86]
There is a white border around images. I suggest removing the border.

Aves:
![Screenshot_20211001-222200_Aves](https://user-images.githubusercontent.com/50382414/135681848-b41a494f-deb8-4ba7-bb24-ee249ca14c2c.png)

Simple gallery pro:
![Screenshot_20211001-222310_Gallery](https://user-images.githubusercontent.com/50382414/135681993-196a4595-0845-4e86-9f3e-d1fba744e0e4.png)

**Comment by Donkey-Doug** [comment]
@deckerst Now that we have mosaic layout I think removal of the borders is more relevant now.

![Screenshot_20221114-173526_Trebuchet](https://user-images.githubusercontent.com/50382414/201715271-79e64a88-0a5a-46d6-bc39-cde0de1e4295.png)

**Comment by deckerst** [comment]
I disagree with you about esthetics, but I want to thank you for all these lovely kittens. They made me smile ^^
