### ISSUE TITLE
Allow sort/group-by date-added

### ISSUE THREAD

**Issue by jinyus** [deckerst/aves#860]
**Describe the solution you'd like**
There's an option to sort and group by date-modified. Give us the ability to sort and group collections by date-added as well. You could have these in the pop-up:

`By date (modified)`
`By date (added)`

![Screenshot_20231227-223851_Aves_Libre](https://github.com/deckerst/aves/assets/30532952/8dd338d2-ec4c-4f58-a92a-e776f06b1f3c)

**Comment by deckerst** [comment]
Silicate:
- #97
