### ISSUE TITLE
Saving an edited picture overwrites the original without further notice.

### ISSUE THREAD

**Issue by dataprolet** [deckerst/aves#862]
**Is your feature request related to a problem? Please describe.**
Editing a picture in any way and saving it overwrites the original picture.

**Describe the solution you'd like**
When saving an edited picture I would like to get asked whether I want to overwrite the original picture or save the edited picture using a different name. Other galleries just append "_2" as default when saving an edited picture.

**Describe alternatives you've considered**
Another solution would be to simply make a copy of the original picture when editing a picture and appending "_copy" or something similar.

**Additional context**
As mentioned before here: https://github.com/deckerst/aves/issues/512

**Comment by deckerst** [comment]
Aves does not include an editor. When you use the "edit" action in Aves, it uses the default editor app on your device (and asks if there is no default).
