### ISSUE TITLE
SD card downloads folder not showing.

### ISSUE THREAD

**Issue by Chrisoyng** [deckerst/aves#863]
that's all. Many folders are missing, and there's no option to explicitly add a directory. More of a feature suggestion but I can't realy change the label

**Comment by deckerst** [comment]
Thanks for the report.

Album discovery relies on the OS Media Store. So if it's not showing albums, either they are not public media, or the Media Store has not discovered them yet, or there's a bug in Aves. But manually adding directories is not necessary.

1) Is there at least one album from your SD card that is visible in Aves?
2) If you have an OEM gallery (Samsung Gallery, Google Photos, etc.) installed, does it show the missing folders?
3) Has your SD card been in your device for a while?

Also, please follow the instructions in the `About` > `Bug Report` section and attach here your system info & logs.
