### ISSUE TITLE
Thanks You And Question

### ISSUE THREAD

**Issue by mitchwalton** [deckerst/aves#868]
Hello, I love this app as it's crazy quality work. However, how does Aves encode to .webp? I ask this because at a 100% quality the photo comes out larger than 100% quality in GIMP. This makes your app my go to for converting to .webp even if I'm on my PC with GIMP at hand. It's kind of crazy how better .webp is to .jpg but after all it's newer tech for lossy encoding. The same happens in lossy music encoding with newer tech but I love my truly lossless .flac! An answer would be greatly appreciated. Thanks and again I throughly impress at this app's privacy and quality as I haven't found a better package closed or open source in gallery apps!

**Comment by deckerst** [comment]
Glad you enjoy the app.

As for WEBP, I use the native capabilities of Android, using the following logic:
1) if you use an Android version older than R:
```
Compress to the WEBP format. quality of 0 means compress for the smallest size. 100 means compress for max visual quality. As of Build.VERSION_CODES.Q, a value of 100 results in a file in the lossless WEBP format. Otherwise the file will be in the lossy WEBP format.
```

2) otherwise, if you use a quality of 100:
```
Compress to the WEBP lossless format. quality refers to how much effort to put into compression. A value of 0 means to compress quickly, resulting in a relatively large file size. 100 means to spend more time compressing, resulting in a smaller file.
```

3) otherwise:
```
Compress to the WEBP lossy format. quality of 0 means compress for the smallest size. 100 means compress for max visual quality.
```

**Comment by mitchwalton** [comment]
That explains a lot as I use android 10 so it's converting to lossless .webp compared to GIMP at 100. That is pretty wacked that android 10 runs converting to .webp like that:) Anyways thanks for the fast response as I wish I would of know this a long time ago!
