### ISSUE TITLE
Automatically rescan thumbnail after rotating photo(s)

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#869]
**Is your feature request related to a problem? Please describe.**
After rotating a photo, the thumbnail will be stale and the thus have the wrong orientation.

**Describe the solution you'd like**
Add a auto rescan of the thumbnail photo after the rotation is complete.

**Describe alternatives you've considered**
I don't think there are any good alternatives.

**Comment by deckerst** [comment]
If i understand correctly, this should already be the case (and it works for me). Could you please provide a video capture of what you're doing? Also please provide a sample image which thumbnail doesn't get refreshed.

**Comment by petazonk** [comment]
Ok I just confirmed this quickly and it is still valid.

If you can't confirm I'll try and send a video but will take a bit more
time.

When looking at a single photo, rotate the photo. Now go back to thumbnail
view and it has the wrong orientation.

**Comment by deckerst** [comment]
Yes, still works for me. Thumbnail is refreshed everywhere.

**Comment by petazonk** [comment]
I must have been having a moment as I went to record a video and couldn't
reproduce :( Sorry for wasting your time.

**Comment by deckerst** [comment]
No worries! Maybe there was a random bug.
