### ISSUE TITLE
Enable taging in full screen mode

### ISSUE THREAD

**Issue by shift18** [deckerst/aves#870]
### The problem

Right  now your only able to tag images in thumbnail mode.

Adding a **single tag** is really **bothersome**
Adding a single tag requires you to select an image by touching it for a second.
Now you have  you have to select the hamburger menu (upper right corner) and then you have to scroll down to select edit.
After selecting edit the hamburger menu elongates and tag button is uncovered.
Now you can finally select a tag by touching it and then selecting the check mark in the upper right corner

### Possible Solution
I'd like to be able to tag images while in full screen mode.
Perhaps a tag icon next to the heart icon on the full screen mode would be a good idea?
Either this icon will take you directly to the current tag editor or perhaps i simplified drop up menu? 
The drop down menu would appears directly on the full screen image viewer and you'd be able to select between you're recently used tags within to taps.

### Alternatives
The thing that really makes it bothersome to edit tags right now is how many taps are required to get to the tag editor.
Something else that would make tagging less bothersome  is to bring the tag button out from the current edit menu and into the unexpanded hamburger menu.

Thank you for developing Aves Gallery!
I find it wonderful

**Comment by deckerst** [comment]
Have you tried adding "Edit tags" as a viewer quick action, and then long press on that quick action button? It's a way to add a recent tag without going to a separate page.

**Comment by deckerst** [comment]
Now that I've actually read the whole OP i see that your suggestion is exactly what is already implemented ^^

By the way, even without the viewer quick action, there's another way: when you're at the viewer page you can swipe up to show the `Info` page, and a bit down on that page you have the rating and tagging buttons.

**Comment by shift18** [comment]
That amazing that not only one but two ways of quickly adding tags is already available!

Thank you for pointing that out for me!
