### ISSUE TITLE
Full resolution delay

### ISSUE THREAD

**Issue by PiloniA** [deckerst/aves#872]
**Describe the bug**
When swiping through the images of any album, it takes 1 to 2 seconds to load the full resolution. The full resolution is only saved for 10 images. Swiping back from the 11th image to the 1st, then the first image again takes long to load its full resolution.
Resolution of the images in the album: 3024x4032
Image sizes: 3-4MB

It does not seem to be a phone issue, as other gallery apps (Google, Piktures) are showing the full resolution without delay

EDIT:
- It does not matter if the images in the album are saved on system memory or SD card.
- The problem is independent from the number of images in the album 

**To Reproduce**
1. Open Album
2. Swipe through images
3. It takes 1-2 seconds to load full resolution 

**Expected behavior**
Full resolution should be shown (almost) instantly

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.2-play, build 111
Flutter: stable 3.16.5
Android version: 9, API 28
Android build: PPW29.116-20-28
Device: motorola moto g(6) plus
Geocoder: ready
Mobile services: ready
System locales: de_AT
Storage volumes: /storage/9320-F9CF/, /storage/emulated/0/
Storage grants: 
Error reporting: false

[aves-logs-20240115_061959.txt](https://github.com/deckerst/aves/files/13935169/aves-logs-20240115_061959.txt)

**Comment by deckerst** [comment]
Duplicate:
- #464
