### ISSUE TITLE
Folder management 📁

### ISSUE THREAD

**Issue by UniverseCodex01** [deckerst/aves#873]
**Is your feature request related to a problem? Please describe.**

Aves shows all pictures and photos files that founds on internal storage and SD card but I don't want that aves shows all pictures, If it's possible I want that aves only scan one specific folder, decided by me.

**Describe the solution you'd like**

I consider that add folder management support, the classic included folders and excluded folders with support to hidden folders can be a good idea.

**Describe alternatives you've considered**

None

**Additional context**

As an example Musicolet app has a very good folder management settings but doesn't support hidden folders, please check it to get an example of the feature that I request.

Sorry but I can't upload screenshot, I get error but maybe you can check these settings from Musicolet app:

Musicolet/Settings/Song library and tags/Song Library/Folders to scan

Musicolet/Settings/Song library and tags/Song Library/Excluded Folders

**Comment by deckerst** [comment]
About hidden files: https://github.com/deckerst/aves/wiki/FAQ#can-aves-display-media-inside-hidden-folders

About directory whitelisting, seems like a duplicate:
- #828
