### ISSUE TITLE
Load external subtitle files

### ISSUE THREAD

**Issue by Saijin-Naib** [deckerst/aves#874]
**Describe the bug**
Despite being enabled in Video options, OpenCamera SRT files are not detected nor loaded. 

**To Reproduce**
1. Use OpenCamera or /e/OS Camera with SRT for location enabled
2. Verify SRT written out next to video
3. Verify Subtitle enabled in Aves
4. Observe no Subtitle rendered

**Expected behavior**  
The subtitle SRT should be detected and loaded. 

**Screenshots**
![image1](https://github.com/deckerst/aves/assets/19295950/074dae7a-0be2-4868-a542-ba3afc8079f9)

**System information and logs:**
```
Package: deckers.thibault.aves.libre
Installer: com.android.packageinstaller
Aves version: 1.10.2-libre, build 11102
Flutter: stable 3.16.5
Android version: 12, API 32
Android build: e_emerald-user 12 SQ3A.220705.004 eng.root.20240109.204516 dev-keys
Device: Teracube Teracube_2e
Geocoder: ready
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/Camera/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/
Error reporting: true
```
[aves-logs-20240116_101953.txt](https://github.com/deckerst/aves/files/13952321/aves-logs-20240116_101953.txt)

**Additional context**
My hunch is the match for SRT includes the video file extension, so it would match on videoname.extension.srt, not how OpenCamera names them, which is videoname.srt

**Comment by deckerst** [comment]
Currently, only embedded subtitles are available within Aves video player. The app does not try to detect separate subtitle files. That would be a new feature, and I'm not even sure it's possible. Aves being a gallery app, it only has access to public media files, and subtitle files are not media files. I should double check that so I'll keep this issue open for now.

**Comment by Saijin-Naib** [comment]
Ah, okay, sorry for the misunderstanding on the scope/implementation of this feature!

**Comment by kenderipa** [comment]
Would it be possible with the app permission to see all files, not just media files? Because I'd love to have one less app installed.

**Comment by deckerst** [comment]
I doubled-check (it only took me 3 months!), and Aves with its current permission can not see ".txt" or ".xml" files but, surprisingly, it can see ".srt" files and open them fine.

So this feature *is* possible.

**Comment by Saijin-Naib** [comment]
Since I am paying you exactly $0/hr to work on this for me, you get to set the timetable 🤣

Does this seem like a fit for your vision of Aves? 

My family and I use srt extensively (hearing impairment, GIS, and teaching language to a toddler) but not sure what other needs may be.

**Comment by deckerst** [comment]
Yeah, it seems doable and it would be useful to me too.
For now I'll try to show subtitle tracks from files that match the name of the video (with a possible suffix) and ending with a subtitle extension ("srt" for starters).
