### ISSUE TITLE
hierarchical tags "stopped" working

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#876]
I don't know if this is a real bug or if it is related to something else, but I've noticed, that Aves seems to have changed the behaviour regarding to the displaying of hierarchical tags.

in digikam the tags are within a "people" parent tag. so my images with my mother would be "people/mother". in the past I would not only apply "mother" but also explicitly apply "people" in order to force aves to display the parent tag as well as "people/mother". 

now my issue is that I have noticed that I have a lot of images which are displayed as "mother" and others as "people/mother". this is a problem because aves treats these two as different tags and so only shows one or the other.

I even reapplied the tags in digikam thinking that maybe the way it saves the tags has changed, but the result stays the same. so I think it could be an aves issue

**Comment by deckerst** [comment]
Things haven't changed, but maybe what was going on wasn't explicit.

For starters, Aves does not handle hierarchical tags (in the sense of the hierarchical keywords in the lightroom XML namespace in XMP). It only reads the flat keywords in the basic XML namespace in XMP. Maybe digikam saves the hierarchical "people/mother" as the flat keyword "mother" or the flat keyword "people/mother", I don't know.

So check the XMP metadata of one image that is displayed having the tag "people/mother", and do the same for the one with the tag "mother". There's no bug if what Aves displays is consistent with the XMP keywords. If you think there's a bug, please provide samples exhibiting the issue.

**Comment by deckerst** [comment]
Unrelated: I've noticed you opened your first issue in this repo 2 years ago! Time sure flies...

**Comment by Ingegneus** [comment]
Yes it is pretty nuts... and you have done an amazing job with this app! 
i mean on the play store you have 50k+ downloads (i think i remember downloading it when there were only a few hundred) and 5/5 stars is pretty crazy

regarding the issue i opened: i am investigating it but i suspect it was my wrongdoing. Will report later

**Comment by Ingegneus** [comment]
Ok I figured it out. It was my fault. I modified the Avanced Metadata options in digikamto "flatten" the tag hierarchy but these changes dont carry over from different digikam venrsions. Had to remake those changes and now it works again
