### ISSUE TITLE
Translation - aves-store-short-description-sv

### ISSUE THREAD

**Issue by shift18** [deckerst/aves#879]
### Discussed in https://github.com/deckerst/aves/discussions/878

<div type='discussions-op-text'>

<sup>Originally posted by **shift18** January 20, 2024</sup>
weblate does not seem to allow changes to the store description although the Swedish ones are untranslated.
Tried open a pull request here on github but i don't have the authority.
Could a dev please add it.
Thank you

[aves-store-short-description-sv.txt](https://github.com/deckerst/aves/files/13996841/aves-store-short-description-sv.txt)</div>

**Comment by deckerst** [comment]
Thank you! I've integrated your translation for the "short description" and it now appears in Weblate too.

But it seems there's the same issue with the "full description" (the 3 keys are missing for Swedish). If you wish to translate that one too, you can send me the translation as you did for this one.
