### ISSUE TITLE
Izzydroid fdroid repo

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#88]
Since it is currently not feasible to add Aves to fdroid (#29), consider adding Aves to the izzydroid repo.

I already submitted al info, except the license (https://gitlab.com/IzzyOnDroid/repo/-/issues/186). Could you tell me what license you want to use for Aves?

I suggest the GNU GPLv3 license. This license states that nobody is allowed to copy your code and make a closed source copy of your app. 
    Example of how to disclose license: https://github.com/M66B/FairEmail
Example of how to add license to github: https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project

**Comment by deckerst** [comment]
License is already defined here: https://github.com/deckerst/aves/blob/develop/LICENSE

It's a 3-clause BSD. Compatible with GPL, but not as restrictive.
