### ISSUE TITLE
Duplicates / Double entries

### ISSUE THREAD

**Issue by laubblaeser** [deckerst/aves#880]
**Describe the bug**
Photos, screenshots and videos are shown as double entries in Aves.

**To Reproduce**
1. Take a Photo or Screenshot 
2. Open Aves
3. See double entries

Note that this doesn't happen every time. Sadly. But roughly two out of three times. It's hard to reproduce reliable (i.e. force a double entry). I just tried to take a photo and a screenshot and both are immediately shown in the app but only occur once in the list. All of my entries from yesterday and the days before appear twice. Maybe this info helps somehow?

**Expected behavior**
Every entry should be shown only once.

**Screenshots**
I guess you know from earlier bug reports of this issue how this behaviour looks. I suppose a screenshot isn't necessary.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.10.2-libre, build 11102
Flutter: stable 3.16.5
Android version: 14, API 34
Android build: 64.2.A.2.103 release-keys
Device: Sony XQ-CT54
Geocoder: ready
Mobile services: not available
System locales: de_DE
Storage volumes: /storage/emulated/0/, /storage/FDFE-D007/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/FDFE-D007/Pictures/
Error reporting: false

**Additional context**
Moving files around is not a solution. It's not even a workaround that I, personally, am happy with and wouldn't bother with it. Other apps (e.g. Fossify Gallery, which is the follow-up app for Simple Gallery) detect the entries just once and don't show this problem at all.

**Comment by deckerst** [comment]
I thought that issue was gone for good. At least it stopped happening to me and i couldn't reproduce it on the emulators either.

Please comment if you notice a pattern to reproduce this.

**Comment by deckerst** [comment]
@laubblaeser 
Could you please do the following:
1) install this [test build](https://drive.google.com/file/d/1KfsSUqS21BnfkCnk4KtI3CbQv6ZtmPcx/view?usp=sharing). It will install as `Aves [Profile]`. Please let the default settings as they are.
2) launch `Aves [Profile]` and let it run its initial media scan. It might take a while if you have many media items.
3) try to reproduce the issue by creating new media and checking in `Aves [Profile]` if you see duplicates
4) when you spot a duplicate, please note the `URI` and `path` of the duplicate (available in the media `Info` page), and save the app logs (from `About` > `Bug Report`)
5) attach here the logs, and let me know the URI/path of the duplicate.

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/issues/971#issuecomment-2323067896
