### ISSUE TITLE
Swedish translation - aves-store-full-description-sv

### ISSUE THREAD

**Issue by shift18** [deckerst/aves#882]
Here is the translation of the full description.
I hope you don't mind that I've taken some minor liberties with the translations both on this one and the main app translations made on weblate.
At times perfect word for word translation might be available, but the word needed might be so old fashioned and rarely used that you probably have to read the sentence several times to make sense of it.
Or sometimes a literal translation just sounds weird.
[aves-store-full-description-sv.txt](https://github.com/deckerst/aves/files/14005967/aves-store-full-description-sv.txt)

**Comment by deckerst** [comment]
Thanks! And no worries for the translation style, as long as the initial meaning is still there.
