### ISSUE TITLE
convert motion images to stills in bulk

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#883]
Atm it is possible to convert motion images to stills one at a time from the metadata view. i recently tried to convert hundreds at once and it was a real pain to find out that there are no straight forward solutions to this. from my research quite a few ppl would fiind this useful and it doesnt seem to be too hard since the core feature already exists.

**Comment by deckerst** [comment]
Fair enough.

But it could be either:
1) a "convert" action variant, meaning it makes a still copy of the motion photo,
2) a "remove metadata" action variant, meaning it would edit the existing motion photo.

The convert action variant is more versatile, letting you delete the original if you wish to do so, perhaps after checking the stills are not corrupted.

**Comment by Ingegneus** [comment]
I would probably prefer the convert variant
