### ISSUE TITLE
The widget edit button doesn't show up on Android 10

### ISSUE THREAD

**Issue by GanZhiXiong** [deckerst/aves#884]
Android 14:
<img width="389" alt="image" src="https://github.com/deckerst/aves/assets/27394631/a6eae51d-4601-45d4-b5c8-ddb3ada2c42f">

Android 10:
![image](https://github.com/deckerst/aves/assets/27394631/4a78309b-7346-439b-a72d-0289bc20ed02)

**Comment by deckerst** [comment]
Hi,

No, editing widgets is a newer feature of modern Android.
On older devices, you need to recreate the widget and configure it then.

Cheers,
- Thibault
