### ISSUE TITLE
Support open videos via other video players

### ISSUE THREAD

**Issue by wanzh5** [deckerst/aves#889]
Some video players have more complete features, maybe some users have the requirement of it. So hope that an option can be added to the settings.
extremely thanks!

My English is not very good. If you have difficulty understanding, please refer to the Chinese below.
title:支持使用其他播放器打开视频
description:一些视频播放器拥有更完备的功能，也许有些用户对此有需求。因此，希望可以在设置中添加一个选项。
非常感谢！

**Comment by deckerst** [comment]
Have you tried `Settings` > `Video` > `Controls` > `Buttons` > `Open with other player`?

**Comment by wanzh5** [comment]
> Have you tried `Settings` > `Video` > `Controls` > `Buttons` > `Open with other player`?

Oh, I find it. Sorry, I didn't noticed it then.
