### ISSUE TITLE
Double click to zoom feature sometimes not working

### ISSUE THREAD

**Issue by wanzh5** [deckerst/aves#890]
When the image is as the same aspect ratio as the screen (such as screenshots), double click to zoom will not working.
Below is a screen recording about it.

My English is not very good. If you have difficulty understanding, please refer to the Chinese below.
title:双击缩放功能有时不起作用
description:当图片的长宽比和屏幕相同时（例如截图），双击放大将不起作用。
下面是录屏。

screen recording:

https://github.com/deckerst/aves/assets/106989902/f9e0eb05-7773-49dc-80c1-519ca5fb3ed3

**Comment by deckerst** [comment]
This is normal behavior, because the double tap to zoom cycles through:
- zoom to fit the entire image in the screen,
- zoom to cover the screen,
- zoom at 100%.

For an image that is exactly the size of your screen, all these zoom levels are the same, so there is no change.
