### ISSUE TITLE
Duplicates / Дублирование фотографий

### ISSUE THREAD

**Issue by Dimitrii91** [deckerst/aves#891]
**Describe the bug**
После использования оригинальным приложением фотоаппарата часть фотографий дублируются (не все)

**Expected behavior**
После того, как я сфотографирую и просматриваю фотографии в Aves, некоторооые из фото дублируются. 
Например: из 10 сделанных фото 2 фото будут дублированы.
Будлированные фото не изменяются по масштабу  (их нельзя увеличить), при попытке увеличить они перемещаются по экрану. При этом, техническую информацию дублированного фото посмотреть можно, она ничем не отличается от оригинала.
При удалении дубликата удаляется и оригинал.

**Screenshots**
![Screenshot_20240201-144910](https://github.com/deckerst/aves/assets/158464178/00c64301-60a7-4268-b530-3fdd420e0e4a)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.3-play, build 112
Flutter: stable 3.16.9
Android version: 14, API 34
Android build: 67.1.A.2.182 release-keys
Device: Sony XQ-DQ72
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: ru_RU, en_US
Storage volumes: /storage/emulated/0/, /storage/0123-4567/
Storage grants: /storage/emulated/0/Movies/, /storage/0123-4567/WhatsApp Images/, /storage/emulated/0/Pictures/, /storage/emulated/0/Download/Nearby Share/, /storage/0123-4567/Pictures/, /storage/0123-4567/DCIM/, /storage/emulated/0/DCIM/PHOTOGRAPHY_PRO/, /storage/emulated/0/Android/media/
Error reporting: false

**Additional context**

**Comment by deckerst** [comment]
Related:
- #880

**Comment by deckerst** [comment]
@Dimitrii91 
Could you please do the following:
1) install this [test build](https://drive.google.com/file/d/1KfsSUqS21BnfkCnk4KtI3CbQv6ZtmPcx/view?usp=sharing). It will install as `Aves [Profile]`. Please let the default settings as they are.
2) launch `Aves [Profile]` and let it run its initial media scan. It might take a while if you have many media items.
3) try to reproduce the issue by creating new media and checking in `Aves [Profile]` if you see duplicates
4) when you spot a duplicate, please note the `URI` and `path` of the duplicate (available in the media `Info` page), and save the app logs (from `About` > `Bug Report`)
5) attach here the logs, and let me know the URI/path of the duplicate.

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/issues/971#issuecomment-2323067896
