### ISSUE TITLE
Can You add Camera as "Home" as an extra option.

### ISSUE THREAD

**Issue by ChAJ07** [deckerst/aves#892]
**Is your feature request related to a problem? Please describe.**
Literally It has been many years using many OEMs gallery apps. Their Homepage is always Camera.So, It became my Habit but with this application I have to go to Albums then Camera.

**Describe the solution you'd like**
It would be good if there's another option "Camera" as Home.
![IMG-20240201-WA0001](https://github.com/deckerst/aves/assets/101049867/6191585e-607d-4c9b-80fc-03739a953f97)

It's a request I hope you will consider & Thank You for making this awesome app.

**Comment by deckerst** [comment]
You can already do so with the latest version of Aves:
1) open your camera album,
2) on the Collection page top right menu, select "Set as home".
