### ISSUE TITLE
Motion photos not recognized on nothing phone 

### ISSUE THREAD

**Issue by DiCaprio37** [deckerst/aves#894]
**Describe the bug**
Pictures shot with the nothing phone are not recognized as motion and display as simple stills

**To Reproduce**
1. Open the attached photo with Aves 
2. Open the attached photo with google photo
3. It works with Gphoto but not aves
![IMG_20240204_135632212_MP](https://github.com/deckerst/aves/assets/58360935/e14b302b-9bdc-4d3a-ac03-26a682b20d9a)

**Expected behavior**
The app should recognize nothing phone shot motion photos too

**Screenshots**
Nothing's photo
![Screenshot_20240204-134954](https://github.com/deckerst/aves/assets/58360935/bc677cbf-fa57-4f8e-853b-8c23dd6a0541)
Google's photo
![Screenshot_20240204-134944](https://github.com/deckerst/aves/assets/58360935/118d17af-74a0-41ac-8289-ea4cf0362c87)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.3-play, build 112
Flutter: stable 3.16.9
Android version: 14, API 34
Android build: U2.5-240116-1446
Device: Nothing A065
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: true
[aves-logs-20240204_140012.txt](https://github.com/deckerst/aves/files/14156846/aves-logs-20240204_140012.txt)

**Additional context**
Photos shot with the google camera display as expected, the problem is only with those shot on Nothing phone 2

The uploded motion image is shot with the .6 camera just to not exceed the 10MB limit

I hope I've explained all in detail and i provided everything needed

**Comment by deckerst** [comment]
Thanks for the nice report.

For reference, here's the xmp of the motion photo from Nothing Phone:
```xml
<rdf:Description rdf:about=""
            xmlns:Camera="http://ns.google.com/photos/1.0/camera/"
            xmlns:Container="http://ns.google.com/photos/1.0/container/"
            xmlns:Item="http://ns.google.com/photos/1.0/container/item/"
          Camera:MotionPhoto="1"
          Camera:MotionPhotoVersion="1"
          Camera:MotionPhotoPresentationTimestampUs="646343"
          Container:Version="1">
          <Container:Directory>
            <rdf:Seq>
            <rdf:li>
            <Container:Item
              Item:Semantic="Primary"
              Item:Mime="image/jpeg"/>
            </rdf:li>
            <rdf:li>
            <Container:Item
              Item:Semantic="MotionPhoto"
              Item:Mime="video/mp4"
              Item:Length="6107920"/>
            </rdf:li>
            </rdf:Seq>
            </Container:Directory>
        </rdf:Description>
```

And here's one that's recognized by Aves:
```xml
<rdf:Description rdf:about=""
        xmlns:GCamera="http://ns.google.com/photos/1.0/camera/"
        xmlns:Container="http://ns.google.com/photos/1.0/container/"
        xmlns:Item="http://ns.google.com/photos/1.0/container/item/"
      GCamera:MotionPhoto="1"
      GCamera:MotionPhotoVersion="1"
      GCamera:MotionPhotoPresentationTimestampUs="2306056">
      <Container:Directory>
        <rdf:Seq>
          <rdf:li rdf:parseType="Resource">
            <Container:Item
              Item:Mime="image/jpeg"
              Item:Semantic="Primary"
              Item:Length="0"
              Item:Padding="59"/>
          </rdf:li>
          <rdf:li rdf:parseType="Resource">
            <Container:Item
              Item:Mime="video/mp4"
              Item:Semantic="MotionPhoto"
              Item:Length="3491777"
              Item:Padding="0"/>
          </rdf:li>
        </rdf:Seq>
      </Container:Directory>
    </rdf:Description>
```

**Comment by DiCaprio37** [comment]
Woow, crazy fast, thank you very much!!
Yeah i noticed the two xmp were different I figured that was the case,
thanks.
Btw how does it work on github to have the updated version, do i just
reinstall the last version or do i have to wait the next one?

Thanks again, best developer ever!


*Leonardo Michelotti *

**Comment by deckerst** [comment]
Well, anybody can get the code and build it themselves, but I recommend just waiting for the next release (whenever that comes).

**Comment by DiCaprio37** [comment]
O ok thank you very much.

btw I have a similar issue with the hdr recognition, works with google
photos but not nothing's.
I'll attach a photo shot on nothing which should have hdr.
Or if u want i can open onether request on github.
Thanks again.

**Comment by deckerst** [comment]
Please attach the undetected HDR image here, it's fine.

But just so you know, Aves can detect HDR items, but cannot render them properly. For more details:
- #838

**Comment by DiCaprio37** [comment]
I'll attach it, thanks

**Comment by deckerst** [comment]
@DiCaprio37 do you have a sample for your issue with HDR detection?

By the way, if you reply to a github thread via email, I think attaching images does not attach it to your comment.

**Comment by DiCaprio37** [comment]
O yeah sorry I was sending it on the email
![IMG_20240204_133652546](https://github.com/deckerst/aves/assets/58360935/6b07bf2f-4477-41a4-a07f-d60ea2976721)

**Comment by deckerst** [comment]
That image does not contain Ultra HDR metadata or even a gain map.

**Comment by DiCaprio37** [comment]
Idk then, nvm, thanks anyways
