### ISSUE TITLE
خطأ عند التمرير بين الصور في وضع اللغة العربية

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#898]
**Describe the bug**
في اللغة العربية، عند التمرير بين الصور لا يكون هناك اي خطأ، لكن عند تكبير الصورة المعروضة حاليا ثم محاولة التمرير الى الصورة التالية يقوم التطبيق بالرجوع الى الصورة السابقة.

**To Reproduce**
1. ادخل في احدى الصور المتوفرة لديك.
2. قم بالتمرير الى الصورة التي بعدها.
3. قم بتكبير الصورة.
4. حاول التمرير الى الصورة التالية.
5. يقوم التطبيق بالرجوع الى الصورة السابقة بدلا من الذهاب الى الصورة التالية في وضع تكبير الصورة.

**Expected behavior**
في اللغة العربية، عند تكبير صورة ما ثم محاولة التمرير الى الصورة التالية يجب ان لا يرجع التطبيق الى الصورة السابقة.

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.3-play, build 112
Flutter: stable 3.16.9
Android version: 14, API 34
Android build: UKQ1.230917.001 release-keys
Device: Xiaomi 23021RAAEG
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: ar_EG
Storage volumes: /storage/emulated/0/, /storage/809D-1606/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/MOHAMED ZEROUG/, /storage/emulated/0/InstaFlow/, /storage/emulated/0/MIUI/, /storage/809D-1606/MOHAMED ZEROUG/
Error reporting: true

**Additional context**
هذا الخطأ موجود فقط عند تغيير لغة التطبيق الى اللغة العربية.

[aves-logs-20240206_183534.txt](https://github.com/deckerst/aves/files/14184815/aves-logs-20240206_183534.txt)

https://github.com/deckerst/aves/assets/153401125/5f60413a-c333-4184-9e38-0cafc64cbaee

**Comment by deckerst** [comment]
Oh, good catch. Thanks for the report

**Comment by deckerst** [comment]
I also noticed the transition effects in the viewer and slideshow were wrong for Arabic.

Especially, the transition for the viewer normally has parallax, but it was missing with Arabic. You might be surprised by the change.
