### ISSUE TITLE
samba lan

### ISSUE THREAD

**Issue by jh7gxu** [deckerst/aves#901]
nvidea Shield TVにavesをインストールしました。
Shieldのsamba共有でlocal network内のnasに入れてある写真をTVに表示したいのですが、うまくいきません。
avesではnetwork共有ファイルにアクセスする機能をリリースする予定はありますか？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerst** [comment]
Duplicate:
- #857
