### ISSUE TITLE
Widget border color based on device theme

### ISSUE THREAD

**Issue by Aditya137x** [deckerst/aves#902]
It would be great if the color of the border of the photo widget would change according to the device theme.

White for light theme and black for dark.

Currently I have to change it everytime.

Also if we can set custom border radius  for the widget it would be awesome.. But that's just a suggestion.

**Comment by deckerst** [comment]
There's some mandatory radius on modern Android, so I'm unlikely to play with that.

However, I'll take a look at providing the system dependent black/white. I wonder how reactive it would be though. By the way, on your device, does it switch between dark/light theme on schedule, or you often manually switch between the two?

And I just thought, maybe I could also provide a colour option that takes the dynamic material you colour. Not sure whether that would be used.

**Comment by Aditya137x** [comment]
Yes I have set a schedule to change between dark/light mode. Or when battery saver mode is turned on it automatically turns dark mode on as well. Most of my widgets on homes screen follow system theme. 

Dynamic colors is also a good idea. Some widgets on my home screen have some parts like texts with dynamic colors and remaining area follows light/dark theme.

**Comment by Aditya137x** [comment]
Thanks alot Man
