### ISSUE TITLE
Option to show and hide folders with .nomedia file

### ISSUE THREAD

**Issue by tawissus** [deckerst/aves#903]
It would be great if the app could handle "hidden" folders. Folders with .nomedia files are ignored by many media apps. However, you can also use the behaviour to hide rarely used folders. 

Compared to hidden folders, .nomedia folders are also hidden in other apps.

It would therefore be nice to add a function to show or hide them in the menu.

**Comment by deckerst** [comment]
As a gallery app, Aves can only access public media files. Cf [FAQ](https://github.com/deckerst/aves/wiki/FAQ#is-aves-a-file-manager).

**Comment by tawissus** [comment]
Understandable. But why not think about it? 
SimpleApps also has the function and it is also accepted by Google. The function was first removed there as a precaution due to Google guidelines, but then reinstalled because many users use it. That's the only blocker I have, for example.

**Comment by tawissus** [comment]
I wouldn't want to use the SimpleApps app with the new owner for much longer, for example. You could pick up users there.

**Comment by deckerst** [comment]
> Understandable. But why not think about it? SimpleApps also has the function and it is also accepted by Google. The function was first removed there as a precaution due to Google guidelines, but then reinstalled because many users use it. That's the only blocker I have, for example.

I agree with the Play Store policy about this: messing with non media files is overreach, in my opinion.

**Comment by deckerst** [comment]
Duplicate:
- #574
