### ISSUE TITLE
Freeze during slideshow

### ISSUE THREAD

**Issue by plneappl** [deckerst/aves#905]
**Describe the bug**
Sometimes during slideshows, screen turns completely black and app no longer responds to inputs, neither "next", "previous" or android "back". Need to kill and relaunch app.

Don't know which file is responsible (folder has 3k items), but if you can tell me the filename from the log I can send it to you.

**To Reproduce**
1. Start slideshow on shuffle
2. After viewing many items, app stops responding

**Expected behavior**
No crash

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.10.2-libre, build 11102
Flutter: stable 3.16.5
Android version: 13, API 33
Android build: TKQ1.220807.001.33.0210.0210.332 release-keys
Device: asus ASUS_I006D
Geocoder: ready
Mobile services: not available
System locales: en_US, de_DE
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false
[aves-logs-20240208_205005.txt](https://github.com/deckerst/aves/files/14214059/aves-logs-20240208_205005.txt)

**Comment by deckerst** [comment]
Could you take a look at this file on your device?
`content://media/external/video/media/1000017876`

You can find it by ID, typing `id=1000017876` in the Search page (or the title filter in the Collection page).

Is it special in any way? Could you start a slideshow on it and see whether it freezes?

**Comment by plneappl** [comment]
Seems very random, I just had it happen on a shuffle slideshow of 250 files after just 3 or so files, then the next time I could view all 250 of them in another shuffle.
the file seems just fine, I can start a slideshow on it and include it in the middle of one.
Logs of the crash after a few files attached, will try just videos/photos next.
[aves-logs-20240209_074756.txt](https://github.com/deckerst/aves/files/14218247/aves-logs-20240209_074756.txt)

**Comment by plneappl** [comment]
just happened with just videos after about 10 or so, log attached
[aves-logs-20240210_204314.txt](https://github.com/deckerst/aves/files/14230312/aves-logs-20240210_204314.txt)

**Comment by deckerst** [comment]
> then the next time I could view all 250 of them in another shuffle.

So it's not because of a specific file. Good to know.

And have you had the chance to try and reproduce the freeze with images only? In all 3 log files you provided, I see some suspicious video-related message before the app stops, but I don't know yet whether it's related.

Could you please also screenshot your settings in `Settings` > `Viewer` > `Slideshow`?

**Comment by plneappl** [comment]
I've tried only pictures a couple of times without it freezing up, so I'd wager about 80-90% chance that only videos are the problem :)
screenshot of settings:
![Screenshot_20240211-174206264](https://github.com/deckerst/aves/assets/4385742/d10f19f4-38ba-4a7f-abb5-53d43057f2e5)

**Comment by deckerst** [comment]
I see that you use a large interval (13 minutes). Does the app freeze happen also with small intervals? And do you go through videos that are shorter or longer than this interval?

**Comment by plneappl** [comment]
I can try, I've set ip up like that so it doesn't auto advance. Videos are shorter than that

**Comment by deckerst** [comment]
Maybe I misunderstood. Does the freeze happen during a transition or while it's in the middle of the video?
For example, you would start a slideshow with a 13 minutes interval, it would starting showing a video and freeze 5 minutes in?

**Comment by plneappl** [comment]
exactly at a transition, way earlier than 13min

**Comment by plneappl** [comment]
the one after a few items:
open program
start slideshow
quickly tap next item
after a few, it hangs

**Comment by plneappl** [comment]
maybe the timers for auto advancing videos aren't cancelled properly on transitioning?

**Comment by plneappl** [comment]
seems like it doesn't happen with 5s auto advance

**Comment by deckerst** [comment]
Ah, i see. You don't use the slideshow as a slideshow. That's why I was confused ^^

What you call auto-advance is the main point of a slideshow. It's supposed to be hands-off, going through the items automatically. You can indeed manually go to the previous or next item but it won't cancel the automatic slideshow. You can stop the automatic behaviour by bringing the overlay with a tap.

**Comment by plneappl** [comment]
Ah hm, I'm using it for shuffled viewing of my meme collection :)
I think another reason for me setting it up like this was #803, which you fixed already, thank you for that!
I guess the overlay is a workaround for now, but it'd be great if all this helps you find the root cause ;)

**Comment by plneappl** [comment]
still happens with the 5s auto advance when just viewing an album filtered by just videos, without slideshow, just regular order

**Comment by deckerst** [comment]
"5s auto advance" and "without slideshow" are mutually exclusive so i don't understand what you mean.

**Comment by plneappl** [comment]
Ah, I meant "with 5s auto advance setting" using normal browse, having the overlay up. I assumed that view would also automatically advance, since its sort of the same view.

**Comment by deckerst** [comment]
@plneappl do you still have the issue with Aves v1.11.17?

**Comment by plneappl** [comment]
I'll check a few times the next few days and let you know!

**Comment by plneappl** [comment]
Did not happen again, thanks for fixing!
