### ISSUE TITLE
Video indicator

### ISSUE THREAD

**Issue by myryk31415** [deckerst/aves#909]
**Is your feature request related to a problem? Please describe.**
When swiping through my gallery without the buttons displayed I accidently skip videos because I think they are photos

**Describe the solution you'd like**
Some indicator that its a video and not a photo, e.g. a play button in the middle of the screen, especially when the gallery shoes only the photo and no extra information and therefore till now no play button either

**Describe alternatives you've considered*
any other type of indicator to let you know its a videi

**Comment by deckerst** [comment]
Wouldn't it be more adequate for you to enable auto play for videos?

**Comment by myryk31415** [comment]
true thats  probably a good idea. ty. still think the indicator would be a quality of live improvement. also thanks for the overall work on the app :D
