### ISSUE TITLE
Explorer / Filtering by folder

### ISSUE THREAD

**Issue by noearchimede** [deckerst/aves#910]
Hi! First of all, great app! Have been using it daily for a year now :)
To explain my feature request, consider the case where there are multiple groups of photos on a single phone separated in different folders, such as:
- DCIM
- "App media" (WhatsApp, photo editing apps, drawing apps, ecc), e.g. in ~/Android or ~/Pictures or a subfolder of these
- A synced folder containig images from another device (this is my specific use case, as I sync my main photo collection to my phone and sometimes would like to be able to see only that collection)

Each of these would have at least a few sub-folders, which will then be treated as albums. It is of course possible to visualize each album individually, but as far as I have seen there is no option to filter the collection to show multiple albums at once, and anyways it wouldn't be very practical to have to select all albums in a specific group manually every time.

This is clearly linked to the more general issues #592 and #268, I don't know if my issue should be considered a duplicate. But I'm posting it anyways because I think this one tackles some of the points raised there (or at least could be used as a workaround in some of the scenarios mentioned in those issues), while also being less invasive on the way albums work in Aves.

I'm not sure about how this could work in practice, here are just some thoughts:

- in the filter options on the main collections page there could be an extra "location" section besides "date", "albums", "countries", etc, which could contain a list of folders (just like the "albums" section contains a list of albums). The folders could be any folder that contains a subfolder that contains a file shown in Aves or any folder that contains at least two subfolders containing an image. For example, if a user has an image in DCIM/Camera and one in DCIM/Screenshot in the first case the list would be [$HOME, DCIM], while in the second case only [DCIM].

- in the filter section (e.g. at the end of the albums list) there could be a special item (e.g. "directory") that opens a folder selection dialog, where the user explicitly selects a folder . This would work a bit differently from any current item though...

None of these ideas is extremely user friendly, but I think the former is quite similar to the album selection dialog and for "normal" folder structures (not deeper than a few layers and with more folders actually containing images tha oarent folders) it would not have more entries than the "album" filter section, and the latter would be more of an advanced feature for user that have a specific folder structure.

Finally I think this would be a great option to have in combination with the new "Set as home" feature!

Sorry for the lengthy feature request, I hope you find it interesting... and thanks for developing and maintaining Aves!

**Comment by deckerst** [comment]
Thanks, it is interesting. I understand the need, but haven't figured out yet how it would fit with the current way, the potential nested folders, etc.

As a side note, the kind of filter that would show what you want is actually what is internally used to recursively filter *out* paths (in `Settings` > `Privacy` > `Hidden items` > `Hidden paths`), but it's not used (yet) to filter *in*.

**Comment by deckerst** [comment]
> there is no option to filter the collection to show multiple albums at once, and anyways it wouldn't be very practical to have to select all albums in a specific group manually every time

Still not practical if you intend to do it often, but at least since Aves v1.11.2 you can do it, by selecting multiple albums in the `Albums` page, then in the top right menu > `Show in Collection`.
