### ISSUE TITLE
[Suggestion] Allow customizing the sort-order of albums

### ISSUE THREAD

**Issue by Aballoffox** [deckerst/aves#912]
**Suggestion 2**
Support for customizing the sort-order of albums. I have over 60 albums to manage, although they are sorted by date, it may take a moment to find the target album. Allow users to customize the sort-order of albums may save this time.

**Additional**
I've been using it for months, and I really love the smoothness and fluent animation of aves. Hope this suggestion to be taken.

**Comment by deckerst** [comment]
Duplicate:
- #231
