### ISSUE TITLE
Untracked vault item

### ISSUE THREAD

**Issue by azaiela** [deckerst/aves#913]
**Describe the bug**
I have a video saved in a vault, but it doesn't show up.

**To Reproduce**
1. Go to 'Albums'
2. Click on 'Vault'
3. See error

**Expected behavior**
It is expected that the video will be available to me within the app.

**Screenshots**
![IMG-20240218-WA0003.jpg](https://github.com/deckerst/aves/assets/160394395/53bbdc6c-7f6e-42dd-a2af-144ca1d07e50)

![IMG-20240218-WA0002.jpg](https://github.com/deckerst/aves/assets/160394395/162b7c99-69c8-434c-b65f-bf64610e32c5)

**System information and logs:**
![aves-logs-20240218_073031.txt](https://github.com/deckerst/aves/files/14322150/aves-logs-20240218_073031.txt)

Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.10.4-libre, build 11302
Flutter: stable 3.16.9
Android version: 10, API 29
Android build: QP1A.190711.020.M305MUBS8CWB1
Device: samsung SM-M305M
Support: dynamic colors=false, geocoder=true, HDR=false
Mobile services: not available
System locales: en_US, ja_JP
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Additional context**
I have only the video saved inside the vault. In addition to having only one vault. In one of the screenshots, the storage usage indicates that there is a file inside the vault. But it doesn't show up. For security reasons of the app itself, I can't take a screenshot inside the vault. Please, help me.

**Comment by deckerst** [comment]
When you click on 'Vault', does it ask you to enter your pin/password/digit to unlock it?

**Comment by azaiela** [comment]
> When you click on 'Vault', does it ask you to enter your pin/password/digit to unlock it?

Yes, my phone's password.

**Comment by deckerst** [comment]
After you have unlocked the vault, if you go back to the Albums page, do you see next to the Vault name the icon is unlocked, and below it does it right "0" or "1" (for the item count)?

If it's 0, is your vault item in the recycle bin maybe?

**Comment by azaiela** [comment]
> After you have unlocked the vault, if you go back to the Albums page, do you see next to the Vault name the icon is unlocked, and below it does it right "0" or "1" (for the item count)?
> 
> If it's 0, is your vault item in the recycle bin maybe?

Yes, the count is zero. But I can not see the item in the recycle bin.![Screenshot_20240220-200055_Aves Libre.jpg](https://github.com/deckerst/aves/assets/160394395/23851739-0d8b-4f31-908b-9b47f0fac5f5)

**Comment by deckerst** [comment]
Deleted vault items are only visible in the recycle bin of the vault is unlocked. If you can take a screenshot, it means the vault is not unlocked.

In any case, you say it displays "0" items in your vault, but the data usage reports 6 MB in the vault, so there's a bug somewhere. Thanks for the report. I'll see what i can do to recover items like that, but be patient. Do *not* clear the app data, or uninstall the app, in the meantime.

**Comment by azaiela** [comment]
I won't. But I'm scared to lose the video. I unlocked the vault and looked in the recycle bin, but nothing changed. Thank you for your attention.

**Comment by deckerst** [comment]
Do you have filters in `Settings` > `Privacy` > `Hidden items` (either `Hidden Filters` or `Hidden Paths`)?
If so, it could potentially hide your vault item if it's matching one of these filters.

**Comment by deckerst** [comment]
@azaiela could you try the latest release v1.10.5? It's on the Play Store as a beta now (anybody can join the beta testers and install it), and soon will be public there too.

Please let me know how it goes with the latest release.

**Comment by azaiela** [comment]
> Do you have filters in `Settings` > `Privacy` > `Hidden items` (either `Hidden Filters` or `Hidden Paths`)?
> If so, it could potentially hide your vault item if it's matching one of these filters.

![Screenshot_20240223-055011_Aves Libre.jpg](https://github.com/deckerst/aves/assets/160394395/e99949ae-73b0-436b-8f26-427cee404faa)

Nothing.

**Comment by azaiela** [comment]
> @azaiela could you try the latest release v1.10.5? It's on the Play Store as a beta now (anybody can join the beta testers and install it), and soon will be public there too.
> 
> Please let me know how it goes with the latest release.

![Screenshot_20240223-055154_Google Play Store.jpg](https://github.com/deckerst/aves/assets/160394395/41050175-3f1c-437f-9960-ef488d49ffd4)

But I would just install other app, no? Thank you for your patience.

**Comment by azaiela** [comment]
I just updated using the Releases page. Thank you so much. Realy. You don't know how important this file is for me, but you invested your time to help me. Thank you, thank you!

**Comment by deckerst** [comment]
I don't understand how the issue happened in the first place, but I'm glad I could help recover from it in the end.
