### ISSUE TITLE
Edit function does not work

### ISSUE THREAD

**Issue by rainxk2** [deckerst/aves#923]
**Describe the bug**
Just as the title says.
I cannot edit any photo nor videos.

**Expected behavior**

**Screenshots**
![Screenshot_20240226_015711_Android System](https://github.com/deckerst/aves/assets/46279789/c5b4d3fb-a514-46a0-bd7d-229971abd581)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.5-play, build 114
Flutter: stable 3.19.1
Android version: 14, API 34
Android build: UP1A.231005.007.G996NKSS4FXAD
Device: samsung SM-G996N
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: en_US, ko_KR
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/DCIM/
Error reporting: false

[aves-logs-20240226_015956.txt](https://github.com/deckerst/aves/files/14397108/aves-logs-20240226_015956.txt)

**Additional context**
There should be at least a choice, but nada.
Funnily, I've have installed F-Stop gallery on my device after figuring out AVES edit feature didn't work.
When f-stop was installed, the edit feature worked on Aves.
When I uninstalled it, it's gone again. 

For media viewing purposes, I currently have VLC, Samsung Gallery, and AVES. (Uninstalled F-Stop)

**Comment by deckerst** [comment]
Aves does not provide an editor. The "edit" action in Aves forwards the item to editors installed on your device.

I usually recommend Snapseed, but there are plenty of other editing apps out there. I personally use the editor from Google Photos. By the way, Samsung Gallery editor is great but it can only be used from within Samsung Gallery.

If the editor from F-Stop suits you, why not using it?

Duplicate:
- #17
