### ISSUE TITLE
Turning on "Allow Media Management" in settings causes app to crash

### ISSUE THREAD

**Issue by efber13** [deckerst/aves#925]
**Describe the bug**
Every time I try to enable allow media management in settings the app crashes.

**To Reproduce**
1. Go to Settings
2. Tap on Privacy
3. Tap on Allow Media Management
4. App crashes 

**Expected behavior**
Turning on Allow Media Management shouldn't crash the app.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: org.fdroid.fdroid
Aves version: 1.10.4-libre, build 11302
Flutter: stable 3.16.9
Android version: 14, API 34
Android build: UP1A.231005.007.S918U1UES2BXAD
Device: samsung SM-S918U1
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/cloudStorage/, /storage/emulated/0/Pictures/
Error reporting: false

[aves-logs-20240225_232628.txt](https://github.com/deckerst/aves/files/14401386/aves-logs-20240225_232628.txt)

**Additional context**
Having a strange issue where I can't save logs with the play store version (1.10.5), it's not giving me the prompt to save the log in a directory when I tap on save. Might be a thing with my phone.  The app crashing issue also happens on this version as well.

**Comment by deckerst** [comment]
Thanks for following up. I'll take a look when I can.

When you were using the Play Store version, did you enable automatic error reporting?

**Comment by efber13** [comment]
Yes I believe I had error reporting enabled and redid the crash several times.

**Comment by deckerst** [comment]
> Having a strange issue where I can't save logs with the play store version (1.10.5), it's not giving me the prompt to save the log in a directory when I tap on save. Might be a thing with my phone.

If you try to export your settings (via Settings > top right menu > Export), does it show you the system dialog to select a location and does it successfully save the settings file? (Play or Libre version, whatever)

Do you use a custom ROM?

> Yes I believe I had error reporting enabled and redid the crash several times.

I've looked in Crashlytics for reports matching Samsung Galaxy S23 Ultra devices, to no avail.
And I don't see any crash or even errors in the log file you have attached above. Did you export the logs right after the crash?

By the way, when you write "crash" you mean that the app forcibly closes, right? (no freeze, no black screen, simply the app closing)

**Comment by efber13** [comment]
> If you try to export your settings (via Settings > top right menu > Export), does it show you the system dialog to select a location and does it successfully save the settings file? (Play or Libre version, whatever)
> 
> Do you use a custom ROM?

Strange. Today when I tried it on the play version it suddenly works now.  I've attached the log of that version. I don't believe I use a custom ROM.

[aves-logs-20240225_232628.txt](https://github.com/deckerst/aves/files/14409773/aves-logs-20240225_232628.txt)

Here's the updated info as well:

Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.5-play, build 114
Flutter: stable 3.19.1
Android version: 14, API 34
Android build: UP1A.231005.007.S918U1UES2BXAD
Device: samsung SM-S918U1
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/cloudStorage/, /storage/emulated/0/Pictures/
Error reporting: true


> By the way, when you write "crash" you mean that the app forcibly closes, right? (no freeze, no black screen, simply the app closing)

Yeah exactly. The app just closes with no error.

> I've looked in Crashlytics for reports matching Samsung Galaxy S23 Ultra devices, to no avail.
> And I don't see any crash or even errors in the log file you have attached above. Did you export the logs right after the crash?

This might have to do with me not being able to export logs last night? Are the reports there now? I redid the error a few times today before I attached the new log.

**Comment by efber13** [comment]
I tried enabling Allow Media Management on a Pixel 7 phone and it's working fine.  It seems to be an issue exclusive to Samsung devices since the crash also happens on my Galaxy Tab S8+ device as well.

**Comment by efber13** [comment]
> What version of Android does your Galaxy Tab S8+ use?

Android 14, same as my samsung galaxy 23 ultra phone.

> Do you think you would have an app or some system settings that aggressively close apps when they go in the background?

No apps that I have affect other apps when they run it in the background, and Aves is set in system settings to run in the background without restrictions.

> In Aves, toggling this "Allow media management" switch brings the user to the system settings screen to let them give the permission at the system level.

Yes on my Pixel 7 phone (also android 14) is able to reach the system settings screen to give permission at the system level as well, which leads me to think the android version isn't the issue here. Maybe the samsung software is at fault here? You said you're using a S10e, are you on One UI version 6.0? Both of my samsung devices are on this version.

**Comment by deckerst** [comment]
The One UI versions follow the Android versions. For Android 14 it's One UI 6 as you said. On my Android 12 device it's One UI 4.1.

It's possible that it is related to One UI 6, but I would be surprised. Because if it's the case, I'd get way more complaints from the many Samsung users out there.

For now, I have no clue how to address this, so don't expect a fix in the short term. Thanks again for following up and providing all these precious details.

**Comment by efber13** [comment]
Yeah no problem, I'm stumped as well on what's making aves close when jumping to system settings. Maybe some other users can chime in on this and see if they can reproduce the same problem.

**Comment by efber13** [comment]
Okay so I might need to correct myself upon further testing. After multiple tries with the temp build and the play version, I'm getting this popup:
![Screenshot_20240226_141615_Microsoft Launcher](https://github.com/deckerst/aves/assets/16296859/c26c22a4-974d-42df-b900-f4b9f0d92a23)

Seems when Aves tries to jump to system settings, settings itself just crashes, which probably is what's making Aves close.

**Comment by deckerst** [comment]
I see. What happens if you go to your Android Settings > Apps > top-right ... menu > Special access > Manage media > Aves? (I'm assuming things haven't changed much between One UI 4 and 6.)

**Comment by efber13** [comment]
If I do it via the method you describe, it works fine and the setting is toggled:

![Screenshot_20240226_145940_Settings](https://github.com/deckerst/aves/assets/16296859/a7a27cac-9f7d-4323-9b3c-de18c78ce568)

Still makes settings crash if I tap on the feature, but it's working now?

![Screenshot_20240226_150020_Aves](https://github.com/deckerst/aves/assets/16296859/fde21feb-1c0e-499e-843d-cf9ed19a4d0e)

**Comment by deckerst** [comment]
I believe it's a bug in One UI, and they will hopefully fix it someday with a patch.
In the meantime, it's possible to enable media management as described above.

I'll close this issue then. But if you find another app that pulls this particular setting screen without making it crash on your device, I'm interested!
