### ISSUE TITLE
Not playing AVI correctly

### ISSUE THREAD

**Issue by Teddyz** [deckerst/aves#926]
**Describe the bug**

1 Playing video in attached zip skips frames. 
2 On other films, a picture from the film is shown on the icon.

[viagmail_20240226_223023.zip](https://github.com/deckerst/aves/files/14411955/viagmail_20240226_223023.zip)

**To Reproduce**
1. Have film in Downloads folder so it is listed in the program.
2. Click on the icon to play it.

**Expected behavior**
Film to play normally, as it does in VLC.

**Additional context**
Film is from old D-Link surveillance camera DCS-5020L, so problem can of course be that the video encoding is broken.
Film shows a rat lurking under an outdoor wooden floor.

**Comment by deckerst** [comment]
I observed the same issue with my old AVI files when i switched from `ijk` to `mpv`, the new video engine used by Aves. It was overall a better engine, despite the regression on these AVI files.

For now, the only workaround i can offer is to disable hardware acceleration when playing them. It works for my AVI files, at least.

**Comment by Teddyz** [comment]
I tried and disabling hardware acceleration solved my problem.

Thanks for the explanation!
