### ISSUE TITLE
Custom Album Path

### ISSUE THREAD

**Issue by LukasMandok** [deckerst/aves#929]
**Is your feature request related to a problem? Please describe.**
My pictures folder is already extremely cluttered by various apps, with pictures I don't need in my gallery nor in my Nextcloud sync. I would like to use the Upload Files Feature of the Nextcloud App to sync all my sorted Albums to Nextcloud, but without all the other junk in my Pictures folder.

**Describe the solution you'd like**
It would be great to be able to adjust the default album path, so I can choose "pictures/albums/" instead of "pictures/" and sync only the albums subfolder to Nextcloud.

**Describe alternatives you've considered**
- Having an app that integrates with Nextcloud like Les Pas and allows you to sync new albums directly to nextcloud would an alternative. However I don't like the private app data aspect of the app and the lacking features of gallery management. Your app would suit my needs much better, even without Nextcloud integration.
- very few apps use sub folders for there albums, which would already be enough for me (like the default OnePlus Gallery "DCIM/myAlbums/"). However, choosing this app versus your vastly superior one would be heartbreaking 😭.
- syncing all the other junk in my "pictures/" folder to nextcloud as well.

**Additional context**
When I granted the permission for your app to write to the pictures folder, it looked like everything needed to set a custom path was already in place, except for the part where any other folder than "pictures/" would be accepted.

**Comment by deckerst** [comment]
Duplicate:
- #295

In the meantime for your case, you can easily create the new album in a subfolder of "Pictures" by giving the album name "albums/Holidays", instead of "Holidays".

> However, choosing this app versus your vastly superior one would be heartbreaking 😭.

Flattery, yes! :D

**Comment by LukasMandok** [comment]
Thanks a lot, that is a great middle way. I didn't know this was possible. And sorry for the dublicate, I really tried to find anything related to this topic.

**Comment by deckerst** [comment]
No worries ^^
