### ISSUE TITLE
True dark theme (black) / Amoled theme

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#93]
I suggest an implementation in which the user can choose for:

    Light theme
    Dark theme
    Follow system settings

And finally, dark theme should have an option for dark grey and pure black.

**Comment by deckerst** [comment]
<img src="https://user-images.githubusercontent.com/13898333/157140665-c45dfc1c-f0da-42e0-a025-ac8778cd6bb7.png" width="250"><img src="https://user-images.githubusercontent.com/13898333/157140671-a648398a-6f35-48d0-b7f4-9638f66c8ba9.png" width="250">

On these screenshots, I highlighted common cases using a dark background or a derivative:
1) page background
2) pop-up menu on page
3) dialog background
4) pop-up menu on dialog

Overlapping layers usually take different shades of grey, but what are the expectations for Amoled themes? 1 only, 1 and 3, or everything?

**Comment by Donkey-Doug** [comment]
Everything

**Comment by Donkey-Doug** [comment]
1: black
2: Dark grey (like the  first 2 examples)
3: Dark grey or black
4: Grey or dark grey (but lighter than 3)

**Comment by Donkey-Doug** [comment]
Don' forget light theme (https://github.com/deckerst/aves/issues/8).

Make sure you do not have to rewrite code for light theme.

**Comment by deckerst** [comment]
> Make sure you do not have to rewrite code for light theme.

Solicitude or condescension, I'll never know...
