### ISSUE TITLE
إقتراح اضافة امكانية انشاء مجلد  يضم عدة البومات في قسم الالبومات

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#930]
مرحبا، لدي اقتراح بسيط اتمنى إضافته لتطبيق Aves

**Is your feature request related to a problem? Please describe.**
في تبويب ألبومات، أشعر بالاحباط دائما عندما اضطر الى البحث عن ألبوم معين من فئة ما، ضمن عدة ألبومات متنوعة.

**Describe the solution you'd like**
الاقتراح هو ان تضيف خيار انشاء مجلد في قسم الألبومات بحيث نستطيع تحديد عدة ألبومات وإضافتها لمجلد معين، فعملية البحث عن الألبومات من نفس الفئة مرهقة وتأخذ وقتا طويلا. شكرا لك على عملك الدؤوب.

**Suggested steps to create a folder in the Albums section**
1- الذهاب الى قسم الألبومات.
2- التحديد على الالبومات اللتي من نفس الفئة (مثال: خرائط فلسطين، خرائط الجزائر، خرائط الدول العربية ...).
3- انشاء مجلد يحتوي على الألبومات المحددة (مثال: مجلد الخرائط).
4- شريطة ان لا يغير المجلد الجديد أماكن الصور في تخزين الهاتف.

**Additional context**

هذا الفيديو يوضح ما أحاول قوله (حجم الفيديو اكبر من 10 ميجابايت)

https://www.mediafire.com/file/0cey97x1ed1an9i/Screenrecorder-2024-02-28-06-21-40-538.mp4/file

**Comment by deckerst** [comment]
Duplicate:
- #268
