### ISSUE TITLE
Nomedia scan.

### ISSUE THREAD

**Issue by UniverseCodex01** [deckerst/aves#931]
**Is your feature request related to a problem? Please describe.**

I have a wallpaper folder with 100+ files and I don't want to see it on every app, I only want to see it when I will change my wallpaper.

**Describe the solution you'd like**

Add support to Included folders and on included directories allows to add folders with .nomedia file. This is useful and avoid hidden folder support that will not be added.

**Describe alternatives you've considered**

Hidden folder support but this feature will not be added as was mentioned on wiki.

**Additional context**

I still waiting for a change of mind on devs to add hidden folder support but for now .nomedia support it's a good alternative.
Please consider it, thanks for your hard work with Aves.

**Comment by deckerst** [comment]
".nomedia support" is the same thing as "hidden folder support".

**Comment by shockergit** [comment]
Please add all files api to see no media folders
