### ISSUE TITLE
Improving Management of Hidden Elements

### ISSUE THREAD

**Issue by dAtA-TRoN** [deckerst/aves#935]
**Description**
The current version of the app allows users to hide albums, tags or paths. These hidden elements can be viewed under

_-> Settings -> Privacy -> Hidden Items_

and can be restored by deleting entries by tapping on the "X" symbols. I suggest enhancing this functionality by displaying the hidden elements vertically rather than horizontally, and by adding toggle switches for each.

![1709642250932-01.jpeg](https://github.com/deckerst/aves/assets/71184627/019e9f14-32f1-4242-93d7-4c970c762224)

This would simplify the process of quickly hiding and revealing existing elements without the need to remember deleted entries or recreate them.

Additionally, adding an option to add a shortcut to access "Hidden Items" directly from the burger menu (sidebar) would streamline navigation, eliminating the need to navigate through multiple menus to toggle items on and off.

![1709643145409.png](https://github.com/deckerst/aves/assets/71184627/6539d15f-868d-45ff-a54a-789ad791f8e1)

**Suggested Solution**
1. Implementing toggle switches for hidden elements in the settings.

2. Adding an option in the settings to include a shortcut to "Hidden Items" in the burger menu.

**Additional Context**
Introducing toggle switches for hidden items and an optional direct shortcut in the burger menu would significantly enhance the user experience, enabling users to manage their private content more efficiently. This feature extension would make the app even more user-friendly and optimize the workflow for hiding and restoring elements.

**Comment by deckerst** [comment]
The point of hidden items is that they are irrelevant to your collection of images. They are not designed for repeatedly showing and hiding them. If you have some private stuff that you only want to occasionally see, maybe vaults are the right tool. Could you explain why you constantly need to show and hide items?

**Comment by dAtA-TRoN** [comment]
Sure, I would appreciate having an option to keep my Collection View (Timeline) clear of images from other apps, memes, or screenshots, while still retaining the flexibility to access hidden images when needed. The solution I proposed isn't necessarily the only one, but there might be alternative approaches, such as creating albums that can be excluded from the Timeline. What's crucial for me is flexibility. I don't want to hide images only to never see them again. Instead, I aim to tidy up my Timeline from irrelevant content while maintaining the ability to quickly access hidden images when necessary. For instance, I have a large collection of memes that I occasionally want to post when appropriate. However, I don't want them constantly visible. Thus, having the ability to easily toggle such content on and off would be ideal.

**Comment by dAtA-TRoN** [comment]
Wow, you actually implemented that? That's absolutely fantastic. Thank you so much. This makes the app even more useful than it already was. As a token of appreciation, I'll throw 5€ into the coffee fund for you 😊.

**Comment by deckerst** [comment]
Thanks! Just so you know, i added the switches as you suggested, but not the additional item in the drawer. Nice day to you too!

**Comment by dAtA-TRoN** [comment]
Ah, okay. Still, thank you very much for your great work.
