### ISSUE TITLE
Search by file size or file size overlay option

### ISSUE THREAD

**Issue by kmcbest** [deckerst/aves#936]
**Is your feature request related to a problem? Please describe.**
I've collected some digital drawings in PNG, but some of them took too much storage when a JPG conversion (even at 100% quality) can reduce drastically their size. Now I need to filter them out and use Aves' conversion feature to do this. I don't want to use other app to do the conversion because Aves preserves the tags.

**Describe the solution you'd like**
Either of these:
1. In the "search collection" feature (click the magnify glass button), there should be an option where  I can specify the file size range.
2. In "Settings-Thumbnail-Overlay" there should be an option "file size". When turn on, the file size (in KB or MB dynamically) will be displayed over thumbnails.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deckerst** [comment]
You may already be able to do what you want with one of these:
1) you can sort by size (Collection page menu > View > Sort),
2) you can see individual file sizes in the list layout (Collection page menu > View > Layout).

**Comment by kmcbest** [comment]
Indeed! It's OK then, thanks!
