### ISSUE TITLE
Aves returns home during app switching

### ISSUE THREAD

**Issue by ajsteele** [deckerst/aves#940]
**Describe the bug**
When I am moving back and forth between Aves and another app (eg sharing images to an app then returning to Aves), roughly 10% of the time it doesn’t return to where I was, but to the home screen (which for me is the albums screen but I realise is user-definable). This is frustrating because it loses my place in the gallery, which could be looking at photos from months ago etc! It’s as though Aves sometimes restarts when switched to.

**To Reproduce**
1. Open Aves
2. Go to somewhere specific, eg looking at an old photo
3. Share this photo to another app, go to that app and eg send as a message
4. Task-switch back to Aves with gesture navigation or task switcher button as appropriate
5. Aves displays home screen, losing your place

**Expected behavior**
Aves returns to where I was, eg viewing a particular image, specific location in gallery, etc.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: org.fdroid.fdroid
Aves version: 1.10.5-libre, build 11402
Flutter: stable 3.19.1
Android version: 14, API 34
Android build: 2024030900
Device: Google Pixel 6 Pro
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: not available
System locales: en_GB, de_DE
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/
Error reporting: false

I’m running GrapheneOS.

**Comment by deckerst** [comment]
Sounds like your OS is aggressively killing apps (or you push a device with tight memory). Have you tried with a regular Android?

**Comment by ajsteele** [comment]
Thanks for the reply! I’m afraid I don’t have a regular Android to try it on, this is my only phone. But I’ve not had this problem with any other apps being aggressively killed, and a Pixel 6 Pro has 12 GB of RAM so it seems fairly unlikely to be a memory issue?

Is there anything else I can do to troubleshoot this problem to confirm whether it’s Aves or something else? Thanks!

**Comment by deckerst** [comment]
I'd say it's a combination of the OS app management and Aves using too much memory. I've just released a new version of Aves that fixes a memory issue during cataloguing, but there are probably other memory leaks somewhere.

In any case, general memory management improvement is always something on my mind, and this ticket is not actionable as it is. I'll close it, but feel free to comment if you get additional insight (maybe it's when you deal with specific formats, or large files, etc.)
