### ISSUE TITLE
Save the Edited Date and Time in across other Gallery apps

### ISSUE THREAD

**Issue by dovah19** [deckerst/aves#945]
Is it possible to save the Edited Date and time to exif or metadata so that other Gallery apps can also recognize the same data.

Currently I am using a workaround where I edit the Date and time and then covert that image and tick "write metadata" which seems to save it. But this workaround does not work on videos.

Will be great if we could save all the metadata directly.

Thanks for the great app.

**Comment by deckerst** [comment]
I honestly don't understand what you are trying to achieve.

> Is it possible to save the Edited Date and time to exif or metadata so that other Gallery apps can also recognize the same data.

What is the "the Edited Date and time" you mention? Are you talking about the file property usually called the "file modified date"?

Date & time can be edited and it will be saved in the Exif, XMP or other metadata standard, depending on the media format. When editing the date & time, you can select `Copy from other date`, and then select `File modified date`, if that's what you meant.

As for metadata editing support, it depends on the format. Some are better supported than others. You can [check out the wiki for details](https://github.com/deckerst/aves/wiki/Support:-Metadata-editing).

**Comment by dovah19** [comment]
> Date & time can be edited and it will be saved in the Exif, XMP or other metadata standard, depending on the media format. When editing the date & time, you can select `Copy from other date`, and then select `File modified date`, if that's what you meant.
>

Yes this is what I meant. Can we have an option to forcefully write this edited date and time to disk and save it permanently. Bcoz when I edit this info, the other Gallery apps like fstop do not catch the new edited date and time.

Write metadata option is there is convert menu which works. So need similar option.

![Screenshot_20240315-193218_Aves](https://github.com/deckerst/aves/assets/142969757/97e9ce36-7467-4e53-816d-6a3eee7aba09)

**Comment by deckerst** [comment]
So:
- saving the current `file modified date` to the `Exif date`: already possible as mentioned above,
- modifying the `file modified date` to be the same as `Exif date`: not possible with Aves because [Aves is not a file manager](https://github.com/deckerst/aves/wiki/FAQ#is-aves-a-file-manager).

Converting creates a new file, which is a different thing from editing existing items.
