### ISSUE TITLE
Add a setting that disables double tap to zoom

### ISSUE THREAD

**Issue by Staubsaugerbeutel** [deckerst/aves#949]
**problem description**
The problem is that when you have "Tap on screen edges to show previous/next item" enabled, trying to quickly scroll through the gallery is not possible because tapping too quickly zooms into the image instead of showing the next item. 

**Describe the solution you'd like**
Add a setting in "Viewer" category that disables this, but ideally preserves the double tap + drag down/up gesture to zoom in and out.

**Comment by deckerst** [comment]
Duplicate:
- #622
