### ISSUE TITLE
Sort by date created.

### ISSUE THREAD

**Issue by MichaelDevon** [deckerst/aves#951]
**Is your feature request related to a problem? Please describe.**
I save videos where the date modified metadata is older than when i saved the video. 

**Describe the solution you'd like**
I would like to be able to sort by date created insted of modified.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by deckerst** [comment]
I don't intend to do it for the same reason as for the other file dates, so I lumped your request with that issue:
- #97
