### ISSUE TITLE
Only v7a arch showing up on IzzyOnDroid

### ISSUE THREAD

**Issue by 48-mq** [deckerst/aves#955]
The v8a and x64 variants of the aves app don't currently appear on the IzzyOnDroid repo, and can only be downloaded from here, on Github.

Searching through the issues and the discussions, I am not seeing any indication that this is intentional, so I am pointing it out in the hopes that it can be remedied.

**Comment by deckerst** [comment]
This is not a mistake. Izzy repo has a limitation on bundle size, and the multi-arch bundle would be beyond this limit. So only a single-arch bundle is offered, v7a being the most versatile. If you think Izzy repo could improve on this, i suggest you open an issue there. As far as Aves is concerned all the bundles are already available via the GitHub release page.

**Comment by 48-mq** [comment]
Thanks for the quick response @deckerst 

Per your suggestion, I am following up with Team Izzy to see what they suggest: https://gitlab.com/IzzyOnDroid/repo/-/issues/515
