### ISSUE TITLE
Support burst groups for Fairphone 5

### ISSUE THREAD

**Issue by Pfeil** [deckerst/aves#956]
**Is your feature request related to a problem? Please describe.**
The burst format from the Fairphone 5 (and possibly others) is not supported as it seems to be for samsung and Sony. Would be nice to display them grouped. 

**Describe the solution you'd like**
In addition to the Samsung and Sony format, support this one. 

**Describe alternatives you've considered**
Allow setting a custom format string to avoid specializations on too many devices/manufacturers. The format could even be guessed automatically, given a selection of images. 

**Additional context**
Some format examples:

IMG_20240215_140034_BURST020⁩
IMG_20240215_135609_BURST003⁩

No subfolders for bursts.

Generic:

IMG_yyyymmdd_hhMMss_BURSTnnn

A burst seems to consist of max. 20 images. But depending on other devices, I would not rely on that. The burst number is always three digits.

There do not seem to be burst related information in the metadata shown by Aves.

**Comment by deckerst** [comment]
Could you please attach here the system information you get via `About` > `Bug Report`?

**Comment by Pfeil** [comment]
Sorry I saw your message too late. In case you still need it:

```
Package: deckers.thibault.aves.libre
Installer: org.fdroid.fdroid
Aves version: 1.10.7-libre, build 11602
Flutter: stable 3.19.3
Android version: 13, API 33
Android build: FP5.TT46.A.144.20240205
Device: Fairphone FP5
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
System locales: de_DE
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/Music/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: false
```

**Comment by deckerst** [comment]
No worries. Thanks for the info, and what i committed *should* work for you. Want a test build to give it a try before the next release?

**Comment by Pfeil** [comment]
Thanks a lot :) Sure I can test it, provided some APK.

**Comment by deckerst** [comment]
https://drive.google.com/file/d/1_jg1XmxVmAHl3E6_zpl6TN-g4lFPIBBi/view?usp=sharing

**Comment by Pfeil** [comment]
It works as expected, thanks!

One minor issue: Analogous to https://github.com/deckerst/aves/issues/597, when I delete something but then restore the file within the three-second time frame, I need to enter the thumbnail view and go back into the detail/burst view to see the restored image. I assume this happens not only for the Fairphone mode, but I can not test it.

As for this issue, I would say it is solved. :)
