### ISSUE TITLE
[BUG] Currently playing video is paused when the device is re-oriented in hand

### ISSUE THREAD

**Issue by marcosilva85** [deckerst/aves#957]
**Describe the bug**
In Aves, the video that is currently being played pauses if we re-orient the device in hand (making the rotation landscape -> portrait or vice-versa).

Its a bit annoying because sometimes after playing a video I decide to adjust the device to the orientation the video was filmed in, but it causes the video to pause. I have to click play once more to continue playback.

**To Reproduce**
1. Enable auto-rotate on your Android device settings
2. In Aves, browse to a video
3. Click play
4. Re-orient your device to landscape or portrait in hand
5. Now click play again.

**Expected behavior**
Video should just continue to play normally.

**Comment by deckerst** [comment]
Please fill all the sections of the issue template.

**Comment by marcosilva85** [comment]
I don't have more to add, what can't be understood from the descriptions given?

**Comment by deckerst** [comment]
Where's the log and system info?

**Comment by marcosilva85** [comment]
I'd like to know where can I send this info privately to you @deckerst. In any case, have you been able to reproduce it with the steps I described?

**Comment by deckerst** [comment]
I couldn't reproduce the issue. I suspect that your particular environment makes the app go through some unusual [lifecycle steps](https://developer.android.com/guide/components/images/activity_lifecycle.png) (as if the app was going to the background for a split second) when you reorient the device. That's why I need details of your environment and the logs. You can always send them via [email](mailto:gallery.aves@gmail.com).

**Comment by marcosilva85** [comment]
I triggered the issue (easy for me) and exported the logs, system info by email, hope it helps @deckerst

**Comment by deckerst** [comment]
Reproduced on emulator with API 33 and API 34. Reorienting on these newer Android versions makes the app go inactive for a split second, as if it was losing focus and navigating to another app.

**Comment by deckerst** [comment]
I can't properly test video playback on emulators, so could you please confirm the fix with [this build](https://drive.google.com/file/d/1iPzGYbHMudT5_B1cbJcN3jxn7DNtxF7j/view?usp=sharing)? It will install as "Aves [Profile]", a separate app with its own settings distinct from your normal install.

**Comment by marcosilva85** [comment]
Tested, it fixed the issue. rotation did not tamper with the video playback.
Besides, I did an extra test and during video playback I switched from Aves to another app, and this pauses the video (expected behaviour).

Btw could the video playback bar be slimmed down, as it looks super bulky at the moment, [specially when using Aves in landscape mode](https://user-images.githubusercontent.com/10670060/229879524-b91dac15-6153-49ed-a0bb-7db37fb8af34.png)?
Maybe like the Google Photos one, which is just simply effective and out of the way.

**Comment by deckerst** [comment]
Thanks for confirming the fix.

As for the layout I agree with you that it is not optimal, but it is tricky:
1) I care about accessibility (i.e. every control should be easy to use for butter fingers, poor eyesight, etc.)
2) controls adapt to the content (e.g. motion photos have multiple pages including a video) and are customizable,
3) the layout should work in all cases, with all form factors, font scaling, etc.

But you know all that:
- #576
