### ISSUE TITLE
What is the best way to search for file extensions?

### ISSUE THREAD

**Issue by dAtA-TRoN** [deckerst/aves#959]
I've been experimenting a bit, but I'm struggling to find out how to search for file extensions in the app. I've found a workaround: I navigate to a file of the type I'm looking for, such as WebM, then I view the file information, where I can tap on the corresponding file extension to filter by it. However, I'm wondering if there's an official method for doing this. I'd appreciate it if someone could explain it to me.

**Comment by deckerst** [comment]
There's a way, but I'll be the first to admit that it's not obvious:
- go to Collection page (unfiltered),
- go to Stats,
- tap on the type in the donut chart legend.

**Comment by dAtA-TRoN** [comment]
Thank you for the very prompt response.
