### ISSUE TITLE
Different hide implementation

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#96]
Aves adds a tag "hide" which aves them does not show anymore. However, when using a file picker, for example, when sending media over whatsapp, the hidden files are all visible.

Since it is only possible to hide folders (and not individual images) perhaps it would be easier to add a .nomedia file to the folder or simple make the folder a hidden folder (by starting its name with a . ).

In #72 you mentioned:
> Rather, I'd leverage tagging for this purpose. Users could tag the files they want to hide with some XMP tag, and then hide that tag. It is a more flexible and scalable way to go about it. These XMP tags stay within the files, so you would benefit from them in other software that understands XMP.

I suggest adding the tag "hide" and adding a .nomedia file. This way you have universal tags and an android specific solution.

**Comment by deckerst** [comment]
> Aves adds a tag "hide" which aves them does not show anymore.

This is incorrect. There is no tag "hide", and Aves does not modify hidden files in any way. You probably misunderstood my comment about XMP tags and how you can leverage them to have more control over what you hide. Anyway, I understand this implementation detail does not change the nature of your issue, it's just for clarification.

> However, when using a file picker, for example, when sending media over whatsapp, the hidden files are all visible.

If you want to pick a file when sending media, social media apps (and the OS file picker itself) allow choosing an app to pick media (never used WhatsApp, but at least Telegram and KakaoTalk do), so you could choose Aves then, or you could send it from Aves in the first place.

> Since it is only possible to hide folders (and not individual images) perhaps it would be easier to add a .nomedia file to the folder or simple make the folder a hidden folder (by starting its name with a . ).

Not only folders, it works with any filter: locations, tags, mime types, animated/videos/etc.
As for ".nomedia", I already explained why this is not a sound solution [here](https://github.com/deckerst/aves/issues/13#issuecomment-776354973). More importantly, adding ".nomedia" would wreck valid use cases, such as hiding images from a music collection.

Also, Aves works with the collection established by the OS Media Store. It is not scanning non-media files. Adding .nomedia files would cut off those files from Aves itself, so it couldn't unhide them, browse them, etc. Allowing Aves to do so on non-media files would turn it into a file manager, no longer a gallery, and would require broader security permissions.

If you absolutely need a ".nomedia" file, use your file manager and create that file. Please do not open another issue about this here.

**Comment by drealph90** [comment]
At least for me the app is ignoring .nomedia files
 
I don't want to hide pictures that are just matching a certain filter, I want to hide pictures by directory, the way Fossify Gallery (I switched to your app because Fossify gallery was crashing repeatedly with my 60,000+ image library) does it (long press on picture, select exclude, choose the level of directory to exclude)
