### ISSUE TITLE
اقتراح تغيير نوع الارقام في ترجمة اللغة العربية (أرقام تاريخ الصورة)

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#960]
هذا اقتراح بسيط ان كنت لا تمانع  وكان لديك الوقت لتنفيذه فلا تتردد
**Describe the bug**
عند اختيار اللغة العربية كلغة للتطبيق، تظهر بعض الارقام في التطبيق بالشكل الغريب مثل ( تاريخ التقاط او تعديل الصور ) وهي ارقام يفهمها فقط عرب في اسيا، اما عرب افريقيا فلا يفهمونها.

**Expected behavior**
تغيير نوع الخط المعتمد في خيار (تاريخ التقاط الصور) ليصبح موافق للارقام العالمية، لان الجميع يفهمون الارقام العالمية.

**Screenshots**
![Screenshot_2024-03-26-23-15-02-714_deckers thibault aves-edit](https://github.com/deckerst/aves/assets/153401125/6dc9046f-2d21-4343-bfcb-e0a23fb292ae)
![Screenshot_2024-03-26-23-16-02-246_deckers thibault aves-edit](https://github.com/deckerst/aves/assets/153401125/a9ae99ee-9f74-4e3c-a3e2-6d85251bf814)

**Additional context**

https://github.com/deckerst/aves/assets/153401125/cb485b47-9f56-48e1-9d2c-805d3e2a9c7a

**Comment by deckerst** [comment]
Yes i understand what you mean and i know that ideally the digits depend on the specific country of the locale. For example Arabic for Jordan (ar_JO) uses Eastern Arabic numerals, but Arabic for Morocco (ar_MA) uses Western Arabic numerals.

At the moment, only one generic Arabic locale is defined in Aves, without specifying the country. I'll try and see if i can switch the numerals according to the system locale country, as I'd like to respect the locale specific numerals.

![Screenshot_٢٠٢٤٠٣٢٧_٠٠٣٠٠٧_Photos](https://github.com/deckerst/aves/assets/13898333/4e5a171e-d4f9-4f05-a86d-892659755b31)

![Screenshot_20240327_003130_Photos](https://github.com/deckerst/aves/assets/13898333/5e28c90e-5070-4bc6-a4fc-9827e799922d)

**Comment by mohamedzerougdz** [comment]
شكرا لك على مجهوداتك.

**Comment by deckerst** [comment]
Aves will use western arabic numerals for users who have in their system locales an Arabic locale of one of these countries:
- 'ar_DZ': // Algeria
- 'ar_EH': // Western Sahara
- 'ar_LY': // Libya
- 'ar_MA': // Morocco
- 'ar_MR': // Mauritania
- 'ar_TN': // Tunisia

For all others, it will use the native eastern arabic numerals.

**Comment by mohamedzerougdz** [comment]
نعم هاته هي الدول التي تستعمل الارقام العالمية، بوركت جهودك اخي.

**Comment by mohamedzerougdz** [comment]
احسنت اخي، التحديث 1.10.8 جاء بمميزات رائعة جدا. 

لكن فيما يخص شكل ارقام التاريخ في اللغة العربية فهي لم تتغير، مازالت نفس الاشكال الغريبة.

**Comment by deckerst** [comment]
Thanks for the feedback. Could you paste here your system info from About > Bug Report?

**Comment by mohamedzerougdz** [comment]
Package: deckers.thibault.aves
Installer: com.google.android.packageinstaller
Aves version: 1.10.8-play, build 117
Flutter: stable 3.19.5
Android version: 14, API 34
Android build: UKQ1.230917.001 release-keys
Device: Xiaomi 23021RAAEG
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: ar_EG
Storage volumes: /storage/emulated/0/, /storage/809D-1606/
Storage grants: 
Error reporting: true


[aves-logs-20240402_153142.txt](https://github.com/deckerst/aves/files/14838442/aves-logs-20240402_153142.txt)

**Comment by deckerst** [comment]
It depends on the country of your locale and Egypt is not one of the countries selected (see my message above).

For Egypt and Sudan, both western Arabic numerals and eastern Arabic numerals are in use, so i wasn't sure which one to pick.

**Comment by mohamedzerougdz** [comment]
هذا غريب، فأنا أسكن في الجزائر واضعها كمنطقة محلية للجهاز!!
 ![Screenshot_2024-04-02-16-01-06-083_com.android.settings.jpg](https://github.com/deckerst/aves/assets/153401125/5d64f073-7a06-4400-8169-2b85add16939)


كما اني حددت اللغة العربية بالارقام الغربية في اعدادات جهازي.!!

![Screenshot_2024-04-02-16-00-58-098_com.android.settings.jpg](https://github.com/deckerst/aves/assets/153401125/539b3281-b416-4413-b493-5f64e1ed7291)

**Comment by deckerst** [comment]
Interesting.

If you select "العربية" instead of:
العربية ( الأرقام الغربية )
, do you still see "ar_EG" as "System locales" in the system info displayed in Aves > About > Bug Report? (You may need to close and reopen Aves to refresh the info)

**Comment by mohamedzerougdz** [comment]
نعم عندما احدد خيار العربية ، لا ازال أرى ar_EG.

اعتقد انهم لم يتعبو انفسهم بإنشاء خيار اللغة العربية للمغرب العربي. كل ما قامو به هو اضافة خيار منفصل لتغيير شكل الارقام، لكنهم فشلوا في تغيير كل شيء.

**Comment by deckerst** [comment]
I double-checked and Google Photos also uses eastern Arabic numerals for Egypt, so I'll keep it that way.

As for your reported locale not matching your selected locale, i couldn't find any additional official settings related to this. I guess Xiaomi messed up.

I'll see if i can provide a toggle to force western numerals (i.e. disable native numerals) in the format settings of Aves.

**Comment by mohamedzerougdz** [comment]
شكرا لك

**Comment by deckerst** [comment]
> I'll see if i can provide a toggle to force western numerals (i.e. disable native numerals) in the format settings of Aves.

Done. It will be in the next release.

**Comment by mohamedzerougdz** [comment]
شكرا لك على كل المجهودات التي تبذلها.
