### ISSUE TITLE
Better tag input and logical operations with tags

### ISSUE THREAD

**Issue by kmcbest** [deckerst/aves#961]
**Is your feature request related to a problem? Please describe.**
1. Currently when I want to filter out images with two or more tags, e.g., "dogs" AND "white", I have to hit the search bar, click "dogs", and hit the search bar again, then click "white". The problem is that the filter is applied instantly on any tag selection.
2. Currently if I enter two or more tags, the app will filter image with all of them, this AND logic. What if I want to filter out dogs that are not white? Dogs or cats? There's no NOT, OR operations for me to do that.

**Describe the solution you'd like**
1. It is common at least for me to enter two or more tags and filter images. I wish I can click them one after another before I hit a "OK" button to apply the filter.
2. I'd like to have logical operations like OR, NOT.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by deckerst** [comment]
You can do NOT by long pressing a filter (tag or otherwise) and select "filter out".

I don't intend to do your other suggestions, because accommodating the UX for it would necessarily make it more complex for the most common cases.
