### ISSUE TITLE
Manual Media Scan Button

### ISSUE THREAD

**Issue by vodknuckles** [deckerst/aves#964]
If I have a folder of media on my phone that contains a .nomedia file (which excludes the folder from being picked up by gallery apps, etc.) and I remove that file, I'd like to have the option to tell Aves to rescan my media folders and show me the folder that isn't hidden anymore.

A simple button, perhaps in the main 3-dot menu that would start a full scan of the system lookibg for media.

As an alternative, I usually force-close the app, clear the cache, and restart my phone. That usually gets it to see the "new" folder, but it can usually take a minute or so.

**Additional context**

**Comment by deckerst** [comment]
I understand why you would need such a functionality if you do so often, but I wonder why you would need to delete `.nomedia` files on a regular basis. Any reason?

**Comment by vodknuckles** [comment]
> I understand why you would need such a functionality if you do so often, but I wonder why you would need to delete `.nomedia` files on a regular basis. Any reason?

It's not something I do very regularly, just an example of a time where a manual rescan would be handy.

**Comment by deckerst** [comment]
Aves reflects the state of the system Media Store, and the Media Store will be momentarily broken if apps/users misuse it. I think providing a band-aid for this is out of scope for Aves.
