### ISSUE TITLE
Double tap to zoom doesn't work when image matches screen resolution

### ISSUE THREAD

**Issue by Kiisu-Master** [deckerst/aves#966]
**Description**
Double tap to zoom doesn't work when image resolution matches screen resolution.

**Reproducing**
1. Take a screenshot to get a photo with matching resolution with screen.
2. Open it in Aves
3. Double tap

**Expected behavior**
As the first zoom step is filling the screen size, which already happened because of the resolution match, it should zoom to the second step.

**Screenshots**
(I can add a recording if necessary)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.google.android.packageinstaller
Aves version: 1.10.8-izzy, build 11701
Flutter: stable 3.19.5
Android version: 11, API 30
Android build: RP1A.200720.011
Device: Xiaomi M2006C3MNG
Support: dynamic colors=false, geocoder=true, HDR=false
Mobile services: ready
System locales: en_GB
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/Download/Images/
Error reporting: false

**Comment by deckerst** [comment]
True.

For reference, the normal zoom cycle via double-tap is:
1) fill screen
2) 100%
3) fit screen

It's also possible for all 3 zoom levels to be the same. Typical for screenshots.

**Comment by deckerst** [comment]
Actually, there's already some logic to skip the next step if the zoom levels are the same.

Could you please give me your device resolution and the resolution of an image with which you have the issue? A screen recording could help too.
