### ISSUE TITLE
set-Gps to one or more photos: Pick Gps from existing photo with gps-info

### ISSUE THREAD

**Issue by k3b** [deckerst/aves#967]
**Is your feature request related to a problem? Please describe.**
I would like to put geo-infos(gps-latitude/longitude) to one or more selected photos

**Describe the solution you'd like**
Some photos already have geo-infos so it would be cool, to say that the selected photos should get the same geo-infos as an other photo.

**Suggested Workflow**

* Menu "Select"
* Select one or more photos, that should receive the same geo-info.
* Menu: Edit/EditLocation
* Select: (new feature): Copy locaton from other photo 
* A New Photo Search Dialog appears that only shows those Photos, that have a geo-info
* select a reference photo and press ok
* ==> The selected photos get the geo-infos

For reference see https://github.com/k3b/APhotoManager/wiki/Howto-geotag-multible-photos

**Comment by deckerst** [comment]
You can already do so. I'm surprised you haven't seen it as it's already like the workflow you suggested.

![Screenshot_20240406_184126_Aves](https://github.com/deckerst/aves/assets/13898333/f6fa647a-2141-481d-9e6e-6c9daf02a123)

**Comment by k3b** [comment]
Oh sorry. I saw this "feature" but was not aware, that i get an image chooser when i click on the "-->"-photo.

**Comment by deckerst** [comment]
True, i missed that.
