### ISSUE TITLE
Some svg images are offset

### ISSUE THREAD

**Issue by wanzh5** [deckerst/aves#969]
**Describe the bug**
Some specific svg images will offset and can't be displayed completely.

**To Reproduce**
1. Open the image. (You can download this image below.)
2. It offset.

**Expected behavior**
Display like this. (This is a png image.)
![Rail_map_of_PRC_zh_hans svg](https://github.com/deckerst/aves/assets/106989902/c2fad88f-3594-484f-9bed-e8cf5f347e44)

**Screenshots**

https://github.com/deckerst/aves/assets/106989902/4fe1a13c-b92f-4742-9da7-9386e2440648

**Additional context**
The picture that causes the bug.
![Rail_map_of_PRC_zh_hans](https://github.com/deckerst/aves/assets/106989902/a5c2aa42-3f4a-4967-96d7-414c9da4cf5f)

**Comment by deckerst** [comment]
Thanks for the sample. I'll take a closer look later but it seems it's because of the document metadata giving it an offset: 
```
View Box⁩ ⁨-21.622 147.891 ...
```
