### ISSUE TITLE
Not recognizing whatsapp folder inside of android/media/com.whatsapp

### ISSUE THREAD

**Issue by jordanss1** [deckerst/aves#974]
**Is your feature request related to a problem? Please describe.**
None of my whatsapp pictures are being recognized by the app. Think this was best to put in the features as don't think it's a bug.

**Describe the solution you'd like**
The ability to select folders/subfolders to be "watched" by the app as it seems that certain folders like the one mentioned in the title cannot be watched.

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/wiki/FAQ#why-isnt-my-album-in-the-albums-page
