### ISSUE TITLE
iPhone photos display incorrectly in the view pane

### ISSUE THREAD

**Issue by qumuq-til** [deckerst/aves#976]
**Describe the bug**
I've recently imported a bunch of iPhone 12 photos into my gallery and use Aves to browse through them. While the thumbnails appear fine, in the view pane photos shot in a portrait (vertical) orientation would have a huge black border around them and zooming in and panning would reveal that Aves treats them as landscape (horizontal) oriented photos and seemingly relies on resolution data instead of honoring the rotation attribute in EXIF.

**To Reproduce**
Import the attached photo and see for yourself.

**Expected behavior**
Aves should honor the rotation attribute and otherwise just work correctly with vertical photos shot on an iPhone.

**Photo sample**
![IMG_8475](https://github.com/deckerst/aves/assets/43707841/3b4d6ab7-be70-4ee5-ab45-ac16c36707ac)

**Comment by deckerst** [comment]
Thanks for the report and sample.

It's more subtle than honoring metadata orientation (which Aves already does). Your sample is actually a JPEG containing multiple images (MPF standard). One of these pictures seems to be a depth map. And it seems the primary image is misinterpreted (size and orientation).

Out of curiosity, did the iPhone 12 leverage the fact that the image contains a depth map? For example to let the user change the focal plane after the fact, or some 3D effect?

**Comment by deckerst** [comment]
Oops, the second embedded image is not a depth map, it's an HDR gain map. My bad.

**Comment by qumuq-til** [comment]
I had no idea that iPhone did that, nor did I know that MPF standard existed. I did lightly edit photos from time to time and it's reasonable to assume that the HDR map is used during editing somehow, but I can't really know. Of course the iPhone wouldn't show anything but the single primary image. As far as I can tell there is no option in the iPhone camera application to turn that embedded HDR map off and the only option present to the user is a 3-photo HDR stacking that seems to alter the original image, and the map is embedded regardless.

**Comment by deckerst** [comment]
Fixed in 2 ways:
1) MPF images will be rotated according to the container Exif rotation,
2) Apple variant of HDR images will be identified as HDR.

With 1), display in the viewer will be as expected, but you will also see the gain map as a secondary image.

To benefit from 2), you'll need to select your images and do `rescan` on them. When they are identified as HDR, the gain map secondary image is automatically hidden from the viewer (but still accessible from the `Info` page, for the curious).

**Comment by qumuq-til** [comment]
Thibault, while we're at it, could you take a look at another loaded iPhone 12 photo I've just found with multiple layers in it to see if Aves could make use of all that additional information.

![9806434709a051dbb17d447924299109cb8599c9](https://github.com/deckerst/aves/assets/43707841/2e6e4f69-405c-45fb-88b5-0b8801546d06)

**Comment by deckerst** [comment]
Indeed, the image has more layers than this pancake.
![Screenshot_20240416_225939_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/c346d732-0bd7-45a9-8822-5a33e84622c4)
![Screenshot_20240416_230003_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/f0744086-5f1e-45c1-aee2-5d1fea2e3fdd)
![Screenshot_20240416_230032_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/eca8df63-3c8f-4b0a-80e0-a25d0d089c15)
![Screenshot_20240416_230055_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/1a038326-46e8-43fb-bf5b-6d4bca5eb2dd)
![Screenshot_20240416_230149_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/27ca84a1-86c0-429a-b738-b307bb1e8f73)
![Screenshot_20240416_230227_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/562461f8-cd4b-4231-aebb-ed80e233b841)
![Screenshot_20240416_230248_Aves  Debug](https://github.com/deckerst/aves/assets/13898333/10b707e9-35c9-4453-b0c4-df8760e36b39)

Mostly Apple specific niche layers: teeth, skin, hair, glasses and portrait depth.
Some more interesting layers:
- an HDR gain map that *could* be used (see #838), even though the metadata is not following documented standards.
- a depth map that *could* be used (see #443), but I'm not even sure it's usable if there's only one main image with the focus already applied, contrary to the Gcam's "portrait mode" with editable depth of field.

In any case, thanks for the sample, but I don't intend to provide additional support for these proprietary layers.

**Comment by qumuq-til** [comment]
I agree with that assessment and conclusion, just maybe you could change Aves so that it hides those useless iPhone layers by default. Currently those are visible and browseable.
As for metadata not following standards, it could be because I cropped the image to hide the face before posting the image here, but that's how all that hair got into it in the first place. Let me know if you need an uncropped sample sent by email.

**Comment by deckerst** [comment]
> I agree with that assessment and conclusion, just maybe you could change Aves so that it hides those useless iPhone layers by default. Currently those are visible and browseable.

For HDR images, I do hide secondary images, so they will be hidden for the 2 samples you provided, at least. But I don't want to hide these additional images in general, because I can't know in advance what they are and how they are used. It could be used as a regular container like TIFF or HEIF images with multiple pages. One principle of Aves is to expose things by default, unless the format is known and understood.

> As for metadata not following standards, it could be because I cropped the image to hide the face before posting the image here, but that's how all that hair got into it in the first place. Let me know if you need an uncropped sample sent by email.

No need. It's not following standards in the sense that it uses custom namespaces and conventions designed and used by Apple only. It's opaque and not meant for used elsewhere.
