### ISSUE TITLE
Scan crash / Video / App crashes right after start

### ISSUE THREAD

**Issue by BieneMaja2** [deckerst/aves#977]
**Describe the bug**
Whenever starting the app it crashes instantly (or after a few seconds).
This behaviour is shown on both normal start and secure start. Also it does not matter if the phone is rebooted or any other way the app was shut down before.

**To Reproduce**
1. Start the app.
2. Do nothing or scroll the list (does not matter).
3. On instant, app crashes (without crash report)

**Expected behavior**
A stable working app.

**Screenshots**
n/a

[aves-logs-20240415_143010.txt](https://github.com/deckerst/aves/files/14979241/aves-logs-20240415_143010.txt)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.8-play, build 117
Flutter: stable 3.19.5
Android version: 13, API 33
Android build: FP5.TT46.A.144.20240205
Device: Fairphone FP5
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: de_DE
Storage volumes: /storage/emulated/0/, /storage/FDF6-9790/
Storage grants: 
Error reporting: true

**Additional context**
Last update did not fix the bug yet.

**Comment by deckerst** [comment]
Thanks for the report. 

> Do nothing or scroll the list

Do you mean you see Aves screen for a little bit? From your report I thought it crashed instantly, so you wouldn't see any frame from Aves.

Have you ever seen Aves work correctly with a previous version of the app on your device?

Do you have a large collection (e.g. more than 50k) of images and videos on your device?

**Comment by BieneMaja2** [comment]
Sorry for this confusing expression.I do see the Aves screen and also my list of media for a few seconds.Yes, I do have a large collection of images and videos on my device (I am not able to count all the content in the folders from apps such as WhatsApp and co.)Aves worked very well some time ago without any issues.But sadly I cannot tell you the last version of it that worked.Am 15.04.24, 15:06 schrieb Thibault Deckers ***@***.***>:

   
  Thanks for the report. 
   
   Do nothing or scroll the list 
   
  Do you mean you see Aves screen for a little bit? From your report I thought it crashed instantly, so you wouldn't see any frame from Aves. 
  Have you ever seen Aves work correctly with a previous version of the app on your device? 
  Do you have a large collection (e.g. more than 50k) of images and videos on your device?

**Comment by BieneMaja2** [comment]
Correction: My collection is about 20k images and videos.Am 15.04.24, 15:26 schrieb Biene Maja ***@***.***>:

  
   Sorry for this confusing expression.
   
   I do see the Aves screen and also my list of media for a few seconds.
   
   Yes, I do have a large collection of images and videos on my device (I am not able to count all the content in the folders from apps such as WhatsApp and co.)
   
   Aves worked very well some time ago without any issues.
   But sadly I cannot tell you the last version of it that worked.
  
  
   Am 15.04.24, 15:06 schrieb Thibault Deckers ***@***.***>:
    
     
    Thanks for the report. 
     
     Do nothing or scroll the list 
     
    Do you mean you see Aves screen for a little bit? From your report I thought it crashed instantly, so you wouldn't see any frame from Aves. 
    Have you ever seen Aves work correctly with a previous version of the app on your device? 
    Do you have a large collection (e.g. more than 50k) of images and videos on your device?

**Comment by deckerst** [comment]
20k might take a few seconds to launch but it's fine. I've asked because beyond 100k it could be a crash from the DB.

I don't see any related crash report in Crashlytics so it will be tricky to debug :/

1) If you know your way around development tools, could you access your device and get logs from `adb logcat` showing the crash details?

2) Otherwise, __if you have no vault and have nothing important in the recycle bin__, you could clear the app data (not only the cache), launch the app and see whether it solves the issue. That would narrow down the possible reasons for the crash in the first place.

3) You could also install [Aves Libre](https://github.com/deckerst/aves/releases/download/v1.10.9/app-libre-arm64-v8a-release.apk) (another flavour of Aves, but very similar), and see whether you encounter the issue.

**Comment by deckerst** [comment]
I could be wrong, but it's unlikely because of the settings, but more probably because the background media scan reaches a file that make it crash. After you clean the app data and start from scratch, the media scan will take time to reach that file. But with subsequent launches, the media scan will crash sooner.

You can do the test by 1) cleaning the data, 2) keep the original settings, 3) let the app scan all your media. If you haven't done so already, you can give Aves notification permission so you can see the media scan progress in the notification bar.

**Comment by BieneMaja2** [comment]
Well, okay.Now I know that the crash happens during the media scan progress at 280/1877How can I deal with that?Am 16.04.24, 18:42 schrieb Thibault Deckers ***@***.***>:

   
  I could be wrong, but it's unlikely because of the settings, but more probably because the background media scan reaches a file that make it crash. After you clean the app data and start from scratch, the media scan will take time to reach that file. But with subsequent launches, the media scan will crash sooner. 
  You can do the test by 1) cleaning the data, 2) keep the original settings, 3) let the app scan all your media. If you haven't done so already, you can give Aves notification permission so you can see the media scan progress in the notification bar.

**Comment by deckerst** [comment]
Please do the following:
1) install this [test build (20251026_2000)](https://drive.google.com/file/d/1gHxHeS49W9BpJZ-epouPWbgjovXBqWAs/view?usp=sharing). It will install as `Aves [Profile]`
2) launch `Aves [Profile]` and let it do the scan until it crashes (or gets stuck)
3) launch the `debug` shortcut of the `Aves [Profile]` app
4) it will prompt you to save a log file. Save it somewhere and leave the app.
5) open the log file. It should contain dates and paths of media files.
6) pick the last line and find the media file at that path
7) send me the media file. You can share it with me via [email](mailto:gallery.aves@gmail.com) if you don't feel comfortable sharing it in this issue thread.

**Comment by BieneMaja2** [comment]
Dear inventor,thank you so much!As you said, the debug function helped to find the corrupted media file (it truely was an mp4 file).Unfortunately, I erased the file before remembering to send it to you.But I noticed it as a file (short Instagram clip) without any meta data that might got lost during the download.So far, thank you so much again. 🤗

 
  
  
 
 Am 17.04.24, 20:03 schrieb Thibault Deckers ***@***.***>:

   
  Please do the following: 
   
   install this test build. It will install as Aves [Profile] 
   launch Aves [Profile] and let it do the scan until it crashes 
   launch the debug shortcut of the Aves [Profile] app 
   it will prompt you to save a log file. Save it somewhere and leave the app. 
   open the log file. It should contain dates and paths of media files. 
   pick the last line and find the media file at that path (most likely an MP4) 
   send me the media file. You can share it with me via email if you don't feel comfortable sharing it in this issue thread.

**Comment by deckerst** [comment]
It would really help me solve this issue if i got my hands on such a file. So please send it to me if you find it again, or if you stumble upon a similar file that makes the app crash.
