### ISSUE TITLE
Ability to modify image data after shuffling the images (i.e. with a slideshow)

### ISSUE THREAD

**Issue by Frc-dev** [deckerst/aves#978]
**Is your feature request related to a problem? Please describe.**
Currently when using the slideshow button it will show a context menu where there is an option to access the exact position of the image, but that button sends you to the image in the album without search filters.

**Describe the solution you'd like**
Add a context menu inside the slideshow where you can edit tags and ratings
or
After going from inside a slideshow into a image, show the entire album in the order shuffled by the slideshow (I suspect this is more complicated but I do not know how this app works beyond the front-end)

**Comment by deckerst** [comment]
Closing in favour of #1090.
