### ISSUE TITLE
Tag a WebP?

### ISSUE THREAD

**Issue by PerspexSphinx** [deckerst/aves#979]
How do I Tag a WebP?
Also can one rename Tags?

**Comment by deckerst** [comment]
> How do I Tag a WebP?

You can't with Aves at the moment. See related support table:
https://github.com/deckerst/aves/wiki/Support:-Metadata-editing

> Also can one rename Tags?

Yes, but the tags are within the files so all the files with that tag will need to be modified:
https://github.com/deckerst/aves/wiki/FAQ#how-do-i-rename-a-tag
