### ISSUE TITLE
مقترح انشاء تصنيفات جديدة في قائمة الألبومات

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#982]
**Is your feature request related to a problem? Please describe.**
أرجو  اضافة انشاء تصنيفات جديدة للألبومات، سيساعد كثيرا في تنظيم المعرض.

**Describe the solution you'd like**
1- تحديد الأبومات المستهدفة
2- الضغط عى رمز إنشاء تصنيف جديد
3- تسمية التصنيف الجديد
4- التنيجة النهائية ظهور التصنيف الجديد

ملاحظة:
تم تعديل لقطات الشاشة بواسطة معدل الصور

**Additional context**

![1](https://github.com/deckerst/aves/assets/153401125/92bc0906-7879-4cef-bf72-ad32597a5931)

///////////////////////////////////////////////////////////

![2](https://github.com/deckerst/aves/assets/153401125/83f08f3b-41f8-47ac-acb6-45c6dfe0398c)

///////////////////////////////////////////////////////////

![3](https://github.com/deckerst/aves/assets/153401125/593b8c14-ee26-4eb4-b1fe-74ff2c4b8e50)

**Comment by deckerst** [comment]
Duplicate:
- #538

**Comment by mohamedzerougdz** [comment]
أعتقد أنه اقتراح جيد للنظر فيه في المستقبل.

**Comment by deckerst** [comment]
Feel free to upvote/subscribe to #538 if you think it's useful.
