### ISSUE TITLE
Large AVIF images are not handled

### ISSUE THREAD

**Issue by kmcbest** [deckerst/aves#986]
**Describe the bug**
I've converted some images to AVIF format (using [AVIF Image Viewer](https://play.google.com/store/apps/details?id=ebusky.avif.image.viewer.converter.pdf)). One large image of 3496x4960 is not handled in Aves. While it can be displayed by the aforementioned app and on Windows (using win11's photo view or IrfanView), it cannot be read in Aves.

**To Reproduce**
1. Download this image to your phone (hub doesn't support avif so I zipped it) :
[sskpwxmlnxtb.zip](https://github.com/deckerst/aves/files/15018735/sskpwxmlnxtb.zip)
2. Try viewing it in Aves
3. See a blank image and a placeholder "AVIF" instead of a thumbnail:

**Expected behavior**
Image handled like other ones

**Screenshots**
![Screenshot_2024-04-18-09-33-08-908_deckers thibau](https://github.com/deckerst/aves/assets/689023/615c8571-dc7b-4449-ace7-1788a670e8a6)

**System information and logs:**

Package: deckers.thibault.aves
Installer: com.miui.packageinstaller
Aves version: 1.10.9-play, build 118
Flutter: stable 3.19.5
Android version: 14, API 34
Android build: UP1A.230905.011
Device: Xiaomi 23078RKD5C
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
System locales: zh_CN
Storage volumes: /storage/emulated/0/
Storage grants: 
/storage/emulated/0/Pictures/, ....
Error reporting: true
**Additional context**

**Comment by deckerst** [comment]
Aves uses the AVIF codec provided by the device. If your file uses exotic features or is somehow invalid and can't be decoded by the device codec, there's nothing Aves can do about it.

You can check this by opening the file with the default gallery on your device, which would also use the device codec. 

I don't intend to ship custom codecs for AVIF.
