### ISSUE TITLE
External Storage Support

### ISSUE THREAD

**Issue by Wave6677** [deckerst/aves#988]
**Is your feature request related to a problem? Please describe.**
I have noticed almost no Gallery apps actually support external storage such as Flash Drives, USB SD Card adapters, External SSDs or any number of other external storage (Excluding phones that are still blessed enough to have an included SD card reader)
I've noticed there is a bit of a hacky way around this with Fossify gallery where you can individually import folders from external storage, however it gets tedious if you're only looking for one photo you took in 2016 and you have to pick and guess which directory the photo could be in.

**Describe the solution you'd like**
I would like Aves to be able to detect when an external storage device is connected and prompt the user with something like "An external device has been connected, would you like to display it's contents on the timeline?"

**Describe alternatives you've considered**
The only alternative there seems to be is file manager apps. They are able to easily access external storage and I can find what I need that way, but Aves UI is so much more user friendly than having to dig around a directory tree, especially with the help of sorting with tags.

**Additional context**

**Comment by deckerst** [comment]
Duplicate:
- #366
