### ISSUE TITLE
Reverse image search

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#99]
I use reverse image search frequently to find higher resolution images of images on my device. Perhaps Aves could integrate a reverse image search functionality? That is, an option "image search" in the 3 dots menu that uploads the image to the reverse image search engine.

It should be easy to code, but I would understand if you decide not to implement it. It is not really the main functionality of a gallery.

**Comment by deckerst** [comment]
It seems to me that the feature amounts to sharing to a specific address. It's hard to believe there's no existing app that allows that kind of bridge. I imagine here an app that can receive any shared item and use it as a parameter for a call to a configurable URL/API.

Anyway, I don't think it should be included in Aves. I wouldn't want to tie this feature to a particular online service.

Out of curiosity, do you use the one by [Google](https://www.google.com/imghp?sbi=1) or another API?

**Comment by Donkey-Doug** [comment]
Google, because it seems to be the only reverse image search engine that actually finds the image.
