### ISSUE TITLE
MD5 Checksum Option in Rename Menu

### ISSUE THREAD

**Issue by vodknuckles** [deckerst/aves#990]
Adding the ability to rename a photo with its checksum (MD5, SHA-256, etc.), perhaps sticking those options in the _More_ drop-down menu section in the _Rename_ menu.

Checksums can provide a file with a unique filename that isn't dependent on the date, time, or an ascending numeral counter.

**Comment by vodknuckles** [comment]
> It's technically possible, but how would it help you? Do you intend to later extract the md5 from the name and compare it with the md5 from the actual file? Or compare it with another backup of your file?

I care less about the mathematical / verification aspects of this, and more about how it is a de-facto duplicate checker. If I download the same photo later on, I'll know I have a duplicate as the filenames will be identical. Over the years, I've found that this is the best way to store tens / hundreds of thousands of photos locally.

**Comment by deckerst** [comment]
I see. Then, wouldn't it be more straightforward for Aves to find duplicates? It could do the comparison, sparing you the renaming.

**Comment by vodknuckles** [comment]
> I see. Then, wouldn't it be more straightforward for Aves to find duplicates? It could do the comparison, sparing you the renaming.

Finding duplicates isn't the primary benefit of using a checksum to name files, although it is a handy byproduct. Having a unique name for a file that isn't based on date / time or arbitrary naming schemes is what I'm most interested in. A duplicate checker feature would be good, but not exactly what I'm looking for.

**Comment by deckerst** [comment]
Done. Default to "md5", but also allows "sha1" and "sha256".
<img width="250" src="https://github.com/deckerst/aves/assets/13898333/835c5503-d69d-4b12-b492-9ba3bd2607d6"/>
