### ISSUE TITLE
Grey photo viewer after pressing "Always" in GCam

### ISSUE THREAD

**Issue by GaucovyAero** [deckerst/aves#997]
**Describe the bug**
Using "Just once" works fine in LMC8.4 R18, but pressing "Always" makes the photo preview grey.

**To Reproduce**
1. Open LMC8.4
2. Click on the photo preview
3. Press Aves and "Always"
4. Open the photo preview again and it will be grey

**Expected behavior**
The preview should work just like it does when pressing "Just once".

**Screenshots**

https://github.com/deckerst/aves/assets/85581164/2f1b4112-3e68-40c8-823f-6d2c3b7b0bab

**System information and logs:**
[aves-logs-20240429_212914.txt](https://github.com/deckerst/aves/files/15153968/aves-logs-20240429_212914.txt)

Package: deckers.thibault.aves.libre
Installer: org.fdroid.fdroid
Aves version: 1.10.9-libre, build 11802
Flutter: stable 3.19.5
Android version: 13, API 33
Android build: lineage_alioth-userdebug 13 TQ3A.230901.001 14751f6718
Device: Xiaomi M2012K11AG
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
System locales: en_US, sk_SK
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/emulated/0/screenrecorder/, /storage/emulated/0/Android/media/
Error reporting: false

**Additional context**
LineageOS 20, MicroG
issue related to #781

**Comment by deckerst** [comment]
I tried the APK from here: https://www.celsoazevedo.com/files/android/google-camera/dev-hasli/f/dl14/1/
And it works fine (on a Samsung S10e with Android 12 API 31).

If you don't have the issue with another gallery app, and you know your way around logcat, could you please attach here the logcat output you get when have the grey screen? I'm not even sure it reaches Aves in that case. It may be a failure of Lineage, as the once/always link option is under the responsibility of the OS.

**Comment by GaucovyAero** [comment]
both https://github.com/IacobIonut01/Gallery and https://github.com/FossifyOrg/Gallery work as expected with GCam.

here is the logcat:

[logcat.txt](https://github.com/deckerst/aves/files/15161192/logcat.txt)

not sure if this is of any info but it seems to me that Aves is somehow being spammed on top of itself, the photo preview is flickers greyer and greyer until the screen is completely grey, the down gesture to close the photo preview works as expected, so i assume Aves is functioning fine behind all of this

**Comment by deckerst** [comment]
Do you have the same issue when selecting `Aves` to always open images, when launching from a different app, say the `Files` app, instead of `GCam`? It might not strictly be the same intent (REVIEW for `GCam`, VIEW for `Files`) but it could help narrow down what's wrong.

**Comment by GaucovyAero** [comment]
no, the issue does not occur when opening "Always" in Aves in Files

https://github.com/deckerst/aves/assets/85581164/0bf044a4-27a3-4782-a78c-b8cd6a7b08c8

**Comment by GaucovyAero** [comment]
oops, the recording is absolutely unusable, lemme send a fix

**Comment by GaucovyAero** [comment]
Not sure if this helps, but it sometimes works if i try really fast to switch the photo

https://github.com/deckerst/aves/assets/85581164/82f0ea0a-1e28-409f-991f-9f6d9a178fea

**Comment by deckerst** [comment]
I wanted to try again on my new phone (an Xperia 5 V) but all the GCam versions I tried (Hasli's 8.4, some 8.8 and 8.9) crash on that device :/

**Comment by GaucovyAero** [comment]
yeah thats kinda unfortunate, but very much expected (i suggest borrowing a phone that has an actual config for haslis 8.4, it might be reproducable, perhaps on aosp-ish devices like motorolas?)

https://www.celsoazevedo.com/files/android/google-camera/f/configs-hasli-02/

**Comment by GaucovyAero** [comment]
cannot reproduce anymore after switching from LineageOS to crDroid (currently on 10.7), works as expected on 1.11.10 release 👍
